### ISSUE TITLE
"Unpanic"?

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#1005]
An option in the Engine menu for "Unpanic" (or a ctrl-click on Panic) that reactivates the plugins that were deactivated on the last click of the Panic button/menu item.

**Comment by moonshaadow** [comment]
Hum... If I'm not wrong, there is no midi note off or no "transport stop" sent when click on Panic. If you have sequenced instruments, they are still processing when you reactivate them, and maybe it's safer to reactivate plugins one by one. Or have a real Panic feature, stopping the plugins processing, so we could reactivate all plugins without risk.

**Comment by falkTX** [comment]
plugins receive all-note-off events when they are reactivated.

stopping the transport is a good idea.

I disagree with the need of such a button though.
if something goes wrong that you need to press panic, I cant see why reactivating everything would be a good idea.

**Comment by mxmilkb** [comment]
Having to reactivate 20+ plugins manually every time I used Kill was majorly frustrating, that's my original problem.

**Comment by falkTX** [comment]
You already have that though. Use menu plugins->macros->enable.
This will enable all plugins. The panic button is a shortcut to the disable action on that submenu.

**Comment by falkTX** [comment]
right-clicking on the rack (an empty area) will also give you the option to enable all plugins

**Comment by mxmilkb** [comment]
My original suggestion was for something that wasn't all or nothing, though thanks, reenabling all will work for my need.

**Comment by falkTX** [comment]
closing this ticket since the "enable all plugins" works for this.
I like to have many options in carla, but there is a limit :P

**Comment by mxmilkb** [comment]
If enable is meant to function as bypass, this means project state will be lost if ever the Panic button is used, better to quickly hit save and quit Carla if one gets a feedback loop.

**Comment by falkTX** [comment]
I dont get your message...
carla saves the entire plugin state no matter if plugins are active, enabled or whatever. so you wont lose anything unless you kill carla

**Comment by mxmilkb** [comment]
Imagine a project with some plugins in a bypassed state (i.e. disabled, given the recent LSP discussion) and some plugins enabled, a set of effects for an input. Various changes get made to the reenabling plugins, but then a sudden increased input level means a loop delay or filter resonance starts to put out a continuous squeal, the user hits Panic, now all plugins are disabled. They wouldn't want to reenable 100% of disabled plugins.

Or is disabled to Carla different from disabled to LV2?

**Comment by falkTX** [comment]
I understand the issue, but dont see a clear solution.
Carla would have to remember more state than it does now.

from the user's perspective, a simple limiter at the end of the chain would work, since disabling that will cut the audio.



> Or is disabled to Carla different from disabled to LV2?

It is the same, as in fully disable where audio does not roll.
Disabled plugins in carla do not run, like in a dry bypass way. At least for now anyway
