### ISSUE TITLE
Carla-Windows bridge crashes if Pigments 2 (vst) UI is turned on

### ISSUE THREAD

**Issue by xnqio** [falkTX/Carla#1006]
I'm trying to run the `Pigments 2` vst by Arturia with the help of Carla Plugin bridge. The sound works properly, i just get crashes every few minutes, especially if the Pigments UI is turned on and i try to access the parameters. I installed the development version of Carla.

Output is the following:

Unhandled exception: page fault on execute access to 0x00000000 in 64-bit code (0x0000000000000000).
Register dump:
 rip:0000000000000000 rsp:000000000032d388 rbp:000000000032d490 eflags:00010246 (  R- --  I  Z- -P- )
 rax:00000000000800a3 rbx:000000001880d6b0 rcx:000000000003009c rdx:0000000000000000
 rsi:0000000000000000 rdi:0000000000000000  r8:000000000032d450  r9:000000000032d448 r10:0000000000000002
 r11:0000000015273a58 r12:0000000000000000 r13:00000000000000ff r14:0000000000000000 r15:000000000003009c
Stack dump:
0x000000000032d388:  00000001806a0df9 0000000015273a60
0x000000000032d398:  0000000015273a60 0000000015273a60
0x000000000032d3a8:  0000000015273a60 00000000000800a3
0x000000000032d3b8:  000000000032d440 0000000000000000
0x000000000032d3c8:  000000000032d40c 0000000000000002
0x000000000032d3d8:  000000007cbf4b10 0000000000000000
0x000000000032d3e8:  00007f5b811abb52 00000000000100a8
0x000000000032d3f8:  000000007ca1df60 000000000c1e0000
0x000000000032d408:  01ff000000000000 00000000005800b9
0x000000000032d418:  007ffe0000000002 0000000018843b80
0x000000000032d428:  003ffc0000000008 0000000000000001
0x000000000032d438:  0000000000000000 0000000000000000
Backtrace:
=>0 0x0000000000000000 (0x000000000032d490)
0x0000000000000000: -- no code accessible --
Modules:
Module	Address					Debug info	Name (192 modules)
PE	          3d0000-          3e6000	Deferred        vcruntime140
PE	          3f0000-          3f4000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	          400000-          a62000	Deferred        carla-bridge-win64
PE	         1200000-         12a6000	Deferred        msvcp140
PE	         13c0000-         13c3000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	         13d0000-         13d4000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	         13e0000-         13e3000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	         13f0000-         13f5000	Deferred        api-ms-win-crt-math-l1-1-0
PE	         1400000-         1403000	Deferred        api-ms-win-crt-time-l1-1-0
PE	         1410000-         1413000	Deferred        api-ms-win-crt-conio-l1-1-0
PE	         3a80000-         3c23000	Deferred        pigmentsprocessor
PE	         9f10000-         9fb5000	Deferred        sqlite
PE	         bc80000-         be0c000	Deferred        libsndfile-2
ELF	        7a800000-        7aa0e000	Deferred        opengl32<elf>
  \-PE	        7a850000-        7aa0e000	\               opengl32
ELF	        7b400000-        7b833000	Deferred        kernel32<elf>
  \-PE	        7b420000-        7b833000	\               kernel32
ELF	        7bc00000-        7bd2f000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bd2f000	\               ntdll
ELF	        7c000000-        7c005000	Deferred        <wine-loader>
PE	       180000000-       180dc6000	Deferred        pigments
ELF	    7f5b7c4a4000-    7f5b7c4ae000	Deferred        libxcb-sync.so.1
ELF	    7f5b7c4ae000-    7f5b7c4b3000	Deferred        libxcb-present.so.0
ELF	    7f5b7c4b3000-    7f5b7c4d0000	Deferred        libxcb-glx.so.0
ELF	    7f5b7c9f1000-    7f5b7e716000	Deferred        libnvidia-glcore.so.435.21
ELF	    7f5b7e716000-    7f5b7e91a000	Deferred        libnvidia-tls.so.435.21
ELF	    7f5b7e91a000-    7f5b7ec34000	Deferred        libglx_nvidia.so.0
ELF	    7f5b7ec37000-    7f5b7ec3d000	Deferred        libxcb-dri3.so.0
ELF	    7f5b7ec7d000-    7f5b7ed3a000	Deferred        libgldispatch.so.0
ELF	    7f5b7ed3a000-    7f5b7ed6e000	Deferred        libglx.so.0
ELF	    7f5b7ed6e000-    7f5b7ee02000	Deferred        libgl.so.1
ELF	    7f5b7ee02000-    7f5b7ee07000	Deferred        libx11-xcb.so.1
ELF	    7f5b7ee6f000-    7f5b7ee98000	Deferred        combase<elf>
  \-PE	    7f5b7ee80000-    7f5b7ee98000	\               combase
ELF	    7f5b7ee9a000-    7f5b7eeae000	Deferred        libdrm.so.2
ELF	    7f5b7eeae000-    7f5b7f059000	Deferred        actxprxy<elf>
  \-PE	    7f5b7eee0000-    7f5b7f059000	\               actxprxy
ELF	    7f5b7f059000-    7f5b7f126000	Deferred        urlmon<elf>
  \-PE	    7f5b7f070000-    7f5b7f126000	\               urlmon
ELF	    7f5b7f126000-    7f5b7f1d3000	Deferred        ieframe<elf>
  \-PE	    7f5b7f140000-    7f5b7f1d3000	\               ieframe
ELF	    7f5b7f1d3000-    7f5b7f258000	Deferred        setupapi<elf>
  \-PE	    7f5b7f1e0000-    7f5b7f258000	\               setupapi
ELF	    7f5b7f258000-    7f5b7f3d3000	Deferred        wined3d<elf>
  \-PE	    7f5b7f280000-    7f5b7f3d3000	\               wined3d
ELF	    7f5b7f3d3000-    7f5b7f418000	Deferred        dxgi<elf>
  \-PE	    7f5b7f3e0000-    7f5b7f418000	\               dxgi
ELF	    7f5b7f418000-    7f5b7f45e000	Deferred        wbemprox<elf>
  \-PE	    7f5b7f420000-    7f5b7f45e000	\               wbemprox
ELF	    7f5b7f45e000-    7f5b7f55d000	Deferred        libasound.so.2
ELF	    7f5b7f56f000-    7f5b7f586000	Deferred        midimap<elf>
  \-PE	    7f5b7f580000-    7f5b7f586000	\               midimap
ELF	    7f5b7f586000-    7f5b7f5bf000	Deferred        winealsa<elf>
  \-PE	    7f5b7f590000-    7f5b7f5bf000	\               winealsa
ELF	    7f5b7f5bf000-    7f5b7f66a000	Deferred        libvorbisenc.so.2
ELF	    7f5b7f66a000-    7f5b7f697000	Deferred        libvorbis.so.0
ELF	    7f5b7f697000-    7f5b7f6d6000	Deferred        libflac.so.8
ELF	    7f5b7f6d6000-    7f5b7f6f3000	Deferred        libnsl.so.1
ELF	    7f5b7f6f3000-    7f5b7f8f9000	Deferred        libasyncns.so.0
ELF	    7f5b7f8f9000-    7f5b7f975000	Deferred        libsndfile.so.1
ELF	    7f5b7f975000-    7f5b7f9f5000	Deferred        libpulsecommon-13.0.so
ELF	    7f5b7f9f5000-    7f5b7fa4a000	Deferred        libpulse.so.0
ELF	    7f5b7fa51000-    7f5b7fa6c000	Deferred        msacm32<elf>
  \-PE	    7f5b7fa60000-    7f5b7fa6c000	\               msacm32
ELF	    7f5b7fa73000-    7f5b7faa2000	Deferred        winepulse<elf>
  \-PE	    7f5b7fa80000-    7f5b7faa2000	\               winepulse
ELF	    7f5b7faa2000-    7f5b7facb000	Deferred        mmdevapi<elf>
  \-PE	    7f5b7fab0000-    7f5b7facb000	\               mmdevapi
ELF	    7f5b7facb000-    7f5b7fbf8000	Deferred        ucrtbase<elf>
  \-PE	    7f5b7fb00000-    7f5b7fbf8000	\               ucrtbase
ELF	    7f5b7fbf8000-    7f5b7fd89000	Deferred        oleaut32<elf>
  \-PE	    7f5b7fc20000-    7f5b7fd89000	\               oleaut32
ELF	    7f5b7ff00000-    7f5b7ff0d000	Deferred        libogg.so.0
ELF	    7f5b7ff0d000-    7f5b7ff19000	Deferred        libwrap.so.0
ELF	    7f5b7ff19000-    7f5b7ff2f000	Deferred        api-ms-win-core-fibers-l1-1-1<elf>
  \-PE	    7f5b7ff20000-    7f5b7ff2f000	\               api-ms-win-core-fibers-l1-1-1
ELF	    7f5b7ff2f000-    7f5b7ff45000	Deferred        api-ms-win-core-synch-l1-2-0<elf>
  \-PE	    7f5b7ff40000-    7f5b7ff45000	\               api-ms-win-core-synch-l1-2-0
ELF	    7f5b7ff45000-    7f5b7ff5b000	Deferred        api-ms-win-crt-utility-l1-1-0<elf>
  \-PE	    7f5b7ff50000-    7f5b7ff5b000	\               api-ms-win-crt-utility-l1-1-0
ELF	    7f5b7ff5b000-    7f5b7ff71000	Deferred        api-ms-win-crt-environment-l1-1-0<elf>
  \-PE	    7f5b7ff60000-    7f5b7ff71000	\               api-ms-win-crt-environment-l1-1-0
ELF	    7f5b7ff71000-    7f5b7ff87000	Deferred        api-ms-win-crt-filesystem-l1-1-0<elf>
  \-PE	    7f5b7ff80000-    7f5b7ff87000	\               api-ms-win-crt-filesystem-l1-1-0
ELF	    7f5b7ff87000-    7f5b7ffa0000	Deferred        api-ms-win-crt-multibyte-l1-1-0<elf>
  \-PE	    7f5b7ff90000-    7f5b7ffa0000	\               api-ms-win-crt-multibyte-l1-1-0
ELF	    7f5b7ffa0000-    7f5b7ffb8000	Deferred        api-ms-win-crt-convert-l1-1-0<elf>
  \-PE	    7f5b7ffb0000-    7f5b7ffb8000	\               api-ms-win-crt-convert-l1-1-0
ELF	    7f5b7ffb8000-    7f5b7ffd0000	Deferred        api-ms-win-crt-string-l1-1-0<elf>
  \-PE	    7f5b7ffc0000-    7f5b7ffd0000	\               api-ms-win-crt-string-l1-1-0
ELF	    7f5b8021a000-    7f5b8023d000	Deferred        libgpg-error.so.0
ELF	    7f5b8023d000-    7f5b8035b000	Deferred        libgcrypt.so.20
ELF	    7f5b8035b000-    7f5b8037b000	Deferred        liblz4.so.1
ELF	    7f5b8037b000-    7f5b803a2000	Deferred        liblzma.so.5
ELF	    7f5b803a2000-    7f5b803ad000	Deferred        librt.so.1
ELF	    7f5b803ad000-    7f5b80455000	Deferred        libsystemd.so.0
ELF	    7f5b80455000-    7f5b8045f000	Deferred        libffi.so.6
ELF	    7f5b8045f000-    7f5b8047a000	Deferred        libresolv.so.2
ELF	    7f5b8047a000-    7f5b80481000	Deferred        libkeyutils.so.1
ELF	    7f5b80481000-    7f5b804d0000	Deferred        libdbus-1.so.3
ELF	    7f5b804d0000-    7f5b80551000	Deferred        libgmp.so.10
ELF	    7f5b80551000-    7f5b80589000	Deferred        libhogweed.so.4
ELF	    7f5b80589000-    7f5b805c1000	Deferred        libnettle.so.6
ELF	    7f5b805c1000-    7f5b805d7000	Deferred        libtasn1.so.6
ELF	    7f5b805d7000-    7f5b80759000	Deferred        libunistring.so.2
ELF	    7f5b80759000-    7f5b8077a000	Deferred        libidn2.so.0
ELF	    7f5b8077a000-    7f5b808af000	Deferred        libp11-kit.so.0
ELF	    7f5b808af000-    7f5b808be000	Deferred        libkrb5support.so.0
ELF	    7f5b808be000-    7f5b808c5000	Deferred        libcom_err.so.2
ELF	    7f5b808c5000-    7f5b808f6000	Deferred        libk5crypto.so.3
ELF	    7f5b808f6000-    7f5b809d3000	Deferred        libkrb5.so.3
ELF	    7f5b809d3000-    7f5b80b92000	Deferred        libgnutls.so.30
ELF	    7f5b80b92000-    7f5b80bdf000	Deferred        libgssapi_krb5.so.2
ELF	    7f5b80bdf000-    7f5b80c70000	Deferred        libcups.so.2
PE	    7f5b80c71000-    7f5b80c99000	Deferred        jackbridge-wine64
ELF	    7f5b80c99000-    7f5b80cd9000	Deferred        uxtheme<elf>
  \-PE	    7f5b80ca0000-    7f5b80cd9000	\               uxtheme
ELF	    7f5b80cd9000-    7f5b80edf000	Deferred        libxfixes.so.3
ELF	    7f5b80edf000-    7f5b80eec000	Deferred        libxcursor.so.1
ELF	    7f5b80eec000-    7f5b80efe000	Deferred        libxi.so.6
ELF	    7f5b80efe000-    7f5b80f03000	Deferred        libxcomposite.so.1
ELF	    7f5b80f03000-    7f5b80f10000	Deferred        libxrandr.so.2
ELF	    7f5b80f10000-    7f5b8111a000	Deferred        libxrender.so.1
ELF	    7f5b8111a000-    7f5b81121000	Deferred        libxxf86vm.so.1
ELF	    7f5b81121000-    7f5b81126000	Deferred        libxinerama.so.1
ELF	    7f5b81126000-    7f5b81140000	Deferred        libbsd.so.0
ELF	    7f5b81140000-    7f5b81148000	Deferred        libxdmcp.so.6
ELF	    7f5b81148000-    7f5b8114e000	Deferred        libxau.so.6
ELF	    7f5b8114e000-    7f5b81177000	Deferred        libxcb.so.1
ELF	    7f5b81177000-    7f5b812b5000	Deferred        libx11.so.6
ELF	    7f5b812b5000-    7f5b812ca000	Deferred        libxext.so.6
ELF	    7f5b812d0000-    7f5b812e3000	Deferred        libavahi-client.so.3
ELF	    7f5b812e3000-    7f5b812f1000	Deferred        libavahi-common.so.3
ELF	    7f5b812f3000-    7f5b81399000	Deferred        winex11<elf>
  \-PE	    7f5b81300000-    7f5b81399000	\               winex11
ELF	    7f5b81470000-    7f5b8149e000	Deferred        libexpat.so.1
ELF	    7f5b8149e000-    7f5b814e4000	Deferred        libfontconfig.so.1
ELF	    7f5b814e4000-    7f5b8151c000	Deferred        libpng16.so.16
ELF	    7f5b8151c000-    7f5b815d7000	Deferred        libfreetype.so.6
ELF	    7f5b81600000-    7f5b81632000	Deferred        iphlpapi<elf>
  \-PE	    7f5b81610000-    7f5b81632000	\               iphlpapi
ELF	    7f5b81632000-    7f5b81662000	Deferred        msacm32<elf>
  \-PE	    7f5b81640000-    7f5b81662000	\               msacm32
ELF	    7f5b81662000-    7f5b8172b000	Deferred        winmm<elf>
  \-PE	    7f5b81670000-    7f5b8172b000	\               winmm
ELF	    7f5b8172b000-    7f5b8176e000	Deferred        ws2_32<elf>
  \-PE	    7f5b81740000-    7f5b8176e000	\               ws2_32
ELF	    7f5b8176e000-    7f5b8179e000	Deferred        mpr<elf>
  \-PE	    7f5b81780000-    7f5b8179e000	\               mpr
ELF	    7f5b8179e000-    7f5b817ba000	Deferred        libz.so.1
ELF	    7f5b817c5000-    7f5b817e3000	Deferred        wsock32<elf>
  \-PE	    7f5b817d0000-    7f5b817e3000	\               wsock32
ELF	    7f5b817e3000-    7f5b81876000	Deferred        wininet<elf>
  \-PE	    7f5b817f0000-    7f5b81876000	\               wininet
ELF	    7f5b81876000-    7f5b81958000	Deferred        msvcrt<elf>
  \-PE	    7f5b81890000-    7f5b81958000	\               msvcrt
ELF	    7f5b81958000-    7f5b819a3000	Deferred        winspool<elf>
  \-PE	    7f5b81960000-    7f5b819a3000	\               winspool
ELF	    7f5b819a3000-    7f5b819ce000	Deferred        imm32<elf>
  \-PE	    7f5b819b0000-    7f5b819ce000	\               imm32
ELF	    7f5b819ce000-    7f5b81a1d000	Deferred        usp10<elf>
  \-PE	    7f5b819e0000-    7f5b81a1d000	\               usp10
ELF	    7f5b81a1d000-    7f5b81ba6000	Deferred        comctl32<elf>
  \-PE	    7f5b81a30000-    7f5b81ba6000	\               comctl32
ELF	    7f5b81ba6000-    7f5b81c4b000	Deferred        rpcrt4<elf>
  \-PE	    7f5b81bc0000-    7f5b81c4b000	\               rpcrt4
ELF	    7f5b81c4b000-    7f5b81e11000	Deferred        ole32<elf>
  \-PE	    7f5b81c70000-    7f5b81e11000	\               ole32
ELF	    7f5b81e11000-    7f5b81e3c000	Deferred        shcore<elf>
  \-PE	    7f5b81e20000-    7f5b81e3c000	\               shcore
ELF	    7f5b81e3c000-    7f5b81fc2000	Deferred        gdi32<elf>
  \-PE	    7f5b81e50000-    7f5b81fc2000	\               gdi32
ELF	    7f5b81fc2000-    7f5b8223b000	Deferred        user32<elf>
  \-PE	    7f5b81fe0000-    7f5b8223b000	\               user32
ELF	    7f5b8223b000-    7f5b822cb000	Deferred        shlwapi<elf>
  \-PE	    7f5b82250000-    7f5b822cb000	\               shlwapi
ELF	    7f5b822cb000-    7f5b82ce5000	Deferred        shell32<elf>
  \-PE	    7f5b822f0000-    7f5b82ce5000	\               shell32
ELF	    7f5b82ce5000-    7f5b82e27000	Deferred        comdlg32<elf>
  \-PE	    7f5b82cf0000-    7f5b82e27000	\               comdlg32
ELF	    7f5b82f27000-    7f5b82fc4000	Deferred        advapi32<elf>
  \-PE	    7f5b82f40000-    7f5b82fc4000	\               advapi32
ELF	    7f5b82fc4000-    7f5b82fd8000	Deferred        libnss_files.so.2
ELF	    7f5b8379c000-    7f5b837b6000	Deferred        libgcc_s.so.1
ELF	    7f5b837b6000-    7f5b83905000	Deferred        libm.so.6
ELF	    7f5b83907000-    7f5b8390d000	Deferred        libdl.so.2
ELF	    7f5b8390d000-    7f5b83afe000	Deferred        libc.so.6
ELF	    7f5b83afe000-    7f5b83b21000	Deferred        libpthread.so.0
ELF	    7f5b83b25000-    7f5b83b2e000	Deferred        libuuid.so.1
ELF	    7f5b83b2e000-    7f5b83b4a000	Deferred        version<elf>
  \-PE	    7f5b83b30000-    7f5b83b4a000	\               version
ELF	    7f5b83cf4000-    7f5b83d23000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000023    0
	00000020    0
	0000001b    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000026    0
	00000022    0
	00000021    0
	0000001f    0
00000024 explorer.exe
	00000029    0
	00000028    0
	00000027    0
	00000025    0
0000002a (D) Z:\usr\local\lib\carla\carla-bridge-win64.exe
	00000058    0
	00000056    0
	00000055    1
	00000054    1
	00000052    0
	00000051    0
	00000050    0
	0000004f    0
	0000004e    0
	0000004d    0
	00000038    0
	00000037    0
	0000002d   15
	0000002c    0
	0000002b    0 <==
System information:
    Wine build: wine-4.0.2 (Ubuntu 4.0.2-1)
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.3.0-29-generic

**Comment by falkTX** [comment]
Not able to reproduce here.
tested with a midi file and playing stuff in pigments vst.

so this might just be a wine thing, which I simply cannot support too much.
unless other plugins are broken in the same way, I consider this "if it works, cool, if not oh well"
