### ISSUE TITLE
Carla refuses to open

### ISSUE THREAD

**Issue by InstantCurry** [falkTX/Carla#1008]
I recently discovered that my install of Carla does not open. I am running pop_OS 18.04, and installed Carla though the ubuntu studio packages. I have no information other that "one day it worked fine, the next day, it didn't" 

I have linked the output when I attempt to run it in terminal, though keep in mind that Mulimc gives a similar error in terminal, yet runs fine on its own.

`Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 30, in <module>
    from PyQt5.QtCore import qCritical, QEventLoop, QFileInfo, QModelIndex, QPointF, QTimer
ModuleNotFoundError: No module named 'PyQt5.QtCore'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 30, in <module>
    from PyQt5.QtCore import qCritical, QEventLoop, QFileInfo, QModelIndex, QPointF, QTimer
ModuleNotFoundError: No module named 'PyQt5.QtCore'
`

**Comment by falkTX** [comment]
Seems like it either updated python without the proper pyqt rebuild, or pyqt got removed.
This is an issue in the linux distribution, nothing to do with carla.

**Comment by coffeeandspaceships** [comment]
See #629. POP OS is System76's derivative of Ubuntu, so this is the same issue. You need to apt install python-qt4 or python-qt5, depending which version of qt you have installed.

**Comment by falkTX** [comment]
If carla is installed via kxstudio repos, the dependency is in the package, so there is no need for that.
If carla is installed via pre-compiled binary, pyqt is pre-included.
This is only an issue if building from source. is that the case?

**Comment by falkTX** [comment]
Note that v2.1 (develop branch) no longer uses qt4, only qt5

**Comment by InstantCurry** [comment]
After re-installing and encountering the same issue while adding a ppa to the system, I discovered that the version of python I updated to is to blame. If you've updated python, pyqt no longer functions. To solve the issue, change your python3 version back to the system one.

**Comment by coffeeandspaceships** [comment]
It looks like pyqt only added 3.8 support in December, and it doesn't look like it's been formally tested and issue closed yet:
https://github.com/altendky/pyqt5-tools/issues/35

**Comment by falkTX** [comment]
Closing this issue since it is not an issue with carla, but pyqt.
Note that in a future release Carla is dropping python and going full c++

**Comment by altendky** [comment]
FYI, PyQt5 had support for Python 3.8 long before December afaik.  The link is to pyqt5-tools which I have not done a good job of keeping up to date.  Though it does presently support latest Python and PyQt5.
