### ISSUE TITLE
Display CV ports with green colour in Carla-patchbay

### ISSUE THREAD

**Issue by grammoboy2** [falkTX/Carla#1011]
CV ports are now blue in RC1. Green would be nice.

**Comment by falkTX** [comment]
they are dark blue, because it is related to audio in a way.

**Comment by grammoboy2** [comment]
I didn't see it as different colors blue. Patchage is showing it as
green I think. Which gave a clear workflow.

**Comment by mxmilkb** [comment]
I must admit I have had to move my head and squint slightly given the ambient light situation a few times already to see if a port was CV or audio.

Possibly turquoise as a half way house, that would be [similar to Ingen](https://i.imgur.com/8wqtLsa.png).

I think though also that symbols would be a good idea for making things easier to understand.

I guess there are different forms of colour blindness to take into account too, maybe even monochrome screens (i.e. e-paper screens/monitors)?

**Comment by grammoboy2** [comment]
I probably should check patchage again, i'm actually not sure anymore if i was right claiming cv was green, cause audio is green on patchage... so maybe they're both green. Will check later...

**Comment by falkTX** [comment]
Some time ago I had the idea of exposing plugin parameters as controls, and a patchcanvas "parameter" type for it.
It kinda fits into CV ports since they are kinda control-type and we can make regular parameters appear as CV.
So now CV are brown :)

![Screenshot_20200413_035159](https://user-images.githubusercontent.com/1334853/79088311-232dca00-7d3a-11ea-8c43-6f7816b0a230.png)

Green color is reserved for ALSA-MIDI, in order to still have that for Catia and keep Carla/Catia colors consistent.

**Comment by mxmilkb** [comment]
I think there is an accessibility problem.

I used https://colororacle.org to make this:

![image](https://user-images.githubusercontent.com/108225/79180481-fe048e80-7e01-11ea-91bd-1ca906684784.png)

There are colour palettes though that ameliorate this http://mkweb.bcgsc.ca/colorblind

**Comment by trebmuh** [comment]
I'm colorblind and I don't see the difference between brown (alsa-midi) and red (jack-midi) connectors.

**Comment by mjsuarez** [comment]
Having a background in mapping, when this issue first came up I made this graphic to express concern over choosing green, though I never posted it.  Looks like brown is even less distinguishable.

![ColorBlindGraphic](https://user-images.githubusercontent.com/5629483/79349211-9b8fb900-7efb-11ea-9389-cc2a820f59db.png)

FWIW, looking at Patchage 1.0.1, it's port colors are user configurable

![Patchage-port-colors](https://user-images.githubusercontent.com/5629483/79349393-c548e000-7efb-11ea-8616-5b411302687d.png)

**Comment by mxmilkb** [comment]
Mentioned in #lad http://pippin.gimp.org/ametameric

**Comment by trebmuh** [comment]
> FWIW, looking at Patchage 1.0.1, it's port colors are user configurable

It'd be a great idea to get the color configurable as an option, then the software could cover all the different colorblindness types.
