### ISSUE TITLE
cannot compile Carla on Fedora32

### ISSUE THREAD

**Issue by martinkg** [falkTX/Carla#1014]
Hi,

the recent version of Carla didn't compile on Fedora32 with gcc10.

`Compiling libjack.cpp
In file included from libjack.cpp:18:
libjack.hpp:172:19: error: 'string' is not a member of 'std'
  172 |     std::map<std::string, JackPortState*> portNameMapping;
      |                   ^~~~~~
libjack.hpp:51:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
   50 | #include "api.hpp"
  +++ |+#include <string>
   51 |
libjack.hpp:172:19: error: 'string' is not a member of 'std'
  172 |     std::map<std::string, JackPortState*> portNameMapping;
      |                   ^~~~~~
libjack.hpp:172:19: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
libjack.hpp:172:41: error: template argument 1 is invalid
  172 |     std::map<std::string, JackPortState*> portNameMapping;
      |                                         ^
libjack.hpp:172:41: error: template argument 3 is invalid
libjack.hpp:172:41: error: template argument 4 is invalid`

the compilation could be fixed with the following patch:

`--- a/source/libjack/libjack.hpp.orig   2020-02-07 11:50:53.267552094 +0100
+++ b/source/libjack/libjack.hpp        2020-02-07 11:52:53.336539210 +0100
@@ -15,6 +15,9 @@
  * For a full copy of the GNU General Public License see the doc/GPL.txt file.
  */

+// needed by gcc10
+#include <string>
+
 #ifndef CARLA_LIBJACK_HPP_INCLUDED
 #define CARLA_LIBJACK_HPP_INCLUDED`

**Comment by falkTX** [comment]
hey, thanks for the report.
can you fix the formatting of the patch?

**Comment by martinkg** [comment]
patch for gcc10

```
--- a/source/libjack/libjack.hpp.orig   2020-02-07 11:50:53.267552094 +0100
+++ b/source/libjack/libjack.hpp        2020-02-07 11:52:53.336539210 +0100
@@ -15,6 +15,9 @@
  * For a full copy of the GNU General Public License see the doc/GPL.txt file.
  */

+// needed by gcc10
+#include <string>
+
 #ifndef CARLA_LIBJACK_HPP_INCLUDED
 #define CARLA_LIBJACK_HPP_INCLUDED


```
