### ISSUE TITLE
ALSA MIDI port selection (can't get ALSA MIDI to work)

### ISSUE THREAD

**Issue by Yoshqu** [falkTX/Carla#1016]
I use ALSA only. "Midi Input / Capture 1" and "Midi Output / Playback 1" is visible in Patchbay, but not in aconnect -l

client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'

so I can't connect midi to Carla...for other standalone apps it works like this:

client 128: 'Helm' [type=user,pid=16736]
    0 'Midi Through Port-0'
	Connected From: 14:0
client 129: 'Helm' [type=user,pid=16748]
    0 'Midi Through Port-0'
	Connected From: 14:0
client 132: 'VCV Rack' [type=user,pid=16767]
    0 'VCV Rack input  '
	Connected From: 14:0
client 133: 'VCV Rack' [type=user,pid=16767]
    0 'VCV Rack output '
	Connecting To: 14:0[real:0]

so i can route midi events from vcv rack to heml (i know - crazy example, but it works - and it's only an example).

For Calra - simplest case would be enough for me - route client 14:0 into Carla.

**Comment by falkTX** [comment]
If you go into (menu) canvas->show external and then connect things, does that work?

**Comment by Yoshqu** [comment]
LOL I have selected smaller canvas - but positions for plugins were old - so, they stacked into rightmost/downmost part of external. (this could be feature request - recenter all plugins when going into smaller canvas)

Thanks, i looked into 3 times and didn't see. I'll check this right now - but names are ok so i suppose it will work. 

Thanks!
