### ISSUE TITLE
mp3 file output is static

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#1017]
Drag an mp3 to the rack, connect to output, turn down the volume and hit play.

**Comment by falkTX** [comment]
Might be due to ffmpeg changes that broke what carla uses.
What version do you have?

Try something like ogg and flag, so that libsndfile handles it.
That might work much better.

**Comment by mxmilkb** [comment]
1:2.1.rc1.r13.g3e085fab9-1

WAV, FLAC and Vorbis work.

If ffmpeg deals with mp3 for Carla, could .dsf (DSD) support be possible?

**Comment by falkTX** [comment]
if mp3 is broken, then other formats likely will.

I need to know your ffmpeg version, so I can disable it in such case.
Better than having broken funcionality

**Comment by mxmilkb** [comment]
ffmpeg 1:4.2.2-2
