### ISSUE TITLE
Middle click on port to disconnect all connections to/from it?

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#1019]
Would make the user workflow just a little bit quicker.

**Comment by falkTX** [comment]
There is already a shortcut for disconnecting ports.
It is not documented anywhere, but I plan to write it in the manual.

Just hold ctrl and press&drag the middle mouse button. it will act as a knife to "cut" connections.

**Comment by mxmilkb** [comment]
I discovered that after by accident when I was showing a friend, who noted it was like Blender, though I didn't try directly ctrl middle click on ports to disconnect, I see now that does work, thanks :)
