### ISSUE TITLE
Carla-git nsm close takes a long time

### ISSUE THREAD

**Issue by grammoboy2** [falkTX/Carla#102]
Using carla-git on Ubuntu 12.04 with NSM. When the GUI of the plugin is open (gxdetune) and I hit close, shutting down Carla takes more then a minute. This is not the case when the plugin GUI is not open.

**Comment by falkTX** [comment]
I think this is fixed now, confirmation would be welcome.

**Comment by falkTX** [comment]
Closing ticket after 5 years without confirmation :)
Other folks have been using Carla with NSM and report regular/expected loading times.

**Comment by grammoboy2** [comment]
On 7/12/20 1:18 AM, Filipe Coelho wrote:
>
> Closing ticket after 5 years without confirmation :)
> Other folks have been using Carla with NSM and report regular/expected 
> loading times.
>

Time flies
>
