### ISSUE TITLE
Internal midi2cv - gate output?

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#1020]
Currently the internal only has pitch, velocity and trigger, but a gate output (like the MOD "MIDI to CV mono/Poly" plugins) would be very handy.

**Comment by mxmilkb** [comment]
Actually, currently the internal midi2cv trigger output behaves like a gate output, i.e., it has a high signal for the duration of the input MIDI node, rather than a trigger style brief high on the start of the MIDI note.

**Comment by falkTX** [comment]
midi2cv plugin is a copy of the mod cv plugins one, so might just be I labelled the cv out wrong.
will check soon

**Comment by falkTX** [comment]
That was indeed a typo :(
sorry, a few projects will be broken now (need manual re-connection of the misnamed port)

**Comment by falkTX** [comment]
See fe545cc42975057209d9a83139fca8886377f23e
