### ISSUE TITLE
MIDI Pattern octave off-by-one issue

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1021]
Patching MIDI Pattern to the MOD MIDI to CV mono plugin, with just a couple of looping F2 notes as the Pattern. When the latter plugin is selected, the virtual MIDI keyboard shows presses on F3.

**Comment by falkTX** [comment]
Fixed in 6f9a4cc7b8dfbc0e3205ce21a24b3e7f156a04e6
