### ISSUE TITLE
Activate patchbay level meters when CV plugin is selected?

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#1023]
Currently only signal going through audio ports of a selected plugin makes the meters do their thing.

**Comment by falkTX** [comment]
That is expected. CV has optional range, so it is impossible to know exactly how to display.
Use a cv meter (like the one in the mod cv plugins) for that.

**Comment by mxmilkb** [comment]
If a CV plugin has min and max for the port, the range is known, no?

Otherwise, sometimes /any/ immediate indication there is signal getting through would be beneficial (rather than having to go through the action of [loading and] patching a plugin). I'm not sure of the best way to visualise that, but even like a single blinking dot or question mark or something at the bottom of the in-built level would help.
