### ISSUE TITLE
Display MIDI notes on virtual keyboard when internal MIDI plugin is selected?

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#1024]
Currently they are only displayed when a MIDI plugin is selected.

**Comment by falkTX** [comment]
I dont understand the request here...

**Comment by mxmilkb** [comment]
If I have x42 MIDI Generator into MOD MIDI to CV, and I select the later, I see the incoming notes on the virtual keyboard. When I have the generator going into the internal MIDI to CV (or any other internal MIDI plugin) and it is selected, I see nothing in the virtual keyboard.

**Comment by falkTX** [comment]
because the canvas keyboard shows the input, not the output.

**Comment by mxmilkb** [comment]
The inputs to internal MIDI plugins, when they receive MIDI, don't make the canvas keyboard show anything

**Comment by falkTX** [comment]
this is not just the internal plugins, it is happening in general :(

**Comment by falkTX** [comment]
Fixed in 57e3a99b74ffd063ccc4c0b8201adc06ed5d02d1
Good catch, a nasty thing that could lead to other issues.
