### ISSUE TITLE
Parameter isn't loaded correctly(?)

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#1029]
![image](https://user-images.githubusercontent.com/108225/75041308-3ba90300-54b4-11ea-9711-12bd1ebefa85.png)

I thought it wasn't saving, but I looked at the file and it's not loading.

https://github.com/mxmilkb/carla-modular-synth-tests/tree/master/drone_winds_on

**Comment by falkTX** [comment]
can you be more specific? which one exactly is not loading?

**Comment by mxmilkb** [comment]
Freq (Hz).

**Comment by falkTX** [comment]
I dont get this.
In your project the "Freq (Hz)" of the ams multiphase lfo is being modulated by the zlfo plugin.
This invalidates any possible saved value the parameter has, since any change from zlfo will trigger a change on the "Freq (Hz)" parameter.

**Comment by mxmilkb** [comment]
That is probably my mistake then! Not sure what I was thinking..

**Comment by falkTX** [comment]
no problem. likely the issue might happen somewhere else.
I will close this one

**Comment by mxmilkb** [comment]
The problem I was conflating something else with;

Trying to set the slew limiters after the multiphase OSC to the organ, I've set them all above 100ms, save, close Carla, reopen and at least one of the slew rate plugins' rise and fall paramaters has reset to 0.

**Comment by mxmilkb** [comment]
Just to confirm that this is still an issue, though apparently just with the MOD Slew Limiter.

![image](https://user-images.githubusercontent.com/108225/75605307-7a087880-5ad9-11ea-819b-2ab625f238d1.png)

**Comment by mxmilkb** [comment]
Note; I Replaced all the MOD Slew Limters with AMS Slew Limiters, saved and reopened. 3 of the AMS Slew Limiters that has been connected from the multiphase osc were disconnected and in a random position. Reconnecting, resaving and loading again and they stayed the same.
