### ISSUE TITLE
Carla Control won't show plugin

### ISSUE THREAD

**Issue by evazzoler** [falkTX/Carla#1042]
Carla 2.0.96 (2.1-RC1) on Ubuntu 18.04 LTE

When I add a plugin (from local or contol) the plugin is added and shown on the local gui but don't appear on the control gui. Patchbay works fine.

**Comment by falkTX** [comment]
Yep, I know. I am just finishing some additional bug-fixing and releasing RC2 very soon.
(the issue is fixed on RC2)

**Comment by evazzoler** [comment]
Thank you! Thank you for all. This software is amazing!

**Comment by OnkelTem** [comment]
Any updates? Plugins don't appear on the Patchbay tab. Just installed Carla from the KXStudio debian repo. Version: 2.0.0. It's a sort of a show-stopper. Which looks pretty odd for a stable version.

**Comment by falkTX** [comment]
Please use the 2.1-RC2 version.
It is going to be out as the stable one in a couple of days.

**Comment by OnkelTem** [comment]
@falkTX Have a look at my addition ^^^^ please. Maybe I do something wrong?

> Please use the 2.1-RC2 version.
> It is going to be out as the stable one in a couple of days.

Sure. Thanks. But is there a binary release somewhere or the only way is to to build it from sources?

**Comment by falkTX** [comment]
you can use carla-git via kxstudio repos, or the releases in this repository. both are in binary form

**Comment by falkTX** [comment]
note that when running in rack mode, there wont be new plugins in the patchbay.
that is just how it works.

**Comment by OnkelTem** [comment]
> you can use carla-git via kxstudio repos, or the releases in this repository. both are in binary form

Perfect! Thanks.

**Comment by OnkelTem** [comment]
@falkTX 

I switched to the **Patchbay** processing mode, restarted the app and it's now adding plugins to the Patchbay view. Now I have the following layout:

![](https://i.gyazo.com/7345f8297b2104eb383f57d322aa039a.png)

At least now it's working.

Unfortunately it doesn't select my external mic. May I open a new issue about it? Or I can ask here @falkTX ?
