### ISSUE TITLE
Issues when running conda

### ISSUE THREAD

**Issue by Nintorac** [falkTX/Carla#1044]
Hey, love the set of tools you are maintaining here! Keep up the good work!!

I have noticed an issue. When using Conda launching Carla from CLI will fail with `ModuleNotFoundError: No module named PyQt5` however installing `PyQt5` just results in more silent and annoying errors later on.

Specifically the issue lies in this line https://github.com/falkTX/Carla/blob/develop/data/carla#L3 since when running conda `which python3` will point to the users local version, eg something like `/home/user/miniconda3/bin/python3`

For the meantime the workaround I have found is to launch Carla like so `PATH=/usr/bin carla -n /path/to/carla.carxp`

**Comment by falkTX** [comment]
I have no idea what "conda" is, but this is an issue with their packaging.
If custom changes are needed to start an application, it should patch the startup files as needed.

**Comment by Nintorac** [comment]
[Conda](https://docs.conda.io/projects/conda/en/latest/) is just a fancy abstraction of pip and venv that can come in handy when developing with python . I imagine this issue would also occur just using a python env too

**Comment by falkTX** [comment]
Carla is not really suitable to be used with such tools.
In fact, v2.2 (or perhaps v3.0) will move the frontend from python to c++. this work has already started

**Comment by Nintorac** [comment]
Fair enough, well if you want I could prepare a pr to hard link to the system python or if you prefer just leave it and wait for the c++

**Comment by Nintorac** [comment]
Hijacking the issue slightly here; are there any chat channels to discuss jack/kxstudio?

**Comment by falkTX** [comment]
yes.
there is #kxstudio and #jack on freenode IRC, or chat.kx.studio that runs a rocketchat instance.

**Comment by falkTX** [comment]
I will close this issue since Carla as-is works in general distributions.
Specialized ones are free to patch carla to work for them. I will accept patches that retain compatibility with existing systems.
