### ISSUE TITLE
Parameter exposed as a CV port shows as audio port

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1045]
![image](https://user-images.githubusercontent.com/108225/76135145-31dae000-601c-11ea-92fb-eeeabaa3dd1c.png)

![image](https://user-images.githubusercontent.com/108225/76135676-2dfd8c80-6021-11ea-83ca-ad0bc1f63fa7.png)
(that's an AMS VCO3)

Though I do actually value having the distinction. Possibly another colour could be used instead? Like in Ingen.

**Comment by mxmilkb** [comment]
On project reload they are displayed as CV

![image](https://user-images.githubusercontent.com/108225/76136055-58514900-6025-11ea-86ed-e50f2db64855.png)

**Comment by falkTX** [comment]
That might be related to issues with jack metadata that carla had before.
Should not be happening anymore now, please confirm.

**Comment by mxmilkb** [comment]
When you expose a port as CV, it goes blue if the value is 0 and brown if the value is not 0.
