### ISSUE TITLE
Carla unable to start (Fedora 31)

### ISSUE THREAD

**Issue by wickyw** [falkTX/Carla#1047]
First of all, thanks for all the hard work put into this program!
I've run into the following issue:
After installing Carla on Fedora 31 from the repos, it refuses to start, giving the following trace:
```Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 30, in <module>
    from PyQt5.QtCore import QT_VERSION, qCritical, QEventLoop, QFileInfo, QModelIndex, QPointF, QTimer, QEvent
ModuleNotFoundError: No module named 'PyQt5.sip' 
```
So, my next step was to try to build Carla from source. Again, the same error:
``` Traceback (most recent call last):
  File "/usr/local/bin/pyrcc5", line 6, in <module>
    from PyQt5.pyrcc_main import main
  File "/usr/local/lib64/python3.7/site-packages/PyQt5/pyrcc_main.py", line 21, in <module>
    from PyQt5.QtCore import PYQT_VERSION_STR, QDir, QFile
ModuleNotFoundError: No module named 'PyQt5.sip'
make[1]: *** [Makefile:271: resources_rc.py] Error 1
make[1]: Leaving directory '/home/wick/Carla/source/frontend'
make: *** [Makefile:171: frontend] Error 2
```
Given this information, I looked up the error and wandered upon the following StackOverflow thread: [https://stackoverflow.com/questions/55087069/no-module-named-pyqt5-sip](url), where a reference is made to a change in PyQt5 5.11: [https://www.riverbankcomputing.com/static/Docs/PyQt5/incompatibilities.html#pyqt-v5-11](url).
The question is: is this to do with my specific installation or is this a problem with the program? If the former, any ideas on how to resolve the issue?

**Comment by falkTX** [comment]
This is an issue with the sip package, I had something similar myself.
Needs to be built with something like `--sip-module PyQt5.sip`.

Nothing to do with carla itself, so I will close this ticket.
