### ISSUE TITLE
Big Meter LV2 and Ardour 5.12

### ISSUE THREAD

**Issue by tank-trax** [falkTX/Carla#1050]
this is probably innocuous or maybe not but when loading Adour shows this error

[WARNING]: Ignoring LV2 plugin "Big Meter" because its buffer-size requirements cannot be satisfied.

Using Carla-git versuib 2.096 (2.1-RC1)

**Comment by falkTX** [comment]
good point, the bigmeter plugin does not actually need fixed buffers. I can remove that restriction

**Comment by tank-trax** [comment]
FYI, the message no longer appears when opening Ardour
Thanks
