### ISSUE TITLE
Informational: gentoo will soon cancel osc feature availability

### ISSUE THREAD

**Issue by CaptainBloodz** [falkTX/Carla#1052]
The following installed packages are masked:
 - media-libs/pyliblo-0.10.0-r1::gentoo (masked by: package.mask)

equery d media-libs/pyliblo
 * These packages depend on media-libs/pyliblo:
media-sound/carla-9999 (osc ? media-libs/pyliblo)

media-libs/pyliblo: last commit in 2015, the only revdep is media-sound/gtklick, there is an actively maintained fork named pyliblo3.

Thks 4 ur attention.

**Comment by falkTX** [comment]
pyliblo does not need any changes, because only the underlying library (liblo) is the one that changes.
personally I do not see a need to move away from it.

Thanks for the attention though, noted.

**Comment by kshpytsya** [comment]
The problem is that currently `pyliblo` is not buildable with the current Cython 3.*.
