### ISSUE TITLE
Carla plugin window is cropped in REAPER

### ISSUE THREAD

**Issue by gwatcha** [falkTX/Carla#1057]
Hey I installed carla through 'carla-git' on the AUR, which uses the develop branch. In REAPER, the plugin window looks like this.

![image](https://user-images.githubusercontent.com/31526638/77202300-4783e700-6aab-11ea-874d-b8e608d25eb6.png)

:(

**Comment by falkTX** [comment]
cant reproduce here

![Screenshot_20200330_173943](https://user-images.githubusercontent.com/1334853/77938299-71a88680-72ad-11ea-871a-7f6a9094303a.png)

anyone else with the same issue?

**Comment by terencode** [comment]
Cannot reproduce with any of carla vsts but this makes me think a lot about https://github.com/falkTX/Carla/issues/932 that I can reproduce within reaper as well.

**Comment by falkTX** [comment]
looking more closely at the screenshot, I see carla is running in high-dpi mode.
carla does not report the correct size to the host in such cases, I need to fix this.
