### ISSUE TITLE
Can't see Pulseaudio JACK sink/source

### ISSUE THREAD

**Issue by redraw** [falkTX/Carla#1060]
Hi @falkTX!

I no longer can see PulseAudio JACK sink/source in Carla, whereas I can from Claudia. Do you guess why?

Actually, it's like Carla is working as a JACK client, not seeing everything outside.

```
➜ uname -a
Linux x556 5.3.0-42-lowlatency #34-Ubuntu SMP PREEMPT Fri Feb 28 06:31:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
➜ apt show carla
Package: carla
Version: 5:2.0.0+git20190808.3
```

![image](https://user-images.githubusercontent.com/10843208/77489737-cd8b8f00-6e17-11ea-8e00-333c589dfad2.png)

![image](https://user-images.githubusercontent.com/10843208/77489957-4f7bb800-6e18-11ea-9f93-6568a8377869.png)

![image](https://user-images.githubusercontent.com/10843208/77492347-1e52b600-6e1f-11ea-808e-9c240856b514.png)

**Comment by redraw** [comment]
I've realized I can only see two process modes (Patchbay and Rack), but I can't see Single / Multi client modes.

I read somewhere that I can run `carla-jack-multi`. Then found out I was missing `pyqt5` (not sure where this is documented) so installed it with pip. Then worked!

However, not sure why default's Carla app can't see single/multi modes to choose from.

**Comment by falkTX** [comment]
single and multi client modes are for the JACK driver engine option only.
In the settings you likely have "JACK with ALSA MIDI" instead.

**Comment by redraw** [comment]
Oh that was it, right. Thanks falkTX for all the work done!

**Comment by redraw** [comment]
Oh that was it, right. Thanks falkTX for all the work done!
