### ISSUE TITLE
Ingen save bundle with CV port crashes Carla

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#1061]
I've created 4 test projects with audio, CV, control and event, one in port connected directly to one out port.

https://github.com/mxmilkb/ingen-tests

They all load apart from the CV port one which makes Carla [crash](https://gist.github.com/mxmilkb/51420ca6b963ed59dfbe08882c42acf9).

**Comment by falkTX** [comment]
isnt that a crash in ingen?
can you try the same in other hosts please?

**Comment by falkTX** [comment]
I can only assume it is an issue with ingen, and not carla.
If you have proof otherwise, please reopen.
