### ISSUE TITLE
Carla - Plans for a command-line version?

### ISSUE THREAD

**Issue by RobinOpletal** [falkTX/Carla#1071]
Hello, as the GUI is quite resource-hungry even on idle, are there any plans for making a command line interface for Carla?

My setup is start jack with pulseaudio-jack module and then I have to start carla manually just to apply the desired effects for systemwide playback

Thank you for taking this into any consideration :)

**Comment by falkTX** [comment]
There are plans to rework the UI from python to c++, already started on that.
This will reduce CPU usage a lot. and then a systray option as well, which will reduce further.

A full CLI version won't be made by me, since I do not have the use for it and thus most likely will just end up being broken most of the time.
You are free to try to do one yourself though, the API is simple to follow I believe.
See https://kx.studio/ns/dev-docs/CarlaBackend/group__CarlaHostAPI.html

**Comment by RobinOpletal** [comment]
Thank you for the reply :) I am happy to hear about the interface being reworked at this time - right now the Carla process is eating up the most of my system resources on idle, which is a little sad, but acceptable since the app is fantastic and enables me to do this after all.

I will follow the project to see any changes as far as the interface rework goes

Thank you for your work!

**Comment by falkTX** [comment]
Note: You can use `carla -n /path/to/project/file` to start an existing project without GUI.
Then using carla-control you are able to control stuff, to a limited degree, while the main carla still has the UI hidden.

**Comment by RobinOpletal** [comment]
Hi again, clicking the save button here:

**Comment by falkTX** [comment]
huh so file->save menu action does nothing?

**Comment by RobinOpletal** [comment]
Yeah, that doesn't bring up any menu/anything else either

**Comment by eeickmeyer** [comment]
Technically, "Save" should only bring up a GUI if it hasn't been saved before (equivalent to "Save As"). If it has been saved before, "Save" should only save the project that's open.

**Comment by RobinOpletal** [comment]
Right, that makes sense, but the project has never been saved and the option to Save As doesn't appear either.

**Comment by falkTX** [comment]
yeah, that part I dont quite understand.
Only makes sense to be that way if carla is running under session management, like NSM.
But I guess that is not the case here. So I am out of ideas..

**Comment by RobinOpletal** [comment]
Sorry for the late reply, it was under NSM. Now everything is working well. Thank you again for the command for starting carla's project, it's working great for me in a script.

All the best!
