### ISSUE TITLE
mingw32 build has a link failure

### ISSUE THREAD

**Issue by plater** [falkTX/Carla#1072]
I maintain carla for openSUSE and the mingw part of the build fails on symbols exported by mingw's libssp.a. I'm attaching the patch I made, you'll most probably have to add a linux conditional to include it in your sources. I suspect that this is gcc9 related. I have to add txt to the name for the sake of github.
[carla-link-mingw.patch.txt](https://github.com/falkTX/Carla/files/4464764/carla-link-mingw.patch.txt)

**Comment by falkTX** [comment]
What is the error message?

Did you try simply adding `-lssp`? seems a lot cleaner than finding the file like that, because the way the patch is done I can never apply it as-is.

**Comment by plater** [comment]
You're 100% right -lssp works, I'm new to mingw, it obviously has a hardcoded path to it's own libraries.

**Comment by plater** [comment]
[carla-link-mingw.patch.txt](https://github.com/falkTX/Carla/files/4466032/carla-link-mingw.patch.txt)
I made this one from git
