### ISSUE TITLE
Automatic conversion between certain port types

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1075]
So CV->Audio is now disabled by default to save possibly damaging speakers if users have certain kinds of soundcard and there is an internal to convert.

But Audio->CV is also now disabled, though I really don't think there is any danger there. Would it be possible to reenable that? (Even if it's not sampling and changing the control parameter at a true audio-rate?)

MIDI->CV - behind the scenes would use the existing MIDI->CV internal.

CV->MIDI - would be something behaving the same as the infamous envelope follower, i.e., outputs MIDI pitch (or CC).

This videos [Bitwig Grid School 05 - Ports and Precords](https://www.youtube.com/watch?v=bQsdD99OvL4) partially explains the benefit of it from a wider Bitwig context.

**Comment by falkTX** [comment]
I am going to close this as wont-fix, sorry.
is a bit complex to handle behind the scenes, and will make problems if I want to extend carla to support more engine drivers (say haiku mediakit that behaves like JACK).

the frontend can allow such connections perhaps though, by placing a plugin and connecting its ports perhaps..
but that wont happen anytime soon, and likely not by me, so I dont want to give hopes.
