### ISSUE TITLE
Expand "Save Image..." into a submenu with different zoom levels?

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1078]
With entries for "Save at 100% zoom", "Save at 90% zoom", "..80..", etc.

**Comment by falkTX** [comment]
I disagree with saving in less than 100% zoom.
But the rest is pretty easy to add, why not.

**Comment by falkTX** [comment]
Done in 96a914ebca486a5a3039ddf7afcbb09a9395d58f

**Comment by mxmilkiib** [comment]
I guess whatever app is viewing the image can do the scaling :)

Might a "Copy Image To Clipboard.." also be possible?

**Comment by falkTX** [comment]
possible? sure. is it needed? what usecase is there for it?

**Comment by mxmilkiib** [comment]
To paste into sites that accept pastes of images, like GitHub and Discourse.

**Comment by falkTX** [comment]
Makes sense. added in 47acfcfa619947267b209cb9aa5af07c12587914
Use ctrl+shift+c as shortcut

**Comment by mxmilkiib** [comment]
I'm trying to use that and paste to a GitHub issue, and the Write box cursor freezes for a second or two after ctrl-v but nothing else happens.

I can however paste it into a LibreOffice document

**Comment by mxmilkiib** [comment]
Apologies but this needs reopening given the ^ bug.

**Comment by falkTX** [comment]
I guess I can reopen, but I dont know much of what to do here..

**Comment by falkTX** [comment]
I am able to paste image here, so it might depend on filesize.

![image](https://user-images.githubusercontent.com/1334853/90377836-77daac00-e070-11ea-8b27-1dba43184be7.png)

**Comment by falkTX** [comment]
Trying with PNG format...

![image](https://user-images.githubusercontent.com/1334853/90378670-8aa1b080-e071-11ea-9665-616939453170.png)

**Comment by falkTX** [comment]
Now testing writing a super big image....

![image](https://user-images.githubusercontent.com/1334853/90379476-b3767580-e072-11ea-8535-83cc2a321402.png)

**Comment by falkTX** [comment]
Now fixed in develop branch.
With such a big canvas, it can take a bit for the clipboard copy, but at least here I was able to paste it sucessfully.
