### ISSUE TITLE
Timeout on bridged wine plugins

### ISSUE THREAD

**Issue by PrinzNika** [falkTX/Carla#1080]
Im on an Arch based System and I am noticing a difference between the carla package from the official repository and the carla-git version from the AUR

In the git version the bridged plugins timeout really quickly even though they easily run otherwise. I am guessing that it might be a good idea to be able to manually set the time until carla sends that message.

**Comment by terencode** [comment]
I think this is a regression.
If you go to the "logs" tab, do you see something similar to
`wine: cannot find '/usr/lib/carla/carla-bridge-win64.exe` ?

**Comment by PrinzNika** [comment]
`
======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  48000
  Process mode: Multi client
Error opening file /home/nika/.lv2/Synthpod_default.preset.lv2/manifest.ttl (No such file or directory)
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/ryukau/LV2Plugins/tree/master/SevenDelay>
lilv_world_add_plugin(): warning: ... found in file:///home/nika/.lv2/SevenDelay.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/SevenDelay.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/ryukau/LV2Plugins/tree/master/CubicPadSynth>
lilv_world_add_plugin(): warning: ... found in file:///home/nika/.lv2/CubicPadSynth.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/CubicPadSynth.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/ryukau/LV2Plugins/tree/master/EnvelopedSine>
lilv_world_add_plugin(): warning: ... found in file:///home/nika/.lv2/EnvelopedSine.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/EnvelopedSine.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/ryukau/LV2Plugins/tree/master/TrapezoidSynth>
lilv_world_add_plugin(): warning: ... found in file:///home/nika/.lv2/TrapezoidSynth.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/TrapezoidSynth.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/ryukau/LV2Plugins/tree/master/FDNCymbal0.2>
lilv_world_add_plugin(): warning: ... found in file:///home/nika/.lv2/FDNCymbal.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/FDNCymbal.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/ryukau/LV2Plugins/tree/master/IterativeSinCluster>
lilv_world_add_plugin(): warning: ... found in file:///home/nika/.lv2/IterativeSinCluster.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/IterativeSinCluster.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/ryukau/LV2Plugins/tree/master/WaveCymbal>
lilv_world_add_plugin(): warning: ... found in file:///home/nika/.lv2/WaveCymbal.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/WaveCymbal.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/ryukau/LV2Plugins/tree/master/SyncSawSynth>
lilv_world_add_plugin(): warning: ... found in file:///home/nika/.lv2/SyncSawSynth.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/SyncSawSynth.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <https://github.com/ryukau/LV2Plugins/tree/master/EsPhaser>
lilv_world_add_plugin(): warning: ... found in file:///home/nika/.lv2/EsPhaser.lv2/
lilv_world_add_plugin(): warning: ... and      file:///usr/lib/lv2/EsPhaser.lv2/ (ignored)
LV2 plugin 'synthpod.lv2/http://open-music-kontrollers.ch/lv2/synthpod#stereo' requires unsupported feature 'http://lv2plug.in/ns/ext/state#threadSafeRestore'
Carla assertion failure: "apiVersion == CARLA_PLUGIN_BRIDGE_API_VERSION" in file ../backend/engine/CarlaEngineBridge.cpp, line 178

Carla assertion failure: "maxPluginNumber == 0" in file ../backend/engine/CarlaEngineInternal.cpp, line 409

Carla assertion failure: "nextPluginId == 0" in file ../backend/engine/CarlaEngineInternal.cpp, line 410

Carla assertion failure: "in == nullptr" in file ../backend/engine/CarlaEngineInternal.cpp, line 41

Carla assertion failure: "out == nullptr" in file ../backend/engine/CarlaEngineInternal.cpp, line 42

Carla assertion failure: "! isThreadRunning()" in file ../utils/CarlaThread.hpp, line 54

Failed to init engine, error was:


`

**Comment by PrinzNika** [comment]
oops i should also delete the duplicated plugins

**Comment by PrinzNika** [comment]
[](======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  48000
  Process mode: Multi client
LV2 plugin 'synthpod.lv2/http://open-music-kontrollers.ch/lv2/synthpod#stereo' requires unsupported feature 'http://lv2plug.in/ns/ext/state#threadSafeRestore'
Carla assertion failure: "apiVersion == CARLA_PLUGIN_BRIDGE_API_VERSION" in file ../backend/engine/CarlaEngineBridge.cpp, line 178

Carla assertion failure: "maxPluginNumber == 0" in file ../backend/engine/CarlaEngineInternal.cpp, line 409

Carla assertion failure: "nextPluginId == 0" in file ../backend/engine/CarlaEngineInternal.cpp, line 410

Carla assertion failure: "in == nullptr" in file ../backend/engine/CarlaEngineInternal.cpp, line 41

Carla assertion failure: "out == nullptr" in file ../backend/engine/CarlaEngineInternal.cpp, line 42

Carla assertion failure: "! isThreadRunning()" in file ../utils/CarlaThread.hpp, line 54

Failed to init engine, error was:



carla_engine_close: Engine is not initialized
)

**Comment by falkTX** [comment]
The versions of the bridges need to match the one of the main carla.
This is why it errors out. Old Carla can work with old bridges, but new bridges cannot work with old carla.
Just update everything to 2.1 which has just been tagged a few days ago and it will work again

**Comment by PrinzNika** [comment]
where can i find the 2.1 carla bridges? In the AUR is only up to version 2.0

**Comment by falkTX** [comment]
Ask the package maintainer to update them
Should be just bumping a number, so it is not a lot of work

**Comment by PrinzNika** [comment]
could i also edit the package build manually? I tried to set pkgver to 2.1 and to achieve it also changed the version name in source to  `{_mirror}/ubuntu/pool/universe/c/carla/carla-bridge-linux32_2.1.0-${_ubuntupkg}_i386.deb` but that gave me an error...

ill definetly comment on the aur page but i am scared to wait as the package hasnt been updated in a loong while

**Comment by PrinzNika** [comment]
however if they change it im guessing that it will break the functionality with upstream Carla which is still in 2.0

**Comment by falkTX** [comment]
Carla is now 2.1, that is the "upstream".

**Comment by PrinzNika** [comment]
oh sorry i didnt check that. I thought it was still in 2.0 as unlike the git version it doesnt show the dsp load and the plugin manager looks different, too.
Anyways I hope that the maintainers will change the bridge versoins soon.

Until then is there another way to get them?

**Comment by falkTX** [comment]
you can use the linux binaries in this repo's releases tab
