### ISSUE TITLE
no audio output of VST3-instruments

### ISSUE THREAD

**Issue by ShantySuffisance** [falkTX/Carla#1084]
I use Carla 2.096 on Win 10 (home, version 2004) and love it! 

All VST3-instruments, that i tried lack audio output! 

![vst3 not working 2](https://user-images.githubusercontent.com/63818756/79506284-fa594d80-8035-11ea-8fbd-de1999ded546.png)

I tried: 
Helm v0.9.0 by Matt Tytel
OB-Xd v1.5 by discodsp
Tunefish4 v4.2.0 by Brain Control 

any ideas, what i could try to have audio output? thx!

**Comment by falkTX** [comment]
Please use the final 2.1 release.

Did you try non-VST3 plugins? Do VST2 versions work?

**Comment by ShantySuffisance** [comment]
i updated to 2.1 but the problems remain the same...

every VST2-plugin or LV2-plugin works fine!

**Comment by alex-tee** [comment]
i have the same problem too. carla discovery reports 0 audio outs for Helm.vst3 for example. I think it's a discovery problem

**Comment by alex-tee** [comment]
also related, surge vst2 returns 0 midi ins:
```
carla-discovery-win32.exe vst "C:\Program Files (x86)\Common Files\VST2\Surge_x86.dll"

carla-discovery::init::-----------

carla-discovery::build::3

carla-discovery::hints::12

carla-discovery::name::Surge

carla-discovery::label::Surge_x86

carla-discovery::maker::Vember Audio

carla-discovery::uniqueId::1667920691

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::664

carla-discovery::end::------------
```

```
carla-discovery-native.exe vst "C:/Program Files/Common Files/VST2/Surge.dll" 
carla-discovery::init::-----------

carla-discovery::build::4

carla-discovery::hints::12

carla-discovery::name::Surge

carla-discovery::label::Surge

carla-discovery::maker::Vember Audio

carla-discovery::uniqueId::1667920691

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::664

carla-discovery::end::------------
```

VST3 reports the midi ins:
```
carla-discovery-native.exe vst3 "C:/Program Files/Common Files/VST3/Surge.vst3"

carla-discovery::init::-----------

carla-discovery::build::4

carla-discovery::hints::12

carla-discovery::name::Surge

carla-discovery::label::Surge

carla-discovery::maker::Vember Audio

carla-discovery::uniqueId::218443882

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::midi.ins::1

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::664

carla-discovery::end::------------
```

this could be a  problem with the surge vst2 release. I seem to have more problems with the vst3 discovery in general though, here are a few weird examples:

```
/mingw64/lib/carla/carla-discovery-native.exe vst3 /c/Program\ Files/Common\ Files/VST3/TAL-Reverb-2-64.vst3

carla-discovery::init::-----------

carla-discovery::build::4

carla-discovery::hints::8

carla-discovery::name::TAL-Reverb-2

carla-discovery::label::TAL-Reverb-2

carla-discovery::maker::TAL-Togu Audio Line

carla-discovery::uniqueId::1564699108

carla-discovery::audio.ins::0 // no audio

carla-discovery::audio.outs::0 // no audio

carla-discovery::midi.ins::0

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::15

carla-discovery::end::------------
```

```
/mingw64/lib/carla/carla-discovery-native.exe vst3 /c/Program\ Files/Common\ Files/VST3/Helm/helm64.vst3

carla-discovery::init::-----------

carla-discovery::build::4

carla-discovery::hints::12

carla-discovery::name::Helm

carla-discovery::label::Helm

carla-discovery::maker::Matt Tytel

carla-discovery::uniqueId::-1425063097

carla-discovery::audio.ins::0

carla-discovery::audio.outs::0 // no audio

carla-discovery::midi.ins::1

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::2221

carla-discovery::end::------------
```

**Comment by ShantySuffisance** [comment]
> also related, surge vst2 returns 0 midi ins:
> 
> ```
> carla-discovery-win32.exe vst "C:\Program Files (x86)\Common Files\VST2\Surge_x86.dll"
> 
> carla-discovery::init::-----------
> 
> carla-discovery::build::3
> 
> carla-discovery::hints::12
> 
> carla-discovery::name::Surge
> 
> carla-discovery::label::Surge_x86
> 
> carla-discovery::maker::Vember Audio
> 
> carla-discovery::uniqueId::1667920691
> 
> carla-discovery::audio.ins::2
> 
> carla-discovery::audio.outs::2
> 
> carla-discovery::midi.ins::0
> 
> carla-discovery::midi.outs::0
> 
> carla-discovery::parameters.ins::664
> 
> carla-discovery::end::------------
> ```
> 
> ```
> carla-discovery-native.exe vst "C:/Program Files/Common Files/VST2/Surge.dll" 
> carla-discovery::init::-----------
> 
> carla-discovery::build::4
> 
> carla-discovery::hints::12
> 
> carla-discovery::name::Surge
> 
> carla-discovery::label::Surge
> 
> carla-discovery::maker::Vember Audio
> 
> carla-discovery::uniqueId::1667920691
> 
> carla-discovery::audio.ins::2
> 
> carla-discovery::audio.outs::2
> 
> carla-discovery::midi.ins::0
> 
> carla-discovery::midi.outs::0
> 
> carla-discovery::parameters.ins::664
> 
> carla-discovery::end::------------
> ```
> 
> VST3 reports the midi ins:
> 
> ```
> carla-discovery-native.exe vst3 "C:/Program Files/Common Files/VST3/Surge.vst3"
> 
> carla-discovery::init::-----------
> 
> carla-discovery::build::4
> 
> carla-discovery::hints::12
> 
> carla-discovery::name::Surge
> 
> carla-discovery::label::Surge
> 
> carla-discovery::maker::Vember Audio
> 
> carla-discovery::uniqueId::218443882
> 
> carla-discovery::audio.ins::2
> 
> carla-discovery::audio.outs::2
> 
> carla-discovery::midi.ins::1
> 
> carla-discovery::midi.outs::0
> 
> carla-discovery::parameters.ins::664
> 
> carla-discovery::end::------------
> ```
> 
> this could be a problem with the surge vst2 release. I seem to have more problems with the vst3 discovery in general though, here are a few weird examples:
> 
> ```
> /mingw64/lib/carla/carla-discovery-native.exe vst3 /c/Program\ Files/Common\ Files/VST3/TAL-Reverb-2-64.vst3
> 
> carla-discovery::init::-----------
> 
> carla-discovery::build::4
> 
> carla-discovery::hints::8
> 
> carla-discovery::name::TAL-Reverb-2
> 
> carla-discovery::label::TAL-Reverb-2
> 
> carla-discovery::maker::TAL-Togu Audio Line
> 
> carla-discovery::uniqueId::1564699108
> 
> carla-discovery::audio.ins::0 // no audio
> 
> carla-discovery::audio.outs::0 // no audio
> 
> carla-discovery::midi.ins::0
> 
> carla-discovery::midi.outs::0
> 
> carla-discovery::parameters.ins::15
> 
> carla-discovery::end::------------
> ```
> 
> ```
> /mingw64/lib/carla/carla-discovery-native.exe vst3 /c/Program\ Files/Common\ Files/VST3/Helm/helm64.vst3
> 
> carla-discovery::init::-----------
> 
> carla-discovery::build::4
> 
> carla-discovery::hints::12
> 
> carla-discovery::name::Helm
> 
> carla-discovery::label::Helm
> 
> carla-discovery::maker::Matt Tytel
> 
> carla-discovery::uniqueId::-1425063097
> 
> carla-discovery::audio.ins::0
> 
> carla-discovery::audio.outs::0 // no audio
> 
> carla-discovery::midi.ins::1
> 
> carla-discovery::midi.outs::0
> 
> carla-discovery::parameters.ins::2221
> 
> carla-discovery::end::------------
> ```

thats strange, cause i have **one midi-in** for vst2-surge... and the other also work in vst2

**Comment by falkTX** [comment]
can you try the carla-discovery-win64.exe that comes inside this archive?
https://launchpad.net/~kxstudio-debian/+archive/ubuntu/apps/+files/carla-bridge-win64_2.1+git20200422.3_amd64.deb

(extract contents, then data.tar.xz, then find it in usr/lib/carla)

That one has an updated JUCE and VST3 SDK, which might make the difference here.

**Comment by alex-tee** [comment]
that gives me the same results. maybe it's the plugin's fault

**Comment by falkTX** [comment]
@alex-tee can you try this again with latest git?
I loaded a vst3 I had here and it correctly shows its audio outputs.

![Screenshot_20200511_182414](https://user-images.githubusercontent.com/1334853/81591642-a4699280-93b4-11ea-8b95-d9a660819682.png)
