### ISSUE TITLE
Could not connect to Audio backend 'JACK'

### ISSUE THREAD

**Issue by frcl** [falkTX/Carla#1087]
Hi,
yesterday I switched from Carla 2.0.0 to 2.1 and after that the following message appears every time I try to start Carla

> Could not connect to Audio backend 'JACK', possible reasons: Failed to create new JACK client

After downgrading to Carla 2.0.0 everything works as expected. Any Idea what could be the reason for this?

Im on Archlinux. Jack version is 1.9.14.

**Comment by falkTX** [comment]
No ideas here, I was hoping someone (also using ArchLinux) would chime-in with a "hey, I also have this issue"

You still have the issue I guess..?
Did you find any information about it?

**Comment by manjaroman2** [comment]
Same issue here

**Comment by falkTX** [comment]
things have changed a lot since then, pipewire is a thing now.
that is likely the issue, something missing or misconfigured.

**Comment by falkTX** [comment]
no worries. closing ticket then.

**Comment by pablodz** [comment]
![image](https://github.com/falkTX/Carla/assets/28235457/2e72db22-b818-4e1e-bb2d-dabd54f5138b)

sad

**Comment by jperier** [comment]
Hello, I had the same problem on arch as well. It was solved for me by installing the `pipewire-jack` package and restarting carla.
