### ISSUE TITLE
Incorrect MIDI CC port base conversion

### ISSUE THREAD

**Issue by gnif** [falkTX/Carla#1088]
It seems there is a base conversion issue when sending CC 0x10 Carla ignores it for parameter automation unless you select Midi Control 10 (0xA).

This can also be seen as when 0x10 is selected the grey text at the top of the context menu states it's on control 22 and not 16 decimal.

**Comment by gnif** [comment]
The following line looks to be the culprit.

https://github.com/falkTX/Carla/blob/ce0cac7d62339eef45742ee3d7bc4476736416b5/source/frontend/carla_widgets.py#L391

This is picking up the decimal number and treating it as base 16

**Comment by falkTX** [comment]
I thought this was fixed already in ce0cac7d62339eef45742ee3d7bc4476736416b5

**Comment by gnif** [comment]
I didn't see that change, but even still it's incomplete as it's only dealing with the displayed number, not the selected number

**Comment by IanCaio** [comment]
It happens here as well on the latest github release. The displayed numbers are fine, but selecting control channel `16 [0x10] General Purpose 1`, for example, maps the parameter to control 22
