### ISSUE TITLE
Unexpected connections 

### ISSUE THREAD

**Issue by manucontrovento** [falkTX/Carla#1092]
Hi everyone!

When loading my Carla session, with SuperBoucle and AMSynth, I would expect Carla to connect what I saved, which is:

AMSynth audio outputs to a ZAM reverb inputs
ZAM reverb outputs to System

But when opening Carla loading my script by command line, it always connects AMSynth also to main system outputs, in addiction to ZAM reverb inputs

Actually, it's not SuperBoucle properly, but SpinTool which is my application, forked from SuperBoucle.

in addiction, my midi device is connected too (akai apc key 25), running with a2jmidid

to give it a try, you could download my SpinTool application:
[https://github.com/manucontrovento/SpinTool/releases](https://github.com/manucontrovento/SpinTool/releases)
then you need AMSynth and I attach my starting script to this issue.
thanks!

[all_the_stuff.zip](https://github.com/falkTX/Carla/files/4500400/all_the_stuff.zip)

**Comment by falkTX** [comment]
in the project file I do not see amsynth there, so I guess it is something running externally.
likely it is just connecting itself to the system output.
run amsynth as a plugin in carla, and all will be fine.

PS: Carla will only connect new things when loading a project, it will never disconnect.
