### ISSUE TITLE
Carla v2.1 multichannel plugin only have 1 in and 1 out in the patch

### ISSUE THREAD

**Issue by michemiche73** [falkTX/Carla#1093]
Hello. when i load multichannel vst plug in the patch i have only 1 in and 1 out audio.
In the previous version if the plug in was stereo I had 2 in and 2 out now no longer.
Can you help me?

**Comment by falkTX** [comment]
which plugin is this? and what format, is it vst3 perhaps?

**Comment by falkTX** [comment]
hello?

**Comment by katta07** [comment]
I have the same problem with Marvel GEQ plugin on windows.
![version 2.0.0](https://user-images.githubusercontent.com/16972885/80588175-826d2900-8a20-11ea-81ba-fe7822091cb3.JPG)
![version 2.1](https://user-images.githubusercontent.com/16972885/80588179-8436ec80-8a20-11ea-9c1c-1bd6628eb8c4.JPG)

**Comment by katta07** [comment]
I don't know if is the same problem. For Marvel GEQ plugin, in carla 2.0.0 I have 8 input/outputs, but in carla 2.1 I have only one.

![old](https://user-images.githubusercontent.com/16972885/80589086-36bb7f00-8a22-11ea-872d-1ef086ea3b9e.JPG)
![new](https://user-images.githubusercontent.com/16972885/80589092-38854280-8a22-11ea-9d01-678d51490cc0.JPG)

**Comment by michemiche73** [comment]
Yes is the same problem Michele Vicentimichelevicenti73@gmail.com Da: katta07Inviato: mercoledì 29 aprile 2020 13:03A: falkTX/CarlaCc: michemiche73; AuthorOggetto: Re: [falkTX/Carla] Carla v2.1 multichannel plugin only have 1 in and 1 out in the patch (#1093) I don't know if is the same problem. For Marvel GEQ plugin, in carla 2.0.0 I have 8 input/outputs, but in carla 2.1 I have only one.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by falkTX** [comment]
This is fixed by 0ebb8d86b2729e0ce24b15c2bfd942bf0e9e15d4

I will do a v2.2 release somewhat soon, need to see what other issues are there to fix.
For now, I believe the VST2 version of these plugins works correctly.

If not let me know, I can do some early builds.
Maybe I should setup some nightly builds or something hmm

**Comment by michemiche73** [comment]
Thanks!

I think Carla is a good product

Michele Vicenti
michelevicenti73@gmail.com

Il giorno 14 mag 2020, alle ore 03:29, Filipe Coelho <notifications@github.com> ha scritto:

﻿
This is fixed by 0ebb8d8

I will do a v2.2 release somewhat soon, need to see what other issues are there to fix.
For now, I believe the VST2 version of these plugins works correctly.

If not let me know, I can do some early builds.
Maybe I should setup some nightly builds or something hmm

**Comment by falkTX** [comment]
For those running Windows, I made an early build https://github.com/falkTX/Carla/releases/download/v2.2b1/Carla_2.2b1-win64.zip
