### ISSUE TITLE
Windows VST Stereo Plugins listed as Mono

### ISSUE THREAD

**Issue by rolodoom** [falkTX/Carla#1106]
Hello there. I'm testing on the Carla  2.1.0 and I've notice that some Windows VST Stereo plugins are now identified as mono.

I'm testing the on Ubuntu 20 package.  This didn't happen before on the 19.10 package - Carla version 2.0. I don't know where to start looking for the solution. Any help would be appreciated.

Thanks.

BEFORE on Carla 2.0 on Ubuntu 19.10:
![Screenshot_20200427_152329](https://user-images.githubusercontent.com/61945227/80424371-35197c00-88a7-11ea-8c4d-988c3e411719.png)

NOW on Carla 2.1 on Ubuntu 20.04 LTS:

![Screenshot_20200427_152328](https://user-images.githubusercontent.com/61945227/80424210-db18b680-88a6-11ea-8af1-577706b0c7e0.png)

**Comment by katta07** [comment]
I have the same problem.

**Comment by falkTX** [comment]
We need to go on a plugin by plugin basis.
Which one do you have where you see this issue?

btw, if you have the kxstudio repos enabled, the carla-git package has updated carla builds.
this might be fixed already in there.

In any case, knowing a plugin to check is a good first step.
Thanks.

**Comment by rolodoom** [comment]
Hello! Here is more information:
Plugin: EZ Mix 2.1.1 64bit VST
KXRepos: Nop, I'm using Carla from Ubuntu 20.04 repositories, sorry but never had used KX before. I check on same PC with Ubuntu 19.10 and there is no problem there. The problem seem to be present on the Carla 2.1 version from Ubuntu 20LTS Repository.

Hope this info helps.

Thanks!!
