### ISSUE TITLE
(bug)  Linuxsampler instancing

### ISSUE THREAD

**Issue by Qualitymix** [falkTX/Carla#111]
When using Carla as a host for linuxsampler, it uses much more resources to host instruments than using linuxsampler plugin with QSampler frontend.

**Comment by nicopan** [comment]
Hi, I made a test with three .SFZ.
I loaded the first 2 files in Fantasia (2.1GB of .wav) and the RAM usage increased: +19MB.
In Carla the RAM increased +62MB.
The third file (440MB of .wav) was +35MB on Fantasia and +59MB on Carla.
Hope it helps, bye!

**Comment by falkTX** [comment]
I don't think the numbers are that different right now.
linuxsampler by being a gui-less CLI app will of course use less RAM.

I did what was possible to get the memory usage as lower as possible via code.
Unless there's still a big memory usage (say 2x more) when compared to CLI linuxsampler, I consider this bug fixed.
(Note that the kxstudio repository packages are not updated to the new code yet)
