### ISSUE TITLE
Save states only work on certain effects?

### ISSUE THREAD

**Issue by Aktzin03** [falkTX/Carla#1117]
Hello, I am using this program as a host for my microphone settings as it works pretty well with pretty much everything. However, I am having problems with getting a couple of plugins to save correctly. I am currently using Reaplugs and for some reason, reacomp and reagate are not cooperating. Strangely, these two plugins are also listed as mono, while everything else I use is stereo. I am on the latest build of Carla, windows version, and I am using a RnNoise vst plugin, reafir, and reaeq in addition to the reacomp and reagate. Any help would be appreciated.

Edit: I am currently finding a workaround to this by using other plugins that don't have this problem. I would still like an explanation to this problem though.

**Comment by falkTX** [comment]
How are you running Carla?
Is this with the 2.1 version for windows? (so you are not running linux with wine, right?)

**Comment by Aktzin03** [comment]
2.1 version of Carla on windows. After testing a couple of other vst plugins, I encountered the same problem. The ones Carla recognized as stereo saved my adjustments while the plugins Carla thought were mono didn’t save them. I did find alternate plugins, but I would like to fix this if it’s a problem with the program.

**Comment by RMCholewa** [comment]
I am getting the same thing here. I also use Carla for vocals. Carla 2.1 on W10 running as administrator. Some reaplugs do not save state, like reacomp. LoudMax is also not being saved,

**Comment by falkTX** [comment]
This might be fixed in 2.2-RC1 release, please confirm!
Pre-built binaries at https://github.com/falkTX/Carla/releases/tag/v2.2.0-RC1

**Comment by RMCholewa** [comment]
Just tested 2.2-RC1.

I could not open the file saved by 2.1. It crashes. Then I started a clean canvas.

I have 2 VST plugins that were not getting their states saved: loudmax and reacomp.

Tried adding loudmax, ok.

Added reacomp, ok.

Saved the canvas, closed carla, reopened it.

Opened the new saved canvas.

States for reacomp and loudmax were saved and properly loaded.

Notes:

When I tried loading the reaeq plugin, Carla rc1 crashes.

**Comment by Aktzin03** [comment]
> Just tested 2.2-RC1.
> 
> I could not open the file saved by 2.1. It crashes. Then I started a clean canvas.

> States for reacomp and loudmax were saved and properly loaded.

I tested reagate and reacomp. Save states were definitely working properly, but old project files would not load. Not much of an issue, as it's easy enough to rebuild the project file. Maybe something to look in to? Anyway, thanks for the fix. I will close this issue as the new problem is not related to this thread.
