### ISSUE TITLE
Problems Loading Bridged Windows VSTs

### ISSUE THREAD

**Issue by gmslater** [falkTX/Carla#1130]
Recently updated to Ubuntu 20.04. Carla version is 5:2.1.0. Wine/WineASIO version is 5.0.

Carla will not load any Windows VSTs. If a saved setting that contains both Linux and Windows plugins is opened, the Linux ones will load normally, but the Windows ones will not. When attempting to load a Windows VST by itself, the following error occurs:

![Carla_error](https://user-images.githubusercontent.com/65368204/81981437-88046a80-95ed-11ea-8d9f-2f781abcc5b2.png)

If I run a terminal command such as:
`/usr/bin/carla-single win32 vst "~/vst/Zebra/Zebra2.dll"`
the VST will open normally. I can also run multiple terminal sessions to open additional VSTs, then open Carla, and they all show up on the patchbay, so I can route everything properly, but this is a huge PITA.

One other note, until updating to 20.04, if I opened Windows VSTs in a separate host, like Nano Host, they would show up on the Carla patchbay (and Catia), but now they do not.

**Comment by falkTX** [comment]
You say carla is at version `5:2.1.0`, so I guess this is from the kxstudio repos, right?
Can you try installing `carla-git` and see if it makes any difference?
Thanks

Also, would be useful to get the carla logs, so I have some information to go by about the error.

Final question, do you have Z: mapped to `/` in your wine settings? Carla needs that.

**Comment by gmslater** [comment]
As an experiment, I launched Carla using the executable version from: https://github.com/falkTX/Carla/releases/download/v2.1/Carla_2.1-linux64.tar.xz and it worked perfectly. Windows VSTs load, both individually, and as part of a prior saved setting. I am a very happy camper now!

Let me know if you still want any logs. Also, to answer you last question, yes Z: is mapped to / in wine.

**Comment by falkTX** [comment]
Well, would be best to actually solve this...

So yeah, see if carla-git works for you please.

**Comment by gmslater** [comment]
Will do and let you know (probably tomorrow).

**Comment by gmslater** [comment]
@falkTX - I tested installing carla-git and it did not work for me (details below)

Running `make` - No errors reported.

Running `./source/frontend/carla` - The program opened, but when I attempted to launch a Windows VST, I got an error that the build does not support the selected file format. Next, attempting to scan for plugins, I noticed that the options for Windows 32bit and Windows 64bit were both disabled.

Running `sudo make install` - No errors reported. I checked the various directories and found that the new expected new files were installed. The program opened, but when I attempted to launch a Windows VST, I got an error that this build does not support the selected file format. Next, attempting to scan for plugins, I noticed that the options for Windows 32bit and Windows 64bit were both disabled.

As reported before, the executable version from: https://github.com/falkTX/Carla/releases/download/v2.1/Carla_2.1-linux64.tar.xz works perfectly, and I am VERY happy with it. Question: since this build is self-contained in one directory, it seems like it would be a natural candidate for an Ubuntu snap. Are you planning on creating such a release? Just curious.

**Comment by falkTX** [comment]
if building locally you and needing bridges, you need to build the bridges too.
I asked about the kxstudio repos, since you mentioned 5:2.1.0 version.
but anyway, whatever, if you are happy with the self-contained binary all is fine.

Carla cant be available as snap or flatpak, since they use a sandbox, which is incompatible with JACK.
