### ISSUE TITLE
compilation problem on arch ppc64le

### ISSUE THREAD

**Issue by martinkg** [falkTX/Carla#1131]
Hi,

I'am trying to compile Carla on Fedora for arch ppc64le, but this fails [] with the following error message:

`make[1]: Entering directory '/builddir/build/BUILD/Carla-f100892fbd0b10a7fdac91f1194378247f4633b5/source/bridges-plugin'
Linking carla-bridge-lv2.so
/usr/bin/ld: ../../build/modules/Release/juce_graphics.a(juce_graphics.cpp.o): in function `juce::pnglibNamespace::png_read_filter_row(juce::pnglibNamespace::png_struct_def*, juce::pnglibNamespace::png_row_info_struct*, unsigned char*, unsigned char const*, int) [clone .part.0]':
/builddir/build/BUILD/Carla-f100892fbd0b10a7fdac91f1194378247f4633b5/source/modules/juce_graphics/image_formats/pnglib/pngrutil.c:4126: undefined reference to `juce::pnglibNamespace::png_init_filter_functions_vsx(juce::pnglibNamespace::png_struct_def*, unsigned int)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:266: ../../bin/carla-bridge-lv2.so] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/Carla-f100892fbd0b10a7fdac91f1194378247f4633b5/source/bridges-plugin'
make[1]: *** Waiting for unfinished jobs....
make[1]: Entering directory '/builddir/build/BUILD/Carla-f100892fbd0b10a7fdac91f1194378247f4633b5/source/bridges-plugin'
Linking carla-bridge-native
/usr/bin/ld: ../../build/modules/Release/juce_graphics.a(juce_graphics.cpp.o): in function `juce::pnglibNamespace::png_read_filter_row(juce::pnglibNamespace::png_struct_def*, juce::pnglibNamespace::png_row_info_struct*, unsigned char*, unsigned char const*, int) [clone .part.0]':
/builddir/build/BUILD/Carla-f100892fbd0b10a7fdac91f1194378247f4633b5/source/modules/juce_graphics/image_formats/pnglib/pngrutil.c:4126: undefined reference to `juce::pnglibNamespace::png_init_filter_functions_vsx(juce::pnglibNamespace::png_struct_def*, unsigned int)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:261: ../../bin/carla-bridge-native] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/Carla-f100892fbd0b10a7fdac91f1194378247f4633b5/source/bridges-plugin'
make: *** [Makefile:165: bridges-plugin] Error 2`

[1] https://kojipkgs.fedoraproject.org//work/tasks/6062/44516062/build.log

How can i solve the problem ?

**Comment by falkTX** [comment]
Seems juce is broken on ppc, likely unsupported by them.
We can just disable juce on those platforms. On Linux, it is only needed for VST3, but VST3 does not support PPC anyway, so...

Should be fixed with 6fb2785918c7f25e53d2caee848f37bc1f604245
Let me know how it goes.

**Comment by martinkg** [comment]
many thanks,fixed now.
