### ISSUE TITLE
Carla 2.1 and 2.1RC fail to start. 2.0 OK.

### ISSUE THREAD

**Issue by therealkitman** [falkTX/Carla#1133]
Hi,
I know this may be a rehash of #1008 but I'm a bit confused. I am using the precompiled linux 64bit of 2.0, 2.1RC and 2.1 version and my distro has QT5 version 5.9
While version 2.0 works fine, the two 2.1 versions fail to open with the following - 

> chris@asus-roc:/data/chris/AudioSoftware/Carla_2.1-linux64> ./Carla
Carla self-contained executable 2.0.97 (2.1-RC2), based on UnZipSFX.
Launching: '/tmp/carla-2.1/carla'
Traceback (most recent call last):
  File "./lib/__startup__.py", line 40, in run
  File "./lib/Console.py", line 23, in run
  File "source/frontend/carla", line 22, in <module>
  File "./lib/carla_host.py", line 30, in <module>
ImportError: /usr/lib64/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /tmp/carla-2.1/lib/PyQt5/QtCore.so)
chris@asus-roc:/data/chris/AudioSoftware/Carla_2.1-linux64>

I did a bit of googling on the private api issue and found [this](https://unix.stackexchange.com/questions/576599/version-qt-5-private-api-not-found) which lead to to check this -

>chris@asus-roc:/data/chris/AudioSoftware/Carla_2.1-RC2-linux64> strings -d /usr/lib64/libQt5Quick.so.5 | grep Qt.*API
Qt_5.9.7_PRIVATE_API
chris@asus-roc:/data/chris/AudioSoftware/Carla_2.1-RC2-linux64>

I'm no expert in compiling but have the 2.1 versions been built correctly? Staying with version 2.0 for now.

Regards...

**Comment by falkTX** [comment]
2.0 used Qt4, 2.1 onwards will use Qt5.

I build Carla with Qt 5.9.7, I could decrease this to 5.9.0.
What exact version of Qt5 do you have installed?

**Comment by therealkitman** [comment]
I'm running Qt5.9.7 too.

**Comment by falkTX** [comment]
This is tricky..
What linux distro are you using?

**Comment by therealkitman** [comment]
I have openSUSE leap 15.1

**Comment by geekositalia** [comment]
> I have openSUSE leap 15.1
> 
> Dumb question but since I have both qt4 and qt5 installed, is there some symlink I need to update so that applications prefer qt5 over qt4?

i, you find carla 2.1 on our opensuse leap repository for Digital Audio Workstation, geekodaw

**Comment by therealkitman** [comment]
Thanks @geekositalia , I had forgotten about the repos. I installed Carla 2.1.0 via the multimedia:apps repo (maintainer edogawa@aon.at) That works for me!!

@falkTX - I'll close this as I can proceed forward. By the way, what's the time frame from moving away from python to C++?

Thanks.

**Comment by falkTX** [comment]
is this supposed to be closed or open!? :D

I dont have an ETA for the UI language conversion yet. I started it, but it is going to take some time, as I am not rushing or stressing myself about it. It is not critical by any means.

**Comment by therealkitman** [comment]
Hm, I may have spoken too early. The wine/plugin bridges for this repo version of Carla seem borked. I can't load any VSTs.

![image](https://user-images.githubusercontent.com/14888092/82389094-d55d5d80-9a6d-11ea-847f-f2d754925bc1.png)
![image](https://user-images.githubusercontent.com/14888092/82389113-e3ab7980-9a6d-11ea-9d86-0da0b7505c15.png)

**Comment by therealkitman** [comment]
@falkTX  - sorry, the first closure was due to my cold hands clicking the wrong button :)

I did close it a second time (deliberately) after my reply to @geekositalia thinking it was resolved. But now I seem to remember why I preferred your binaries over any repos. I tried to compile carla myself a few years ago and had issues with the bridges.

I'm going to stay with the V2.0 version for now and leave this as an open issue.

**Comment by falkTX** [comment]
I guess fedora does not package the bridges, that is fine.
you can copy the exe and dll files in the lv2 plugin of carla 2.1 into /usr/lib64/carla/ and then you will have the bridges with the fedora package :)

**Comment by therealkitman** [comment]
> you can copy the exe and dll files in the lv2 plugin of carla 2.1

yes, that worked! :) I now have a functioning Carla 2.1.0 from the repo using the bridges from your precompiled binary zip.

Is there some licensing issue with not packaging those bridges in the repos or should I bring this to the maintainers attention?

Regarding the original QT5 issue with your precompiled binary version 2.1 - do you want me to keep this issue open or shall we call this 'resolved'?

**Comment by falkTX** [comment]
> Is there some licensing issue with not packaging those bridges in the repos or should I bring this to the maintainers attention?

no, just more complications for a feature that is not essential.



> Regarding the original QT5 issue with your precompiled binary version 2.1 - do you want me to keep this issue open or shall we call this 'resolved'?

whatever you prefer. if you are fine with the current solution, then seems fine to close it.

**Comment by therealkitman** [comment]
>  just more complications for a feature that is not essential

Well that confuses me. Using these to get Windows VSTs running under Linux I would deem essential. Or have I missed a different method/technique?

Regardless, closing this issue....with thanks :)

**Comment by falkTX** [comment]
> > just more complications for a feature that is not essential
> 
> Well that confuses me. Using these to get Windows VSTs running under Linux I would deem essential. Or have I missed a different method/technique?

Can be a matter of opinion.
We have a LOT of Linux plugins now, for example https://kx.studio/Repositories:Plugins and http://linux-sound.org/linux-vst-plugins.html
It is best to try to go native and leave behind Windows stuff, because it is simply never going to be as reliable as native.

**Comment by KottV** [comment]
@therealkitman there is Carla from git/develop packages with all bridges  https://software.opensuse.org//download.html?project=home%3Akill_it&package=carla

**Comment by geekositalia** [comment]
> Hm, I may have spoken too early. The wine/plugin bridges for this repo version of Carla seem borked. I can't load any VSTs.
> 
> ![image](https://user-images.githubusercontent.com/14888092/82389094-d55d5d80-9a6d-11ea-847f-f2d754925bc1.png)
> ![image](https://user-images.githubusercontent.com/14888092/82389113-e3ab7980-9a6d-11ea-9d86-0da0b7505c15.png)

Hi, our repo has bridge, multimedia:apps dont have mingw officialy, required for wine bridge! On geekosdaw repo bridge is compiled and it will be installed by carla-bridge :)
