### ISSUE TITLE
red zeppelin drumkit plugin lv2 no gui

### ISSUE THREAD

**Issue by marcscama** [falkTX/Carla#1134]
hello,
when i lunch the plugin no gui window start:

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x3200003
  Serial number of failed request:  28
  Current serial number in output stream:  28
CarlaPipeCommon::_writeMsgBuffer(..., 5) - failed with -1 (true), message was:
atom.

Optional 1:
in the description of the file carla installation in Synaptic i read that there are 2 carla version. i installed the normal one. The carla-bridge-linux64 say in the description:
"This package provides the linux64 bridge for loading 64bit Linux plugins".
What is this package? Is it normal 64bit or you mean 32bit?

Optional 2:
in Cadence under configure/engine realtime priority the default setting is 10.
Which paramaters i need to use? 99 is too high?

Optional 3:
in Carla  what is the OSC in the config settings? I need this?

Best regards
Marks

**Comment by falkTX** [comment]
This has been fixed already, turns out the x11 child window is not always valid.
Not sure in which release now, but any recent 2.2 will do.
