### ISSUE TITLE
System output node position lost (nee 'All nodes squished together on start')

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1139]
![image](https://user-images.githubusercontent.com/108225/82334182-8b2d9b00-99df-11ea-8d7a-4182563e9758.png)

**Comment by mxmilkiib** [comment]
I just started the boom2 project from cli and it looked like this after it had finished loading;

![image](https://user-images.githubusercontent.com/108225/82345304-06e21480-99ed-11ea-90b5-ac6f81976332.png)

**Comment by falkTX** [comment]
This is a work-in-progress, I am still changing stuff.
specially loading projects from different sources, like an internal patchbay to a multi-client jack project.
Carla used to load positions based on where they were last used, but this leads to some items seemingly appearing at "random" places.

**Comment by falkTX** [comment]
ping. has this happened again recently?

**Comment by SpotlightKid** [comment]
Happens here fairly often. Can't establish a pattern yet, though. Carla compiled from git via `carla-git` AUR package.

**Comment by falkTX** [comment]
This will happen for new JACK sessions where no value has been set on the "system" client yet.

**Comment by Skrappjaw** [comment]
I have issue with this as well. Plus, I use pacmd to create a handful of bridges between jack/pulse. Non of the modules or system boxes restore position, even after loading my project. Only the plugins go back to their saved positions when i load a project.

> #!/bin/bash
killall -9 carla
killall -9 jackdbus
killall -9 pulseaudio
sleep 5
jack_control start & 
sleep 1
pulseaudio --start
cadence &
sleep 2
pacmd unload-module module-jack-sink
pacmd unload-module module-jack-source
sleep 2
#pulseaudio bridges | in / out
pacmd load-module module-jack-source channels=2 source_name=voip-in client_name=voip-in connect=false
pacmd load-module module-jack-sink channels=2 sink_name=voip-out client_name=voip-out connect=false
pacmd load-module module-jack-sink channels=2 sink_name=games-out client_name=games-out connect=false
pacmd load-module module-jack-source channels=2 source_name=media-in client_name=media-in connect=false
pacmd load-module module-jack-sink channels=2 sink_name=media-out client_name=media-out connect=false
sleep 5
carla &
sleep 3
wall "Audio systems up and running"
sleep 1
exit 0

![image](https://user-images.githubusercontent.com/21233073/100883793-bc068680-347e-11eb-8904-bcf5f9400125.png)

**Comment by logiczny** [comment]
Hi,
You are doing great job developing this project!
This one is also bugged for me. When I load config file, they layout is not saved and all plugins and sink

**Comment by mxmilkiib** [comment]
What version of JACK?

**Comment by logiczny** [comment]
JACK: 
$: jackd --version
jackdmp version 1.9.18 
Qjack:
Version: 0.9.2
Using: Qt 5.11.3
Carla: 2.3.0
Same occurs on previous versions of Carla and JACK.

**Comment by falkTX** [comment]
what is the output of `jack_property -l` when carla is running?

you should see stuff like:
```
8589934963
key: https://kx.studio/ns/carla/osc-tcp value: osc.tcp://falkTX-PC:22752/Carla type: text/plain
key: https://kx.studio/ns/carla/osc-udp value: osc.udp://falkTX-PC:22752/Carla type: text/plain
```

anything else (errors, or empty) mean the jack2 version does not support meta-data and thus carla cannot save client information.

**Comment by logiczny** [comment]
```
$: jack_property -l
could not retrieve all properties
```
Could you please point me in the right direction what should I do? 
1. Compile jack2 with meta-data feature, then Carla start working?
OR
2. Change something in configuration of Jack?

**Comment by falkTX** [comment]
Build jack2 with metadata enabled. I cant do that for you, might be a problem in your distribution packages.

**Comment by logiczny** [comment]
so simple...
`waf configure --db=yes` and layout is saved as expected!
Thank you!
