### ISSUE TITLE
'Parameters' window bug

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#1140]
Hi there.
Click on some parameters makes the window turning back to 'Edit'.
i.e. : midiSimpleLFO from InsertPizHere, parameter 'Freq mode'

**Comment by falkTX** [comment]
I don't understand.. which window "turns back to Edit" ?

**Comment by moonshaadow** [comment]
In the Edit window, when I am in the Parameters tab and I click on some parameter's value or I try to move slide-bar, the window turns back to the Edit tab.
It seems to happen when a parameter changes the values names of another parameter.

**Comment by falkTX** [comment]
This can happen if a plugin parameter changes stuff from another parameter.
Carla recreates the parameter list on a few cases like this.

Noted, should be fixed to handle such cases better.

**Comment by falkTX** [comment]
Fixed in d808f53447a0368e6ce4638026c5f3c257cc9398

We lose the parameter mouse-down control though, as the parameters are recreated, but I think we can live with that.
If there is an action that triggers the reloading of parameters, it is better to not do it very fast.
