### ISSUE TITLE
"Midi Pattern" plugin : bugs

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#1142]
Hello there.
MIDI Pattern :
   - missing 'note off' at the end of the loop
   - does not play first note when starting playback
   - sometimes after erasing a note, a 'note off' stays in the pattern.

**Comment by falkTX** [comment]
I was able to fix the first 2, but I dont understand this one:

> * sometimes after erasing a note, a 'note off' stays in the pattern.

what does this mean? something leftover in the GUI?

**Comment by moonshaadow** [comment]
> what does this mean? something leftover in the GUI?

No, the note disappears from the GUI after erasing it, but a "ghost" note-off stay in the pattern. (tested with a midi monitor)

**Comment by falkTX** [comment]
All those should be fixed in latest git.
Stable release for 2.3 will be in 4 days.
