### ISSUE TITLE
Carla assertion failure: "pthread_equal(pthread_self(), fMainThread)" in file CarlaPluginVST2.cpp, line 1982

### ISSUE THREAD

**Issue by jsravn** [falkTX/Carla#1146]
Hello,

Thank you for this great application. I've been using it for a while to load the Sonarworks VST plugin. It's worked great in the past, but after swapping to a different Linux distro, I cannot get the plugin to work. The top level UI loads, but whenever I try to click on anything I get this error:

```
Carla assertion failure: "pthread_equal(pthread_self(), fMainThread)" in file CarlaPluginVST2.cpp, line 1982
```

I'm using Carla 2.1.0.

Do you have any idea what the cause would be? Is it a missing/incompatible lib?

**Comment by falkTX** [comment]
This is carla preventing the plugin misbehaviour from causing issues.
On this particular instance the plugin is giving the host "idle time" outside of the main-thread, which is very problematic. So carla just ignores it, and logs a warning.
Better to contact the plugin author, this seems rather suspicious, they need to fix their plugin.

**Comment by jsravn** [comment]
Is there any additional logging I can enable? It sounds like that wouldn't be the cause of the non-responsive UI.

**Comment by jsravn** [comment]
Nevermind, thanks for your help. Figured it out via strace that it was calling `zenity` which I don't have installed. I wonder if this kind of error is supposed to surface in the carla logs though?

**Comment by falkTX** [comment]
It is all up to the plugin to log some information about it. If they keep themselves quiet, carla (or the user) have no way to know.
