### ISSUE TITLE
[question] Carla-control help from Windows to other platforms?

### ISSUE THREAD

**Issue by jMahnO** [falkTX/Carla#1149]
I've had success running 64-bit carla-control v2.1 between several platforms but some combinations to/from Windows ~~won't~~ did not work for me, even with Windows Firewall disabled.

Any tips for carla-control on Windows?

**Solution! Set Reported host to "Custom:" and enter IP address of machine running Carla-control.**

(I was sure I tried that before - oops - but it works for all the cases below that did not work before)

What I've tested (where Worked == I see patch in the running Carla and can control transport):

(table updated with above solution)

| Carla-Control | Carla | Worked? | Tip |
| --- | --- | --- | --- |
|          MacOS   |  Arm (RPi)  |      Yes  | |
|          Win7      |   Arm (RPi)   |      ~~No~~ Yes  | Set Reported host to Custom: |
|          Win10     |  Arm (Rpi)    |     ~~No~~ Yes  |
|          Win7       | Win7             |   Yes (same machine)  | |
|          Win7       |  Linux x86 VM | Yes (same machine)  | |
|   Linux x86 VM |  Win7              |   ~~No~~ Yes  (same machine)  | Set Reported host to Custom:  |
|          Win7      |  MacOS           |  ~~No~~ Yes  | Set Reported host to Custom: |

**Comment by jMahnO** [comment]
Solution found, which was to use that handy "Reported host = Custom" field and enter IP address of the machine running Carla-control.

When looking at logs and a Wireshark trace, I could see that TCP and UDP registrations were using the symbolic name for the controlling PC. Either my simple network isn't configured for name resolution or my PC's aren't. The Mac had no trouble responding to its own name.

So using actual IP address of the controlling host solves the issue (or I suppose I could learn about setting machine name correctly in Windows - Nyyaaahhhhh).

**Comment by falkTX** [comment]
oh that. I have bitten by that too, that is why I added such an option.
preferably we tell liblo (which is handling osc) to not use names but only IPs. but I did not figure out how to achieve this.

**Comment by falkTX** [comment]
FYI just added a fix for this in latest develop/git
I was having the same issue, where a remote machine could not resolve the machine name and communicate back to carla-control.

The "custom" IP is not used or needed anymore, I will remove it in the next release.

**Comment by jMahnO** [comment]
Sweet!
