### ISSUE TITLE
[Features] MIDI : Add "send note" option in the Edit window

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#1154]
Could avoid to add a midi filter plugin in some case. With the currently available options (send CC, send Pitchbend....), I suppose it makes sense.

**Comment by falkTX** [comment]
Isnt that what the midi keyboard in the edit window is for?

**Comment by moonshaadow** [comment]
I don't think so... The 'Send Control Changes', 'Send Channel Pressure', etc.. act as midi filters, right ? To add a 'Send Notes On / Notes Off' filter could be useful. Or is there any way to do that with the midi keyboard ?

**Comment by falkTX** [comment]
ah yes, that makes sense. I misunderstood you initially.
those options work as a midi filter indeed, and I can see the option to not send notes being useful. I will add this in soon.

**Comment by falkTX** [comment]
Add in 53b3a2cbac8cd416a16f94ec1f4394dcd532b513

**Comment by moonshaadow** [comment]
@falkTX Nice!
But feature is disabled by default, it should be enabled, as others.

**Comment by moonshaadow** [comment]
Oh sorry it's already done. thank you.
