### ISSUE TITLE
Feature request: save MIDI CC parameter mappings and settings with project

### ISSUE THREAD

**Issue by aaltman** [falkTX/Carla#116]
For an example of what I'm thinking of here, start up Carla with a new project and add an instance of Wolpertinger.  In the Plugins pane, if you click the wrench next to Wolpertinger (settings icon? this could probably use a tooltip) you get to a sub-window with tabs "Edit | Parameters (1) | Parameters (2)".  

Suppose I want to automate Wolpertinger's gain from within my DAW while using Carla as a plugin host.  To set this up, I go to the "Parameters (1)" tab, find Wolpertinger's Gain control up at the top, and click the up icon in the MIDI CC box.  This assigns Gain to cc#0 on channel 1.  All good so far.

Now, if I close out Wolpertinger, save my Carla project, close Carla, reopen, and reload the project, when I navigate back to Wolpertinger's parameters page, it's back to the default of (none) on channel 1.  

It would be cool to be able to have these mappings save with the project.

**Comment by joaoms** [comment]
This happens to me with all vst plugins. DSSI and LV2 work fine (incl. wolpertinger).

**Comment by falkTX** [comment]
ah yes, this happens with vst plugins only, when chunks are enabled.
I'll get a fix very soon.
