### ISSUE TITLE
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by my6jay30** [falkTX/Carla#1164]
Hi, I tried to use Carla on Ubuntu 16.04.
I have installed PyQt5==5.9 via pip (python3).
When I run  `./Carla`
It shows error:
```
Carla self-contained executable 2.0.97 (2.1-RC2), based on UnZipSFX.
Launching: '/tmp/carla-2.1/carla'
Traceback (most recent call last):
  File "./lib/__startup__.py", line 40, in run
  File "./lib/Console.py", line 23, in run
  File "source/frontend/carla", line 22, in <module>
  File "./lib/carla_host.py", line 30, in <module>
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory
```
Can anyone tell me how to solve this problem?
Thanks.

**Comment by falkTX** [comment]
You don't need PyQt, only Qt5.
Also, please try with the final 2.1 binary.

**Comment by falkTX** [comment]
Any news on this? Can you try with the 2.2 binaries?

**Comment by my6jay30** [comment]
Yes, as the latest Qt version on Ubuntu 16.04 is below 5.9. After I manually install Qt5.9 and run `ldconfig` it works.
Thanks
