### ISSUE TITLE
Cannot load Carla-Rack: ‘NameError: name 'CarlaHostQtPlugin' is not defined’

### ISSUE THREAD

**Issue by Joermungand** [falkTX/Carla#1166]
Hi!

Working with the latest Carla built from git, I get the following error when trying to load Carla-Rack (whether VST or LV2) in any host:
```
Traceback (most recent call last):
  File "/usr/lib/vst/carla.vst/resources/carla-plugin", line 34, in <module>
    class PluginHost(CarlaHostQtPlugin):
NameError: name 'CarlaHostQtPlugin' is not defined
```
I don’t know if this is work in progress, but I thought I should let you know.

**Comment by falkTX** [comment]
I am in the middle of cleaning up the code, you caught a side-effect of it.
Will fix right away. For more stable carla, use the master branch.
