### ISSUE TITLE
Plugin stdout in Carla ?

### ISSUE THREAD

**Issue by mhugo** [falkTX/Carla#1167]
Hi,

I'm trying to understand why a plugin (samplv1) correctly loads its state from a .carxp in Carla, but does not work as expected with my code that calls Carla's Python API.

I'll try to use gdb, but I thought looking at the standard output of loaded audio plugins would be handy (I've added some debugging outputs). I can't see anything. Is there some log file ? An environment variable to set ? Or is it not possible, by design ?

**Comment by falkTX** [comment]
Carla captures the logs to send to its log tab by default.
You can set `ENGINE_OPTION_DEBUG_CONSOLE_OUTPUT` to 0 (false) to disable this.
See https://kx.studio/ns/dev-docs/CarlaBackend/group__CarlaBackendAPI.html#ga9e2ec80686059b800d34605a80e46a29

You can also set env var `CARLA_LOGS_DISABLED` to any value to disable it.

**Comment by mhugo** [comment]
> Carla captures the logs to send to its log tab by default.

Ahh, I was sure I was missing something obvious : the logs tab. Thanks !

And thanks also for the env var and the engine option.
