### ISSUE TITLE
[2.1.1] looks like an issue in "about"

### ISSUE THREAD

**Issue by trebmuh** [falkTX/Carla#1169]
![carla-soucis](https://user-images.githubusercontent.com/8705846/84403052-8be3d680-ac05-11ea-9060-5a42b637992e.png)

**Comment by falkTX** [comment]
huh, never noticed this... oh well, not worth a 2.1.2 at this point lol.
I will do a simple commit fix on master branch, feel free to take the diff

**Comment by trebmuh** [comment]
> huh, never noticed this... oh well, not worth a 2.1.2 at this point lol.

sure it doesn't :smile: 

Thanks for the quick fix.
