### ISSUE TITLE
Feature: More than two outputs in rack mode.

### ISSUE THREAD

**Issue by Qualitymix** [falkTX/Carla#117]
Currently Carla is limited to two channels while being used in rack mode(so any time i want to use it as a plugin in Ardour).
This doesn't allow the use of a plugin like Session Drummer, which has 24 outputs.

Not sure on how the programming would go, but perhaps something could be worked out that the carla-rack has as many outputs as the channel it is inserted to has.
i.e. I create an audio track with 24 outputs, add carla-rack as a plugin, and I can only use plugins with 24 or less outputs.

**Comment by falkTX** [comment]
Chiming in 4 years later :)

Multi-in/out plugins can now be loaded in Carla-Rack (from latest git version).
As I said before, Carla uses the first 2 channels, the extra ones are just ignored.
