### ISSUE TITLE
Make Carla more robust to a JACK restart?

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1175]
At the moment, after stopping and restarting JACK, Carla just doesn't work; the engine cannot be stopped, and Carla has to be closed entirely.

If JACK has been restarted, could Carla at least be made to allow it's own engine to be stopped and restarted so as to connect to the new JACK session?

**Comment by falkTX** [comment]
Good point. It is very annoying to me when it happens too, I just happen to run jack mostly 100% of the time.
Let's fix it for next release, should be pretty simple. just need to map jack shutdown callback of the main client to an engine stop action.

**Comment by codecollider** [comment]
I don't know if this is related, but I guess it could be:

Bitwig has a Deactivate Audio Engine Switch. When using Carla (Rack) in Bitwig and I switch on / off the audio engine several times all plugins won't load again. When I try the same without Carla it works. So Carla seems to hang preventing other plugins from loading. This is with running Carla inside Bitwig and Bitwig is connected to Jack. 

It's possible to terminate all processes in Bitwig, but if the project is not saved this can result in a loss of changed presets.
