### ISSUE TITLE
Patchbay: system node 'Join' state(/position) after reload

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1177]
If one of the two system nodes is right clicked and Join is selected, then the project saved, on the next start it opens up like this;

![image](https://user-images.githubusercontent.com/108225/85150114-09cd6080-b24a-11ea-8e7a-9daf17f48d0c.png)

**Comment by falkTX** [comment]
Yes, you found the hole I forgot to cover up :P
the split yes/no mode is not saved at the moment, causing this.
