### ISSUE TITLE
Symbolic links in git repository are not fully compatible with checking out on Windows itself

### ISSUE THREAD

**Issue by andlabs** [falkTX/Carla#1179]
By default, git does not create symbolic links on Windows; you have to enable it, either by passing `-c core.symlinks=true` to your `git` commands or by setting that in your git configuration. But there's a reason: on Windows, symbolic links are typed — a symbolic link to a file is fundamentally different from a symbolic link to a directory,  while on Unix all symbolic links are the same. ([One source of more information](https://stackoverflow.com/questions/5917249/git-symlinks-in-windows))

With `-c core.symlinks=true`, git tries to determine what type to give to the symlink, but for whatever reason the heuristic doesn't work right on Carla, even in cases where the symlink target already exists. Running `git -c core.symlinks=true clone --recursive` ([yes, the order of the options is important here](https://stackoverflow.com/a/49903616/3408572)) complains "no such file or directory" when trying to make some of the symlinks, and that appears to be because git is trying to make them as file symlinks instead of directory symlinks.

Fortunately this can be fixed using a [`.gitattributes` file](https://stackoverflow.com/a/55945987/3408572). I created this one, where combining with a `git reset --hard` allows me to create most of the symlinks:

```
bin/carla.lv2/resources symlink=dir
source/includes/lilv    symlink=dir
source/includes/serd    symlink=dir
source/includes/sord    symlink=dir
source/includes/sratom  symlink=dir
```

However, I wouldn't suggest using this one directly, since I'm not sure how correct it is for all the symlinks in the Carla repo. If this file is present in the repository, it *should be* picked up by the git clone.

Furthermore, this still doesn't seem to work for `bin/carla.lv2/resources` either, since that doesn't exist until after Carla is built; I had to create an empty folder (which requires a dummy file to store in a git repository). There's probably a better solution here, and by extension a better `.gitattributes` file; I'll leave that to you to determine.

I am using Windows 7 64-bit with [MSYS2](https://www.msys2.org/), and I'm trying to build using its 32-bit MinGW-w64 environment, using its own git (instead of the Git Windows distribution).

Sorry I can't provide more precise information about what's going on; Windows symlinks and git for Windows behavior are new to me. I figure you are building using MinGW-w64 on Linux? I can do that too; I was only building on Windows because I had some old 32-bit VSTs for that.

**Comment by falkTX** [comment]
If you find something that really works, cool, but I have to say I have little to zero interest on a "fix" for thsi.
The symlinks are there for good reason, making life easier for the owner of the project to do things.

and yes, I build the win32/64 stuff in Linux.

**Comment by coffeeandspaceships** [comment]
If you are using git for Windows, have you tried v2.27? It includes what seems a very complex fix for symlink parsing, which might have the side-effect of fixing this...

**Comment by falkTX** [comment]
I have to say sorry, but I am closing this ticket.
Does not make sense to keep it open if I have no intention of ever working on it.
I do not run Windows, only for the occasion of needing to test something, so development will never happen there.

If you find something that works without breaking anything else, feel free to send a PR, I will likely merge that.
