### ISSUE TITLE
Problems loading Windows VSTs via Carla on Manjaro

### ISSUE THREAD

**Issue by PonySchreck** [falkTX/Carla#1180]
Hey, I've been trying to get my VSTs working for a while now with Carla and I rly don't know what I'm doing wrong, if i forgot to install dependencies or if its a bug. (actually its only the "MTPowerDrumkit" which offers an optimized version for Carla + Wine, and some other minor VSTs which are less important)

OS: Manjaro (Gnome) - Lysia 20.0.3

i installed `carla-git` and `carla-bridges-win` via AUR.
According to the following window I think the bridges are detected and the PlugIn Paths are also SetUpped.
<br>
![image](https://user-images.githubusercontent.com/22845026/85375147-2b726480-b536-11ea-8929-e710eaf3ca92.png)

this are my wine settings:
![image](https://user-images.githubusercontent.com/22845026/85375463-9e7bdb00-b536-11ea-8aa4-8a76023bd942.png)

this my output when i start carla:
<br>
```
LRDF Support not available (LADSPA-RDF will be disabled)
Carla 2.2.0-beta1 started, status:
  Python version: 3.8.3
  Qt version:     5.15.0
  PyQt version:   5.15.0
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
Frontend pixel ratio is 1.0
libjack.so.0 loaded successfully!
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
Cannot use real-time scheduling (RR/5) (1: Operation not permitted)
JackClient::AcquireSelfRealTime error
```
i switched yesterday to 100% Linux and deleted my Windowssystem, the problem with the VST is my only issue why i might could want to go back to windows so i realy appreciate your work!

Greetings from Germany!

edit: the native Linux ones work great in carla.

**Comment by PonySchreck** [comment]
i started again and got this output
                              
```
LRDF Support not available (LADSPA-RDF will be disabled)
Carla 2.2.0-beta1 started, status:
  Python version: 3.8.3
  Qt version:     5.15.0
  PyQt version:   5.15.0
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
Frontend pixel ratio is 1.0
libjack.so.0 loaded successfully!
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

```

And i forgot to post the output when i try to refresh in "Add New"

```
carla-discovery::error::Not a LADSPA plugin - <VST-Path>/VSTs/AllGVSTLinux64Beta/GTune.so
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
carla-discovery::error::Not a LADSPA plugin - <VST-Path>/VSTs/DrumPro_Win32/Drum Pro Win32/Drum Pro.dll
carla-discovery::error::Not a LADSPA plugin - <VST-Path>/VSTs/MTPDK-2.0.9-VST-32bit-for-Linux-Wine-FULL/MT-PowerDrumKit.dll
carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo" - /usr/lib/vst/carla.vst/CarlaPatchbay.so
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo" - /usr/lib/vst/carla.vst/CarlaPatchbay16.so
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo" - /usr/lib/vst/carla.vst/CarlaPatchbay32.so
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo" - /usr/lib/vst/carla.vst/CarlaPatchbay64.so
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo" - /usr/lib/vst/carla.vst/CarlaPatchbayFX.so
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo" - /usr/lib/vst/carla.vst/CarlaRack.so
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo" - /usr/lib/vst/carla.vst/CarlaRackFX.so
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/carla-bridge-lv2.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_interposer-jack-x11.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_interposer-safe.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_interposer-x11.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_native-plugin.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_utils.so```

**Comment by falkTX** [comment]
Try to add some native, internal plugins first.
From the logs, you don't even have carla's engine running at all.

Carla defaults to JACK on Linux, but it seems you are not using that.
So go to carla settings, and in engine settings change audio driver to pulseaudio or alsa, I guess pulseaudio is the one for you

**Comment by PonySchreck** [comment]
@falkTX thank you for this fast support! i will try that!

**Comment by PonySchreck** [comment]
@falkTX i have selected pulseaudio, started the engine and refreshed the pluginlist again. unfortunately it still doesn't work.
maybe i didn't describe my problem that well or used the wrong words. my mistake. 
My WindowsVSTs are not shown in the "Add New" list after refreshing, i think they are not recognized as WindowsVSTs by carla while the scanning process although the .dll is displayed in the progressbar.  Native plugins are loaded and added without any problems in the Carla-Rack.

**Comment by falkTX** [comment]
try to drag&drop the dlls into the rack view first.
This will skip the discovery altogether. check logs for anything suspicious.

**Comment by raphourbe** [comment]
> @falkTX i have selected pulseaudio, started the engine and refreshed the pluginlist again. unfortunately it still doesn't work.
> maybe i didn't describe my problem that well or used the wrong words. my mistake.
> My WindowsVSTs are not shown in the "Add New" list after refreshing, i think they are not recognized as WindowsVSTs by carla while the scanning process although the .dll is displayed in the progressbar. Native plugins are loaded and added without any problems in the Carla-Rack.

Hi, I add the same problem today while installign Carla on my Manjaro with the same plugin!
The problem was not that Carla didn't get the VST, it was that it wasn't tell to display them.
I went to Architecture in the left menu in the "Add plugin", then checked "Bridged win32" and "Bridged wine"... and there it was.

![image](https://user-images.githubusercontent.com/37442071/85948606-25272280-b952-11ea-9aad-6337753e9723.png)

I hope this helped. :)

**Comment by PonySchreck** [comment]
i checked this, but still no windows plugins, but thank you all! i switched to LinVST to run/convert my vsts

**Comment by falkTX** [comment]
One thing I discovered kinda recently, is that if you check the Wine option to disable access to the full linux system, Carla can no longer find the Windows VSTs.
Carla needs the wine Z: drive to be mapped to "/".

@PonySchreck could this be your issue? Would be great to check, thanks.

**Comment by PonySchreck** [comment]
@falkTX sure, i can check that out the next days!

**Comment by terencode** [comment]
@falkTX wasn't it the "Hide wine version from applications" checkbox from the staging tab
?

**Comment by falkTX** [comment]
@terencode yes, that one! Carla 2.0 and 2.1 use that flag as a way to detect presence of wine (which we need to load windows plugins on linux).
as you know (since we debug this together), the next version 2.2/git no longer needs that option disabled in wine settings.

since @PonySchreck is installing carla from git, true indeed this no longer applies.
but the Z: drive being mapped to "/" is still required.

**Comment by falkTX** [comment]
@PonySchreck I am closing this issue, since you moved on to use linvst. feel free to open again if you still have issues  (after confirming indeed that the Z: drive is accessible via wine, easy to check by running `wine explorer`)
