### ISSUE TITLE
Unsaved Catla-Patchbay plugins do not retain patchbay graphical layout

### ISSUE THREAD

**Issue by to7m** [falkTX/Carla#1181]
If I add a Carla-Patchbay, then open the custom GUI, then reorder some items in the patchbay, then close that GUI, when it is next opened the patchbay will show something different. If the patchbay is saved as a file first, then it will be preserved.

Steps for reproduction:
* Open Carla
* Add a Carla-Patchbay
* Open the GUI for the Carla-Patchbay
* In the Patchbay tab, move ‘Audio Output’ to the left of ‘Audio Input’
* Close the GUI (without saving)
* Open the GUI again and observe that the Patchbay tab's graphical layout has not been preserved

Expected behaviour: the Patchbay tab's graphical contents should be preserved, just like the connections and plugins. It should not be necessary to save the plugin instance to an external file first, given that it is not necessary for preserving the connections and plugins.

**Comment by falkTX** [comment]
What carla version are you using?
This has been fixed already in latest develop/git branch

**Comment by to7m** [comment]
My bad. I was using 2.1.1-1. Patchbay layouts are preserved on 2.2.0-beta1. Thanks!
Plugin parameters aren't though, so I'll make another report for that.
