### ISSUE TITLE
Carla-v2.1.0 & v2.1.1 plugin host does not automatically detect and display plugin i/o channels when using iem vst plugins

### ISSUE THREAD

**Issue by syams86** [falkTX/Carla#1184]
Hi,
   When I select iem vst plugins such as MultiEncoder in Carla-v2.1.1 (recent version) (or Carla-v2.1.0) vst plugin host the number of  i/o channels in patchbay panel shows only one when select auto mode (bus too small) but in the case of previous version of Carla v2.0.0  vst host all the 64 number of  i/o channels is displayed in patchbay panel in auto mode and there is no problem. I hope this issue will be  solve in the next version release of Carla vst plugin host. For claritiy please see the screen shot shown below. thanks
![Carla-v2 1 1](https://user-images.githubusercontent.com/3140919/85941803-cd34ef80-b942-11ea-9ffa-48ca0b214403.png)
![Carla-v2 0 0](https://user-images.githubusercontent.com/3140919/85941812-daea7500-b942-11ea-845e-b252912930c4.png)

**Comment by falkTX** [comment]
For this to be working in Carla 2.0, I guess this is a VST2 plugin and not a VST3 one, correct?
Just to be sure, are you running Windows?

**Comment by syams86** [comment]
Hi, iem plugins are VST2 plugins. I am using Windows 10 platform. On 29-Jun-2020 1:44 AM, Filipe Coelho <notifications@github.com> wrote:
For this to be working in Carla 2.0, I guess this is a VST2 plugin and not a VST3 one, correct?
Just to be sure, are you running Windows?
