### ISSUE TITLE
Firewire soundcard not in patchbay

### ISSUE THREAD

**Issue by wvengen** [falkTX/Carla#1187]
With JACK running on [ffado](http://ffado.org/) connected to an [AudioFire Pre8](https://www.soundonsound.com/reviews/echo-audiofire-pre-8) device, Carla doesn't show the device in the patchbay. In the past somewhere I remember that it did work. QJackCtl does show the device.

Relevant logs:
```
CarlaEngine::setOption(34:ENGINE_OPTION_CLIENT_NAME_PREFIX, 0, "(null)")
libjack.so.0 loaded successfully!
CarlaEngineJack::init("Carla")
CarlaEngineOsc::init("Carla")
OSC TCP server running and listening at osc.tcp://mydevice:22752/Carla
OSC UDP server running and listening at osc.udp://mydevice:22752/Carla
CarlaEngineThread::run()
CarlaEngineJack::findPluginIdAndIcon("firewire_pcm", ...)
CarlaEngineJack::findPluginIdAndIcon("PulseAudio JACK Sink", ...)
CarlaEngineJack::findPluginIdAndIcon("PulseAudio JACK Source", ...)
CarlaEngine::callback(true, false, 20:ENGINE_CALLBACK_PATCHBAY_CLIENT_ADDED, 1, 3, 65535, 0, 0,000000, "Carla")
CarlaEngine::callback(true, false, 20:ENGINE_CALLBACK_PATCHBAY_CLIENT_ADDED, 2, 2, -1, 0, 0,000000, "firewire_pcm")
Carla assertion failure: "uuidstr != nullptr && uuidstr[0] != '\0'" in file CarlaEngineJack.cpp, line 3906
Carla assertion failure: "fCount == 0" in file ../../utils/LinkedList.hpp, line 80
Carla assertion failure: "fCount == 0" in file ../../utils/LinkedList.hpp, line 80
Carla assertion failure: "fCount == 0" in file ../../utils/LinkedList.hpp, line 80
```

show that `jackbridge_get_uuid_for_client_name` returns `NULL`. According to [JACK docs](https://jackaudio.org/api/group__ClientFunctions.html#ga4c995eb51f38f3962dea4408122ced88) it means that the given client does not exist. That's pretty odd, since we know `firewire_pcm` does exist.

Part of the backtrace in a breakpoint on this line:
```
(gdb) bt
#0  CarlaBackend::CarlaEngineJack::initJackPatchbay(bool, bool, char const*, bool) (this=0x1654f30, sendHost=true, sendOSC=false, ourName=0x7fffe876300e "Carla", groupsOnly=false)
    at CarlaEngineJack.cpp:3906
#1  0x00007fffeacd8333 in CarlaBackend::CarlaEngineJack::init(char const*) (this=0x1654f30, clientName=0x7fffe9062950 "Carla") at CarlaEngineJack.cpp:1542
#2  0x00007fffeac78b3f in carla_engine_init(CarlaHostHandle, char const*, char const*)
    (handle=0x7fffeb709780 <carla_standalone_host_init::gStandalone>, driverName=0x7fffe9062920 "JACK", clientName=0x7fffe9062950 "Carla") at CarlaStandalone.cpp:355
(gdb) print uuidstr
$1 = 0x0
(gdb) print group
$2 = (const CarlaBackend::CarlaEngineJack::GroupToIdData &) @0x15ffc60: {id = 2, icon = CarlaBackend::PATCHBAY_ICON_HARDWARE, pluginId = -1, 
  strVal = "firewire_pcm", '\000' <repeats 242 times>}
```

I'll see if I can write a small JACK application, and if it exhibits the same behaviour (in which case it is a JACK bug).

**Comment by falkTX** [comment]
I am changing Carla quite a lot recently, so make sure you have the latest version from git/develop

The uuid check can fail against JACK internal clients, which can happen here with firewire stuff.
I just went to check in the code, and it is wrongly returning from the function at that point, where it should just safely continue.

Please try with fda792130a854b1a6583d8574beacac1df510019
Might just fix this for you entirely

**Comment by wvengen** [comment]
Yes, it works (audio driver _JACK, with audio driver _JACK with ALSA-MIDI_ it doesn't start, probably because the device has a JACK MIDI port). Super, thank you!

**Comment by falkTX** [comment]
Thanks for the detailed report too.
Those are always very useful.
