### ISSUE TITLE
Latest Carla VST starts in Reaper with a black screen

### ISSUE THREAD

**Issue by Nanotwerp** [falkTX/Carla#1189]
![Screenshot from 2020-07-02 22-07-55](https://user-images.githubusercontent.com/17240342/86424863-a7487b80-bcb1-11ea-91a7-8a2329dc8cbc.png)

It doesn't work at all. Carla's VST is completely broken on my PC, on two distros (Solus and Fedora)

The errors in red repeat ad infinitum.

**Comment by falkTX** [comment]
are you able to try the git/develop version?

**Comment by falkTX** [comment]
Even 2.1.1 would be an improvement, 2.1.0 has a few issues that were already fixed there.

**Comment by Nanotwerp** [comment]
> are you able to try the git/develop version?

This what I get when I try it with the latest develop version.
![Screenshot from 2020-07-02 22-57-29](https://user-images.githubusercontent.com/17240342/86427175-8125da00-bcb7-11ea-84cd-94c806bb6274.png)

Both work standalone but they don't work as plugins.

**Comment by falkTX** [comment]
Are you using wayland?

**Comment by falkTX** [comment]
Try this:
```
export QT_QPA_PLATFORM=xcb
```
Then run reaper from that same terminal.

Let me know how that works for you.
Thanks

**Comment by Nanotwerp** [comment]
> Try this:
> 
> ```
> export QT_QPA_PLATFORM=xcb
> ```
> 
> Then run reaper from that same terminal.
> 
> Let me know how that works for you.
> Thanks

Yes, I am using Wayland and this fix works! Much thanks!!!!

**Comment by falkTX** [comment]
Alright, thanks for confirming. I will have to figure out a way to force this for the plugin version.

**Comment by falkTX** [comment]
Now handled in 3c27fbdd3a913b25d378c418f31b787251390b96

Would be great if you could confirm the fix. It should work without having to modify/set any environment variables

**Comment by Nanotwerp** [comment]
> Now handled in [3c27fbd](https://github.com/falkTX/Carla/commit/3c27fbdd3a913b25d378c418f31b787251390b96)
> 
> Would be great if you could confirm the fix. It should work without having to modify/set any environment variables

It works perfectly without any env variable tinkering! Thank you!

**Comment by falkTX** [comment]
good to know. closing the ticket then.
