### ISSUE TITLE
No module named 'ui_carla_host'

### ISSUE THREAD

**Issue by katdaniel** [falkTX/Carla#1190]
I'm on Ubuntu 18.04. I installed Carla fine and it shows up in my DAW (LMMS 1.2.1) but for some reason I can't get the GUI to show.. This is the output I get when typing `carla` 
```daniel@rmf:~/Downloads/Carla-develop$ carla
Traceback (most recent call last):
  File "/usr/local/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/local/share/carla/carla_host.py", line 47, in <module>
    import ui_carla_host
ModuleNotFoundError: No module named 'ui_carla_host'
```
This is the output I get when doing `make features`
```daniel@rmf:~/Downloads/Carla-develop$ make features
---> Main features 
Front-End:     YES
LV2 plugin:    YES
VST2 plugin:   YES
Link support:  YES
OSC support:   YES
Binary detect: YES

---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  YES
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]
WASAPI:      NO  [Windows only]

---> Plugin formats: 
Internal: YES
LADSPA:   YES
DSSI:     YES
LV2:      YES
VST2:     YES (with UI)
VST3:     YES (with UI, using JUCE)
AU:       NO  [MacOS only]

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     YES (bridge)
Gtk3:     YES (bridge)
Qt4:      YES (bridge)
Qt5:      YES (bridge)
X11:      YES (direct+bridge)
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
Basic: YES
Extra: NO [FFmpeg missing or too new]
SF2/3: YES
SFZ:   YES

---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: NO
```
If more info is needed I'll add it ASAP.

**Comment by falkTX** [comment]
what is your output of `sudo make install` ?

this seems like an installation failure.
are you mixing self-compiled carla with prebuilt carla from some repository?

**Comment by sydmattersfan** [comment]
I fixed it somehow, unfortunately I actually completely forgot how... shit. I hate doing the "oh i fixed it myself (issue closed)" thing but if I ever remember how I got it working I'll edit my original post. Thanks for reaching out though! (and thanks for the incredible software)

**Comment by katdaniel** [comment]
I fixed it somehow, unfortunately I actually completely forgot how... shit. I hate doing the "oh i fixed it myself (issue closed)" thing but if I ever remember how I got it working I'll edit my original post. Thanks for reaching out though! (and thanks for the incredible software)
