### ISSUE TITLE
Web Based UI

### ISSUE THREAD

**Issue by mnesarco** [falkTX/Carla#1191]
Hi,
Is it possible to run Carla in a headless Raspberry Pi and control it from a Web GUI using some kind of protocol?

Web -> http -> **Backend** -> Carla

Or does it exposes any public API so I can implement an http backend?

**Comment by falkTX** [comment]
You can use carla-control over the network (it uses OSC protocol).
There is no HTTP version, I tried to start one with c++ "restbed" but it keeps crashing and building it in debug mode seems problematic, so I stopped trying.

**Comment by mnesarco** [comment]
@falkTX it sounds like a proxy can be created:

Web -> **HttpProxy** -> OSC -> Carla

Can you point me to some OSC protocol documentation?

**Comment by falkTX** [comment]
The Carla OSC protocol is not documented, and it ties to the Carla version at the moment.
best I can do is point you to the code https://github.com/falkTX/Carla/blob/develop/source/frontend/carla_control.py#L314
(there is a TCP and UDP connection at the same time btw)

The WIP, crashy REST stuff is at https://github.com/falkTX/Carla/tree/develop/source/rest

**Comment by mnesarco** [comment]
Ok, thanks I will take a look.
