### ISSUE TITLE
Activate Side Panel via some widget on the left?

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1193]
A quicker action than going via the Settings menu.

**Comment by falkTX** [comment]
What about a keyboard shortcut?

**Comment by mxmilkiib** [comment]
A hotkey would be good.

I think a button would also be good as some users would miss the existence of the hotkey or just prefer mouse actions over keyboard actions.

**Comment by falkTX** [comment]
> as some users would miss the existence of the hotkey

This will depend on the desktop.
Most will show the shortcuts together with the action.

![Screenshot_20200714_042835](https://user-images.githubusercontent.com/1334853/87380524-925dc900-c58a-11ea-9265-98e1448243cb.png)

Sadly Gnome thinks it knows best and hides these (too complex and weird for regular people to understand, somehow :disappointed:)

**Comment by mxmilkiib** [comment]
Maybe how about clicking the Patchbay left side audio meter/left edge of the Pack to toggle the sidebar?
