### ISSUE TITLE
MIDI Pattern becomes out of sync when tempo is changed

### ISSUE THREAD

**Issue by ryukau** [falkTX/Carla#1210]
MIDI Pattern (internal plugin) becomes out of sync when tempo is changed while playing.

I tested against [BSEQuencer](https://github.com/sjaehn/BSEQuencer) and [stepseq.lv2](https://github.com/x42/stepseq.lv2).

Tested on Carla 2.1.0 and 2.2.0-RC1.

**Comment by falkTX** [comment]
I can confirm the issue.

The MIDI pattern plugin needs some attention.
I fixed it up a bit before, but it is not enough.

**Comment by ryukau** [comment]
Thanks for looking into this issue.

I tested `develop` branch today, but it still goes out of sync when tempo is changed. When tested, I changed the tempo around the range from 100 to 200.

The video on following link shows the test setup I used, and out of sync behavior of MIDI Pattern.
- https://drive.google.com/file/d/1YastXoZPU3fkGaWijog1M6RPXCqQjZy4/view?usp=sharing
