### ISSUE TITLE
carla-jack-multi is not displaying patchbay view under NSM protocol

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#1211]
Is that wanted ?
I think patchbay view is always useful, even with NSM . What's about .json canvas files ?
If it is not a bug, what would you suggest ? To use Catia ?

**Comment by moonshaadow** [comment]
Hum... strange, I use carla-git, and I have updated it today...
Current version : 5:2.2~rc1+git20200713

**Comment by falkTX** [comment]
Needs to be even more recent than that. I have not updated the version in the kxstudio repos yet

**Comment by moonshaadow** [comment]
Ok. Sorry I am too impatient sometimes ;)
Thank you for your good work!
