### ISSUE TITLE
no MIDI after update

### ISSUE THREAD

**Issue by tank-trax** [falkTX/Carla#1212]
Debian Buster
Carla 2.2.0-RC1

recently updated Carla and am not getting MIDI input
tested other hosts and they are working

Audio out works if playing the virtual keyboard

**Comment by falkTX** [comment]
damn, must be a regression of adding the new "send midi notes" option. but I made it inverse in code so it would be on by default..
which plugin type does not have midi input? err just need some details, likely I just missed something obvious

**Comment by tank-trax** [comment]
sorry can't test now... but every Instrument I tried failed. will be back in 4-5 hours

**Comment by falkTX** [comment]
all plugins I tried work though..

**Comment by tank-trax** [comment]
maybe it's something local on my system, will get back with more info once I can run some tests but a2jmidid works in all other hosts, ALSA MIDI is OK, just not in Carla

**Comment by falkTX** [comment]
Try to see if you can get some logs, maybe there is an error there.
I am holding off the release until we confirm this.

**Comment by tank-trax** [comment]
I have an earlier local build version 2.1.0 with no 32 bit or WINE support but it does allow for VST3 and MIDI works with that version, 

trying uninstall and reinstall

Carla 2.1.1  (with no VST3 support) is OK = MIDI input works

tried Carla git version 2.2.0 RC1 and same thing = MIDI input does not work
also built the latest commit a5ae5f and it also does the same thing = MIDI input does not work

**Comment by tank-trax** [comment]
OK. I see what the issue is... 

Send Notes is not selected by default. Once selected things work.

![image](https://user-images.githubusercontent.com/41337033/87842873-e7952580-c87d-11ea-804e-ef7b381204f3.png)

**Comment by falkTX** [comment]
is this a linux vst3? I tried with internal plugins and also lv2 and even bridges, all worked

**Comment by falkTX** [comment]
ok my bad, my testing was limited. loading a project works, and when loading a new plugin and using the provided midi keyboard it all works too. but not when sending midi to new synths. got a fix now.

**Comment by falkTX** [comment]
Fixed in 6dbe64bc1f01906f92e6a1b75e010e10c38fc6eb
