### ISSUE TITLE
Saving, reopening, resaving, and reopening an internal patchbay causes plugin parameter problems

### ISSUE THREAD

**Issue by to7m** [falkTX/Carla#1217]
When loading a patchbay plugin within Carla, parameters are lost after saving and reopening.

For an “internal” format patchbay:
* Add a plugin
* Save the patchbay
* Open that saved file
* Try to change something - it will ping back to a set value and the display will glitch

For an LV2 format patchbay:
* Add a plugin
* Change a parameter
* Save the patchbay
* Open that saved file
* Change a parameter
* Save the patchbay again
* Open that new saved file
* The original parameter change is gone

[youtube link showing the problem](https://www.youtube.com/watch?v=_b8py6sFeXE)

**Comment by to7m** [comment]
Is it possible to find, from a patchbay plugin's GUI, some text that shows what parameters it thinks are loaded?

**Comment by to7m** [comment]
One thing that might be relevant: If using an “internal” format patchbay plugin, then if you add some plugins within that along with an internal patchbay plugin (either “internal” or LV2), then if you click Edit for the outermost patchbay plugin, then Parameters, it will show parameters for all the other plugins, but not for the patchbay plugins.

Maybe troubleshooting would be easier if we could see what data the outermost patchbay is storing for any patchbay plugins?

**Comment by zynmuse** [comment]
I have same problem ( besides zynaddsubfx  parameters not saving which I reported some time ago).

Plugin "Midi note to CC" always forgets parameter " Operation Mode". 
I set it to 2 and save then reload and it reverts back to 0.

I am using ubuntu 18.04 on AMD64 and carla version 2.1.0

**Comment by to7m** [comment]
> I am using ubuntu 18.04 on AMD64 and carla version 2.1.0

please see [this issue](https://github.com/falkTX/Carla/issues/1171)

**Comment by falkTX** [comment]
Video was very helpful, thanks!

**Comment by to7m** [comment]
This example is now fixed. This makes things a lot easier for me, thank you! There are still a few other glitches which I am trying to find reproducible examples for — I think I will make separate issues for these.
