### ISSUE TITLE
Standalone fails to load configuration due to TCP/UDP assertions

### ISSUE THREAD

**Issue by gnif** [falkTX/Carla#1218]
https://github.com/falkTX/Carla/blob/f07b0d867868ab39082414f4bc1efa736b933632/source/backend/CarlaStandalone.cpp#L732
https://github.com/falkTX/Carla/blob/f07b0d867868ab39082414f4bc1efa736b933632/source/backend/CarlaStandalone.cpp#L737

These assets are being triggered after upgrading to the latest version of carla when running in standalone mode preventing it from loading the specified configuration. In my configuration TCP and UDP are not in use.

**Comment by falkTX** [comment]
This is not a reason to fail to "load configuration"
Those 2 specific items will fail, but the rest should still work as usual.

The assertion is there to prevent bad values from being used.
If you change the OSC settings and restart carla, the warnings should go away. Can you confirm?

**Comment by falkTX** [comment]
Can you confirm please?

**Comment by gnif** [comment]
I am sorry but I have not had an opportunity to re-test this. I will close this for now, if it happens again I will do more diagnostics and re-open this if it's a valid issue.
