### ISSUE TITLE
ui_closed() callback (external UI) is not called by carla

### ISSUE THREAD

**Issue by alex-tee** [falkTX/Carla#1224]
closing carla patchbay UI (lv2 plugin) in zrythm causes a segfault because zrythm is trying to call `run()` on the external UI after the UI is closed
`ui_closed()` is not called by carla before that
Carla 2.2.0-beta1 started, status:
  Python version: 3.8.2
  Qt version:     5.14.2
  PyQt version:   5.14.2

**Comment by alex-tee** [comment]
note that I dont have this issue with BBC meter, which also uses external UI

**Comment by falkTX** [comment]
Did we solve this already?
You were trying to get the ui-closed for the custom plugin you opened, right? the main `ui_closed` refers to carla-rack UI, which you never open in the first place.

**Comment by alex-tee** [comment]
no i am doing it similar to rgareus' jalv patch for kx external UIs and it's still broken in zrythm.

this is about the actual carla plugin, not plugins opened through the API.

the relevant code is in here line 1260 until the end of the file: https://git.zrythm.org/cgit/zrythm/tree/src/plugins/lv2/lv2_gtk.c?h=v0.8.797#n1260
`on_external_ui_closed()` is not called when the  UI closes to set `visible` to false, so the flow enters line 1286 and calls `run()` after the UI is closed, which causes a segfault

**Comment by falkTX** [comment]
Looking at the code, I can see how this could happen.
Is the `LV2_External_UI_Host` feature you pass to the plugin is on the stack?

Carla takes a pointer to this variable at https://github.com/falkTX/Carla/blob/master/source/plugin/carla-lv2.cpp#L626
It is later called at https://github.com/falkTX/Carla/blob/master/source/plugin/carla-lv2.cpp#L818
But by that time, your `LV2_External_UI_Host` feature variable is no longer in the stack, thus carla has a pointer to a random value.

Try to allocate or put the LV2_External_UI_Host on the plugin/ui struct, so the pointer remains valid for the lifetime of the UI.
That might just fix the issue.

**Comment by alex-tee** [comment]
ah! nice find, thanks, it works fine now!
