### ISSUE TITLE
Carla [Windows 7 32 bits] Error at launching the program

### ISSUE THREAD

**Issue by Razmus02** [falkTX/Carla#1227]
Well, I'm new to using Carla, and I couldn't even install it properly, this is the error I get (I don't use any other systems or linux and others as such, I just need it for voicemeeter)
https://kx.studio/Applications:Carla
I've used this link to download the program.
When I try to open the program even as an administrator what it says is this.
My PC is in spanish so I'll try to translate as much as I can:
-gxx-personality-sj0 not found on libstdc++-6.dll.
And when I press the accept button what happens next is this line of code as an error:
![ErrorCarla](https://user-images.githubusercontent.com/68974668/88861770-0f1cb400-d1d5-11ea-883c-32fde39c1086.png)

**Comment by falkTX** [comment]
Please try with the RC3 builds, I believe this is fixed now.
https://github.com/falkTX/Carla/releases/tag/v2.2.0-RC3

**Comment by Razmus02** [comment]
> 
> 
> Please try with the RC3 builds, I believe this is fixed now.
> https://github.com/falkTX/Carla/releases/tag/v2.2.0-RC3

Unfortunately, this error happens when I tried to open the program, I've downloaded the 32 bits .zip, 
![Carla Error Report 01](https://user-images.githubusercontent.com/68974668/94102746-3a083a80-fe09-11ea-8583-059e34d1f1ea.png)
![Carla Error Report 02](https://user-images.githubusercontent.com/68974668/94102749-3b396780-fe09-11ea-82dc-1169b2791a4d.png)
This is the error that I got, if you could instruct me on how to fix it or how to install it if needed, please let me know, again, thank you for your work on the bug fixes.
You're awesome.

**Comment by falkTX** [comment]
I think you must have a libstdc++-6.dll file installed somewhere that overrides the one used by carla.
Removing that file from the system should help.

Otherwise, you will have to wait for carla v2.3 where I will change how carla is built

**Comment by falkTX** [comment]
Release is out, closing issue.
