### ISSUE TITLE
[Windows] ValhallaRoom_x64 crashes carla-discovery-native.exe

### ISSUE THREAD

**Issue by syboxez** [falkTX/Carla#1231]
gdb backtrace:

Starting program: /c/Program Files/Zrythm/bin/carla-discovery-native.exe vst "C:/Program Files/VstPlugins/ValhallaDSP/ValhallaRoom_x64.dll"
[New Thread 5628.0x82c]
[New Thread 5628.0xa70]
[New Thread 5628.0x3fc]
warning: Attempting to load VST: C:\Program Files\VstPlugins\ValhallaDSP\ValhallaRoom_x64.dll
warning: Creating VST instance: ValhallaRoom_x64

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffa2aa22537 in ?? ()
   from /c/Program Files/VstPlugins/ValhallaDSP/ValhallaRoom_x64.dll
(gdb) bt
#0  0x00007ffa2aa22537 in ?? ()
   from /c/Program Files/VstPlugins/ValhallaDSP/ValhallaRoom_x64.dll
#1  0x00007ffa2aa293d9 in ?? ()
   from /c/Program Files/VstPlugins/ValhallaDSP/ValhallaRoom_x64.dll
#2  0x00007ffa2aa29089 in ?? ()
   from /c/Program Files/VstPlugins/ValhallaDSP/ValhallaRoom_x64.dll
#3  0x00007ffa2ab35f23 in ?? ()
   from /c/Program Files/VstPlugins/ValhallaDSP/ValhallaRoom_x64.dll
#4  0x00007ffa2ab3b449 in ?? ()
   from /c/Program Files/VstPlugins/ValhallaDSP/ValhallaRoom_x64.dll
#5  0x00000000005a698e in carla-discovery-native!_ZN22_CarlaCachedPluginInfoC2Ev ()
#6  0x00000000004e840d in carla-discovery-native!_ZN22_CarlaCachedPluginInfoC2Ev ()
#7  0x0000000000585fa3 in carla-discovery-native!_ZN22_CarlaCachedPluginInfoC2Ev ()
#8  0x000000000068ca23 in carla-discovery-native!_ZN22_CarlaCachedPluginInfoC2Ev ()
#9  0x00000000004e7d37 in carla-discovery-native!_ZN22_CarlaCachedPluginInfoC2Ev ()
#10 0x000000000042755c in ?? ()
#11 0x0000000000825fd1 in carla_juce_init ()
#12 0x00000000004013bd in ?? ()
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x00000000004014cb in ?? ()
#14 0x00007ffa435b7974 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#15 0x00007ffa43cfa271 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#16 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by moonshaadow** [comment]
FWIW, this plugin works correctly on linux through Wine.

**Comment by falkTX** [comment]
Plugin is running fine here.

Try updating carla and the plugin.

![Screenshot_20200924_035837](https://user-images.githubusercontent.com/1334853/94095730-3f21b580-fe1a-11ea-90a4-994b14f62398.png)
