### ISSUE TITLE
Carla plugin bridge for the requested arch (win32) does not exist

### ISSUE THREAD

**Issue by phil123456** [falkTX/Carla#1235]
Hello,

is it possible to build Carla on a raspberry PI ?

```
make
sudo make install
```

I got  `resource folder does not exist, is Carla installed?`

I created the missing folders

now I get a missing exec file ????? and it's nowhere to be found on the system

```
carla-single win32 vst vst/Ambience.dll 
/usr/local/lib/carla/carla-bridge-win32.exe
Carla plugin bridge for the requested arch (win32) does not exist
```

apparently the packages are not available

```
pi@raspberrypi:~ $ sudo apt-get install carla-git carla-bridge-win32 carla-bridge-wine32
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package carla-git
E: Unable to locate package carla-bridge-win32
E: Unable to locate package carla-bridge-wine32
```

can you help me compile and install Carla on my raspberry PI ?

thanks

**Comment by falkTX** [comment]
the wine bridges do not work on the raspberry pi, I have not even attempted to make it work since it is quite obvious it won't be sucessful. sorry.

**Comment by phil123456** [comment]
becos the cpu is ARM or what ?
I'll play with LV2 plugins

I just managed to make jalv compile and work

thanks anyway, I mean for all the work you accomplished so far
quiet impressive

**Comment by falkTX** [comment]
Yes, because of being ARM.
There is a project that started being able to load win64 binaries in ARM64, but still early stages.
