### ISSUE TITLE
Close project file when engine is stopped (data loss)

### ISSUE THREAD

**Issue by jkoderu-git** [falkTX/Carla#1243]
Open project file, stop engine, press yes to remove loaded plugins, start engine again and press save. Carla overwrites the project file with an empty project file loosing data. I did not have a backup of the file #338. I am attempting to recover it with file recovery tools

**Comment by moonshaadow** [comment]
If you remove plugins then you save the project, it makes sense to have an empty project, right? 
There is no backup feature for now. Be careful when you save a project, it will save plugins as they are loaded. No plugins = empty session.

**Comment by jkoderu-git** [comment]
I recovered the project file successfully.

> If you remove plugins then you save the project, it makes sense to have an empty project, right?

Yes, but I did not explicitly removed the plugins. I stopped the engine and in order to do it Carla asks to remove all plugins. I expect starting it is going to load them again, the filename of the project is still in the Carla window title.
