### ISSUE TITLE
Carla VST gui makes Ardour crash

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#1244]
Carla vst works fine without GUI, but opening gui or loading the plugin makes Ardour unusable
Carla lv2 is ok.

It has happened since last update. Possibly related to #1229 
```
Using Carla version 5:2.2~rc1+git20200818
  Python version: 3.6.9
  Qt version:     5.9.5
  PyQt version:   5.10.1
Ardour5.12.0 (construit avec 5.12 et GCC version 5.2.1 20150903)
```
[EDIT] Carla vst works fine in Qtractor and Bitwig

**Comment by moonshaadow** [comment]
Same problem with Ardour 6.2.213

**Comment by falkTX** [comment]
I was not able to trigger a crash, but was able to get ardour to freeze.
Pushing a fix now.

**Comment by moonshaadow** [comment]
Nice, thank you
