### ISSUE TITLE
Carla_2.2.0-RC1-macos-10.12.dmg requires newer macOS version (> 10.15) to run

### ISSUE THREAD

**Issue by htcl2k20-PMN** [falkTX/Carla#1247]
trying to start Carla on macOS 10.13.6 shows me that error and will not start:
![image](https://user-images.githubusercontent.com/64279322/91872555-45d46700-ec78-11ea-98b0-6d9031f45886.png)

**Comment by falkTX** [comment]
that is a bummer.
the code is able to run on old versions, but I do not have a way to build under 10.12 or 10.13.

Does the 10.8-compat version works for you?

**Comment by htcl2k20-PMN** [comment]
the download took a bit, but yes, this one works, thank you 👍 
Are there special build requirements, if not I could try to build on the 10.13.6 available on this older machine?

**Comment by falkTX** [comment]
the macos build steps are not fully documented. for now I just run it manually.

if you really want to try it yourself, just to see if you can build it, check `./data/macos/build-deps-new.sh`, there are a few external things needed from macports.
this script will download and build all the dependencies.
would be very interesting to know if it fails at some point.

and again, nothing in carla needs such new macos stuff. it is compatible with 10.8, which I use to build the "compat" version.
Qt5.9 is patched to bring compatibility with 10.8.

also, if there is a way to for sure force the macos version it depends on, I am open to it. just dont know what else to put there right now, as the usual tricks for backwards compatibility are already being used.

**Comment by htcl2k20-PMN** [comment]
macos is not really my native environment, so I cannot tell that much about compatibility.
Just curious if Carla would build correctly here, so how to continue, with mac-build-test.sh or simply build.sh?

**Comment by falkTX** [comment]
you run the build.sh script after build-deps-new.sh one.

(mac-build-test.sh one is an old thing I should delete)

**Comment by htcl2k20-PMN** [comment]
for package building Python is needed as it seems , just V3 or something special?

**Comment by falkTX** [comment]
see the top line on build-deps-new.sh, all the external dependencies are there (except xcode, that is needed all the time)
everything else not mentioned at the top of the file, carla will build during that script setup.

**Comment by htcl2k20-PMN** [comment]
xcode is the problem, the version in the appstore requires a newer OS than mine, so we are out of luck here.
If you are interested in havin an alternative environment I can try to workaround and set it up somehow different, but for the time being I will continue with my tests bridging the best of macOS / Linux with hopefully some help of Carla;-)

**Comment by falkTX** [comment]
> xcode is the problem, the version in the appstore requires a newer OS than mine, so we are out of luck here.

ah that, I have an image of xcode for 10.8 just for the case I reinstall it. it is very annoying having to install xcode just to get a few tools (clang and make) plus the SDKs.
might be possible to find semi-official links for older xcode, but whatever you trust those or not is up to you. understandable if not.

**Comment by htcl2k20-PMN** [comment]
found something official in the Apple dev zone, but will have to free up some disk space in my triple boot environment or re partition here because for whatever reason this needs a lot of space in the Apple world.
If you are interested I will continue with this tomorrow. This machine will never be upgraded to something newer because 
- Apple does strange things in newer versions and
- it is out of support for newer versions anyway
 so if you need things to be tested on macOS versions between yours I will be happy to help out if I can ..

**Comment by falkTX** [comment]
no worries.
the building process will also need quite some space too though.. so perhaps overkill.
It is just hard to get a machine working with such a version, or VM, or hackintosh. 

do you happen to know if it is possible to setup a dual-boot for an older and newer version of macos?

**Comment by htcl2k20-PMN** [comment]
not being a Mac expert and not having tons of expertise in that specific area, dualboot should be easily possible on not extremely new hardware, e.g.  -> 
https://www.macworld.co.uk/how-to/mac-software/dual-boot-mac-3659676/
But let me ask a colleague who designs hackintoshes for heavier media productions and may know more (this may take a few days ..)
But again, if I can really help with the tools I have I am happy to do so, overkill or not. That's what open source is about somehow, no? I have enjoyed a lot using your tools and even the KXstudio distro for short that time back, so if there is something to contribute back what makes some sense ..

**Comment by falkTX** [comment]
just getting the thing to build on real 10.12 will be useful. that will tell us if something is wrong with the current setup scripts.
maybe you can try running the new carla binary from a terminal? that should have some info on why it cannot run

**Comment by falkTX** [comment]
I was able to get 10.12 installed in a VM. Will use that for v2.2 macOS-10.12 builds.

Can you please try the RC3 and confirm if it works for you? thanks a lot!
https://github.com/falkTX/Carla/releases/tag/v2.2.0-RC3

**Comment by falkTX** [comment]
This was fixed in 2.3.1, which was built in a macOS 10.8 system
