### ISSUE TITLE
Incorrect CC values scaling (all the time, all plugins)

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#1249]
Hey there.

Carla transforms some parameters values, independently of clients.
i.e. : value 52 becomes 51, value 9 becomes 8. (I haven't tested all values)

Steps to reproduce : 
- Open carla and load any plugin with midi in and out ; 
- Use EXTERNAL tools to generate and monitor MIDI (I had personally used my midi keyboard and Gmidimonitor, tools inside Carla give false results)
- Generate any CC parameter with value = 9 or value = 52 , with MIDI monitoring before and after carla.

If you use i.e. carla-patchbay and just connect carla midi IN to carla midi OUT without plugin, there is no value's change. Change occurs as soon as midi signal crosses a client.
If you monitor inside carla, you will see that change is already done.

**Comment by falkTX** [comment]
This is not happening in multi-client mode, maybe specific to the patchbay mode.

**Comment by falkTX** [comment]
cant reproduce this. I generate a CC with xycontroller tool, and verify the values with jack_midi_dump tool.
values match before and after carla. (there is a simple midi gain plugin inside)

![image](https://user-images.githubusercontent.com/1334853/92323408-644bb100-f030-11ea-8485-d6779d452429.png)

**Comment by moonshaadow** [comment]
This is happening in multi-client mode as in patchbay or plugin mode.
This is on specific values, like there was a kind of scaling or rounding somewhere. Values affected, if I'm not wrong : 9, 13, 18, 26, 36, 52, 72, 104. This is independent  of CC number or channel number.

Here with xy controller, midi-gain in carla, Gmidimonitor: 
![Capture d’écran_2020-09-08_21-05-16](https://user-images.githubusercontent.com/29754932/92560773-40c47880-f273-11ea-9f6d-6dea0ce2b929.png)

Here in Ardour : Midi 1 has MidiGain.lv2, Midi 2 has the same plugin in carla-rack and the same midi source.  : 
![Capture d’écran_2020-09-08_21-17-30](https://user-images.githubusercontent.com/29754932/92561264-322a9100-f274-11ea-8287-a1fc82e035a5.png)
