### ISSUE TITLE
Plugin's GUI doesn't open in Patchbay view (Multi client JACK)

### ISSUE THREAD

**Issue by john-bonachon** [falkTX/Carla#1268]
Hi falk, I'm running on Ubuntu 20.04.1 LTS, carla (5:2.1.1+git20200611)

I've noticed that I can no longer double click plugins in Patchbay mode to open the GUI, neither right-click Edit.
I can only open GUI on the Rack tab.

Btw, is there a way to default to Patchbay tab? I've never used the rack mode, and always need to make an extra click when opening Carla. That's minor anyway.

**Comment by falkTX** [comment]
> I've noticed that I can no longer double click plugins in Patchbay mode to open the GUI, neither right-click Edit.
> I can only open GUI on the Rack tab.

This is expected if you use jack multi-client mode in carla and your jack version is jack2 below < 1.9.13
Either find a way to update jack2, or switch to jack1. Or also use carla engine in patchbay mode



> Btw, is there a way to default to Patchbay tab?

Not at the moment

**Comment by john-bonachon** [comment]
thanks for the quick reply! I couldn't find any info on internet, now it's clear.

**Comment by colmoni** [comment]
I had this issue and it was solved by using the Git version of Carla and the 1.9.14 Jackd2 backport build from Ubuntu Studio.

I've installed a new system with Hirsute, running Jackd2 1.9.17, and the issue has returned.

**Comment by falkTX** [comment]
make sure that you can use jack metadata on that system.
this has never been a carla issue, but one with jack setup.

**Comment by colmoni** [comment]
Thanks, I'll check those out. It may be Ubuntu Studio controls doesn't support metadata, so I'll try Qjackctl instead.

**Comment by falkTX** [comment]
that wont change a thing.

**Comment by colmoni** [comment]
I found the metadata options on QJackctl and turned them all on. I'm using it to launch my Jack server. Still no GUIs or patchbay position persistence on reload.

**Comment by colmoni** [comment]
The jack_property -l command cannot retrieve anything, if that answers your question re: metadata.
