### ISSUE TITLE
Carla 2.2.0 does not save canvas position

### ISSUE THREAD

**Issue by jkoderu-git** [falkTX/Carla#1274]
Create new project with Carla jack multi-client and save it, the json file is not created. Every time Carla engine is stopped and started and the project is loaded the plugins in canvas have random position.

**Comment by falkTX** [comment]
Which version of JACK are you using? 1.9.12 or lower does not support what carla needs.
See "Notes for users" in https://kx.studio/News/?action=view&url=carla-plugin-host-v22-is-finally-here

**Comment by jkoderu-git** [comment]
- I use jack1.9.14. Projects made with Carla 2.1.1 which have the json file are restored successfully with their position. Projects with Carla 2.2.0 change position starting from the second or third time the project is opened.

- After some time of opening the projects again and again, pulseaudio jack sink, pulseaudio jack source, system capture, system playback and the connections between plugins disappear visually but audio continues to work. It works after closing Carla completely and open again.

- After some time, when you click "stop engine" the entry to start engine is greyed out as it is still running but it is not. The clickable entry "stop engine" logs to console `carla_engine_close: Engine is not initialized`. It works after closing Carla completely and open again.

**Comment by falkTX** [comment]
This issue is new to me, dont really know what is happening there.

When you save a carla project, do you see the positions saved inside the project file?
You should have something like this:
```
  <Positions>
   <Position x1="1422" y1="1056">
    <Name>Carla</Name>
   </Position>
   <Position x1="1046" y1="849" x2="1524" y2="780">
    <Name>system</Name>
   </Position>
   <Position x1="1059" y1="1151" x2="1550" y2="1153">
    <Name>a2j</Name>
   </Position>
   <Position x1="1238" y1="644">
    <Name>PulseAudio JACK Sink-01</Name>
   </Position>
   <Position x1="1692" y1="908">
    <Name>PulseAudio JACK Source-01</Name>
   </Position>
   <Position x1="1054" y1="778">
    <Name>PulseAudio JACK Sink</Name>
   </Position>
   <Position x1="1557" y1="892">
    <Name>PulseAudio JACK Source</Name>
   </Position>
  </Positions>
```

**Comment by jkoderu-git** [comment]
No, I do not have positions saved.

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE CARLA-PROJECT>
<CARLA-PROJECT VERSION='2.2'>
<EngineSettings>
<ForceStereo>false</ForceStereo>
<PreferPluginBridges>false</PreferPluginBridges>
<PreferUiBridges>false</PreferUiBridges>
<UIsAlwaysOnTop>false</UIsAlwaysOnTop>
<MaxParameters>200</MaxParameters>
<UIBridgesTimeout>4000</UIBridgesTimeout>
</EngineSettings>

<Transport>
<BeatsPerMinute>120</BeatsPerMinute>
</Transport>

<ExternalPatchbay>
<Connection>
<Source>system:capture_1</Source>
<Target>PulseAudio JACK Source:front-left</Target>
</Connection>
<Connection>
<Source>system:capture_2</Source>
<Target>PulseAudio JACK Source:front-right</Target>
</Connection>
<Connection>
<Source>PulseAudio JACK Sink:front-left</Source>
<Target>system:playback_1</Target>
</Connection>
<Connection>
<Source>PulseAudio JACK Sink:front-right</Source>
<Target>system:playback_2</Target>
</Connection>
</ExternalPatchbay>
</CARLA-PROJECT>
```

**Comment by falkTX** [comment]
hmm might be that your jack build does not support meta-data then.
when carla is running and some plugins loaded, do you get empty output when running
```
jack_property -l
```
that would confirm it

**Comment by jkoderu-git** [comment]
`could not retrieve all properties`. What can I do to enable metadata? I use Cadence to manage jack and pulseaudio.

Many thanks for your fast answers.

**Comment by falkTX** [comment]
I dont know what your linux distro is, but it will need a change there.
jack2 needs to be rebuild with meta-data support enabled.

**Comment by jkoderu-git** [comment]
The jack2 build script of my distro (void linux) does not have `db-devel` dependency which provides the needed `db.h` file for metadata support.

I rebuild jack with db-devel and `jack_property -l` displays all the output. Thank you for your help.

**Comment by falkTX** [comment]
Great, so carla should be able to handle the positions now. please verify, thanks

**Comment by jkoderu-git** [comment]
Sorry for the delay, yes carla saves and restore positions now. Thanks again!
