### ISSUE TITLE
No module named 'ui_carla_host'

### ISSUE THREAD

**Issue by hasikome** [falkTX/Carla#1283]
**i just download carla from here and try to run without install from "/Downloads/Carla-master/source/frontend$" here is the output;**

Traceback (most recent call last):
  File "/home/lala/Downloads/Carla-master/source/frontend/./carla", line 22, in <module>
    from carla_host import *
  File "/home/lala/Downloads/Carla-master/source/frontend/carla_host.py", line 53, in <module>
    import ui_carla_host
ModuleNotFoundError: No module named 'ui_carla_host'

**and when i try to install from "/Downloads/Carla-master$"  as "sudo make install" here is the output;**

Create directories
install -d /usr/local/bin
install -d /usr/local/lib/carla/jack
install -d /usr/local/lib/pkgconfig
install -d /usr/local/include/carla/includes

 Install script files (non-gui)
install -m 755 \
	data/carla-single \
	/usr/local/bin
 Adjust PREFIX value in script files (non-gui)
sed -i -e 's?X-PREFIX-X?/usr/local?' \
	/usr/local/bin/carla-single
 Install backend libs
install -m 644 \
	bin/libcarla_*.* \
	/usr/local/lib/carla
install: cannot stat 'bin/libcarla_*.*': No such file or directory
make: *** [Makefile:441: install_main] Error 1

**, here is my distro info**
/Downloads/Carla-master$ cat /etc/linuxmint/info
RELEASE=20
CODENAME=ulyana
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 20 Ulyana"
DESKTOP=Gnome
TOOLKIT=GTK

**Comment by falkTX** [comment]
you need to run `make` once so it actually compiles/builds the code.

**Comment by falkTX** [comment]
closing ticket as invalid
