### ISSUE TITLE
jack applications not working on aarch64 = 64bit arm

### ISSUE THREAD

**Issue by hexdump0815** [falkTX/Carla#1286]
hello,

i'm trying to get vcvrack as a jack application working in carla on aarch64 (ubuntu 18.04 on 64bit arm) and it starts vcvrack properly but does not seem to recognize that it started as the "loading jack application" window stays open forever and blocks carla (logs look all ok and no error messages shown anywhere) ... i tried the exact same setup (i.e. same ubuntu version, same build version of carla - 2.2.0 btw. - and vcvrack etc.) and there everything is working well and as expected.

are jack applications expected to just work on aarch64 or have they never been tested on that arch maybe? are there maybe any x86 specifics used when waiting the jack application to start?

a lot of thanks in advance and best wishes - hexdump

**Comment by hexdump0815** [comment]
i just tried it on armv7l (same setup on 32bit arm) and there it works well too - just like on x86_64 - so the problem seems to be aarch64 specific ...

**Comment by hexdump0815** [comment]
i tried it on ubuntu 20.04 as well to rule out problems of a specific ubuntu version, but the problem is there same there too.

**Comment by hexdump0815** [comment]
is there any good way to debug something like this, any debug options etc.in carla? can you maybe point me to the places in the code where the jack application starting happens and where carla is waiting for the application to appear? maybe i can run carla in gdb around there ...

**Comment by falkTX** [comment]
there is a checkbox when adding a jack application, allowing to run externally (which is for debugging)

**Comment by hexdump0815** [comment]
i tried that, started carla, added the jack application with that option, set the env variables before starting vcvrack, vcvrack start properly but carla is still waiting - it looks like it is not properly recognizing that vcvrack is up already ...

in the env variables i noticed that it contains a shared mem id - i checked with "ipcs -a" before starting carla, after starting it and after starting the jack application and in the last two steps each time a new shared memory entry is created ... not sure if this is related or helps

**Comment by hexdump0815** [comment]
a little update: i just tried it on another aarch64 machine (allwinner instead of amlogic) and there to my surpise it works as expected ... so looks like its related to the opengl hackery i had to do to make it work on arm: gl4es plus gpu accelerating legacy mali blob to run vcvrack and carla running using mesa software rendering as it does not start with the other hack on the amlogic side and mesa software rendering only for everything on the allwinner side ... or it is related to maybe some bugs on amlogic side ... at least that hacky way to run opengl via gl4es and legacy mali blob works fine for arm7l, thus i did not expect this to be a problem ... in the end it seems to not be a carla problem and thus i'm closing this issue now ...

**Comment by hexdump0815** [comment]
seems to be an amlogic soc related problem (or my kernel is missing something): i just tried it by configuring away all libmali related stuff, so that it also only uses mesa software rendering, but the problem is still there ...

**Comment by hexdump0815** [comment]
another update: it is that mali blob in the end - i was able to get it working with full mesa software rendering even on amlogic now ... lets hope the lima project gets the remaining bugs which prevent vcvrack from using it fixed so that i can finally switch to a fully open source gpu accelrated opengl setup on aarch64 without the need for any binary blobs ...
