### ISSUE TITLE
Build failure: GCC 4.8.5 - corecvt

### ISSUE THREAD

**Issue by h1z1** [falkTX/Carla#1288]
Not sure how you'd want to handle this tbh, old as it is 4.8.5 is still used in CentOS.  Make fails building juce

```
In file included from format_types/juce_VST3Headers.h:107:0,
                 from format_types/juce_VST3PluginFormat.cpp:28,
                 from juce_audio_processors.cpp:152:
../../includes/vst3sdk/base/source/fstring.cpp:234:21: fatal error: codecvt: No such file or directory
 #include <codecvt>
                     ^
compilation terminated.
```

TBH I'm not entirely sure why that is failing.  The header is present

```
$ find /usr/include/c++/4.8.5/ -name  codecvt.h
/usr/include/c++/4.8.5/bits/codecvt.h
$
``

**Comment by falkTX** [comment]
VST3 SDK does not support gcc4, nothing I can do for that.
so you need to build carla with `make USING_JUCE=false`

**Comment by h1z1** [comment]
I did that, it still failed to build.  Should the makefile not detect compiler version/features?

**Comment by falkTX** [comment]
you might need a few commits from git master
like https://github.com/falkTX/Carla/commit/f2692659aa5f0ed91d3e8b0a8e0652d530ce279a
