### ISSUE TITLE
Compilation failing on Zyn: Invalid use of incomplete type 'mxml_node_t' {aka 'struct _mxml_node_s}

### ISSUE THREAD

**Issue by IanCaio** [falkTX/Carla#1289]
I'm trying to compile the master branch of Carla and everything seems to be compiling fine until I reach the ZynAddSubFX compilation. I start getting lots of compilation errors, all of which complain about invalid uses of incomplete type `mxml_node_t` (or `const mxml_node_t`).

`make features` don't complain about anything missing for Zyn:
```
---> Main features 
Front-End:     YES
LV2 plugin:    YES
VST2 plugin:   YES
Link support:  YES
OSC support:   YES
Binary detect: YES

---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  YES
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]
WASAPI:      NO  [Windows only]

---> Plugin formats: 
Internal: YES
LADSPA:   YES
DSSI:     YES
LV2:      YES
VST2:     YES (with UI)
VST3:     YES (with UI, using JUCE)
AU:       NO  [MacOS only]

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     YES (bridge)
Gtk3:     YES (bridge)
Qt4:      NO  [Qt4 missing]
Qt5:      YES (bridge)
X11:      YES (direct+bridge)
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
Basic: YES
Extra: NO [FFmpeg missing or too new]
SF2/3: YES
SFZ:   YES

---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: YES

---> External plugins: 
DPF Plugins:  YES (with UI)
DPF ProM:     YES
ZynAddSubFX:  YES (with FLTK UI)
```

And I have both `libmxml1` and `libmxml-dev` installed:

```
ii  libmxml-dev:amd64                             3.1-1                                  amd64        small XML parsing library (development)
ii  libmxml1:amd64                                3.1-1                                  amd64        small XML parsing library (runtime)
```

Is there something about the version of `libmxml`? Looking at `/usr/include/mxml.h` the `mxml_node_t` doesn't seem to be defined and the node type seems to be returned by a method called `mxmlGetType()`, while on the Zyn code it seems to be accessed directly by the pointer as `node->type`. Maybe that was a recent change on `libmxml`?

**Comment by falkTX** [comment]
Those external plugins are not needed, best to build without them.
`make EXTERNAL_PLUGINS=false` should work

**Comment by IanCaio** [comment]
Thanks for the quick response! I was wondering how to compile without those, it worked! Should I close the issue, as they seem to be on the external plugin's end?

**Comment by falkTX** [comment]
yeah, I will close this one.
the plugins are optional, they are not really needed if you have other plugins already installed which is likely the case here.

these plugins are mostly in carla so that it can make noise on systems without any plugins installed whatsoever
