### ISSUE TITLE
eg-sampler chrashed carla

### ISSUE THREAD

**Issue by brummer10** [falkTX/Carla#1295]
Trying to load Exsampler (eg-sampler from the LV2 examples) crashed Carla when you try to enable the UI.

**Comment by falkTX** [comment]
Might be related to https://github.com/lv2/lv2/issues/44 depending on the lv2 package version

**Comment by brummer10** [comment]
eg-sampler 1.18.0-1 from debian/sid failed 
eg-sampler from a fresh git checkout failed as well

libliv is version 0.24.10-1 from debian/sid,

**Comment by falkTX** [comment]
With latest eg-sampler and carla, I cannot reproduce this.

**Comment by brummer10** [comment]
Indeed, with latest carla and the old eg-sampler I can't reproduce it as well any more. Conclusion is, you've fixed it in carla without any code change in eg-sampler needed. Your label "can't reproduce" is a bad sign by the way, as you know. I love when bug fixed that the related issue number is mentioned in the commit message, so that users like me could reproduce the fix, because they could read the related diff. Anyway, close it now

**Comment by falkTX** [comment]
I agree with your points, but there were many changes in carla since the bug was reported (6 months ago). So reaching a specific commit would be a bit time-wasting.
needs-recheck would be a better label, but anyway, thanks for confirming the fix.
