### ISSUE TITLE
Embedding plugin UIs in canvas?

### ISSUE THREAD

**Issue by mxmilkiib** [falkTX/Carla#1296]
Like [Ingen](https://gitlab.com/drobilla/ingen/-/issues/1) (`ingen:uiEmbedded` I think). The ability to change at least some parameters as a first class operation on a canvas view seems to be a keeper paradigm (VCV Rack, Bitwig, MOD, etc).

**Comment by falkTX** [comment]
not interested. maximum is the inline-display on canvas.

getting embed to work on the canvas is very tricky to get right. not just in 1 system, but in 4 or more (Windows, macOS, X11, Wayland, soon BeOS/Haiku)

Even drobilla is considering removing this altogether from ingen last time we talked about it.

Maximum I am willing to go is to have a proxy screenshot of the plugin UI rendered as inline display.
