### ISSUE TITLE
Complete crash on Vital.lv2 with certain presets

### ISSUE THREAD

**Issue by dromer** [falkTX/Carla#1306]
Carla version: 2.3.0-alpha1

Also reported on Vital forums, Carla crashes when selecting the following presets in Vital:

* FM Drum Circle
* Growl Bass Sidechain
* Special Glitch Thing
* Strings Section

With the rest of the presets it seems to be fine.

Kind of nasty and of course shouldn't take Carla down when this happens.

**Comment by falkTX** [comment]
Does it happen with other hosts?
Hard to imagine how this would be Carla's fault here.

Vital is not opensource, I lost interest after hearing about that.

**Comment by dromer** [comment]
I know, but Carla shouldn't go down when a plugin crashes I assume.

Haven't tried any other hosts yet. Will try in qtractor and ardour as well.

**Comment by falkTX** [comment]
> I know, but Carla shouldn't go down when a plugin crashes I assume.

Sadly it does, because in order to prevent that we would have to sandbox each plugin, which would be quite CPU intensive.

Likely this crashes all other hosts in a similar way, if it is a plugin bug

**Comment by dromer** [comment]
Yup, it happens in Qtractor and Ardour as well. Notified them about it.

I thought that Carla could mitigate such crashes, but I understand the limitations there.

**Comment by falkTX** [comment]
Carla can yes, if the crash comes from the UI and the UI is bridged (which only happens for LV2)

For plugins, you can enable the experimental setting to run plugins as bridges.
In the future, I want to have a per-plugin option that allows to run single ones as bridges, not the entire thing. But we are not there yet.
