### ISSUE TITLE
No sound in nogui mode

### ISSUE THREAD

**Issue by 00sapo** [falkTX/Carla#1310]
Hello,
in my Linux 5.4.80-2 (Manjaro) with pulseaudio 14.0,  jackd 1.9.16 and Carla 2.2.0/2.1.1, when running with `-n` option no sound arrives to the output. No roblem when using the gui. I'm using the `patchbay` mode. I tried both the github version and the manjaro official repositories.

There are two errors in the log:

```
LRDF Support not available (LADSPA-RDF will be disabled)
Carla 2.2.0 started, status:
  Python version: 3.6.9
  Qt version:     5.15.2
  PyQt version:   5.15.2
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
Carla assertion failure: "value <= 0 || value >= 1024" in file CarlaStandalone.cpp, line 732
Carla assertion failure: "value <= 0 || value >= 1024" in file CarlaStandalone.cpp, line 737
libjack.so.0 loaded successfully!
Cannot lock down 107341338 byte memory area (Cannot allocate memory)
Carla ready!
```

**Comment by 00sapo** [comment]
I'm running KDE and Manjaro, maybe this is related to https://github.com/falkTX/Carla/issues/1308

**Comment by 00sapo** [comment]
Possible workaround in unix-based systems is using Xvfb virtual display:

```
>>>$ Xvfb :1
>>>$ DISPLAY=:1 carla
```

**Comment by falkTX** [comment]
This should be fixed with the latest 2.3, please check. thanks

**Comment by amazingidiot** [comment]
I have a similar problem, in GUI mode Carla-Rack automatically restores all connections while it stays disconnected in non-GUI mode. I haven't found 2.3 for linux nor was I able to compile it, but you released it yesterday so probably coming in a few days in the fedora repos?
Best regards!

**Comment by 00sapo** [comment]
I assume it works then, let's close this for now
