### ISSUE TITLE
where did carla-bridge-win go?

### ISSUE THREAD

**Issue by uuuuggghhh** [falkTX/Carla#1320]
Why is it gone?

**Comment by falkTX** [comment]
What are you even talking about?

**Comment by uuuuggghhh** [comment]
Ah, sorry for the vagueness. It's no longer available on kx repositories. I'm quite new to linux, so I assumed it must be gone. So bridging 32 bit plugins is still possible with carla? 

I apologise for bothering you with my noobness and thanks for the quick response.

**Comment by uuuuggghhh** [comment]
figured it out, sorry mate

**Comment by falkTX** [comment]
Yeah you must be confusing something. the bridges still there in the repositories, nothing has changed
The latest build of carla-git still has these packages
https://launchpad.net/~kxstudio-debian/+archive/ubuntu/apps/+sourcepub/11827384/+listing-archive-extra

They are still listed on https://kx.studio/Repositories:Applications

Can still reinstall them.

**Comment by uuuuggghhh** [comment]
I got a server error the other day, but it's working now. Thanks!
