### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by Anvolne** [falkTX/Carla#1321]
Hi!

I wrote an example lv2 plugin (a basic gain/amp), but I am unable to run it in Carla.
It found my plugin in the ~/.lv2 folder but when I added it, it said: 
```
Failed to load plugin
Could not find the requested plugin URI in the plugin library
```

I (kinda) followed this tutorial for the lv2: https://lv2plug.in/book/#_simple_amplifier
Is there something I am missing? Is the URI invalid for Carla? I don't own a domain, so I didn't want to write some invalid http://... there.

Specs:
Manjaro 5.9.11-3
Carla installed via `pacman -S carla`

manifest.ttl:
```
@prefix lv2:  <http://lv2plug.in/ns/lv2core#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.

<file:///home/<privacy username>/.lv2/gaintest.lv2/gaintest.so>
  a lv2:Plugin;
  lv2:binary <gaintest.so> ;
  rdfs:seeAlso <gaintest.ttl> .
```

gaintest.ttl:
```
@prefix doap:  <http://usefulinc.com/ns/doap#> .
@prefix lv2:   <http://lv2plug.in/ns/lv2core#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix units: <http://lv2plug.in/ns/extensions/units#> .

<file:///home/<privacy username>/.lv2/gaintest.lv2/gaintest.so>
  a lv2:Plugin, lv2:AmplifierPlugin, lv2:UtilityPlugin, doap:Project ;
  doap:name "Simple Example Amp/Gain" ;
  doap:maintainer <privacy fullname> ;
  doap:license <https://opensource.org/licenses/LGPL-3.0> ;
  lv2:optionalFeature lv2:hardRTCapable ;
  lv2:extensionData state:interface ;
  lv2:requiredFeature urid:map ;

  lv2:port [
    a lv2:ControlPort,
      lv2:InputPort ;
    lv2:index 0 ;
    lv2:symbol "gain" ;
    lv2:name "Gain" ;
    lv2:minimum -56.0 ;
    lv2:maximum 48.0 ;
    lv2:default 0.0 ;
    units:unit units:db ;
  ], [
    a lv2:AudioPort,
      lv2:InputPort ;
    lv2:index 1 ;
    lv2:symbol "input" ;
    lv2:name "Input" ;
  ], [
    a lv2:AudioPort,
      lv2:OutputPort ;
    lv2:index 2 ;
    lv2:symbol "output" ;
    lv2:name "Output" ;
  ];
  rdfs:comment "An LV2 plugin for amplification" ;
.
```

**Comment by falkTX** [comment]
Seems like your plugin is broken, likely the URI you specify on the descriptor given during library load has a typo, or the ttl file.
Please use https://open-music-kontrollers.ch/lv2/lv2lint/ to test for these things instead, not carla.

Oh and you do not have to use a real URL for the plugin. This is a *URI* which is an identifier. not a URL to open.

**Comment by Anvolne** [comment]
Thank you for the linter, I have forgot to change the URI in code from what I copied from the tutorial.

I also was having problems with "Cannot lock down 67 byte memory area" that I fixed by setting the allowable max memory lock in `/etc/security/limits.conf` to unlimited:
```
@audio          -       rtprio          99
@audio          -       memlock         unlimited
```
So I guess there were a few plugins in rack that just fit and this one just happened to go over that limit.
