### ISSUE TITLE
Carla gets no response when loading VST3 plugin in LMMS and fl studio

### ISSUE THREAD

**Issue by hibobmaster** [falkTX/Carla#1325]
Carla version: 2.2.0
LMMS version:  LMMS1.3.0-alpha.1
fl studio: 20.8
Platform: windows10-20H2-19042.685
Carla Rack and Carla Patchbay get no response when loading VST3 plugin in LMMS and Fl studio. #https://github.com/LMMS/lmms/issues/5692#issuecomment-751414995
If i use Carla.exe directly everything works fine.
VST3 sample file: https://csueducn-my.sharepoint.com/:u:/g/personal/bobmaster_csu_edu_cn/EfBY7gntMZtEm2OLc0R-IJsBPcJ_THa2f7JXC1tApbzBLw?e=ArtxnB

**Comment by falkTX** [comment]
Please test with latest 2.3-RC2, I believe this to be already fixed in there.

**Comment by hibobmaster** [comment]
Fixed!
Thank you!
