### ISSUE TITLE
A error with binaries

### ISSUE THREAD

**Issue by afrolino02** [falkTX/Carla#1328]
i've install all binares and packages, i need help with this error
![image](https://user-images.githubusercontent.com/77623794/104921113-e8129400-5966-11eb-83ff-2b8e6276ca6d.png)

![image](https://user-images.githubusercontent.com/77623794/104921292-1c865000-5967-11eb-9cd5-166d490e90f6.png)

**Comment by falkTX** [comment]
so what are you trying to load then?

**Comment by afrolino02** [comment]
I'm trying get my vst for windows, but i can't some plugins and vst are 32 and 64 bits but i can't
![image](https://user-images.githubusercontent.com/77623794/104933632-2748e100-5977-11eb-8263-3b31700ed250.png)
I know this is my problem, on Ubuntu i did't ha ve any issue.

**Comment by falkTX** [comment]
you need to install those bridges then.
carla-bridge... something in AUR I think. I do not use arch, so dont know the names myself. once you install, this will work
