### ISSUE TITLE
sfizz: No sfz path is saved at all

### ISSUE THREAD

**Issue by jamshark70** [falkTX/Carla#1329]
I am not sure if https://github.com/sfztools/sfizz/issues/596 is a bug in sfizz or in Carla.

1. Create a new Carla project.
2. Add a sfizz plugin.
3. Choose a sampled instrument and verify that audio is produced correctly.
4. Save the Carla project to an ext4 filesystem (or any filesystem that supports symlinks).
5. Close Carla.
6. Relaunch Carla and open the project file.
7. Open the sfizz instrument. Now it says "DefaultInstrument" instead of the instrument selected earlier, and it's silent (unsurprisingly, as the interface shows zero zones loaded).

When I inspect the Carla project file, I see *no* xml node for the chosen instrument, and no instrument name anywhere.

https://github.com/falkTX/Carla/issues/1319 refers to symlinks being created when using sfizz in Carla -- but I'm not seeing any directories or symlinks.

sfizz settings are saved correctly in Ardour and Reaper, so I think the issue is not purely sfizz.

**Comment by paulfd** [comment]
Hi ! For me in Carla 2.2 there is still a sine sound after operation 7. Inspecting the `.carxp` file there is no file name saved, may this be the issue?

**Comment by falkTX** [comment]
that would explain it.
please try this in v2.3, should be fixed already

**Comment by falkTX** [comment]
Was not fixed after all, but now is in https://github.com/falkTX/Carla/commit/5f3741c5d81672c4c65c7f02e499078e90e7a64c.
