### ISSUE TITLE
Carla Still bad i've installed all right, whats wrongs? Just pictures.

### ISSUE THREAD

**Issue by afrolino02** [falkTX/Carla#1330]
![image](https://user-images.githubusercontent.com/77623794/105200638-0ebeff00-5b0e-11eb-9320-b4365e074f62.png)
![image](https://user-images.githubusercontent.com/77623794/105200698-1ed6de80-5b0e-11eb-84b0-845fe0676957.png)

i've do make step by step, i can't use carla yet... i have the depencences i need the external plugins

![image](https://user-images.githubusercontent.com/77623794/105201220-9dcc1700-5b0e-11eb-89f1-ff6ad4f0d45f.png)

**Comment by falkTX** [comment]
Sorry but this is an awful way to report things.
I have no idea what this is about...

carla is running right? seems fine to me. the external plugins are not ever needed.
