### ISSUE TITLE
midi input not working on OS X 10.15 with Carla 2.2.0 macOS 10.12 package

### ISSUE THREAD

**Issue by lokkiikkol** [falkTX/Carla#1331]
hi there,

i cannot get any midi input to work on OS X with the aformentioned version of Carla. 
i thought there would be a setting somewhere where i could map my usb-midi devices to Carla, but i cannot find any, do i need an additional program? or should this "just work"? playing au-instruments with the builtin keyboard works flawlessly.
i looked in the Carla preferences and expected a midi menu there, but couldn't find something there.
thanks...

**Comment by falkTX** [comment]
see canvas -> show external. and connect midi devices there

**Comment by lokkiikkol** [comment]
Ouch! So obvious. Sorry...and thanks!

**Comment by falkTX** [comment]
No worries, this should be documented, but I have been working on things rather than writing how they work.
So partially my fault too.
