### ISSUE TITLE
Carla 2.2.0 stable Cannot Run ERROR. cxFreeze

### ISSUE THREAD

**Issue by wygtr22** [falkTX/Carla#1334]
Help me, please.

In my case,
Carla2.2.0stable x64 cannot start, cxFreeze ERROR.

cx_Freeze: Python ERROR.

Traceback(most recent call last):
File "\lib\__startup__.py", line 14, in run
File "\lib\Console.py", line 26, in run
File "\lib\carla", line 22, in <module>
File "\lib\carla_host.py", line 43, in <module>
ImportError: DLL load failed: ??? The specified procedure cannot be found...

##
Carla 2.2.0 RC1 x64 Can start normaly SUCCESS.

## My PC.

DELL note PC: 5482

Windows10 home x64.    ver. 20H2

##
I do'nt know how to fix it.

Please tell me how to fix.

Thank you.

**Comment by YMI-Black-Moon** [comment]
![fb](https://user-images.githubusercontent.com/57836744/106120919-ed0aeb00-6191-11eb-8ce8-ac327d83595b.jpg)
i got the same issue when running carla 2.2.0, also windows 10 home 64bit
i have latest pyphon(3.9.1 64bit) installed
i tried reinstalling pyphon but it still doesn't work

**Comment by falkTX** [comment]
Carla does not use the system python, so that part does not matter.

I am working to get a custom-built python version for carla that will no longer have this issues, coming in v2.3

**Comment by wygtr22** [comment]
Thank you for reply, falkTX.

Now, I'm looking forward to your "good job !".

**Comment by falkTX** [comment]
I got new builds.
Testing is very very much appreciated. I need to confirm that the new stuff works.
Download https://falktx.com/data/Carla-2.3a2-win64-test.zip and extract, then run the "Carla.exe" inside.

Hopefully this finally fixes it.
Thanks

**Comment by wygtr22** [comment]
![スクリーンショット (6)---Cropped](https://user-images.githubusercontent.com/1077356/106372701-df35af80-63b5-11eb-9e37-0c5277fc9303.png)


Thank you for fixing.




Carla-2.3a2 start normally SUCCESS.

Midi work fine.

Audio work fine, too.


But,


In My Case:: some Error occorred.


Carla-Refresh>

ERROR 001::    Search for new ...>

	CANNOT add check-mark to LADSPA, DSSI, VST2, SF2, SFZ

	Able to add Check-mark to LV2, VST3, AU



ERROR 002::     Available tools:>

	X    carla-discovery-native     = Not work.

	X    carla-discovery-win32      = Not work.



ERROR 003::     Unable to press Scan-Button.

Carla Cannot start Scan.




>>>
So, I cannot Refresh All-VST, Sf2,Sfz.



? Am I the only one who gets the error?

Thanks.

**Comment by falkTX** [comment]
That is expected. This binary is not complete, it was just a test to see if it could run.
So that is good news, it means v2.3 will really fix this.

Give me a few more days to finish fixing the last issues and make a release.

**Comment by falkTX** [comment]
The v2.3-RC2 has this fully working now, closing.
