### ISSUE TITLE
When plugin added to patchbay with <Ctrl><A>, right-click shows magnifier (not context menu)

### ISSUE THREAD

**Issue by gwyndaf** [falkTX/Carla#1358]
In the patchbay view, if I add a plugin with Ctrl+A, then right-click on the newly-added plugin, or any other module already in patchbay, magnifier icon is displayed, not the context menu.

In effect, it seems like Carla thinks the Ctrl key is still being pressed.

Adding the plugin using the toolbar button doesn't produce this effect.

A workaround is simply to press and release the Ctrl key, then expected behaviour returns for all modules in the patchbay.

Carla 2.3.0-RC1 on Debian Buster and Debian Bullseye.

**Comment by falkTX** [comment]
> In the patchbay view, if I add a plugin with ,

some crucial element missing there. you mean with ctrl+a maybe?

**Comment by gwyndaf** [comment]
Sorry, brackets got treated as markup. Now fixed.

**Comment by falkTX** [comment]
Fixed in b553ff4ebdd1548db171a2aa883033e7063c8dce
