### ISSUE TITLE
Patchbay context menu items missing (on Debian Testing/Bullseye?)

### ISSUE THREAD

**Issue by gwyndaf** [falkTX/Carla#1359]
In some situations, the right-click context menu for plugins in the patchbay is missing entries such as 'Show Custom GUI' or 'Remove' or 'Replace' and shows only connection-related entries (connect/disconnect/split). Those entries are available if I right-click the same module in the rack view.

This seems to happen on Debian Bullseye. In Windows and Debian Buster, the full context menu is shown.

I don't know if it might be related to QT dependencies: carla-git recommends libqtcore4 and libqtgui4, which aren't available in Bullseye.

Carla 2.3.0-RC1 on Debian Bullseye

**Comment by falkTX** [comment]
Known "issue". See the release notes on https://kx.studio/News/?action=view&url=carla-plugin-host-v22-is-finally-here

The recommends are there so that carla can run qt4 lv2 uis. Ubuntu 18.04 still has a few.
