### ISSUE TITLE
Carla won't open

### ISSUE THREAD

**Issue by akuilera** [falkTX/Carla#1360]
Hi, I had Carla installed before and I used it without a problem. Recently I tried to use it but it just won't open. I tried reinstalling it, as well as uninstalling it a installing again but didn't work. I also downloaded the files on the KXStudio and it opens, but Ubuntu won't recognize it as an application, so I can just see it as an executable file in the folder where I have it.

Is there something else I should do?

**Comment by falkTX** [comment]
I have no idea what you are talking about here, you need to be more clear.
what do you mean by not opening and not being recognized as application?

**Comment by akuilera** [comment]
I mean that I double click it, doesn't matter where and nothing happens. I actually uninstalled it and still appears among my applications... And the other is that I can't see the downloaded file among the applications and can't add it to favorites, has a generic image and I can just open it by going to the containing folder.

**Comment by falkTX** [comment]
just use the command-line to get some output then.
running "carla" should tell you something at least, perhaps even why carla cant start.

regarding the downloads, well, same thing applies. run it from the command-line and post here the output so I can begin to investigate what is going on.

thanks

**Comment by akuilera** [comment]
I'm sorry, I'm not such a pro. I had already tried to find the path before, but got confused, and now I looked on the internet how to do it. This is what I got, maybe I'm doing something wrong, but I can't say what.

![Screenshot from 2021-02-21 00-39-30](https://user-images.githubusercontent.com/31493164/108611266-4fe05280-73dd-11eb-93cb-07d63a85ad4f.png)

If I go to the path /usr/bin/carla there is only one file with the name carla, no folder, and I get this:

![bin](https://user-images.githubusercontent.com/31493164/108611349-2ecc3180-73de-11eb-9ad8-57236ae7dff0.png)


If I go to the path /usr/lib/carla none of them is just carla or carla-bridge-linux64

![lib](https://user-images.githubusercontent.com/31493164/108611352-38559980-73de-11eb-9988-214af250c2ed.png)


If I go to the path /usr/inlude/carla the same as before

![include](https://user-images.githubusercontent.com/31493164/108611372-5cb17600-73de-11eb-9f4d-14f09aaa7bf4.png)


If I go to the path /usr/share/carla there is a file named carla. On the terminal I get this:

![share](https://user-images.githubusercontent.com/31493164/108611376-62a75700-73de-11eb-938b-541d039f75c6.png)


I also tried typing Alt + F2 and then carla and carla-bridge-linux64 but it says that the command is not recognized.

Thank you very much!

**Comment by falkTX** [comment]
no worries.

I see the issue. you have a local custom python installation that overrides what is in the system, and carla tries to use that instead of the system python.
running this could work for you:
```
/usr/bin/python3 /usr/share/carla/carla
```

Might be best to delete your custom `/usr/local/bin/python3` so "python3" is reserved for the system python stuff, while still possible to run if specifically calling "python3.9" for you.
