### ISSUE TITLE
VST3 loads in session, but fails on reload

### ISSUE THREAD

**Issue by hijinio** [falkTX/Carla#1361]
I'm using v2.2.0-RC1 with Qtractor. I'm able to use Wine bridges to use winVSTs, including Melodyne. However, whenever I restart Qtractor, this is the only winVST plugin that fails to load (along with its presets) into Carla, even though it functions fine if I manually load it in. I've tried both 32 and 64bit versions of Melodyne as a VST3. Any ideas? Thank you.

This is the error:
[31mFailed to load a plugin 'Melodyne', error was:
VST3 support not available[0m

**Comment by falkTX** [comment]
This was reported a few days ago, fixed in https://github.com/falkTX/Carla/commit/a9350aa73b37193f8213502325b1e7796d974a43
