### ISSUE TITLE
Scan for native plugins fails in Carla 2.3.0-RC1 (with workaround)

### ISSUE THREAD

**Issue by AdrianAvenarius** [falkTX/Carla#1362]
Carla-2.3-win64 on Windows 10 Home (20H2) produces no metadata (i.e., empties the corresponding Registry path) for 64-bit VST2/3 plugins. Bridged plugins are doing fine.
Powershell logs this as "`runCarlaDiscovery() - tool '' does not exist`", most probably once per 64-bit plugin.

Copying `carla-discovery-win64.exe` (e.g., from Carla-2.2.0-win64) into the Carla directory solves the problem - possible packaging error here?

P.S. and to end on a positive note: RC1 rocks - the GUIs for some indispensable "legacy" plugins (SQ8L, Xen-Arts stuff, etc.) finally render alright!

**Comment by terranauts** [comment]
thanks, this fix worked for me.

**Comment by k4custom** [comment]
so how would one get that particular executable if they did not have 2.2.0-win64 previously?

**Comment by AdrianAvenarius** [comment]
> 
> 
> so how would one get that particular executable if they did not have 2.2.0-win64 previously?

https://github.com/falkTX/Carla/releases/download/v2.2.0/Carla_2.2.0-win64.zip

**Comment by falkTX** [comment]
Fixed in RC2, release binaries at https://github.com/falkTX/Carla-Releases/releases

**Comment by RoscoeTheDog** [comment]
I am having the same issue. I have tried both the 2.2 win64 builds linked earlier here, as well as the newest RC2 on Windows 10 pro x64.

I have even tried individually pointing to folders that I know do not require many resources (images, other extensions, etc), like fabfilter, which runs fine on other standalone hosts using just the .dll file.

Ideas?

**Comment by falkTX** [comment]
That must be a separate issue then. Mind opening a new ticket? thanks
