### ISSUE TITLE
Windows VSTs not loading on opening previous sessions

### ISSUE THREAD

**Issue by alecvn** [falkTX/Carla#1364]
When I setup and configure VST's in Carla and close the session, the Windows VST's don't load when I open that session again later.  This happens whether I open Carla as standalone and explicitly save and try to load my setup, or when I use it in a DAW (Reaper) and load a project.

I assumed it would be related to #802, but reloading the project didn't make the VST's load for me and also it seems that fix had made it's way into master a good while ago.

I'm running the latest Carla (2.2.0) and I'm on Kubuntu 18.04.

I also get the following errors (the two Ignite plugins here are DLL's):

```
Failed to load a plugin 'Ignite - Emissary', error was:
Failed to get plugin description
Failed to load a plugin 'Ignite - NadIR', error was:
Failed to get plugin description
```

**Comment by falkTX** [comment]
What distro are you using? I heavily recommend using the RC1 of v2.3 at this point, since many fixes related to this were made in 2.3, so this might be fixed already.

**Comment by alecvn** [comment]
Thanks for the quick response falkTX.

I'm on Ubuntu 18.04.  It doesn't look like there's a Linux build for 2.3 RC1 yet, would you suggest I build from source?  If so, is there a best practice way of making sure I don't have version conflicts between the two versions (2.2 and 2.3 RC1)?  Should I just delete 2.2 first?

**Comment by falkTX** [comment]
I have it in the kxstudio repositories as carla-git.
But you can just grab the precompiled debs from https://launchpad.net/~kxstudio-debian/+archive/ubuntu/apps/+sourcepub/12149346/+listing-archive-extra

**Comment by alecvn** [comment]
Excellent, I will give that a try and provide feedback tonight, thank you!

**Comment by alecvn** [comment]
So I've got a second to try to install `carla-git` and I'm afraid I'm in "dependency hell".  Do you perhaps have any tips?

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libmagic1 is already the newest version (1:5.32-2ubuntu0.4).
You might want to run 'apt --fix-broken install' to correct these.

The following packages have unmet dependencies:
 carla-git:i386 : Depends: libmagic1:i386 (>= 5.12) but it is not going to be installed
                  Depends: carla-git-data:i386 (= 5:2.3~rc1+git20210217) but it is not installable
                  Depends: python3-liblo:i386 but it is not going to be installed
                  Depends: python3-pyqt5:i386 but it is not going to be installed
                  Depends: python3-pyqt5.qtsvg:i386 but it is not going to be installed
                  Recommends: python3-rdflib:i386 but it is not installable
                  Recommends: python3-pyqt5.qtopengl:i386 but it is not going to be installed
                  Recommends: libqtcore4:i386 (>= 4:4.5.3) but it is not going to be installed
                  Recommends: libqtgui4:i386 (>= 4:4.6.1) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

I've tried `--fix-broken` but it just keeps deleting and re-installing things.

**Comment by falkTX** [comment]
Are you on a 32bit install? why is this trying to install "carla-git:i386" ?

Anyway, I think this might be due to you having carla-lv2 and others installed.
So try to specify more packages in the install command, like so:
```
sudo apt-get install carla-git carla-lv2 carla-vst
```

**Comment by alecvn** [comment]
My bad, I didn't see a 64bit carla-git version on the repositories page!  The above command installed `2.3.0 RC1` correctly (I assumed the `apt` version would still be `2.2.0`).

I can also confirm Windows VST's are now loading correctly.  Excellent stuff, thanks again falkTX!
