### ISSUE TITLE
Carla calls setParameter() immediatetly after audioMasterAutomate() when the editor is closed

### ISSUE THREAD

**Issue by robbert-vdh** [falkTX/Carla#1365]
Hi,

I noticed that Carla handles `audioMasterAutomate()` (for VST2 plugins) differently when the editor is open versus when it is closed. When the editor is open Carla just accepts this request as expected, but when the editor is closed (either because it was never opened or after closing the window) Carla will immediately call `setParameter()` on the plugin with the exact same parameter change the plugin just reported to Carla. Of course, plugins _shouldn't_ be calling be calling `audioMasterAutomate()` while the editor is closed (although Carla never actually closes the editor for VST2 plugins once it has been opened), but doing a `setParameter()` immediately after receiving that same parameter change from the plugin still sounds like a bug. I've seen some plugins calling `audioMasterAutomate()` from the DSP thread, which means that they could get stuck in a deadlock when using non-recursive mutexes. They of course probably shouldn't be automating parameters from within the audio processing call, but it does happen.

**Comment by falkTX** [comment]
I have just checked this, and it is not an issue in v2.3
There is some rules to try and check where the change comes from, to ensure it is valid.

```
            const pthread_t thisThread = pthread_self();

            if (pthread_equal(thisThread, kNullThread))
            {
                carla_stderr("audioMasterAutomate called with null thread!?");
                setParameterValue(uindex, fixedValue, false, true, true);
            }
            // Called from plugin process thread, nasty! (likely MIDI learn)
            else if (pthread_equal(thisThread, fProcThread))
            {
                CARLA_SAFE_ASSERT(fIsProcessing);
                pData->postponeParameterChangeRtEvent(true, index, fixedValue);
            }
            // Called from effSetChunk or effSetProgram
            else if (pthread_equal(thisThread, fChangingValuesThread))
            {
                carla_debug("audioMasterAutomate called while setting state");
                pData->postponeParameterChangeRtEvent(true, index, fixedValue);
            }
            // Called from effIdle
            else if (pthread_equal(thisThread, fIdleThread))
            {
                carla_debug("audioMasterAutomate called from idle thread");
                pData->postponeParameterChangeRtEvent(true, index, fixedValue);
            }
            // Called from main thread, why?
            else if (pthread_equal(thisThread, fMainThread))
            {
                if (fFirstActive) {
                    carla_stdout("audioMasterAutomate called while loading, nasty!");
                } else {
                    carla_debug("audioMasterAutomate called from main thread");
                }
                CarlaPlugin::setParameterValue(uindex, fixedValue, false, true, true);
            }
            // Called from UI?
            else if (fUI.isVisible)
            {
                carla_debug("audioMasterAutomate called while UI visible");
                CarlaPlugin::setParameterValue(uindex, fixedValue, false, true, true);
            }
            // Unknown
            else
            {
                carla_stdout("audioMasterAutomate called from unknown source");
                setParameterValue(uindex, fixedValue, false, true, true);
            }
```

Did you test this with 2.3 or an older version? Which plugin has this behaviour?

**Comment by robbert-vdh** [comment]
I tested this with Carla 2.3.0 rc2 (commit 2294a5c86). Someone reported to me that when using the VST2 version of the SWAM Trumpets plugin through yabridge in Carla, playing a note while the editor is closed will cause Carla to lock up. They reported the same thing when touching the mod wheel while the editor is closed when using the VB3-II VST2 plugin running through yabridge. During these situations, the plugin calls `audioMasterAutomate()` from the audio thread, and yabridge will relay this function call from its own thread since it's listening on a socket. [This line](https://github.com/falkTX/Carla/blob/fba2b5c4ef46d9595d3034e35cfa20fe077f96d9/source/backend/plugin/CarlaPluginVST2.cpp#L2000) from the snippet you mentioned above will then trigger an immediate `setParameter()` on the plugin with the same parameter values it just reported to the host. I don't think calling `setParameter()` in response to `audioMasterAutomate()` to set the same parameter values a plugin just reported to the host is correct, and in this particular case it can cause deadlocks since the plugin is trying to lock a mutex while handling `setParameter()` that has already been locked from the audio thread.

**Comment by falkTX** [comment]
well I can tweak this of course, but if the plugin sends the changes on the audio thread, would be best to keep that aspect while in yabridge.

**Comment by robbert-vdh** [comment]
I could do that, but that would require a lot of additional complexity. On both the plugin and the host side, you would need to delegate the actual socket operations involved in calling both `processReplacing()` and `audioMasterAutomate()` to another thread, and then you'd have to run a worker on those threads to be able to call functions directly from the audio thread while that thread is technically already blocked by something else. I'm doing something similar in two other places to handle mutually recursive function calls in VST3 plugins, but I'd really like to avoid all of that complexity if it's not strictly necessary. In this case Carla seems to be the only host that handles `audioMasterAutomate()` in this way, hence the report! There probably aren't a lot of other plugins that call `audioMasterAutomate()` from something that isn't either the audio or the UI thread, but given the sheer number of VST2 plugins out there there _must_ be at least one other plugin that does this.
