### ISSUE TITLE
Canvas meters slow when running main carla binary.

### ISSUE THREAD

**Issue by g3r** [falkTX/Carla#1370]
I'm experiencing very slow refresh rate (about 3fps) on dsp and level meters, only when running carla binary (/usr/bin/carla).
Running as plugin works fine.
Running carla-patchbay (standalone) works fine.
Running carla-rack (standalone) works fine..

OS: Manjaro.
KERNEL: Linux 5.11.2
WM: Both Fluxbox
Jack: Jack2 (1.9.17)

**Comment by falkTX** [comment]
There is a setting for this. on the 1st tab of settings actually.
Try changing that first.

**Comment by g3r** [comment]
Oops, I may have accidentally changed it from 20 to 200 ms. Thanks.
