### ISSUE TITLE
Can't load any wine plugins since wine 6.3 staging

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#1373]
Carla can't load wine plugins anymore.

Plugins are correctly loaded in a wine's host (LiveProfessor2)

I've tested with a clean wineprefix, same behavior. 

```
======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  48000
  Process mode: Multi client
wine: Unhandled page fault on read access to 0000000000000068 at address 000000007BC3851E (thread 011c), starting debugger...
CarlaRingBuffer::tryWrite(0x7fffc139c744, 4): failed, not enough space
Process of pid=0118 has terminated
No process loaded, cannot execute 'echo Modules:'
Cannot get info on module while no process is loaded
No process loaded, cannot execute 'echo Threads:'
process  tid      prio (all id:s are in hex)
00000038 services.exe
	["C:\windows\system32\services.exe"]
	0000003c    0
	00000040    0
	0000007c    0
	00000094    0
	000000a8    0
	000000c0    0
	000000f8    0
	00000148    0
0000004c explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	00000050    0
	00000068    0
	0000006c    0
00000074 mDNSResponder.exe
	["C:\Program Files (x86)\Audinate\Shared Files\mDNSResponder.exe"]
	00000078    0
	00000084    0
	00000088    0
0000008c svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	00000090    0
	00000098    0
	0000009c    0
000000a0 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	000000a4    0
	000000ac    0
	000000b0    0
	000000b4    0
000000b8 plugplay.exe
	[C:\windows\system32\plugplay.exe]
	000000bc    0
	000000c4    0
	000000c8    0
	000000cc    0
	00000108    0
000000f0 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	000000f4    0
	000000fc    0
	00000100    0
	00000104    0
	00000110    0
	00000114    0
0000012c explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	00000130    0
	00000134    0
	00000138    0
00000140 rpcss.exe
	[C:\windows\system32\rpcss.exe]
	00000144    0
	0000014c    0
	00000150    0
	00000154    0
	00000158    0
	0000015c    0
winedbg: Internal crash at 0x7fed91e22287.



```
_Using Carla version 2.3.0-RC1
  Python version: 3.6.9
  Qt version:     5.9.5
  PyQt version:   5.10.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources_

_wine-6.3 (Staging)_

_ubuntu studio 18.04_

**Comment by moonshaadow** [comment]
Sorry I hadn't seen recent commit related to wine bridge. Maybe I should wait it comes with carla-git ? 
(For now I've got _5:2.3~rc1+git20210217 amd64_ )

**Comment by falkTX** [comment]
winelib is broken in 6.3, no plugins will work in bridged mode.
Not with carla, nor yabridge, not anything.
Revert to 6.2 for now.

**Comment by JRSV** [comment]
is the only way to downgrade to uninstall the packages and reinstalling or is there a way that I can do this via terminal? I am using MXlinux (debian 10)

**Comment by falkTX** [comment]
No idea, it will depend on the distribution.
This is not something I can give support to.

**Comment by JRSV** [comment]
yeah, I imagined, this problem caught me by surprise. thanks

**Comment by moonshaadow** [comment]
@JRSV  For me (ubuntu 18.04), no need to uninstall.
use at your own risk, with replacing by your correct packages names :
`sudo apt install --install-recommends winehq-staging=6.2~bionic-1 wine-staging=6.2~bionic-1 wine-staging-amd64=6.2~bionic-1 wine-staging-i386:i386=6.2~bionic-1`
(I've used synaptic to see the correct packages names)

**Comment by JRSV** [comment]
thanks @moonshaadow, 
I will check your suggestions, I had some warnings of packages being removed that I definitely  didn't want to remove them, so I hesitate. Hope I find all the packages because as mentioned, I am AVL-MXE not an Ubuntu. But as I understand you were successful, so I will give it a go. Thanks

**Comment by moonshaadow** [comment]
@JRSV using synaptic you will know which packages are currently installed, their complete names and also which versions of these packages are available (including former packages still available). Of course you only need to replace wine staging packages, not all wine packages. In my case there are 4 packages. The command line method is recommanded. I'm not familiar with MX but it's debian-based, so the method should be so different. In any case `apt` should tell you what you're exactly going to do.

**Comment by JRSV** [comment]
@moonshaadow, as I suspected, it is much trickier for my abilities :(
first, those packages are not available for my distribution through apt-get. I did however get the files, but apt-get makes it impossible to cleanly uninstall all traces of wine, I do not know why it just keeps me in a loop of uninstalling packages and apt installing "newer versions". thanks though

**Comment by basti0001** [comment]
Hi, 
I can confirm this issue. Also I can confirm falkTX advice to roll back wine-6.3 to wine-6.2 works fine again. You even don't need to backup/restore the .wine folder. Just prevent your distro from updating wine again. That's all.

Cheers

Sebastian

**Comment by JRSV** [comment]
different when the distro brings 6.3 by default. Again in AVL-MXE it is apparently is trickier, but a solution is already described here:
[https://forum.mxlinux.org/viewtopic.php?f=127&t=63582&sid=dd62ba3d8350adbf4d60cd455843ec3b&start=10](url). Also in that thread wine 6.4 is on its way to fix this.

**Comment by moonshaadow** [comment]
6.4 is here, at least for ubuntu bionic, and fixes the bug.
If it's packaged for everyone, we could close the issue.

**Comment by falkTX** [comment]
seems like we can use wine bridges again indeed
