### ISSUE TITLE
vst2 plugins not scanned in Windows 10 with 2.3.0 RC1

### ISSUE THREAD

**Issue by keno184** [falkTX/Carla#1378]
A new plugin scan does not see any vst2 plugins in Windows 10 with 2.3.0 RC1.

**Comment by falkTX** [comment]
Yes, known issue.
Already fixed in the code, but I am yet to make a release. Will try later this week.

**Comment by AdrianAvenarius** [comment]
In the meantime, #1362 might help.

**Comment by falkTX** [comment]
Fixed in RC2, release binaries at https://github.com/falkTX/Carla-Releases/releases
