### ISSUE TITLE
Opening saved *.carxp files doesn't restore LV2 plugins

### ISSUE THREAD

**Issue by yurivict** [falkTX/Carla#1381]
Plugins I had instantiated in the saved session appear to be listed in the file, but Carla doesn't open them when this file is opened.

Version: 2.2.0
OS: FreeBSD 12.2

**Comment by falkTX** [comment]
Try with 2.3 please, I think this issue is already fixed.

**Comment by yurivict** [comment]
This is fixed in 2.3.0-RC2, thanks.
