### ISSUE TITLE
carla-single does not receive CC

### ISSUE THREAD

**Issue by jpcima** [falkTX/Carla#1394]
Using carla 6275b66a4
The program carla-single no longer transmits MIDI controllers and pitch bend to the plugin.
This is with VST3 and this invocation: `carla-single native vst3 ./build/sfizz.vst3`

This works in the ordinary `Carla`.

**Comment by falkTX** [comment]
Just noticed something suspicious.
Try with b612c7512762fb1bd0d1d285f8e10cff45c208c3 thanks

**Comment by jpcima** [comment]
The build has failed, `PLUGIN_OPTIONS_NULL` not declared in the scope.

**Comment by falkTX** [comment]
err right, it needs CarlaBackend:: namespace prefix. I should build before committing next time

**Comment by falkTX** [comment]
Done, build fixed

**Comment by jpcima** [comment]
It works again, thanks!
