### ISSUE TITLE
No "open file" dialog box in REAPER

### ISSUE THREAD

**Issue by sisyphusmc** [falkTX/Carla#1398]
I'm not sure if this a REAPER issue or a Carla issue: the new Midi File .lv2 plugin loads in REAPER, but then does not show an icon for the 'open midi file' dialogue box. In Ardour this icon shows up for me. Also when loading Carla as a .vst or an .lv2 in REAPER and then loading the "Midi File" plugin, either as a native plugin or as a .lv2 plugin, the "open file" dialog will not open.

![midi_file_reaper](https://user-images.githubusercontent.com/76957788/115424591-84b72d00-a207-11eb-9731-907d5fe5af22.png)
![midi_file_ardour](https://user-images.githubusercontent.com/76957788/115424596-854fc380-a207-11eb-8d8a-ba7055e4d015.png)

**Comment by falkTX** [comment]
when using the midi file directly in reaper, the issue will be on reaper side.
it needs to support plugin parameters of atom:Path type.
I guess it does not do that right now.

carla as plugin not being able to open file dialogs is a separate issue.
those 2 things are not related.
(worth opening a ticket for that 2nd one, if you care to see it working/fixed)

**Comment by sisyphusmc** [comment]
Awesome, I will submit a fr in the REAPER forum for the first case. I mess around with Carla the second case a little more and submit a separate ticket. Cheers!
