### ISSUE TITLE
Carla patch changes not handled properly using gig files

### ISSUE THREAD

**Issue by asbaklm** [falkTX/Carla#140]
I tried some gig files in Carla and patch changes in the editor when selecting from "Program" aren't working properly (don't seem to change, or they change somewhat but appear to keep playing the original patch + new patch overlaid?). These work ok when using Qsampler.

**Comment by falkTX** [comment]
Can you check if this issue still happens? (It should be fixed now)
Thanks.

**Comment by yubatake** [comment]
I see this is an old bug but it appears it's still present as I'm having the same problem using Carla-Rack as an LV2 plugin in Qtractor.

Upon changing "Program" for a loaded gig, the name will update correctly but the actual sound will not - it remains that of the initial patch. After re-loading the session in Qtractor, Program's name returns to the initial patch (the sound is the initial patch too). I've tried various gigs with the same result, though I have had the sound change correctly on a handful of occasions (around 5% so far) and can't ascertain why it worked correctly on these occasions.

FYI, in case it's relevant, upon changing Program the following appears in Qtractor's Messages window:

`Carla assertion failure: "sendGui || sendOsc || sendCallback" in file ../backend/plugin/CarlaPluginLinuxSampler.cpp, line 467`

And, on closing Carla's GUI, the following appears:

`Using "carla" theme`
`Carla 1.9.6 (2.0-beta4) started, status:`
 ` Python version: 3.3.5`
  `Qt version:     4.8.6`
  `PyQt version:   4.10.3`
  `Binary dir:     /usr/local/lib/carla`
  `Resources dir:  /usr/local/share/carla/resources`
`Carla assertion failure: "pData->pipeRecv != INVALID_PIPE_VALUE" in file ../../utils/CarlaPipeUtils.cpp, line 1013`
`Carla assertion failure: "pData->pipeSend != INVALID_PIPE_VALUE" in file ../../utils/CarlaPipeUtils.cpp, line 1094`
`Carla assertion failure: "pData->pipeSend != INVALID_PIPE_VALUE" in file ../../utils/CarlaPipeUtils.cpp, line 831`
[the assertion failures are variously repeated below this]

The patches do appear to change correctly when running Carla-Rack in standalone mode. Save/load state are also working.

I'm running Carla-Rack 1.9.6 (2.0-beta4) from git, a recent Qtractor git version (0.7.7.17) and LinuxSampler 2.0.0, on opensuse 13.1.

**Comment by geckolinux** [comment]
I suspect that this is happening to me with `maestro_concert_grand_v2.gig` from http://linuxsampler.org/instruments.html . The first program does not have sustain pedal release noises, but the second one does, but when switching to it there are still no sustain pedal release noises.

**Comment by geckolinux** [comment]
To follow up on my last comment, it appears that it is now working correctly with the `2.0-beta7` in my distro's repo, my previous comments were with the precompiled binary tarball supplied by falkTX/Carla.

**Comment by falkTX** [comment]
what version of libgig do you have installed from opensuse repos?

**Comment by geckolinux** [comment]
`libgig8 4.1.0`

**Comment by falkTX** [comment]
Gig file support was removed from Carla, due to many issues regarding linuxsampler (the library used for gig sampling).
I'm closing this bug, sorry for the inconvenience.

**Comment by falkTX** [comment]
Issue was mostly with SFZ files it seems, but anyway, you can just load linuxsampler within carla and control it with qsampler.
Or if you just use gig files, use the ls16 plugin.

**Comment by geckolinux** [comment]
Thanks for the reply.

I really don't like the qsampler interface, and ls16 doesn't appear to be available for my distro.

What about adding back the GIG support under Experimental Features?

**Comment by falkTX** [comment]
I really rather not do that.

For ls16, you can use my sources or even the binary.
See https://launchpad.net/~kxstudio-debian/+archive/ubuntu/plugins/+sourcepub/3810796/+listing-archive-extra
(deb extraction is need on that case)
the plugins as I build them are self-contained, so no external libs necessary.

**Comment by geckolinux** [comment]
Thanks for the link. I tried extracting the `dssi` directory to `/usr/local/lib64/dssi` and setting that path for searching DSSI plugins in Carla. But the scan for new plugins doesn't seem to find it. When running the scan I can briefly see `/usr/local/lib64/dssi/ls16.so` flash across the scan progress, but even after running Carla it says no DSSI plugins are available.
