### ISSUE TITLE
Priority of Wine bridge and VSTs

### ISSUE THREAD

**Issue by Philipp91** [falkTX/Carla#1400]
With `htop` I'm checking the priorities of Jack, Carla and Wine. With default settings (`jackd -R` and such), the main processes of Jack and Carla run with priority 20 (i.e. the standard), but their worker threads run with -6, -11 or even -81. It seems like there are some sensible defaults and it works fine.

What doesn't work are my Wine VSTs, where I get xruns when other applications (like Chrome) are doing something. That's not surprising, as `carla-bridge-wine64` and `wineserver64` only have priority 0. Is that a bug in Carla? Should it start those processes with a lower priority?

When I start Carla itself with realtime priority (e.g. `chrt -rr 10 carla`), which isn't ideal because the UI doesn't need it, then the Wine processes/threads inherit the resulting -11 priority and I get no xruns anymore, no matter what I do in Chrome or elsewhere.

**Comment by falkTX** [comment]
Carla has wine settings to set those priority through wine-staging.
See https://wiki.winehq.org/Wine-Staging_Environment_Variables for what they do.

Unless you use wine-staging, the priorities of the windows audio bridges is going to be suboptimal.

**Comment by Philipp91** [comment]
Thanks!
