### ISSUE TITLE
random crashes when dragging / refreshing patchbay with fancy eye-candy enabled

### ISSUE THREAD

**Issue by cheesehead544** [falkTX/Carla#1402]
i use carla as a patchbay for pipewire, and with the fancy eye-candy option enabled sometimes it just crashes with a segmentation fault(core dump) when i refresh the patchbay. it seems to happen more often if i also drag things around while refreshing but i might be wrong on that. i'm running arch linux, updated this morning. i'm running the carla-git AUR package, it also does it running the repo version. if i run it with carla --gdb it gives "0x00007ffff21960c0 in QGraphicsItem::parentItem() const () from /usr/lib/libQt5Widgets.so.5" when crashing. i have no idea how to narrow it down further, so any help is appreciated.

**Comment by falkTX** [comment]
I investigated this before, crash is happening deep within Qt.
Some time ago I had to just fully disable the drop shadow effect because that caused crashes too.

Sadly there doesnt seem to be much we can do.

**Comment by cheesehead544** [comment]
thanks for the quick reply, it seems i will have to live without the fancy eye-candy option for now.
