### ISSUE TITLE
Update required FFmpeg version

### ISSUE THREAD

**Issue by minijackson** [falkTX/Carla#1403]
Hello! I maintain Carla over on the NixOS Linux distribution, and we're trying to migrate away from ffmpeg <= 3.x, due to several vulnerabilities (see https://github.com/NixOS/nixpkgs/issues/94003 and https://github.com/NixOS/nixpkgs/issues/120372).

I looked at the [Makefile](https://github.com/falkTX/Carla/blob/v2.3.0/source/Makefile.mk#L311-L314) and saw that Carla requires ffmpeg v2.8.15 maximum, which felt weird to me, since currently on NixOS it is packaged with ffmpeg 3.4.8. I'm not sure how those pkg-config commands didn't fail.

Carla builds fine with ffmpeg 3.4.8 and ffmpeg 4.3.2, but I'm not sure where the ffmpeg decoder is used. I tried using the Audio file internal plugin, but couldn't hear anything, I'm not sure if this is a user error or an issue with our build, but Carla didn't crash with ffmpeg 4.3.2.

Do you think it would be possible to upgrade the required ffmpeg version? Or should we ship Carla without ffmpeg support?

Thanks for the great work!

**Comment by falkTX** [comment]
Just dont use ffmpeg. that part is legacy code.
At some point I am going to update it, but didnt bother with it yet. the main use was for mp3 support but there is a different/new library built-in carla for that now.

**Comment by minijackson** [comment]
Got it, thanks! Should I leave the issue open?

**Comment by falkTX** [comment]
depends on how much you care to see this (re)added.
it is not a priority for me at all, likely for many months

**Comment by minijackson** [comment]
I'll close this then
