### ISSUE TITLE
Inconsistent double click to open plugin settings behavior in Patchbay of Linux vs Windows

### ISSUE THREAD

**Issue by walterwatson** [falkTX/Carla#1407]
I'm experiencing inconsistent double click behavior and not sure if this is correct or not.

Using the official release Carla-2.3.0-win64.zip for Windows 10, I can successfully double click a plugin in Patchbay and a dialog box will open and I can make changes to the plugin.

However, on Ubuntu 18.04, using the official release Carla_2.2.0-linux64.tar.xz I _cannot_ open a plugin's settings by double clicking on it in Patchbay.

I've even gone so far as to compile the latest 2.3.0 on Ubuntu 18.04 and it too has the same issue for me.

Item's do open in Linux from the gear icon in the 'rack'.

Is there something that I am doing wrong?

Thank you.

**Comment by falkTX** [comment]
what is your jack2 version? Stock Ubuntu 18.04 has a version too old that doesnt work for this

**Comment by walterwatson** [comment]
Hello @falkTX !

Yes I'm using a stock Ubuntu 18.04, so the stock jack2.

Sorry I did not see this anywhere for the minimum requirements.  I suppose this also explains, why the visual displays of the equalizers of calfjackhost plugins are missing too when opening them from the rack as well. 

All is not lost, I can run carla headless and achieve my goals so thank you again for your hard work on this project.   

To answer your question, here is the dpkg listing of jack libs on my Ubuntu 18.04:
`
dpkg -l libjack-jackd2-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libjack-jackd2 1.9.12~dfsg- amd64        JACK Audio Connection Kit (librar
ii  libjack-jackd2 1.9.12~dfsg- i386         JACK Audio Connection Kit (librar
`

**Comment by falkTX** [comment]
Everytime I do a new release I add it as part of release news
https://kx.studio/News/?action=view&url=carla-22-rc1-is-here
https://kx.studio/News/?action=view&url=carla-plugin-host-v22-is-finally-here
https://kx.studio/News/?action=view&url=carla-plugin-host-v23-is-here

> This was already the case for v2.2 but it is worth reiterating:
> When using JACK2, the canvas - plugin integrations requires at least JACK2 v1.9.13.
> This is because Carla relies on JACK meta-data in order to store information about each plugin/client, and meta-data was only added to JACK2 in version 1.9.13.
> Alternatively, you can use JACK1 instead of JACK2, which has meta-data support since a long time.
