### ISSUE TITLE
Issues with JACK with ALSA-MIDI mode

### ISSUE THREAD

**Issue by lorenzosu** [falkTX/Carla#1409]
Unless I'm misunderstanding what this Audio driver mode does. I would expect that this mode allows to have directly access to ALSA MIDI from Carla, i.e. creating a writable and readable ALSA MIDI device for Carla.

When the engine is set to patchbay mode, there is a Midi Input and Midi Output in Carla visible in the patchbay display, but they are not accessible from ALSA MIDI (nor in aconnect -l, qjackctl, nor directly from clients).

When in continuous rack mode, ALSA MIDI ports (both readable and writable) are exposed in Carla, but they are not updated if they are added/removed (e.g. if an application is started/quits, or a new port is created), something changes if CTRL+R is pressed but not all ports are updated.

This mode would be very useful to support ALSA MIDI clients natively. Of course a way to do this is to use e.g. a2j.

**Comment by falkTX** [comment]
Use menu canvas -> show external.
The MIDI devices are listed in there.

**Comment by lorenzosu** [comment]
Hi @falkTX thanks for the quick response. Indeed Canvas > show external shows the connections.

I still see a maybe unexpected behavior where if an ALSA MIDI port is connected via carla then disconnected externally (say in qjackctl in the alsa midi tab), while the port seems effectively disconnected (no midi data seems to come in), then a refresh (CTRL+R) is done the two ports still seem connected and there's still an option to disconnect them in the patchbay.
Indeed unless you explicitly disconnect them in Carla there is still a port shown as writable of the. For example if I connect Qtractor's master output:
"Carla:Qtractor:Master 136:0:Qtractor:Master 136:0 136:0 129:0"

The screenshot shows this kind of situation *after* having actually disconnected the port with qjackctl and doing a CTRL+R in the patchbay.

![image](https://user-images.githubusercontent.com/463937/116825833-3a339a00-ab91-11eb-8a82-5162c9a864e4.png)

**Comment by falkTX** [comment]
well nothing to do there from carla side, that external disconnect is not something carla knows about.
carla is using rtmidi for the alsa-midi mode, and it doesnt support such notifications.
in fact, only with linux alsa midi such thing is possible, it is not the case with windows midi or coremidi on macos afaik.

so from what I can see, this external disconnect is an edge case not really worth caring about much.
