### ISSUE TITLE
Feature request: Control external (player) applications

### ISSUE THREAD

**Issue by Philipp91** [falkTX/Carla#1413]
My MIDI keyboard has play/pause/forward/rewind buttons and I'd like to control my media player (e.g. Rhythmbox) with them. This could be as simple as simulating the respective HID keyboard keys, which would ideally be picked up automatically by the active player software.

Is there already a way to achieve this? Or would perhaps a plugin be the right way, which could offer a bunch of common features/buttons to be MIDI-learned within Carla?

**Comment by falkTX** [comment]
This is out of scope for carla.
You can make a plugin that translates MIDI events into global keyboard events or even talks to MPRIS/DBus for this.
But has nothing to do with carla.

**Comment by Philipp91** [comment]
Thanks, a plugin worked just fine: https://github.com/Philipp91/lv2xdo
