### ISSUE TITLE
Problem playing gig files

### ISSUE THREAD

**Issue by varpa** [falkTX/Carla#142]
I am running kxstudio 14.04 with Carla version 1.9.5 (2.0-beta-3).   Loading any gigasampler file (any I've tried of various sizes) and playing with keyboard or by sending midi from audacious results in stuttered playing and even crash of Carla.   While playing get lots of these message in terminal:
EngineBase: ERROR, voice stealing didn't work out!
DiskThread: there was no free slot
Disk stream order failed!
... lots of these ....
Segmentation fault

Gig files play fine in QSampler.   Problem only with GIG, SFZ play fine

**Comment by falkTX** [comment]
This should be fixed now (the voice stealing).
