### ISSUE TITLE
Carla freezes with plugins or apps larger than 32 ports

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#1425]
Hi there.
Possible regression.

- Carla is freezing when I load a plugin with more than 32 ports ( in + out > 32). No matters which type of plugin.

- When Carla is open, when I try to launch a external jack application or a wineasio app with more than 32 ports, Carla is freezing and the app doesn't show its gui untill I kill Carla.

You can test it adding a carla-patchbay (32chan) .

Doing a `git bisect`, it points me to c777cd02d92ba8a61adb29d61fd39f84e3d1bc55 as first bad commit.

**Comment by falkTX** [comment]
The offending commit has been reverted on 2.3.1
I assume this behaviour to be fixed now.
Reopen if not the case.
