### ISSUE TITLE
VST Plugin State not loaded (win64)

### ISSUE THREAD

**Issue by christianbrugger** [falkTX/Carla#1430]
Thank you much for prividing such a wonderful tool. I just have a small problem.

I am using the [ReaPlug VST plugins](https://www.reaper.fm/reaplugs/) via the wine win64 bridge. For some of them the state is not loaded when loading the project file. In particular `ReaComp` and `ReaGate`. On the otherhand the state loading works for `ReaFir` and `ReaEQ`. I checked the save file and the information seems to be saved correctly, just when re-loading the project, everything is again the default.

I am using `Carla 2.3.0` from the repo at `https//kx.studio/repo/` on Ubuntu `2020.10`. I tried both the package `carla` and `carla-git`, but it seems they install the same version.

I just tested version `2.2.0` from the homepage. And there the laoding of the plugins work `ReaComp` and `ReaGate`. Although I get there an error when loading the VST `ReaEQ` from the bridge. Although I think thats because the bridge from the repo is probably not compatible with this version.

**Comment by falkTX** [comment]
Try to uncheck "use chunks" in the generic carla-provided plugin editor/settings.

**Comment by christianbrugger** [comment]
@falkTX Where do I find this setting?

**Comment by christianbrugger** [comment]
That did the trick, thank you very much.

**Comment by falkTX** [comment]
I added something extra in 2.3.1 to work better for plugins that do not use chunks even though they report that they can.
This can be considered fixed.
