### ISSUE TITLE
Pipewire MIDI often not working

### ISSUE THREAD

**Issue by kuon** [falkTX/Carla#1439]
I do not know if this is a pipewire or Carla issue, but when using Carla with pipewire jack dropin, the MIDI controls often stop working.

Pipewire issue:

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1290

**Comment by falkTX** [comment]
I have never seen this issue myself, so I can only assume it is pipewire related.

**Comment by sfjuocekr** [comment]
I noticed a similar issue when I switched to the kxstudio packages.

The first time I connect a MIDI device a note is being played, when I disconnect it and then reconnect it usually works. Sometimes it will not work, but simply reconnecting makes it work.

**Comment by dromer** [comment]
@kuon Have you tried this with recent PipeWire master branch?

I believe they recently made some fixes to MIDI that should make it more reliable. For me there where some issues with PureData and sometimes with external devices that MIDI wasn't working properly. Should be all good now.

**Comment by kuon** [comment]
I gave it a go, and it seemed stable for like an hour. I'll close it, and if it happen again, I'll reopen it.
