### ISSUE TITLE
Out of range sfz key values crashes Carla

### ISSUE THREAD

**Issue by asbaklm** [falkTX/Carla#144]
jeffg asked me to file a report on this issue where a wrong sfz sample set keyrange value crashes Carla. The idea being that something like this shouldn't cause the entire app to crash but rather that it should just refuse to load the "bad" sampleset / instrument.

In this case the hikey value was set to 888 instead of 88 resulting in Carla crashing & exiting when trying to load the instrument.

sample=4_Gb_d.wav
lokey=76 hikey=888 pitch_keycenter=78

http://www.linuxmusicians.com/viewtopic.php?f=50&t=12949&p=56522#p56522

**Comment by falkTX** [comment]
Issue now kinda irrelevant, linuxsampler was removed and replaced by sfzero.
The crash wont happen anymore :)
