### ISSUE TITLE
Allow variable audiofile playback speed

### ISSUE THREAD

**Issue by underdoeg** [falkTX/Carla#1443]
Would be a useful feature to have an additional knob to control the playback speed of an audio file. Probably in a range from 0-2

**Comment by falkTX** [comment]
Perhaps, but this is not my purpose for the plugin.
Better to find another one for such things, the carla audiofile plugin is intended to be in sync with the host, transport-wise.
Plus the whole disk streaming logic would have to be redone to consider variable speed.

**Comment by underdoeg** [comment]
I disagree about the purpose, different playback speed is still in sync. but yes, I looked into the code and the disk streaming would be tricky... Is there any lv2 plugin that is not a full blown sampler but more like an audio player?
