### ISSUE TITLE
`Qt_5_PRIVATE_API' not found 

### ISSUE THREAD

**Issue by joenoone** [falkTX/Carla#1447]
Running Fedora 34 with qt5 5.15.2. Couldn't find any library that supports Qt_5_PRIVATE_API...

$ ./Carla
Carla self-contained executable 2.2.0, based on UnZipSFX.
Launching: '/tmp/carla-2.2.0/carla'
Traceback (most recent call last):
  File "./lib/__startup__.py", line 40, in run
  File "./lib/Console.py", line 23, in run
  File "source/frontend/carla", line 22, in <module>
  File "./lib/carla_host.py", line 40, in <module>
ImportError: /lib64/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /tmp/carla-2.2.0/lib/PyQt5/QtCore.so)

**Comment by falkTX** [comment]
Fedora should have latest carla, best to use that directly instead, can you use that? does it work?

**Comment by joenoone** [comment]
Ah, missed that the package was "Carla" (didn't use upper case C). Didn't find that with dnf so downloaded from git. That works, thanks
