### ISSUE TITLE
make wine32 fails

### ISSUE THREAD

**Issue by ryanpg123** [falkTX/Carla#1449]
make wine32
make -C source/jackbridge wine32
make[1]: Entering directory '/home/ryanpg/src/Carla/source/jackbridge'
Linking jackbridge-wine32.dll.so
/usr/bin/ld: skipping incompatible /usr/lib64/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/lib64/librt.so when searching for -lrt
/usr/bin/ld: skipping incompatible /usr/lib64/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/lib64/librt.so when searching for -lrt
/usr/bin/ld: cannot find -ladvapi32
/usr/bin/ld: cannot find -luser32
/usr/bin/ld: cannot find -lwinecrt0
/usr/bin/ld: cannot find -lkernel32
/usr/bin/ld: cannot find -lntdll
/usr/bin/ld: skipping incompatible /usr/lib64/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib64/libc.so when searching for -lc
collect2: error: ld returned 1 exit status
winegcc: /usr/lib64/ccache/gcc failed
make[1]: *** [Makefile:174: ../../build/modules/Release/jackbridge-wine32.dll.so] Error 2
make[1]: Leaving directory '/home/ryanpg/src/Carla/source/jackbridge'
make: *** [Makefile:363: wine32] Error 2

**Comment by ryanpg123** [comment]
Sorry, my mistake the error above was my fault, the actual error is below:

make wine32
make -C source/jackbridge wine32
make[1]: Entering directory '/home/ryanpg/src/Carla/source/jackbridge'
Linking jackbridge-wine32.dll.so
/usr/bin/ld: skipping incompatible /usr/lib64/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/lib64/librt.so when searching for -lrt
/usr/bin/ld: skipping incompatible /usr/lib64/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/lib64/librt.so when searching for -lrt
/usr/bin/ld: cannot find -ladvapi32
/usr/bin/ld: cannot find -luser32
/usr/bin/ld: cannot find -lwinecrt0
/usr/bin/ld: cannot find -lkernel32
/usr/bin/ld: cannot find -lntdll
/usr/bin/ld: skipping incompatible /usr/lib64/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib64/libc.so when searching for -lc
collect2: error: ld returned 1 exit status
winegcc: /usr/lib64/ccache/gcc failed
make[1]: *** [Makefile:174: ../../build/modules/Release/jackbridge-wine32.dll.so] Error 2
make[1]: Leaving directory '/home/ryanpg/src/Carla/source/jackbridge'
make: *** [Makefile:363: wine32] Error 2

**Comment by falkTX** [comment]
I need to know where your wine libs are installed so I can add it to the linker path

**Comment by ryanpg123** [comment]
Sorry, though I've used Linux a long time, I'm not 100% clear where the wine libraries are installed on Fedora. I do know that if I add: /usr/lib64/wine/x86_64-unix/ to the jackbridge Makefile the build fails with a different error:

make -C source/jackbridge wine32
make[1]: Entering directory '/home/ryanpg/src/Carla/source/jackbridge'
Linking jackbridge-wine32.dll.so
/usr/bin/ld: relocatable linking with relocations from format elf64-x86-64 (/usr/lib64/wine/x86_64-unix//libwinecrt0.a(dll_main.o)) to format elf32-i386 (jackbridge-wine32.KYTcfL.o) is not supported
winebuild: /usr/bin/ld failed with status 1
winegcc: /usr/bin/winebuild failed
make[1]: *** [Makefile:178: ../../build/modules/Release/jackbridge-wine32.dll.so] Error 2
make[1]: Leaving directory '/home/ryanpg/src/Carla/source/jackbridge'
make: *** [Makefile:363: wine32] Error 2

**Comment by ryanpg123** [comment]
Got it to build by adding:

WINE_32BIT_FLAGS += -L/usr/lib/wine/i386-windows
WINE_32BIT_FLAGS += -L/opt/wine-staging/lib/wine/i386-unix
WINE_32BIT_FLAGS += -L/opt/wine-staging/lib/wine/i386-windows

Probably only one of them is the correct entry though. Sorry I'm not helping much! Thank you for all your work!

**Comment by falkTX** [comment]
Only one of them is correct. can you find out which one?
specially the last one are conflicting paths, you cant have unix and windows versions of the same wine lib.

**Comment by ryanpg123** [comment]
OK, looks like the magic is found in:

WINE_32BIT_FLAGS += -L/opt/wine-staging/lib/wine/i386-unix

**Comment by falkTX** [comment]
And `-L/opt/wine-staging/lib/wine/i386-windows` doesnt work?

**Comment by ryanpg123** [comment]
Both seem to allow the build to finish actually. I'm editing the Makefile, then doing "make clean" followed by make wine32.

**Comment by falkTX** [comment]
Right, but only one will actually work.

**Comment by ryanpg123** [comment]
The problem I'm having, is that once it builds successfully, all subsequent builds work regardless of what I comment out in the Makefile. I thought "make clean" would prevent this, but apparently not.

**Comment by falkTX** [comment]
try `make distclean` which will remove even more things

**Comment by ryanpg123** [comment]
Ok so I've confirmed my comment above:

`WINE_32BIT_FLAGS += -L/opt/wine-staging/lib/wine/i386-unix` compiles correctly.

But

`WINE_32BIT_FLAGS += -L/opt/wine-staging/lib/wine/i386-windows` fails to compile.
