### ISSUE TITLE
Cannot open Vital UI in Carla

### ISSUE THREAD

**Issue by jaddison06** [falkTX/Carla#1450]
(possible duplicate of #1445 ?)

Vital works fine as a standalone application, and I can load it into Carla just fine. I can play notes and load presets from outside the synth. However, when I click the gear icon to open the UI, Carla seems to freeze. There isn't any output printed in the terminal.

I'm on Elementary OS 5.1.7, based on Ubuntu 18.04.

Using Carla version 2.3.0
Python version: 3.6.9
Qt version:     5.15.2
PyQt version:   5.15.4
Binary dir:     /usr/lib/carla
Resources dir:  /usr/share/carla/resources

**Comment by thoth-amon** [comment]
I'm also having problems.  The VST2 works fine. The LV2 crashes carla and the VST3 shows this error message. 
![Screenshot_20210716_124241](https://user-images.githubusercontent.com/78971907/125942411-5aa4424f-e410-4596-a49b-8b3836ad180e.png)

Surge vst3 UI also doesn't work, just returns a blank white window. Odin2 vst3 also does this (the lv2 ui opens fine).  ChowKick vst3 also the same. Granulizer 2 vst3 also the same.

Kubuntu 20.04
Carla 2.3.1. installed from kxstudio repository

**Comment by jaddison06** [comment]
Just had a quick look, all of these plugins use Juce (apart from Granulizer which isn't open-source)

**Comment by ponimas** [comment]
I've built a couple of Juice vst3 plugins locally and they both don't show the UI.

**Comment by robbert-vdh** [comment]
With Carla 3.3.1 (or the latest master branch), any VST3 plugin causes `carla-single` to crash, and in regular Carla the UIs never get embedded (but there are no obvious crashes either) so you end up with windows with gray backgrounds. I feel like that has to be related to the `carla-single` issue. With `carla-single` it appears as if the parent window passed to the VST3 plugin in `IPlugView::attached()` just doesn't exist. I've tested yabridge and a bunch of native JUCE based plugins. All JUCE based plugins will result in the same Xlib error:

```
❯ carla-single vst3 ~/.vst3/CHOWTapeModel.vst3/
['/usr/lib/carla/carla-bridge-native', 'vst3', '/home/robbert/.vst3/CHOWTapeModel.vst3/', '(none)', '0']
libjack.so.0 loaded successfully!
Using RTNeural ModelT STN
Previous plugin state in '/home/robbert/Documenten/projecten/yabridge/CHOWTapeModel.carxs' is non-existent, will start from default state
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0xa200020
  Serial number of failed request:  183
  Current serial number in output stream:  183
Carla assertion failure: "engine == nullptr" in file ../backend/CarlaHostImpl.hpp, line 86
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
JUCE Assertion failure in juce_Singleton.h:50
```

With Windows VST3 plugins running through yabridge you get a different error, but note that this error was generated by Carla (yabridge doesn't use Xlib, nor does it do any X11 stuff outside of the Wine process):

```
14:17:43 [ValhallaDelay-48NQdfmw] [Wine STDERR] 011c:fixme:x11drv:X11DRV_DestroyNotify window 0x1006e/c000007 destroyed from the outside
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0xc000007
  Serial number of failed request:  221
  Current serial number in output stream:  223
Carla assertion failure: "engine == nullptr" in file ../backend/CarlaHostImpl.hpp, line 86
fish: Job 2, 'carla-single vst3 ~/.vst3/yabri…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by falkTX** [comment]
Fixed in https://github.com/falkTX/Carla/commit/b0f1b0530929cd94c9a583f6586eeef8f3d8ace4

Issues with vitalium in specific are something else.
