### ISSUE TITLE
carla --gdb not starting debugger on MinGW

### ISSUE THREAD

**Issue by lucianoiam** [falkTX/Carla#1454]
Is it supported?

1. Build latest Carla on MinGW
2. source/frontend/carla --gdb
3. Load a plugin that is known to crash
4. Host crashes as expected but returns to bash (also no GDB indication)

**Comment by falkTX** [comment]
No this is not supported.
the gdb option is only there for the installed scripts, typically used in linux systems.
see https://github.com/falkTX/Carla/blob/main/data/carla#L10

I guess I should remove that print/help if not under linux.

**Comment by lucianoiam** [comment]
Ouch, thanks for the info. Yes --help is a bit misleading.
