### ISSUE TITLE
master fails to buid on gentoo.

### ISSUE THREAD

**Issue by CaptainBloodz** [falkTX/Carla#1458]
Every master change request for a rebuild here:

     Mon May 31 07:04:16 2021 >>> media-sound/carla-9999-r1
       merge time: 6 minutes and 28 seconds.

     Sat Jun  5 01:25:21 2021 >>> media-sound/carla-9999-r1
       merge time: 5 minutes and 3 seconds.

     Thu Jun 10 09:24:04 2021 >>> media-sound/carla-9999-r1
       merge time: 6 minutes and 47 seconds.

     Sat Jun 12 02:52:50 2021 >>> media-sound/carla-9999-r1
       merge time: 8 minutes and 53 seconds.

     Tue Jun 22 10:03:20 2021 >>> media-sound/carla-9999-r1
       merge time: 9 minutes and 28 seconds.

     Tue Jun 22 14:27:28 2021 >>> media-sound/carla-9999-r1
       merge time: 5 minutes and 24 seconds.

     Sat Jun 26 20:39:14 2021 >>> media-sound/carla-9999-r1
       merge time: 5 minutes and 40 seconds.

     Mon Jun 28 15:17:43 2021 >>> media-sound/carla-9999-r1
       merge time: 12 minutes and 34 seconds.

     Wed Jun 30 01:14:21 2021 >>> media-sound/carla-9999-r1
       merge time: 5 minutes and 22 seconds.

     Fri Jul  2 10:34:51 2021 >>> media-sound/carla-9999-r1
       merge time: 4 minutes and 43 seconds.

     Tue Jul  6 07:41:02 2021 >>> media-sound/carla-9999-r1
       merge time: 5 minutes and 15 seconds.

     Sun Jul 11 07:34:50 2021 >>> media-sound/carla-9999-r1
       merge time: 5 minutes and 41 seconds.

     Sun Jul 11 19:31:12 2021 >>> media-sound/carla-9999-r1
       merge time: 5 minutes and 1 second.

     Tue Jul 13 22:09:06 2021 >>> media-sound/carla-9999-r1
       merge time: 6 minutes and 22 seconds.

     Wed Jul 14 06:59:49 2021 >>> media-sound/carla-9999-r1
       merge time: 6 minutes and 13 seconds.

     Thu Jul 15 13:54:14 2021 >>> media-sound/carla-9999-r1
       merge time: 5 minutes and 25 seconds.

     Thu Jul 22 11:08:04 2021 >>> media-sound/carla-9999-r1
       merge time: 12 minutes and 25 seconds.

     Fri Jul 23 22:32:54 2021 >>> media-sound/carla-9999-r1
       merge time: 5 minutes and 15 seconds.

Build log file:
[media-sound:carla-9999-r1:20210803-181644.log.gz](https://github.com/falkTX/Carla/files/6926337/media-sound.carla-9999-r1.20210803-181644.log.gz)

Thks

**Comment by falkTX** [comment]
Log has this error:
```
/usr/bin/pyrcc5 ../../resources/resources.qrc -o resources_rc.py
/usr/bin/python3.9: No module named PyQt5.pyrcc_main
```
nothing to fix on carla side, but on the system-side.

**Comment by CaptainBloodz** [comment]
My apologizes for not reading log properly.
Indeed, switched PyQt 5.15.4-> 5.15.5_pre2107091435, likely to cause the issue.
 
Thks
