### ISSUE TITLE
Carla assertion failure: "uuidstr != nullptr && uuidstr[0] != '\0'" in file CarlaEngineJack.cpp, line 3937

### ISSUE THREAD

**Issue by enorrmann** [falkTX/Carla#1460]
compiled tag 2.3.1 under ubuntu 21.04
loaded plugin Vital (.so version)
some presets fail with that error, for example Big Stomp

**Comment by falkTX** [comment]
that is not related to presets, but your jack version missing meta-data support.
the log maybe appeared late and it seems related, but I know for sure it is not.

**Comment by enorrmann** [comment]
I see. the strange thing is it works most of the time, and only fails consistently on the same presets
