### ISSUE TITLE
Doesn't start, missing library "libfluidsynth.so.2"

### ISSUE THREAD

**Issue by Kulasko** [falkTX/Carla#1462]
Hello there,

it came to my attention that since the lib32-fluidsynth update to 2.2.2-1 on my machine (Arch/Manjaro), that library doesn't provide "libfluidsynth.so.2" anymore. As Carla wants that library at startup, it doesn't start anymore. However, there is a "libfluidsynth.so.3" and when renaming it to the former, Carla starts as normal. It might crash when using that library, but I don't know that since I basically don't use it.

**Comment by falkTX** [comment]
this just needs a rebuild then.
everytime a build dependency is updated and their soname changed, all applications that use this library need to be rebuilt to match.
nothing on my side to do.
