### ISSUE TITLE
state is not restored correctly when using `ENGINE_OPTION_PREFER_PLUGIN_BRIDGES`

### ISSUE THREAD

**Issue by alex-tee** [falkTX/Carla#1465]
State saving/loading with `carla_save_plugin_state()`/`carla_load_plugin_state()` is broken when the plugin is bridged fully (using `carla_set_engine_option()` with `ENGINE_OPTION_PREFER_PLUGIN_BRIDGES`)

Here are a few before/after pics from zrythm before saving the project and after loading it. the window title says "bridged: full" if the plugin is fully bridged

# Vitalium VST3

before save

![Screenshot from 2021-08-25 10-55-25](https://user-images.githubusercontent.com/3407655/130773273-d0cd1477-439e-4753-af26-5baf2534112d.png)

after load

![Screenshot from 2021-08-25 10-56-09](https://user-images.githubusercontent.com/3407655/130773223-a917f000-4529-40f4-b935-b41a91829722.png)

# Surge VST3

after load (made similar changes in both plugins but only some parameters seem to be restored properly)

![Screenshot from 2021-08-25 11-06-09](https://user-images.githubusercontent.com/3407655/130773351-e3e309d6-c438-4264-b919-1acbf8c973b5.png)

# Vitalium LV2

before save

![Screenshot from 2021-08-25 11-08-27](https://user-images.githubusercontent.com/3407655/130773451-a8161d60-98d2-4b82-832c-18ab0cbcf4b7.png)

after load

![Screenshot from 2021-08-25 11-09-04](https://user-images.githubusercontent.com/3407655/130773480-db8b7377-c02c-4905-81ab-2649b241557e.png)

----

I also tried with only bridging UIs (by passing `ENGINE_OPTION_PREFER_UI_BRIDGES` instead of `ENGINE_OPTION_PREFER_PLUGIN_BRIDGES`). that seems to be working properly

after load (window title says "bridged UI" for plugins with bridged UIs)

![Screenshot from 2021-08-25 11-13-47](https://user-images.githubusercontent.com/3407655/130773742-3d7be5c2-1c71-479d-b9d8-432c79c7b796.png)

----

# Steps to reproduce in Zrythm

1. create a new project
2. right click on a plugin in plugin browser and select "open with carla"
3. change a few parameters
4. right click on the same plugin in plugin browser and select "open with carla (bridged full)"
5. change a few parameters
6. save the project and close
7. load the project

observe the fully bridged plugin is not loaded correctly

*note: zrythm needs to be compiled with meson option `-Dcarla=enabled` to enable carla support*

**Comment by falkTX** [comment]
can you show me the relevant code you use for saving the carla state?

**Comment by alex-tee** [comment]
this saves the state: https://github.com/zrythm/zrythm/blob/master/src/plugins/carla_native_plugin.c#L2364

and this loads it: https://github.com/zrythm/zrythm/blob/master/src/plugins/carla_native_plugin.c#L2432

**Comment by alex-tee** [comment]
can confirm the issue is fixed for LV2/VST3 (I tried with Surge and Vitalium as above and their states seem to be restored properly for both UI-only and full bridges)
thanks!
