### ISSUE TITLE
QColor Error 

### ISSUE THREAD

**Issue by mkohlhaas** [falkTX/Carla#1489]
Trying to compile with the latest version and the current git master but get the same error message after compiling:

./source/frontend/carla
Carla 2.4.0 started, status:
  **Python version: 3.10.0
  Qt version:     5.15.2
  PyQt version:   5.15.4**
  Binary dir:     /home/schmidh/Gitrepos/Carla/bin
  Resources dir:  /home/schmidh/Gitrepos/Carla/bin/resources
Traceback (most recent call last):
  File "/home/schmidh/Gitrepos/Carla/./source/frontend/carla", line 52, in <module>
    gui = HostWindow(host, True)
  File "/home/schmidh/Gitrepos/Carla/source/frontend/carla_host.py", line 137, in __init__
    self.ui.setupUi(self)
  File "/home/schmidh/Gitrepos/Carla/source/frontend/ui_carla_host.py", line 46, in setupUi
    self.listWidget = RackListWidget(self.frame)
  File "/home/schmidh/Gitrepos/Carla/source/frontend/widgets/racklistwidget.py", line 236, in __init__
    self._updateStyle()
  File "/home/schmidh/Gitrepos/Carla/source/frontend/widgets/racklistwidget.py", line 428, in _updateStyle
    self.rail_col = QColor((r0*3+r1)/4, (g0*3+g1)/4, (b0*3+b1)/4)
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'float'
  QColor(int): argument 1 has unexpected type 'float'
  QColor(QRgba64): argument 1 has unexpected type 'float'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'float'
  QColor(str): argument 1 has unexpected type 'float'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'

Compilation itself runs smoothly and prerequisites are also fulfilled:

---> Main features 
Front-End:     YES
LV2 plugin:    YES
VST2 plugin:   YES
Link support:  YES
OSC support:   YES
Binary detect: NO  [Missing libmagic/file]

---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  YES
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]
WASAPI:      NO  [Windows only]

---> Plugin formats: 
Internal: YES
LADSPA:   YES
DSSI:     YES
LV2:      YES
VST2:     YES (with UI)
VST3:     YES (with UI, using JUCE)
AU:       NO  [MacOS only]

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     YES (bridge)
Gtk3:     YES (bridge)
Qt4:      NO  [Qt4 missing]
Qt5:      YES (bridge)
X11:      YES (direct+bridge)
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
Basic: YES
MP3:   YES
Extra: NO [FFmpeg missing or too new]
SF2/3: YES
SFZ:   YES

---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: NO

Kind regards!

**Comment by falkTX** [comment]
We can close this one now, right?
