### ISSUE TITLE
[abrt] Carla: free_iirf_t(): carla-discovery-native killed by SIGSEGV

### ISSUE THREAD

**Issue by martinkg** [falkTX/Carla#1496]
Hi,

A user reported this error to me. 

           Bug ID: 2014099
           Summary: [abrt] Carla: free_iirf_t(): carla-discovery-native
                    killed by SIGSEGV
           Product: Fedora
           Version: 34
          Hardware: x86_64
            Status: NEW
        Whiteboard: abrt_hash:1cd8772ce46882dbb8c3469b5ce15f2126090957;VAR
                    IANT_ID=workstation;
         Component: Carla
          Assignee: mgansser@netcom-mail.de
          Reporter: gstephan@redhat.com
        QA Contact: extras-qa@fedoraproject.org
                CC: erich@ericheickmeyer.com, mgansser@netcom-mail.de
  Target Milestone: ---
             Group: fedora_contrib_private
    Classification: Fedora

Version-Release number of selected component:
Carla-1:2.4.0-1.fc34

Additional info:
reporter:       libreport-2.15.2
backtrace_rating: 4
cmdline:        /usr/lib64/carla/carla-discovery-native LADSPA
/usr/lib64/ladspa/notch_iir_1894.so
crash_function: free_iirf_t
executable:     /usr/lib64/carla/carla-discovery-native
journald_cursor:
s=20d35d8582fe4a4d891ca02453477d6c;i=d8e;b=091f29a527a84634921c7ac3514d2405;m=19b91bd92;t=5ce4ff1c97a45;x=b200aa6fcef50cf
kernel:         5.14.11-200.fc34.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000

Truncated backtrace:
Thread no. 1 (3 frames)
 #0 free_iirf_t at util/iir.h:66
 #1 cleanupNotch_iir at
/usr/src/debug/ladspa-swh-plugins-0.4.17-8.fc34.x86_64/notch_iir_1894.xml:51
 #2 do_ladspa_check at
/usr/src/debug/Carla-2.4.0-1.fc34.x86_64/source/discovery/carla-discovery.cpp:224

fedora bugzilla
[https://bugzilla.redhat.com/show_bug.cgi?id=2014099](url)

**Comment by falkTX** [comment]
That bugzilla is private, I cannot see details.

In any case this will be the fault of the plugin, not carla.
Carla even runs the discovery in a separate process so it does not crash in these situations.

Something to fix in the plugin, not in Carla.
