### ISSUE TITLE
[Feature Request] changeable stacking order of plugins in the rack.

### ISSUE THREAD

**Issue by mikobuntu** [falkTX/Carla#152]
It would be great if Carla had an easy method to move plugins up/down in the rack. I think there could be a few different approaches to how this would be implemented within the gui...
(1) A dedicated up and down arrow on each plugin.
(2) context menu option.
(3) hotkeys like CTRL and drag will relocate the plugins above/below when dragged. @falkTX

**Comment by wvengen** [comment]
(4) drag handle (like Audacity or Musescore)
(5) dragging the plugin name
(6) Ctrl-up / Ctrl-down (same as Ardour) (:+1:)

**Comment by trebmuh** [comment]
Adding my voice here. It'd be really handy.
