### ISSUE TITLE
Feature: add a way to check if an audio/MIDI input port is a sidechain port

### ISSUE THREAD

**Issue by alex-tee** [falkTX/Carla#1543]
In Zrythm, you can connect sends to plugin sidechain input ports. Carla doesn't have a way to let me know if an audio/MIDI input is a sidechain port so this functionality doesn't work when using Carla.

I tried to write a patch to set a hint but I realized that hints only work with parameters and not audio/MIDI inputs. In fact, Carla doesn't have any port info about MIDI/audio ports - it just gives you the number of audio/MIDI inputs.

LV2 property: https://lv2plug.in/ns/lv2core#isSideChain

**Comment by falkTX** [comment]
Handled in 1cc16af5c2ed853ed7d9a3bb8add0e89045c3cdc
Have no use for it myself, so didnt test it, please do so and report back.

**Comment by alex-tee** [comment]
thanks. sorry apparently isSideChain is not enough, some plugins use sidechain groups and don't mark the ports as `isSideChain`. I'm not exactly sure why the spec is like this but this is how ardour and zrythm detect sidechain ports

I made a pull request with this change here: https://github.com/falkTX/Carla/pull/1575
