### ISSUE TITLE
Add LICENSE file to repo

### ISSUE THREAD

**Issue by kmturley** [falkTX/Carla#1592]
Thanks for your great work.

In the README it says:
_"open source and licensed under the GNU General Public License, version 2 or later."_

Could you add a corresponding LICENSE file to the root of the repo?
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

This allows GitHub to parse the LICENSE and display it via the API and search/filters. Should take 5 mins to do!

Thanks!

**Comment by falkTX** [comment]
its already inside doc/ folder

**Comment by kmturley** [comment]
GitHub requires it at the root of the repo.

Could you move it to meet the standard?

**Comment by falkTX** [comment]
no, github does not dictate such standard.
I host carla on other git instances too, makes no sense to change things just because of github.

**Comment by kmturley** [comment]
_"Most people place their license text in a file named LICENSE.txt (or LICENSE.md or LICENSE.rst) in the root of the repository"_
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Consider the difference in the GitHub experience of a repo which follows their guidlines:

https://github.com/DISTRHO/Kars/blob/master/LICENSE
https://api.github.com/repos/DISTRHO/Kars/license

vs this repo which does not:

https://github.com/falkTX/Carla/blob/main/doc/GPL.txt
https://api.github.com/repos/falkTX/Carla/license

**Comment by kmturley** [comment]
Sure it's not a standard, but it is a convention.

LICENCE files existed before GitHub. Regardless of where you store your code, the convention will exist.
