### ISSUE TITLE
2.4.2 Can't Refresh Plugins (Windows)

### ISSUE THREAD

**Issue by verydanny** [falkTX/Carla#1598]
**Version:** 2.4.2
**OS:** Windows 11 21H2 (OS Build 22000.527)

**Issue:**
Can't refresh plugins. Version 2.4.1 doesn't have this issue.

**Reproduce:**
Add VST3 plugin into `C:\Program Files\Common Files\VST3`, hit "Refresh" in Carla -> Add Plugin. Nothing.

In Carla 2.4.1 refresh presents a dialog on which plugin type to refresh (LV2, VST3, etc).

**Comment by Panagiotis-Kouvelis** [comment]
Same thing here. Hitting refresh on the Add Plugin window does nothing. Looking to add VST3 64-bit plugins to Carla on Windows 10 64-bit latest.

I also cannot load 64-bit VST2 plugins too.

Is that an issue with 64-bit plugins in general?

**Comment by falkTX** [comment]
Might be an issue that was fixed post-release.

Please try the builds from https://github.com/falkTX/Carla-Releases/actions/runs/1963085981
Let me know if those work.
Thanks

**Comment by falkTX** [comment]
Does it work?

**Comment by Panagiotis-Kouvelis** [comment]
> Does it work?

Sorry, I had a buzzy day. Thanks for the fast response.

Yes, it works!

The zipped download (Win x64 build) from the link above has some kind of corruption, but it got uncompressed and the content copied properly.

Also, I don't know if this is good, the available tools list on the plugin refresh wizard shows only native.

Here's a screenshot:

![Carla_2022-03-11_18-06-14](https://user-images.githubusercontent.com/37593694/157904305-3a99d516-772d-4f57-83c2-23910b905abc.png)

The refresh works anyway and Carla found all my plugins.

:-)

**Comment by falkTX** [comment]
Alright, I guess another 2.4.x is warranted at this point

**Comment by Panagiotis-Kouvelis** [comment]
> Alright, I guess another 2.4.x is warranted at this point

Sounds great. I added the repo to my watch list to get updates. Cheers!

**Comment by falkTX** [comment]
this was fixed in 2.4.3, forgot to close before so will do it now
