### ISSUE TITLE
carla patchbay vst doesn't start with patchbay tab

### ISSUE THREAD

**Issue by cocreature** [falkTX/Carla#162]
Currently the rack tab is opened by default which doesn't make a lot of sense if you open the patchbay.

**Comment by ViktorNova** [comment]
This confused me too, I would assume the rack is not actually supposed to be there at all?

**Comment by falkTX** [comment]
I though about not showing the rack/plugins tab, but some actions are faster in the rack mode vs patchbay (like finding a specific plugin).

I'll make carla-patchbay open the patchbay by default soon.
