### ISSUE TITLE
Is this normal resp how do I avoid this?

### ISSUE THREAD

**Issue by christian179717** [falkTX/Carla#1623]
OS: Mint
```
user@user-Latitude-E5550:~$ carla
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 27, in <module>
    from ctypes import (
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```
Many thanks in advance!

**Comment by falkTX** [comment]
your custom python install has a broken ctypes, likely other things broken too.
something for you to fix, likely you installed some other python thing without fully grasping what was going on.

this has nothing to do with carla, but something for you to fix on your system yourself
