### ISSUE TITLE
config.h?

### ISSUE THREAD

**Issue by TomCoalfish** [falkTX/Carla#1639]
In CarlaDefines it include config.h. But, it did not generate a config.h. There is no config.h anywhere in my carla build directory. What is it?

**Comment by falkTX** [comment]
local usage file for IDEs.
carla defines `REAL_BUILD` during build, which bypasses that include

**Comment by TomCoalfish** [comment]
Hmmm, can you use CarlaHost to use the backend?

**Comment by TomCoalfish** [comment]
I just commented it out and it compiles so I will continue with the experiment

**Comment by falkTX** [comment]
Either define `REAL_BUILD` yourself, or use the pkg-config files that set that for you

**Comment by TomCoalfish** [comment]
Well I figured out how to get mod-host and jalv to work which is what I needed. I thought that the Backend did that too I don't know what carla backend is at all but thanks.
