### ISSUE TITLE
Virus detected for Win 64 binaries

### ISSUE THREAD

**Issue by aprasadh** [falkTX/Carla#1648]
I have Bitdefender Total Defender for Windows 11 Pro. Whenever I download any carla windows x64 binaries above version 2.4.1, my anti-virus alerts me with a virus warning. I am now settled with using v2.4.1. The alert screenshot is attached.

![image](https://user-images.githubusercontent.com/98056/180091260-afe57ee4-5b6f-422f-bc77-5d43693208bd.png)

**Comment by falkTX** [comment]
The build is automated and comes from https://github.com/falkTX/Carla-Releases
We can see the entire build logs, latest one is https://github.com/falkTX/Carla-Releases/runs/7366372113?check_suite_focus=true
Comparing 2.4.1 against 2.4.2 can be done with https://github.com/falkTX/Carla-Releases/compare/3cb7186854ebef57938c42848c0f675adf89b99c...e3b7931b206751c45f8034d51fc6eba5402f7e1e

I dont see how this could possibly get there.
And there is no way for me to check this properly anyhow, so it wont ever get fixed.

**Comment by aprasadh** [comment]
@falkTX What I am saying even the latest binary v2.5.0 for Windows x64 have this issue. That means it is not usable.

**Comment by mxmilkiib** [comment]
The binary or the compressed archive of the binary? Is there a specific file noted?

**Comment by aprasadh** [comment]
I think it is the zip file, because as soon as I download the zip my AV flags it and shows an alert.

**Comment by aprasadh** [comment]
Can you try the zip file in any of the online AV scanners?
