### ISSUE TITLE
Carla 2.5.0 on Linux does not display Wine Windows VST plugins in Add New menu.

### ISSUE THREAD

**Issue by wujekbrezniew** [falkTX/Carla#1650]
I'm running Carla 2.5.0 on Ubuntu 22 and i cannot see any detected WinVST plugins from Wine. Plugins are detected in Refresh menu but not visible in Add New menu despite that i have installed all bridges and i have ticked all architectures. Screenshot of what i see below.
![image](https://user-images.githubusercontent.com/11708702/180294993-a6b90b37-5820-4629-8e6e-4848f2f7d7d7.png)

**Comment by wujekbrezniew** [comment]
With Carla 2.2.0 (from latest avaiable binary releease on KXStudio site)  everything works fine 
![image](https://user-images.githubusercontent.com/11708702/180648936-a9ea1c41-f42c-4c01-924d-db57f1df8dc9.png)

**Comment by wujekbrezniew** [comment]
Another interesting hint. As (propably) configs are shared between versions in user directory in 2.5.0 plugins are visible but not loadable with error: 
![image](https://user-images.githubusercontent.com/11708702/180651330-dea2332a-6d59-4893-9956-15bc6f582aee.png)
Nothing interesting in logs though...

**Comment by cadrian** [comment]
I have the same problem. VSTs are loaded during refresh (at least it takes the expected lots of time doing processing checks) — but nothing appears in the Add New window. Worked well with 2.4.
I removed the ~/.config/falkTX directory and did the config from scratch to be sure, adding the paths and all… To no avail.
The Logs tab shows nothing relevant.

**Comment by cadrian** [comment]
Seems fixed with 2.5.0+git20220726
My plugins are visible and do work (#1642)
Thank you!

**Comment by wujekbrezniew** [comment]
Can confirm that is fixed. As fix went to ppa i'm closing this issue. Thx @falkTX <3
