### ISSUE TITLE
Plugins can't be safely removed when using Carla Patchbay as plugin

### ISSUE THREAD

**Issue by Penguinum** [falkTX/Carla#166]
There are several problems with Carla Patchbay. How to reproduce them (for example, in LMMS): add Carla Patchbay, open it, add a plugin, connect plugin output to "Audio output", then remove this plugin. "Wires" from "Audio output" now aren't disappeared, but "connected" with left top corner of a patchbay. But after reopening of Carla's GUI everything looks OK. You can add another plugin, connect it and use it.
Another problem: In Carla Patchbay add 2 plugins (for example, synth and effect). Connect one plugin to output and another plugin to this plugin. When I remove one of plugins from "rack" tab, LMMS segfaults, but Carla doesn't fall. First problem also appears. Also, both plugins are still shown in the "rack" tab (but doesn't shown in the "patchbay" tab). If I remove an effect from "patchbay" tab, LMMS doesn't fall, but the first problem also appears.
The same when using Carla Patchbay in Qtractor, but it just freezes without error messages.
I'm using Carla 1.9.5 from KXStudio.
Output of LMMS when if falls:
```
VST sync support disabled in your configuration
Trying to start carla-plugin using "/usr/share/carla/resources//carla-plugin-patchbay"
LRDF Support not available (LADSPA-RDF will be disabled)
Using "carla" theme
Carla 1.9.5 (2.0-beta3) started, status:
  Python version: 3.4.0
  Qt version:     4.8.6
  PyQt version:   4.10.4
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
ScopedPluginAction(0) - blocking START
ScopedPluginAction(0) - blocking DONE
Carla assertion failure: "oscData.path != nullptr && oscData.path[0] != '\0'" in file ../../utils/CarlaOscUtils.hpp, line 230
[1]    28185 segmentation fault (core dumped)  lmms
```
Screenshot of a patchbay after removing a plugin:
![Screenshot](http://storage6.static.itmages.com/i/14/1128/h_1417208146_2147591_56aeb8174d.png)

**Comment by ViktorNova** [comment]
I know you're working on it - just wanted to confirm this bug as well, in combination with:  https://github.com/falkTX/Carla/issues/185#issuecomment-68974214
