### ISSUE TITLE
How does Carla detect midi port changes on windows?

### ISSUE THREAD

**Issue by dunkfordyce** [falkTX/Carla#1665]
Hi, this is not a bug report but a general code help request.

I'm trying to see how Carla detects midi port changes on windows with the aim to implement something similar for Jack. RTMidi does not support this so I'm curious how you do it. Please could you point me at the relevant code?

Thanks

**Comment by falkTX** [comment]
you sure that carla does?

typically carla official builds use juce for the native support on windows and macOS.

**Comment by dunkfordyce** [comment]
You're probably right. I think I got confused but have now achieved what I wanted. I needed the multi-client jack mode.
