### ISSUE TITLE
CLAP plugins support

### ISSUE THREAD

**Issue by suhr** [falkTX/Carla#1669]
There is a *yet another* audio plugin standard: https://u-he.com/community/clap/

**Comment by djtuBIG-MaliceX** [comment]
This one's got commercial support too and isn't prohibitively licensed like VST.

**Comment by just-Nob** [comment]
Hi @falkTX ,

I'm just slowly getting into audio recording on Linux, but Carla really seems to be a great tool, thx!

Anyway, I saw that CLAP support is built into [https://github.com/DISTRHO/Ildaeil](Ildaeil). Do you plan to directly support CLAP in Carla as well, or is Ildaeil the workaround to be used?

Greetings to my original home town Berlin! ;)

**Comment by dacresni** [comment]
is clap support only available in the alpha?

**Comment by alex-tee** [comment]
@dacresni currently yes

**Comment by SolitudeSF** [comment]
looks like its supported in latest release, should this be closed?

**Comment by ColinKinloch** [comment]
Clap support isn't in the current release (2.5.10) https://github.com/falkTX/Carla/discussions/1951#discussioncomment-15664871
