### ISSUE TITLE
Carla crashes that are seemingly random

### ISSUE THREAD

**Issue by SnipeXandrej** [falkTX/Carla#1738]
This has been an issue of mine for a **long** time, so nothing new...
I am using PipeWire's JACK with Carla for a long time, and it works perfectly fine, except when it decides to just crash at random. 

I am not entirely sure if this is a PipeWire thing, or a Carla thing because I have already reported this issue on [PipeWire's gitlab](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2863) because I thought it was a problem on their end. They did seem to fix at least one bug that was causing these crashes, but there seems to be another bug that's also causing these crashes, but it has been a silence since I reported that these crashes still happen...

So as a last resort I am trying to report it here and hope for the best.

Here are some backtraces and logs:
[carla_journal.log](https://github.com/falkTX/Carla/files/10539287/carla_journal.log)
[carla_gdb.log](https://github.com/falkTX/Carla/files/10539303/carla_gdb.log)

PS: I have setup Carla as a systemd service that restarts automatically when Carla crashes/exits as a workaround.
Also, from the journal log there are (I believe) always these same reccuring lines in each crash: 
```
'c != NULL' failed at ../pipewire/pipewire-jack/src/pipewire-jack.c:5985 jack_transport_query()
[carla] Carla assertion failure: "fBuffer != nullptr" in file CarlaEnginePorts.cpp, line 159
```
```
'c != NULL' failed at ../pipewire/pipewire-jack/src/pipewire-jack.c:5702 jack_port_by_id()
[carla] Carla assertion failure: "port != nullptr" in file CarlaEngineJack.cpp, line 4392
'c != NULL' failed at ../pipewire/pipewire-jack/src/pipewire-jack.c:5702 jack_port_by_id()
[carla] Carla assertion failure: "portA != nullptr" in file CarlaEngineJack.cpp, line 4424
```

Some system info:
Distro: Arch
DE: KDE Plasma 5.26.90
Carla: 2.5.3
Pipewire: 0.3.64

**Comment by falkTX** [comment]
unless the issue happens with jack2 or jack1, we blame pipewire.

best approach here would be to build carla in debug mode (using "make debug") and try to get a gdb backtrace when the crash happens.
or try to reduce variables surrounding the crashes, so it becomes a bit more reproducible.

**Comment by SnipeXandrej** [comment]
Here is the same setup but with Carla compiled with debug mode.

[carla_journal2.log](https://github.com/falkTX/Carla/files/10543596/carla_journal2.log)
[carla_gdb2.log](https://github.com/falkTX/Carla/files/10543597/carla_gdb2.log)

**Comment by SnipeXandrej** [comment]
I also noticed that these crashes can be quite oddly caused by just moving my mouse over opened apps in my taskbar :/

**Comment by SnipeXandrej** [comment]
I can confirm that Carla works fine with PulseAudio + JACK2 without a single crash from the past 3 days, with PipeWire + PipeWire's JACK implementation Carla would have crashed several times already.

**Comment by SnipeXandrej** [comment]
I will close this issue as this is not directly related to Carla, but PipeWire JACK and KDE Plasma.
