### ISSUE TITLE
add jack applications in macOS M1/M2 ?

### ISSUE THREAD

**Issue by langrenne** [falkTX/Carla#1768]
Hello,

Under linux ubuntu studio, no problem: I have the experimental features with add jack applications.

I want use it on macOS M2 (Ventura 13). Carla works great (through rosetta), but in experimental features, no "add jack applications" check button. Must Carla be re-compilated with an option ?

Thank for your help.
Best

**Comment by falkTX** [comment]
we can recompile it, but it will not work.
the dynamic lib tricks we have on Linux are much harder or near impossible to setup properly on macOS, also it is considered a security breach of sorts so whatever method we find that works could stop working on new macOS releases.

as much as I would like to see this working too myself, dont think it is feasible and worthwhile to pursue.
