### ISSUE TITLE
Carla uses "Carla" as it's jack client name when running under Non Session Manager

### ISSUE THREAD

**Issue by ViktorNova** [falkTX/Carla#179]
As first mentioned here: https://github.com/falkTX/Carla/issues/176, 

Carla uses "Carla" as it's jack client name when running under Non Session Manager, rather than the session name. I'm looking at this right now

**Comment by falkTX** [comment]
This is now fixed with the NSM code rework.

**Comment by ViktorNova** [comment]
Excellent!
