### ISSUE TITLE
Suggestion for your Git repo.

### ISSUE THREAD

**Issue by mikobuntu** [falkTX/Carla#180]
Hi @falkTX  As I am a constant daily builder of your Carla project, and obviously builds will fail sometimes as the code is being updated so regularly, I suggest that you use Travis ( which i believe is part of Git ? ) , which will automatically build and show whether or not your code passes ( on your project page )  the make process . Perhaps talk to some of the devs on LMMS if you are unsure of how this all works and I'm sure they will be more than happy to help ;)    thanks ;)

**Comment by falkTX** [comment]
Travis is now used in this repo :)

**Comment by mikobuntu** [comment]
Great job @falkTX 

![screenshot from 2015-01-23 11 54 49](https://cloud.githubusercontent.com/assets/335217/5874362/7e374d9e-a2f8-11e4-83aa-918df20dd726.png)
