### ISSUE TITLE
VST3 plugins don't receive MIDI input in latest main

### ISSUE THREAD

**Issue by alex-tee** [falkTX/Carla#1801]
Has been happening since at least since aug 19 but likely earlier than that. I reproduced with Carla standalone from latest main:

![Screenshot from 2023-08-29 08-06-14](https://github.com/falkTX/Carla/assets/3407655/d85d55db-5624-4f65-a0bc-1d80e6c2286f)

I connected B.SEQuencer MIDI output to 2 instances of Surge XT: one VST3 and one LV2.
Surge XT in the top left is a VST3 and you can see that it's output meter is not moving. The LV2 version shows output. This can be reproduced with any VST3 instrument.

**Comment by falkTX** [comment]
Fixed in 15d7e42cfca143c99aa4bfb6313ee589947edc19
