### ISSUE TITLE
Carla 2.5.6 on Mac M1 keeps asking access to microphone and filesystem

### ISSUE THREAD

**Issue by lcupial** [falkTX/Carla#1810]
I try to use Carla 2.5.6 on a Mac Mini M1.
The macOS version is Monterey 12.6.6.
Each time i start Carla it asks permission to access the microphone.
Each time i load a project it asks access to the file system.
I have already granted these accesses and i can see that the application has the requested permissions in the macOS security settings.
Does anyone have the same issue ?

**Comment by lcupial** [comment]
Just in case it happens to somebody else, running this command in a terminal fixed the issue for me :
`sudo codesign --force --deep --sign - /Applications/Carla.app`

The idea came from a similar issue from another software : https://github.com/openscad/openscad/issues/4059

**Comment by egroys** [comment]
This has been DRIVING ME NUTS! Thank you!!!
