### ISSUE TITLE
Surge and other VST3 instruments have no audio output in latest main

### ISSUE THREAD

**Issue by alex-tee** [falkTX/Carla#1845]
Surge and Vaporizer2 VST3 plugins have no audio output. LV2 versions work. Other tested VST3 instruments work as expected (Odin2, Vital).

(See https://gitlab.zrythm.org/zrythm/zrythm/-/issues/4970 and https://gitlab.zrythm.org/zrythm/zrythm/-/issues/4971)

![surge_error](https://github.com/falkTX/Carla/assets/3407655/b3d5cd26-e17e-4dfd-a0df-16fefd5d46ab)

**Comment by falkTX** [comment]
to give extra info here:

issue is present on the native/custom vst3 hosting implementation of carla, but not on the juce hosting side (which I am deprecating and moving away from slowly)

almost sure this is something to do with default buses reported by the plugin, and my misunderstanding of the vst3 spec.
likely the plugin is expecting the host to do something with "bus active by default", and carla does nothing as it assumes "if they are active by default, doing nothing means they start in active state".

relevant code is in https://github.com/falkTX/Carla/blob/main/source/backend/plugin/CarlaPluginVST3.cpp#L1973 if someone wants to give it a try.

**Comment by alex-tee** [comment]
I commented out that part and the corresponding part in outputs and ran `carla-single native vst3 '/usr/lib/vst3/Surge XT.vst3'` but it still shows the same error in surge.

https://github.com/alex-tee/Carla/commit/61076bd615cf811cea17c79448eb34307c0f7b47

**Comment by alex-tee** [comment]
Commenting out the if statements for inputs and outputs fixed the issue
