### ISSUE TITLE
Precompiled binaries on website are obsolete versions

### ISSUE THREAD

**Issue by luzpaz** [falkTX/Carla#1850]
As of this writing, https://kx.studio/Applications:Carla#Download shows

> Linux 32bit (requires Qt 5.9 or higher) 
Linux 64bit (requires Qt 5.9 or higher)  
MacOS universal build (requires macOS 10.12 or higher) 
Windows 32bit
Windows 64bit

These are their links respectively:

https://github.com/falkTX/Carla/releases/download/v2.2.0/Carla_2.2.0-linux32.tar.xz  
https://github.com/falkTX/Carla/releases/download/v2.2.0/Carla_2.2.0-linux64.tar.xz  
https://github.com/falkTX/Carla/releases/download/v2.5.6/Carla-2.5.6-macos-universal.dmg  
https://github.com/falkTX/Carla/releases/download/v2.5.6/Carla-2.5.6-win32.zip  
https://github.com/falkTX/Carla/releases/download/v2.5.6/Carla-2.5.6-win64.zip

Note the version numbers are dated.

**Comment by falkTX** [comment]
Fixed in [9028d3c278a584e6e1e875d997267da883287dd2](https://github.com/KXStudio/Website/commit/9028d3c278a584e6e1e875d997267da883287dd2)

Carla linux downloads are old because I dont do those anymore, likely I should just remove them, but not today
