### ISSUE TITLE
No mic capture when using JACK+ALSA/MIDI (because of wrong Jack connections?)

### ISSUE THREAD

**Issue by Euximion** [falkTX/Carla#186]
*working*:
When only using JACK driver (no +ALSA/MIDI), in the QjackCtl Connections window, in the Writable Cients / Input Ports column, under 'Carla' it shows **audio-in1** and **audio-in2** as expected. I connect both of these with the **capture_1** input entry of my mic. They correspond with what Carla shows in its patchbay: a 'Carla' box that contains **audio-in1** and **audio-in2**. Audio from the mic is captured fine.

vs

*not working*:
When using the JACK + ALSA/MIDI (and 'continuous rack' because the patchbay option results in an error message), instead of the two items under 'Carla' in the QjackCtl Connections window, there is only one, called **import 0**. I connect that one to the **capture_1** input entry of my mic. But in Carla itself, the 'Carla' box still contains **audio-in1** and **audio-in2**; so it does not quite correspond to the situation displayed by QjackCtl. If I nevertheless connect everything up, no sound is produced through Carla. I am guessing that in this case, the audio from my mic simply isn't entering Carla at all (whereas the data from my midi controller go in fine - correspondingly, the ALSA midi connection in QjackCtl looks normal).

**Comment by falkTX** [comment]
Thanks for the report.

Can you post some screenshots of both carla and qjackctl so I understand the issue better?

**Comment by Euximion** [comment]
Hi, sorry for the long delay. Here are two screenshots. Note that in the working case, any connections changes I make in either program are immediately reflected in the other. Whereas in the nonworking case, this is not so. (E.g. disconnecting everything in Carla's patchbay does nothing to the QjackCtl connections.)

versions:
Linux Mint 15
Carla 1.9.6 (2.0-beta4)
jackdmp 1.9.10
QjackCtl 0.3.9

Good luck!

![carla qjackctl_not_working](https://cloud.githubusercontent.com/assets/10438224/5840531/82da5a98-a196-11e4-8ea1-71c9fc1d4f63.png)
![carla qjackctl_working](https://cloud.githubusercontent.com/assets/10438224/5840532/82e642a4-a196-11e4-9410-a20ea4251567.png)
