### ISSUE TITLE
Yoshimi-LV2 causes crash from .carxp file

### ISSUE THREAD

**Issue by Stazed** [falkTX/Carla#187]
1. Add yoshimi-lv2 to the rack
2. save to file .carxp
3. Try to drag and drop, load from menu or from nautilus.

Carla will freeze then eventually crash.
yoshimi-lv2 does save and load from qtractor.

**Comment by falkTX** [comment]
Are you sure it crashes?

I've been doing some tests here.
From what I saw carla just takes a very very very very long time to load the state.
Seems to be an issue dealing with the ~5Mb string xml file generated by yoshimi.

**Comment by Stazed** [comment]
I just checked on 2 machines.  The slow lenovo laptop I have did crash... 2gb etc.  My fast machine did finally load.  So the crash was prabably due the ancient machine, and my lack of patience on the fast one.  MY apologies.

**Comment by falkTX** [comment]
Note that I still find this a somewhat serious bug.
The fix (optimization) needs to be done in the Juce XML code though, I'll report it upstream.
