### ISSUE TITLE
Browse to plugin file (skip scanning)

### ISSUE THREAD

**Issue by ThoughtPhotography** [falkTX/Carla#1873]
Hi,

I only want to use Carla with a specific VST3 plugin (Slate VSX, hoping I can get systemwide working.)
Many potential users will have similar use cases. Rather than take 30+ minutes to scan all my plugins before I can even see if the program works for me, it would be much better to browse to the plugin I want to load vs. scan and populate a list with 99.9% of plugins I don't want.

A user could simply load Bluecat's Patchwork to load additional plugins/chains etc. and never need Carla to see any other plugin.

Btw, your scanning is better than some DAWs. A skip button should be a standard feature when scanning. :)

**Comment by falkTX** [comment]
just drag and drop the vst3 into carla then
