### ISSUE TITLE
Internal/LV2 plugin parameters changing on GUI close and re-open

### ISSUE THREAD

**Issue by Stazed** [falkTX/Carla#190]
1. From Carla host add Internal Carla-Rack/ Carla-Patchbay plugin
2. Open Carla-Rack/Patchbay plugin GUI
3. Add Internal ZynPhaser plugin to Carla-Rack/Patchbay rack
4. Open ZynPhaser parameters and make a note of the settings
   ex: LFO Frequency Default is 35
       LFO Stereo is 63
       Depth = 109 ... etc
       
5. Close ZynPhaser parameters
6. Close Carla-Rack GUI
7. Re-open Carla-Rack GUI and check the ZynPhaser parameters.
   On my machines the parameters will be decremented by 1
   ex: LFO Frequency becomes 34
       LFO Stereo becomes 62
       Depth becomes 108  ... etc
       
8. Each successive close and re-open of Carla-Rack GUI causes the decrement.
9. Occurs on all internal Zyn effects and on some LV2/DSSI effects.
10. On the LV2 plugins not all the parameters decrement as the internal ones do.
    ex: Load ZynPhaser from the LV2 list (not internal) and change the STAGES to 8.
    Upon close and re-open the stages decrement to 7 while all the other parameters
    do not change. In the ZynPhaser LV2 example, only the First close and re-open
    causes the decrement to the STAGES parameter.

I have noticed this occurring on other LV2 effects and DSSI (CALF) intermittently but
NOT on LADSPA or others.

Seems to occur with all the Carla Plugin variations and also occurs when using
Qtractor as the host.

Thanks for the quick response on the yoshimi issue!!!!

**Comment by falkTX** [comment]
This is probably an issue with float -> int -> float conversion.
Somewhere in the code the rounding is not working as intended.

I'll take a look a this soon.
