### ISSUE TITLE
reminder to change server ping from 5 secs, for closing carla

### ISSUE THREAD

**Issue by alextone** [falkTX/Carla#191]
As the title says, settings have been changed already for load, and save, but need changing for close as well.

Alex.

**Comment by falkTX** [comment]
carla can now take as long as it needs without the bridges auto-closing.
the only way that the bridges can close now is if they crash, receive a quit message, or don't receive a ping for 30 seconds.
considering the ping and other messages are handled outside the main thread I don't think bridges will ever auto-quit now.
