### ISSUE TITLE
`make win32` fails

### ISSUE THREAD

**Issue by egasimus** [falkTX/Carla#192]
...on this system:

```
Linux mesecina 3.17.6-1-ARCH #1 SMP PREEMPT Sun Dec 7 23:43:32 UTC 2014 x86_64 GNU/Linux
```

...with this output:

```
make[1]: Entering directory '/home/epimetheus/code/kunst/Carla/source/jackbridge'
Compiling JackBridgeExport.cpp
Creating jackbridge.win32e.a
make[1]: Leaving directory '/home/epimetheus/code/kunst/Carla/source/jackbridge'
make[1]: Entering directory '/home/epimetheus/code/kunst/Carla/source/modules/juce_audio_basics'
Compiling juce_audio_basics.cpp (32bit)
Creating juce_audio_basics.win32.a
make[1]: Leaving directory '/home/epimetheus/code/kunst/Carla/source/modules/juce_audio_basics'
make[1]: Entering directory '/home/epimetheus/code/kunst/Carla/source/modules/juce_audio_processors'
Compiling juce_audio_processors.cpp (32bit)
In file included from ../juce_gui_basics/../juce_graphics/../juce_core/system/juce_StandardHeader.h:53:0,
                 from ../juce_gui_basics/../juce_graphics/../juce_core/juce_core.h:143,
                 from ../juce_gui_basics/../juce_graphics/juce_graphics.h:28,
                 from ../juce_gui_basics/juce_gui_basics.h:28,
                 from juce_audio_processors.h:28,
                 from juce_audio_processors.cpp:39:
processors/juce_AudioProcessorEditor.cpp: In destructor ‘virtual juce::AudioProcessorEditor::~AudioProcessorEditor()’:
processors/juce_AudioProcessorEditor.cpp:39:24: error: ‘class juce::AudioProcessor’ has no member named ‘getActiveEditor’
     jassert (processor.getActiveEditor() != this);
                        ^
../juce_gui_basics/../juce_graphics/../juce_core/system/juce_PlatformDefs.h:108:46: note: in definition of macro ‘MACRO_WITH_FORCED_SEMICOLON’
  #define MACRO_WITH_FORCED_SEMICOLON(x) do { x } while (false)
                                              ^
processors/juce_AudioProcessorEditor.cpp:39:5: note: in expansion of macro ‘jassert’
     jassert (processor.getActiveEditor() != this);
     ^
Makefile:100: recipe for target '../../../build/juce_audio_processors/Release/juce_audio_processors.cpp.win32.o' failed
make[1]: *** [../../../build/juce_audio_processors/Release/juce_audio_processors.cpp.win32.o] Error 1
make[1]: Leaving directory '/home/epimetheus/code/kunst/Carla/source/modules/juce_audio_processors'
Makefile:227: recipe for target '/home/epimetheus/code/kunst/Carla/build/modules/Release/juce_audio_processors.win32.a' failed
make: *** [/home/epimetheus/code/kunst/Carla/build/modules/Release/juce_audio_processors.win32.a] Error 
```

**Comment by egasimus** [comment]
Some more info in case it's any use: after removing the offending `jassert` at `processors/juce_AudioProcessorEditor.cpp:39:24:`, `make win32` fails with this:

```
juce_graphics.cpp:78:24: fatal error: ft2build.h: No such file or directory
```

I have `freetype2` and `lib32-freetype2` installed, and `ft2build.h` is in `/usr/include/freetype2/`.

**Comment by falkTX** [comment]
hmm, why is freetype being used for win32 builds?
did you forgot to set:
```export WIN32=true```
?

**Comment by falkTX** [comment]
btw, I hope you're using mingw to build this "win32" method...
If you're trying to build the win32/64 bridges using regular gcc, it won't work.

**Comment by egasimus** [comment]
Whoa whoa whoa. Where are these things documented?

**Comment by falkTX** [comment]
They are not, these builds are still experimental.
I need a safe environment to test them (kxstudio repos) so that I have more control over the issues it generates.
Because it's still unfinished I'm not very interested on build issues.

BUT with the upcoming beta4 things are starting to look good.
I'll probably document how to build win32/64 bridges when that is released.

PS: If you really don't want to use the kxstudio repo packaged for some reason, you can see this archlinux PKGBUILD to understand how it's built:
https://aur.archlinux.org/packages/carla-bridges-win32-git/

**Comment by egasimus** [comment]
I tried that first, but had some build issues with it too. I'll give it another spin and try to make it work -- will post here if anything goes awry.

**Comment by egasimus** [comment]
Here's the output from `makepkg`. Do you know how to make it add add `src/VST3 SDK` (where the missing file seems to reside) to the include path?

```
==> Making package: carla-bridges-win32-git 2624.4036ed2-1 (Wed Jan 14 11:57:26 EET 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating carla-bridges-win32-git git repo...
Fetching origin
  -> Found vstsdk360_22_11_2013_build_100.zip
==> Validating source files with md5sums...
    carla-bridges-win32-git ... Skipped
    vstsdk360_22_11_2013_build_100.zip ... Passed
==> Extracting sources...
  -> Creating working copy of Carla git repo...
Reset branch 'makepkg'
  -> Extracting vstsdk360_22_11_2013_build_100.zip with bsdtar
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
make[1]: Entering directory '/home/epimetheus/build/carla-bridges-win32-git/src/carla-bridges-win32-git/source/jackbridge'
make[1]: Nothing to be done for 'win32e'.
make[1]: Leaving directory '/home/epimetheus/build/carla-bridges-win32-git/src/carla-bridges-win32-git/source/jackbridge'
make[1]: Entering directory '/home/epimetheus/build/carla-bridges-win32-git/src/carla-bridges-win32-git/source/modules/juce_audio_basics'
make[1]: Nothing to be done for 'win32'.
make[1]: Leaving directory '/home/epimetheus/build/carla-bridges-win32-git/src/carla-bridges-win32-git/source/modules/juce_audio_basics'
make[1]: Entering directory '/home/epimetheus/build/carla-bridges-win32-git/src/carla-bridges-win32-git/source/modules/juce_audio_processors'
Compiling juce_audio_processors.cpp (32bit)
In file included from juce_audio_processors.cpp:161:0:
format_types/juce_VSTPluginFormat.cpp:49:44: fatal error: pluginterfaces/vst2.x/aeffectx.h: No such file or directory
 #include "pluginterfaces/vst2.x/aeffectx.h"
                                            ^
compilation terminated.
Makefile:100: recipe for target '../../../build/juce_audio_processors/Release/juce_audio_processors.cpp.win32.o' failed
make[1]: *** [../../../build/juce_audio_processors/Release/juce_audio_processors.cpp.win32.o] Error 1
make[1]: Leaving directory '/home/epimetheus/build/carla-bridges-win32-git/src/carla-bridges-win32-git/source/modules/juce_audio_processors'
Makefile:227: recipe for target '/home/epimetheus/build/carla-bridges-win32-git/src/carla-bridges-win32-git/build/modules/Release/juce_audio_processors.win32.a' failed
make: *** [/home/epimetheus/build/carla-bridges-win32-git/src/carla-bridges-win32-git/build/modules/Release/juce_audio_processors.win32.a] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by falkTX** [comment]
Create a includes/vst folder and link pluginterfaces from VST3SDK in there, plus also the public.sdk folder.

**Comment by egasimus** [comment]
`/usr/includes/vst`? or `~/my-build-dir/carla-bridges-win32-git/includes/vst`? or `~/my-build-dir/carla-bridges-win32-git/src/carla-bridges-win32-git/includes/vst`? or what? sorry if I'm being annoying :(

**Comment by falkTX** [comment]
./source/includes/vst folder in the carla source.

**Comment by egasimus** [comment]
Hmm, it already exists?!

**Comment by falkTX** [comment]
then just create the symlinks there.
plugininterfaces and public.sdk need to exist inside and to link vst2.4 or vst3 sdk folders.

**Comment by egasimus** [comment]
No, I mean the symlinks already exist. `~/build/carla-bridges-win32-git/src/carla-bridges-win32-git/source/includes/vst` is a symlink pointing to `~/build/carla-bridges-win32-git/src/VST3 SDK` which is where the actual SDK is extracted. Yet the compiler doesn't seem to pick it up for some reason.

**Comment by falkTX** [comment]
oh, actually the folder is "vst2", not "vst".
ie, source/includes/vst2

sorry

**Comment by egasimus** [comment]
Yay! Progress! [...okay what.](http://pastebin.com/raw.php?i=4YSG1XG8)

**Comment by falkTX** [comment]
seems like your mingw might be broken.

**Comment by egasimus** [comment]
How do these things even break? Any next steps? I'll purge and reinstall every package with `mingw` in its name shown by `pacman -Qs` but other than that I have no idea how to proceed. I don't think I've messed with my mingw setup.

**Comment by falkTX** [comment]
It's "broken" because including a header generates errors.
This should never happen.

This might be fixable in Juce, but I'd have to update it first.
I can do that but I need time.

**Comment by egasimus** [comment]
After your latest commits, the Win32 VST bridge compiled. Thank you! :) However, `carla-database` doesn't see the bridge, and `carla-single` segfaulted with one plugin (Swierk) and showed no mouse in the GUI of another (Turnado). However, both plugins worked flawlessly in Carla proper.

**Comment by falkTX** [comment]
The bridges don't work on carla-single for some reason.
Something about wine + jack, I'll have to investigate later.

**Comment by egasimus** [comment]
Great, thank you again for your time :)

**Comment by wvengen** [comment]
I'm trying to compile the win32 bridge on Ubuntu 15.04, and I finally managed to get it done.

Preparations:
```sh
## add MinGW-X PPA for cross-compilation
$ sudo apt-repository-add ppa:tobydox/mingw-x-trusty -y
$ sudo apt-get update

## install old dependency, in case you're running a newer system
$ wget https://mirrors.kernel.org/ubuntu/pool/main/i/isl/libisl10_0.12.2-1_amd64.deb
$ sudo dpkg -i libisl10_0.12.2-1_amd64.deb

## install mingw and wine-dev packages
$ sudo apt-get install -y mingw32-x-gcc mingw32-x-pkgconfig mingw32-x-liblo wine1.6-dev

## get VST3 SDK from http://www.steinberg.net/en/company/developers.html
$ wget http://www.steinberg.net/sdk_downloads/vstsdk365_28_08_2015_build_66.zip
$ unzip vstsdk365*.zip
$ mv 'VST3 SDK' source/includes/vst2

## build static liblo (because it's not part of mingw32-x-liblo)
$ wget http://vorboss.dl.sourceforge.net/project/liblo/liblo/0.28/liblo-0.28.tar.gz
$ tar xzf liblo-0.28.tar.gz
$ (PATH=/opt/mingw32/bin:/opt/mingw32/x86_64-w64-mingw32/bin:$PATH && \
    cd liblo-0.28 && 
    ./configure --enable-static --disable-shared --host=i686-w64-mingw32 && \
    make -C src)
$ sudo cp liblo-0.28/src/.libs/liblo.a /opt/mingw32/lib
```

Then some changes were required:
* comment `_set_abort_behavior` in VSTSDK3's `base/source/fthread.cpp` ([would need msvcrt8+](https://sourceforge.net/p/mingw/support-requests/153/))
* comment `DEF_CLASS_IID (ISizeableStream)` in `source/modules/juce_audio_processors/format_types/juce_VST3Headers.h` since that's defined in VSTSDK3 now.

Finally building:
```sh
## cross-compile win32 vst bridge
$ PATH=/opt/mingw32/bin:/opt/mingw32/x86_64-w64-mingw32/bin:$PATH \
  AR=i686-w64-mingw32-ar CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ \
  PKG_CONFIG_LIBDIR=/opt/mingw32/lib/pkgconfig \
  WIN32=true LDFLAGS=-static \
  make win32
## compile jack bridge
$ make wine32
```

No sound yet, plugin UIs run and appear as jack clients.

**Comment by falkTX** [comment]
liblo is no longer a required dependency, so you can build carla-win32 without any external libs (except the vst sdk).
the juce thing has been fixed upstream, won't be needed when I update carla's copy of it.
the fthread.cpp changes is not something I can fix, obvious license reasons.

sadly the important thing - having the plugin actually working - I have no idea what's going on yet.

**Comment by wvengen** [comment]
Good to hear it'll be easier in the future :) I suppose the undefined symbol may disappear from the sdk again at some point - or else comment it out. I don't know if adding a dummy function would break plugins depending on msvcrt8. And I'm curious to find out what's happening in #234.
