### ISSUE TITLE
DAW freezes with CarlaRingBuffer::tryWrite(0x7ffc2b451d70, 4): failed, not enough space

### ISSUE THREAD

**Issue by pabloasanchez** [falkTX/Carla#1932]
Hello, thank you for Carla, it's an awesome project.
I have been using Carla for a long time with no relevant issues.
However today I tried to open a recent REAPER project, but REAPER froze, with this output:

```
/usr/local/lib/lv2/carla.lv2//usr/local/lib/lv2/carla.lv2/LC_NUMERIC / LANG is set to 'es_MX.UTF-8', overriding LC_NUMERIC environment to POSIX
Using WINEPREFIX '/home/unknown/.wine', with base RT prio 15 and server RT prio 10
Starting plugin bridge, command is:
/home/unknown/.vst/carla.vst/carla-bridge-win32.exe "VST2" "/home/unknown/.vst/MetalDemonV11.dll" """" 0
CarlaRingBuffer::tryWrite(0x7ffc2b451d70, 4): failed, not enough space
```

Both project and VST seemed to work fine recently. As far as I remember, I haven't made any significant changes to my system or updated REAPER, Carla, Wine.

Ubuntu 22.04.5 LTS x86_64
Carla 2.2.0
Python version: 3.10.12
Qt version:     5.15.3
PyQt version:   5.15.6
Binary dir:     /usr/local/lib/carla
Resources dir:  /usr/local/share/carla/resources

**Comment by falkTX** [comment]
that carla version is too old, so even if there was a fix it wont be on your version.
update first then try again

**Comment by pabloasanchez** [comment]
Thanks. [The website points to 2.2.0](https://kx.studio/Applications:Carla) but I didn't check the releases page.
