### ISSUE TITLE
Can't map MIDI controls to parameters with amsynth

### ISSUE THREAD

**Issue by jedomed** [falkTX/Carla#1946]
Hi, when using amsynth I can't map MIDI controls to parameters, all the options are greyed out and I can't find why, it doesn't happen with any other plugins I tried:

![image](https://github.com/user-attachments/assets/60722341-4e89-4e19-aefa-aee6ffa96a3a)
Maybe this is related, but I also don't see amsynth in the "Add Plugin" list, I can only add it by opening it directly from the folder: "/usr/local/lib/vst/amsynth_vst.so"

**Comment by falkTX** [comment]
that likely means amsynth doesnt report those parameters as automatable, so carla complies.

**Comment by jedomed** [comment]
That makes sense, I noticed half an hour after posting this that amsynth has it's own "MIDI Learn" feature, so there's no need to do it in Carla :-)
