### ISSUE TITLE
ReWire for Linux.

### ISSUE THREAD

**Issue by juanpc2018** [falkTX/Carla#1953]
PropellerHeads created [ReWire](https://en.wikipedia.org/wiki/ReWire_(software_protocol))
similar concept to Jack, but works like an Audio Input Plugin in the DAW "ProTools, etc..."

ReBirth 338 v2.01 works in [Linux / Wine](https://ubuntuforums.org/showthread.php?t=846551),
but there is No ReWire for Linux...

it would require a JackPlugin with 18 outputs or more, if using Reason.

**Comment by falkTX** [comment]
ReWire is a proprietary protocol not compatible with open-source tools.
