### ISSUE TITLE
Reopening Guitarix custom GUI does not reflect changes

### ISSUE THREAD

**Issue by zettberlin** [falkTX/Carla#196]
When I open Guitarix' custom GUI and make some settings, these settings are stored OK but when I reopen the GUI to make more changes the GUI *shows* the initial defaults again, not the settings made before.
These settings, however, have still effect as intended, they are *not* reset, just the GUI is.

**Comment by falkTX** [comment]
This was just fixed on the latest commit a few hours ago.
Please re-test.

**Comment by zettberlin** [comment]
awsome falkTX is awsome ;-)
Works perfectly, Guitarix looks as it is set both at reopening at runtime and reopening carla with the given patch.
 I'll mention this in the article, I am writing at the moment for the german Linux User mag ;-) As we are on it: would you mind to exchange some e-mails, answering some questions for the article? You know, all that rockstar-stuff ;-)

**Comment by falkTX** [comment]
exchanging emails is ok, but I'd prefer IRC if we both can get online at the same time.
(freenode network, #kxstudio or #lad channel)

you can also meet me at this year's LAC ;)

**Comment by zettberlin** [comment]
To be frank: I am not a big fan of chat, I am not that fast at typing and at the same time I am a bit snobbish about grammars, spelling etc.... So maybe I send you an E-mail, you have a look upon it and answer and then we may meet at IRC to clearify any remaining questions, would that be OK?
We should be at more or less the same timezone(UTC or UTC+1). Next week I hopefully could meet any apointment you like to propose.

**Comment by falkTX** [comment]
email should be fine then I guess.
