### ISSUE TITLE
Closing CALF custom GUI crashes Carla.

### ISSUE THREAD

**Issue by zettberlin** [falkTX/Carla#197]
I have a strange behaviour of some Calf-plugins in Carla. They work perfectly OK but whenever I adjust something in Calf Limiter or Multiband Limiter Carla crashes with core dumped as I close the native UI of the plugin.

Strange enough, that this happens in all combinations of Carla-git from Ubuntu 14.04 repos as well as in Carla built from git today and so with the repo-binaries of Calf as well as Calf built from git. 

The terminal tells me this:

Plugin DSP wants UI feature 'http://lv2plug.in/ns/ext/data-access', ignoring this
Plugin DSP wants UI feature 'http://lv2plug.in/ns/ext/instance-access', ignoring this
Will use LV2 Gtk2 UI, NOT!
Plugin DSP wants UI feature 'http://lv2plug.in/ns/ext/instance-access', ignoring this
Plugin DSP wants UI feature 'http://lv2plug.in/ns/ext/data-access', ignoring this
Will use LV2 Gtk2 UI, NOT!
using block size: 256
mlock 446078 bytes
Will use UI-Bridge, binary: "/usr/local/lib/carla/carla-bridge-lv2-gtk2"
CALF DEBUG: instance 0x3c60070 data 0x3c6e5f0
CALF DEBUG: calf 0x7f59d19a1df0 cpi 0x7f59d0fa2930
Send configures...
Trying to get window...
Match found using UTF-8 name
Match found using simple name
Speicherzugriffsfehler (Speicherabzug geschrieben)

The last line says: segfault.
Most strange, that it used to work perfectly well last week, no trouble like this at all, as long as I used Carla from Ubuntus Repos and still no trouble with the one build from source. 
Now this happens always, including with Ubuntus Carla and Calf, that used to work OK and that have not changed. I also deleted the settings in .config/FalkTX several times, made new patches etc....
Any version of Carla dies when closing the native GUI of any version of Calf Limiter, Calf Multiband Limiter and Calf Gate. The plugins have to be connected in the patchbay, opening/closing them when unconnected does not trigger the crash(nor does it anything useful ;-) )

**Comment by falkTX** [comment]
This is something we're trying to solve with the latest calf git code.

Does this happen everytime?

**Comment by zettberlin** [comment]
I can reproduce the crash reliably here. Any of the named CALF-Plugins crashes Carla, when it is connected to *both* audio in/out. When the modules input comes from a synth *inside* carla, there is no crash. It makes no difference, whether the connection is direct or with another plugin in between...

**Comment by kfoltman** [comment]
Which git version did you use, the one from repo.or.cz or from sourceforge? (the latter is usually out of date)

Does it still happen with the newest Git version?

**Comment by falkTX** [comment]
I tested it with a clone from yesterday, it still happens.
Can't reproduce it 100% of the time though.

**Comment by falkTX** [comment]
This bug should be fixed now with the latest calf-plugins-git and carla-git packages.

@zettberlin Please confirm.

**Comment by kfoltman** [comment]
I made a couple more changes related to object lifecycle, and there is one patch from falkTX that is a workaround for the crashes and is still not applied, but maybe it won't be necessary after the recent changes.

**Comment by zettberlin** [comment]
Tested whith a recent calf from repo.or.cz in Carla from git 3 days ago: cannot reproduce the problem anymore, works like a charm ;-)

**Comment by zettberlin** [comment]
I consider this closed, kudos to all!
