### ISSUE TITLE
include option to hide file browser

### ISSUE THREAD

**Issue by rhetr** [falkTX/Carla#199]
I have never used the file browser and would like to be able to hide it.

**Comment by falkTX** [comment]
The file-browser is just 1 of many tabs to come.
"Plugins" will be the 2nd one, displaying the plugins as a filesystem
ie, Filter > [list of lv2 filters]
"Presets" will likely be one too, but it will be tricky to implement.

tbh the reason for the file-browser is to have something on top of the mini-canvas.
I'll make an option to hide that, but there's probably good small content we can put in those new tabs.
Suggestions welcome :)

**Comment by rhetr** [comment]
Sounds good, though I'm in the process of writing my own [mini browser](https://github.com/rhetr/surplus/) that handles the way I like and can be easily utilized in other workflows (e.g. with ardour/probably qtractor), so I'd rather use mine. Would it be possible to hide the minicanvas in the rack view and have it simply jut out of the corner in the patchbay view?
