### ISSUE TITLE
retain connections when renaming plugin

### ISSUE THREAD

**Issue by rhetr** [falkTX/Carla#201]
whenever you rename a plugin the connections are lost, it can be quite inconvenient. Would also make https://github.com/falkTX/Carla/issues/200 easier

**Comment by falkTX** [comment]
This irritates me a bit sometimes too...
To do before the 2.0-final release.

**Comment by nilehmann** [comment]
This issue is the same reason because I get multiple assertion errors when renaming a plugin that is connected?

Carla assertion failure: "plugin != nullptr && plugin->isEnabled()" in file CarlaEngineThread.cpp, line 68

**Comment by falkTX** [comment]
renaming is not safe for now, I wrote that in the last release notes.
to be fixed soon.

**Comment by nilehmann** [comment]
Ah, ok. I started using Carla just two days ago and didn't know it :-)

**Comment by nilehmann** [comment]
Is safe to rename the plugin directly in the .carxp file?

**Comment by falkTX** [comment]
Yes.
You may need to modify the name in the connections too.
