### ISSUE TITLE
yosemite - build Error 71 bin/libcarla_*.*: No such file or directory

### ISSUE THREAD

**Issue by johndpope** [falkTX/Carla#203]
any ideas?

$ sudo make install
# Create directories
install -d /usr/local/bin/
install -d /usr/local/lib/carla/
install -d /usr/local/lib/carla/styles/
install -d /usr/local/lib/lv2/carla.lv2/
install -d /usr/local/lib/vst/carla.vst/
install -d /usr/local/lib/pkgconfig/
install -d /usr/local/include/carla/
install -d /usr/local/include/carla/includes/
install -d /usr/local/share/applications/
install -d /usr/local/share/carla/
install -d /usr/local/share/carla/resources/
install -d /usr/local/share/carla/resources/nekofilter/
install -d /usr/local/share/carla/resources/zynaddsubfx/
install -d /usr/local/share/icons/hicolor/16x16/apps/
install -d /usr/local/share/icons/hicolor/48x48/apps/
install -d /usr/local/share/icons/hicolor/128x128/apps/
install -d /usr/local/share/icons/hicolor/256x256/apps/
install -d /usr/local/share/icons/hicolor/scalable/apps/
install -d /usr/local/share/mime/packages/
# Install script files
install -m 755 \
		data/carla \
		data/carla-database \
		data/carla-patchbay \
		data/carla-rack \
		data/carla-single \
		data/carla-settings \
		/usr/local/bin/
# Install desktop files
install -m 644 data/*.desktop /usr/local/share/applications/
# Install icons, 16x16
install -m 644 resources/16x16/carla.png            /usr/local/share/icons/hicolor/16x16/apps/
install -m 644 resources/16x16/carla-control.png    /usr/local/share/icons/hicolor/16x16/apps/
# Install icons, 48x48
install -m 644 resources/48x48/carla.png            /usr/local/share/icons/hicolor/48x48/apps/
install -m 644 resources/48x48/carla-control.png    /usr/local/share/icons/hicolor/48x48/apps/
# Install icons, 128x128
install -m 644 resources/128x128/carla.png          /usr/local/share/icons/hicolor/128x128/apps/
install -m 644 resources/128x128/carla-control.png  /usr/local/share/icons/hicolor/128x128/apps/
# Install icons, 256x256
install -m 644 resources/256x256/carla.png          /usr/local/share/icons/hicolor/256x256/apps/
install -m 644 resources/256x256/carla-control.png  /usr/local/share/icons/hicolor/256x256/apps/
# Install icons, scalable
install -m 644 resources/scalable/carla.svg         /usr/local/share/icons/hicolor/scalable/apps/
install -m 644 resources/scalable/carla-control.svg /usr/local/share/icons/hicolor/scalable/apps/
# Install mime package
install -m 644 data/carla.xml /usr/local/share/mime/packages/
# Install pkg-config file
install -m 644 data/carla-standalone.pc /usr/local/lib/pkgconfig/
# Install backend libs
install -m 644 \
		bin/libcarla_*.* \
		/usr/local/lib/carla/
install: bin/libcarla_*.*: No such file or directory
make: *** [install] Error 71

**Comment by falkTX** [comment]
make install is only used for Linux systems.

if you want to install and package carla for OSX see the data/macos scripts.
"build-deps.sh" first, then "build.sh".
It's been a while since I used those scripts though, so they might be broken.

**Comment by johndpope** [comment]
thx
