### ISSUE TITLE
[Feature Request] Fixed or Static OSC port

### ISSUE THREAD

**Issue by didgewind** [falkTX/Carla#209]
Hi, it would be nice to have a fixed osc port or being able to choose one from the command line (like --osc-port option in non-mixer). There's a workaround described in http://fernandoquiros.com/always-get-osc-port-carla-kxproject/, but that involves compiling the sources.

Thanks!!!

**Comment by egasimus** [comment]
+1

**Comment by falkTX** [comment]
I'm planning on adding an OSC page to the carla settings later on.
Something with OSC on/off, static port numbers and other misc stuff.

Until that happens I can make the OSC port selection work via environment variables.

**Comment by egasimus** [comment]
By the way, is there a documented way to e.g. add a new plugin via OSC? I couldn't find one, or figure it out from reading the source.

**Comment by falkTX** [comment]
Adding plugins, no.

There are undocumented "/register" and "/unregister" methods that are used to sync with external apps (like carla-control), but I haven't worked on this for a while so it might be broken.
OSC has kinda being left for last in carla 2.x.

I'll get carla-control working again (and thus full OSC control) before the final version is released.

**Comment by falkTX** [comment]
Ok, now you can use:
```
export CARLA_OSC_UDP_PORT=12345
carla
```
or
```
env CARLA_OSC_UDP_PORT=12345 carla
```

Replace UDP with TCP if needed.

**Comment by bencrossman** [comment]
^^ Thanks for this, very useful

On Windows it's:
set CARLA_OSC_UDP_PORT=12345
