### ISSUE TITLE
Make: bin/CarlaRack*.* Not found

### ISSUE THREAD

**Issue by nabulator** [falkTX/Carla#210]
Running ubuntu 14.04 and having problems installing the program.
The `make install` command breaks down when trying to install the VST. 

> Install vst plugin
> install -m 644 \
>		bin/CarlaRack*.* \
>		bin/CarlaPatchbay*.* \
>		/usr/local/lib/vst/carla.vst/
>install: cannot stat ‘bin/CarlaRack*.*’: No such file or directory
>install: cannot stat ‘bin/CarlaPatchbay*.*’: No such file or directory
>make: *** [install] Error 1

Looks like the carlaRack files don't exist? I don't think my make failed or anything

**Comment by falkTX** [comment]
ah yes, in your current config the VST plugin is not built.
need to handle that case...
