### ISSUE TITLE
Carla freezes when playing with Shreddage sfz's

### ISSUE THREAD

**Issue by savuori** [falkTX/Carla#211]
I'm trying to use Shreddage guitar sfz's using Carla. It has 8 sfz files which are used simultaneously. I can usually load them up but after playing for a while Carla freezes. The last notes usually keep playing. I have tried this with lmms and bitwig, both behave the same way. Using plain LinuxSampler _seems_ to work but it's clunky and I need to have guitarix lv2 effects too. I can try to debug it & get more information about this if someone's willing to point me to the right direction.

**Comment by falkTX** [comment]
Can you link me to those sfzs? I'll take a look.

If you want to debug, simply do a "make DEBUG=true".
Then use "carla --debug" which will start gdb.
(or local build via 'gdb --args python3 source/carla'.

**Comment by sampovuori** [comment]
Unfortunately it's a commercial sound library http://impactsoundworks.com/products/guitar-and-bass/shreddage-complete-edition/ I don't know if they'd provide it for debugging purposes, Carla is pretty well known piece of software after all.

**Comment by falkTX** [comment]
Should not be an issue anymore, linuxsampler replaced by sfzero and all.
