### ISSUE TITLE
os x 32 bit bridge crash

### ISSUE THREAD

**Issue by J--L** [falkTX/Carla#214]
hi, 
just to mention crashes when trying to load VST 32 bit plugins in 32 bit bridge mode
thanks

http://fpaste.org/190914/96202414/

**Comment by falkTX** [comment]
I investigated this issue and can't fix for beta4 release.
MacOS is not liking that carla is opening 3 shared memory regions very shortly.

A fix will come in beta5.

**Comment by J--L** [comment]
thanks Filipe 


no more problem, Ardour + Mixbus are ok now 
JL 
----- Mail original -----

De: "Filipe Coelho" <notifications@github.com> 
À: "falkTX/Carla" <Carla@noreply.github.com> 
Cc: "J--L" <jeanluc.nest@free.fr> 
Envoyé: Jeudi 12 Mars 2015 18:34:40 
Objet: Re: [Carla] os x 32 bit bridge crash (#214) 


I investigated this issue and can't fix for beta4 release. 
MacOS is not liking that carla is opening 3 shared memory regions very shortly. 
A fix will come in beta5.

**Comment by falkTX** [comment]
bridges are now properly implemented on OSX, finally..
the next binary release will have them working again.

**Comment by J--L** [comment]
Hi Filipe 
or falk :) 


thanks ! 
with Robin, we've spent hours on a terrible libs problem from the Philarmonik2 64 bit update... I hope I get an answer this afternoon 


Best Wishes 
Jean-Luc or JL__ :) 

----- Mail original -----

De: "Filipe Coelho" <notifications@github.com> 
À: "falkTX/Carla" <Carla@noreply.github.com> 
Cc: "J--L" <jeanluc.nest@free.fr> 
Envoyé: Lundi 11 Janvier 2016 11:24:11 
Objet: Re: [Carla] os x 32 bit bridge crash (#214) 


bridges are now properly implemented on OSX, finally.. 
the next binary release will have them working again.

**Comment by J--L** [comment]
falktx isn't that the guy that keeps ranting about vst3 being stupid ? 




no, it's not me :) 
----- Mail original -----

De: "Filipe Coelho" <notifications@github.com> 
À: "falkTX/Carla" <Carla@noreply.github.com> 
Cc: "J--L" <jeanluc.nest@free.fr> 
Envoyé: Lundi 11 Janvier 2016 11:24:11 
Objet: Re: [Carla] os x 32 bit bridge crash (#214) 


bridges are now properly implemented on OSX, finally.. 
the next binary release will have them working again.

**Comment by falkTX** [comment]
hehe, ok got it :)

I'll let you know when osx binaries are ready

**Comment by J--L** [comment]
thanks 


and i got philharmonic 2 plugin to work !! 

----- Mail original -----

De: "Filipe Coelho" <notifications@github.com> 
À: "falkTX/Carla" <Carla@noreply.github.com> 
Cc: "J--L" <jeanluc.nest@free.fr> 
Envoyé: Lundi 11 Janvier 2016 18:45:15 
Objet: Re: [Carla] os x 32 bit bridge crash (#214) 


hehe, ok got it :) 
I'll let you know when osx binaries are ready

**Comment by J--L** [comment]
Hi Filipe 


just to be sure: ( cause I only found a tricky way to get this specific AU plugin update to work) 
the new Carla will be " able " to load AU in 64 and 32 bits ? 


Thanks 

----- Mail original -----

De: "Filipe Coelho" <notifications@github.com> 
À: "falkTX/Carla" <Carla@noreply.github.com> 
Cc: "J--L" <jeanluc.nest@free.fr> 
Envoyé: Lundi 11 Janvier 2016 18:45:15 
Objet: Re: [Carla] os x 32 bit bridge crash (#214) 


hehe, ok got it :) 
I'll let you know when osx binaries are ready

**Comment by falkTX** [comment]
yes, that is the intention.
