### ISSUE TITLE
Carla LMMS plugin error messages

### ISSUE THREAD

**Issue by mikobuntu** [falkTX/Carla#215]
Carla built from git master today.

Running LMMS from the terminal and as soon as I load Carla-rack plugin there is a constant overload of the following debug error:  ( note I used a screenshot as I could not copy and paste from the terminal )
![screenshot from 2015-02-28 23 38 15](https://cloud.githubusercontent.com/assets/335217/6428728/a61a67b6-bfa3-11e4-8eb1-4d66dbe1dd24.png)

Perhaps this is just a problem with how LMMS interfaces with your plugin, if so I will report to the LMMS devs?

thanks Mikobuntu :)

**Comment by Penguinum** [comment]
Have the same issue.

**Comment by mikobuntu** [comment]
**update**

I have pinpointed that the error messages stop while the actual Carla GUI is opened from the LMMS plugin " show GUI " button ( with the normal loading message " Trying to start carla-plugin using "/usr/local/share/carla/resources//carla-plugin" etc etc ), and then continue again when the Carla gui is closed.

**Comment by mikobuntu** [comment]
:+1:  good work :)
