### ISSUE TITLE
Carla cannot locate lv2 plugins within lmms

### ISSUE THREAD

**Issue by faraway1nspace** [falkTX/Carla#217]
Not sure if this is a carla or lmms issue... anyway, Carla-lmms doesn't see lv2 plugins. After clicking "add plugins" and hiting "refresh", it lists 0 lv2. I did a fresh install of lmms 1.1.3 from the kxstudio repos on Ubuntu 14.04.2, after installing both carla-git and carla-lv2 (1.9.6 2.0-beta4). Carla and lmms work fine together with ladspa and other plugins, but not with lv2.
 
The solution is to execute 'carla' outside of lmms, and repeat the 'add plugins'+'refresh': then Carla successfully finds the lv2 plugins. Futhermore, the newly found plugins are now available within the lmms-carla instances and work fine. If I install new lv2 plugins, then they are not available in lmms+carla until I once gain run the 'refresh' in carla outside of lmms.

So, this isn't a big deal, but it is confusing to lmms users if they don't use Carla outside of lmms, and aren't lucky enough to stumble upon this peculiar sequence to adding lv2 plugins.
Great job!

**Comment by falkTX** [comment]
I somehow missed this, I already had all the work done for this...

Fixed now.

**Comment by faraway1nspace** [comment]
Yep, that did it :)

**Comment by sonicmaelstrom** [comment]
Hi, 

I have the same problem. I have installed two LV2 plug ins but Carla doesn't not load them into the list after I hit refresh for some reason. I run Carla outside LMMS and I am using AVlinus2016 and Carla 1.9.6 (2 beta 4).


Any help would be greatly appreciated.

Thank you.
