### ISSUE TITLE
[LV2] Calf eq8: GUI update behaves with "high viscosity" when bypass button is toggled

### ISSUE THREAD

**Issue by distrozapper** [falkTX/Carla#218]
Hi falktx,
Not sure whether it is the right place to report, but maybe you can confirm and invoke more actions.
Running carla-git 1.9.5~git20150311.2 + Calf Equalizer 8 Band LV2 on updated system born from KXStudio_14.04b_64bit.iso
Steps:
- Start Carla in terminal
- add plugin: Calf Equalizer 8 Band LV2
- open the plugin's GUI
- set the Highpass unit to "ON" (the "Bypass" button is lit blueish by default here, KDE)
- Turn the Highpass Frequency knob and watch the graph adapting very slowly to the new value
  (it should update in realtime I think)
- Toggle the "Bypass" button, turn the Frequency knob again and watch the graph being updated in
  realtime 

Since this behaviour is the same under host jalv.gtk, I don't think it is Carla-related. But could you have a look at it?
Thanks in advance
Robert

**Comment by falkTX** [comment]
Well you say the behaviour is the same on jalv.gtk, so better report it to official calf then?

Also, make sure you're using the calf-plugins-git package and not calf-plugins.
The git version will soon be the stable one (new official calf release coming soon).

**Comment by distrozapper** [comment]
Yes I am using calf-plugins-git. So I will report to official calf support then. Thank you and have a nice time!
