### ISSUE TITLE
Carla hangs with cabbage-hsboscil GUI

### ISSUE THREAD

**Issue by distrozapper** [falkTX/Carla#221]
Carla hangs with
JUCE Assertion failure in juce_MessageManager.cpp:158
when cabbage-hsboscil-synth's GUI is invoked.
Happens with:
carla-git 1.9.5~git20150313.2
cabbage-plugins-extra-lv2/vst 1:20140623-1kxstudio3

**Comment by falkTX** [comment]
I need to update the cabbage stuff. Doing that now, but not sure when I'll finish...

**Comment by distrozapper** [comment]
Issue is fixed, thanks for the update!
