### ISSUE TITLE
Problems loading patches in native linux vsts

### ISSUE THREAD

**Issue by amsynthdotcom** [falkTX/Carla#222]
Hello!
For some reason, when I try to load my patches in my native vsts like Tunefish, Digits and Peggy2000, it causes the plugin to switch off. No crashes or disconnections, just that Carla doesn't load the patches.

Thanks!

brian

**Comment by falkTX** [comment]
What kind of patches are you loading?
Does carla print something in the terminal when this happens?

**Comment by amsynthdotcom** [comment]
The patches are native Carla patches. I'll run it again and post here what the terminal gives.
Thanks! 

brian

**Comment by amsynthdotcom** [comment]
Here's the error code from the terminal that I got when trying to load a preset in Digits:

KGlobal::locale(): Warning your global KLocale is being recreated with a valid main component instead of a fake component, this usually means you tried to call i18n related functions before your main component was created. You should not do that since it most likely will not work
Object::connect: No such signal org::freedesktop::UPower::DeviceAdded(QDBusObjectPath)
Object::connect: No such signal org::freedesktop::UPower::DeviceRemoved(QDBusObjectPath)


brian

**Comment by falkTX** [comment]
those warnings are related to kde and won't affect this.

I need to try this for myself.
Does it happen with all vsts? what about lv2s?

**Comment by amsynthdotcom** [comment]
I think the issue is really about preset handling. Some lv2s, such as the Calf Monosynth, have preset selection already incorporated, and works fine.  The Cabbage lv2 "Choir" has no means to import presets, and the Carla control window for Choir does not have the "load preset" button activated, so I cannot test it.  Amsynth (lv2 version) allows preset loading, but for some reason, no matter what preset is selected, the sound is always the same.

**Comment by falkTX** [comment]
I can confirm this issue.
Thanks for the report, I'll see if I can fix it soon.

**Comment by amsynthdotcom** [comment]
ok, thanks falkTX! :+1:
