### ISSUE TITLE
Calf plugins: GUI's "Bypass" button is ambivalent between hosts  Carla and calfjackhost

### ISSUE THREAD

**Issue by distrozapper** [falkTX/Carla#224]
Hi falkTX,
Running Calf equalizer (5band, 8band) LV2 GUI with Carla, I encounter the Bypass button being "lit" by default. This isn't the case with calfjackhost.
Under Carla, I have to toggle the Bypass button from on/lit -> off/non-lit -> on/lit to have calf equalizer have an effect.
Hope this describes enough, please let me know if you need more info.

**Comment by falkTX** [comment]
This seems related to another bug - the buttons on calf plugins are reversed.

On the same eq plugins, notice the "analyze" button activates the scope when it's OFF.
The same for the bypass, the plugin is ON when the bypass is ON.

It doesn't happen with jalv, so maybe it's really a carla bug.
Weird stuff...

**Comment by rhetr** [comment]
this also happens with the linuxdsp workstation plugins.
