### ISSUE TITLE
Carla doesn't load UI from uhe Zebra synth

### ISSUE THREAD

**Issue by daeavelwyn** [falkTX/Carla#225]
I've tried those plugins from uhe : 
http://www.kvraudio.com/forum/viewtopic.php?f=31&t=424953

I can load every UI except the zebra synth's one. The fact is carla even not recognize the zebra synth UI as you can see on the attached picture. The UI perfectly work when I use qtractor.
Let me know if you want futher tests.

![carla-issue1](https://cloud.githubusercontent.com/assets/4292225/6801057/e2c9f814-d224-11e4-9b0d-cfb68f65c73a.png)

**Comment by falkTX** [comment]
I know some u-he plugins make use of the vst-shell feature, which I sorta implemented in carla but never tested it.
Now I have some plugins to test it with. :)

To be fixed soon.

**Comment by daeavelwyn** [comment]
:-) thks !
