### ISSUE TITLE
makefile looks in wrong dir for theme/styles (master branch on 64bit Ubuntu)

### ISSUE THREAD

**Issue by mikobuntu** [falkTX/Carla#226]
make install fails with this error:-
 Install theme
install -m 644 \
		bin/styles/* \
		/usr/local/lib/carla/styles/
install: cannot stat ‘bin/styles/*’: No such file or directory
make: *** [install] Error 1

the correct place to look should be /Carla/source/theme/*

thanks :)

**Comment by falkTX** [comment]
installing should not use any files from the source/ dir, but from bin/ only.

it seems like you don't have the qt dev packages installed so carla skip building the custom theme.
I should add a check for that.

**Comment by mikobuntu** [comment]
ok thanks @falkTX  just noticing I'm missing a few dependencies with command 'make features'

mikobuntu@mikobuntu-MS-7721:~/Carla$ make features
---> Main features 
Front-End:   NO  [Missing PyQt]
LV2 plugin:  NO  [No front-end]
VST plugin:  NO  [No front-end]
OSC support: YES 

---> Engine drivers 
JACK:        YES 
ALSA:        YES 
PulseAudio:  YES 
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]

---> Plugin formats: 
Internal: YES 
LADSPA:   YES 
DSSI:     YES 
LV2:      YES 
VST:      YES (with UI)
VST3:     NO  [Windows and MacOS only]
AU:       NO  [MacOS only]

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     YES (bridge)
Gtk3:     NO  [Gtk3 missing]
Qt4:      YES (bridge)
Qt5:      NO  [Qt5 missing]
X11:      YES (direct+bridge)
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
GIG: NO   [LinuxSampler missing or too old]
SF2: YES 
SFZ: NO   [LinuxSampler missing or too old]

---> Internal plugins: 
Carla-Patchbay:  YES 
Carla-Rack:      YES 
DISTRHO Plugins: YES (with UI)
DISTRHO ProM:    YES 
ZynAddSubFX:     YES (with NTK UI)

**Comment by falkTX** [comment]
If you install something new to change those, you'll need to rebuild carla.

**Comment by mikobuntu** [comment]
yes with make clean && make distclean && make && make install <( as root )
