### ISSUE TITLE
lmms crashes with Triceratops & amsynth GUI parameter tweaking

### ISSUE THREAD

**Issue by faraway1nspace** [falkTX/Carla#227]
I'm not sure if this is an lmms (1.1.3) or Carla-git (1.9.6 2.0-beta4) issue, but lmms crashes when playing with the GUI's of triceratops-lv2, amsynth-lv2, occassionally synthv1. I say when playing with the GUI because if I just tweak parameters through the Carla rack parameter editor (I.e., the 'wrench' button) then I can tweak parameters without causing a crash. I am fine with this solution, but it is not necessarily optimal because not all parameters in the instruments' GUI have their full proper range in the Carla parameter editor: e.g., the Triceratops 'unison' parameters (which invariably cause the crash) are limited to just [0,1] range in the carla editor, whereas they have much larger values >1 in the Triceratops GUI (its not just a rescaling issue either). 

When crashing, Carla and the synth GUI remain open, but lmms crashes. I have a bunch of lmms .crash/apport files, and a few carla apport files. Running gdb on the lmms .crash returns the following report for both triceratop and amsynth crashes (just  a small snippet of the >5mb crash files):

Core was generated by `lmms'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f06e9ba9cc9 in __GI_raise (sig=sig@entry=6)

```
at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
```

56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

The above showed up for playing with Triceratops unison settings, as well as using amsynth portomento. Nothing shows up in the carla-terminal, just that lmms crashed. Again, I am not sure if it's lmms or Carla or triceratops issue, because the crashes do not happen if I use these synths in Carla outside of the lmms plugin.

Thanks for Carla!! Great work. Other lv2 instruments/plugins work like a charm (TAL-Noisemakr, Obxd, Wolpertinger, Zyn, drmr, MDA), but I can get any lmms-production out of triceratops, amsynth, and sorcer + openav all plugins).

**Comment by falkTX** [comment]
You should try the plugins in carla standalone and see if they also crash there.

The "SIGABRT" signal makes me believe the plugins are the one causing the crash though,
carla doesn't have "aborts" in the code.

**Comment by faraway1nspace** [comment]
No, they don't crash in carla standalone. I guess I should raise the issue on the triceratops github site. 
Would they also be responsible for the mis-match between the unison parameter range in the Carla parameter editor (0 to 1) versus the triceratops GUI (0 - 5)? Thanks again and great work.

**Comment by falkTX** [comment]
well, one bug at a time.
that bug should be reported separately, and leave this one for the crash.

before going any further, is your triceratops and carla both updated to their latest release?

**Comment by faraway1nspace** [comment]
Yep, latest in the kxstudio repositories or anywhere else I can find them. Carla-git 1.9.5 (although when I run it in terminal it says 1.9.6 2-beta-4) , triceratops-lv2 0.1.9, amsynth-lv2 1:1.5.1.

**Comment by falkTX** [comment]
the kxstudio repositories don't always have everything up to date.
triceratops for example is outdated now. (update coming)

**Comment by faraway1nspace** [comment]
Apologies, I found the latest. Yes, I can confirm that the same type of crash and error report happens with triceratops-lv2 0.3.0 (in lmms with carla-git). Presets now load, which is great, but doing so will often result in the crash too.
