### ISSUE TITLE
feature request: MIDI control/learn for Drywet, Volume, L and R knobs

### ISSUE THREAD

**Issue by Ghaydn** [falkTX/Carla#228]
...on Edit tab - as it made in Parameters tab.

**Comment by rhetr** [comment]
fyi those are currently set to the [CC defaults](http://nickfever.com/music/midi-cc-list)

**Comment by falkTX** [comment]
Volume, Dry/Wet and Balance will NOT have MIDI learn because their CC ids are static.

Volume uses CC 7 (volume)
Dry/Wet uses CC 2 (breath)
Balance uses CC 8 (balance)

This ought to be documented somewhere, but that's a different issue...

**Comment by Ghaydn** [comment]
1. Some plugins use these CCs for the same things.
2. It's useful to remap these parameters - for example when two or more synths are played at the same time.
3. It's also useful to remap them when controller is mapped for another things
4. Breath is not the same as dry/wet; balance (and Pan CC 10)  is not the same as L + R
5. There's also Portamento, Cutoff and many other defaults in MIDI standard - they are all recommended only

**Comment by falkTX** [comment]
1. You can set the "midi control channel" to any value or 'N' to disable this internal mapping so it won't conflict with plugin parameters.
2. You have 15 other midi channel at your disposal for this
3. same as 2
4. There is no real midi-cc equivalent of L+R (separate) and dry/wet, so carla uses somewhat equivalents of this. the midi-cc list, per spec, is only hints not requirements.
5. not sure what you mean here
