### ISSUE TITLE
parameter mismatch in Carla editor and Triceratops-lv2 GUI

### ISSUE THREAD

**Issue by faraway1nspace** [falkTX/Carla#229]
Hi,
Re-reporting the parameter mismatches in the Carla Rack parameter editor (i.e., the 'wrench') and the Triceratops GUI. Below I list the Triceratops tab name, the parameter: its correct range of values in the triceratops GUI; the incorrect range of values in Carla. Please note these are not rescaling issues, for example, raising the dco1 unison value to 1 in the Carla editor will correctly raise the Triceratops parameter value to 1, but it stops there and cannot raise it any further to its correct maximum value of 7.

UNISON DCO1: tri 0-7 continuous; carla 0-1 continuous
UNISON DCO2: same issue as above
UNISON DCO3: same issue as above
AMP/Filter Drive: tri 0-1 continuous; carla 0-80 continuous
LFO1 Retrig: tri on/off discrete; carla 0-2 continuous
LFO2 Retrig: same issue as above
LFO3 Retrig: same issue as above

Using triceratops 0.3 (from kxstudio, as well as from source) and carla-git 1.9.5 and carla standalone.

**Comment by falkTX** [comment]
This is not an issue with carla, but with triceratops.
Carla, like any other lv2 plugin host, reads the plugin information from its ttl files.

Look at this part of the triceratops.ttl file:
```
[
	a lv2:ControlPort, lv2:InputPort;
	lv2:index 102;
	lv2:symbol "unison_one";
	lv2:name "DCO1 Unison";
	lv2:minimum 0;
	lv2:maximum 1;
	lv2:default 0;
],
```
The maxium value is set to 1 by the plugin, so the host uses that value.

Triceratops is broken, please report the bug to them.
Thanks.
