### ISSUE TITLE
carla-control doesn't works

### ISSUE THREAD

**Issue by Houston4444** [falkTX/Carla#233]
I saw that the new package contains carla-control. There is an application in application menu. but it doesn't works. Launching carla-control from terminal says:
/usr/bin/python3: can't open file '/usr/share/carla/carla-control': [Errno 2] No such file or directory

the error is in /usr/bin/carla-control
It calls /usr/share/carla/carla-control
but the existing file is /usr/share/carla/carla_control
not a "-", but a "_"

**Comment by falkTX** [comment]
already fixed
