### ISSUE TITLE
Setting values for dB plugin parameters don't allow fractions

### ISSUE THREAD

**Issue by didgewind** [falkTX/Carla#236]
Using carla 2.0 beta 4 from 6th of April build, with a process mode of multiple clients in Ubuntu 14.10 with LXDE (Lubuntu).

When setting values manually for dB parameters (ex, Input gain or Limit in Fast Lookahead Limiter) you can only insert integer values.

Edit plugin, Set value in the context menu for any of the dB parameters.

**Comment by falkTX** [comment]
I don't think this is still an issue.
Sometime ago I reworked the set-value dialogs.

Please test with the latest carla version if this issue is still preset (or not) and report back.
Thanks.

**Comment by didgewind** [comment]
hey,

i was on a trip and right now i am really busy, but i'll check asap.

xxx

On 17/05/15 01:27, Filipe Coelho wrote:
>
> I don't think this is still an issue.
> Sometime ago I reworked the set-value dialogs.
>
> Please test with the latest carla version if this issue is still 
> preset (or not) and report back.
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/falkTX/Carla/issues/236#issuecomment-102711413>.
>

-- 
kike
Expand your consciousness through sound
http://sonicbaths.com
https://www.facebook.com/omandsb

**Comment by didgewind** [comment]
hi, sorry for the delay, it seems it's working ok.

xxx

On 17/05/15 00:27, Filipe Coelho wrote:
>
> I don't think this is still an issue.
> Sometime ago I reworked the set-value dialogs.
>
> Please test with the latest carla version if this issue is still 
> preset (or not) and report back.
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/falkTX/Carla/issues/236#issuecomment-102711413>.
>

-- 
kike
Expand your consciousness through sound
http://sonicbaths.com
https://www.facebook.com/omandsb

**Comment by falkTX** [comment]
thanks, I'll close the issue then.
