### ISSUE TITLE
segfault: void Jack::MidiBufferMixdown  "next_event != 0" 

### ISSUE THREAD

**Issue by nico202** [falkTX/Carla#238]
I was playing with carla-git from kxstudio repo (version 2.0beta4).
It segfaulted returning this:
python3: ../common/JackMidiPort.cpp:133: void Jack::MidiBufferMixdown(void*, void**, int, jack_nframes_t): asserzione "next_event != 0" non riuscita.

I loaded 3 instances of Yoshimi and 1 of vectorjuice. I don't know how to reproduce it.
Thanks, Nicolò

**Comment by falkTX** [comment]
This is not an issue with Carla but with JACK2, see https://github.com/jackaudio/jack2/issues/46.
