### ISSUE TITLE
Right-click plugin context menu in patchbay is missing "Replace" entry

### ISSUE THREAD

**Issue by SpotlightKid** [falkTX/Carla#241]
ATM it's only in the context menu of the rack view.

**Comment by falkTX** [comment]
replacing plugins in patchbay mode is not very complete, it needs to attempt to restore the old connections.
but yeah, the menu action is missing.

**Comment by falkTX** [comment]
Added in bd87821c3a1a2ef01e62387357fe7de07952fd5b.
