### ISSUE TITLE
Only 2 audio inputs and outputs in Jack/Patchbay engine mode

### ISSUE THREAD

**Issue by Xipazi** [falkTX/Carla#245]
Program version: Carla-2.0beta4-win32
Engine: JACK

This may be a feature, but I have 4 inputs and outputs in JACK and can only see 2 of each in the Jack/Patchbay engine mode.

**Comment by falkTX** [comment]
This is on purpose, the rack and patchbay engine modes in carla (when using jack) always use 2 audio ports.
If you're using JACK you can select multi-client mode to access all jack ports.
