### ISSUE TITLE
LowPass Filter crashed Carla

### ISSUE THREAD

**Issue by amsynthdotcom** [falkTX/Carla#248]
Hi falkTX,
I just updated Carla, then ran it in terminal. Loaded the LowPass Filter, and clicked the GUI button: Carla crashed.
Here's the output:

File exists:/usr/lib/vst/cabbage-LowpassFilter.csd
0dBFS level = 32768.0
Csound version 6.04 (double samples) Apr  2 2015
libsndfile-1.0.25
compiled Ok
everything still good...
GUI has been created
*** Leaked objects detected: 1 instance(s) of class ActiveProcess
*** Leaked objects detected: 1 instance(s) of class ChildProcess
*** Leaked objects detected: 1 instance(s) of class MouseInputSource
*** Leaked objects detected: 1 instance(s) of class MouseInputSourceInternal
*** Leaked objects detected: 1 instance(s) of class OwnedArray
*** Leaked objects detected: 1 instance(s) of class ScrollBar
*** Leaked objects detected: 1 instance(s) of class CabbageLookAndFeelBasic
*** Leaked objects detected: 1 instance(s) of class CabbageLookAndFeel
*** Leaked objects detected: 2 instance(s) of class LookAndFeel_V2
*** Leaked objects detected: 2 instance(s) of class LookAndFeel
*** Leaked objects detected: 1 instance(s) of class CabbagePluginAudioProcessorEditor
*** Leaked objects detected: 1 instance(s) of class ComponentBoundsConstrainer
*** Leaked objects detected: 1 instance(s) of class OwnedArray
*** Leaked objects detected: 1 instance(s) of class OwnedArray
*** Leaked objects detected: 2 instance(s) of class OwnedArray
*** Leaked objects detected: 4 instance(s) of class Component
*** Leaked objects detected: 4 instance(s) of class MouseCursor
*** Leaked objects detected: 1 instance(s) of class 'X11PluginUI'
*** Leaked objects detected: 1 instance(s) of class 'CarlaEngineJackEventPort'
*** Leaked objects detected: 4 instance(s) of class 'CarlaEngineJackAudioPort'
*** Leaked objects detected: 1 instance(s) of class 'CarlaEngineJackClient'
*** Leaked objects detected: 1 instance(s) of class JuceVSTWrapper
*** Leaked objects detected: 2 instance(s) of class AudioSampleBuffer
*** Leaked objects detected: 1 instance(s) of class TimerThread
*** Leaked objects detected: 1 instance(s) of class MemoryBlock
*** Leaked objects detected: 1 instance(s) of class CabbagePluginAudioProcessor
*** Leaked objects detected: 1 instance(s) of class MidiKeyboardState
*** Leaked objects detected: 5 instance(s) of class MidiBuffer
*** Leaked objects detected: 1 instance(s) of class TimeSliceThread
*** Leaked objects detected: 1 instance(s) of class OwnedArray
*** Leaked objects detected: 7 instance(s) of class AsyncUpdater
*** Leaked objects detected: 1 instance(s) of class AudioProcessor
*** Leaked objects detected: 1 instance(s) of class OwnedArray
*** Leaked objects detected: 1 instance(s) of class MessageManager
*** Leaked objects detected: 3 instance(s) of class Thread
*** Leaked objects detected: 8 instance(s) of class WaitableEvent
*** Leaked objects detected: 8 instance(s) of class StringArray
*** Leaked objects detected: 1 instance(s) of class 'CarlaPluginVST2'
*** Leaked objects detected: 1 instance(s) of class 'ProtectedData'
JUCE Assertion failure in juce_VST_Wrapper.cpp:543
JUCE Assertion failure in juce_VST_Wrapper.cpp:543
JUCE Assertion failure in juce_VST_Wrapper.cpp:543
JUCE Assertion failure in juce_VST_Wrapper.cpp:543
*** Leaked objects detected: 1 instance(s) of class MessageManager
*** Leaked objects detected: 1 instance(s) of class 'CarlaEngineJack'
*** Leaked objects detected: 1 instance(s) of class 'CarlaEngineOsc'
*** Leaked objects detected: 1 instance(s) of class 'CarlaEngineThread'
Segmentation fault (core dumped)

brian

**Comment by falkTX** [comment]
This is a known issue, see http://linuxmusicians.com/viewtopic.php?f=4&t=13724

**Comment by amsynthdotcom** [comment]
ok! thanks.
