### ISSUE TITLE
Multiple zyn instances in Carla and Ardour causes broken sound

### ISSUE THREAD

**Issue by caryoscelus** [falkTX/Carla#249]
Steps to reproduce:
* launch Ardour or Carla
* add MIDI track with ZynAddSubFx as synth (or the plugin in Carla) - sound is fine
* add another ZynAddSubFx track/plugin - sound is broken in both of them

I also tried Qtractor, but there's no issue with it, so it has something to with how host manages multiple instances.

Bisect shows that this commit is to blame: b3e434849a3b46436c6a51c28cb31d4d405d33c4. Prior to it everything works fine.

In case it helps, i'm using x86_64 GNU/Linux.

**Comment by falkTX** [comment]
Thanks for the report.
Do you know if ardour using more than 1 thread to do processing?

It's weird how adding a mutex that is precisely there to fix this issue is what causes it... :S

**Comment by caryoscelus** [comment]
Hmm, it has an option to choose amount of CPU cores used for signal
processing, so i assume so. I don't have any code knowledge of it
though.

**Comment by falkTX** [comment]
Ok thanks.
I don't use ardour much but I'll give it a test to see if I can replicate this bug.

btw, can you do a small recording of the issue?
Thanks

**Comment by caryoscelus** [comment]
Is it not reproducable in Carla for you?

Sure, i'll make one after i rebuild broken version.

**Comment by caryoscelus** [comment]
http://my-files.ru/DownloadSave/pgnii3/session.ogg - from ardour using it's export feature, this isn't exactly how it sounded when played, but still has glitches at the beginning and end
http://my-files.ru/DownloadSave/wcmoen/2015_05_05_testest-Track_3-1.flac - from carla, note that the sound continues even when i stop playing

**Comment by falkTX** [comment]
Fixed with the update to latest zyn.
A few things might be broken in the UI, so report any issues you find.

Banks are not working via zyn UI, but that's a known issue.
