### ISSUE TITLE
Convert fsthost files to Carla presets

### ISSUE THREAD

**Issue by Ghaydn** [falkTX/Carla#251]
Since Carla didn't support loading Windows VSTs before (on my past computer I had an old version) but fsthost worked fine - I have lots of FPS files. Now it's possible to load WinVST plugins directly to Carla (I suppose it included fsthost code, right?) - but how to load old FPS presets? Maybe a simple converter would be useful? Or if Carla could load them directly.

**Comment by falkTX** [comment]
fsthost and carla are completely separate projects and share no code.
if you want to load old fps presets in carla you can try to do a file-converter yourself.
