### ISSUE TITLE
Zyn UI is not displayed

### ISSUE THREAD

**Issue by caryoscelus** [falkTX/Carla#252]
Here's the error message i'm getting in console:

    Trying to start UI using "/usr/local/share/carla/resources/zynaddsubfx-ui"
    zynaddsubfx-ui: ERROR: Cannot find pixmaps/knob.png
    *** Leaked objects detected: 1 instance(s) of class 'CarlaPipeClient'
    *** Leaked objects detected: 1 instance(s) of class 'CarlaPipeCommon'
    ALL OK!

**Comment by caryoscelus** [comment]
This breaks building again:

    /usr/bin/ld: ../../build/native-plugins/Release/zynaddsubfx-ui.cpp.o: undefined reference to symbol 'dladdr@@GLIBC_2.2.5'
    //lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line

**Comment by falkTX** [comment]
hah, always something.
I'll fix that up too.
