### ISSUE TITLE
Library flag missing in Zyn Makefile

### ISSUE THREAD

**Issue by caryoscelus** [falkTX/Carla#253]
/usr/bin/ld: ../../build/native-plugins/Release/zynaddsubfx-ui.cpp.o: undefined reference to symbol 'XCreateBitmapFromData'
    //usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line

I added ZYN_LD_FLAGS  += -lX11 and it compiled, but not sure if that's enough since UI doesn't work for me.

**Comment by falkTX** [comment]
ah yes, I forgot about that.
the new zyn ui has code that uses some x11 calls directly, so it needs to link to x11.
