### ISSUE TITLE
Zyn: loading xiz crashes host, editing instrument crashes UI

### ISSUE THREAD

**Issue by caryoscelus** [falkTX/Carla#256]
As for editing - it crashes a moment after displaying AddSynth window. The plugin remains in working state, though, but never displays UI again.

**Comment by falkTX** [comment]
I reported the issue upstream, seems like a weird thing zyn is doing.
For now you can drag&drop xiz files into carla and they will work without crashing.

**Comment by caryoscelus** [comment]
Well, that's not really an option for me since i use zyn only as Ardour or Qtractor plugin. I'm just going to use old stable build until it will be possible to load and restore instruments through them..

**Comment by laanwj** [comment]
Good to see this is a known issue. Haven't noticed it crash (with master as of 3130631), but it appears Zyn no longer loads the instrument banks.

**Comment by caryoscelus** [comment]
"Banks are not working via zyn UI, but that's a known issue." (#249)

**Comment by falkTX** [comment]
bank loading is working.
it was a very temporary thing when I didn't implement some new stuff.

**Comment by caryoscelus** [comment]
Well, "Show instrument bank" still doesn't show any banks to load from.

**Comment by falkTX** [comment]
now that's a known issue ;)
