### ISSUE TITLE
Build fails when linuxsampler is present

### ISSUE THREAD

**Issue by caryoscelus** [falkTX/Carla#257]
./carla-lv2-export: error while loading shared libraries: liblinuxsampler.so.3: cannot open shared object file: No such file or directory
    Makefile:187: recipe for target '../../bin/carla.lv2/manifest.ttl' failed

Disabling linuxsampler build through source/Makefile.mk helps, but that isn't nice solution even if sampler is not required.

    $ pkg-config --libs linuxsampler
    -L/usr/local/lib/linuxsampler -llinuxsampler

**Comment by falkTX** [comment]
Your linuxsampler install seems to be broken.
Do you have /usr/local/lib/linuxsampler/liblinuxsampler.so.3 ?

Usually liblinuxsampler.so (what pkg-config is telling carla to use) is a symlink to liblinuxsampler.so.3, so if that file is missing linuxsampler based software won't build.

For now you can do:
```
make distclean
make HAVE_LINUXSAMPLER=false
```
Until you solve this issue in your system.

**Comment by caryoscelus** [comment]
I do have /usr/local/lib/linuxsampler/liblinuxsampler.so.3, .so
and .so.3.0.0 (first two are symlinks to third one), otherwise i
wouldn't post this issue.

**Comment by falkTX** [comment]
is /usr/local/lib/linuxsampler/liblinuxsampler.so.3.0.0 a valid file?

What does this command say:
```
ldd /usr/local/lib/linuxsampler/liblinuxsampler.so
```

**Comment by caryoscelus** [comment]
$ ldd /usr/local/lib/linuxsampler/liblinuxsampler.so
            linux-vdso.so.1 (0x00007fffb18a0000)
            libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
    (0x00007f438c018000) libgig.so.6
    => /usr/local/lib/libgig/libgig.so.6 (0x00007f438bdc8000)
    libsndfile.so.1 => /usr/lib/x86_64-linux-gnu/libsndfile.so.1
    (0x00007f438bb58000) libjack.so.0
    => /usr/lib/x86_64-linux-gnu/libjack.so.0 (0x00007f438b908000)
    libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2
    (0x00007f438b610000) libpthread.so.0
    => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f438b3f0000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f438b1e8000)
    libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1
    (0x00007f438afe0000) libstdc++.so.6
    => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f438acd0000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f438a9c8000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f438a618000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
    (0x00007f438a400000) libFLAC.so.8
    => /usr/lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007f438a188000)
    libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2
    (0x00007f4389ed0000) libopus.so.0
    => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f4389c80000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1
    (0x00007f4389a78000) /lib64/ld-linux-x86-64.so.2
    (0x00007f438c8e0000) libogg.so.0
    => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f4389868000)
    libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0
    (0x00007f4389638000)

Yes, it is valid. And linuxsampler does work standalone and as plugin.

**Comment by falkTX** [comment]
Ah wait, this is a different issue.
It links fine, but doesn't run.

That's because linuxsampler is on a custom library path that is not searched by default on linux.
(that is, /usr/local/lib/linuxsampler)

Please post the contents of /usr/local/lib/pkgconfig/linuxsampler.pc , thanks.

**Comment by caryoscelus** [comment]
Name: linuxsampler
    Description: LinuxSampler C++ library
    Version: 1.0.0.svn61
    Libs: -L${libdir} -llinuxsampler
    Cflags: -I${includedir}

**Comment by falkTX** [comment]
so there's no info there that will help us directly...
the only thing we can do is force rpath. not pretty but it may work.

**Comment by falkTX** [comment]
please pull the new code, make clean and build again.
let me know if it works now.

**Comment by caryoscelus** [comment]
Yeah, this seem to work.
