### ISSUE TITLE
Use more flexible build system?

### ISSUE THREAD

**Issue by caryoscelus** [falkTX/Carla#258]
Current Makefile system forces manually editing build files to disable/enable some feature, which is quite inconvenient.

**Comment by falkTX** [comment]
The makefile system is needed because of the alternative builds
(posix32, posix64, wine32, wine64, win32 and win64).

What feature do you want to enable or disable?
(Carla is supposedly to be built with the maximum features available)

**Comment by caryoscelus** [comment]
I can't see why makefile would handle alternative builds better than
more automated systems (except for the fact that they already handle
it).

Well, at the moment i would've disabled linuxsampler build until #257
is solved. In theory it can be used in any similiar situations when
some plugin build is problematic or to create custom packages in
distros.

**Comment by falkTX** [comment]
The other build systems do not allow to have multiple builds types inside a single project running *at the same time*.
ie, building the windows binaries while leaving the linux ones untouched.

I don't want to have to re-clone, build in separate dirs or just having to reconfigure the project for a new build type.

Anyway, the issue you have with linuxsampler is something in your system.
A library needed to build it is missing, so it's broken.

You can also do something like this:
```
make HAVE_LINUXSAMPLER=false
```

**Comment by caryoscelus** [comment]
Hmm, any system with out-of-source build support (e.g. cmake) would
automatically allow having multiple builds from single source. That
implies building in separate dirs though, so if just that is
unacceptable for you, there's nothing else i can propose.

Anyway, thx for pointing out a way to build without linuxsampler.

**Comment by falkTX** [comment]
FYI Anything you can see in source/Makefile.mk can be overridden.
And the things with "... ?= ..." will listen to environment variables.

So I think the build system is flexible enough :)
