### ISSUE TITLE
carla-patchbay duplicates internal clients

### ISSUE THREAD

**Issue by rhetr** [falkTX/Carla#263]
in a new carla-patchbay, the internal clients are duplicated such that there are 2 of each (e.g. 2 "Audio Input"s, 2 "Midi Input"s, etc). It appears to be an issue with the split/join functionality because the ports themselves aren't duplicated, and you can get rid of the duplicate clients by rightclick->join, but you cannot join the outputs and inputs like you can in the global patchbay, presumably since they don't have the same name.

**Comment by falkTX** [comment]
can you do a screenshot of this happening? thanks.

**Comment by rhetr** [comment]
![carla](https://cloud.githubusercontent.com/assets/4017049/7981509/cda5c7e0-0af2-11e5-9317-472234c2bdbf.jpg)

**Comment by rhetr** [comment]
![carla](https://cloud.githubusercontent.com/assets/4017049/7981533/f1761738-0af2-11e5-947c-debf7bdb86b8.jpg)

**Comment by falkTX** [comment]
oh that.
that is not a bug, it's intentional.
if you have clients/groups splitted and they don't provide both inputs+outputs there will be "empty" groups in there.

There's an option in carla's canvas settings, "Auto-hide groups with no ports" which will hide those for you.
