### ISSUE TITLE
Using the eq10q plugins within Carla results in different problems.

### ISSUE THREAD

**Issue by rvega** [falkTX/Carla#265]
I'm using Linux Mint 17 with the latest KXStudio repos. 
This happens happen with standalone Carla and using it as a VST plugin within Bitwig.

Load the EQ10Q, EQ4Q or EQ1Q plugins. Plugins load fine in the rack. If you make audio connections and then try to open the plugin GUI, it will not show up. If you open the GUI first and then connect audio, the GUI will show up but there will be no sound output from the plugin and the GUI's spectrum analyzer shows no input signal either.  Sometimes, making an input audio connection will crash the plugin and Carla. In this last case, the plugin's GUI will remain visible even after Carla crashed and disappeared.
With Carla Rack as a VST, in Bitwig, Carla crashes as soon as any of these plugins is loaded. I guess because the audio connection is done automatically by the host.

Other EQ10Q plugins behave better:

GT10QM appears to be working fine but crashes Carla when plugin is removed.
BassUp appears to be OK.
CS10QM appears to be OK.

**Comment by falkTX** [comment]
I don't think it's a problem in Carla, eq10q has never ran stable for me (the latest version).
I have been investigating the issue but no solutions yet.

(I think this has been reported already...)

**Comment by rvega** [comment]
Where can I find logs or dumps or whatever that is useful for you at this point?

**Comment by rvega** [comment]
I'll see if I can get Eq10q's author to join the conversation... 
Where can I find logs or dumps or whatever that is useful at this point?

**Comment by rvega** [comment]
https://sourceforge.net/p/eq10q/bugs/12/

**Comment by rvega** [comment]
Related https://github.com/falkTX/Carla/issues/239 (Duplicate?)

**Comment by falkTX** [comment]
A new eq10q update has been released, and it's on the kxstudio repos too now.
Please confirm if this is still an issue.
I think it might be fixed now.

**Comment by falkTX** [comment]
I'm considering this fixed because I can no longer get a crash.
If you can get it to crash let me know and I'll reopen this bug.

**Comment by rvega** [comment]
Tested very lightly and I'm not having crashes. I'll reopen if needed. Thanks!!
