### ISSUE TITLE
Carla crashes at "disconnect all"  

### ISSUE THREAD

**Issue by distrozapper** [falkTX/Carla#269]
Seems to be plugin type independent (happens with carla internal plugins, lv2, vst).
E.g. zynaddsubfx, zynEcho, zynChorus, Calf Monosynth, cabbage choir.
The more connections exist, the more likely carla crashes on "disconnect all".
In case of crash, carla leaves these lines in terminal:

Carla assertion failure: "! fUsingItenerator" in file ../../utils/LinkedList.hpp, line 236
Segmentation fault.

Happens on/with:
kxstudio/ubuntu 14.04 64bit KDE
recent carla-git package, version 1.9.6 (2.0-beta4)

**Comment by falkTX** [comment]
Ah, so my little code rework is making progress.
This means the code is somewhere iterating over a list twice.
I'll investigate.
