### ISSUE TITLE
Sustain (MIDI CC64) does not work in zynaddsubfx lv2 plugin

### ISSUE THREAD

**Issue by Fak3** [falkTX/Carla#271]
Sustain (MIDI CC64) does not work in zynaddsubfx lv2 plugin, when it is used in Carla or Ardour.
Sustain works for me in standalone zynaddsubfx (tried latest git and v 2.4.x)

Maybe related old issue (marked as fixed): https://github.com/falkTX/Carla/issues/56 (2013 may 25  - CC64 doesn't work with pianoteq lv2)

**Comment by falkTX** [comment]
Did you enable the "send control changes" option?

**Comment by Fak3** [comment]
Yes, it is enabled. "Sustain" is also enabled in the zynaddsubfx controller settings.

**Comment by Fak3** [comment]
I tried synthv1 in carla, and it does work properly - sustain is honored, when it "send control changes" option is enabled. Only zynaddsubfx does not work.
