### ISSUE TITLE
rpmlint error: zynaddsubfx-ui binary in /usr/share  hierarchy

### ISSUE THREAD

**Issue by Fak3** [falkTX/Carla#272]
Trying to build rpm lead me to this error from rpmlint.

```
[  489s] Carla.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/carla/resources/zynaddsubfx-ui
[  489s] This package installs an ELF binary in the /usr/share  hierarchy, which is
[  489s] reserved for architecture-independent files.
```

Not sure about severity of this, i am still allowed to build a package for my distro (openSUSE) with this error. Maybe this will hit in the future, if the rules will become more strict.

**Comment by falkTX** [comment]
well, those UI files are binaries yeah but they need to be in the resources folder.
I know debian will not like this either...

Do you know if a symlink to a binary is ok?

**Comment by falkTX** [comment]
carla no longer installs the internal zynaddsubfx plugin by default.
no binaries are installed on /usr/share now.
