### ISSUE TITLE
install failed due to missing directory

### ISSUE THREAD

**Issue by JohnOShock** [falkTX/Carla#274]
after compiling with 'make' and running 'sudo make install' the following: 

john@linux-fi0j:~/Downloads/Audio/Carla-master> sudo make install
root's password:
# Create directories
install -d /usr/local/bin/
# .... ......... .....and so on until:
# Install theme
install -m 644 \
	bin/styles/* \
	/usr/local/lib/carla/styles/
install: cannot stat ‘bin/styles/*’: No such file or directory
Makefile:399: recipe for target 'install' failed
make: *** [install] Error 1

the directory does not exist in the package downloaded from here today prior to time of writing this..

**Comment by falkTX** [comment]
please post your output of "make features" (run it the carla code dir)

**Comment by JohnOShock** [comment]
like so? (sorry. I'm a bit of a newbie)
john@linux-fi0j:~/Downloads/Audio/Carla-master> make features
\033[36m---> Main features \033[0m
Front-End:  \033[31m NO \033[0m \033[33m[Missing PyQt]\033[0m
LV2 plugin: \033[31m NO \033[0m \033[33m[No front-end]\033[0m
VST plugin: \033[31m NO \033[0m \033[33m[No front-end]\033[0m
OSC support:\033[31m NO \033[0m \033[33m[Missing liblo]\033[0m

\033[36m---> Engine drivers \033[0m
JACK:       \033[32m YES \033[0m
ALSA:       \033[31m NO \033[0m \033[33m[Missing ALSA]\033[0m
PulseAudio: \033[31m NO \033[0m \033[33m[Missing PulseAudio]\033[0m
CoreAudio:  \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m
ASIO:       \033[31m NO \033[0m \033[30;1m[Windows only]\033[0m
DirectSound:\033[31m NO \033[0m \033[30;1m[Windows only]\033[0m

\033[36m---> Plugin formats: \033[0m
Internal:\033[32m YES \033[0m
LADSPA:  \033[32m YES \033[0m
DSSI:    \033[32m YES \033[0m
LV2:     \033[32m YES \033[0m
VST:     \033[32m YES \033[0m(with UI)
VST3:    \033[31m NO \033[0m \033[30;1m[Windows and MacOS only]\033[0m
AU:      \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m

\033[36m---> LV2 UI toolkit support: \033[0m
External:\033[32m YES \033[0m(direct)
Gtk2:    \033[32m YES \033[0m(bridge)
Gtk3:    \033[32m YES \033[0m(bridge)
Qt4:     \033[32m YES \033[0m(bridge)
Qt5:     \033[31m NO \033[0m \033[33m[Qt5 missing]\033[0m
X11:     \033[32m YES \033[0m(direct+bridge)
Cocoa:   \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m
Windows: \033[31m NO \033[0m \033[30;1m[Windows only]\033[0m

\033[36m---> File formats: \033[0m
GIG:\033[31m NO \033[0m  \033[33m[LinuxSampler missing or too old]\033[0m
SF2:\033[31m NO \033[0m  \033[33m[FluidSynth missing]\033[0m
SFZ:\033[31m NO \033[0m  \033[33m[LinuxSampler missing or too old]\033[0m

\033[36m---> Internal plugins: \033[0m
Carla-Patchbay: \033[32m YES \033[0m
Carla-Rack:     \033[32m YES \033[0m
DISTRHO Plugins:\033[32m YES \033[0m(with UI)
DISTRHO ProM:   \033[31m NO \033[0m (missing libprojectM)
ZynAddSubFX:    \033[31m NO \033[0m \033[33m[fftw3, mxml or zlib missing]\033[0m

**Comment by JohnOShock** [comment]
like so? (sorry. I'm a bit of a newbie)
john@linux-fi0j:~/Downloads/Audio/Carla-master> make features
\033[36m---> Main features \033[0m
Front-End:  \033[31m NO \033[0m \033[33m[Missing PyQt]\033[0m
LV2 plugin: \033[31m NO \033[0m \033[33m[No front-end]\033[0m
VST plugin: \033[31m NO \033[0m \033[33m[No front-end]\033[0m
OSC support:\033[31m NO \033[0m \033[33m[Missing liblo]\033[0m

\033[36m---> Engine drivers \033[0m
JACK:       \033[32m YES \033[0m
ALSA:       \033[31m NO \033[0m \033[33m[Missing ALSA]\033[0m
PulseAudio: \033[31m NO \033[0m \033[33m[Missing PulseAudio]\033[0m
CoreAudio:  \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m
ASIO:       \033[31m NO \033[0m \033[30;1m[Windows only]\033[0m
DirectSound:\033[31m NO \033[0m \033[30;1m[Windows only]\033[0m

\033[36m---> Plugin formats: \033[0m
Internal:\033[32m YES \033[0m
LADSPA:  \033[32m YES \033[0m
DSSI:    \033[32m YES \033[0m
LV2:     \033[32m YES \033[0m
VST:     \033[32m YES \033[0m(with UI)
VST3:    \033[31m NO \033[0m \033[30;1m[Windows and MacOS only]\033[0m
AU:      \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m

\033[36m---> LV2 UI toolkit support: \033[0m
External:\033[32m YES \033[0m(direct)
Gtk2:    \033[32m YES \033[0m(bridge)
Gtk3:    \033[32m YES \033[0m(bridge)
Qt4:     \033[32m YES \033[0m(bridge)
Qt5:     \033[31m NO \033[0m \033[33m[Qt5 missing]\033[0m
X11:     \033[32m YES \033[0m(direct+bridge)
Cocoa:   \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m
Windows: \033[31m NO \033[0m \033[30;1m[Windows only]\033[0m

\033[36m---> File formats: \033[0m
GIG:\033[31m NO \033[0m  \033[33m[LinuxSampler missing or too old]\033[0m
SF2:\033[31m NO \033[0m  \033[33m[FluidSynth missing]\033[0m
SFZ:\033[31m NO \033[0m  \033[33m[LinuxSampler missing or too old]\033[0m

\033[36m---> Internal plugins: \033[0m
Carla-Patchbay: \033[32m YES \033[0m
Carla-Rack:     \033[32m YES \033[0m
DISTRHO Plugins:\033[32m YES \033[0m(with UI)
DISTRHO ProM:   \033[31m NO \033[0m (missing libprojectM)
ZynAddSubFX:    \033[31m NO \033[0m \033[33m[fftw3, mxml or zlib missing]\033[0m

**Comment by falkTX** [comment]
ok, it seems like you have a lot of stuff required to get the carla interface missing.

I can certainly fix the install when the theme is missing, but if you continue now you won't get the carla GUI. (Which I guess is not what you want?)

**Comment by JohnOShock** [comment]
right, so I don't understand what I should do... sorry about the delayed responses but I am in a GMT +8 timezone

**Comment by JohnOShock** [comment]
right, so I don't understand what I should do... sorry about the delayed responses but I am in a GMT +8 timezone

**Comment by JohnOShock** [comment]
I notice it says things are missing like QT5 which is actually installed ... I also have alsa... I'm using cadence and Jack works fine and am even running pusleaudio through it

**Comment by falkTX** [comment]
If you have issues building Carla you can always try the binaries.
See the bottom of this page: http://kxstudio.sourceforge.net/Applications:Carla#Download

**Comment by JohnOShock** [comment]
OK will do .... thanks

**Comment by JohnOShock** [comment]
Yes, I did download the kxstudio binaries and everything is working nicely..  thanks
