### ISSUE TITLE
Carla doesn't load midi binding properly from .carxp file

### ISSUE THREAD

**Issue by sonejostudios** [falkTX/Carla#276]
It saves them properly in the .carxp file, but while loading it into carla only the first few parameters are set.
all the best
vince (superdirt)

**Comment by falkTX** [comment]
which kind of plugin are you using? internal, ladspa, lv2 ?

can you upload an example carxp file with this issue?

**Comment by sonejostudios** [comment]
for now only lv2.
https://dl.dropboxusercontent.com/u/1560838/carlatest3.carxp

in the file all parameter are saved properly. the bug happens only while opening the file.

is carla also saving the patchbay connections?

**Comment by falkTX** [comment]
I see that you're using carla version 1.
Please try the project in the new carla 2.x series and let me know if the issue is still present.

**Comment by sonejostudios** [comment]
hey FalkTX
with 2.x is the same problem with opening carxp files, only the 3 first parameters are loaded properly. Maybe it is a bug because all parameters have the same name? (send1, send2)

**Comment by falkTX** [comment]
well, looking at the project you uploaded I can see why some values are ignored.
the plugin uses the same symbols for several ports, which is forbidden by lv2.
in short, the plugin is broken.

if you try to save in any other decent host you'll get the same issues.

**Comment by sonejostudios** [comment]
ha okay nice to know. I made this plugin with faust, faust seems to accept that but not its lv2 build..
Do you mean with symbols the parameter name?
I'll fix it. Thank you for the support!

**Comment by falkTX** [comment]
I don't know how faust-lv2 works, so can't say too much about it.

but anyway, you can name your ports whatever you like.
the lv2 symbols are the ones that must be unique.

the faust code is probably generating lv2 symbols from the name the user provides.
BUT it must make sure the symbols are unique.
I do this for the juce-lv2 wrapper, see https://github.com/DISTRHO/DISTRHO-Ports/blob/master/libs/juce/source/modules/juce_audio_plugin_client/LV2/juce_LV2_Wrapper.cpp#L126

who makes faust-lv2? can you ping them about this issue?

**Comment by sonejostudios** [comment]
I think it's Albert Gräf, I'll report the bug. Thx for the info!

**Comment by falkTX** [comment]
Forgot about this bug..
afaik this seems like a faust-lv2 issue, as it should *never* allow duplicated port symbols.
If any port symbol is duplicated the host will get messed up (not just carla).
