### ISSUE TITLE
bypass Carla Midi binding 

### ISSUE THREAD

**Issue by sonejostudios** [falkTX/Carla#278]
Is there a possibility to bypass carla's own midi binding?
in my case CC34 is assigned by carla to Filta Dry/Wet and I'd like to disconnect it so I could use cc34 somewhere else.

**Comment by sonejostudios** [comment]
workaround: just set carla controls to channel 2 and the problem is solved  :)

**Comment by falkTX** [comment]
you can also set the "midi control channel" to N which disables for all channels.
