### ISSUE TITLE
Renaming Plugins in Carla: strenge behaviour

### ISSUE THREAD

**Issue by sonejostudios** [falkTX/Carla#279]
Renaming a plugin changes the port name (add a number in parenthesis)

outL becomes outL (n) while n is the number of time the plugin is renamed. Is that a normal behaviour? Because renaming a plugin will cause loosing the connections after reloading the project, right?

**Comment by falkTX** [comment]
This was just fixed a few days ago.
Please make sure you have the latest carla version installed.

As I said in another bug report, I update it quite often.. ;)

**Comment by sonejostudios** [comment]
great!

**Comment by falkTX** [comment]
so can you confirm if the issue is fixed?

**Comment by sonejostudios** [comment]
Is the last git version already in th kxstudio repo? i'm using 1.9.6 (2.0beta4) right now.

**Comment by falkTX** [comment]
It is, it always is.

Everytime I do a change in the source I quickly follow up with a package update in the repos.

**Comment by sonejostudios** [comment]
Hmm I tried again but the renaming bug is still here. Carla version is 1.9.5~git20150423.2

**Comment by falkTX** [comment]
that version is several months old.
which distro are you using?

**Comment by sonejostudios** [comment]
linuxmint 13 (ubuntu 12.04 LTS) with kxstudio repos.

**Comment by falkTX** [comment]
ah I see, I no longer do kxstudio updates for 12.04 based distros.
you'll need to either update to 14.04, build carla manually or wait for the next release binaries.
