### ISSUE TITLE
parameters of vst plugin are changed when opening carla-rack plugin 

### ISSUE THREAD

**Issue by rghvdberg** [falkTX/Carla#280]
Ardour 4.1 session with carla-rack as plugin.
Carla as host, has Charlatan win64 plugin loaded (http://www.blaukraut.info/).
When opening carla-rack plugin, parameters of the win64 plugin are changed. You can easily hear this.

video: https://www.youtube.com/watch?v=fSpJvuf--ag

dpkg -l | grep carla
ii  carla-bridge-win32      2:1.9.5~git20150630.2     amd64        carla win32 bridge
ii  carla-bridge-win64      2:1.9.5~git20150630.2    amd64        carla win64 bridge
ii  carla-bridge-wine32    2:1.9.5+git20150630       i386         carla win32 bridge (wine DLL)
ii  carla-bridge-wine64    1.9.5+git20150423          amd64        carla win64 bridge (wine DLL)
ii  carla-data                    2:1.9.5~git20150705       all          audio plugin host (common data)
ii  carla-git                       2:1.9.5~git20150705        amd64        audio plugin host
ii  carla-lv2                      2:1.9.5~git20150705        amd64        audio plugin host (LV2 plugin)
ii  carla-vst                      2:1.9.5~git20150705        amd64        audio plugin host (VST plugin)

 dpkg -l | grep ardour
ii  ardour4                        1:4.1.0-1kxstudio1  amd64        digital audio workstation (graphical gtk2 interface)

**Comment by falkTX** [comment]
hmm, that is weird.

inside your ardour project folder there should a lv2 bundle/preset of that carla-rack instance.
can you try to find it and upload it?

have you experienced this with other plugins?
native ones? some other win64 vst?

**Comment by rghvdberg** [comment]
this is the first time i've noticed this

there were a lot of files/directories in the plugin dir, I guess this is 
the one. (removed the rest and the plugin still loads)

Op 05-07-15 om 18:54 schreef Filipe Coelho:

**Comment by rghvdberg** [comment]
update: same thing happens in Qtractor
video ! https://www.youtube.com/watch?v=Gra8UoCCpw4

**Comment by rghvdberg** [comment]
update: parameter change when saving preset ...
video ! https://www.youtube.com/watch?feature=player_detailpage&v=_1li8tMfrSg

**Comment by rghvdberg** [comment]
Just tried it with obxd as win32 vst plugin. Same thing happens. Parameters are changed when saving preset.

**Comment by falkTX** [comment]
what about native ones?

hopefully I'll be able to look at this today..

**Comment by rghvdberg** [comment]
Native Noize Mak3r VST plugin. Same thing :-(

**Comment by falkTX** [comment]
ok, I can confirm this issue.

investigating...

**Comment by falkTX** [comment]
something is wrong with charlatan, after loading a project with it inside it will sound different.
but I have right now the old (unclosed) and new project loaded at the same time, and the parameter values are the same.
still, it sounds different (high pitched on the loaded project)

hmmm

**Comment by falkTX** [comment]
Thanks for the report, I found some minor things with carla as plugin that needed fixing thanks to this.

The fact that some plugins sound different when loading their preset/project is a different issue.
If you experience it and it bothers you too much please fill a new bug report.
