### ISSUE TITLE
Can't load plug-ins in carla-rack

### ISSUE THREAD

**Issue by wargreen** [falkTX/Carla#281]
Carla-rack just don't load any plug-ins.
When carla-rack is loaded inside carla, i got 
readlineblock timed out
Carla assertion failure: "readNextLineAsUInt(options)" in file CarlaEngineNative.cpp, line 197
Got SIGTERM -> Closing now
when I try to load an plug-in.

At carla init :
Carla 1.9.6 (2.0-beta4) started, status:
  Python version: 3.4.3+
  Qt version:     4.8.7
  PyQt version:   4.11.4
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
ALL OK!

**Comment by wargreen** [comment]
It work  after updating...

**Comment by falkTX** [comment]
ok then
