### ISSUE TITLE
Recent CALF GUI do not show animation in carla

### ISSUE THREAD

**Issue by zettberlin** [falkTX/Carla#282]
Calf Multi Chorus 0.0.60, as built today from Calfs git does not show its animations in Carla. The animation-window works as expected in both calfjackhost and Ardour 4.1. 
Carla shows an empty space.

While loading in carla I get:

Test UI feature http://lv2plug.in/ns/extensions/ui#makeResident
Is resizable => true
ALL OK!
CALF DEBUG: instance (nil) data (nil)
Configuration not available because of lack of instance-access/data-access

I have no explanation, same effect in Calf Analyser and others from Calf 
Similar animations work OK in CS10Q Compressor and Signal Distribution Histogram...

**Comment by falkTX** [comment]
See https://github.com/falkTX/Carla/issues/247

Not a bug but a feature.
