### ISSUE TITLE
After latest update carla won't load any windows vst (64 or 32 bit)

### ISSUE THREAD

**Issue by rghvdberg** [falkTX/Carla#283]
Title says it all 
After latest update carla won't load any windows vst (64 or 32 bit) :scream: 

output of terminal

>$ carla
>Using "carla" theme
Carla 1.9.6 (2.0-beta4) started, status:
  Python version: 3.4.0
  Qt version:     4.8.6
  PyQt version:   4.10.4
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
libjack.so.0 loaded sucessfully!
Error opening file /usr/lib/lv2/PowerCut/manifest.ttl (Bestand of map bestaat niet)
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/PowerCut/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///usr/lib/lv2/PowerCut/manifest.ttl
Carla Server Info:
  sizeof(BridgeRtClientData):    6360
  sizeof(BridgeNonRtClientData): 16400
  sizeof(BridgeNonRtServerData): 65552
starting plugin bridge, command is:
/usr/lib/carla/carla-bridge-win32.exe "VST2" "/home/rob/vst/Synth1/Synth1 VST.dll" "Synth1 Soft Synth" 1395742323
WINE realtime scheduling hack enabled, realtime base priority has been set to 15
wineserver running SCHED_NORMAL
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: /usr/lib/i386-linux-gnu/pkcs11/p11-kit-trust.so: kan gedeeld objectbestand niet openen: Bestand of map bestaat niet
Carla assertion failure: "funcs->unique1 == funcs->unique2" in file JackBridgeExport.cpp, line 65
A JACK or Wine library is missing, cannot continue
CarlaPluginBridgeThread::run() - bridge closed cleanly
>plugin bridge finished
  
carla package installed

>$ dpkg -l | grep carla
>ii  carla-bridge-win32                          2:1.9.5~git20150722                                 amd64        carla win32 bridge
ii  carla-bridge-win64                          2:1.9.5~git20150722                                 amd64        carla win64 bridge
ii  carla-bridge-wine32                         2:1.9.5+git20150722                                 i386         carla win32 bridge (wine DLL)
ii  carla-bridge-wine64                         2:1.9.5+git20150722                                 amd64        carla win64 bridge (wine DLL)
ii  carla-data                                  2:1.9.5~git20150722                                 all          audio plugin host (common data)
ii  carla-git                                   2:1.9.5~git20150722                                 amd64        audio plugin host
ii  carla-lv2                                   2:1.9.5~git20150722                                 amd64        audio plugin host (LV2 plugin)
ii  carla-vst                                   2:1.9.5~git20150722                                 amd64        audio plugin host (VST plugin)

**Comment by falkTX** [comment]
I forgot to update some packages, should be fixed now.
Please confirm.

**Comment by rghvdberg** [comment]
Fixed! Thanks
Op 22 jul. 2015 19:29 schreef "Filipe Coelho" <notifications@github.com>:
