### ISSUE TITLE
replace 'lib' path by LIBDIR to allow install in /usr/lib64

### ISSUE THREAD

**Issue by ycollet** [falkTX/Carla#284]
Hello,

A variable LIBDIR is defined in the main makefile.
This variable should be used to perform installation of carla.
For example, this section of the main Makefiles:

install:
        # Create directories
        ...
        install -d $(DESTDIR)$(PREFIX)/lib/carla/
        install -d $(DESTDIR)$(PREFIX)/lib/carla/styles/
        install -d $(DESTDIR)$(PREFIX)/lib/pkgconfig/
        install -d $(DESTDIR)$(PREFIX)/lib/python3/dist-packages/
        ...

Should be replaced by:

install:
        # Create directories
        ...
        install -d $(DESTDIR)$(LIBDIR)/carla/
        install -d $(DESTDIR)$(LIBDIR)/carla/styles/
        install -d $(DESTDIR)$(LIBDIR)/pkgconfig/
        install -d $(DESTDIR)$(LIBDIR)/python3/dist-packages/
        ...

Best regards,

YC

**Comment by ycollet** [comment]
Here is a diff:

diff --git a/Makefile b/Makefile
index f033f98..893d367 100644
--- a/Makefile
+++ b/Makefile
@@ -402,10 +402,10 @@ stoat:
 install:
 	# Create directories
 	install -d $(DESTDIR)$(PREFIX)/bin/
-	install -d $(DESTDIR)$(PREFIX)/lib/carla/
-	install -d $(DESTDIR)$(PREFIX)/lib/carla/styles/
-	install -d $(DESTDIR)$(PREFIX)/lib/pkgconfig/
-	install -d $(DESTDIR)$(PREFIX)/lib/python3/dist-packages/
+	install -d $(DESTDIR)$(LIBDIR)/carla/
+	install -d $(DESTDIR)$(LIBDIR)/carla/styles/
+	install -d $(DESTDIR)$(LIBDIR)/pkgconfig/
+	install -d $(DESTDIR)$(LIBDIR)/python3/dist-packages/
 	install -d $(DESTDIR)$(PREFIX)/include/carla/
 	install -d $(DESTDIR)$(PREFIX)/include/carla/includes/
 	install -d $(DESTDIR)$(PREFIX)/include/carla/utils/
@@ -471,29 +471,29 @@ endif
 	install -m 644 data/carla.xml $(DESTDIR)$(PREFIX)/share/mime/packages/
 
 	# Install pkg-config files
-	install -m 644 data/*.pc $(DESTDIR)$(PREFIX)/lib/pkgconfig/
+	install -m 644 data/*.pc $(DESTDIR)$(LIBDIR)/pkgconfig/
 
 	# Install backend libs
 	install -m 644 \
 		bin/libcarla_*.* \
-		$(DESTDIR)$(PREFIX)/lib/carla/
+		$(DESTDIR)$(LIBDIR)/carla/
 
 	# Install other binaries
 	install -m 755 \
 		bin/*bridge-* \
 		bin/carla-discovery-* \
-		$(DESTDIR)$(PREFIX)/lib/carla/
+		$(DESTDIR)$(LIBDIR)/carla/
 
 	# Install the real modgui bridge
 	install -m 755 \
 		data/carla-bridge-lv2-modgui \
-		$(DESTDIR)$(PREFIX)/lib/carla/
+		$(DESTDIR)$(LIBDIR)/carla/
 
 ifeq ($(HAVE_QT),true)
 	# Install theme
 	install -m 644 \
 		bin/styles/* \
-		$(DESTDIR)$(PREFIX)/lib/carla/styles/
+		$(DESTDIR)$(LIBDIR)/carla/styles/
 endif
 
 	# Install python code
@@ -508,7 +508,7 @@ endif
 	install -m 644 \
 		source/carla_backend.py \
 		source/carla_utils.py \
-		$(DESTDIR)$(PREFIX)/lib/python3/dist-packages/
+		$(DESTDIR)$(LIBDIR)/python3/dist-packages/
 
 	# Install headers
 	install -m 644 \
@@ -630,34 +630,34 @@ endif
 		$(DESTDIR)$(PREFIX)/bin/carla-rack \
 		$(DESTDIR)$(PREFIX)/bin/carla-single \
 		$(DESTDIR)$(PREFIX)/bin/carla-settings \
-		$(DESTDIR)$(PREFIX)/lib/carla/carla-bridge-lv2-modgui \
-		$(DESTDIR)$(PREFIX)/lib/pkgconfig/carla-standalone.pc \
-		$(DESTDIR)$(PREFIX)/lib/pkgconfig/carla-utils.pc
+		$(DESTDIR)$(LIBDIR)/carla/carla-bridge-lv2-modgui \
+		$(DESTDIR)$(LIBDIR)/pkgconfig/carla-standalone.pc \
+		$(DESTDIR)$(LIBDIR)/pkgconfig/carla-utils.pc
 
 	# --------------------------------------------------------------------------------------------------------------------
 
 	# Install lv2 plugin
-	install -d $(DESTDIR)$(PREFIX)/lib/lv2/carla.lv2/
+	install -d $(DESTDIR)$(LIBDIR)/lv2/carla.lv2/
 
 	install -m 644 \
 		bin/carla.lv2/carla.* \
 		bin/carla.lv2/*.ttl \
-		$(DESTDIR)$(PREFIX)/lib/lv2/carla.lv2/
+		$(DESTDIR)$(LIBDIR)/lv2/carla.lv2/
 
 	# Link binaries for lv2 plugin
-	@for i in $(shell find $(DESTDIR)$(PREFIX)/lib/carla/ -maxdepth 1 -type f -exec basename {} ';'); do \
-		$(LINK) $(PREFIX)/lib/carla/$$i $(DESTDIR)$(PREFIX)/lib/lv2/carla.lv2/; \
-		$(LINK) $(PREFIX)/lib/carla/$$i $(DESTDIR)$(PREFIX)/lib/vst/carla.vst/; \
+	@for i in $(shell find $(DESTDIR)$(LIBDIR)/carla/ -maxdepth 1 -type f -exec basename {} ';'); do \
+		$(LINK) $(LIBDIR)/carla/$$i $(DESTDIR)$(LIBDIR)/lv2/carla.lv2/; \
+		$(LINK) $(LIBDIR)/carla/$$i $(DESTDIR)$(LIBDIR)/vst/carla.vst/; \
 	done
-	rm -f $(DESTDIR)$(PREFIX)/lib/lv2/carla.lv2/libcarla_standalone2.*
-	rm -f $(DESTDIR)$(PREFIX)/lib/vst/carla.vst/libcarla_standalone2.*
+	rm -f $(DESTDIR)$(LIBDIR)/lv2/carla.lv2/libcarla_standalone2.*
+	rm -f $(DESTDIR)$(LIBDIR)/vst/carla.vst/libcarla_standalone2.*
 
 	# Link styles for lv2 plugin
-	$(LINK) $(PREFIX)/lib/carla/styles $(DESTDIR)$(PREFIX)/lib/lv2/carla.lv2/
+	$(LINK) $(LIBDIR)/carla/styles $(DESTDIR)$(LIBDIR)/lv2/carla.lv2/
 
 	# Link resources for lv2 plugin
-	rm -rf $(DESTDIR)$(PREFIX)/lib/lv2/carla.lv2/resources
-	$(LINK) $(PREFIX)/share/carla/resources/ $(DESTDIR)$(PREFIX)/lib/lv2/carla.lv2/
+	rm -rf $(DESTDIR)$(LIBDIR)/lv2/carla.lv2/resources
+	$(LINK) $(PREFIX)/share/carla/resources/ $(DESTDIR)$(LIBDIR)/lv2/carla.lv2/
 
 	# --------------------------------------------------------------------------------------------------------------------
 
@@ -665,25 +665,25 @@ ifeq ($(LINUX),true)
 ifeq ($(HAVE_X11),true)
 ifeq ($(DEFAULT_QT),4)
 	# Install vst plugin
-	install -d $(DESTDIR)$(PREFIX)/lib/vst/carla.vst/
+	install -d $(DESTDIR)$(LIBDIR)/vst/carla.vst/
 
 	install -m 644 \
 		bin/CarlaRack*.* \
 		bin/CarlaPatchbay*.* \
-		$(DESTDIR)$(PREFIX)/lib/vst/carla.vst/
+		$(DESTDIR)$(LIBDIR)/vst/carla.vst/
 
 	# Link binaries for vst plugin
-	@for i in $(shell find $(DESTDIR)$(PREFIX)/lib/carla/ -maxdepth 1 -type f -exec basename {} ';'); do \
-		$(LINK) $(PREFIX)/lib/carla/$$i $(DESTDIR)$(PREFIX)/lib/vst/carla.vst/; \
+	@for i in $(shell find $(DESTDIR)$(LIBDIR)/carla/ -maxdepth 1 -type f -exec basename {} ';'); do \
+		$(LINK) $(LIBDIR)/carla/$$i $(DESTDIR)$(LIBDIR)/vst/carla.vst/; \
 	done
-	rm -f $(DESTDIR)$(PREFIX)/lib/vst/carla.vst/libcarla_standalone2.*
+	rm -f $(DESTDIR)$(LIBDIR)/vst/carla.vst/libcarla_standalone2.*
 
 	# Link styles for vst plugin
-	$(LINK) $(PREFIX)/lib/carla/styles $(DESTDIR)$(PREFIX)/lib/vst/carla.vst/
+	$(LINK) $(LIBDIR)/carla/styles $(DESTDIR)$(LIBDIR)/vst/carla.vst/
 
 	# Link resources for vst plugin
-	rm -rf $(DESTDIR)$(PREFIX)/lib/vst/carla.vst/resources
-	$(LINK) $(PREFIX)/share/carla/resources/ $(DESTDIR)$(PREFIX)/lib/vst/carla.vst/
+	rm -rf $(DESTDIR)$(LIBDIR)/vst/carla.vst/resources
+	$(LINK) $(PREFIX)/share/carla/resources/ $(DESTDIR)$(LIBDIR)/vst/carla.vst/
 endif
 endif
 endif
@@ -692,7 +692,7 @@ endif
 
 uninstall:
 	rm -f $(DESTDIR)$(PREFIX)/bin/carla*
-	rm -f $(DESTDIR)$(PREFIX)/lib/pkgconfig/carla-standalone.pc
+	rm -f $(DESTDIR)$(LIBDIR)/pkgconfig/carla-standalone.pc
 	rm -f $(DESTDIR)$(PREFIX)/share/applications/carla.desktop
 	rm -f $(DESTDIR)$(PREFIX)/share/applications/carla-control.desktop
 	rm -f $(DESTDIR)$(PREFIX)/share/icons/hicolor/*/apps/carla.png
@@ -701,10 +701,10 @@ uninstall:
 	rm -f $(DESTDIR)$(PREFIX)/share/icons/hicolor/scalable/apps/carla-control.svg
 	rm -f $(DESTDIR)$(PREFIX)/share/mime/packages/carla.xml
 	rm -rf $(DESTDIR)$(PREFIX)/include/carla/
-	rm -rf $(DESTDIR)$(PREFIX)/lib/carla/
-	rm -rf $(DESTDIR)$(PREFIX)/lib/lv2/carla.lv2/
-	rm -rf $(DESTDIR)$(PREFIX)/lib/lv2/carla-native.lv2/
-	rm -rf $(DESTDIR)$(PREFIX)/lib/vst/carla.vst/
+	rm -rf $(DESTDIR)$(LIBDIR)/carla/
+	rm -rf $(DESTDIR)$(LIBDIR)/lv2/carla.lv2/
+	rm -rf $(DESTDIR)$(LIBDIR)/lv2/carla-native.lv2/
+	rm -rf $(DESTDIR)$(LIBDIR)/vst/carla.vst/
 	rm -rf $(DESTDIR)$(PREFIX)/share/carla/
 
 # ----------------------------------------------------------------------------------------------------------------------------

**Comment by falkTX** [comment]
Have you actually ran carla after doing those changes?

I know there's some places in the code that will need change too.

**Comment by ycollet** [comment]
I was just trying to build a spec file for fedora for both Carla and 
Cadence.
The spec file for Cadence works fine, the one for Carla needed then 
changes for the lib64 directory.
I see that you modified some pieces of python code. I will relaunch the 
packaging and tries it ASAP.

Thanks for the changes.

**Comment by ycollet** [comment]
Carla works fine when using a lib64 directory. But I  noticed that the pkg-config files need to be modified too: there a remaining ${exec_prefix}/lib instead of ${exec_prefix}/lib64.

**Comment by ycollet** [comment]
Here is a diff of the last changes:

```
diff --git a/Makefile b/Makefile
index 2c157ae..99b50f9 100644
--- a/Makefile
+++ b/Makefile
@@ -646,7 +646,11 @@ endif
 
 	# Adjust LIBDIR and DATADIR value in code
 	sed -i 's?X_LIBDIR_X = None?X_LIBDIR_X = "$(LIBDIR)"?' \
-		$(DESTDIR)$(DATADIR)/carla/carla_shared.py
+		$(DESTDIR)$(DATADIR)/carla/carla_shared.py 
+	
+	sed -i 's?X-LIBDIR-X?$(LIBDIR)?' \
+		$(DESTDIR)$(LIBDIR)/pkgconfig/carla-standalone.pc \
+		$(DESTDIR)$(LIBDIR)/pkgconfig/carla-utils.pc
 
 	sed -i 's?X_DATADIR_X = None?X_DATADIR_X = "$(DATADIR)"?' \
 		$(DESTDIR)$(DATADIR)/carla/carla_shared.py
diff --git a/data/carla-standalone.pc b/data/carla-standalone.pc
index 6e1ae60..94e3cd6 100644
--- a/data/carla-standalone.pc
+++ b/data/carla-standalone.pc
@@ -1,6 +1,6 @@
 prefix=X-PREFIX-X
 exec_prefix=${prefix}
-libdir=${exec_prefix}/lib/carla
+libdir=X-LIBDIR-X
 includedir=${prefix}/include/carla
 
 Name: carla-standalone
diff --git a/data/carla-utils.pc b/data/carla-utils.pc
index 0519803..2eea39a 100644
--- a/data/carla-utils.pc
+++ b/data/carla-utils.pc
@@ -1,6 +1,6 @@
 prefix=X-PREFIX-X
 exec_prefix=${prefix}
-libdir=${exec_prefix}/lib/carla
+libdir=X-LIBDIR-X
 includedir=${prefix}/include/carla
 
 Name: carla-utils
```

**Comment by falkTX** [comment]
I was already doing the needed changes for this, but thanks anyway. fix for that coming

**Comment by ycollet** [comment]
Thanks a lot, I am recompiling lmms-1.1.3 using carla and I will see if everything is fine.

Best regards,

YC
