### ISSUE TITLE
following the changes due to LIBDIR, carla still has 'lib' part

### ISSUE THREAD

**Issue by ycollet** [falkTX/Carla#289]
I set LIBDIR to $PREFIX/lib64
Carla compiles fine.
When I started carla, I noticed that in the bin directory, some files have still some 'lib' path instead of 'lib64'. 
All the files in the bin directory have these path.

When I start carla-rack using lmms-1.1.3, I've got the following message too and carla-rack doesn't start:

Carla assertion failure: "cPlugin != nullptr" in file ../../utils/CarlaLv2Utils.hpp, line 470
Failed to load a plugin, error was:
Failed to find the requested plugin
Carla assertion failure: "cPlugin != nullptr" in file ../../utils/CarlaLv2Utils.hpp, line 470
Failed to load a plugin, error was:
Failed to find the requested plugin
fluidsynth: warning: No preset found on channel 9 [bank=128 prog=0]
Trying to start carla-plugin using "/local/stow/carla-devel/lib64/carla/libcarla_standalone2.so/share/carla/resources//carla-plugin"
exec failed: N'est pas un dossier
waitForClientFirstMessage() - read returned 0

Best regards,

YC

**Comment by Baggypants** [comment]
There is a bunch of places that it needs to be changed. I'm trying to package for Fedora which uses lib64, so far I've needed to change all the references to $(PREFIX)/lib/ in the Makefile and the hard coded line in carla_shared.py:        pathBinaries  = os.path.join(libPrefix, "lib", "carla")

**Comment by falkTX** [comment]
I didn't code carla thinking of using lib64 at all, so this one might be tricky to handle.

**Comment by Baggypants** [comment]
I've written a kludgy patch which gets Carla running for me. https://gitlab.com/spec-files-for-various-rpms/spec-files-for-various-rpms/blob/master/carla/Carla-libdir.patch

**Comment by falkTX** [comment]
@Baggypants 
It seems like you're using an old version.
I already fixed some of those issues.
See https://github.com/falkTX/Carla/blob/master/source/carla_shared.py#L619

I forgot about the plugins paths, like /usr/lib64/lv2.

**Comment by Baggypants** [comment]
Good to know, I was using the tagged version 1.9.6.

**Comment by Baggypants** [comment]
OK. so I did a rebuild from git commit 12db7be2 and it builds and loads without any patching required and I can add lv2 plugins to a rack.

**Comment by falkTX** [comment]
I'd like to have confirmation if more work is still needed or not.
I don't run a distro that uses lib64, so someone else needs to check.
ie, Grab latest git and build it the same way again, see if the vars gets respected during install.
Thanks.

**Comment by falkTX** [comment]
There has not been any comments on this issue for 2 years, so I assume it is fixed now.
If it is not the case, please reopen.
