### ISSUE TITLE
Carla hangs when renaming a plugin instance

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#293]
I'm using carla-git package from KX Studio repos.

Carla hangs every time I try to rename a plugin. I open the rename dialog, type in a new name press enter, the dialog disappears and Carla stops responding. I wasn't able to get any extra commandline output to supply for this.

**Comment by falkTX** [comment]
What engine mode are you using?
and which driver? (I would guess JACK?)

**Comment by falkTX** [comment]
Hello? Need some more info here..
Renaming plugins involves different things depending on which driver and engine mode you have selected.
It might rename the jack ports, recreate the client or simply update some internal data.
So knowing which mode causes the freeze would be nice.
Also, please confirm if this is still an issue or not. Perhaps it's already been fixed.

**Comment by falkTX** [comment]
Looking at the bugs now I see you reported this twice..
Closing this one, continue conversation at #337.
