### ISSUE TITLE
zynaddsubfx ui bugs

### ISSUE THREAD

**Issue by Fak3** [falkTX/Carla#295]
I use current git-master (876cf812785e138c8c33a2e1810dd289d87f30bf)
After i updated to git-master, zynaddsubfx plugin UI shows wrong data\state in some places. This goes away after some actions, see below.
How to reproduce:
[1] Add zynaddsubfx plugin to Carla or Ardour, open its user interface, click "edit instrument". In the opened dialog you will see that "ADsynth" is disabled, but it is really enabled and produce simple sine wave, by default (you can hear that). 
[2] More - click "Edit" under Adsynth, then click "Show voice parameters" and you will see that oscillator wave displayed is flat, but really it is sine. Although if you click "change" to open oscillator config dialog - displayed graph will get changed to sine.

I described 2 visible issues, but i think those are related.

**Comment by falkTX** [comment]
@fundamental: that commit has the last git of zyn.
Do you know of these issues?

**Comment by Fak3** [comment]
I just checked latest git version of standalone zynaddsubfx - and it does not have this issue

**Comment by falkTX** [comment]
standalone zyn is a different kind of build.
if you want to test the same scenario with official zyn you'll have to start it headless first and then the UI separately.
Like this:
```
zynaddsubfx --no-gui
```

```
zynaddsubfx-ext-gui
```

**Comment by Fak3** [comment]
Hm... starting this way, UI is completely detached from the synthesizer, and does not control anything. Should i provide some sort of connection path in arguments?

**Comment by fundamental** [comment]
I don't think that the standalone has had these bugs. To me it sounds like the UI is just not receiving anything back from the RT/middleware side of things as being unchecked and a flat graph would be the widget's default state.

**Comment by Fak3** [comment]
I downgraded standalone zynaddsubfx from current git to 2.5.1, but still have the same behavior launching zynaddsubfx-ext-gui separetely - it lives its own life... I suppose this related to osc? What can i do to make it work?

**Comment by fundamental** [comment]
to connect 'zynaddsubfx-ext-gui' you've got to use liblo's syntax which should be something like zynaddsubfx-ext-gui osc.udp://localhost:1234 which would correspond to port 1234 (which in the standalone can be specified with the -P option)

**Comment by Fak3** [comment]
Oh, thak you. Now i launched zynaddsubfx-ext-gui successfully, and don't see this bug.

**Comment by Fak3** [comment]
I tested current git-master version, and i can't reproduce this bug anymore.
