### ISSUE TITLE
Hexter not availlable in DSSI plugin list

### ISSUE THREAD

**Issue by Barbouze** [falkTX/Carla#296]
Hello,

Using Carla-git, I installed Hexter from KXstudio repositories. I can use it in Qtractor but it is not shown in Carla's DSSI plugins list.

**Comment by falkTX** [comment]
Hexter uses DSSI's run_multiple_synths without supporting run_synth.
I had some hacks in place for handling this before, but they never worked properly so I removed them.

So in short, Hexter uses a feature that Carla cannot provide.
(nor can a multi-plugin host that runs multiple plugin processing at the same time).
This is why Hexter doesn't also work in Renoise.

I'm sad to say this is "won't fix".
Please give 'dexed' a try, it's a DX7 synth like Hexter.
