### ISSUE TITLE
C* eq10, eq10x2 and eq4p - LV2 versions

### ISSUE THREAD

**Issue by Barbouze** [falkTX/Carla#297]
Hello,
I didn't find any way to post this issue in the caps-lv2 section but anyhow it is somewhat related to Carla-git.
C* eq10 and eq10x2: you can see that even if they correctly process the source they output nothing and as soon as their output is connected to the soundcard, an audible pop is heard and then the only way to get a sound is by disconnecting their output.
C* eq4p crashes Carla as soon as its output is added to the rack.
The LADSPA versions are working fine.

**Comment by Barbouze** [comment]
Found the same bugs with other members of the C* family, should I post a list here or do you want me to give it to you in another way?

**Comment by Barbouze** [comment]
Well, ran trough all of them and here are the following results:
The following plugins crashes Carla as soon as they are added:
Compress, Compressx2, Noisegate, Saturate, Spice

The following plugins outputs something that kills the audio card when their output is connected:
Cabinet IV, ChorusI, Plate, Platex2, Scape, Tonestack, Wider

Narrower outputs a weird sound at full volume all the time
Autofilter seems to be broken too, it outputs something that is far from what the LADSPA version does.

**Comment by falkTX** [comment]
the caps-lv2 plugins seem to be broken for the most part.
not sure how, I think they worked before.
this is something that I'll fix on caps-lv2 later on, they are needed for MOD anyway.

not a carla issue though, but I'll keep this open until the real bug is fixed.

**Comment by Barbouze** [comment]
Thanks! :)

**Comment by Barbouze** [comment]
Hi!
With the recent update of caps-lv2, all those issues have been fixed, thanks a lot for your awesome work! :)

**Comment by falkTX** [comment]
yes, I did an overall check of all the plugins and they should work fine now.
even valgrind agrees, which is good. :)
