### ISSUE TITLE
Crash with u-he plugins

### ISSUE THREAD

**Issue by Barbouze** [falkTX/Carla#302]
Hello,

I wanted to try u-he plugins that are currently in public beta (see forum thread here: http://www.kvraudio.com/forum/viewtopic.php?f=31&t=424953).
They are loading properly in Ardour 4 but make carla-git instantly crash as soon as they are added.

Regards,
Barbouze

**Comment by falkTX** [comment]
strange, I had them working not so long ago.
are you using the latest version of those plugins?
If not please update and try again.

**Comment by Barbouze** [comment]
I'm using the one provided in the first post (v 3531, 14/06/2015) and it seems to be the latest
I didn't test all the plugins, only the one I could be interested in, Diva and Zebra. Do you want me to test all the plugins? Is there a log file for Carla that I could look at or link here?

**Comment by falkTX** [comment]
I can confirm the issue, I'll investigate.

**Comment by falkTX** [comment]
hmm this seems to be an issue with u-he plugins.
it's throwing an exception on VSTPluginMain().

because the plugins are not opensource and the builds are stripped it's not possible for me to know what's going on.

**Comment by falkTX** [comment]
plus, I know the plugins were working before (with the same code).
so something changed recently in the u-he code that broke compatibility with carla.
try to use some older version in the mean time.

**Comment by falkTX** [comment]
using carla-single seems to be able to load the plugins, like this:
```carla-single vst ~/.vst/u-he/ACE.64.so```
no idea what's going on.

**Comment by Barbouze** [comment]
Diva is fine with carla-single but Zebra2 is not, I'll try to find older versions or wait for updates :) . I'm just curious but how different are Carla and Ardour VST support? Is one more strict on VSTs specs?

**Comment by falkTX** [comment]
It's not about the vst spec here I think.
I think it's something about exception handling, optimizations, symbol clashing or some other weird error.

**Comment by falkTX** [comment]
hmm, if you enable the "run plugins as bridge" option u-he plugins will load.
I don't recommend turning that on though, as it will be for all plugins.
I need to make that option usable per-plugin...

**Comment by Barbouze** [comment]
Yay! Should I report this problem to u-he support?
Thanks for the support by the way :)

**Comment by falkTX** [comment]
Sure, it's probably their problem anyway :P
It's definitely a recent change (I'd say no older than 2-3 weeks)

**Comment by varpa** [comment]
Crash still occurs on recent u-he update  3940 using kxstudio 14.04, up-to-date.  If you run from the command iine there is a message "Aborted" when he crash occurs.   U-he plugins work in Ardour.

**Comment by lentferj** [comment]
Could you put "ZebraHZ" on that list, too? It is a customized version of Zebra2 that comes with the "The Dark Zebra" patch library. Zebra2 works for me, mut ZebraHZ crashes carla immediatley (as described above).
One more point: It works in carla-rack within ardour. But CPU usage triples (going from around 20% when idle to around 60% when idle). Is that a known thing or should I try to investigate more?

**Comment by falkTX** [comment]
is ZebraHZ a public download?

**Comment by lentferj** [comment]
No, it only comes with the "Dark Zebra" addon (https://www.u-he.com/cms/118-tdz-news).

**Comment by falkTX** [comment]
ok then please post the carla-discovery output for that plugin.

run it like this:
```
/usr/lib/carla/carla-discovery-native vst /path/to/zebrahz.so
```

**Comment by lentferj** [comment]
There are 3 .so files: ZebraHZ.32.so, ZebraHZ.64.avx.so, ZebraHZ.64.so. Only the 64-bit ones produce output with carla-discovery. I put it here: http://pastie.org/10717758

**Comment by falkTX** [comment]
Done in a248ce0d454d193afe753837bbd4ba684e021b09
Let me know if that works.

**Comment by lentferj** [comment]
Will you push that version to the kxstudio repositories soon?

**Comment by falkTX** [comment]
Sure, I'll do that now.

**Comment by lentferj** [comment]
Works now. Thx for the quick fix!
