### ISSUE TITLE
Fail to start with PyQt5-5.5 || PyQt5-5.4.2 works

### ISSUE THREAD

**Issue by mekosmowski** [falkTX/Carla#303]
The below runtime failure was resolved by downgrading PyQt5 from 5.5 to 5.4.2.

According to <The-Compiler> at #pyqt on freenode, the problem is due to "a change in PyQt 5.5 which doesn't allow to use Python string as byte strings anymore."  Full details may be found at: http://pyqt.sourceforge.net/Docs/PyQt5/incompatibilities.html#pyqt-v5-5

The runtime error:
```
$ cat carla_runtime_error
mark@gentoodesktop ~/portage $ carla
Using "carla" theme
Carla 1.9.6 (2.0-beta4) started, status:
  Python version: 3.4.1
  Qt version:     5.4.2
  PyQt version:   5.5
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 52, in <module>
    gui = HostWindow(host, True)
  File "/usr/share/carla/carla_host.py", line 323, in __init__
    self.loadSettings(True)
  File "/usr/share/carla/carla_host.py", line 1238, in loadSettings
    self.restoreGeometry(settings.value("Geometry", ""))
TypeError: QWidget.restoreGeometry(QByteArray): argument 1 has unexpected type 'str'
```

**Comment by The-Compiler** [comment]
The issue here is that the geometry is stored as a `str` in `QSettings`, but `QWidget.restoreGeometry` expects a `QByteArray` - in earlier PyQt versions, `str` objects got implicitely encoded as `latin1` in such a case, but that was error-prone, so it got deprecated with 5.4 and removed with 5.5.

Something like `self.restoreGeometry(settings.value("Geometry", "").encode("ascii"))` should probably work - but there might be more places where this issue is present.

**Comment by falkTX** [comment]
thanks for the heads up.
btw what is your distro? I didn't even knew qt 5.5 was out already...

**Comment by mekosmowski** [comment]
Gentoo.

**Comment by almereyda** [comment]
Same error here on Fedora 22.

**Comment by falkTX** [comment]
What do you mean playing with non?
Carla already supports NSM.

**Comment by almereyda** [comment]
Yes yes, NSM is working, but compiling Carla didn't work. But I needed only Catia, which I now built from Cadence. That's working so I don't bother the issue here anymore.

Yes, JACK audio routing also works without interfaces like Catia or patchage, but it's so much nicer with them! :smile:
