### ISSUE TITLE
LV2 plugins not loaded...

### ISSUE THREAD

**Issue by rcspam** [falkTX/Carla#304]
After install some new plugins (infamous, rkrlv2,...), they don't appear (in carla-git), carla can see "729 LV2" plugins (as it's in the bottom carla bar of add new window) but only about 100 are displayed...
Regards

**Comment by falkTX** [comment]
Did you set some custom filters for the plugins?
Does the search bar contains any letters?

**Comment by rcspam** [comment]
I had mv  ~/.config/Cadence/Carla.conf, so it's ok now.
Perhaps an old conf ...
Thanks
