### ISSUE TITLE
Saving Patch Connections

### ISSUE THREAD

**Issue by sonejostudios** [falkTX/Carla#306]
I'm using Carla in Multi-Track Mode. Until now Carla seems to save and restore all connections in the carla project file. If a software is missing (i.e crashing) the connections disappears, thats fine. 
Now I DON'T save the carla project file and restart everything. So I'm starting the original carla project file with the connection, but although the software is not missing anymore carla doesn't restore the connections (although it should do it because I'm starting the original carla project file with all connections).
To me it seems Carla is saving the connections in real-time to the project file, not on "saving" ich via the menu, right? Should it be like that? Or is there a workaround to keep the connections if everything is fine? Or maybe even to restore them on the fly as soon as the ports of a program are visible/registered in jack?

**Comment by falkTX** [comment]
if you didn't tell carla to save, it won't save.
the only exceptions is when carla is running as a plugin (host is the to save) or under session-management (SM triggers the save).

this seems like the app that crashed/missing started itself with a different name, and thus carla can't find it.

**Comment by sonejostudios** [comment]
I'm using carla as standalone.
Hmm it as the same name, but maby another id or something like that?
Anyway if you say that's a normal behavior, its fine, probably this is a bug with the other software (currently in heavy development)
thanks falkTX!

**Comment by falkTX** [comment]
not sure what exactly this bug is about...
carla does save & restore jack connections together with the project, provided the client names remain the same.
client names are the only way to identify jack clients in the patchbay right now, so not much we can do when they randomly change.
