### ISSUE TITLE
GUI bridge binaries symlinks to LV2 plugin are not created on clean build

### ISSUE THREAD

**Issue by jypma** [falkTX/Carla#309]
I'm running Carla from git master on arch linux, built using [carla-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=carla-git). Carla shows plugin GUIs fine when running standalone.

However, when adding any carla variant as LV2 or VST plugin to Ardour, that Carla instance isn't able to show any plugin GUIs (testing with qMidiArp, which has a qt4 GUI). The wrench icon does not show, and stderr says `Failed to find UI bridge binary, cannot use UI`. This happens for all GUI types.

I added a bit of debug logging, and it seems that 
```
pData->engine->getOptions().binaryDir
``` 
returns `/usr/lib/lv2/carla.lv2` when running as LV2, but returns `/usr/lib/carla` when running standalone.

The plugin bridge binaries only exist in `/usr/lib/carla`, hence they are not found when running as LV2 or VST.

For the moment, I can symlink my way into making this work, but I wonder where the real cause lies.

**Comment by falkTX** [comment]
There should be some symlinks in /usr/lib/lv2/carla.lv2.
Here's what I have in my system:
```
lrwxrwxrwx   1 root root       33 Set 22 14:50 carla-bridge-lv2-gtk2 -> ../../carla/carla-bridge-lv2-gtk2
lrwxrwxrwx   1 root root       33 Set 22 14:50 carla-bridge-lv2-gtk3 -> ../../carla/carla-bridge-lv2-gtk3
lrwxrwxrwx   1 root root       38 Abr  5  2015 carla-bridge-lv2-modgui -> /usr/lib/carla/carla-bridge-lv2-modgui
lrwxrwxrwx   1 root root       32 Set 22 14:50 carla-bridge-lv2-qt4 -> ../../carla/carla-bridge-lv2-qt4
lrwxrwxrwx   1 root root       32 Set 22 14:50 carla-bridge-lv2-qt5 -> ../../carla/carla-bridge-lv2-qt5
lrwxrwxrwx   1 root root       32 Set 22 14:50 carla-bridge-lv2-x11 -> ../../carla/carla-bridge-lv2-x11
lrwxrwxrwx   1 root root       31 Set 22 14:50 carla-bridge-native -> ../../carla/carla-bridge-native
lrwxrwxrwx   1 root root       32 Set 22 14:52 carla-bridge-posix32 -> ../../carla/carla-bridge-posix32
lrwxrwxrwx   1 root root       34 Jul 22 09:39 carla-bridge-win32.exe -> ../../carla/carla-bridge-win32.exe
lrwxrwxrwx   1 root root       34 Jul 22 09:39 carla-bridge-win64.exe -> ../../carla/carla-bridge-win64.exe
lrwxrwxrwx   1 root root       34 Set 22 14:50 carla-discovery-native -> ../../carla/carla-discovery-native
lrwxrwxrwx   1 root root       35 Set 22 14:52 carla-discovery-posix32 -> ../../carla/carla-discovery-posix32
lrwxrwxrwx   1 root root       37 Jul 22 09:39 carla-discovery-win32.exe -> ../../carla/carla-discovery-win32.exe
lrwxrwxrwx   1 root root       37 Jul 22 09:39 carla-discovery-win64.exe -> ../../carla/carla-discovery-win64.exe
```

Don't you have those?

**Comment by jypma** [comment]
Nope, not there. I actually edited the `PKGBUILD` to create symlinks just like that. Arch's PKGBUILD just does a `make install` during packaging; where in the makefile should those symlinks normally be created?

**Comment by falkTX** [comment]
See starting from line 673
https://github.com/falkTX/Carla/blob/master/Makefile#L673

**Comment by jypma** [comment]
The existing `find` that scans for binaries doen't return anything. It seems my `make` or `bash` might be interpreting the `$(...)` too soon, differently, or not at all. If I change line 679 to
```
for i in `find $(DESTDIR)$(LIBDIR)/carla/ -maxdepth 1 -type f -exec basename {} ';'` ; do \
```
(i.e. replacing `$(...)` with `` `...` ``), the files are found. Any idea what might be causing that?

I'm running bash 4.3.42(1) and GNU Make 4.1.

**Comment by falkTX** [comment]
It could be that the command is being executed before that line is reached.
I guess I'll need to change it to "`".

**Comment by jypma** [comment]
Ah yes, that would make sense. If you meant to use bash's `$(` syntax, you might have needed to write `$$(` to prevent make from escaping it.
