### ISSUE TITLE
Carla running as LV2 plugin distorts audio (buffer size miscalculation?)

### ISSUE THREAD

**Issue by jypma** [falkTX/Carla#310]
I am running Carla inside Ardour. Carla is built from git master, running on arch linux.

When I run Carla as VST plugin, sound is fine. I can load both internal and LV2 plugins into Carla's VST instance, at low latencies, with no distortions.

When I run Carla as LV2 plugin, the sound distorts. I'm loading Carla's internal ZynAddSubFX into the Carla LV2 instance. At low latency (2x128 jack buffer size), the sound is completely distorted. 

I increased the jack buffer size to 2x1024, and I started to notice individual pops/silences between what I think is each buffer (consistently). The same distortion does not occur when, in the same Ardour session, using LV2 plugins plugged directly into Ardour. So the distortions are on Carla's track only.

No buffer underrun messages or other errors are printed to the console or JACK. `qjackctl`'s XRUN counter is at zero.

**Comment by falkTX** [comment]
I know about this issue.
It has been fixed in ardour after the 4.2 release.
You can either wait for ardour4.3 (should be out soon) or use the latest git version.

**Comment by jypma** [comment]
Confirmed fixed in ardour 4.3
