### ISSUE TITLE
Carla won't properly scan the ~/.wine directory.

### ISSUE THREAD

**Issue by lucmp** [falkTX/Carla#316]
Carla scans all directories specified in the configuration section that are supposed to contain plugins, and adds detected plugins to a catalogue or database, so to speak.

For some reason, Carla will scan the ~/.wine directory, but will not add plugins found there to the catalogue.

I ran a quick experiment: I was suspicious of the home and/or hidden directories, so I created the ~/plugins directory, copied a bunch of Windows plugin DLLs into it, and had Carla scan it (Refresh). All the plugins were listed on the catalogue. Then I renamed that directory to ~/.plugins (notice the dot), updated the configuration and rescanned. Again, all the plugins were listed. It's the ~/.wine directory that Carla doesn't like specifically.

I only tested Windows VST plugins, not any other format.

**Comment by falkTX** [comment]
I just tested this and can't reproduce.

These are my paths:
![scr556](https://cloud.githubusercontent.com/assets/1334853/10933576/c32118b0-82d9-11e5-8c1b-0c4bafe47ca6.png)

After a refresh (and showing wine plugins) they are listed correctly:
![scr557](https://cloud.githubusercontent.com/assets/1334853/10933584/d872266e-82d9-11e5-862d-3373e5593658.png)

**Comment by lucmp** [comment]
I just got back from one week's vacation, saw many updates on Synaptic but didn't install any. Then I saw this notification, tested Carla again and it worked! All my plugins in ~/.wine are found and usable.

I have no explanation for this. Maybe the much needed vacation fixed my brain and I did it right this time. Sorry about this embarrassment.
