### ISSUE TITLE
ZynAddSubFX Internal/LV2: boken part's MIDI key range learning

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#317]
Hey!

I'm using latest Git version of Carla, and I found out that the Part's MIDI range interface is broken.
This happens both in Carla's Internal plugina s weel as withing Ardour 4, when using LV2 plugin.

![part midi range](https://cloud.githubusercontent.com/assets/491704/10710797/0ece8f0a-7a69-11e5-96e5-91672772465a.png)

All works well when working on Part 1, but when I selected Part 2, 3 etc the "learn" function (min/max buttons) didn't do anything when I press them (the Part's 2 MIDI key range didn't change) instead - they always modify the Part 1's MIDI key range.

Looks like the Min/Max button's don't realise which part is selected right now.

Anybody can confirm this?

**Comment by fundamental** [comment]
The bug is confirmed to exist in the git version of the standalone

**Comment by fundamental** [comment]
The bug is confirmed to be fixed by https://github.com/fundamental/zynaddsubfx/commit/6d554221f91f17073063248255cf82758210b60c

**Comment by falkTX** [comment]
Thanks!

**Comment by unfa** [comment]
Thanks!

**Comment by unfa** [comment]
Yup. It's fixed, awesome! I can now make killer live setups :D
