### ISSUE TITLE
ZynAddSubFX Internal/LV2: FX are reset on loading

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#318]
I'm using latest Carla-git package.

I don't know if this is a problem with saving presets or loading them, but when I save a Carla or Arodur session with ZynAddSubFX used in it, after loading this again all Zyn's internal FX parameters are set to 0, effectively destroying the patch.

![fx reset](https://cloud.githubusercontent.com/assets/491704/10710856/51308230-7a6a-11e5-942d-31b898dbe2a3.png)

Anybody can confirm this?

**Comment by falkTX** [comment]
is the ui simply not updated, or do you notice the effects (in the sound) are also not restored?

**Comment by fundamental** [comment]
@falkTX when was this particular -git package synced up?
This was a bug which was introduced and then fixed (to my knowledge) in the past two months.

**Comment by falkTX** [comment]
the current plugin version (carla+zyn) has the latest version from 2 days ago.

**Comment by fundamental** [comment]
Hm, I can't replicate this bug in the git version of the standalone and checking zynaddsubfx-synth.cpp::setState() in carla's code it looks like everything should be loaded correctly.

**Comment by falkTX** [comment]
I've updated zyn recently, is this still an issue?

**Comment by unfa** [comment]
falkTX: the sound was affected too, it's wouldn't be such an issue if it sounded right, even if it'd look off. I wanted to prepare live set for performing with a band, and that's making internal Zyn effects useless for that purpose (which I use a lot).

I'm now installing Carla-Git again replacing Carla (stable) package and I'll see if the problems still exists.

**Comment by falkTX** [comment]
I do not do any updates to the old stable carla.
I though this issue was with the current git all along...

**Comment by unfa** [comment]
The issue is still present. To reproduce:

1. Open Carla
2. Add ZynAddSubFX
3. Add an efect (any will do)
4. Save Carla patch
5. Close Carla
6. Open Carla again
7. Load the patch saved previously
8. Open Zyn interface and find the effect
9. All controls should be at 0

**Comment by fundamental** [comment]
Interesting. I guess I should sit down and get Carla git installed on my system as what seems to be happening is:

1. A knob is set to some non-zero value
2. A message is sent to update the synthesis parameter
3. A message is translated into a response which has forced the value to zero
4. The knob receives a response that doesn't match it's current value
5. The knob updates to the new value which happens to be zero

So, the three likely spots where I'd imagine things could go wrong would be:
1. transmitting the message with a wrong value at [2-3]
2. an invalid bit of dispatch happens at [3]
3. some misinterpretation of a message happens at [4]

**Comment by fundamental** [comment]
The bug is confirmed to occur on my system

**Comment by unfa** [comment]
So maybe this problem is unrelated to having wrong values stored or restored from files, but the fact that after loading a patch ZynAddSubFX gets stuck in an undesired state.

**Comment by fundamental** [comment]
Right now it's looking like an issue in the loading process, but I'm still debugging this one

**Comment by unfa** [comment]
Thanks, let me know if I can help you in any way.

**Comment by fundamental** [comment]
@unfa please verify that https://github.com/falkTX/Carla/pull/322 solves the issue.

**Comment by unfa** [comment]
Looks like it's fixed now! I'm so happy! Thank you!
