### ISSUE TITLE
Fabla plugin has no GUI

### ISSUE THREAD

**Issue by lucmp** [falkTX/Carla#319]
The Fabla plugin loads on Carla, but has no GUI, just a blank screen.

The problem does not occur when the plugin is loaded by jalv.

**Comment by falkTX** [comment]
which carla version do you have?
the 1.2.x series or the 1.9.x beta?

**Comment by lucmp** [comment]
Carla version 1.9.6 (2.0-beta4)
Python version: 3.4.2
Qt version:     4.8.6
PyQt version:   4.11.2

**Comment by SpotlightKid** [comment]
I can't reproduce this. Fabla show fine here. I have Qt 4.8.7 and PyQt 4.11.4 and Fabla compiled from Git (gcfbd4b3).

**Comment by lucmp** [comment]
I have fabla 1:1.3+git20140320-1kxstudio1

**Comment by falkTX** [comment]
This should no longer be an issue if you use the latest git of carla or fabla.
