### ISSUE TITLE
Increase timeout when loading bridged plug-in

### ISSUE THREAD

**Issue by milasudril** [falkTX/Carla#320]
I try to load KeroVee through the VST2-win32 bridge, and it works great, when it actually loads. The problem is that I need some retrys before it works. It claims it is a possible timeout. It would be nice if the timeout was configurable rather than using clever guesses. I would suggest one minute for loading a bridged VST2-win32.

**Comment by falkTX** [comment]
Does it actually fail to load? Or just de-activates automatically after being loaded?

Currently there's a timeout of 5secs for linux bridges, 10s for wine.
The value is doubled when it's the first time you load a bridge plugin.
I guess I can make the initial value configurable.

**Comment by milasudril** [comment]
I guess the load is not complete. Retrying some times and it works, so maybe some random workload. Also, without wineserver running in SCHED_FIFO, there is no problems (except a lot of xruns in a lowlatency env).

**Comment by milasudril** [comment]
I copied the pre-compiled bridge to the Carla/bin directory, and increasing the timeout worked. Some loading times:

 * First time: 1 min
 * Second time (after removing the plug): 42 sec
 * First time after using firefox for a while (no plug removal): 30 sec

Booting wine takes some time and is I/O limited. Also, remember that wine updates its configuration after upgrade. So I would set the timeout to 2 min always

**Comment by falkTX** [comment]
I disagree with the 2min.
If you have a SSD wine updates take only a few seconds.

Anyway, increasing the timeout is not something I'm comfortable with.
Although carla still works while waiting for the bridge, any operation is disabled (like adding or removing plugins).

A configuration option seems the best option.

**Comment by milasudril** [comment]
> A configuration option seems the best option.

Definitely, this quantity is hard to predict at compile time  (loading was much faster without SCHED_FIFO, for example, and if wine is running configuration update, its load time may be 3 times longer than normal). It looks like the timeout only is an error check, and if there is a response before the timeout the loop stops. So setting a higher value is only harmful for bad plug-ins. Then, why not deliver the package with a test plug-in to measure against?

**Comment by falkTX** [comment]
tbh in both my systems this has never been a problem.
20s for the initial load has been enough for my old laptop, and my new desktop pc (i7, ssd) it only needs 2-3s for the first wine plugin to load.

anyway, configuration option is coming soon.

**Comment by milasudril** [comment]
I think it can be a Linux disk cache issue. The above benchmark was on an an old Pentium M laptop (it does not run the GUI well but the DSP thread is working without XRUNs) with 500 MB RAM. On my newer Ivy box with 8 GB RAM, it also took some time to load a VST failing on first try due to time out then succeeding on the second. After removing KDE and switching to Xfce, the problem disappeared and it only take one second to load it. If you add configuration option and plan to use a different timeout on first load, then both should be configurable individually since the difference between the first and second load may vary depending on the system.
