### ISSUE TITLE
Size overflow warning on 32-bit system

### ISSUE THREAD

**Issue by milasudril** [falkTX/Carla#321]
Why this warning? I guess this code is broken on 32-bit systems.

    In file included from src/pugl/pugl_x11.c:46:0,
                 from src/Window.cpp:36:
    src/pugl/../sofd/libsofd.c: In function ‘void fmt_size(Display*, FibFileEntry*)’:
    src/pugl/../sofd/libsofd.c:1042:14: warning: comparison is always false due to limited range of data type [-Wtype-limits]
    if (f->size > 10995116277760) {
                   ^
    src/pugl/../sofd/libsofd.c:1045:14: warning: comparison is always false due to limited range of data type [-Wtype-limits]
    if (f->size > 1099511627776) {
              ^
    src/pugl/../sofd/libsofd.c:1048:19: warning: comparison is always false due to limited range of data type [-Wtype-limits]
    else if (f->size > 10737418240) {

**Comment by falkTX** [comment]
The code is fine, that section is part of DPF but never used in carla.
