### ISSUE TITLE
Renamed/replaced plugins are not loaded

### ISSUE THREAD

**Issue by distrozapper** [falkTX/Carla#325]
Renamed/replaced plugins can't be found by Carla. This breaks older Carla projects.
In my case, Calf LV2 Equalizers were renamed from "eq5/eq8" to "Equalizer5Band/Equalizer8Band" by an update. When loading an old project, Carla terminal then shows errors like:

Failed to load a plugin, error was:
Failed to find the requested plugin

**Comment by distrozapper** [comment]
Hi falkTX,
Since you provided a workaround (thanks x1000 BTW) I could close this issue . Would you agree to declare this  "CLOSED" or would you like to let it stay open? (since on IRC you mentioned lilv "maybe being involved)?

**Comment by falkTX** [comment]
it can be closed yes.
the plugins were actually missing by mistake.

**Comment by distrozapper** [comment]
Issue SOLVED/CLOSED. Thank you falkTX :)
