### ISSUE TITLE
Zynaddsubfx plugin does not restore its settings in Ardour

### ISSUE THREAD

**Issue by Fak3** [falkTX/Carla#326]
When Zynaddsubfx LV2 plugin is used as instrument in ardour session, it does not save\restore its state on session save\load.

**Comment by falkTX** [comment]
Zyn has been updated frequently before, can you please check if this issue still happens to you?
Thanks.

**Comment by Fak3** [comment]
I tested git version of 18 Dec 2015, and this issue still applies. I will test current git master.

**Comment by Fak3** [comment]
Current git master still has this issue

**Comment by falkTX** [comment]
I believe this is fixed now, please re-test.
Note that old sessions might still not work (data was never saved), better open and re-save.

**Comment by Fak3** [comment]
I tested current git master (15bec22636bc19c2f8b1a287461a2caf5fb7103b) and bug is still here.
I re-saved old ardour session with new instrument selected and zyn-master-volume changed, but after load it is still getting reset to the default sine wave and master volume does not restored.

**Comment by Fak3** [comment]
OTOH "Part volume" does get properly saved and restored. And all other settings, which are available with the Ardour-generic plugin settings window.

**Comment by falkTX** [comment]
please try again.
(the f1f3324012406f8bf5e977ecc2dde659c1b9b144 commit is quite important)

Create a new project, save, re-check if the bug is still there and if yes upload the ardour folder/project here.
Somehow this works fine to me but not for you :/
With a project file at least I'll know if what's failing is the save or the restore.

**Comment by Fak3** [comment]
I tried current master (b9f04c961b9e7a87f72de8987fbbf39681c9667f) and bug is still here for me.
Here is my ardour session dir: https://yadi.sk/d/otZizHcimoVEy

**Comment by Fak3** [comment]
To my observation plugin state is properly saved in state.ttl - i tried to changevalue of controllers -> portamento-time, and its value does get properly reflected in the state.ttl after i saved ardour session. But after load this session anew. the portamento-time is reset to default value of 64.

**Comment by fundamental** [comment]
It should be safe to close this issue as this appears to have been a bug in an old version of sratom

**Comment by falkTX** [comment]
I guess so.

@Fak3 fundamental has confirmed the issue, it's something that happens in old lv2-related libs.
you'll need to update serd, sord, sratom and lilv to get this fixed.

**Comment by Fak3** [comment]
Thanks. I upgraded sratom and the issue resolved.
