### ISSUE TITLE
Midi controlled slider skips zero and passes from -1 to +1 

### ISSUE THREAD

**Issue by MichelV87** [falkTX/Carla#327]
Distrib KXStudio
Carla Version 1.9.6 (2.0-beta-4) 
- Insert "Midi Chromatic Transpose" plugin in Carla
- Click on Edit - Parameters and assign a control number to "Transpose" slider
- Move assigned controller on your midi device : a value of 63 sets the Carla slider to -1 and a value of 64 sets it to +1. Impossible to get 0. You have to right-click on slider to reset it.

**Comment by MichelV87** [comment]
Or is it a plugin issue ?

**Comment by SpotlightKid** [comment]
The LV2 control port for the "Transpose" parameter is defined in the `midifilter.ttl` file like this:

```
[ a lv2:InputPort, lv2:ControlPort ; lv2:index 4 ; lv2:symbol "transpose" ; lv2:name "Transpose"; lv2:minimum -72 ; lv2:maximum 72 ; lv2:default 0; lv2:portProperty lv2:integer ]
```

So it has actually 145 possible values. That's greater than the range of a MIDI CC (0-127). Some values will go lost in the mapping of the input range (0..127) to the parameter range (-72..+72).

**Comment by MichelV87** [comment]
Ok, thanks for this info. I open a new issue on midifilter github.

**Comment by MichelV87** [comment]
Issue fixed with a range of -64..+63 in midifilter.ttl
