### ISSUE TITLE
carla vst won't load win32 vst in Bitwig

### ISSUE THREAD

**Issue by progwolff** [falkTX/Carla#329]
I installed carla-git, carla-bridges-win32-git and carla-bridges-win64-git from the Arch AUR.
Everything is working nicely in the standalone version, but using the carla vst plugins in Bitwig I am not able to load any win32 (or 64) vst.  
By default it says that this carla build could not handle win32 plugins. After symlinking the win32 and win64 bridges to the carla.vst directory I'm getting timeouts.

Are the carla vst plugins able to load win32 vsts?

**Comment by falkTX** [comment]
The bridges work fine, I just tested them in renoise now.
![scr001](https://cloud.githubusercontent.com/assets/1334853/11762306/7e3ccbb4-a0e2-11e5-94c3-b8ff3dea168f.png)

The AUR packages install are missing the lv2 and vst plugin symlinks, I just added a comment there about this.

And the timeout, it's probably cause you didn't copy the *.dll files along with the *.exe ones.
You need to copy both.

Let me know if that works!

**Comment by progwolff** [comment]
Thanks for your quick response!

I rebuilt the AUR packages, still no luck.
Loading a vst instance of carla inside carla standalone and loading win32 vsts inside this instance is working though, so it seems like it's specific to Bitwig.

**Comment by falkTX** [comment]
did you try it on any other host besides bitwig?

**Comment by progwolff** [comment]
Just installed Renoise, no problems there...

**Comment by falkTX** [comment]
What version of bitwig are you using?
Please try an older version and see if it works there.

**Comment by alexejmilstein** [comment]
Same problem here. Bitwig 1.3.5 and latest carla-git from KXStudio repos on Ubuntu 15.10. The plugins load fine in the standalone version but timeout immediately in Bitwig.

**Comment by SpotlightKid** [comment]
In Tracktion win32 plugins work, but Carla disables them after some time, i.e. the power icon turns red. Haven't exactly determined, when this happens, but usually after Tracktion was idle for some minutes.

**Comment by SpotlightKid** [comment]
Have to qualify my comment above: the same thing happens in Carla stand-alone, so it's not related to Tracktion nor probably the subject of this ticket.

**Comment by progwolff** [comment]
I tried it with the git versions of Carla, Bitwig 1.1.11 and 1.3.5

**Comment by falkTX** [comment]
ok, so just that we're clear.
it works fine on the standalone, also when using carla-vst in renoise. but not when using carla-vst in bitwig.
is that it?

**Comment by progwolff** [comment]
That's it.

**Comment by psychonain** [comment]
hi,
same issue here since the early versions of carla-vst i never get any windows vst to load in bitwig, ... timleout ... (from bitwig 1.0.15 to 1.3.5) however it's working amazingly with ardour or lmms.
so it must be a bitwig issue ... note that all lv2 ladspa and linuxvsts works fine in bitwig with carla vst
thanks Falk-tx for your amazing work ! (and sorry for my english)

**Comment by RelativePrime** [comment]
I'm having the same issue with Bitwig 1.3.5 - loading Windows VSTs in Carla works great standalone, but when loaded with Carla in Bitwig it times out, producing an error window "Timeout while waiting for a response from plugin-bridge(or the plugin crashed on initialization?)" I am able to load lv2 and LinuxVSTs fine.

Trying to load the DSK Music strings VST in Bitwig shows nothing on std err, though strace gives:

```
15048 ioctl(45, FIONREAD, [104])        = 0
15048 read(45, "wine: cannot find '//home/paracelsus/Downloads/Carla-2.0beta4-linux64/carla.vst/carla-bridge-win32.e"..., 8192)
 = 104
15048 fstat(45, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
15048 ioctl(45, FIONREAD <unfinished ...>
14992 poll([{fd=23, events=POLLIN|POLLOUT}], 1, 4294967295 <unfinished ...>
15048 <... ioctl resumed> , [0])        = 0
14992 <... poll resumed> )              = 1 ([{fd=23, revents=POLLOUT}])
15048 write(41, "\33[31mCarla assertion failure: \"getType() != kEngineTypePlugin\" in file CarlaEngine.cpp, line 289\33[0m"...
, 205 <unfinished ...>
14992 writev(23, [{"\202\3\n\0\350\5\300\5\352\5\300\5\220\6\263\3\\\1\31\0\31\0\3\0\\\1\31\0\30\2\0\0\351\5\300\5\0\0\0\0+\0\1
\0", 44}], 1 <unfinished ...>
15048 <... write resumed> )             = 205
14992 <... writev resumed> )            = 44
15048 read(45,  <unfinished ...>
14992 futex(0x7ffd148ad234, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
```

I'd love to be able to use Carla in Bitwig with Windows VSTs. Does this look like something that might be fixable? Can I help troubleshoot further?

Cheers, 
Pete

**Comment by falkTX** [comment]
it's certainly fixable.
bitwig is just a bit tricky to debug because it captures console output..
do you know a way around that?

**Comment by falkTX** [comment]
Found the issue, fix coming

**Comment by RelativePrime** [comment]
Fantastic!! Thank you so much!

**Comment by RelativePrime** [comment]
Fantastic! I can't wait to test. Thank you so much for this, the ability to use this in Bitwig will be wonderful.

Sadly, I ran into a snag. Could you maybe offer some insight? I compiled with dependencies in place (make features output below).

However, when I try to add a Windows VST plugin (from DSK Music), Carla reports "This Carla build can not handle this binary." There are no messages to std out. (I've tried with a few other Windows VSTs as well.)

Might I have missed something in the build process?

My carla.vst build contains:

<code>
ls /opt/carla/lib/vst/carla.vst/
carla-bridge-lv2-gtk2    carla-bridge-lv2-x11    CarlaPatchbay.so             libcarla_interposer-x11.so
carla-bridge-lv2-modgui  carla-bridge-native     CarlaRackFX.so               libcarla_utils.so
carla-bridge-lv2-qt4     carla-discovery-native  CarlaRack.so                 resources
carla-bridge-lv2-qt5     CarlaPatchbayFX.so      libcarla_interposer-safe.so  styles
</code>

Make features output:

<code>
paracelsus@calculus:~/Carla> make features
\033[36m---> Main features \033[0m
Front-End:  \033[32m YES \033[0m(Using Qt4)
LV2 plugin: \033[32m YES \033[0m
VST plugin: \033[32m YES \033[0m
OSC support:\033[32m YES \033[0m

\033[36m---> Engine drivers \033[0m
JACK:       \033[32m YES \033[0m
ALSA:       \033[32m YES \033[0m
PulseAudio: \033[32m YES \033[0m
CoreAudio:  \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m
ASIO:       \033[31m NO \033[0m \033[30;1m[Windows only]\033[0m
DirectSound:\033[31m NO \033[0m \033[30;1m[Windows only]\033[0m

\033[36m---> Plugin formats: \033[0m
Internal:\033[32m YES \033[0m
LADSPA:  \033[32m YES \033[0m
DSSI:    \033[32m YES \033[0m
LV2:     \033[32m YES \033[0m
VST:     \033[32m YES \033[0m(with UI)
VST3:    \033[31m NO \033[0m \033[30;1m[Windows and MacOS only]\033[0m
AU:      \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m

\033[36m---> LV2 UI toolkit support: \033[0m
External:\033[32m YES \033[0m(direct)
Gtk2:    \033[32m YES \033[0m(bridge)
Gtk3:    \033[31m NO \033[0m \033[33m[Gtk3 missing]\033[0m
Qt4:     \033[32m YES \033[0m(bridge)
Qt5:     \033[32m YES \033[0m(bridge)
X11:     \033[32m YES \033[0m(direct+bridge)
Cocoa:   \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m
Windows: \033[31m NO \033[0m \033[30;1m[Windows only]\033[0m

\033[36m---> File formats: \033[0m
GIG:\033[32m YES \033[0m
SF2:\033[32m YES \033[0m
SFZ:\033[32m YES \033[0m

\033[36m---> Internal plugins: \033[0m
Carla-Patchbay: \033[32m YES \033[0m
Carla-Rack:     \033[32m YES \033[0m
DISTRHO Plugins:\033[32m YES \033[0m(with UI)
DISTRHO ProM:   \033[31m NO \033[0m (missing libprojectM)
ZynAddSubFX:    \033[31m NO \033[0m \033[33m[fftw3, mxml or zlib missing]\033[0m
</code>

**Comment by falkTX** [comment]
Building the windows bridges is not documented yet, as it's still an experimental feature.
If you want to build it yourself I suggest having a look at the AUR PKGBUILD, https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=carla-bridges-win32-git

basically you need mingw and wine.
On the first step you setup the environment for mingw and build using 'make win32'.
Then you cleanup the environment (not the build!) and use 'make wine32'.

**Comment by RelativePrime** [comment]
Hey there,

Thank you for the build tips from the Arch pkg. Sadly, I'm running into the same type of build issues as described in https://github.com/falkTX/Carla/issues/192

I'm afraid building the windows bridges is beginning to exceed my compiling debug skills, with the mingw layer, etc.

Might there, by chance, happen to be pre-compiled binaries for 2.0-beta5 made available at some point at http://sourceforge.net/projects/kxstudio/files/Releases/carla/

I appreciate the work you are doing on Carla - it's wonderful. 

Cheers.
Pete

**Comment by falkTX** [comment]
There will be a release very soon, just need to finish some very small details first.

**Comment by RelativePrime** [comment]
Wonderful. Thank you!

**Comment by RelativePrime** [comment]
Just curious if a newer pre-compiled build might still be in the works? 2.0-beta4 seems the latest on sourceforge. It would still be great to be able to use Carla within Bitwig. Thanks for your work on Carla!

**Comment by falkTX** [comment]
I'm hoping to do a new release very soon.
Want to squash the last bugs in the 2.0-beta5 milestone first.
But considering it has been more than 1 year since the last release, I don't want to wait long.
I'm setting a deadline for next tuesday, regarding code changes. After tuesday I can only change things to fix the build :)

**Comment by RelativePrime** [comment]
Brilliant! Looking forward to the new release, thank you!

**Comment by RelativePrime** [comment]
Hi there. Just wondering if a 2.0-beta5 binary package might be available via sourceforge soon-ish? I'd love to try some new plugins in Bitwig.

**Comment by falkTX** [comment]
the 2.0-beta5 has been available to download for quite a while now.
http://kxstudio.linuxaudio.org/Downloads#Binaries

**Comment by RelativePrime** [comment]
Doh! Thanks. (I looked at the sourceforge site rather than kxstudio.)

Thanks for the work, very happy it works in Bitwig 2.1.1!

**Comment by zannis** [comment]
Hello everyone, I think I am still having the same error.

I'm on Arch linux, with AUR packages carla-git and carla-bridges-win packages installed and up-to-date.

Carla standalone loads windows VSTs just fine but carla-plugin does not when I invoke it as a VST from Bitwig 2.1.3 or Ardour 5.9 with the error message "This Carla build cannot handle this binary". When I try to refresh my VSTs using carla-plugin it looks like the windows bridges are not installed at all, the tick-boxes have an X. Is there something I am missing completely here? 

I tried replacing the carla-bridges-win package with the 2 explicit ones in the AUR "carla-bridges-win32-git" and "carla-bridges-win64-git" but the build failed.

Any help would be greatly appreciated.

**Comment by progwolff** [comment]
Hi @zannis, 

carla-bridges-win is too old. You will need the git packages.
Make sure you have gcc-multilib installed before building them. If the build still fails, please show us the error messages.

**Comment by zannis** [comment]
Hey @progwolff! It worked, thanks so much! 

The dream of working with audio in linux is alive !
