### ISSUE TITLE
Feature request: configure WINEPREFIX for win32/64 bridges

### ISSUE THREAD

**Issue by jypma** [falkTX/Carla#332]
It seems that Carla currently has no means to configure which WINEPREFIX is used for bridged windows VST plugins. This means that I wouldn't be able to combine e.g. a 32-bit and a 64-bit windows VST (or a WinXP and a Win7 one) inside one ardour session. Since I believe all bridges are separate processes, don't they have a separate environment as well, making this fairly straightforward to implement?

**Comment by falkTX** [comment]
I agree with this.
Something I want to see in carla before 2.0 final release.

**Comment by jypma** [comment]
How about starting with having `CarlaPluginBridge` auto-detect a path being inside a wine prefix, e.g. by finding the closest parent path having `./system.reg`? I think such logic might be added to [CarlaPluginBridge:552](https://github.com/falkTX/Carla/blob/master/source/backend/plugin/CarlaPluginBridge.cpp#L552) when launching wine. It could then auto-set `WINEPREFIX` if such a path was found.

@falkTX I could give it a shot if you agree with that approach.

Actually, about the `carla_setenv` calls around [CarlaPluginBridge:586](https://github.com/falkTX/Carla/blob/master/source/backend/plugin/CarlaPluginBridge.cpp#L586), is there a mutex on those? Or would two plugin bridges starting at once simply try to set up the same env before launching the external process?

**Comment by falkTX** [comment]
finding the parent path until a system.reg is found is a good idea.
but after finding that we should also test for 'dosdevices' folder too.

the discovery code will need something similar too, and I think it's better to start with that.
(python is easier to do for these things)
this will be done in the python code, not c++.

And yes, there's a lock for those environment variables, see https://github.com/falkTX/Carla/blob/master/source/backend/plugin/CarlaPluginBridge.cpp#L577
