### ISSUE TITLE
infamous lushlife causes segmentation fault when Force Mono option is enabled

### ISSUE THREAD

**Issue by spectromas** [falkTX/Carla#334]
44100 Hz, 512 buffer size, 64 bit linux 4.3.3.
Driver: JACK
Mode: Multiple Clients
Max Parameters: 200
Force mono plugins as stereo (ticked)

http://kxstudio.linuxaudio.org/paste/ef4Bw

Disabling Force mono plugins as stereo option stops the crash from happening.

**Comment by falkTX** [comment]
I'm unable to reproduce this because no matter what I try the force-stereo option for that plugin cannot be enabled. (which is on purpose, otherwise crashes would happen)

What carla version are you using? latest carla-git package?

**Comment by spectromas** [comment]
Yes, it's a build of the latest git version. Not sure what else I can provide to let you replicate it. Can I export all the carla settings somehow?

**Comment by falkTX** [comment]
yes, zip the contents of ~/.config/falkTX/ and upload them somewhere.

**Comment by spectromas** [comment]
[falkTX.zip](https://github.com/falkTX/Carla/files/72251/falkTX.zip)

Ok, here you go.
