### ISSUE TITLE
Will not build when using multiple threads

### ISSUE THREAD

**Issue by InTheMorning** [falkTX/Carla#335]
When makepkg is set to use multiple cores, carla and carla-git fail to build.
https://gist.github.com/InTheMorning/c9f0a5e3b700b88e31ae

**Comment by falkTX** [comment]
Your gist url seems invalid, gives 404

**Comment by InTheMorning** [comment]
Sorry, it was because I changed my username.  I fixed the url.

**Comment by falkTX** [comment]
Ok, got it.
Seems to be something in the theme. I'll fix it soon.
