### ISSUE TITLE
Carla hangs up when trying to rename a plugin

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#337]
Every time I try to rename a plug-in node in Carla - it becomes unresponsive and I have to restart it to regain control.

**Comment by falkTX** [comment]
I need more info here.
(I was just looking into renaming btw)

which driver you use? alsa, jack, other?
which process mode?
is the plugin you're trying to rename running as a bridge?

**Comment by unfa** [comment]
Driver: JACK,
Process mode: Multiple processes,
The plugin isn't running as a bridge AFAIK.

This never worked for me, no matter what I wanted to rename. When I press the "Ok" button in the rename dialog - Carla hangs.

I performed a test run with an "Audio File internal plugin" trying to rename it to "NEW NAME":

Here's gdb output:

	$ carla --gdb
	GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
	Copyright (C) 2014 Free Software Foundation, Inc.
	License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
	This is free software: you are free to change and redistribute it.
	There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
	and "show warranty" for details.                                                                                                                                                                                                                                                
	This GDB was configured as "x86_64-linux-gnu".                                                                                                                                                                                                                                  
	Type "show configuration" for configuration details.                                                                                                                                                                                                                            
	For bug reporting instructions, please see:                                                                                                                                                                                                                                     
	<http://www.gnu.org/software/gdb/bugs/>.                                                                                                                                                                                                                                        
	Find the GDB manual and other documentation resources online at:                                                                                                                                                                                                                
	<http://www.gnu.org/software/gdb/documentation/>.                                                                                                                                                                                                                               
	For help, type "help".                                                                                                                                                                                                                                                          
	Type "apropos word" to search for commands related to "word"...                                                                                                                                                                                                                 
	Reading symbols from /usr/bin/python3...(no debugging symbols found)...done.                                                                                                                                                                                                    
	(gdb) run                                                                                                                                                                                                                                                                       
	Starting program: /usr/bin/python3 /usr/share/carla/carla --with-appname=/usr/bin/carla --with-libprefix=/usr --gdb                                                                                                                                                             
	[Thread debugging using libthread_db enabled]                                                                                                                                                                                                                                   
	Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".                                                                                                                                                                                                      
	Traceback (most recent call last):                                                                                                                                                                                                                                              
	File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>                                                                                                                                                                     
	from libstdcxx.v6.printers import register_libstdcxx_printers                                                                                                                                                                                                               
	ImportError: No module named 'libstdcxx'                                                                                                                                                                                                                                        
	Using "carla" theme                                                                                                                                                                                                                                                             
	Carla 1.9.6 (2.0-beta4) started, status:                                                                                                                                                                                                                                        
	Python version: 3.4.3                                                                                                                                                                                                                                                         
	Qt version:     4.8.6                                                                                                                                                                                                                                                         
	PyQt version:   4.10.4                                                                                                                                                                                                                                                        
	Binary dir:     /usr/lib/carla                                                                                                                                                                                                                                                
	Resources dir:  /usr/share/carla/resources                                                                                                                                                                                                                                    
	[New Thread 0x7fffd7025700 (LWP 8375)]                                                                                                                                                                                                                                          
	[New Thread 0x7fffd6824700 (LWP 8376)]                                                                                                                                                                                                                                          
	libjack.so.0 loaded sucessfully!                                                                                                                                                                                                                                                
	[New Thread 0x7fffd589a700 (LWP 8377)]                                                                                                                                                                                                                                          
	[New Thread 0x7fffd4cbd700 (LWP 8380)]                                                                                                                                                                                                                                          
	[New Thread 0x7fffd42ce700 (LWP 8381)]                                                                                                                                                                                                                                          
	[New Thread 0x7fffcefff700 (LWP 8382)]                                                                                                                                                                                                                                          
	[New Thread 0x7fffce7fe700 (LWP 8383)]                                                                                                                                                                                                                                          
	[New Thread 0x7fffc2d20700 (LWP 8394)]                                                                                                                                                                                                                                          
	[Thread 0x7fffd4cbd700 (LWP 8380) exited]                                                                                                                                                                                                                                       
	[Thread 0x7fffc2d20700 (LWP 8394) exited]                                                                                                                                                                                                                                       
	[Thread 0x7fffd589a700 (LWP 8377) exited]                                                                                                                                                                                                                                       
	^C                                                                                                                                                                                                                                                                              
	Program received signal SIGINT, Interrupt.                                                                                                                                                                                                                                      
	__lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135                                                                                                                                                                                                 
	135     ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.                                                                                                                                                                                       
	(gdb) bt
	#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
	#1  0x00007ffff7bc8ccc in pthread_cond_signal@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_signal.S:144
	#2  0x00007fffd5c48052 in jack_messagebuffer_thread_init () from /usr/lib/x86_64-linux-gnu/libjack.so.0
	#3  0x00007fffd5c46dae in jack_set_thread_init_callback () from /usr/lib/x86_64-linux-gnu/libjack.so.0
	#4  0x00007fffdcb79edc in ?? () from /usr/lib/carla/libcarla_standalone2.so
	#5  0x00007fffdcb05938 in ?? () from /usr/lib/carla/libcarla_standalone2.so
	#6  0x00007ffff197cadc in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
	#7  0x00007ffff197c40c in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
	#8  0x00007fffe4feffed in _ctypes_callproc () from /usr/lib/python3.4/lib-dynload/_ctypes.cpython-34m-x86_64-linux-gnu.so
	#9  0x00007fffe4ff0563 in ?? () from /usr/lib/python3.4/lib-dynload/_ctypes.cpython-34m-x86_64-linux-gnu.so
	#10 0x000000000051c577 in PyEval_EvalFrameEx ()
	#11 0x000000000051c29d in PyEval_EvalFrameEx ()
	#12 0x00000000004879bf in ?? ()
	#13 0x00000000004c05ad in ?? ()
	#14 0x00000000005548ee in PyEval_CallObjectWithKeywords ()
	#15 0x00007ffff4f70928 in sip_api_invoke_slot () from /usr/lib/python3/dist-packages/sip.cpython-34m-x86_64-linux-gnu.so
	#16 0x00007ffff6254206 in ?? () from /usr/lib/python3/dist-packages/PyQt4/QtCore.cpython-34m-x86_64-linux-gnu.so
	#17 0x00007ffff6257a60 in ?? () from /usr/lib/python3/dist-packages/PyQt4/QtCore.cpython-34m-x86_64-linux-gnu.so
	#18 0x00007ffff625778e in ?? () from /usr/lib/python3/dist-packages/PyQt4/QtCore.cpython-34m-x86_64-linux-gnu.so
	#19 0x00007ffff6257c12 in ?? () from /usr/lib/python3/dist-packages/PyQt4/QtCore.cpython-34m-x86_64-linux-gnu.so
	#20 0x00007ffff5d5fa78 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
	#21 0x00007ffff3ae7a62 in QWidget::customContextMenuRequested(QPoint const&) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
	#22 0x00007ffff3af58f7 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
	#23 0x00007ffff3e9704e in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
	#24 0x00007ffff4ad69eb in ?? () from /usr/lib/python3/dist-packages/PyQt4/QtGui.cpython-34m-x86_64-linux-gnu.so
	#25 0x00007ffff3aa5e2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
	#26 0x00007ffff3aad1f8 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
	#27 0x00007ffff4ad15d6 in ?? () from /usr/lib/python3/dist-packages/PyQt4/QtGui.cpython-34m-x86_64-linux-gnu.so
	#28 0x00007ffff5d4b4dd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
	#29 0x00007ffff3b20a40 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
	#30 0x00007ffff3b20289 in QApplication::x11ProcessEvent(_XEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
	#31 0x00007ffff3b47b32 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
	#32 0x00007ffff560ae04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
	#33 0x00007ffff560b048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
	#34 0x00007ffff560b0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
	#35 0x00007ffff5d787a1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
	#36 0x00007ffff3b47be6 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
	#37 0x00007ffff5d4a0af in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
	#38 0x00007ffff5d4a3a5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
	#39 0x00007ffff5d4fb79 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
	#40 0x00007ffff4a8d430 in ?? () from /usr/lib/python3/dist-packages/PyQt4/QtGui.cpython-34m-x86_64-linux-gnu.so
	#41 0x0000000000518545 in PyEval_EvalFrameEx ()
	#42 0x000000000051c29d in PyEval_EvalFrameEx ()
	#43 0x0000000000487164 in PyEval_EvalCode ()
	#44 0x000000000056be90 in ?? ()
	#45 0x000000000047b1c3 in PyRun_FileExFlags ()
	#46 0x000000000047b5a0 in PyRun_SimpleFileExFlags ()
	#47 0x00000000005c0b33 in Py_Main ()
	#48 0x000000000047dbc1 in main ()
	(gdb) q
	A debugging session is active.

		Inferior 1 [process 8369] will be killed.

	Quit anyway? (y or n) y

**Comment by falkTX** [comment]
are you using jack1 or jack2?

**Comment by unfa** [comment]
I'm using jack1.

**Comment by unfa** [comment]
Today I tried renaming a plugin and Carla froze for a few seconds, but then it cam back to life. What a surprise! I have no idea why it hung for so long, but I'm glad it's still alive. Gotta do more testing.

**Comment by unfa** [comment]
Today I tried renaming a plugin and Carla froze for a few seconds, but then it cam back to life. What a surprise! I have no idea why it hung for so long, but I'm glad it's still alive. Gotta do more testing.

**Comment by falkTX** [comment]
I think it only happens with jack1, I haven't checked it yet.

**Comment by falkTX** [comment]
I can confirm the issue happens with jack1, with jack2 everything is fine.
