### ISSUE TITLE
wish: add a favorite plugins menu somewhere

### ISSUE THREAD

**Issue by Houston4444** [falkTX/Carla#339]
The "add plugin" window can be long to open  (very long on old computers) when a lot of plugins are installed on system, that is normal. But it should be nice to can add quickly plugins stored in a favorite menu as ardour does. 
for example: right click on a plugin could purpose "add to favorites", and favorites could be a tab on side panel.

I think that most users use almost time the same plugins.

**Comment by falkTX** [comment]
I don't think it's normal for the add-plugin dialog to take so long.
I'm sure it can be optimized.

A favourite system is planned, together with a way to flag a plugin as unstable so it always runs in bridge mode.

**Comment by falkTX** [comment]
Favorite plugins has been added some time ago,
Basically click on the left side of the plugin list to enable the "star" and have it become part of the favorites.

**Comment by Houston4444** [comment]
Oh nice, I did not see this.
Thanks !
