### ISSUE TITLE
wish: force mono plugins to stereo in carla-rack

### ISSUE THREAD

**Issue by Houston4444** [falkTX/Carla#340]
All is in the title. I think you already think to that but I don't see anything about in Issues.

**Comment by falkTX** [comment]
This is already the case in carla.
Plugins loaded inside carla-rack as plugin will always have its force-stereo option enabled.
The thing is that not all plugins can support this.

**Comment by falkTX** [comment]
what plugin are you seeing  that is not being run as forced-stereo?

**Comment by Houston4444** [comment]
ohhh, that was  GxAmplifier. But plugin GxAmplifier Stereo exists, so it's really not a problem. 
But for main application or carla-patchbay, if carla can know if plugins aren't stereo able, it would be better to set disable the "Force Stereo" box in edit window.
I thought that it works as in ardour where plugins seems to be loaded 2 times with a combined interface.

**Comment by falkTX** [comment]
The force-stereo is disabled when not possible to achieve (at least in theory).
Carla does have some limitations on what plugins can be used in force-stereo mode, and gxamp probably triggers those.

**Comment by falkTX** [comment]
I consider this fixed.
Under rack processing mode force-stereo option will now be forced to all plugins.

Carla can't make all plugins run in force-stereo mode at the moment, but that's a different issue.
The more complex the plugins are, the harder it is to have that working.
