### ISSUE TITLE
Carla VST adds noise to output

### ISSUE THREAD

**Issue by suhr** [falkTX/Carla#342]
I tried to use Carla to connect zynaddsubfx to some DAW that supports onlly VST, but Carla adds noise to VST output.
Noise description: it sounds somewhat like electrical hum with distortion.

**Comment by falkTX** [comment]
Which host?
It's probably because it's using the wrong buffer size.

**Comment by suhr** [comment]
CarlaPatchbay.

**Comment by falkTX** [comment]
I mean *which host*.
As in, what DAW or other application are you loading the Carla VST in?

**Comment by suhr** [comment]
Bitwig Studio. I can also try it in Radium.
Dexed or Oxe FM Synth work fine there.

**Comment by falkTX** [comment]
What sample rate and buffer size do you use?
Also do you use bitwig with ALSA or JACK?

**Comment by suhr** [comment]
I use it with ALSA. Sample rate is 44100 and buffer size is 256 samples.

**Comment by falkTX** [comment]
damn bitwig always reports 1024 buffer size to plugins, no matter what it actually uses.
we'll need a bitwig-specific hack.. :(

**Comment by suhr** [comment]
Well, at least now I know how to workaround this issue.
