### ISSUE TITLE
[Suggestion] Cancel and/or close button in Add plugin window

### ISSUE THREAD

**Issue by Barbouze** [falkTX/Carla#343]
Hi!

The only solution to to go back to the rack or patchbay after refreshing the available plugins is to insert a new plugin. Or let's say you want to add a plugin but change your mind about that for whatever reason and just want to go back to the rack or patchbay. You can't without adding a new one (that you have to delete after).
Is it possible to add a "cancel" button and/or the usual cross button to close the Add plugin.. window? 

Regards,
Barbouze

**Comment by falkTX** [comment]
You can press the window 'x' button to close it.
Or press the 'Esc' key.

But I can certainly add a cancel button, no problem.

**Comment by Barbouze** [comment]
There is no 'x' button :p
![capture du 2016-01-09 19 09 44](https://cloud.githubusercontent.com/assets/2013289/12217562/a67d0e44-b704-11e5-980d-32fd5d4c9b52.png)
I didn't think of pressing any key (specially the 'Esc' one, my bad) as there was no clear clue that the window could be closed like that, hence this humble request. I'm using carla-git with Linux Mint 17.3 Cinnamon and this has been here for at least a few weeks but I can't say if this was like that in 17.2 :(

If there's anything I can do feel free to ask anything and thanks for the reply and the great job you're doing here :)

**Comment by falkTX** [comment]
FYI I consider the Mint WM broken if it really can't show buttons for modal dialogs...
Does that mean all the carla help->about actions don't have buttons? and the settings as well?

In any case I added the cancel button.
If there's any more unclosable dialogs let me know.

**Comment by Barbouze** [comment]
Well, it is broken then... As you guessed, nothing for help->about or the settings window. I'll dig into Cinnamon settings and bug reports and write here if I find something :)

**Comment by Barbouze** [comment]
Found out why \o/

In Mint 17.3, "Dialog windows are now attached to their parent window by default. This setting was already present in Cinnamon (in “System Settings”->”Windows”->”Behavior”->”Attach dialog windows to the parent window”), but it was improved in version 2.8; Dialog windows are now attached to the center of their parent window rather than their titlebar, and the shading of the parent window was made a little more obvious than it was before."

Set this option off and buttons are back :)

**Comment by falkTX** [comment]
having the window centered sounds a good idea, removing the buttons is awful.
but anyway, their choice.
