### ISSUE TITLE
Recent carla-lmms update kills connectors in patchbay 

### ISSUE THREAD

**Issue by faraway1nspace** [falkTX/Carla#344]
Hello, and thanks for this great plugin.
There was a recent update to carla-lmms plugins in the KXSTUDIO repos. Sorry I don't know which update caused this error, but I suspect it was the the most recent (I hadn't updated in about two weeks). Anyway, after the update, connections were lost in the carla-patchbay lmms plugin for saved lmms projects which used a carla patchbay, as well as for saved carla lmms-instruments. This doesn't seem to effect .carxp files used outside of lmms. 
More detail: it seems the patchbay connections are lost somewhat randomly: some were maintained, some were lost. The only consistency was that the connections to the final 'AUDIO OUT' jack were lost 100% of the time, and very often with connections associated with IR lv2 plugin and the Eqinox lv2 plugins. Otherwise, the problem seems randomly to apply to lv2, ladspa plugins, but not for the connections leading to instruments and midi-tools (i.e., the midi connections were maintained).

Finally, this seems to have been a one-time thing due to the update. Subsequent saved carla-patchbay connections ARE maintained. Its just a real bummer because all my old project files are now dis-connected, and I have to go back and try to figure out the chain of connections. A great thing about Carla was that I could have VERY elaborate parallel chains of audio, but now I can't remember what I was doing for old projects.

I am using lmms 1.1.3  And Carla version 1.9.6 (2.0-beta4) binaries from the kxstudio repos.

**Comment by falkTX** [comment]
First time I hear about this.
Please post an example of such project (lost connections) and I'll take a close look.

**Comment by faraway1nspace** [comment]
Thanks FalkTX.
Let me know if the attached files are adequate or if you need something else.
- guitar_bass_crunch_pl_whine.zip has an lmms preset file (.xpf) that is a saved carla-patchbay instrument: it has a sfz from the no budget orchaestra project, plus two rakarack lv2 plugins. 
- carla_debug.zip has the lmms project files .mmpz which used the above carla patchbay instrument.
Thanks again

[guitar_bass_crunch_pl_whine.zip](https://github.com/falkTX/Carla/files/91611/guitar_bass_crunch_pl_whine.zip)

[carla_debug.zip](https://github.com/falkTX/Carla/files/91607/carla_debug.zip)

**Comment by falkTX** [comment]
I think I know what's going on.
I recently made so that some plugins will always run in bridge mode, one of them being ir.lv2.
The problem happens to be that bridged plugin port names are not exported, they use generic names right now like "audio_in_1".

So your patches are fine, and the only ones that don't load properly right now are the ones that include ir.lv2 and/or calf analyzer.

Exporting the port names for bridged plugins is something I need to do, so I'll make sure to do this ASAP.
Once I do this I'll ask you to re-test.
(probably this weekend)

**Comment by faraway1nspace** [comment]
Great to hear! Standing by to retest...

**Comment by faraway1nspace** [comment]
Hi falkTX
After the most recent carla update (1.9.6 (2.0-beta4)), I didn't see any improvement with LMMS project files that use Carla patch-bay instruments. Connections to audio-out from Eqinox and IR lv2 and some other plugins are still lost. But hopefully your update prevents it from happening again in the future.

**Comment by falkTX** [comment]
I haven't pushed the update yet.
But I'll do it now.
