### ISSUE TITLE
Cannot assign multiple parameters to a single CC control - only the first one reacts

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#345]
I tried assigning a bunch of controls in an effect (Amount controls in a GxMultibandEcho) to a single CC knob on my MIDI keyboard. Looks like only the first one in stack (vertically) rects, the rest ignores the motion. When I changed the MIDI channel of the first control to a different one, the second one started moving, Looks like whatever reads the data, deletes it so no other control can make use of it.

I'd like to be able to control multiple parameters with a single knob on the same MIDI channel. Ideally with amount multipliers (-2..+2) and offset (-1..+1) controls so I can then have macro-like control over the effects and synths.

**Comment by falkTX** [comment]
Currently carla only supports 1 parameter per midi cc, as otherwise it might be confusing.
Some time later when midi learn appears (with a dedicated page for midi cc stuff) I'll make sure to handle this.

**Comment by SpotlightKid** [comment]
That's also something I would like to see (rather sooner than later ;)).

**Comment by jkroll20** [comment]
Me too. Some plugins have separate controls for right & left channels which are really cumbersome to control with a single CC right now.

**Comment by falkTX** [comment]
hmm the carla GUI allows to have the same CC mapped to multiple parameters.
I'm not sure why I thought about limiting this, perhaps because we could forgot we mapped some parameters?
If an action for "clear all mappings" is added,  I think carla can do what you request just fine then.
