### ISSUE TITLE
Carla doesn't restore nodes arrangement and connections

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#346]
I'm trying to prepare a live set with Carla, but looks like my patch doesn't save or load properly.

Here's the carxp file:

http://pastebin.com/J1PMUbMU

And this is how it's supposed to look like:

![carla](https://cloud.githubusercontent.com/assets/491704/12372298/6a1968b0-bc51-11e5-91c9-baae45cb77ec.png)

However when I load it it looks like this:

![carla2](https://cloud.githubusercontent.com/assets/491704/12372305/a4a834fc-bc51-11e5-8a38-aa4e2f5b619b.png)

**Comment by falkTX** [comment]
are you using a session manager like ladish or NSM?

**Comment by unfa** [comment]
I'm not. I only use Carla to handle the connections.

I've written a Bash script to start linuxsampler, and setup MIDI bridge first, then run Carla to finalize the project. Here's the script:

  #! /bin/bash

  # define the root path of the set
  path="/unfa/Projects/SmallHint/Live/Sets/Live-01/"

  # kill all procesess to reset the studio if something is already running
  pkill -9 -f a2jmidid
  pkill -9 qsampler &
  pkill -9 -f /usr/bin/jack_mixer &
  pkill -9 -f Carla.carxp
	  
  # enable ALSA to JACK MIDI bridge with hardware ports export to provide MIDI controller input ports
  a2jmidid -e &

  # run Qsampler
  qsampler $path"Qsampler.lscp" &

  # run jack_mixer for master volume control for fader C9
  jack_mixer --no-lash -c $path"jack_mixer" &

  # set buffer size to 256
  jack_bufsize 256 &

  # wait for Qsampler to expose ports
  echo "Waiting for Qsampler to expose ports"
  zenity --info --title="Continue?" --text="Ready to run Carla?"

  # run Carla to load plugins and patch everything
  carla $path"Carla.carxp" &

**Comment by unfa** [comment]
Ok, I've got my system back from backup. Carla loads arrangement and connections fine now.

Here's the Carla version:

				$ carla -v
				Using Carla version 1.9.6 (2.0-beta4)
				Python version: 3.4.3
				Qt version:     4.8.6
				PyQt version:   4.10.4
				Binary dir:     /usr/lib/carla
				Resources dir:  /usr/share/carla/resources

**Comment by falkTX** [comment]
ok found the issue.
your project file has all the connections with a '-01' suffix.

you can even see in your first post, the client names of the top screenshot don't match the bottom ones.
simply open the project file and remove all '-01' strings.

not sure why the jack client names get like that, perhaps an old carla instance didn't stop properly?
if that still happens it's a different bug anyway.

**Comment by unfa** [comment]
Ok. I see. Yes. Carla crashes on my end occasionally and this might have brought the bad naming in.

I did what you said and now it loads fine, but still, the nodes are not arranged as I left them.

I guess I should make another issue for that anyway.

**Comment by unfa** [comment]
I added this line to my script just before running Carla and the problem is gone for good:

    sed 's/-01//g' $path"Carla.carxp"
