### ISSUE TITLE
Carla floats plugin windows whether I want it or not

### ISSUE THREAD

**Issue by wolftune** [falkTX/Carla#348]
Carla shows a plugin UI window always over the Carla screen so I cannot make it go behind. It doesn't use the float-on-top option that I could turn off in KDE. Rather, it keeps the window on top even when that is off.

This is frustrating as I can't keep a UI open and also see the main Carla screen.

Note: the float is not system-wide, just within the Carla application.

**Comment by falkTX** [comment]
This is actually the behaviour the I prefer myself.
I need to make it an option I guess. Coming soon.
