### ISSUE TITLE
Not finding PyQt?

### ISSUE THREAD

**Issue by DeathHammer000** [falkTX/Carla#356]
I'm trying to get LMMS to compile by installing Carla properly (instead of logging in as root to copy the files) and then see if the missing files turn up (see: https://github.com/LMMS/lmms/issues/2543). However, I've run into a problem involving compiling Carla itself.

I get this just by running sudo make install:

```
# Install backend libs
install -m 644 \
	bin/libcarla_*.* \
	/usr/local/lib/carla/
install: cannot stat ‘bin/libcarla_*.*’: No such file or directory
```

I checked the dependencies and using make featuress and it said that PyQt wasn't there. I used APT repos and even used alien on an RPM package but it still said:

```
Front-End:   NO  [Missing PyQt]

```

Can this be fixed? I used devel and non-devel packages for PyQt and Python3-PyQt.

**Comment by falkTX** [comment]
Are you trying to install without building first?

You're likely missing something there anyway.
In debian based systems the pyqt devel stuff can be installed with:
```sudo apt-get install pyqt4-dev-tools libqt4-dev```

**Comment by DeathHammer000** [comment]
Thanks! I just wasn't sure what to do. (So that I can prevent this in future, is there a way to get make to automatically install dependencies? I also had to run make before sudo make install...)

**Comment by falkTX** [comment]
The dependencies are described in the INSTALL file.

And yes, you need to actually build the code before you can install it.
That's just how 90% of software builds from source works.

If you're using a Debian based distro, why not simply use the kxstudio repositories?
The latest carla and lmms are already there, no need to compile anything.

**Comment by DeathHammer000** [comment]
I found those and used those. Thanks!

**Comment by falkTX** [comment]
Assuming this is fixed and closing report.
