### ISSUE TITLE
What do the rack LEDs mean?

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#357]
![leds](https://cloud.githubusercontent.com/assets/491704/12949634/3bcfa020-d009-11e5-9b00-e00cef54a1ca.png)

I don't know what all these indicators mean. The second one from the left shows if there's a MIDI signal received, I can see that light up when I press a key, but the rest?

**Comment by falkTX** [comment]
in order, is:
parameter changes | midi received | audio input | audio output

**Comment by unfa** [comment]
Thank you!
