### ISSUE TITLE
Calf Wavetable with a custom skin crashes Carla

### ISSUE THREAD

**Issue by Barbouze** [falkTX/Carla#358]
Hi!

I recently discovered that I could change the Calf plugins skins with the standalone Calf host (in the file/preferences menu) and that it was applied system wide. I went for the midnight one as it provides better visibility but this bug occurs with any skin. As soon as you add Calf wavetable synth in Carla, if you're not using the default skin then Carla will close instantly.
One interesting thing is that sometime, if you add another Calf plugin like Organ before adding Wavetable, the later one will work but Carla may crash when removing it.

Feel free to ask for logs or further tests if needed :)
Barbouze

**Comment by falkTX** [comment]
calf wavetable is an experimental, unfinished plugin.
don't use it.

**Comment by Barbouze** [comment]
Oops, I forgot about that, sorry :/
