### ISSUE TITLE
Carla crashes when Ingen plugin exposes new input port

### ISSUE THREAD

**Issue by jkroll20** [falkTX/Carla#362]
I ran into the following problem with Carla. Thanks for your great work and let me know if I can help.

To reproduce: Using Carla version 1.9.6 (2.0-beta4):
- add one of the ingen templates
- open ingen gui
- create any object, such as 'internal->controller'
- right-click on any of the object's inputs
- click Expose 
- expected: new port shows up in Carla
- result: carla crashes

**Comment by falkTX** [comment]
have you tried it in other hosts?
ie, does it crash on jalv?
because if it does, it might be a crash on ingen.

LV2 does not have dynamic ports, so ingen should not be allowing you to add more ports on the fly.

**Comment by jkroll20** [comment]
Ok, so I was looking for another LV2 host to try:
It seems JOST doesn't support LV2 right?
Next I tried ardour4 which crashes with SIGSEGV on creating a new session. ardour2 crashes before showing any GUI. Not sure what's going on there.

Next I tried jalv.gtk which worked. Tried to expose a new port - jalv crashed with SIGSEGV. So you're probably right; the lv2 version of ingen shouldn't allow to create new ports at runtime. If there isn't a mechanism to report new ports to the host (?) it shouldn't give the user the option to do it...

**Comment by falkTX** [comment]
correct, lv2 does not allow that right now.
please report a bug against ingen.

**Comment by falkTX** [comment]
Yes.
Trying it now, I see that ingen gui crashes when being opened by carla...

**Comment by SynthaClaus** [comment]
It either crashes or opens a white empty window in Ubuntu 18.04, Mint 18/19 and Neon here. I thought it wasn't supposed to work, but it would be awesome if it does :).

**Comment by falkTX** [comment]
I am closing this ticket since ingen keeps changing its behaviour and even core libraries and other things.
Until ingen has a stable release, there is no point on open tickets for its use, in my opinion.
