### ISSUE TITLE
Problem loading some ImageLine VSTs

### ISSUE THREAD

**Issue by goofymongol** [falkTX/Carla#364]
Hello
I use FLstudio bit it's not compactible with carla so I'll probably ditch it. But I love slicex and Sytrus so I tried loading my vst(i)s. And a lot of them work like drumaxx and GMS but oddly my two facourite ones don't want to show up in the plugin selecta

**Comment by falkTX** [comment]
The FLStudio VSTi works just fine in carla.
And the other IL plugins do too afaik.
(I know Sytrus and Harmless work, I've tested them myself)

Note that IL plugins need the WINEPREFIX variable to be correct.
You can't install them on a prefix and run carla/wine on another.

**Comment by goofymongol** [comment]
Flstudio VSTi Multi is what I needed thx!! Time to make FAT BEATS.

Only I was wondering can I set a BPM inside carla and have a master play button? So I could play multiple instances of fl and have all my plugins playing in time as slaves of carla for live sets?
ay button? So I could play multiple instances of fl and have all my plugins playing in time as slaves of carla for live sets?

I just reread my post and it wasn' clear at all.
Carla's plugin selector just doesn't want to read the plugin for some reason and it doesn't show up in the add new menu when I search for them. For the rest everything runs ridiculously well.

Just donated 20 euro for your hard work and personal help :) Don't know where you find the time to create music with all this coding. Also I  would like to help out with KxStudio, but don't know where you need help I only did small & half assed python projects (used to be into computer hackings).

**Comment by falkTX** [comment]
if you're using carla with the jack driver, then any application that supports jack transport can trigger playback and control the BPM.
carla currently doesn't export BBT info alone, but it's planned.

so for now you can use klick, like this:
```
klick -T 120
```
then the VSTs should get time info when you press play in carla.
if this doesn't work, let me know (klick might not be accurate 100% of the time)


regarding the plugins not showing up, please run this and report the output:
```
wine /usr/lib/carla/carla-discovery-win32.exe vst /path/to/vst.dll
```
Replace '/path/to/vst.dll' to wherever the unloadable plugin is.

**Comment by goofymongol** [comment]
~$ wine /usr/lib/carla/carla-discovery-win32.exe vst '/home/braakpand/.wine/drive_c/Slicex/Slicex.dll'
fixme:dwmapi:DwmIsCompositionEnabled 0x9ef634
fixme:dwmapi:DwmIsCompositionEnabled 0x9ef634

carla-discovery::error::Not a VST plugin


same with sytrus weird maybe because it's a crack? Tried win64.exe this gave no output at all

Also is there a way I can use my shortcuts like ctrl +a and shift + arrows inside FL because now it thinks I want to control carla while I'm actually working inside fl

**Comment by falkTX** [comment]
Some shortcuts don't work on the FLStudio VST version.
I think it's an 'official' limitation.

> same with sytrus weird maybe because it's a crack?
and with that we stop here.
please stop using cracks! I won't help you in any way for those.

**Comment by faseh329** [comment]
Download 🟢Link👉👉[FL Studio 2025 Activated Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢

**Comment by faseh329** [comment]
Download 🟢Link👉👉[FL Studio 2025 Key Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢

**Comment by faseh329** [comment]
Download 🟢Link👉👉[FL Studio Activated Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢

**Comment by faseh329** [comment]
Download 🟢Link👉👉[FL Studio 2025 Crack Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢

**Comment by faseh329** [comment]
Download 🟢Link👉👉[FL Studio 2025 Reg Key Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢

**Comment by faseh329** [comment]
Download 🟢Link👉👉[FL Studio Keygen Activated Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢

**Comment by faseh329** [comment]
Download 🟢Link👉👉[FL Studio Serial Key Activated Version](https://tinyurl.com/fl-studio-2025-activated)🟢🟢
