### ISSUE TITLE
Allow to set osc port via plugin parameter

### ISSUE THREAD

**Issue by falkTX** [falkTX/Carla#366]
Right now the only way to set a specific OSC port is using an environment variable.
This is not optimal and doesn't even work if loading more than 1 carla plugin.

A way to make it work for the plugin version is through a plugin parameter.
Need to mark it as non-automable/expensive, but still allow it to be changed during runtime.

It might be a good idea to add a new CLI argument for this too.

**Comment by Rippert** [comment]
I was just looking for a way to do this with multiple Carla Rack plugins inside a master Carla host. Your last post here is pretty old, but I just wanted to say I would love to see this in the 2.0 final release (which looks like it's getting close with the RC releases).

**Comment by falkTX** [comment]
OSC settings have been added to carla, see develop branch
I decided against having carla as plugin exposing these OSC ports, as things can get messy there, specially once carla exposes plugin parameters to the host.
