### ISSUE TITLE
Plugins not drawing GUI on a system using bumblebee (nVidia Optimus technology)

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#370]
![opengl](https://cloud.githubusercontent.com/assets/491704/13403053/67325410-df13-11e5-9687-051b31405217.png)

I believe this used to work well. I run Carla through optirun or primusrun and plugins like MVerb that use OpenGL graphics for drawing GUI were displayed correctly. Some time ago (2 months) I noticed it's not working.

Right now even though I use optirun or primusrun, Carla plugins behave like I don't. Those that use OpenGL (GPU rendering) are drawing black windows or some messed up patterns looking like random bits of binary data from the memory displayed as image.

Plugin packs or units affected:

**x42** - the great pack of audio analyzers from Robin Gareus
**DISTRHO**  - various different plugins like mVerb
**setBfree** - a fantastic tonewheel organ emulator

**Comment by falkTX** [comment]
this is not an issue with carla.
those plugin UIs use OpenGL for drawing stuff, so you need to have that working first.
there's nothing I can do on carla's side to fix this.
