### ISSUE TITLE
Build problem on fedora 23

### ISSUE THREAD

**Issue by ycollet** [falkTX/Carla#375]
I uses fedora 23 64 bits to compile carla from git repo.
With the current master (dd2c61377073a889d80bc9c998fe03b91cbb0292), the build fails. It gets stuck while compiling zynaddsubfx:

make[1]: Entering directory '/home/collette/repositories/Carla/source/plugin'
Linking carla-lv2-export
Generating LV2 ttl data
Generating data for LFO...
Generating data for MIDI Channel Filter...
Generating data for MIDI Gain...
Generating data for MIDI Join...
Generating data for MIDI Split...
Generating data for MIDI Through...
Generating data for MIDI Transpose...
Generating data for MIDI Pattern...
Generating data for Carla-Rack...
Generating data for Carla-Patchbay...
Generating data for Carla-Patchbay (sidechain)...
Generating data for Carla-Patchbay (16chan)...
Generating data for Carla-Patchbay (32chan)...
Generating data for Big Meter...
Generating data for Notes...
Generating data for ZynAlienWah...
Generating data for ZynChorus...
Generating data for ZynDistortion...
Generating data for ZynDynamicFilter...
Generating data for ZynEcho...
Generating data for ZynPhaser...
Generating data for ZynReverb...
Generating data for ZynAddSubFX...
lo server running on 17975

It stays stuck here and never leave this message.

**Comment by falkTX** [comment]
Did it used to build ok before?

Are you building this on some system with limited network? (like a build server)

**Comment by falkTX** [comment]
I can confirm this issue.
zynaddsubfx is hanging then trying to close. investigating...

**Comment by ycollet** [comment]
Thanks a lot.

YC

**Comment by ycollet** [comment]
Works fine now.
