### ISSUE TITLE
Black GUI on Arch Arm

### ISSUE THREAD

**Issue by mavmala** [falkTX/Carla#376]
I build Carla from git repo on arch arm, when starting carla I get a warning and  carla opens with a completely black window: 

[a0@alarm ~]$ carla
LRDF Support not available (LADSPA-RDF will be disabled)
Using "carla" theme
Carla 1.9.6 (2.0-beta4) started, status:
  Python version: 3.5.1
  Qt version:     4.8.7
  PyQt version:   4.11.4
  Binary dir:     /usr/local/lib/carla
  Resources dir:  /usr/local/share/carla/resources
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libjack.so.0 loaded sucessfully!

The same happens with PyQT5.. any suggestions to fix the black window?

**Comment by falkTX** [comment]
is carla gui completely black, or just the patchbay canvas?
do other qt apps works?

you can try this:
`env QT_GRAPHICSSYSTEM=raster carla`

**Comment by mavmala** [comment]
It is completely black, only other apps installed are jalv and guitarix, those work. Using:
`env QT_GRAPHICSSYSTEM=raster carla` does not change it, still completely black.

**Comment by falkTX** [comment]
Try this:
`env QT_GRAPHICSSYSTEM=native carla`

although I expect it to not work either.

did you try jalv.qt? maybe qtractor?

**Comment by mavmala** [comment]
jalv.qt works, `env QT_GRAPHICSSYSTEM=native carla` gives the same black result.

**Comment by mavmala** [comment]
After a new install and updates + some modifications carla now works as expected!
