### ISSUE TITLE
Carla assertion failure:  "eventOut != nullptr" in file CarlaEngineJack.cpp, line 1608

### ISSUE THREAD

**Issue by jofemodo** [falkTX/Carla#377]
When i fork a carla-patchbay process from another process that is a Jack Client too (MIDI only), then i get this infinite sequence:

```
jack_port_get_buffer called with an incorrect port 0
Carla assertion failure: "eventOut != nullptr" in file CarlaEngineJack.cpp, line 1608
```

Carla creates the MIDI input port, but not the MIDI output port. Audio processing is not working.

There are not other ports called "eventOut", so, as far as i know, the port name is unique.
If i "remove" the MIDI input port from the parent, everything works fine.

**Platform: Raspberry Pi + Debian Jessie**

**Comment by falkTX** [comment]
forking processes is not a good idea for applications with jack clients.
(related: https://github.com/Ardour/ardour/blob/master/libs/vfork/README)

how are you forking the process?
if you're using C/C++ code, you could try vfork which I think won't have these issues.

**Comment by jofemodo** [comment]
I'm forking from python3:
			
```
command=("/usr/local/bin/carla-patchbay", patch_path)
command_env=os.environ.copy()
command_env['DISPLAY']=os.environ.get('ZYNTHIANX')
proc=Popen(command,shell=False,bufsize=1,universal_newlines=True,stdin=PIPE,stdout=PIPE,stderr=STDOUT,env=command_env)
```

**Comment by falkTX** [comment]
hm, that is tricky.

if I understood you correctly, your main process already has a jack client right?

have you tried using the carla's python API?
it's a bit more complex, but it doesn't require forking.

**Comment by falkTX** [comment]
oh, have you tried the lv2 plugin version yet?

if you have an lv2 host in zynthian you can load carla as plugin, then use lv2 presets to save/restore state.
it's easy to convert a raw carla project file into a carla-plugin lv2 preset, it just needs a few lines for the lv2 syntax.

**Comment by jofemodo** [comment]
Exactly. The main process has already a jack client ...
In the near future (next months), i would like to integrate Carla vía API (or LV2, i will study this way!!), but currently i was doing a quick&dirty integration. Only a quick way of launching a carla patch and connecting it to zynthian.
Anyway, perhaps it is time to explore the API or LV2 way ... ;-)

**Comment by falkTX** [comment]
If you're going to try the python API, the file that you need is carla_backend.py
https://github.com/falkTX/Carla/blob/master/source/carla_backend.py

The CarlaHost.h documents the API
https://github.com/falkTX/Carla/blob/master/source/backend/CarlaHost.h#L45

basically you do something like this:
```
from carla_backend import *
carla = CarlaHostDLL("/path/to/libcarla_standalone2.so")
carla.engine_init("JACK", "carla-zynthian")
carla.load_project("/abspath/to/project.carxp")
# call idle at regular intervals to dispatch osc and gui events
carla.engine_idle()
# when done:
carla.engine_close()
```

Note that the main Carla application uses this API too, so anything that the main carla can do you'll be able to do as well.
There are some caveats:
- all calls must be made within the same thread (usually the 'main' one)
- there's an engine callback for receiving events from carla, but those can happen in any thread. if you decide to enable this callback make sure to put a lock or postpone the messages to your main thread.

**Comment by jofemodo** [comment]
OK! I will try this way. Thanks for the advice ...

**Comment by jofemodo** [comment]
I've found a quick&dirty way ... really dirty, i know, but it will be enough while implementing a nice solution vía API or LV2. Currently, i don't need the carla-patchbay MIDI output, so i removed it ;-)

```
diff --git a/source/backend/engine/CarlaEngineJack.cpp b/source/backend/engine/CarlaEngineJack.cpp
index 8f39427..c7f137a 100644
--- a/source/backend/engine/CarlaEngineJack.cpp
+++ b/source/backend/engine/CarlaEngineJack.cpp
@@ -1596,7 +1596,8 @@ protected:
             float* const audioOut1 = (float*)jackbridge_port_get_buffer(fRackPorts[kRackPortAudioOut1], nframes);
             float* const audioOut2 = (float*)jackbridge_port_get_buffer(fRackPorts[kRackPortAudioOut2], nframes);
             void* const  eventIn   = jackbridge_port_get_buffer(fRackPorts[kRackPortEventIn],  nframes);
-            void* const  eventOut  = jackbridge_port_get_buffer(fRackPorts[kRackPortEventOut], nframes);
+            void* const eventOut   = NULL;
+            //void* const  eventOut  = jackbridge_port_get_buffer(fRackPorts[kRackPortEventOut], nframes);
 
 #if 1
             // assert buffers
@@ -1605,7 +1606,7 @@ protected:
             CARLA_SAFE_ASSERT(audioOut1 != nullptr);
             CARLA_SAFE_ASSERT(audioOut2 != nullptr);
             CARLA_SAFE_ASSERT(eventIn != nullptr);
-            CARLA_SAFE_ASSERT(eventOut != nullptr);
+            //CARLA_SAFE_ASSERT(eventOut != nullptr);
 #endif
 
             // create audio buffers
@@ -1645,6 +1646,7 @@ protected:
                 pData->graph.process(pData, inBuf, outBuf, nframes);
 
             // output control
+            if (0)
             {
                 jackbridge_midi_clear_buffer(eventOut);
```

I've been trying the API way and it works. Easy. The problem here is that:

- without the carla-patchbay "jail", i need to manage the complexity of autoconnecting the carla patch with keyboards and controllers.
- i really like the posibility of opening the carla-patchbay GUI in a remote X11 display 

So i have some work to do ... meanwhile, this dirty patch will do the trick ;-)

**Comment by falkTX** [comment]
you can still use the patchbay mode.
as I said, anything carla does you can do as well. carla uses that API you know...

add this line before carla.engine_init():
`carla.set_engine_option(ENGINE_OPTION_PROCESS_MODE, ENGINE_PROCESS_MODE_PATCHBAY)`

**Comment by jofemodo** [comment]
OK. I understand ...
Then ... could i open the Carla GUI as a separate process and connect it to my carla instance?

**Comment by falkTX** [comment]
in theory yes, but since I never needed it that feature is not implemented.

there's other ways to do it though.
carla-control can show the plugin stuff, and loading carla itself as a plugin allows to show its native interface. BUT:
carla-control doesn't show the patchbay or native plugin guis.
carla as plugin does not export plugin parameters or presets.

**Comment by falkTX** [comment]
I'm curious what's possible to do here.
Please try the latest change and see if it's enough for you.
Or if this bug is no longer applicable (you moved to mod-host?) then please close it, thanks.

**Comment by jofemodo** [comment]
Hi falkTX, currently i moved to mod-host+mod-gui.
Thanks a lot!
