### ISSUE TITLE
CALF plugins don't display levels > 0dB

### ISSUE THREAD

**Issue by suedwestlicht** [falkTX/Carla#383]
Although I raise input volume to large values CALF plugins don't show values > 0dB. I attach one screenshot with CALF limiter in Carla and one with CALF limiter in CALF plugin pack.

![carla](https://cloud.githubusercontent.com/assets/5550538/14042525/f4a9800a-f27a-11e5-80f7-51f2340f4ac9.png)

![calf](https://cloud.githubusercontent.com/assets/5550538/14042557/40f13b10-f27b-11e5-8a43-4bff7eb6f9c1.png)

**Comment by SpotlightKid** [comment]
Digital signals usually use the the dbFS (db Full Scale) unit. As the name implies 0dB is the maximum sample value, so signal can not have a higher level than 0dB (or if they do, they are clipped, if measures to protect against this are employed).

**Comment by suedwestlicht** [comment]
As far as I understand and I experience JACK can handle values louder than 0 dB perfectly. Only in the last stage (mastering) I make sure that the peaks are below 0 dB. That's not the problem that I reported. See the first screenshot. The limiter is working with heavy attenuation. That means that it has much more than 0 dB in its input, see Input Gain as well.
But we have a display problem here: it doesn't show the +dBs in red numbers right besides the input meter. It shows 0.00 and that's not true.

If I use the same plugin in the CALF plugin host then you see the red numbers showing 12.03 and 15.87 dB.

So Carla behaves differently. Falktx supposes that the CALF plugins have some issues in the TTL files but he asked me to write a bug report.

**Comment by falkTX** [comment]
likely related to lv2 strictBounds.
either calf is mis reporting or carla doing it wrong.
