### ISSUE TITLE
Carla either hangs or doesn't load all plugins

### ISSUE THREAD

**Issue by oswald2** [falkTX/Carla#385]
I got an update of Carla through the KxStudio repos to carla-git 2:1.9.5~git20160329.3 (reported from synaptic) and now there are several effects:

- On  loading it as a LV2 in Ardour blocks Ardour but only sometimes

- if it loads, it doesn't load some plugins (e.g. TSE 808, LePou), though it sometimes does it

- This is not a problem of Ardour, I work since a few months on the same Ardour version and had no problems with the Carla/Ardour combi until now

- The standalone Carla application behaves the same

The messages from Ardour while loading a plugin set in Carla are:
/usr/lib/lv2/carla.lv2/carla-bridge-win32.exe "VST2" "/home/oswald/lmms/vst/TSE_808_2.0.dll" """" 2021143603
CarlaPluginBridgeThread::run() - bridge refused to close, force kill now
[Thread 0x7fff6d490700 (LWP 6295) exited]
Failed to load a plugin, error was:
Timeout while waiting for a response from plugin-bridge
(or the plugin crashed on initialization?)
Plugin UI requires a feature that is not supported:
http://lv2plug.in/ns/ext/atom
Plugin UI requires a feature that is not supported:
http://lv2plug.in/ns/ext/options
Will use UI-Bridge, binary: "/usr/lib/lv2/carla.lv2/carla-bridge-lv2-gtk2"
Carla Server Info:
sizeof(BridgeRtClientData): 6360
sizeof(BridgeNonRtClientData): 16400
sizeof(BridgeNonRtServerData): 65552
[New Thread 0x7fff6d490700 (LWP 6332)]

**Comment by falkTX** [comment]
This should be fixed now, please confirm.

**Comment by oswald2** [comment]
Yup, I can confirm that it works now again. Thanks a lot!

**Comment by falkTX** [comment]
cool, thanks for confirming.
