### ISSUE TITLE
Carla-bridge64 crash when trying to save 

### ISSUE THREAD

**Issue by daeavelwyn** [falkTX/Carla#386]
Hi,
To reproduce : 
1- open carla
2- add kontakt instance (64bit/16out)
3- add instruments into kontakt
4- click save
=> got a carla-bridge 64 crash

Carla seems to save the carxp file, but when I try to load, it just load kontakt without the instruments i've previously saved loaded in kontakt.

I've tried both "run plpugin in bridge mode when possible". once with this option (first backtrace) and once without (second one). Not sure it has any influence, but in case of....

I attach the backtrace.
[backtrace_carla-save-crash.txt](https://github.com/falkTX/Carla/files/232983/backtrace_carla-save-crash.txt)
[backtrace_carla-save-crash02.txt](https://github.com/falkTX/Carla/files/232984/backtrace_carla-save-crash02.txt)

**Comment by daeavelwyn** [comment]
Ok, so, futher investigation seems to show that it's a path issue.
1-In fact I create *.nkm (kontakt instrument set) file into reaper first.
2-Then I load carla and import thos nkm file into kontakt (whish is itself into carla).
3- carla-bridge-64 crash

BUT

1- open carla
2- insert kontakt
3- add instrument
4-click save or save as...
5- either use an exsiting file (overwrite) or create a new one
=> carla-bridge-64  crash

I put the wine output as an attachement
[backtrace_carla-save-crash03.txt](https://github.com/falkTX/Carla/files/233527/backtrace_carla-save-crash03.txt)

**Comment by falkTX** [comment]
@daeavelwyn can you retry this against the latest version please?
would save me quite some time

**Comment by daeavelwyn** [comment]
@falkTX : Will try ASAP but i'm really busy during september !

**Comment by falkTX** [comment]
closing this issue as I assume it works now. if not, feel free to reopen
