### ISSUE TITLE
Calf plugins don't display graphs

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#389]
![carla no calf graphs](https://cloud.githubusercontent.com/assets/491704/15098055/d822bb3e-1531-11e6-9633-6dce2501ebf2.png)

For some reason Calf plugins show no graphs inside their GUI.
It looks this way since I remember.

It's not a big problem, as the DSP works as expected, but programming the plugins is a bit difficult.

**Comment by falkTX** [comment]
You need to disable UI bridges if you want those graphs to appear.
But then calf plugins might randomly crash carla on close.

**Comment by unfa** [comment]
I tried it but it didn't work for me.

![carla no calf graphs not bridged](https://cloud.githubusercontent.com/assets/491704/15123427/fd3318d6-1623-11e6-8b6a-b928af6eea5b.png)

**Comment by unfa** [comment]
Update: some next Carla instance after the initial restart after the UI bridging was switched off seems to display graphs in most of the plugins - Only Calf Analyzer doesn't draw all stuff as expected.

![carla no calf graphs not bridged some](https://cloud.githubusercontent.com/assets/491704/15124295/bef9ee56-1627-11e6-8024-498e4dcb1b76.png)

**Comment by unfa** [comment]
I've noticed that this one Calf Analyzer plugin is being run through a bridge, while all the rest run inside Carla. This happens every time I load the project.

Htop shows:

![calf](https://cloud.githubusercontent.com/assets/491704/15124808/0168e312-162a-11e6-806e-e02144f687b7.png)

**Comment by falkTX** [comment]
Seems like a bug in the bridges, calf-analyzer runs as bridge because it always needs instance-access.
When running as bridge the UIs don't need to be bridged as well (erm, double bridged...)

**Comment by unfa** [comment]
I've filled an issue about this in Carla Git also:
https://github.com/calf-studio-gear/calf/issues/109

Maybe a cooperation could help fixing this problem.

**Comment by falkTX** [comment]
The calf analyzer case is handled in https://github.com/calf-studio-gear/calf/pull/113.
The reason it runs as bridge is to make sure it doesn't crash carla, as it (should) require instance-access to run.
The same is true for ir.lv2 (there's a special hardcoded case for these 2 plugins).

The rest is working as intended, those fancy graphs are optional and I'm glad so.
Users can disable the UI bridges to get them back, and risk some small stability.
