### ISSUE TITLE
Multithreaded operation of a single plugin?

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#392]
Is it possible to split the CPU usage of a single plugin run inside Carla among several CPU cores?

I guess it'd require the plugin to implement this feature, but is anything preventing that from happening?

**Comment by falkTX** [comment]
That's just impossible.
If it's about multiple plugins though, that's a different story..

**Comment by unfa** [comment]
So I guess the best strategy is to separate the instruments as much as possible among multiple plugin instances to make it multi-threadable by Carla, right?

**Comment by falkTX** [comment]
FYI the only way to get multi-threaded plugin processing in carla right now is using jack2 with multi-client mode.
