### ISSUE TITLE
Can't re-open KlangFalter Plugin correctly

### ISSUE THREAD

**Issue by Houston4444** [falkTX/Carla#402]
This is still the same bug as here : https://github.com/HiFi-LoFi/KlangFalter/issues/7 . But it's quite annoying for me and I detect something, I really think it comes from carla because this bug now appears  on carla only.

The bug: launch carla, add Klangfalter (LV2 or VST, same problem), save, reload saved file. 

KlangFalter'gui now looks like that:
![klangfalter_buggy1](https://cloud.githubusercontent.com/assets/3808689/15506067/5e2e55d0-21c6-11e6-95c3-33e97cdd52b2.png)

Changes does nothing (except changing name of loaded file) and plugin sounds as bypass.

No problem in ardour, qtractor or else.

Something interesting: If I add Klangfalter inside a Carla-Rack Plugin (or Carla-PatchBay) inside my carla project, I can save and reload my carxp file and it works fine.
However, if I launch carla-rack from command line, add klangfalter on this, save and reload, problem appears.

This bug appears ALWAYS. It doesn't seems to depend of distribution (it appears on my laptop with 14.04 and this computer with 15.10 ).

**Comment by falkTX** [comment]
I can confirm the issue.
Can also confirm that loading it inside a carla-rack plugin works around it.
Very strange...
