### ISSUE TITLE
LV2 plugins don't use MIDI channels above 1

### ISSUE THREAD

**Issue by FaTony** [falkTX/Carla#411]
I'm not sure what is the cause of this problem. I can use Carla GUI to send correct messages but external inpit goes to channels 1 only.

**Comment by tavasti** [comment]
I also noticed, that VST plugins generating midi don't work correctly. Regardless to which midi channel plugin tries to generate output, it ends up to midi channel 10.

I have seen this problem at lest with these:
http://www.vst4free.com/free_vst.php?pl ... or&id=1556 (outputs only when midi transport running)
http://www.thepiz.org/plugins/?p=midiChords

**Comment by falkTX** [comment]
I cannot reproduce the issue.
Loaded Harmony Rotator, set the channels to something other than 1, and got the correct output.

Please re-test this issue and let me know if still happens.
Probably has been fixed already.

**Comment by FaTony** [comment]
I think this is because of no raw program change handling. False alarm.
