### ISSUE TITLE
Drumgizmo does not open GUI anymore

### ISSUE THREAD

**Issue by oswald2** [falkTX/Carla#412]
Loading the Drumgizmo plugin and trying to open the GUI doesn't do so, so effectively the plugin can't be used.

Messages in the terminal (when trying to open the GUI):

Carla assertion failure: "fHandle != nullptr" in file CarlaBridgeUI-LV2.cpp, line 508
Carla assertion failure: "pData->pipeRecv != INVALID_PIPE_VALUE" in file ../utils/CarlaPipeUtils.cpp, line 1013

Other messages from Carla:

Carla 1.9.6 (2.0-beta4) started, status:
  Python version: 3.4.3
  Qt version:     4.8.6
  PyQt version:   4.10.4
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
libjack.so.0 loaded sucessfully!
Will use UI-Bridge, binary: "/usr/lib/carla/carla-bridge-lv2-x11"
Test UI extension http://lv2plug.in/ns/extensions/ui#resize
Test UI feature http://lv2plug.in/ns/extensions/ui#idleInterface
Test UI feature http://lv2plug.in/ns/extensions/ui#resize
Is resizable => true
ALL OK!

**Comment by falkTX** [comment]
The 'fHandle != nullptr' message tells me the UI failed to open.
What version of drumgizmo do you have?

**Comment by oswald2** [comment]
0.9.10. 

It works in Ardour and I can also load and use it in Muse, but because of the stereo track limitation there I would need Carla to patch it to only 2 channels.

**Comment by falkTX** [comment]
The UI is really refusing to open itself.
`carla-bridge-lv2-x11 http://drumgizmo.org/lv2 "http://drumgizmo.org/lv2#ui"`
this returns a null handle, so the UI failed to init.

And now I see it in the code. the UI now requires instance-access. :(

If we add this info to the ttl (as it should have been there in the first place..), it works again.
Find your drumgizmo.ttl and make the UI section looks like this:
```

<http://drumgizmo.org/lv2#ui>
    a ui:X11UI ;
    lv2:requiredFeature ui:resize ;
    lv2:extensionData ui:resize ;  
    lv2:requiredFeature ui:idleInterface ;
    lv2:extensionData ui:idleInterface ;
    lv2:requiredFeature <http://lv2plug.in/ns/ext/instance-access> ;
    ui:binary <drumgizmo.so> .
```
note the new instance-access near the end.

Will report to drumgizmo devs.
