### ISSUE TITLE
It's not possible to load presets of the amsynth plugin

### ISSUE THREAD

**Issue by ycollet** [falkTX/Carla#414]
I compiled amsynth from sources repo.
When I load amsynth into Carla, I am not able to load a preset into amsynth.
I can "load state" and I see all the presets name, but when I click on a preset, it's still the Derren one which is selected.
Carla is compiled from sources repo on Fedora 24.

**Comment by distrozapper** [comment]
I can confirm the issue under/with
ubuntu 14.04/KDE 64bit
Carla 1.9.6 (2.0-beta4) from package carla-git 2:1.9.5~git20160801.
amsynth LV2
Upon loading an amsynth state via its GUI, Carla reports assertion failures in terminal (last two lines):

Using "carla" theme
Carla 1.9.6 (2.0-beta4) started, status:
  Python version: 3.4.3
  Qt version:     4.8.6
  PyQt version:   4.10.4
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
libjack.so.0 loaded sucessfully!
Carla Server Info:
  sizeof(BridgeRtClientData):    6360
  sizeof(BridgeNonRtClientData): 16400
  sizeof(BridgeNonRtServerData): 65552
starting plugin bridge, command is:
/usr/lib/carla/carla-bridge-native "LV2" """" "http://code.google.com/p/amsynth/amsynth" 0
Carla Client Info:
  BufferSize: 1024
  SampleRate: 44100
  sizeof(BridgeRtClientData):    6360/6360
  sizeof(BridgeNonRtClientData): 16400/16400
  sizeof(BridgeNonRtServerData): 65552/65552
Will use UI-Bridge, binary: "/usr/lib/carla/carla-bridge-lv2-gtk2"
Carla Client Ready!
Carla assertion failure: "index < pData->midiprog.count" in file CarlaPluginBridge.cpp, line 1937
Carla assertion failure: "fExt.state != nullptr" in file ../backend/plugin/CarlaPluginLV2.cpp, line 1179

There is a similar issue reported earlier involving amsynth: #398

**Comment by falkTX** [comment]
Fixed in 38f697820c1534164bda7faf4f253d847abac0d1
