### ISSUE TITLE
The release of Carla (1.2.4) fails to build on Arch Linux with GCC 6.1.1

### ISSUE THREAD

**Issue by WoefulDerelict** [falkTX/Carla#415]
I've captured the complete output of Arch's makepkg here: https://gist.github.com/WoefulDerelict/cdfbfcea3a3a0d1dc1068d1bf31f855d

It is failing in a different way than the current code in master which has already been patched.

**Comment by falkTX** [comment]
should be fixed now in the 'stable' branch.
I don't really recommend using that though.
Go for carla-git instead.

**Comment by WoefulDerelict** [comment]
Thanks for your help with the patch. I've got it published in the AUR for users who want the older version. I look forward to migrating the carla package to the next beta version when that becomes available. Hopefully brave users will try carla-git.
