### ISSUE TITLE
Fails to start: argument 1 has unexpected type 'sip.voidptr'

### ISSUE THREAD

**Issue by rosslagerwall** [falkTX/Carla#417]
On Arch Linux, a freshly compiled carla from git with no existing config file fails to start:

```
$ source/carla
LRDF Support not available (LADSPA-RDF will be disabled)
Using "carla" theme
Carla 1.9.6 (2.0-beta4) started, status:
  Python version: 3.5.2
  Qt version:     5.7.0
  PyQt version:   5.7
  Binary dir:     /home/ross/Downloads/Carla/bin
  Resources dir:  /home/ross/Downloads/Carla/bin/resources
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "source/carla", line 52, in <module>
    gui = HostWindow(host, True)
  File "/home/ross/Downloads/Carla/source/carla_host.py", line 325, in __init__
    self.loadSettings(True)
  File "/home/ross/Downloads/Carla/source/carla_host.py", line 1309, in loadSettings
    self.restoreGeometry(settings.value("Geometry", b""))
TypeError: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'sip.voidptr'
```

If I replace the line with: `self.restoreGeometry(settings.value("Geometry", bytearray(b"")))` then it fails on the next line with a similar issue. This looks to me like a default value of `b""` is not handled correctly by pyqt5, but I'd be surprised if was the first person to notice this.

Output of `make features`:

```
$ make features
\033[36m---> Main features \033[0m
Front-End:  \033[32m YES \033[0m(Using Qt5)
LV2 plugin: \033[32m YES \033[0m
VST plugin: \033[32m YES \033[0m
OSC support:\033[32m YES \033[0m

\033[36m---> Engine drivers \033[0m
JACK:       \033[32m YES \033[0m
ALSA:       \033[32m YES \033[0m
PulseAudio: \033[32m YES \033[0m
CoreAudio:  \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m
ASIO:       \033[31m NO \033[0m \033[30;1m[Windows only]\033[0m
DirectSound:\033[31m NO \033[0m \033[30;1m[Windows only]\033[0m

\033[36m---> Plugin formats: \033[0m
Internal:\033[32m YES \033[0m
LADSPA:  \033[32m YES \033[0m
DSSI:    \033[32m YES \033[0m
LV2:     \033[32m YES \033[0m
VST:     \033[32m YES \033[0m(with UI)
VST3:    \033[31m NO \033[0m \033[30;1m[Windows and MacOS only]\033[0m
AU:      \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m

\033[36m---> LV2 UI toolkit support: \033[0m
External:\033[32m YES \033[0m(direct)
Gtk2:    \033[32m YES \033[0m(bridge)
Gtk3:    \033[32m YES \033[0m(bridge)
Qt4:     \033[32m YES \033[0m(bridge)
Qt5:     \033[32m YES \033[0m(bridge)
X11:     \033[32m YES \033[0m(direct+bridge)
Cocoa:   \033[31m NO \033[0m \033[30;1m[MacOS only]\033[0m
Windows: \033[31m NO \033[0m \033[30;1m[Windows only]\033[0m

\033[36m---> File formats: \033[0m
GIG:\033[32m YES \033[0m
SF2:\033[32m YES \033[0m
SFZ:\033[32m YES \033[0m

\033[36m---> Internal plugins: \033[0m
Carla-Patchbay: \033[32m YES \033[0m
Carla-Rack:     \033[32m YES \033[0m
DISTRHO Plugins:\033[32m YES \033[0m(with UI)
DISTRHO ProM:   \033[31m NO \033[0m (missing libprojectM)
ZynAddSubFX:    \033[31m NO \033[0m \033[33m[fftw3, mxml or zlib missing]\033[0m
```

Thanks for taking a look.

**Comment by Schmetzler** [comment]
bytearray(b"") solves the issue, but when I click on Add Plugin it just segfaults.

So I tried carla-database and it gave me:
Traceback (most recent call last):
  File "/usr/share/carla/carla_database.py", line 1846, in <module>
    gui = PluginDatabaseW(None, host)
  File "/usr/share/carla/carla_database.py", line 1284, in __init__
    self.loadSettings()
  File "/usr/share/carla/carla_database.py", line 1384, in loadSettings
    self.restoreGeometry(settings.value("PluginDatabase/Geometry", b""))
TypeError: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'sip.voidptr'

And there also replacing b"" with bytearray(b"") solves the issue... Maybe this is a problem with python3.6 since Arch-Linux-Repositories have the updated python version.

**Comment by Kubuxu** [comment]
Having the same issue after installing AUR package.

**Comment by falkTX** [comment]
I guess it's time to install archlinux in a VM.

**Comment by Kubuxu** [comment]
The fix referenced by @Schmetzler helped, it is two files in `/usr/share/carla/`.

**Comment by falkTX** [comment]
Installed archlinux, but cannot reproduce this.
There was another issue starting carla, fixed in master now.

Both Qt and PyQt are in version 5.7.1 here.

**Comment by Kubuxu** [comment]
The AUR package currently includes patch to fix the issue.

**Comment by Kubuxu** [comment]
Ok, it works fine now.

**Comment by falkTX** [comment]
Thanks for confirming.
Closing the bug now.

**Comment by badosu** [comment]
I can confirm that this happened today installing from AUR.

```
  Python version: 3.6.0
  Qt version:     5.7.1
  PyQt version:   5.7
```

Applying `sed -i 's/b""/bytearray(b"")/g' *.py` and `sed -i 's/b""/bytearray(b"")/g' */*.py` inside `/usr/share/carla` fixed for me, following @Schmetzler and @Kubuxu suggestions.

**Comment by falkTX** [comment]
Just get the updates to get PyQt 5.7.1 and it will not be an issue.

**Comment by badosu** [comment]
Hmm, I guess the problem is that I am using Manjaro then, thanks!

**Comment by falkTX** [comment]
Considering the bug is not present in PyQt 5.6 (that I use at home), or 5.7.1 (used now in arch), I believe the issue only happens on exactly 5.7.0.
So I'm led to think it was a regression, or something they (pyqt devs) changed and decided to revert back.
