### ISSUE TITLE
How is the standalone binary supposed to be called?

### ISSUE THREAD

**Issue by simonvanderveldt** [falkTX/Carla#419]
Hi Filipe,

First of all thanks a lot for the hard work on the Linux music creation landscape! It's great to see someone so dedicated creating these awesome projects! :)

I have a bit of a simple question: How is the standalone supposed to be called?
I'm asking because within LMMS there's a [check](https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L225) if `carla-standalone` exists, but when I build Carla from this repo from `master` I don't get such a binary or script.
Is LMMS's check out of data or am I missing something?

**Comment by falkTX** [comment]
carla-standalone is the name of the *pkg-config* file, not the script that starts carla.
Carla in LMMS runs as a plugin, the code is linked to LMMS (via libcarla_standalone2.so)

**Comment by simonvanderveldt** [comment]
Thanks for the quick response, just [figured this out](https://people.freedesktop.org/~dbn/pkg-config-guide.html#concepts) as well. Never expected a build tool to do these crazy kinds of metadata work :x

Anyway, I'm creating an ebuild for Gentoo for some of the KX Studio applications. What apparently happens is that everything is installed to `/usr/local` as a prefix and `/usr/local/lib/pkgconfig/` isn't part of the paths that pkg-config uses to check of the `.pc` file exists.

What I've done is override the [`PREFIX` variable in the Makefile](https://github.com/falkTX/Carla/blob/master/Makefile#L29) by running `make PREFIX="/usr"`, then everything is installed to `/usr` and works as expected. So I'll close this issue.
If I've done something crazy please let me know ;)
