### ISSUE TITLE
Zebra2 and Zebralette don't work

### ISSUE THREAD

**Issue by danboid** [falkTX/Carla#421]
I am running the latest Carla build (1.2.4) from the KX repos under Ubuntu Mate 16.04 x64.

The Linux native builds of Zebra2/Zebralette (4458) work fine for me under Ardour 5 but I've been unable to get either to work under Carla, even with "Run plugins in bridge mode' enabled. The Carla plugin chooser doesn't list Zebralette as an option at all, only Zebra2 is listed. If I load Zebra2 into Carla, however, I am unable to open its UI as its icon is greyed out.

**Comment by falkTX** [comment]
Don't use 'carla' package, use carla-git instead.
This has been fixed already on it.
