### ISSUE TITLE
add zoom setting for rack

### ISSUE THREAD

**Issue by wolftune** [falkTX/Carla#422]
like the patchbay has a zoom, give the rack a zoom control for viewing. Especially for high-res monitors this will be useful.

**Comment by falkTX** [comment]
the rack was not made thinking about this.
It won't be scalable anytime soon.

**Comment by falkTX** [comment]
I am closing this as wont-fix.
Carla is slowly supporting high-dpi, so we can just use that instead of a rack-specific zoom level.
