### ISSUE TITLE
USE_ZLIB is used in the code but not defined

### ISSUE THREAD

**Issue by simonvanderveldt** [falkTX/Carla#423]
`USE_ZLIB` is used in multiple places in Carla's own code but isn't set anywhere, it probably should be?

For a list of files that include it see this search https://github.com/falkTX/Carla/search?utf8=%E2%9C%93&q=use_zlib&type=Code

**Comment by falkTX** [comment]
Where did you saw that?

**Comment by simonvanderveldt** [comment]
> Where did you saw that?

I've added a link to the search that shows the relevant files.

**Comment by falkTX** [comment]
Yeah, that's completly fine and intentional.
It's how my unzipfx module works. It's only used for windows builds in this
carla repo.

**Comment by simonvanderveldt** [comment]
OK, but since `USE_ZLIB` is never set all the `if(n)defs` can be removed, right?
Just to be sure, it's not relevant at all for Linux?

**Comment by falkTX** [comment]
The code is a fork of zlib. I want to maintain the original stuff to make
it easier to get a patch out if needed.

**Comment by simonvanderveldt** [comment]
Ah, that makes sense :)
Thx for the quick answers!
