### ISSUE TITLE
Resources (sample libraries, sound files etc.) under NSM need to be linked or saved into session dir

### ISSUE THREAD

**Issue by diovudau** [falkTX/Carla#427]
To create portable sessions NSM recommends that all resource files like instrument samples (sf2, sfz etc.) or audio files should be saved into the session dir. 

One implementation is to create a symlink on load and then load the link directly, instead of the original file location. tar can resolve these links so tarring a session makes it portable.

**Comment by falkTX** [comment]
Implemented in the last few commits.
I tested with a few plugins, if you still find any issues please let me know.
