### ISSUE TITLE
Engine Core / Process Mode is not saved as NSM setting

### ISSUE THREAD

**Issue by hilbrichtsoftware** [falkTX/Carla#428]
Add Carla to NSM, set preferences -> engine core / process mode to "Continuous Rack". Save, close it.

Then add another Carla instance to the session and set the preference to "Single Client" (or multi client). Save, close it. 

The first instance, on restart, now is a single client. 

So it looks like this setting (and probably more settings?) is a user-wide parameter that is not used and saved in the session. 

Obviously such musically relevant settings and properties of Carla itself should be independent of the system and saved/restored with the session.

**Comment by falkTX** [comment]
This is intentional.
Use 'carla-rack' or 'carla-patchbay' if you want that specific mode.

I haven't made a 'carla-jack-single/multi' init script yet, but I can add one if needed.

**Comment by falkTX** [comment]
I consider this fixed in 3645cf789147562eb973c48743a19e01aa3a199e.
You now have carla-jack-single and carla-jack-multi which can be used in NSM to make sure the jack driver and process mode is the same everytime.
