### ISSUE TITLE
mouse wheel on knobs on slots

### ISSUE THREAD

**Issue by Houston4444** [falkTX/Carla#429]
hey.
I've made this modifications to enable mouseWheel on knobs of the plugin's custom skins.
The idea is to have a normal run with the mousewheel and a slow run with ctrl+mousewheel (invert from qdial default setting).
Parameters with ScalePoints are supported and only goes on supported values.

I had to sort the list of scalepoints sended to paramspinbox too because it works better this way (and it's fine to get them in the good order in edit window).

In attachment, there is a list of the 4 diff files, and the 4 files.

[diffs.tar.gz](https://github.com/falkTX/Carla/files/519563/diffs.tar.gz)

[sourceWheel.tar.gz](https://github.com/falkTX/Carla/files/519569/sourceWheel.tar.gz)

Now I think that a display of value would be welcome, even it would take a little much space on rack.
I think too that dragging on button should modify value according the y mouse position.
I could make easily that, what do you think about ?

Oww. Why number of parameters is limited to 8 ? rack minimum size could allow 11 parameters...

**Comment by Houston4444** [comment]
arrgg, sorry. I sent you the original python files, not the modified ones.
So, this is it:
[sourceWheel.tar.gz](https://github.com/falkTX/Carla/files/520418/sourceWheel.tar.gz)

**Comment by falkTX** [comment]
I don't think I'll accept this.
I want to rework that dial code to work as real knobs, like every other audio application or plugin does - ie, by having only up/down changing the value, and don't allow to skip from min to max so easily.
Also, this would be much much much better as a pull request...

The number of params in the rack isn't supposed to be limited.
I want it dynamic, but wasn't able to make it work properly before, so I hardcoded a kinda sane value.

**Comment by Houston4444** [comment]
I agree that we could not change so easily parameter from min to max, Or by doubleClick, as works knobs in GxAmplier plugin for example. So, I can't see why enable mouseWheel isn't a progress !!! Prevent dial to switch value by clicking is very easy.

That's a good new to know that number of params is'n't supposed to be limited, but dynamic.

**Comment by Houston4444** [comment]
So. This is a new version. Knobs behaves as almost plugin's knobs. 
Value change on mouseMove according to Y value of mouse pointer.
Mouse Wheel moves value, Ctrl+MouseWheel moves value slowly.
DoubleClick moves value exactly under mouse pointer (as Guitarix plugins, on Calf plugins double click reset value to default).

[sourceWheel.tar.gz](https://github.com/falkTX/Carla/files/521847/sourceWheel.tar.gz)


Sorry, I'll take a look on Pull Requests, If I understand, I have to create my own carla repo...

**Comment by falkTX** [comment]
Closing this since the PR handles it, forgot to do that before.
Will merge this and the patchbay groups after 2.2 release
