### ISSUE TITLE
Feature Request: set range for midi-cc parameters 

### ISSUE THREAD

**Issue by rghvdberg** [falkTX/Carla#431]
I would like to have the midi-cc bindings not affect the whole range of a parameter but just a percentage of this.

It's actually a request from someone else.
Here's the transcript of the chat about the subject:

> rghvdberg: You can load carla plug-in host. Which can host as much other plugin as you like. All parameters of all hosted plugins in carla can be assigned to a midi controller.
>  You can add midi controller as modulation lanes in a track.
> j.ruegg: That could work... can you set the amount of modulation that the  MIDI control will do?
> for example, just modulate the filter from layer 1 from 0% to 50%, but the filter from layer 2 from 30% to 70% or so

**Comment by falkTX** [comment]
Not sure when this was added, but it is present now.

![Screenshot_20210731_123928](https://user-images.githubusercontent.com/1334853/127738736-f238ffdb-5d34-41d5-aa18-ed7b801337cd.png)
