### ISSUE TITLE
Build script for Carla on "Standard" Ubuntu

### ISSUE THREAD

**Issue by draekko** [falkTX/Carla#436]
Just an FYI...

I recently had to set up an Ubuntu Studio (16.10 / Yakkety) box for a new Linux user who wanted only the default repos, so i ended up creating a build script for him to install Carla packages on it. I tested them on my own box with Standard Uubntu with the default Ubuntu Studio repos added.

https://github.com/draekko/Carla-on-Ubuntu

Figured it might be of interest to someone else out there.

**Comment by falkTX** [comment]
I dont think this ticket is relevant any longer.
linuxsampler is not used since 2.0 is officially out, plus the external plugins build are not recommended, at least in linux, since we can easily get them elsewhere.

your script is installing many things that are not needed btw

**Comment by draekko** [comment]
Indeed and i didn't get the notification and just noticed this. This was over 3 or 4 yrs old.
