### ISSUE TITLE
Carla crashes when controlled by midi and GUI displayed

### ISSUE THREAD

**Issue by Blindekinder** [falkTX/Carla#438]
When MIDI value is sent, Carla crashes immediately, only if plugin GUI is displayed.

**Comment by falkTX** [comment]
Which plugin are you using? Is it LV2, VST or other different version?
Which OS?

**Comment by Blindekinder** [comment]
Sorry, I made new tests and actually it's the only plugin crashing: it's Robin Gareus' Stereo Balance Control. I tried other LV2 before and it crashed, probably I forgot to remove ladish MIDI connection to Stereo Balance when testing with others. It crashes also with plugin on standalone mode.
Anyway, I run KXStudio from install CD, 14.04.
I think I'd better to write to gareus...

**Comment by falkTX** [comment]
I can reproduce the crash.
Seems to be on the plugin side though.
