### ISSUE TITLE
Carla for Windows: No log file

### ISSUE THREAD

**Issue by progwolff** [falkTX/Carla#439]
It would be great if there was a way to read the stdout of Carla running on Windows.
Currently it seems like the log file falls back to stdout, but as you distribute Carla as a Win32GUI application stdout is not accessible. 
I think you should either log to a file or distribute Carla as a Win32 (console) application (which does not prevent it from having a GUI).

The reason I ask is that I ported [Performer](http://github.com/progwolff/performer) to Windows and need the output of Carla for it to work correctly.

**Comment by falkTX** [comment]
Latest git has brought back the log tab (used to be in 1.x).
Made it work under windows, but only tested using wine.

Please try it this build when possible:
https://drive.google.com/open?id=0B_uWSrIHpVoGNGlhMW82TG9vREU

A simple test is to add a plugin and then click 'remove all'.
There should be some "blocked start ... blocked done" messages in the log.

btw, there's an environment variable you can set to make carla skip saving and restoring connections.

**Comment by progwolff** [comment]
Thanks, it's working in a virtual machine. The log is shown as expected, so a user can read it.
However, I need a way to read the log / stdout of Carla programmatically from an external application. See https://github.com/falkTX/Carla/issues/435#issuecomment-260203343 .

> btw, there's an environment variable you can set to make carla skip saving and restoring connections.
Thanks, I missed that.

**Comment by progwolff** [comment]
I see, you fixed this with https://github.com/falkTX/Carla/commit/a184b0af1fbc1e45dcfaaf5aaec7c62a84af6285 
But Carla_Debug.exe ist not contained within the latest release. Could you add it there? I struggle myself to set up a working mingw build system with all dependencies...

**Comment by falkTX** [comment]
It's on the latest release, not as separate binary but contained in the released one.
Rename the Carla.exe to Carla.zip and extract the contents, then replace the Carla.exe inside with the one on Debug folder.

I will need to investigate later what we can do to make this work.
At least it works on wine, so I know the existing code should be correct.
But need to figure out a way to make this work within cxfreeze and real Windows.

**Comment by progwolff** [comment]
This might help isolating the issue: 
Trying to unzip with `ark`:
```
ark.kerfuffle: Mimetype for filename extension ( "application/octet-stream" ) did not match mimetype for content ( "application/x-ms-dos-executable" ). Using content-based mimetype.
```

Trying to unzip with `unzip`:
```
warning [Carla.exe]:  309047 extra bytes at beginning or within zipfile
  (attempting to process anyway)

```

**Comment by falkTX** [comment]
expected. this is one of those 2-in-1 magic files :)
unzip works here, does it work for you too?

**Comment by progwolff** [comment]
Yes. 
I copied the files over to my virtual machine running Windows 10, replaced Carla.exe in C:\Users\...\AppData\Temp\Carla\ with the Debug exe. I'm receiving debug output as expected. Great!
