### ISSUE TITLE
Add option to auto-connect jack rack and patchbay clients

### ISSUE THREAD

**Issue by falkTX** [falkTX/Carla#442]

**Comment by SpotlightKid** [comment]
Maybe make this a per plugin-instance option? So in the settings window of each plugin, you could set port patterns (similar to [jack-matchmaker](https://github.com/SpotlightKid/jack-matchmaker)) to connect to for the plugins' ins and outs.

**Comment by falkTX** [comment]
I have started to implement this, but per plugin auto-connect is something quite different.
Open a new ticket if you really care about the feature.
