### ISSUE TITLE
seg fault since kxstudio last update 

### ISSUE THREAD

**Issue by rcspam** [falkTX/Carla#448]
Hi,
My system Ubuntu 16.04 + kxstudio ppa
Since last upgrade (2016.01.05) carla crash at startup and produce a segmentaion fault.
Here is the output from gdb/coredump:

> 
> $ gdb /usr/bin/carla ./core 
> GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
> Copyright (C) 2016 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> "/usr/bin/carla": not in executable format: Format de fichier non reconnu
> [New LWP 10083]
> [New LWP 10096]
> Core was generated by `/usr/bin/python3 /usr/share/carla/carla --with-appname=/usr/bin/carla --with-li'.
> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  0x00007f83e8ddb0df in ?? ()
> [Current thread is 1 (LWP 10083)]
>

and output from python3 command:

> 
> $ /usr/bin/python3 /usr/share/carla/carla --with-appname=/usr/bin/carla  --with-li
> qt5ct: using qt5ct plugin
> Using "" theme
> Carla 1.9.7 (2.0-beta5) started, status:
>   Python version: 3.5.2
>   Qt version:     5.5.1
>   PyQt version:   5.5.1
>   Binary dir:     /usr/share/carla
>   Resources dir:  /usr/share/carla/resources
> Traceback (most recent call last):
>   File "/usr/share/carla/carla", line 46, in <module>
>     host = initHost(initName, libPrefix, False, False, True)
>   File "/usr/share/carla/carla_host.py", line 2233, in initHost
>     host = HostClass() if HostClass is not None else CarlaHostQtDLL(os.path.join(pathBinaries, libname))
>   File "/usr/share/carla/carla_backend_qt.py", line 104, in __init__
>     CarlaHostDLL.__init__(self, libName)
>   File "/usr/share/carla/carla_backend.py", line 2106, in __init__
>     self.lib = CDLL(libName, RTLD_GLOBAL)
>   File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
>     self._handle = _dlopen(self._name, mode)
> 

Thanx

**Comment by falkTX** [comment]
Don't use gdb carla, use carla --gdb instead.

Also your 2nd log is missing the last lines (which are the important ones).

**Comment by rcspam** [comment]
> $ carla --gdb
> GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
> Copyright (C) 2016 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from /usr/bin/python3...(no debugging symbols found)...done.
> (gdb) run
> Starting program: /usr/bin/python3 /usr/share/carla/carla --with-appname=/usr/bin/carla --with-libprefix=/usr --gdb
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> [New Thread 0x7fffdd087700 (LWP 27081)]
> 
> Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
> 0x00007fffecc5b0df in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
> (gdb)

and

> $ /usr/bin/python3 /usr/share/carla/carla --with-appname=/usr/bin/carla --with-libprefix=/usr
> Erreur de segmentation (core dumped)

so

> $ /usr/bin/python3 /usr/share/carla/carla --with-appname=/usr/bin/carla 
> qt5ct: using qt5ct plugin
> Using "" theme
> Carla 1.9.7 (2.0-beta5) started, status:
>   Python version: 3.5.2
>   Qt version:     5.5.1
>   PyQt version:   5.5.1
>   Binary dir:     /usr/share/carla
>   Resources dir:  /usr/share/carla/resources
> Traceback (most recent call last):
>   File "/usr/share/carla/carla", line 46, in <module>
>     host = initHost(initName, libPrefix, False, False, True)
>   File "/usr/share/carla/carla_host.py", line 2233, in initHost
>     host = HostClass() if HostClass is not None else CarlaHostQtDLL(os.path.join(pathBinaries, libname))
>   File "/usr/share/carla/carla_backend_qt.py", line 104, in __init__
>     CarlaHostDLL.__init__(self, libName)
>   File "/usr/share/carla/carla_backend.py", line 2106, in __init__
>     self.lib = CDLL(libName, RTLD_GLOBAL)
>   File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /usr/share/carla/libcarla_standalone2.so: cannot open shared object file: No such file or directory

If i have link  "/usr/share/carla/libcarla_standalone2.so" and other libcarla* from share/carla dir to /usr/lib/carla dir then:

> $ carla --gdb
> GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
> Copyright (C) 2016 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from /usr/bin/python3...(no debugging symbols found)...done.
> (gdb) run
> Starting program: /usr/bin/python3 /usr/share/carla/carla --with-appname=/usr/bin/carla --with-libprefix=/usr --gdb
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> [New Thread 0x7fffdd087700 (LWP 2101)]
> 
> Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
> 0x00007fffecc5b0df in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
> (gdb)

and

> $ /usr/bin/python3 /usr/share/carla/carla --with-appname=/usr/bin/carla --with-libprefix=/usr
> Erreur de segmentation (core dumped)

**Comment by rcspam** [comment]
Hi falkTX,
Until fix for this issue, is there a way to downgrade last carla2 upgrade (16.04 + kxstudio ppa), because this segfault with this last version prevents me to work. Thanks

**Comment by falkTX** [comment]
You can try using the qt4 version, maybe it works.

`sudo apt-get install carla-git/trusty carla-data/trusty carla-lv2/trusty carla-vst/trusty`

**Comment by rcspam** [comment]
Cool, carla-git for trusty works... :) Thank you very much and thank you for kxstudio tools which are wonderfull tools.

**Comment by rcspam** [comment]
Apparently, if qt4 version works, is a qt5 issue ?!
Can you warm me here, so i'll help to test future version on my system....
And yet thanks...

**Comment by rcspam** [comment]
I have install last carla-git and all is ok now.... Thanx

**Comment by falkTX** [comment]
I don't really what this issue was, so closing now.
If it's still a problem, let me know.
