### ISSUE TITLE
Antergos / Arch install guide

### ISSUE THREAD

**Issue by marcshake** [falkTX/Carla#449]
I installed carla with AUR successfully. https://aur.archlinux.org/packages/carla/ (yaourt -S carla) and it seems to work fine. I had carla running perfecty with ubuntu but now I am not able to get my windows-vst up and running. The usual message is "this carla build cannot handle this binary" (sfz is the plugin) 

When trying to build the win32-brigdge the build fails. Linuxversion is antergos. I am not quite sure how to file this issue...

**Comment by falkTX** [comment]
Then give the logs of the failing bridges build.

**Comment by progwolff** [comment]
The package "carla" only installs carla itself, not the windows bridges.
Try to install "carla-git", "carla-bridges-win32-git" and "carla-bridges-win64-git"

**Comment by marcshake** [comment]
Carla itself works. Here's the commandview when trying to compile 
![log](https://cloud.githubusercontent.com/assets/11273309/21744065/5289282a-d50f-11e6-893a-375285c65c0f.png)

**Comment by progwolff** [comment]
Do you have gcc-multilib installed?

**Comment by marcshake** [comment]
I try it.

**Comment by marcshake** [comment]
That did it. Thankes. Issue is to be closed. Thanks
