### ISSUE TITLE
Carla plugin issues in Ardour

### ISSUE THREAD

**Issue by funkmuscle** [falkTX/Carla#450]
I'm using Arch64 and Carla works fine as a standalone. Loading Carla as a plugin in Ardour loads but with no controls. I get a blank Carla plugin with this in the terminal.

`0:1:1:0
CarlaPipeCommon::_writeMsgBuffer(..., 11) - failed with -1. Message was:
100.000000
CarlaPipeCommon::_writeMsgBuffer(..., 10) - failed with -1. Message was:
transport
CarlaPipeCommon::_writeMsgBuffer(..., 6) - failed with -1. Message was:
false
CarlaPipeCommon::_writeMsgBuffer(..., 8) - failed with -1. Message was:
0:1:1:0
CarlaPipeCommon::_writeMsgBuffer(..., 11) - failed with -1. Message was:
100.000000
CarlaPipeCommon::_writeMsgBuffer(..., 10) - failed with -1. Message was:
transport
CarlaPipeCommon::_writeMsgBuffer(..., 6) - failed with -1. Message was:
false
CarlaPipeCommon::_writeMsgBuffer(..., 8) - failed with -1. Message was:
0:1:1:0
CarlaPipeCommon::_writeMsgBuffer(..., 11) - failed with -1. Message was:
100.000000
CarlaPipeCommon::_writeMsgBuffer(..., 5) - failed with -1. Message was:
quit
`
I've built the latest from AUR this morning after reporting to you guys in IRC.

**Comment by falkTX** [comment]
Does the same happen to you with jalv?
`jalv.gtk http://kxstudio.sf.net/carla/plugins/carlapatchbay`

**Comment by funkmuscle** [comment]
no. I use jalv-select and I have no issues. Could this be due to jalv update? I don't think it's updated yet in Arch.

**Comment by falkTX** [comment]
something there is failing to start.
what happens if you run:
`/usr/share/carla/resources/carla-plugin` ?

**Comment by falkTX** [comment]
Quite a few things have changed in the Carla's code.
Please update and let me know if it's still an issue.
I cannot reproduce it here locally.

**Comment by funkmuscle** [comment]
I haven't tried for a long time. I have to upgrade my system and reinstalled Arch. While installing carla-bridges-win32-git, I get this error:
`make[1]: Leaving directory '/tmp/pamac-build-harv/carla-bridges-win32-git/src/carla-bridges-win32-git/source/jackbridge'
make[1]: Entering directory '/tmp/pamac-build-harv/carla-bridges-win32-git/src/carla-bridges-win32-git/source/modules/juce_audio_basics'
Compiling juce_audio_basics.cpp (32bit)
In file included from ../juce_core/juce_core.h:236:0,
                 from juce_audio_basics.h:60,
                 from juce_audio_basics.cpp:42:
../juce_core/maths/juce_NormalisableRange.h: In member function ‘ValueType juce::NormalisableRange<ValueType>::convertFrom0to1(ValueType) const’:
../juce_core/maths/juce_NormalisableRange.h:132:13: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
             if (skew != static_cast<ValueType> (1) && proportion > ValueType())
             ^~
../juce_core/maths/juce_NormalisableRange.h:135:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
                 return start + (end - start) * proportion;
                 ^~~~~~
In file included from juce_audio_basics.cpp:93:0:
buffers/juce_FloatVectorOperations.cpp: In static member function ‘static void juce::FloatVectorOperations::enableFlushToZeroMode(bool)’:
buffers/juce_FloatVectorOperations.cpp:1010:1: internal compiler error: in ix86_compute_frame_layout, at config/i386/i386.c:12444
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[1]: *** [Makefile:87: ../../../build/juce_audio_basics/Release/juce_audio_basics.cpp.win32.o] Error 1
make[1]: Leaving directory '/tmp/pamac-build-harv/carla-bridges-win32-git/src/carla-bridges-win32-git/source/modules/juce_audio_basics'
make: *** [Makefile:131: /tmp/pamac-build-harv/carla-bridges-win32-git/src/carla-bridges-win32-git/build/modules/Release/juce_audio_basics.win32.a] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by falkTX** [comment]
you can still build normal carla without the bridges, just to confirm the bug.

**Comment by funkmuscle** [comment]
Yes it builds and runs fine. I did out to be the best host for vst that's
why I need the bridge.
It sometimes crashes Ardour now but big improvement over the original issue.

Harvey Lord

**Comment by falkTX** [comment]
Ok thanks for confirming, I'll close the bug then.
The bridges should build now once again.
