### ISSUE TITLE
Native Helm GUI (lv2 and vst) are not displayed

### ISSUE THREAD

**Issue by ghost** [falkTX/Carla#452]
I'm using Debian "Jessie" (AntiX) 32-bit, and noticed that Helm's native GUI provides only a black window. 

brian

**Comment by SpotlightKid** [comment]
Can't reproduce this on 64-bit arch (using helm-git AUR package). GUI shows fine here.

Does the GUI show using helm's standalone version?

**Comment by amsynthdotcom** [comment]
The GUI is fine in standalone version, as well as the (LV2?) version using jalv.gtk.

brian

**Comment by falkTX** [comment]
I was never able to reproduce this issue...
Does it still happen?

**Comment by trebmuh** [comment]
FWIW, I've just tried with 2.0-RC1 on a Debian Stretch, and the Helm GUI appears as expected. Both with LV2 and VST2 version.

**Comment by trebmuh** [comment]
PS: @falkTX it looks like the [ghost user](https://github.com/ghost) is a kind of "account-deleted" user in the github realm.

**Comment by falkTX** [comment]
ah, thanks for noticing.
I guess the user is no longer interested on the issue. closing
