### ISSUE TITLE
Plugin instruments disconnected when loading a preset bank

### ISSUE THREAD

**Issue by amsynthdotcom** [falkTX/Carla#454]
(Debian, "Jessie," 32-bit)
Tested on both WhySynth and Xsynth, when loading a preset bank the midi and audio connections in the patchbay have to be remade.

brian

**Comment by falkTX** [comment]
Is this carla 1.x or git version?

**Comment by falkTX** [comment]
hello?

**Comment by falkTX** [comment]
Doesn't seem to be an issue anymore with the latest version.
Please confirm, otherwise I'll close the issue in a few days.

**Comment by falkTX** [comment]
Can't reproduce, closing issue.
