### ISSUE TITLE
Gig sample program setting isn't being reloaded when Carla is used as VST

### ISSUE THREAD

**Issue by KGZM** [falkTX/Carla#463]
I'm using Carla as a VST in Bitwig and when I export my rack which contains a gig sampleset, and reimport it.. the program setting is just blank.

It works in Carla standalone but not when hosted by Bitwig or Ardour.

Carla version is 1.9.7 (2.0-beta5) installed from carla-git package on AUR.

**Comment by falkTX** [comment]
is it possible for you to provide a session file that has this issue?

**Comment by falkTX** [comment]
Gig file support was removed from Carla, due to many issues regarding linuxsampler (the library used for gig sampling).
I'm closing this bug, sorry for the inconvenience.
