### ISSUE TITLE
Carla window shows a Black Screen when loading Carla Rack as vst in Renoise.

### ISSUE THREAD

**Issue by billyblackburn** [falkTX/Carla#464]
Hi falktx.  

Im on a minimal funtoo install so I may be missing some dependencies. I compiled it from source with no errors.

here is a screenshot
http://imgur.com/a/KpnuP

here is a log from Renoise
https://paste.pound-python.org/show/gSEAppRV4lq6MdARBqXy/

here is output from "make features"
https://paste.pound-python.org/show/10afh7v06JgKWUXgZVGQ/

i see that 
VST plugin: \033[31m NO \033[0m \033[33m[No front-end]\033[0m

but I don't know how to resolve this

**Comment by falkTX** [comment]
make features shows that the frontend was not built...

what version of pyqt do you have?

**Comment by billyblackburn** [comment]
it seems that i dont have pyqt at all. does it matter what version I get?

**Comment by falkTX** [comment]
if you don't have pyqt, then carla UI can't be used.
so you don't get an interface on carla-vst...

does running "carla" work for you?
ie, does the standalone work?

**Comment by billyblackburn** [comment]
no it doesnt.  i only have option to run carla-single but i it didnt work when i tried it

**Comment by billyblackburn** [comment]
i have to go to work but ill be back later tonight and try to fix it.  what should I do?  recompile after installing pyqt?

**Comment by billyblackburn** [comment]
thanks brother, I'll try it when I get home and let you know what happens

**Comment by billyblackburn** [comment]
its worknig now thanks again

**Comment by falkTX** [comment]
great, thanks for confirming.
