### ISSUE TITLE
Don't build LV2 or VST if PyQt is missing

### ISSUE THREAD

**Issue by falkTX** [falkTX/Carla#465]

**Comment by simonvanderveldt** [comment]
@falkTX I'm packaging Carla for gentoo same as some of your other packages and one thing that's missing is the option for the user to choose which "version" (Standalone, LV2, VST) of Carla to build and install.

I can create a PR that fixes that and I can than make sure I include the checks for PyQt as well. Is that OK for you?

**Comment by falkTX** [comment]
Why do you even want to skip installing the LV2 and VST version?
You can simply build everything, then delete from DESTDIR whatever you don't need.

Carla has a lot of shared resources, installing LV2 without standalone does not really make sense.
The standalone is just a simple python script that inits the engine and UI in a different way from the plugin version.

**Comment by falkTX** [comment]
Handled with the latest commits.
Only the useful stuff is installed when pyqt, x11, or other things are missing.
