### ISSUE TITLE
Calf plugins GUI won't close

### ISSUE THREAD

**Issue by lucmp** [falkTX/Carla#469]
I add a Calf plugin to Carla, any of them. I see the Calf rack. 
I press the GUI button. It lights up in blue and the GUI pops up.
I press the GUI button. The light turns off, but the GUI is still there. 
The buttons don't work, but I still can drag the GUI around. 
I press the GUI button. It lights up in blue and the GUI buttons become responsive again.
I press the GUI button. The light turns off, but the GUI won't go away.

**Comment by falkTX** [comment]
I noticed this too, happens only when the calf plugins are run under bridge mode.
(so calf analyzer and fluidsynth, unless you checked the option to run all plugins as bridge)

**Comment by falkTX** [comment]
Fixed in latest git.
You'll need the latest git of calf-plugins.
(on kxstudio repos you can just install calf-plugins-git)
