### ISSUE TITLE
Fix knob-mouse behaviour

### ISSUE THREAD

**Issue by unfa** [falkTX/Carla#470]
![selection_230](https://cloud.githubusercontent.com/assets/491704/22825175/f1311fc8-ef8b-11e6-9793-9ac994e020fe.png)

Currently Carla's knobs work in an angular fashion (blue arrow) - it's based on the angle between the knob origin and the mouse cursor.

The fundamental problem with that is every time I click on a knob **it changes it's value based on which pixel did I hit** (angle form the origin) - **basically** changing it's position **to a random value**. This often produces bad loudness bursts, as something that was 12% gets to 80% suddenly.

Maybe this should become relative instead of absolute - so whenever you click, nothing changes until you move the mouse, but still this seems as imprecise.  It's much easier to follow a linear path than a circular one with a mouse controller, even for a graphic designer like me.

I think that a linear, relative approach would be better (green arrow).
You click on a knob - nothing changes, when you move the mouse up the value goes up. Moving further away to the left or right could be used for extra precision. (the further you go away in the X axis, the lower the change multiplier for the Y axis offset.

Anybody has the same problems with knobs as I do?

**Comment by ShalokShalom** [comment]
+1 

While i think, that it might be senseful, to use the X angle for the general movement and the Y one for the extra precision. 

And its surely nice to adjust this in the settings. (Change job for X/Y)

**Comment by falkTX** [comment]
At one point I will do this, in time for 2.0 final version.
Someone already proposed some changes, I'm yet to review them.

Not currently in focus since the current behaviour, athough bad, works.

**Comment by falkTX** [comment]
fuck it, I added a linear mode for the knobs and I'm sticking with it.
the previous behavior was just because that's what Qt does by default.
it never bothered me much, so I didn't change it. until today :P
enjoy your linear knobs :)

**Comment by ShalokShalom** [comment]
Thanks ^-^
