### ISSUE TITLE
Carla don't start

### ISSUE THREAD

**Issue by profejuanca** [falkTX/Carla#471]
Hey everybody, the last version of Carla cannot start, maybe is a problem with some dependency? the message is:

juanca@juanca-desktop:~$ carla
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 28, in <module>
    from PyQt5.QtCore import qCritical, QFileInfo, QModelIndex, QPointF, QTimer
ImportError: No module named 'PyQt5'
 I understand PyQT5 is a graphical library, is missing in my system? obviously my sources is updated, thanks in advance.

**Comment by ShalokShalom** [comment]
Which distro? Simply try to find it in your package manager

While i think your distro should packaged Carla with it..

**Comment by falkTX** [comment]
well yeah, you need python3-pyqt5, or something along those lines.

what distro are you using?

**Comment by milkmiruku** [comment]
I'm getting a somewhat similar problem with 6589315 (second last) commit

 ```Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 44, in <module>
    from carla_panels import *
  File "/usr/share/carla/carla_panels.py", line 29, in <module>
    from PyQt5.QtGui import QDialog, QFontMetrics
ImportError: cannot import name 'QDialog'
```

I tried upgrading python-pyqt5 and pyqt5-common to 5.8.1-1 which are in Arch testing, no change. Python can import QFontMetrics fine, just not QDialog..

**Comment by milkmiruku** [comment]
Quick fix, was afk after; as error, /usr/share/carla/carla_panels.py, as line 30 imports QDialog from QtWidgets, removing QDialog from 29 resolves.

**Comment by profejuanca** [comment]
I change the repository in sources list and update, problem solved. Carla
actually can manage kontakt in win32 mode? It is the most important plugin
for me and festige crash until 5.1 version of kontakt...

**Comment by falkTX** [comment]
So I'm not sure what the issue here really is...
@profejuanca did you solved the issue you're having, about carla not being able to start?

**Comment by profejuanca** [comment]
Yes, Carla now starts

**Comment by kpanic** [comment]
I had a similar issue:

### Carla installation
```
$ dpkg -l|grep carla
ii  carla                                         5:2.2.0+git20201005                        amd64        audio plugin host
ii  carla-data                                    5:2.2.0+git20201005                        all          audio plugin host (common data)
```

### pyqt5 installation

```
$ dpkg -l|grep python3-pyqt5
ii  python3-pyqt5                                 5.15.0+dfsg-1                              amd64        Python 3 bindings for Qt5
ii  python3-pyqt5.qtopengl                        5.15.0+dfsg-1                              amd64        Python 3 bindings for Qt5's OpenGL module
ii  python3-pyqt5.qtsvg                           5.15.0+dfsg-1                              amd64        Python 3 bindings for Qt5's SVG module
ii  python3-pyqt5.qtwebchannel                    5.15.0+dfsg-1                              amd64        Python 3 bindings for Qt5's WebChannel module
ii  python3-pyqt5.qtwebengine                     5.15.0-1                                   amd64        Python 3 bindings for Qt5's WebEngine module
ii  python3-pyqt5.qtwebkit                        5.15.0+dfsg-1                              amd64        Python 3 bindings for Qt5's WebKit module
```

### Carla execution
```
$ carla
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 40, in <module>
    from PyQt5.QtCore import (
ModuleNotFoundError: No module named 'PyQt5'
```
### Import from `python3`

```
$ python3
Python 3.7.4 (default, Feb 29 2020, 09:34:37) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5.QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5'
```

Turns out that I had a local python `3.7.4` installed with `asdf` that did not see system level python `3.8.6` packages (like PyQt5)
I removed the `asdf-python` plugin and now it works.
I don't need `asdf-python` for now, so that's fine for me!

I guess this issue can be closed

**Comment by falkTX** [comment]
Yeah, this is completely a non-carla issue.
