### ISSUE TITLE
atom events don't reach UI - add support for ui:PortNotification

### ISSUE THREAD

**Issue by ventosus** [falkTX/Carla#472]
Atom events seem only to be sent to atom ports which are marked as lv2:control.
Additional ports which would like to get notifications and request so in the .ttl with ui:PortNotification are ignored. No events to the UI -> broken plugin.

**Comment by falkTX** [comment]
What exact kind of events are missing, and for which plugin(s)?
Carla should be sending all events possible to the UI, it ignores portNotification because I sends everything.

**Comment by ventosus** [comment]
patch:Get/Set/...

I send them on an atom port which is *not* marked as lv2:control and I don't get any events in 'port_event'. If I mark the port with lv2:control, events do arrive in 'port_event'.

The plugin in question has up to 5 in/out atom ports and I can put lv2:control only on one of them...

Here the .ttl
https://github.com/OpenMusicKontrollers/moony.lv2/tree/master/plugin

**Comment by falkTX** [comment]
Carla does not support patch get/set/etc messages yet.
This has nothing to do the UI or port notifications.

**Comment by ventosus** [comment]
Events are sent to *my* X11 UI. Carla does not filter them, does it?

**Comment by ventosus** [comment]
Here it is, I think:

https://github.com/falkTX/Carla/blob/master/source/backend/plugin/CarlaPluginLV2.cpp#L3378

If I read the code correctly, output atom sequences seem only to be iterated over and sent to UI for the port marked as lv2:control.

And there's no filtering (apart from MIDI)

https://github.com/falkTX/Carla/blob/master/source/backend/plugin/CarlaPluginLV2.cpp#L3408

That's why it works when I mark the port with lv2:control, but not otherwise...

**Comment by falkTX** [comment]
I guess something quick can be done here regarding it.
There was just no need for such thing before.

**Comment by ventosus** [comment]
Well, I cross-checked some other hosts, ardour, qtractor and ingen all ignore lv2:control.

Jalv also considers the port marked with lv2:control to be the main DSP<->UI comm channel.

I seem to have wrongly assumed that the main event port (e.g. MIDI) needs to be marked with lv2:control. When marking my main comm channel as lv2:control, there's no issue with Carla. As I don't need any notifications on my other event ports, I'll be fine for now even without any changes.

But some day someone may want to get notifications on multiple event output ports, so I will keep the issue open for now...

**Comment by falkTX** [comment]
I also noticed that multi-midi-ports plugins don't work at the moment, likely related to this.
Should not be hard to fix the current behaviour.
To do for next beta.
