### ISSUE TITLE
Binaries should not be stripped during build

### ISSUE THREAD

**Issue by simonvanderveldt** [falkTX/Carla#474]
The current Makefiles strip all binaries during build when building on Linux. This shouldn't be the case. Stripping should happen either by the package manager or if it really has to be definied in the Makefile a separate `install-strip` target should be used.

See https://www.gnu.org/prep/standards/html_node/Standard-Targets.html for more info

Creating this issue because this causes a QA warning when building on Gentoo:
```
QA Notice: Pre-stripped files found:
<list of files>
```

**Comment by falkTX** [comment]
That would be the case if carla was intended to only be packaged in linux distros.
But carla has builds for osx and windows, not to mention personal builds and AUR.
By default I want carla binaries to be stripped, specially since plugins are involved.

**Comment by simonvanderveldt** [comment]
@falkTX I'm fine with it being an option that defaults to `true`, as long as it can be turned off.
Created this issues to discuss, I don't mind to create a PR to add these options but don't know how you'd want to do so.

**Comment by simonvanderveldt** [comment]
@falkTX OK, I can add a variable set to `true` by default that adds `-Wl,--strip-all` to `LINK_OPTS`.
Do you also want this enabled for Linux? That's not really how it's supposed to work, so just checking to make sure I understand you correctly.

Also the Makefile doesn't actually strip when building for OS X, see https://github.com/falkTX/Carla/blob/master/source/Makefile.mk#L70

**Comment by falkTX** [comment]
Stripping for OSX is done in a different way.

Regarding this issue, I'd suggest adding a "SKIP_STRIPPING,true" check in the makefile.
So it would be possible to skip it by using `make SKIP_STRIPPING=true`, leaving normal builds unchanged.

**Comment by simonvanderveldt** [comment]
> Regarding this issue, I'd suggest adding a "SKIP_STRIPPING,true" check in the makefile.
> So it would be possible to skip it by using make SKIP_STRIPPING=true, leaving normal builds unchanged.

OK, I'll create a PR to add it
