### ISSUE TITLE
Renaming  plugin locks up Carla with error messages

### ISSUE THREAD

**Issue by Quirq-UK** [falkTX/Carla#479]
Using Carla 1.9.7 (2.0-beta5) with jackd2 (2:1.9.11~20161209-1~xenial5 from UbunutuStudio repositories).

Renaming a plugin in Carla results in it being impossible to connect the plugin up to anything (midi or audio) both in Carla's patchbay or in the Connections window of QJackCtl.

When any plugin is renamed there is an endless stream of error messages, all saying the same thing:  `Carla assertion failure: "plugin != nullptr && plugin->isEnabled()" in file CarlaEngineThread.cpp, line 75`

**Comment by falkTX** [comment]
Yes, I noticed that too.
It was working before, so something I changed caused this.
