### ISSUE TITLE
Make it possible to set instrument number for SFZ & GIG

### ISSUE THREAD

**Issue by johnsen** [falkTX/Carla#48]
Make it possible to set instrument number for SFZ & GIG, some apps have channel and program number 'hard coded', like impro-visor.

http://en.wikipedia.org/wiki/General_MIDI#Program_change_events

**Comment by falkTX** [comment]
Gig file support was removed from Carla, due to many issues regarding linuxsampler (the library used for gig sampling).
SFZ support still remains, but those have only 1 single "program".
I'm closing this bug, sorry for the inconvenience.
