### ISSUE TITLE
Canvas piano keyboard / computer keyboard layout

### ISSUE THREAD

**Issue by sirius-c** [falkTX/Carla#481]
The canvas piano keyboard can be operated by the computer keyboard, but this assumes a qwerty layout. With my qwertz layout (German keyboard) the result is unexpected for the notes on y and z.
Could the keyboard layout be made configurable, as in ZynAddSubFX for example?

**Comment by falkTX** [comment]
It needs to be configurable at some point, yes.
Something to do after v2.0 is out.

**Comment by falkTX** [comment]
Why did you close this? it's a perfectly valid feature request.

**Comment by trebmuh** [comment]
I'm adding my voice here. I'm using an (French) AZERTY keyboard and am hitting the same issue.

I'm glad to see that it's already on the TODO list.

**Comment by trebmuh** [comment]
Thanks!

**Comment by falkTX** [comment]
Latest git now has keyboard layouts option (right click on the piano)
has qwerty and qwertz for now.
Adding new options should be easy, but I won't do it myself.
I moved the file to modify, now it is https://github.com/falkTX/Carla/blob/master/source/frontend/widgets/pixmapkeyboard.py#L68

**Comment by trebmuh** [comment]
I've tried something on #738 (WIP).

**Comment by sirius-c** [comment]
Thanks for implementing this feature.
