### ISSUE TITLE
Cannot lock down 82274202 byte memory area 

### ISSUE THREAD

**Issue by umren** [falkTX/Carla#483]
Hey

I'm on Linux 64 bit, downloaded binary carla 2.0beta5 both 32 bit and 64 bit

i got some plugins installed by wine vst (sugar bytes factory and obscurium, u-he zebra2)

i discovered plugins by carla

each time i try to "Add" plugin in carla it crashes with "cannot lock down memory area"

i tried every plugin, 32 bit and 64 bit versions of plugins and 32 bit and 64 bit versions of Carla, same story everywhere

[screenshoot](http://i.imgur.com/3B9EzoN.png)

am i doing something wrong or it's just not working?

**Comment by falkTX** [comment]
likely you're using wine-rt without your user being in the audio group.
add your user to the audio group first, then things should work again.

usually that message also means nothing else regarding wine works either.

**Comment by umren** [comment]
Well i was using wine, but not wine-rt from kxaudio repositories, installing wine-rt right now to check this again
