### ISSUE TITLE
invalid desktop categories

### ISSUE THREAD

**Issue by Animtim** [falkTX/Carla#485]
Hi,
while packaging carla for mageia, I had these errors:
```
- invalid-desktopfile /usr/share/applications/carla-control.desktop
value "AudioVideo;AudioEditing;Qt;" for key "Categories" in group
"Desktop Entry" contains an unregistered value "AudioEditing"; values
extending the format should start with "X-"
 - invalid-desktopfile /usr/share/applications/carla.desktop value
"AudioVideo;AudioEditing;Qt;" for key "Categories" in group "Desktop
Entry" contains an unregistered value "AudioEditing"; values extending
the format should start with "X-"
```
meaning the AudioEditing category is not a valid additional category, as per https://specifications.freedesktop.org/menu-spec/latest/apas02.html

So I made this patch to fix it:
http://svnweb.mageia.org/packages/cauldron/carla/current/SOURCES/desktop-categories.patch?view=markup&pathrev=1100621

Maybe it is a good idea to use it upstream?

Also on a side note, I had issues with hard-coded /python3/dist-packages in the Makefile, so I needed to make another patch for it. Though for this one I'm not sure that my patch is the cleanest way to do it upstream.. Check python-version.patch and the spec if you need more info http://svnweb.mageia.org/packages/cauldron/carla/current/

**Comment by falkTX** [comment]
The custom category is on purpose.
It won't be changed.

**Comment by Animtim** [comment]
Ok, I thought so but was asked if it could go upstream. Now I can also clearly answer No :)
We can keep this patch to make our build system happy.

**Comment by simonvanderveldt** [comment]
@Animtim see https://github.com/falkTX/Carla/issues/434

This should actually be fixed, otherwise why have standards?
I guess KX Studio needs to be updated/fixed to use either `X-` prefixed categories or just use the existing ones.

**Comment by ShalokShalom** [comment]
What is the reason for this individual category?

**Comment by falkTX** [comment]
This was a request by AVLinux, so it can place certain applications in a custom menu I believe.
The custom category doesn't hurt me at all, so I just went ahead and added it.
afaik there is no visible issues with category being there.

If your distro requires you to have 100% clean desktop files, then patching them for your distro seems a good choice. I don't think it's good enough reason to remove the category from the source code though.

**Comment by ShalokShalom** [comment]
You are sure its a sane idea to patch your software for one distro, while all the others follow the standards and get have to patch for themself?

Custom decisions should be taken by own, custom action. Not vice versa

**Comment by falkTX** [comment]
Debian/Ubuntu and Fedora do not complain about this.
Changing this now would mean breaking the setup for AVLinux.

**Comment by ShalokShalom** [comment]
They dont complain, because they dont care. Mixed categories are fine for them. 
People, who care about a clean implementation will think how inconsiderate that is.

**Comment by ShalokShalom** [comment]
To implement something on the request of a single distro, breaking well established standards is a mistake from the very beginning. That should be implemented in the distro at all, of course. 

This here is a sound software. AV Linux is a distribution. So implement distro-specific standards is something up to the distro.

**Comment by falkTX** [comment]
I think it's more inconsiderate to break something that works right now because of a validator output.
The AVLinux category is wrong, sure, but it's too late to change that now.
When the next AVLinux gets released, we can revisit this issue.

**Comment by falkTX** [comment]
I noticed this is a duplicated bug, see #434 
Any further discussion should happen there.
