### ISSUE TITLE
editing a-fluid synth soundfont filename property doesn't work

### ISSUE THREAD

**Issue by swesterfeld** [falkTX/Carla#492]
I use carla from kxstudio: 2:1.2.4-1kxstudio2

I can load the a-fluid synth plugin into rack, but the filename property doesn't show up on the edit pages, so I can't load a soundfont.

**Comment by falkTX** [comment]
Carla doesn't support lv2 filename states at the moment.
Something to do after v2.0.

**Comment by SpotlightKid** [comment]
This should be fixed now.

**Comment by falkTX** [comment]
yes, though it requires latest develop version.
a v2.1 will be out in a few weeks

**Comment by robertmuth** [comment]
I use carla from kxstudio  5:2.4.1 and it does not see memorize the sound font name.

The carxp file also does not seem to have any stanza for soundfonts

**Comment by falkTX** [comment]
Did you wait for the file to load? If you ask it to load a file and directly save it afterwards, nothing will be saved on the plugin side because it expects the file to be loaded (completely) first

**Comment by robertmuth** [comment]
I just re-did my setup and made sure I could play the sounds (a drumkit) before saving the carxp file. 
Still no trace of anything referring to soundfonts in that file.

Are there any diagnostic tools that I could use to make debugging easier? For example:
* how do I put carla in "debug logging" mode?
*  is there a way to dump the list of config options of a plugin like fluid-synth either inside of carla or using an external tool? 
   (to rule out problems with the plugin itself).
   
  I do not think this is very likely to cause issues but the soundfont lives  on an nfs mount and I did not specify any default directory for sound fonts in carla.
