### ISSUE TITLE
OS X Built-in AU plug-ins can't be added

### ISSUE THREAD

**Issue by squidbidness** [falkTX/Carla#494]
When I click 'Add plugin' and then choose (apparently) any of the OS X builtin AU plugins, such as AUAudioFilePlayer, AUBandpass, AUDelay, etc., and then confirm with "Add Plugin", an error dialog box appears stating, "No compatible plug-in format exists for this plug-in".

My impressions from googling around are that this error message is being propagated from JUCE.  For example, this JUCE help request post shows how one user resolved this error message in their own JUCE-based project by following a code update suggestion:  https://forum.juce.com/t/opening-plugins/19794.

I'm running OS X El Capitain (10.11.6).  I've only just recently installed Jack OS X (0.91) and Carla (1.9.7 2.0-beta5) per the normal procedure of mounting the .dmg and dragging the .app file into Applications.

Incidentally, this same error appears when trying to insert SooperLooper as a plug-in (also a new install, SooperLooper v 1.7.3; 64-bit .component file).  With luck this is the same bug.

**Comment by squidbidness** [comment]
I see there are a fair number of commits on Carla's master branch since 2.0 beta-5 was released, but I only just cloned the repo and I don't have many of the dependencies installed yet, so I'm not able to build Carla on my own machine yet to check if by chance any unreleased updates resolve this.

(For example, I notice commit c7bd702 mentions changes in JUCE; though looking at the particular code changes they don't look very significant aside from fixing the OS X build itself, so I'm not sure that one resolves it)

**Comment by falkTX** [comment]
Try this build and let me know if it works. https://github.com/falkTX/Carla/releases/download/1.9.7b/Carla.zip

**Comment by squidbidness** [comment]
That build resolves the problem.  Thank you!

Incidentally, I found that I had to uninstall the version of Jack that I had installed using Homebrew, and go back to the MacOs-package-installer I had downloaded from the Jack web site before Carla could connect to jack.  Would you like me to open a separate issue for that problem?

**Comment by falkTX** [comment]
That's not a bug, it's a feature - kinda.
Homebrew installs in a custom prefix, which systems applications do not use.
So using Carla's mac binaries, provided by me, will not work with those.
