### ISSUE TITLE
carla-plugin fails in Tracktion

### ISSUE THREAD

**Issue by jshou** [falkTX/Carla#496]
Hi! I've installed carla-git through the kvraudio repository. Any time I try to load the carla plugin through Tracktion, the GUI loads up but none of the buttons respond. gdb output looks like this:

```
Carla assertion failure: "fIsActive" in file carla-vst.cpp, line 256
Trying to start carla-plugin using "/usr/lib/vst/carla.vst/resources/carla-plugin"
LRDF Support not available (LADSPA-RDF will be disabled)
Qt: Session management error: Could not open network socket
Using "carla" theme
Carla 1.9.7 (2.0-beta5) started, status:
  Python version: 3.5.2
  Qt version:     5.5.1
  PyQt version:   5.5.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
ALL OK!
Got SIGTERM -> Closing now
```

Eventually the plugin quits out and displays `Got SIGTERM -> Closing now` and then the window closes. Is there anything I should be doing differently?

Thanks!

**Comment by falkTX** [comment]
Which tracktion version?
Also, kvraudio repository? do you mean kxstudio?

**Comment by jshou** [comment]
Tracktion t5 in Ubuntu. And yes, I meant kxstudio, sorry about that. Carla works fine standalone though.

**Comment by jshou** [comment]
Interesting, I seem to be able to get keyboard shortcuts to respond but it looks like mouse clicks aren't going through for some reason.

**Comment by jshou** [comment]
Ah, looks like this has already been reported here: https://github.com/falkTX/Carla/issues/170

Apologies for the duplicate report, took me awhile to figure out it was the same thing :)
