### ISSUE TITLE
Make Carla able to set maximum voices/disk stream count for LinuxSampler

### ISSUE THREAD

**Issue by FrnchFrgg** [falkTX/Carla#497]
When using LinuxSampler LV2 together with QSampler, when QSampler is launched it sets the maximum number of simultaneous voices and disk streams, according to its configuration in the Tuning tab of the View/Options dialog.

I also used the following LSCP commands (with socat on 8888):
SET STREAMS 256
SET VOICES 256

(Unfortunately LinuxSampler LV2 does not save those as plugin state, and moreover uses a weird state saving system IIRC)

In Carla those limits seem to be hard-coded, to values clearly too low for heavy-duty uses: big pianos with velocity layer mixing and pedal on-off mixing (to get string resonance when the pedal is pressed after the note press) and even harmonics and hammer noise can mean as many as 6 samples per note, and when a good pianist plays [that piece](http://www.piano-e-competition.com/MIDIFiles/2011/Teo08.MID) the voice count is often stationary at the maximum 128 for long periods of time.

Since the voice count hits the hard maximum, LS silences abruptly the oldest sample (presumably), but when a lot of notes are played the stolen voices are still quite loud and that creates a very audible artifact.

(For that file and that SFZ, 256 is even too low, but the voice stealing is almost inaudible so that would be OK)

Can the hard limits be increased, or even made configurable and part of Carla's state ? It seems that changing those parameters while LS is playing something can crash it so beware (in particular, I had to be very careful when opening QSampler or it would bring my ardour session down, since it applies the settings at startup).

**Comment by falkTX** [comment]
Sorry, this is now not possible to implement.
linuxsampler was replaced by sfzero for sfz handling, and gig file support removed.

on sfzero, voices are hardcoded to 128. (this could be changed I guess)
disk streaming is not supported.

linuxsampler had too many issues that made it quite the pain to manage, decided to get rid of it.
also the license was always in the way..

**Comment by FrnchFrgg** [comment]
If disk streaming is not supported, does that mean that all sound files have to fit in memory ? This could be a problem for huge libs (the free IvyPiano SFZ is already >4GB of samples, not to mention pro-grade SFZ which can weigh more than 30GB sometimes).

Also, I do not know if SFZero handles as many opcodes as linuxsampler. Last time I checked (two years ago IIRC) it didn't, and there were important ones missing.

128 voices is only 32 notes sounding at the same time in a SFZ that mixes velocity and pedal layers, and when some good pianist plays with the pedal on (see http://www.piano-e-competition.com/MIDIFiles/2011/Teo08.MID linked above), this limit is soon reached.

Good to see the licensing stuff sorted out, though.

**Comment by falkTX** [comment]
yeah, sfzero is meant for simpler SFZ files.
for such big libraries, linuxsampler as a plugin is still an option.

the amount of hacks needed to get internal linuxsampler working was getting too much. and it still did not work.

I will add opcodes on a by-need basis.
For now leaving current code as-is, it is good enough to warrant a release and testing.
Once I come back to work on carla after the next release, I will be adding a few things to it.
