### ISSUE TITLE
Carla resource folder does not exist, is it installed?

### ISSUE THREAD

**Issue by interstar** [falkTX/Carla#501]
Following the build instructions from https://github.com/falkTX/Carla/blob/master/INSTALL.md for the first time.

After I make and make install, I'm getting this message : 

`Carla resource folder does not exist, is it installed?`

when I try to run.

Any thoughts?

**Comment by falkTX** [comment]
give me the commands you used to build and install. ie, PREFIX, DESTDIR, etc etc.
and by the way, DESTDIR is only used for packaging, not self-installs.

**Comment by interstar** [comment]
Cheers for the response @falkTX 

I literally just did this : 

`
git clone https://github.com/falkTX/Carla.git carla
cd carla
make 
sudo make install
carla-single native vst /usr/local/lib/vst/Lua\ Protoplug\ Gen.so
`
(I'm trying to get Protoplug working in Linux and Carla was recommended as a host which which it works with. I'm on Ubuntu Xenial, BTW)

**Comment by falkTX** [comment]
run `make features` and post here the output.
I think maybe you're missing a few dependencies for the frontend.

**Comment by falkTX** [comment]
I reduced the requirements for you, but you will likely want to install the extra dependencies to get the frontend. At the very least you should have libx11-dev so VST UIs work.
carla-single will work now without the frontend.

**Comment by interstar** [comment]
```
---> Main features 
Front-End:    NO  [Missing PyQt]
LV2 plugin:   NO  [No front-end]
VST plugin:   NO  [No front-end]
Link support: YES 
OSC support:  NO  [Missing liblo]

---> Engine drivers 
JACK:        YES 
ALSA:        YES 
PulseAudio:  NO  [Missing PulseAudio]
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]

---> Plugin formats: 
Internal: YES 
LADSPA:   YES 
DSSI:     YES 
LV2:      YES 
VST:      YES (with UI)
VST3:     NO  [Windows and MacOS only]
AU:       NO  [MacOS only]

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     NO  [Gtk2 missing]
Gtk3:     NO  [Gtk3 missing]
Qt4:      YES (bridge)
Qt5:      NO  [Qt5 missing]
X11:      YES (direct+bridge)
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
GIG: NO   [LinuxSampler missing or too old]
SF2: NO   [FluidSynth missing]
SFZ: NO   [LinuxSampler missing or too old]

---> Internal plugins: 
Carla-Patchbay:  YES 
Carla-Rack:      YES 
DISTRHO Plugins: YES (with UI)
DISTRHO ProM:    NO  (missing libprojectM)
ZynAddSubFX:     NO  [fftw3, mxml or zlib missing]

```

**Comment by interstar** [comment]
libx11-dev is already the newest version

**Comment by interstar** [comment]
python-pyqt5 also seems to be installed and newest version.

**Comment by interstar** [comment]
Ah ... ok .. I realize you updated the repo. 

Thanks ... yes. That now seems to be working. (At least, it loads and seems to run the plugin .. no sound coming out yet, but that may be the plugin's issue)

cheers again.
