### ISSUE TITLE
Reference winVST Plugin by "Mastering the Mix" fries the CPU

### ISSUE THREAD

**Issue by lentferj** [falkTX/Carla#505]
When I load this plugin (demo available here: https://www.masteringthemix.com/products/reference) as a win32 bridged plugin into carla it will eat up the CPUs my 12 core Xeon box entirely...

p.s.: I this the right place to report such things as it might not actually carla related, but wine or be a problem with the specific plugin?

**Comment by falkTX** [comment]
it's fine to report here, at least we have a place for the discussion.

Does the same happen when you run this plugin in other hosts?
(say, reaper)

**Comment by lentferj** [comment]
yes, actually. Same in Bitwig via airwave :(

**Comment by lentferj** [comment]
... and in Ardour with LinVST. I would think this is a problem with h/w acceleration for the gui in wine, not a carla issue.

**Comment by IvanDSM** [comment]
I'd recommend you report this issue on the Wine AppDB and open up a bug report. It'd be great help! :)

**Comment by lentferj** [comment]
That was actually a problem with the plugin itself, it seems. With version 1.02 the problems are gone for me and it's actually usable. The change log for 1.02 states "Significant CPU utilisation improvements". Case closed. Thanks.

**Comment by falkTX** [comment]
Great to know, closing this bug then.
