### ISSUE TITLE
Carla project files aren't loading proper plugin settings

### ISSUE THREAD

**Issue by Barbouze** [falkTX/Carla#506]
Hi!

I've been using a Carla rack for headphones listening for a few month and since a few days I noticed that some parameters don't get loaded correctly anymore. When loading the attached file, the output gain should be set at something like -18dB and the 120Hz band level at +3dB but I get -36.1 and 0. I've noticed this with other plugins too (at least in the Calf suite). I tried re-setting the parameters and saving again but no success so far.
Using carla-git and calf-plugin*git.

Cheers,
Barbouze

[Casque.carxp.zip](https://github.com/falkTX/Carla/files/1240335/Casque.carxp.zip)

**Comment by falkTX** [comment]
sadly for some plugins you will have to re-save.
