### ISSUE TITLE
PulseAudio & ALSA jack bridge autoconnect vs LADISH studio

### ISSUE THREAD

**Issue by Barbouze** [falkTX/Carla#510]
Hi!
I've created a LADISH studio using Claudia to get a system wide equalizer+limiter using Calf JACK host.
I routed PulseAudio and ALSA bridges to Calf Jack host and the later to system output.

The problem is that those bridges are connecting themselves automatically to the system output too as soon as they are started by Cadence, which defeats the purpose of the LADISH studio.

How/where can I change this behavior (bridges autoconnecting to system output)?

Cheers,
Barbouze

**Comment by falkTX** [comment]
Configure JACK (the studio) and check the option to ignore self connect requests.

**Comment by Barbouze** [comment]
Well, that did the trick except for the Alsa audio bridge.
Not using it much anyway, I might simply not start it at session start.

Thanks!

**Comment by falkTX** [comment]
Closing this issue, I guess it's kinda solved and it was meant for Cadence anyway, not Carla.
