### ISSUE TITLE
carla-control not working "Name or service not known"

### ISSUE THREAD

**Issue by simonvanderveldt** [falkTX/Carla#511]
Maybe I'm doing something wrong, but when trying out carla-control to connect to carla running on the same machine I get this error
```
Connecting to "osc.tcp://localhost.localdomain:13718/Carla" as 'Carla'...
Traceback (most recent call last):
  File "/usr/share/carla/carla_control.py", line 505, in slot_fileConnect
    self.connectOsc(addr)
  File "/usr/share/carla/carla_control.py", line 456, in connectOsc
    lo_send(lo_target, "/register", self.fOscServer.getFullURL())
  File "src/liblo.pyx", line 186, in liblo.send (src/liblo.c:3667)
  File "src/liblo.pyx", line 160, in liblo._send (src/liblo.c:3532)
OSError: sending failed: b'Name or service not known'
```

**Comment by falkTX** [comment]
Use the real IP instead of localhost.localdomain.

**Comment by simonvanderveldt** [comment]
> Use the real IP instead of localhost.localdomain.

Just to check: 127.0.0.1 also doesn't work?

**Comment by falkTX** [comment]
is that a question?

usually this all relates to /etc/hosts not being 100% well configured.
liblo can be very picky.

**Comment by falkTX** [comment]
I am closing this bug as invalid.
Cleaning up the OSC related items now.
If you want to try again, please get the latest develop branch stuff, there are some nice changes regarding OSC in there, though still not complete yet.
