### ISSUE TITLE
liblo/osc dependent applications shouldn't be installed when liblo isn't present

### ISSUE THREAD

**Issue by simonvanderveldt** [falkTX/Carla#512]
Since OSC/liblo support is optional, see https://github.com/falkTX/Carla/blob/8d95f5946bcabad0451a1a27cb9241137838d941/Makefile#L851, applications that require it shouldn't be installed if liblo isn't available.
AFAIK this only concerns `carla-control`.

**Comment by falkTX** [comment]
actually, at least on debian, you can have python3-liblo installed without liblo-dev.
so carla-control would still work, just not to connect to a local instance.
but the idea makes sense.
