### ISSUE TITLE
feature: Resize canvas on the fly

### ISSUE THREAD

**Issue by nick87720z** [falkTX/Carla#516]
I'm just getting attention to carla, and during update to fresh code and draft overview for news i got this idea.

For now size of entire canvas, available for object placing, is specified statically by canvas size option, and it proposes only hardcoded list, organized in combobox.
However, more convenient ways are possible.
From simpler to smarter:
- Replace combobox with widget set: [QSpinBox width] [QLabel "x'] [QSpinBox height] + option to aspect ratio
- Rescale overview by mouse scroll, but without Ctrl (since overview never needs panning)
- Don't restrict canvas size. Size control way, implemented in main viewport, is same as currently in catia. Canvas size is completely defined by bounding box of all objects at canvas, overview just syncs with it.
  - Overview also could change scale by scrolling, as mentioned above in second way, but with minimal scale enough to overview all boxes.

p.s. Same may be true about claudia (whose funtionality is lower than in catia, regardless it is in one package with catia)

**Comment by falkTX** [comment]
the issue with this is the mini-canvas needs to understand the size of the canvas.
also, allowing arbitrary sizes means it will lose aspect ratio.

so this is not a priority for now.

**Comment by nick87720z** [comment]
Aspect ration may be kept by automatic correction of second value.
As for feature to change it... this is another deal.
For least unexpected gui behavior it may be possible to change it manually by simple resizing.

While sidebar resize should simple change overview size, keeping aspect ratio (btw, currrently it doesn't), overview itself may have vertical resize grip, whose purpose is to correct aspect ratio.

As for value of support for different aspect ratio - very useful if you have long change of elements, organized in one line. In this particular case it would be great also to implement overview in QDockWidget, then place in bottom - workflow should be more convenient. Place such dock separated on another sidebar, and similar, but vertical layout is possible.

**Comment by falkTX** [comment]
I'm going to say no to this.
It's something I don't personally think adds too much value to carla in my view.

of course you can add it yourself, but I don't want to maintain such feature at this point.
