### ISSUE TITLE
Xhip synthesizer doesn't show its custom GUI

### ISSUE THREAD

**Issue by Barbouze** [falkTX/Carla#527]
Hi!

I know you are already aware of this problem as written in [this post](https://linuxmusicians.com/viewtopic.php?f=24&t=17634) but I just wanted to make it "official by creating a bug report here :)

Cheers,
Barbouze

**Comment by falkTX** [comment]
Not an issue with Carla.
The plugin returns a 0 value to the effEditOpen opcode, which in the VST spec means the UI failed to open.
As such, Carla interprets this value as the UI not being available, and presents the user from trying to open it again.
