### ISSUE TITLE
Can't lauch Carla (CX_Freeze issue?)

### ISSUE THREAD

**Issue by IvanDSM** [falkTX/Carla#537]
I can't launch Carla on my desktop. It isn't able to extract itself successfully to run. Here's the console output of trying to run Carla:

`$ ./Carla
Carla self-contained executable 1.9.5 (2.0 beta3), based on UnZipSFX.
  inflating: /tmp/carla/resources/at1/ctrlsect.png  
 extracting: /tmp/carla/resources/at1/hmeter0.png  
 extracting: /tmp/carla/resources/at1/hmeter1.png  
 extracting: /tmp/carla/resources/at1/hscale.png  
 extracting: /tmp/carla/resources/at1/midi.png  
 extracting: /tmp/carla/resources/at1/note.png  
  inflating: /tmp/carla/resources/at1/notesect.png  
  inflating: /tmp/carla/resources/at1-ui  
  inflating: /tmp/carla/resources/bls1/inputsect.png  
  inflating: /tmp/carla/resources/bls1/lfshfsect.png  
 extracting: /tmp/carla/resources/bls1/shuffsect.png  
  inflating: /tmp/carla/resources/bls1-ui  
    linking: /tmp/carla/resources/PyQt4.Qt.so  -> ../PyQt4.Qt.so 
    linking: /tmp/carla/resources/PyQt4.QtCore.so  -> ../PyQt4.QtCore.so 
    linking: /tmp/carla/resources/PyQt4.QtGui.so  -> ../PyQt4.QtGui.so 
    linking: /tmp/carla/resources/PyQt4.QtOpenGL.so  -> ../PyQt4.QtOpenGL.so 
    linking: /tmp/carla/resources/PyQt4.QtSvg.so  -> ../PyQt4.QtSvg.so 
    linking: /tmp/carla/resources/_codecs_cn.cpython-32mu.so  -> ../_codecs_cn.cpython-32mu.so 
    linking: /tmp/carla/resources/_codecs_hk.cpython-32mu.so  -> ../_codecs_hk.cpython-32mu.so 
    linking: /tmp/carla/resources/_codecs_jp.cpython-32mu.so  -> ../_codecs_jp.cpython-32mu.so 
    linking: /tmp/carla/resources/_codecs_tw.cpython-32mu.so  -> ../_codecs_tw.cpython-32mu.so 
    linking: /tmp/carla/resources/_json.cpython-32mu.so  -> ../_json.cpython-32mu.so 
    linking: /tmp/carla/resources/bz2.cpython-32mu.so  -> ../bz2.cpython-32mu.so 
    linking: /tmp/carla/resources/libcarla_interposer-safe.so  -> ../libcarla_interposer-safe.so 
    linking: /tmp/carla/resources/libcarla_utils.so  -> ../libcarla_utils.so 
    linking: /tmp/carla/resources/libmagic.so.1  -> ../libmagic.so.1 
    linking: /tmp/carla/resources/libssl.so.0.9.8  -> ../libssl.so.0.9.8 
 extracting: /tmp/carla/resources/rev1/ambsect.png  
 extracting: /tmp/carla/resources/rev1/eq1sect.png  
 extracting: /tmp/carla/resources/rev1/eq2sect.png  
 extracting: /tmp/carla/resources/rev1/mixsect.png  
  inflating: /tmp/carla/resources/rev1/revsect.png  
  inflating: /tmp/carla/resources/rev1-ui  
    linking: /tmp/carla/resources/_multibytecodec.cpython-32mu.so  -> ../_multibytecodec.cpython-32mu.so 
    linking: /tmp/carla/resources/libcarla_standalone2.so  -> ../libcarla_standalone2.so 
    linking: /tmp/carla/resources/libffi.so.5  -> ../libffi.so.5 
    linking: /tmp/carla/resources/libselinux.so.1  -> ../libselinux.so.1 
    linking: /tmp/carla/resources/carla-plugin-patchbay  -> carla-plugin 
 extracting: /tmp/carla/resources/zynaddsubfx/black_key.png  
 extracting: /tmp/carla/resources/zynaddsubfx/black_key_pressed.png  
  inflating: /tmp/carla/resources/zynaddsubfx/knob.png  
 extracting: /tmp/carla/resources/zynaddsubfx/module_backdrop.png  
 extracting: /tmp/carla/resources/zynaddsubfx/white_key.png  
 extracting: /tmp/carla/resources/zynaddsubfx/white_key_pressed.png  
 extracting: /tmp/carla/resources/zynaddsubfx/window_backdrop.png  
  inflating: /tmp/carla/resources/zynaddsubfx-ui  
  inflating: /tmp/carla/resources/carla-plugin  
  inflating: /tmp/carla/resources/midipattern-ui  
    linking: /tmp/carla/resources/_codecs_iso2022.cpython-32mu.so  -> ../_codecs_iso2022.cpython-32mu.so 
    linking: /tmp/carla/resources/_codecs_kr.cpython-32mu.so  -> ../_codecs_kr.cpython-32mu.so 
    linking: /tmp/carla/resources/_hashlib.cpython-32mu.so  -> ../_hashlib.cpython-32mu.so 
    linking: /tmp/carla/resources/libbz2.so.1.0  -> ../libbz2.so.1.0 
    linking: /tmp/carla/resources/libcarla_interposer-x11.so  -> ../libcarla_interposer-x11.so 
    linking: /tmp/carla/resources/libcrypto.so.0.9.8  -> ../libcrypto.so.0.9.8 
    linking: /tmp/carla/resources/libpython3.2mu.so.1.0  -> ../libpython3.2mu.so.1.0 
    linking: /tmp/carla/resources/sip.so  -> ../sip.so 
  inflating: /tmp/carla/resources/bigmeter-ui  
  inflating: /tmp/carla/resources/notes-ui  
  inflating: /tmp/carla/jackbridge-wine32.dll  
  inflating: /tmp/carla/jackbridge-wine64.dll  
  inflating: /tmp/carla/carla-bridge-win32.exe  
  inflating: /tmp/carla/carla-bridge-win64.exe  
  inflating: /tmp/carla/carla-discovery-win32.exe  
  inflating: /tmp/carla/carla-discovery-win64.exe  
  inflating: /tmp/carla/carla-bridge-lv2-gtk3  
  inflating: /tmp/carla/carla-bridge-lv2-qt5  
  inflating: /tmp/carla/carla-bridge-lv2-gtk2  
  inflating: /tmp/carla/carla-bridge-lv2-qt4  
  inflating: /tmp/carla/carla-bridge-lv2-x11  
  inflating: /tmp/carla/carla-bridge-native  
  inflating: /tmp/carla/carla-bridge-posix32  
  inflating: /tmp/carla/carla-discovery-native  
  inflating: /tmp/carla/carla-discovery-posix32  
  inflating: /tmp/carla/libcarla_interposer-safe.so  
  inflating: /tmp/carla/libcarla_interposer-x11.so  
  inflating: /tmp/carla/libcarla_standalone2.so  
  inflating: /tmp/carla/libcarla_utils.so  
 extracting: /tmp/carla/styles/carlastyle.json  
  inflating: /tmp/carla/styles/carlastyle.so  
  inflating: /tmp/carla/carla        
  inflating: /tmp/carla/libpython3.2mu.so.1.0  
  inflating: /tmp/carla/PyQt4.Qt.so  
  inflating: /tmp/carla/PyQt4.QtCore.so  
  inflating: /tmp/carla/PyQt4.QtGui.so  
  inflating: /tmp/carla/PyQt4.QtOpenGL.so  
  inflating: /tmp/carla/PyQt4.QtSvg.so  
  inflating: /tmp/carla/_codecs_cn.cpython-32mu.so  
  inflating: /tmp/carla/_codecs_hk.cpython-32mu.so  
  inflating: /tmp/carla/_codecs_iso2022.cpython-32mu.so  
  inflating: /tmp/carla/_codecs_jp.cpython-32mu.so  
  inflating: /tmp/carla/_codecs_kr.cpython-32mu.so  
  inflating: /tmp/carla/_codecs_tw.cpython-32mu.so  
  inflating: /tmp/carla/_hashlib.cpython-32mu.so  
  inflating: /tmp/carla/_json.cpython-32mu.so  
  inflating: /tmp/carla/_multibytecodec.cpython-32mu.so  
  inflating: /tmp/carla/bz2.cpython-32mu.so  
  inflating: /tmp/carla/sip.so       
  inflating: /tmp/carla/libffi.so.5  
  inflating: /tmp/carla/libmagic.so.1  
  inflating: /tmp/carla/libssl.so.0.9.8  
  inflating: /tmp/carla/libcrypto.so.0.9.8  
  inflating: /tmp/carla/libbz2.so.1.0  
  inflating: /tmp/carla/libselinux.so.1  
finishing deferred symbolic links:
  /tmp/carla/resources/PyQt4.Qt.so -> ../PyQt4.Qt.so
  /tmp/carla/resources/PyQt4.QtCore.so -> ../PyQt4.QtCore.so
  /tmp/carla/resources/PyQt4.QtGui.so -> ../PyQt4.QtGui.so
  /tmp/carla/resources/PyQt4.QtOpenGL.so -> ../PyQt4.QtOpenGL.so
  /tmp/carla/resources/PyQt4.QtSvg.so -> ../PyQt4.QtSvg.so
  /tmp/carla/resources/_codecs_cn.cpython-32mu.so -> ../_codecs_cn.cpython-32mu.so
  /tmp/carla/resources/_codecs_hk.cpython-32mu.so -> ../_codecs_hk.cpython-32mu.so
  /tmp/carla/resources/_codecs_jp.cpython-32mu.so -> ../_codecs_jp.cpython-32mu.so
  /tmp/carla/resources/_codecs_tw.cpython-32mu.so -> ../_codecs_tw.cpython-32mu.so
  /tmp/carla/resources/_json.cpython-32mu.so -> ../_json.cpython-32mu.so
  /tmp/carla/resources/bz2.cpython-32mu.so -> ../bz2.cpython-32mu.so
  /tmp/carla/resources/libcarla_interposer-safe.so -> ../libcarla_interposer-safe.so
  /tmp/carla/resources/libcarla_utils.so -> ../libcarla_utils.so
  /tmp/carla/resources/libmagic.so.1 -> ../libmagic.so.1
  /tmp/carla/resources/libssl.so.0.9.8 -> ../libssl.so.0.9.8
  /tmp/carla/resources/_multibytecodec.cpython-32mu.so -> ../_multibytecodec.cpython-32mu.so
  /tmp/carla/resources/libcarla_standalone2.so -> ../libcarla_standalone2.so
  /tmp/carla/resources/libffi.so.5 -> ../libffi.so.5
  /tmp/carla/resources/libselinux.so.1 -> ../libselinux.so.1
  /tmp/carla/resources/carla-plugin-patchbay -> carla-plugin
  /tmp/carla/resources/_codecs_iso2022.cpython-32mu.so -> ../_codecs_iso2022.cpython-32mu.so
  /tmp/carla/resources/_codecs_kr.cpython-32mu.so -> ../_codecs_kr.cpython-32mu.so
  /tmp/carla/resources/_hashlib.cpython-32mu.so -> ../_hashlib.cpython-32mu.so
  /tmp/carla/resources/libbz2.so.1.0 -> ../libbz2.so.1.0
  /tmp/carla/resources/libcarla_interposer-x11.so -> ../libcarla_interposer-x11.so
  /tmp/carla/resources/libcrypto.so.0.9.8 -> ../libcrypto.so.0.9.8
  /tmp/carla/resources/libpython3.2mu.so.1.0 -> ../libpython3.2mu.so.1.0
  /tmp/carla/resources/sip.so -> ../sip.so
Traceback (most recent call last):
  File "/usr/share/cx-freeze-common/initscripts/Console3.py", line 27, in <module>
  File "build-carla/src/carla", line 22, in <module>

`

I'm running Gentoo, and I've tried running Carla on python 2.7.14, 3.4.6, 3.5.4 and 3.6.3. All versions gave the same output. I've tried downgrading the Cx_Freeze package to 4.3.4 and that didn't work either.

**Comment by falkTX** [comment]
cxfreeze is only used for the binary builds.
if you build from source you don't need it.

**Comment by falkTX** [comment]
The latest beta tweaked the build a little, this might be fixed there now, please test.
Thanks.

**Comment by falkTX** [comment]
Assuming fixed. newer builds have changed quite a lot and do not even use Qt4 anymore, so the ticket is no longer relevant in any case
