### ISSUE TITLE
ZynAddSubFX non listed

### ISSUE THREAD

**Issue by tonilink** [falkTX/Carla#538]
I'm using KXStudio in a Debian 9. After the last update of the package "carla-git" (1.9.7+git20171118.2) and "carla-lv2" (1.9.7+git20171118.2) the "ZynAddSubFX by FalkTX" isn't working in Ardour 5.12 anymore. It's appear and works in Carla. But Ardour say that plugin was removed.

**Comment by falkTX** [comment]
Yes, correct.
Zyn provides an LV2 and VST plugin officially since a few releases, so I want to remove the carla's exported version.
Need to do this before Carla is released as stable.
I'll post something later today explaining the latest breaking changes in carla.
