### ISSUE TITLE
can't built Carla from git anymore on Arch

### ISSUE THREAD

**Issue by funkmuscle** [falkTX/Carla#539]
ever since the update of Carla, we can't build from git on Arch:

In file included from zita-at1/jclient.h:27:0,
                 from zita-at1/jclient.cc:26,
                 from zita-at1.cpp:21:
../includes/CarlaNativeJack.h: In function ‘int jack_midi_event_get(jack_midi_event_t*, void*, uint32_t)’:
../includes/CarlaNativeJack.h:272:16: error: ‘ENODATA’ was not declared in this scope
         return ENODATA;
                ^~~~~~~
make[1]: *** [external/Makefile:188: ../../build/native-plugins/Release/zita-at1.cpp.o] Error 1
make[1]: Leaving directory '/home/harv/.cache/pacaur/carla-git/src/carla-git/source/native-plugins'
make: *** [Makefile:97: /home/harv/.cache/pacaur/carla-git/src/carla-git/build/modules/Release/native-plugins.a] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build carla-git package(s)
When EXPERIMENTAL_PLUGINS=false is set in the PKGBUILD, it compiles fine.

**Comment by falkTX** [comment]
Should be fixed now, please test and report.

**Comment by funkmuscle** [comment]
no now this:
Package libpng12 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpng12.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpng12' found
Compiling zita-at1-ui.cpp
In file included from /usr/include/clxclient.h:31:0,
                 from zita-at1/png2img.cc:24,
                 from zita-at1-ui.cpp:20:
/usr/include/X11/Xft/Xft.h:39:10: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
          ^~~~~~~~~~~~
compilation terminated.
make[1]: *** [external/Makefile:183: ../../build/native-plugins/Release/zita-at1-ui.cpp.o] Error 1
make[1]: Leaving directory '/home/harv/.cache/pacaur/carla-git/src/carla-git/source/native-plugins'
make: *** [Makefile:97: /home/harv/.cache/pacaur/carla-git/src/carla-git/build/modules/Release/native-plugins.a] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build carla-git package(s)

packages libpng12 and lib32-libpng12 are installed from official repo so the path issue should not be an issue should it?

**Comment by falkTX** [comment]
I was going to remove them soon anyway, so went ahead and did it a little early.

**Comment by funkmuscle** [comment]
success! that worked! thanx falkTX. great work as usual
