### ISSUE TITLE
[nsm] add optional GUI

### ISSUE THREAD

**Issue by grammoboy2** [falkTX/Carla#54]
A disadvantage of one-task-one-tool is the clutter on the desktop. Could you add
optional GUI to the nsm support? Laborejo has it already.
http://non.tuxfamily.org/nsm/API.html#n:1.2.4.1

**Comment by mxmilkiib** [comment]
Having the GUI remember whether it should be visible or not would be handy to quicker get back to the state at save.

**Comment by falkTX** [comment]
Yes, but that is a separate ticket then.
Carla now does have optional-gui in NSM, I just did not notice this ticket which I should have closed some weeks ago.
