### ISSUE TITLE
Carla crash on u-he plugins after latest changes in codebase

### ISSUE THREAD

**Issue by AlbertoZ33n** [falkTX/Carla#541]
Hello Felipe, after the last updates to Carla (the one that stripped down the Juce stuff, 22/11/17) trying to load any u-he plugins crashes Carla on my system. They worked reliably before.
Instead calling for example:
carla-single vst ~/.vst/u-he/ACE.32.so
loads the plugin correctly. 
Moreover, Carla discovery provides the output attached in the file below. 

[carla_discovery.txt](https://github.com/falkTX/Carla/files/1503476/carla_discovery.txt)

I already tried, without success, the workaround that worked in the past (deselect "Load Carla backend in global namespace"). 
I'm on Linux Mint 17.3, tried both on 32 and 64 bit OS.

Let me know if I can provide more information.

Alberto

**Comment by falkTX** [comment]
for u-he plugins you often need to enable the experimental global-namespace option.
Have you tried that yet?

**Comment by AlbertoZ33n** [comment]
I did few experiments. It works if:
launch carla 
==>experimental features 
==> enable "Load Carla backend in global namespace"
==> exit carla
==> launch carla, 
==> deselect "Load Carla backend in global namespace", 
==> load u-he ==> OK.

If carla is entered and "Load Carla backend in global namespace" is non selected (by default), load u-he ==> crash.

Seems something not properely initialized related to "backend in global namespace"? 
Thanks,

Alberto

**Comment by falkTX** [comment]
The u-he plugins need that option enabled, then a restart of carla. (the restart required text does not fit the GUI :P)
Just leave it enabled for now. (other plugins might have issues though, hopefully not many..)

**Comment by AlbertoZ33n** [comment]
Yes, it worked like you suggested. The restart of Carla is mandatory. Then it works fine.
Thanks for your support.
