### ISSUE TITLE
Carla rack not saving all plugin state parameters

### ISSUE THREAD

**Issue by Quirq-UK** [falkTX/Carla#549]
Since upgrading to 2:1.9.7+git20171129/1202v5 not all plugin parameters are being saved.

Using Carla-rack in Ardour 5.12 with the G-Force M-Tron Pro VSTi, changes to parameters such as filter cutoff are saved, but the instrument loads blank every time with no sound loaded.

**Comment by OrsonMaxwell** [comment]
I probably experience this same issue? I'm running aur/carla-git 1:1.9.7b.r283.g7068200a-1 and it does not save states of any windows VST plugins (specifically Guitar Rig 5 and midiCurve).

**Comment by progwolff** [comment]
Can confirm. Also parameters of win32 VSTs in previously saved patches aren't restored properly.

**Comment by falkTX** [comment]
old patches (before the juce removal update) won't load, but resaving should.
I will investigate resave windows plugins missing state very soon.
