### ISSUE TITLE
Logic inversion enabling force stereo

### ISSUE THREAD

**Issue by dfoxfranke** [falkTX/Carla#552]
Plugins' force stereo option becomes grayed out when the 'Force mono plugins as stereo' experimental feature is enabled, rather than when it is disabled.

**Comment by falkTX** [comment]
I was wondering about this, but seems correct as it is now.
The option is forced, ie always on, when the experimental setting is on.
So we are indeed forcing all (possible) mono plugins to run as stereo.

This is working as intended for LADSPA and DSSI, but we're missing being able to turn on/off on LV2 and internal plugins. This is the small part that needs fixing.
