### ISSUE TITLE
Double-clicking folder in file browser sidebar shows error message

### ISSUE THREAD

**Issue by noedigcode** [falkTX/Carla#554]
In the file browser sidebar in the main Carla window, when double-clicking on a folder/directory, a message box is displayed saying "Failed to load file...".
Double-clicking on a folder should simply expand/collapse that folder.

**Comment by falkTX** [comment]
This has been fixed already in the latest git version.
Which exact build of carla are you using?

**Comment by noedigcode** [comment]
Oh, sorry. I'll get the new version.
I was using version 1.9.7 (2.0-beta5), package 2:1.9.7+git20170828v5

**Comment by falkTX** [comment]
Did you check if this is fixed on the absolute latest? Thanks

**Comment by noedigcode** [comment]
Yes, it's fixed. Thank you!
