### ISSUE TITLE
Carla does not save win VST plugin state

### ISSUE THREAD

**Issue by OrsonMaxwell** [falkTX/Carla#557]
Hello. 
I'm using the latest (1666475...) build of Carla and the latest bridges from the git as well.
When I save a project containing any windows VST plugins, their state won't be saved. They will have the default settings upon next project load .
Looking at the project file, it seems to no longer contain the binary state blobs like it used to - don't know if it is relevant.
I'll be glad to provide any additional info and perform any required testing.

**Comment by falkTX** [comment]
Please post the contents of the log when you press save in carla.
(either terminal or carla's log window, depending on your settings).

Seems weird as I really thought I had this fixed now...

**Comment by OrsonMaxwell** [comment]
I do this:
1. Add Guitar rig 5.1.0 to the rack
2. Tweak any setting
3. "Save as" tst1.carxp

Here is the log from the Logs tab:
`Carla assertion failure: "jassertfalse triggered" in file files/File.cpp, line 158

carla_vst_hostCanDo("asyncProcessing") - unknown feature

carla_vst_hostCanDo("editFile") - unknown feature

Carla Bridge Ready!

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Carla assertion failure: "out.failedToOpen()" in file files/File.cpp, line 749

Carla assertion failure: "fInfo.chunk.size() > 0" in file CarlaPluginBridge.cpp, line 475`

**Comment by falkTX** [comment]
You're not using the code you reported to use.
In the first post you say you're using latest commit 1666475bb34b26099d5a43b3d6d3f9e3d5d2887f
The assertion is on line 158, which on that commit leads to https://github.com/falkTX/Carla/blob/1666475bb34b26099d5a43b3d6d3f9e3d5d2887f/source/modules/water/files/File.cpp#L158
There is no assertion here.

Please make sure you update everything first, then try again.

**Comment by falkTX** [comment]
The last 2 commits on Carla right now have fixed this issue. Somehow you do not have them.
Note that both carla-git and the bridges need to be updated.

**Comment by OrsonMaxwell** [comment]
Indeed. It appears I've failed to install the latest carla-bridges from git. Truly sorry and thanks!
