### ISSUE TITLE
Memory leak in Carla Rack plugin

### ISSUE THREAD

**Issue by kitterion** [falkTX/Carla#565]
When using Carla Rack from inside Claudia via Application -> Add New -> Plugin, it steadily leaks memory. It had eaten 5 Gigs of memory after a few days of uptime when I noticed. It leaks even with an empty rack but it seems that the rate is higher with something loaded in the rack, however I can't say for sure.

Also looks like the console version `carla-rack` doesn't leak.

I'm running KDE Neon 16.04 lowlatency with kxstudio repos.

Carla 1.9.7 (2.0-beta5)
Python version: 3.5.2
Qt version: 5.9.3
PyQt version: 5.8.2

**Comment by kitterion** [comment]
I think I've found the culprit. It seems to be in the python-c++ glue code.
There's a function `carla_pipe_client_readlineblock` that gets called quite a lot from python.

On the c++ side it [returns `const char *`](https://github.com/falkTX/Carla/blob/f3ee9dfedbef79ef589876c9d5dce0e4fc55f0e0/source/backend/CarlaUtils.cpp#L634) which [after](https://github.com/falkTX/Carla/blob/f3ee9dfedbef79ef589876c9d5dce0e4fc55f0e0/source/backend/CarlaUtils.cpp#L638) [a few](https://github.com/falkTX/Carla/blob/f3ee9dfedbef79ef589876c9d5dce0e4fc55f0e0/source/backend/CarlaUtils.cpp#L569) [function](https://github.com/falkTX/Carla/blob/f3ee9dfedbef79ef589876c9d5dce0e4fc55f0e0/source/utils/CarlaPipeUtils.cpp#L1038-L1039) [calls](https://github.com/falkTX/Carla/blob/f3ee9dfedbef79ef589876c9d5dce0e4fc55f0e0/source/utils/CarlaPipeUtils.cpp#L1028) gets allocated by `new[]` in `carla_strdup`.
On the python side it's [declared returning `c_char_p`](https://github.com/falkTX/Carla/blob/f3ee9dfedbef79ef589876c9d5dce0e4fc55f0e0/source/carla_utils.py#L201) which is [passed](https://github.com/falkTX/Carla/blob/f3ee9dfedbef79ef589876c9d5dce0e4fc55f0e0/source/carla_utils.py#L317) through [`charPtrToString`](https://github.com/falkTX/Carla/blob/f3ee9dfedbef79ef589876c9d5dce0e4fc55f0e0/source/carla_backend.py#L70-L75) but it's never deleted.

In my local Carla build I added string deleting function to the shared library and subverted `ctypes` as [this SO answer](https://stackoverflow.com/a/13452473) suggests. It doesn't constantly leak anymore as far as I can tell.

I could send a PR with the changes if needed. Or maybe there's a better way to fix this that I'm missing.

**Comment by falkTX** [comment]
wow, nice catch!
the c++ code does indeed delete the pointer, not using free() but using delete[].
should be easy to handle with a new utils function, I'll do this later today.
thanks.
