### ISSUE TITLE
Build fails on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [falkTX/Carla#567]
Hi falkTX,

Now, after a while, the current Carla revision doesn't build any more.
One error:
```
gmake[3]: Leaving directory '/usr/ports/audio/carla/work/Carla-1.9.7b-372-gf3ee9dfe/source/modules/water'
CarlaEngineRtAudio.cpp:90:19: error: no member named 'UNIX_PULSE' in 'RtAudio'; did you mean 'LINUX_PULSE'?
    case RtAudio::UNIX_PULSE:
         ~~~~~~~~~^~~~~~~~~~
                  LINUX_PULSE
/usr/local/include/rtaudio/RtAudio.h:271:5: note: 'LINUX_PULSE' declared here
    LINUX_PULSE,    /*!< The Linux PulseAudio API. */
    ^
```
```/usr/local/include/rtaudio/RtAudio.h``` is installed by ```rtaudio-5.0.0```, the latest version.

When I patch this difference, I get another one with RtAudio:
```
Compiling CarlaEngineRtAudio.cpp
CarlaEngineRtAudio.cpp:434:48: error: member function 'getCurrentApi' not viable: 'this' argument has type 'const RtAudio', but function is not marked const
        return CarlaBackend::getRtAudioApiName(fAudio.getCurrentApi());
                                               ^~~~~~
/usr/local/include/rtaudio/RtAudio.h:829:32: note: 'getCurrentApi' declared here
inline RtAudio::Api RtAudio :: getCurrentApi( void ) { return rtapi_->getCurrentApi(); }
                               ^
```
-----
Now I see that the above errors are due to the conflict with external RtAudio. The build picks the external version over the bundled one.
Any chance to just use the standard RtAudio-5.0.0 ?

-----

Now, once I removed the installed RtAudio-5.0.0, I get another error:
```
Compiling CarlaBridgeToolkitNative.cpp (X11)
../../build/modules/Release/carla_engine.a(CarlaEngineRtAudio.cpp.o): In function `CarlaBackend::CarlaEngineRtAudio::connectExternalGraphPort(unsigned int, unsigned int, char const*)':
CarlaEngineRtAudio.cpp:(.text._ZN12CarlaBackend18CarlaEngineRtAudio24connectExternalGraphPortEjjPKc[_ZN12CarlaBackend18CarlaEngineRtAudio24connectExternalGraphPortEjjPKc]+0x2d0): undefined reference to `RtMidiIn::RtMidiIn(RtMidi::Api, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int)'
CarlaEngineRtAudio.cpp:(.text._ZN12CarlaBackend18CarlaEngineRtAudio24connectExternalGraphPortEjjPKc[_ZN12CarlaBackend18CarlaEngineRtAudio24connectExternalGraphPortEjjPKc]+0x43f): undefined reference to `RtMidiOut::RtMidiOut(RtMidi::Api, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)'
../../build/modules/Release/carla_engine.a(CarlaEngineRtAudio.cpp.o): In function `bool CarlaBackend::CarlaEngineRtAudio::refreshExternalGraphPorts<CarlaBackend::PatchbayGraph>(CarlaBackend::PatchbayGraph*, bool)':
CarlaEngineRtAudio.cpp:(.text._ZN12CarlaBackend18CarlaEngineRtAudio25refreshExternalGraphPortsINS_13PatchbayGraphEEEbPT_b[_ZN12CarlaBackend18CarlaEngineRtAudio25refreshExternalGraphPortsINS_13PatchbayGraphEEEbPT_b]+0x386): undefined reference to `RtMidiIn::RtMidiIn(RtMidi::Api, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int)'
CarlaEngineRtAudio.cpp:(.text._ZN12CarlaBackend18CarlaEngineRtAudio25refreshExternalGraphPortsINS_13PatchbayGraphEEEbPT_b[_ZN12CarlaBackend18CarlaEngineRtAudio25refreshExternalGraphPortsINS_13PatchbayGraphEEEbPT_b]+0x5cf): undefined reference to `RtMidiOut::RtMidiOut(RtMidi::Api, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)'
../../build/modules/Release/carla_engine.a(CarlaEngineRtAudio.cpp.o): In function `bool CarlaBackend::CarlaEngineRtAudio::refreshExternalGraphPorts<CarlaBackend::RackGraph>(CarlaBackend::RackGraph*, bool)':
```

-----

Or, perhaps, I shouldn't even be trying to update? Maybe it's unstable at the moment?

**Comment by falkTX** [comment]
As you guessed, this is because of rtaudio also being installed on the system.
Something I still need to figure out how to handle better.
Same for rtmidi, even though it could build initially, the linking fails.

Temporarily remove rtaudio and rtmidi when building carla.
I will install freebsd on my main pc this week to test the audio issues, so I'll check this one too.

**Comment by yurivict** [comment]
I see. I found RtAudio conflict, but didn't notice the RtMidi one.
It builds now. I will submit a port update now.

FYI: py-sip dependency was missing. I've added it. Not sure if it is missing in your docs.

I couldn't make the keyboard work. It doesn't make sound, while Carla passes the external midi signal fine. It isn't clear where its signal is supposed to go to. Is it permanently connected to Carla's midi output?

Also, like before, hitting the "close" button caused a freeze. It leaves these processes.

Thank you for your help!
Yuri

**Comment by falkTX** [comment]
if you have a midi keyboard, then you need to connect whatever group/port it has into the plugin you want to receive the notes.
in linux, using a2j, we connect the a2j port jack-midi to the plugin midi-input port.
I don't know how MIDI works on BSD systems.

**Comment by yurivict** [comment]
On FreeBSD, midi can be supported in kernel via OSS4, but only midi is only supported in USB sound cards. Otherwise, soft-midi through Jack/FluidSynth.

**Comment by falkTX** [comment]
So unless there is some bridge, I don't think it's possible to get MIDI working with Carla on BSD at the moment...
Or does JACK on BSD supports audio and midi at the same time?

In any case, you need something that provides a JACK MIDI output port.
So you can connect things like this:

![screenshot_20180108_115759](https://user-images.githubusercontent.com/1334853/34667887-3e228dfa-f46b-11e7-9af1-d6f7edffe42f.png)
