### ISSUE TITLE
Failing to load Calf LV2 plugins

### ISSUE THREAD

**Issue by kitterion** [falkTX/Carla#569]
After upgrading to beta6, `carla-bridge-native` started crashing trying to load any calf lv2 plugin.
AFAICT looking at it in the debugger it seems to be because access to `fUI.window` here:
https://github.com/falkTX/Carla/blob/97aa532c7aab4019c4202eadae9323e2f0e5c29d/source/backend/plugin/CarlaPluginLV2.cpp#L1486-L1488
is not protected by the `if` check just below.

My system: KDE neon 16.04 lowlatency with kxstudio repos
Carla 1.9.8 (2.0-beta6)
Python version: 3.5.2
Qt version: 5.9.3
PyQt version: 5.9.2

**Comment by falkTX** [comment]
yep, that seems correct.
nice catch, will fix now. thanks.
