### ISSUE TITLE
Carla 2.0.beta6 : "cx_Freeze : Python error in main script" with Windows 32 Bits version

### ISSUE THREAD

**Issue by E-Gwen** [falkTX/Carla#570]
Hi,

I just try Carla 2.0.beta6, but when I launch it, I get this error message : 

(Header) : cx_Freeze: Python error in main script

	Traceback (most recent call last):
		File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
		File ",\source\Carla.pyw", line 46, in <module>
		File "Z:\Shared\Personal\FOSS\GIT\falkTX\Carla\source\carla_host.py", line 2502, in iniHost
		File "Z:\Shared\Personal\FOSS\GIT\falkTX\Carla\source\carla_backend_qt.py", line 97, in __init__
		File "Z:\Shared\Personal\FOSS\GIT\falkTX\Carla\source\carla_backend.py", line 2172, in __init__
		File "C:\Python34\lib\ctypes\in __init__.py, line 351, in __init__
		OSError : [WinError 998] l'accès à cet emplacement mémoire n'est pas valide
                                                      (The direct ? memory access is not available) ?

Note that Carla 2.0.beta5 was running.

Can you fix that ?

Best regards.

E-Gwen.

**Comment by falkTX** [comment]
Which windows version are you using? (XP, 7, 10, something else)
Did you try the beta5 on that same computer?
Does it still work *right now*?

**Comment by E-Gwen** [comment]
I use Windows XP 32 Bit SP3 with full updates.

Yes, I try the beta 5 on the same computer.

I try several times, but it gives me the same results.


Envoyé: lundi 29 janvier 2018 à 20:43
De: "Filipe Coelho" <notifications@github.com>
À: falkTX/Carla <Carla@noreply.github.com>
Cc: Gwen <gaumend0@gmx.com>, Author <author@noreply.github.com>
Objet: Re: [falkTX/Carla] Carla 2.0.beta6 : "cx_Freeze : Python error in main script" with Windows 32 Bits version (#570)


Which windows version are you using? (XP, 7, 10, something else)
Did you try the beta5 on that same computer?
Does it still work right now?

**Comment by falkTX** [comment]
Might just be that the binaries are not compatible with XP.

In what PC did you try the beta5 on? That same one?
Was it really beta5, or was it a previous version?

**Comment by E-Gwen** [comment]
Yes, I try the beta 5 on the same PC.

 

It was really beta5, and it still runs (as the 1.2.4 version)


Envoyé: mardi 30 janvier 2018 à 14:13
De: "Filipe Coelho" <notifications@github.com>
À: falkTX/Carla <Carla@noreply.github.com>
Cc: Gwen <gaumend0@gmx.com>, Author <author@noreply.github.com>
Objet: Re: [falkTX/Carla] Carla 2.0.beta6 : "cx_Freeze : Python error in main script" with Windows 32 Bits version (#570)


Might just be that the binaries are not compatible with XP.

In what PC did you try the beta5 on? That same one?
Was it really beta5, or was it a previous version?

**Comment by jam-s** [comment]
I have the same same error message on W7 in 32bits.
I checked the compatibility of the binary to run on W7.
The beta 5 works very well.

The PC is an old Intel Pentium D processor with W7 SP1 version.

**Comment by falkTX** [comment]
The change that I see that might affect this, is that I activated/forced SSE2 on the libs used by Carla.
Carla requires something that provides SSE2 instructions, as otherwise audio operations can get too expensive on the CPU.

Please try this build and let me know if it works:
https://github.com/falkTX/Carla/releases/download/1.9.8/Carla_2.0-beta6-win32-nosse-test1.zip

**Comment by jam-s** [comment]
Yes , it's work :)

**Comment by falkTX** [comment]
Cool, thanks for testing.
When I get home later today I'll do a proper build. That one is missing SFZ and GIG file support.

**Comment by E-Gwen** [comment]
Yes, it works for me too, with Windows XP SP3 32 Bits fully updated.
I can now launch it. It will be a pleasure to test it.
Thank you very much.
Have a nice week.

E-Gwen.

**Comment by falkTX** [comment]
I forgot about this.. I have a new build which has all the features in a non-SSE optimized build for old PCs: https://github.com/falkTX/Carla/releases/download/1.9.8/Carla_2.0-beta6-win32-nosse.zip
Please try it and let me know if it still works for you.
If yes, use this build instead of the testing one I posted earlier.

If the build still works, I will close this issue :)

**Comment by E-Gwen** [comment]
Well, this last release doesn't work, neither with XP nor Vista 32 bits on a laptop.

I got the same error message as the very first release for Windows : ""cx_Freeze : Python error in main script".
But the first no-sse one works fine with both, even with Windows 7 32 bits, so...

Thank you for your attention.

E-Gwen.

**Comment by jam-s** [comment]
Hello,
Indeed this version does not work on W7 32bits.

**Comment by falkTX** [comment]
hmm I messed up somewhere then.. will do a new build shortly.

**Comment by E-Gwen** [comment]
I've got the same error message for the beta 7, except for the lines : 

Traceback (most recent call last):
	File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
	File ",\source\Carla.pyw", line 46, in <module>
	File "Z:\Shared\Personal\FOSS\GIT\falkTX\Carla\source\carla_host.py", line 2589, in iniHost
	File "Z:\Shared\Personal\FOSS\GIT\falkTX\Carla\source\carla_backend_qt.py", line 97, in __init__
	File "Z:\Shared\Personal\FOSS\GIT\falkTX\Carla\source\carla_backend.py", line 2176, in __init__
	File "C:\Python34\lib\ctypes\in __init__.py, line 351, in __init__
	OSError : [WinError 998] l'accès à cet emplacement mémoire n'est pas valide
                                                  (The direct ? memory access is not available) ?

**Comment by falkTX** [comment]
Are you using the 32bits-nosse build?

**Comment by E-Gwen** [comment]
No, sorry.

All right, I found it here ; 
https://github.com/falkTX/Carla/releases

It runs, thank you.

**Comment by falkTX** [comment]
nice, thanks for testing.
another little bug fixed :)
