### ISSUE TITLE
Lilvmm.hpp not found on Fedora 27

### ISSUE THREAD

**Issue by ycollet** [falkTX/Carla#571]
Hello,

I compile Carla from master branch on Fedora 27.
I meet compile problem:
```
Compiling CarlaPluginLV2.cpp
In file included from CarlaPluginLV2.cpp:25:0:
../../utils/CarlaLv2Utils.hpp:72:10: erreur fatale: lilv/lilvmm.hpp : No such file or directory
 #include "lilv/lilvmm.hpp"
          ^~~~~~~~~~~~~~~~~
```

pkg-config result on my machine:
```
$ pkg-config lilv-0 --cflags
-I/usr/include/lilv-0 -I/usr/include/serd-0 -I/usr/include/sord-0 -I/usr/include/sratom-0
```

**Comment by falkTX** [comment]
this is not system lilv, carla includes its own copy.
did you download the zip file of carla by any chance?
I suspect the symlinks in carla's code got broken.

**Comment by ycollet** [comment]
OK.
I just clone the repo, not downloaded the zip file.
I will try to do a fresh clone and see what happens.

Le 28/01/2018 à 18:58, Filipe Coelho a écrit :

**Comment by ycollet** [comment]
It's works with a rfesh clone.
Something was corrupted in the old one.

Le 28/01/2018 à 18:58, Filipe Coelho a écrit :

**Comment by falkTX** [comment]
closing this issue then.
