### ISSUE TITLE
Carla1.9.8(2.0b6): Wine (Windows) VST 32 + 64 bit: does not work

### ISSUE THREAD

**Issue by AzZzX** [falkTX/Carla#572]
Hi falkTX!
wine: cannot find '/usr/lib/carla/carla-discovery-win32.exe'
wine: cannot find '/usr/lib/carla/carla-discovery-win64.exe'
![carla-discovery-win64](https://user-images.githubusercontent.com/35890799/35481993-7c76270e-0426-11e8-8e6d-84f42b52d58f.png)

System: Linux Mint XFCE 18.3 lowlatency x64 + Jack (Wine 2.0.1)
![term system](https://user-images.githubusercontent.com/35890799/35481997-93a2f2ea-0426-11e8-9ac4-18a3af509763.png)
Synaptic: Carla packs
![synaptic carla](https://user-images.githubusercontent.com/35890799/35482031-f95ed37e-0426-11e8-9ad5-531007419130.png)
Synaptic: Wine packs
![synaptic wine](https://user-images.githubusercontent.com/35890799/35482043-0d8c9b06-0427-11e8-8549-c787afa508db.png)

PS: Linux VST 32 + 64 bit and LV2 works fine in Carla Standalone, and Carla VST. I tried to reinstall Carla and Wine packs in Synaptic, with no resultat.
Thnx a lot for U Work!

**Comment by falkTX** [comment]
Does your wine have Z: mapped to the root of the file system?

**Comment by AzZzX** [comment]
Thank you very much Dear Filipe! 
I add Z: to the root. Now win VST 64+32 work fine)
![_2018-01-30_12-19-13](https://user-images.githubusercontent.com/35890799/35561262-a24e1842-05a7-11e8-9009-ec43da2bbe73.png)

**Comment by falkTX** [comment]
Great! So it was rather simple :)
