### ISSUE TITLE
Nekobee GUI's broken

### ISSUE THREAD

**Issue by jam-s** [falkTX/Carla#573]
Hello, 

On W7 32 bits noly ,  The nekkobee GUI is empty. 
On the other hand, the little dog is alive. :) 

(versions beta 4,5 and 6)

**Comment by falkTX** [comment]
Likely an issue with the graphics driver.
Those UIs use OpenGL.

Can you describe the PC you're using Csrla on? specifically, what graphics card does it have?

**Comment by jam-s** [comment]
Ok 
W7 32bits Pentium D 2.80gHz + 4 GB ram corsair  + nvidia gforce7300LE.

**Comment by falkTX** [comment]
I don't know how to debug this on windows, unfortunately.
I guess you have the official nvidia drivers installed, correct? (not the ones from microsoft)

**Comment by jam-s** [comment]
mmh:
Nvidia Corporation 
Version 8.15.118593

On the other hand it is an old machine so I disabled all features and the control panel nvidia.

**Comment by falkTX** [comment]
well, this is a graphics driver issue in the end.
those UIs need OpenGL drivers to display properly. I will close this as wont-fix because I have no ways to fix this on my side.
