### ISSUE TITLE
Wine bridge not available (via KXstudio package)

### ISSUE THREAD

**Issue by ViktorNova** [falkTX/Carla#574]
This was working at some point on my machine but after updating recently I am no longer able to scan for Windows VSTs on my system (Ubuntu 16.04 64bit with KXStudio repos)

This is Carla 1.9.8 (2.0 -beta6) with carla-git packages and the wine64/win64 bridge packages installed as you can see on my terminal. 

![carlabug](https://user-images.githubusercontent.com/3234333/36176383-4682c352-10c7-11e8-89b3-41364d849ae8.png)

**Comment by falkTX** [comment]
They're now in experimental settings, which need to be enabled first.
See http://kxstudio.linuxaudio.org/News/?action=view&url=carla-20-beta6-is-here

**Comment by ViktorNova** [comment]
My apologies, I did not realize that! 
Thanks for pointing that out
