### ISSUE TITLE
Carla compiles without support of non-native plugins

### ISSUE THREAD

**Issue by suhr** [falkTX/Carla#575]
OS: Linux

**Comment by falkTX** [comment]
not sure what you mean here.
missing wine bridges? that's normal, there is a more complex setup for that.

**Comment by suhr** [comment]
![2018-02-18-202203_565x289_scrot](https://user-images.githubusercontent.com/65870/36354703-379a6fc2-14d0-11e8-9c3f-7782a63e3cb9.png)


Linux 32 bridges are missing too.

> that's normal, there is a more complex setup for that.

How do I ensure Linux32 and Wine bridges to be installed?

**Comment by falkTX** [comment]
run `make posix32` to build the 32bit bridges.

the wine bridges require a mingw compiler and wine developer tools (winegcc and its headers).
do you have that already?
If yes, first build the wine dll by running `make wine32 wine64`.
Then setup the environment for mingw32 and run `make win32` (I mean env vars here, CC, CXX, CFLAGS, etc). And do the same for mingw64 and run `make win64`

**Comment by suhr** [comment]
I guess there should be a few words in INSTALL.md.

> run make posix32 to build the 32bit bridges

Hm, it fails to build with `skipping incompatible /usr/lib/liblo.so`

**Comment by falkTX** [comment]
Yeah, you'll need 32bit development libs to build this, or a chroot environment.
Do you even have plugins that are available only in 32bit, why are you trying to build this?
The wine bridges is going to be a lot of work... be sure you're prepared for it.

**Comment by suhr** [comment]
> The wine bridges is going to be a lot of work... be sure you're prepared for it.

That's unfortunate. Airwave 1.3.3 hangs Carla, so the only microtonal sampler I had doesn't work anymore.

I hoped Carla could replace it.

**Comment by falkTX** [comment]
Maybe it can, but carla uses a real windows compiler to make sure it works as best as it can - it's not built only using wine tools. This makes the build more complex.

But Carla is already on AUR, kxstudio repos and there's pre-compiled binaries too.
All of them provide the wine bridges.

Are you using a specific distro that can't use any of those?

**Comment by suhr** [comment]
> But Carla is already on AUR, kxstudio repos and there's pre-compiled binaries too. All of them provide the wine bridges.

Gentoo is a source-based distro, so I used to compile Carla from sources. But binaries work too, so I'll use them.

Thanks for help anyway!
