### ISSUE TITLE
[Feature Request] Add 32 and 64 channel variant to Carla-Patchbay plugins

### ISSUE THREAD

**Issue by RCJacH** [falkTX/Carla#579]
Necessary for bouncing drum tracks with multiple microphones.

**Comment by RCJacH** [comment]
Hmm I see 32chan variant within Carla instances, but cannot find such vst or lv2 plugins, either in reaper or terminal ls. Am I missing something?
The reason for 64 channel is that with BFD or Superior Drummer or other multi-miced drum libraries, in order to fine tune with DAW plugins, I have to send each microphone output to a separated channel, thus the required channels usually goes up beyond 32 especially with all those ambient mics, this matters when building track template (setting up everything upfront and mute unnecessary tracks in actual production). 
However, I did manage to cut the output to exactly 32 channels in my normal setups so that may suffice.
BFD3 does only have 32 outputs but since I don't see Macro parameter/controller in Carlo I guess I have to set them up in the DAW so it would still be nice to have different outputs.

**Comment by falkTX** [comment]
hmm for LV2 I see it clearly with lv2ls, and this command works:
`jalv.gtk http://kxstudio.sf.net/carla/plugins/carlapatchbay32`

for the VST, the 32chan version is missing, so I guess you're using VST.
I'll fix this soon, adding the 32ch out variant.

**Comment by falkTX** [comment]
Now handled in 3ea17b46113a83148e3d9a9b376dea3380678131
