### ISSUE TITLE
Carla 2.0 beta6 makefile issue on Linux for WINE_32BIT_FLAGS and WINE_64BIT_FLAGS

### ISSUE THREAD

**Issue by piep-piep** [falkTX/Carla#581]
Hello falkTX,

thank you for your incredible work.

To be compliant with the Debian's package "libwine-development-dev:i386" and "libwine-development-dev:x86_64" could you modify a bit the makefile : Carla-1.9.8/source/jackbridge/Makefile

from:
WINE_32BIT_FLAGS = $(32BIT_FLAGS) -L/usr/lib32/wine -L/usr/lib/i386-linux-gnu/wine -L/opt/wine-staging/lib -L/opt/wine-staging/lib/wine
to
WINE_32BIT_FLAGS = $(32BIT_FLAGS) -L/usr/lib32/wine -L/usr/lib/i386-linux-gnu/wine -L/usr/lib/i386-linux-gnu/wine-development -L/opt/wine-staging/lib -L/opt/wine-staging/lib/wine

idem for x86_64
from
WINE_64BIT_FLAGS = $(64BIT_FLAGS) -L/usr/lib64/wine -L/usr/lib/x86_64-linux-gnu/wine -L/opt/wine-staging/lib64 -L/opt/wine-staging/lib64/wine
to
WINE_64BIT_FLAGS = $(64BIT_FLAGS) -L/usr/lib64/wine -L/usr/lib/x86_64-linux-gnu/wine -L/usr/lib/x86_64-linux-gnu/wine-development -L/opt/wine-staging/lib64 -L/opt/wine-staging/lib64/wine

it will avoid the error : 
ld: Relocatable linking with relocations from format elf64-x86-64 (/usr/lib/x86_64-linux-gnu/wine-development/libwinecrt0.a(dll_entry.o)) to format elf32-i386 (jackbridge-wine32.yacHLg.o) is not supported
winebuild: ld failed with status 1
winegcc: /usr/lib/wine-development/winebuild failed

thank you.
Piep

**Comment by falkTX** [comment]
sure thing, why not.
I'll do this later today.
