### ISSUE TITLE
Carla 2.0.beta6 : build on debian / question on Makefiles proposed

### ISSUE THREAD

**Issue by piep-piep** [falkTX/Carla#583]
Hello, 

my goal was to build carla-bridge-win32.exe, carla-bridge-win64.exe on debian 9.
if they are still available on this 1.9.8/Carla_2.0-beta6-src.tar.gz (?)

and I succeeded to build them (and others stuff) by changing most of the makefiles for "all:" to include posix32, posix64, win32, win64.

I'm a bit lost on the makefiles supermarket (but I can  longer shop happily ;-) )
is it the standard way to build or is there any other better way ?

here are my changes done on Makefiles.
```
$ for i in ./source/bridges-plugin/Makefile ./source/discovery/Makefile ./source/jackbridge/Makefile ./source/modules/lilv/Makefile ./source/modules/rtmempool/Makefile ./source/modules/water/Makefile; do echo ${i}; grep "all:" ${i}; done

./source/bridges-plugin/Makefile
#all: native
all: native posix32 win64 posix64 win32 win64
./source/discovery/Makefile
#all: native
all: native posix32 posix64 win32 win64
./source/jackbridge/Makefile
all:      $(MODULEDIR)/$(MODULENAME).a posix32 posix64 posix32e posix64e win32 win64 win32e win64e wine32 wine64
./source/modules/lilv/Makefile
all:     $(MODULEDIR)/$(MODULENAME).a posix32 posix64 win32 win64
./source/modules/rtmempool/Makefile
all:     $(MODULEDIR)/$(MODULENAME).a posix32 posix64 win32 win64
./source/modules/water/Makefile
all:     $(MODULEDIR)/$(MODULENAME).a $(MODULEDIR)/$(MODULENAME).files.a posix32 posix64 win32 win64
```

best regards,
Piep

**Comment by falkTX** [comment]
the entire code is there yes.
but you can't just simple build win32 and win64 on a native toolchain and expect it to work.

you need mingw setup and wine devel
and there is no need to modify makefiles, just add the rule to build after the make command, like `make all posix32 posix64`

for building win32 and win64, make sure to setup the build environment for mingw compiler, then start the build.

**Comment by piep-piep** [comment]
ok. thank you very much for your answer

**Comment by falkTX** [comment]
how's the building process going?

**Comment by piep-piep** [comment]
it's fine I succeeded to build . I have to test my binaries now.

thank you


Le 10/03/2018 à 17:38, Filipe Coelho a écrit :

**Comment by falkTX** [comment]
Forgot to close this ticket back then, doing it now. sorry for the noise
