### ISSUE TITLE
The GUI of calf plugins Freezes when trying to close it

### ISSUE THREAD

**Issue by legocef01** [falkTX/Carla#587]
Hi,
I'm on fedora 26 and I downloaded the binary of carla 1.9.8 (2.0-beta6)

When I load any calf plugin and open the GUI, all things work fine. But when I try to close the GUI of a calf plugin, the GUI freezes and after about 10 seconds, the system ask me to kill the GUI. And when I kill, the corresponding calf plugin becomes useless in carla unless I remove it and add it aigain!

when I kill, this is what carla writes in logs : 

>waitForClient(process) timed out
CarlaRingBuffer::tryWrite(0x7ffea17c58f0, 4): failed, not enough space

after kill, when I try to reload the GUI (activate GUI button),  this is what carla writes in logs many times untill I desactivate the GUI button  : 

> Carla assertion failure: "fProcess != nullptr" in file CarlaPluginBridge.cpp, line 127
Carla assertion failure: "fProcess != nullptr" in file CarlaPluginBridge.cpp, line 127
Carla assertion failure: "fProcess != nullptr" in file CarlaPluginBridge.cpp, line 127
Carla assertion failure: "fProcess != nullptr" in file CarlaPluginBridge.cpp, line 127
Carla assertion failure: "fProcess != nullptr" in file CarlaPluginBridge.cpp, line 127
Carla assertion failure: "fProcess != nullptr" in file CarlaPluginBridge.cpp, line 127
Carla assertion failure: "fProcess != nullptr" in file CarlaPluginBridge.cpp, line 127
Carla assertion failure: "fProcess != nullptr" in file CarlaPluginBridge.cpp, line 127

I have the same behaviour with experimental features enabled or disabled.

Thanks for your support.

**Comment by falkTX** [comment]
what version of calf is this?
I had this issues with them before, which I already fixed.

**Comment by legocef01** [comment]
It's calf version 0.0.60

**Comment by falkTX** [comment]
Ah, please update to 0.90.0 then.
I believe this was fixed there, the only remaining issue being that GUI updates for calf plugins are slow in carla.
This can be fixed by backporting this commit: https://github.com/calf-studio-gear/calf/commit/934949fc2bb06d794b90fd7e017f1584071b7c86

If you can't update calf manually yourself, please ask the package maintainer in fedora.
