### ISSUE TITLE
Symlinks needed for Export LV2 on Windows

### ISSUE THREAD

**Issue by E-Gwen** [falkTX/Carla#588]
Hi,

When you try to export a LV2 plugin, after enabling "enable experimental features" in "Settings", you get this error message : 

"Operation Failed.
Failed to create symbolic link of plugin binary"

In C:\\\Local\Temp\Carla, a file that contains "manifest.ttl", "plugin_name.ttl", and "plugin_name.xml" is created. ("plugin-name" is for the name you choose)
Notice that no .dll file is created.

Hope it's a little help.

E-Gwen.

**Comment by falkTX** [comment]
What version of windows is this?
I did not tried on Windows, but I know symlinks are not easy there...

**Comment by E-Gwen** [comment]
It happens with "Windows Vista SP2 32 bits Family Edition" inside an F3Se ASUS model.

**Comment by falkTX** [comment]
I just added some more aggressive things to try to make linuxsampler behave better...
Might fix our issue, might change nothing at all... testing welcome.
Will push the new changes to the kx repos now, beta7 release will include these changes.

**Comment by falkTX** [comment]
ah, I know what happens. symlinks just not working under mingw compiler that I use for windows binaries.
I will take care of this for beta8, where I plan to give a little more attention to the windows builds.

**Comment by E-Gwen** [comment]
Thank you for your attention.

Where can I download this beta7 to test it ?

Nice summer.

**Comment by falkTX** [comment]
As I said, I will take care of this for beta8, the just-released beta7 does not have this yet.

**Comment by E-Gwen** [comment]
Yes, of course, I understood.
But I can't wait trying the new release.
To try the beta version, go to : https://github.com/falkTX/Carla/releases

See you.

**Comment by falkTX** [comment]
Now fixed in latest git, tested to work in a win7 VM.
Next release will include this feature :)
