### ISSUE TITLE
Carla steals system audio?

### ISSUE THREAD

**Issue by rampartisan** [falkTX/Carla#589]
Hey everyone,

Running the carla.app on mac osx with the core audio driver all audio output except carla is muted. Is this expected behavior?

**Comment by falkTX** [comment]
Good question... I is a flag set there unintentionally that might be settings this. (RTAUDIO_HOG_DEVICE)
It was there for testing, only noticed it now that it's only implemented on CoreAudio and OSS.

I will remove it for the next beta release.

**Comment by rampartisan** [comment]
Thanks!

I have just tried compiling carla libs with all references to RTAUDIO_HOG_DEVICE removed and unfortunately I still have no system audio(both with carla.app and python scripts)

Am I missing a thing?

**Comment by falkTX** [comment]
You build carla and used its libcarla_standalone2.dylib on macOS?
(I'm surprised someone is actually building from source on macOS, that's all...)

I dont really have an idea about this though, sorry.
But you have access to the code, if you spot anything relevant just let me know.

**Comment by falkTX** [comment]
This has now been fixed in 2.1-RC1
Was also fixed in 2.0, forgot to close the issue back then
