### ISSUE TITLE
"env: ‘/usr/bin’: Permission denied"

### ISSUE THREAD

**Issue by Taikakim** [falkTX/Carla#594]
I'm really new to Linux, sorry if this is something super obvious, but I get that error in the logs once for each time Carla tries to access Wine. I'm not sure what permissions to set, since the user already has the permissions for that location.

So Carla finds and tries to load Windows VSTs, but Wine does not work it seems. Windows installers run from the command line at least, so it should be set up correctly.

**Comment by falkTX** [comment]
likely you dont have the right path to wine in the settings.
open settings, make sure experimental, bridges and wine bridges are all enabled.
then on the wine tab, specify a path to "wine" that works for you. I imagine /usr/bin/wine should do the trick

**Comment by Taikakim** [comment]
That's what I thought so I double checked everything, both path /usr/bin and wineprefix /home/kim/.wine are right. I have wine-rt installed too. WINEPREFIX environment variable was missing for some reason I just now realized. All those options are checked both under experimental and Wine settings.

I have wine-staging installed, but it should not interfere since the binaries are in a different place?

It's a fresh install of Ubuntu 17.1 running an older 3.X low latency kernel, not much things installed yet so things should not be too messed up.

**Comment by falkTX** [comment]
Having /usr/bin/ as the path is what is making this not work, that's the wrong path to put there.
It wants the path to the wine binary, not the folder where "wine" exists in.
So in your case it could be either /usr/bin/wine or /opt/wine-staging/bin/wine

**Comment by Taikakim** [comment]
Ah, it started scanning. I specified just the path before since "Path to 'wine' binary" was requested in the settings, since there is not a folder of that name under /bin.

This so much more convenient than adding everything by hand like in Airwave, thank you :)

**Comment by falkTX** [comment]
Alright, great to work it's working. I'll close the issue then.

and by the way, you can drag&drop dll files from your file manager into the carla rack view, if you want to quickly load a plugin without having to scan it first. :)
