### ISSUE TITLE
Save image save always as a png

### ISSUE THREAD

**Issue by trebmuh** [falkTX/Carla#597]
Even when choosing a jpeg format, it saves a png image.

Same issue than here: https://github.com/falkTX/Cadence/issues/208

**Comment by falkTX** [comment]
Check locally and cannot reproduce.
Likely an issue with the file dialog under gnome? the dialog not returning a path with the right extension.

**Comment by trebmuh** [comment]
mmh OK.
I've got close to no time at all for this week so I'll try to reproduce probably next week.
IIRC, it was with MATE. I'll let you know on my next try.

**Comment by falkTX** [comment]
no worries, I took 3 months to reply to you here, so you can take your time too..

**Comment by trebmuh** [comment]
Ok, so retrying this one from GIT fcc1597 , I can see the issue is still here. But I've looked a bit further. So, when bing asked to fill a name, if I type:

- myimage.jpg, it does work (ie: the image is saved as a jpeg image)
- myimage, the image is saved as a png

In those 2 cases, whatever is I chooses the png or the jpeg format in the bottom-right corner's dropdown menu, it doesn't make any difference. One needs to add the .jpeg extension **in the image name field** to get it right.

**Comment by falkTX** [comment]
carla sets the file format depending on the filename, so without a proper extension it is just not possible to know what to do...
on the kde file dialog, the extension is added automatically

**Comment by trebmuh** [comment]
Understood.

From an user point of view, I though that selecting the "JPEG" format in the dropdown menu was indicating to Carla in which format I wanted the image to be saved in.

**Comment by falkTX** [comment]
In theory, that would be enough, yes.
the dialog would then add the suffix if it is not in the filename. some file dialogs do, some dont.
afaik we only get the chosen filename in qt at the end of such dialog, so it becomes impossible to know which option was chosen.
maybe there is an alternative, but I dont know it yet.

**Comment by falkTX** [comment]
I assume this is now really fixed, but please confirm.
