### ISSUE TITLE
support tempo-sync with JACK

### ISSUE THREAD

**Issue by wolftune** [falkTX/Carla#6]
Plugins that don't even necessarily do this themselves should still be made to work in Carla.

Carla could simply have a way to make a parameter be synced in some relative way to the JACK tempo. This is especially useful for things like echo / delay.

**Comment by mxmilkiib** [comment]
To get the tempo number, https://github.com/ryukau/LV2Plugins/tree/master/lv2cvport/CV_TimeInfo

Then one can use a math CV plugin to half, third etc that figure to
