### ISSUE TITLE
Completely hide the Logs tab when configured to console output

### ISSUE THREAD

**Issue by trebmuh** [falkTX/Carla#602]
When using the _Configure Carla -> Main -> Interface -> Show console output in Logs tab (needs engine restart)_ to get the logs output in the console, and after restarting Carla, it works as expected (ie: the messages are outputed in the terminal if/when Carla is launched from it). That said, the Logs tab is still present on the main window.

It'd be great/consistent if the tab would be completely hidden from Carla's main window.

**Comment by falkTX** [comment]
I decided against this.
It is a really minor thing, and having auto-hide can cause edge cases.
