### ISSUE TITLE
Carla-rack and transport

### ISSUE THREAD

**Issue by trebmuh** [falkTX/Carla#603]
_(Carla build from https://github.com/falkTX/Carla/commit/04b5999f485cc2a2947ea48153a658edb79a319f)_

Even when the experimental feature is ticked on (and thus, is working when Carla is launched as a standalone app), it stay greyed out when using Carla through Carla-rack LV2. Tested with jalv.select (jalv -s mode), and Qtractor 0.8.6 .

**Comment by falkTX** [comment]
well, yes. if carla is a plugin, it cannot control the transport.
the host is the one with the control.

**Comment by trebmuh** [comment]
OK that makes sens. Would that be possible then to hide the transport tab in carla-as-a-plugin? It's confusing to be able to select the "Configure Carla -> Experimental -> Enable Transport Controls", seeing the tick-box being ticked, and still have the transport greyed out.

Going further on that, It'd be even more perfect to have that tick-box being enforced to non-ticked when using carla-as-a-plugin for consistency.

_(I acknowledge that this is not a big deal)_
