### ISSUE TITLE
[Feature request] sf3 support

### ISSUE THREAD

**Issue by trebmuh** [falkTX/Carla#607]
Since SF3 is now supported within fluidsynth, it is now possible to support SF3 in software depending on fluidsynth which Carla is.

See https://github.com/LMMS/lmms/pull/3895 and https://github.com/LMMS/lmms/issues/3286 .

**Comment by falkTX** [comment]
This needs new fluidsynth version.
I tried to update it before, but failed to build it.
To be done someday. Perhaps if you can point me to a good sf3-only file it will motivate me to support it faster :)

**Comment by trebmuh** [comment]
> Perhaps if you can point me to a good sf3-only file it will motivate me to support it faster :)

That is right that a lot of sf3 are available as well as a sf2. This is because of its purpose I guess : "_same as an sf2, but lighter weight because it's OGG and not WAV_".

Promise, if I find one, I'll tell you!

**Comment by falkTX** [comment]
I believe carla should support this now.
It will search for sf2 and sf3 files. The rest is up to fluidsynth to handle.
Please confirm.

**Comment by falkTX** [comment]
@trebmuh ping :)

**Comment by milkmiruku** [comment]
ftp://ftp.osuosl.org/pub/musescore/soundfont/MuseScore_General/MuseScore_General.sf3

Loads and make piano sounds for me, though I turned all the reverb/chorus dials up and it didn't sound different.

**Comment by falkTX** [comment]
I see in the kxstudio builds at least, sf3 is not supported.
Need to update the static fluidsynth so it handles this.
It is a good idea to disable sf3 automatically.
I will close this issue, since carla itself can handle it now, it is something else that needs updating&check,

PS: regarding the chorus and reverb, these are soundfont specific, and also something that fluidsynth does internally. carla only tells fluidsynth to activate the parameters.

**Comment by trebmuh** [comment]
@falkTX I've rebuild a carla from GIT https://github.com/falkTX/Carla/commit/fcc1597bdf736daaa3bbc625bc5c07cdcde85aa6 and the SF3 is working. Thanks!

I've spotted a small buggish thingy: while it reads the SF3, the "type column" is set to SF2. That's not a big deal but it did confuses me for a few minutes while I was searching for a SF3 with the help of the "type" column.

![carla-sf3](https://user-images.githubusercontent.com/8705846/45390859-165a6900-b621-11e8-980d-a3e782c69531.png)

Please, let me know if you prefer a new issue to be open or if you're fine with being here.

Once again, thanks!

**Comment by falkTX** [comment]
yeah, not something I am going to "fix" right now.
SF2 is just the type of plugin/item in the list.
Naming it "SoundFont" might be an issue for stupid copyright reasons.

If it is something you really care about, open a new bug report for it.
But know in advance it is not something I will change in (very soon coming) 2.0 release.

**Comment by trebmuh** [comment]
Done here: #739 .
