### ISSUE TITLE
Add plugin window: sorting by table column resets filters

### ISSUE THREAD

**Issue by SpotlightKid** [falkTX/Carla#610]
To reproduce:

- Open "Add plugin" window.
- Show "Special Filters" checkboxes.
- Select "VST", "Instruments" and "Native".

==> Only native VST instrument plugins are shown.

- Click table header "Name".

==> Table is sorted by plugin name, but filtering on format VST is lost, LV2 plugins are now shown too.

**Comment by falkTX** [comment]
I cannot reproduce this.
Which version of carla do you have? latest git? Is it using qt5 or qt4?

**Comment by SpotlightKid** [comment]
I'm using the [carla-git](https://aur.archlinux.org/packages/carla-git/) AUR package (which is maintained by me), i.e. compiled on my machine from the git repo (gebd3f2e5). Qt version is 5.10.1.

Here's a screen shot that shows the behavior. Notice how "VST" format is selected and sorting by "Label" is activated but all plugin formats are listed. If I deselect "VST" and select it again, the list is filtered correctly again.

![carla-add-plugin-sort-vs-filter](https://user-images.githubusercontent.com/5719151/38255466-20cdeb26-375c-11e8-8cff-c399ca2ae8aa.png)

**Comment by SpotlightKid** [comment]
I'm still getting this with the latest git version?

Does somebody else get the described behaviour?

**Comment by SpotlightKid** [comment]
Is there any more info I can provide?

**Comment by falkTX** [comment]
Not really, I just have to try to reproduce.
So far on Ubuntu 14.04 and 16.04 I cannot.

The issue is open, so if someone else has it, I hope they leave a comment here too...
(same applies to other bugs)

**Comment by pdesaulniers** [comment]
While I can't reproduce, I have a very similar issue. I'm also using the carla-git package from the AUR.

After following SpotlightKid's procedure, even if I select a different plugin format, only VST plugins are shown:
![2018-04-20-12 55 35](https://user-images.githubusercontent.com/23723605/39063897-7c95ae08-449a-11e8-9e63-e744fb82e715.png)

In other words, the plugin format filters that were inactive when I sorted by table column are now ignored.

The only way to revert this that I've found is to close and reopen the window.

**Comment by trebmuh** [comment]
Cannot reproduce either (Debian Stretch).

**Comment by pdesaulniers** [comment]
I cannot reproduce this anymore.

**Comment by falkTX** [comment]
Maybe it was a PyQt bug, as the explained actions to trigger the issue seem quite normal usage for me on carla, and I never got the bug myself.
@SpotlightKid please confirm if you still have the issue after getting all your distro updates

**Comment by SpotlightKid** [comment]
Yes, issue is still there. Just recompiled carla from git with an up-to-date system. Qt is at 5.11.0 now.

**Comment by falkTX** [comment]
What is the easiest way to have an archlinux-like system installed in a VM?
Manjaro..? I really need to reproduce this in order to fix it. In my current system it all works fine hmm

**Comment by SpotlightKid** [comment]
You can probably just boot a Manjaro install image in Virtualbox. It functions as a live system as well (but without persistence, so don't shut down the vm, just freeze it).

**Comment by eeickmeyer** [comment]
Cannot reproduce in Ubuntu 18.04 or 19.04.

**Comment by SpotlightKid** [comment]
I can't reproduce this anymore with recent versions of Carla.

It is a bit unsatisfying to have no idea what might have caused this, but that's the way it is. ;)
