### ISSUE TITLE
carla --no-gui won't  load

### ISSUE THREAD

**Issue by smrg-lm** [falkTX/Carla#612]
When trying to run a carla session with no GUI it terminates immediately after posting the next message:

$ carla -n zyn.carxp
Carla 1.9.8 (2.0-beta6) started, status:
  Python version: 3.5.2
  Qt version:     5.5.1
  PyQt version:   5.5.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
libjack.so.0 loaded sucessfully!
$

To try it just make a session that loads and ZynAddSubFX. Without the -n option it works as normal. I'm on Ubuntu 16.04.

**Comment by smrg-lm** [comment]
There it is:

$ carla -n zyn.carxp 
Carla 1.9.8 (2.0-beta6) started, status:
  Python version: 3.5.2
  Qt version:     5.5.1
  PyQt version:   5.5.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
libjack.so.0 loaded sucessfully!
Carla assertion failure: "path.startsWith ("./") || path.startsWith ("../")" in file files/File.cpp, line 222
Carla assertion failure: "file.existsAsFile()" in file CarlaEngine.cpp, line 1131
Failed to load selected project file, possible reasons:
Requested file does not exist or is not a readable file

$ carla -n ./zyn.carxp # or absolute path ok!

I was using relative paths with implicit ./ in terminal

**Comment by smrg-lm** [comment]
As a consequence of it working, ctrl-c to quit crashes wine VSTs, it doesn't happens when running and closing with GUI:

^Cwine: Unhandled page fault on read access to 0x00000000 at address 0x489736 (thread 002c), starting debugger...
ScopedPluginAction(0) - blocking START
ScopedPluginAction(0) - blocking DONE
waitForClient(process) timed out
waitForClient(deactivate) timed out
CarlaPluginBridgeThread::run() - bridge refused to close, force kill now

**Comment by falkTX** [comment]
I noticed that error sometimes too, seems like a null pointer de-reference somewhere.
Please open an new issue for that. I am closing this one now, since you got it working.
