### ISSUE TITLE
Disto::Fx Version 1.4 Free issue 

### ISSUE THREAD

**Issue by martinbangens** [falkTX/Carla#615]
Im using carla 2.0 beta6 as an plugin with Renoise on standard KXStudio 64-bit install
Disto::Fx works fine but when saving the Renoise song and closing the program then open Renoise and open the song again all parameters in Disto are down to null and there is no sound from the plugin :(
My sound is gone and lost. this plug in is important to me :(

**Comment by martinbangens** [comment]
When I change the plugin sound Renoise doesn't ask to save and doesn't seem aware the the plugin was actually changed, I can save the sound as file but its no so nice

**Comment by falkTX** [comment]
This should be fixed now (the original report regarding state not being loaded properly), please confirm.
(The packages on the kxstudio repos are updated)

Regarding no "dirty" flag being set yet, this is something carla still needs to do.
Feel free to open a new feature request for this.

**Comment by martinbangens** [comment]
The VST Plug-in is now working correctly, thank you <3

**Comment by falkTX** [comment]
thanks for confirming!
