### ISSUE TITLE
Carla patchbay not showing jack graph

### ISSUE THREAD

**Issue by smrg-lm** [falkTX/Carla#617]
After the previous package update patchbay tab of Carla is not showing jack connections anymore on Ubuntu 16.04.

**Comment by falkTX** [comment]
It works for me here.
Do you get any error messages in the logs? what engine processing mode are you using?

**Comment by smrg-lm** [comment]
it's the same with any engine and there is no error messages, experimenting, the only thing I see is that setting canvas theme throws:

======= Starting engine =======
======= Engine started ========
CarlaEngine::setOption(1:ENGINE_OPTION_PROCESS_MODE, 1, "") - Cannot set this option while engine is running!
CarlaEngine::setOption(1:ENGINE_OPTION_PROCESS_MODE, 1, "") - Cannot set this option while engine is running!
CarlaEngine::setOption(12:ENGINE_OPTION_AUDIO_DEVICE, 0, "") - Cannot set this option while engine is running!
CarlaEngine::setOption(9:ENGINE_OPTION_AUDIO_NUM_PERIODS, 2, "") - Cannot set this option while engine is running!

**Comment by smrg-lm** [comment]
User mistake... sorry, it is shown but not centred and very zoomed out.
