### ISSUE TITLE
MIDI CC controls stuck on Carla assertion failure: "param >= MAX_MIDI_VALUE" 

### ISSUE THREAD

**Issue by Rippert** [falkTX/Carla#619]
On latest Master branch commit:
`commit 813fd4ead7fa712234c1dd0b19f104217bd2000f
Author: falkTX <falktx@gmail.com>
Date:   Mon Apr 9 09:15:25 2018 +0200`

MIDI continuous controllers don't work. Every time a CC message is sent to Carla, the log shows:
`Carla assertion failure: "param >= MAX_MIDI_VALUE" in file CarlaEngineData.cpp, line 35`

I only see those log entries for CC messages, not for program change or note on messages.

**Comment by progwolff** [comment]
Can confirm.
