### ISSUE TITLE
Feature request: MIDI Channel Filter but also with "Off" event-out

### ISSUE THREAD

**Issue by milkmiruku** [falkTX/Carla#621]
Two outputs, one for On, the other for Off, so, with instruments on different channels, one could build a chain of MIDI effects with insert control.

Extra feature potential: three outputs, the third a Thru, which passes everything so one could do a form of [half-normal](https://www.misterpatchbay.com/normaling/normal.html) style patching.

**Comment by falkTX** [comment]
Not sure if I understood this request.
Feel free to make a PR for it, of course :)

**Comment by milkmiruku** [comment]
Thanks for the merge!

Maybe I missed something, but the internal version has yourself as the Maker;
![rose_2018-06-28-10 18 57](https://user-images.githubusercontent.com/108225/42025984-df328c08-7abd-11e8-8d00-e62c5614a719.png)

**Comment by falkTX** [comment]
The plugin meta-data is cached, so you get old data there.

here is my window:

![screenshot_20180628_113149](https://user-images.githubusercontent.com/1334853/42026223-da3f6f00-7ac6-11e8-9296-e8a573bb547f.png)

**Comment by milkmiruku** [comment]
Grand, cheers :)
