### ISSUE TITLE
harrison lv2 plugins dont update gui

### ISSUE THREAD

**Issue by occulkot** [falkTX/Carla#624]
Ive tried to run harrison lv2 plugins inside carla host and found out that gui is not updating.
Plugin itself change its behaviour, i see parameters inside carla gui beeing updated but plugin itself dont update.

Ive tried to find help on harrison forum and got reply from one of developer, quote:

> This is a known issue. The XT-* plugin GUIs depend on the host to confirm the change. There are also a few other plugin UIs that work that way.
> Say you use the mouse to move a knob to "10" but the corresponding parameter is automated in the host and stays at "11", so your change does nothing and the GUI should not move to "10" in the first place.

**Comment by falkTX** [comment]
Carla now implemented the needed LV2 bits to get this working.
Robin (@x42) will update the plugins, as a small change in their meta-data is needed to report to the host of the expected behavior.
With an updated Carla and (upcoming) updated Mixbus/Harrison plugins, this bug is fixed.
