### ISSUE TITLE
Freetype font renderer for windows build

### ISSUE THREAD

**Issue by nick87720z** [falkTX/Carla#628]
I just tried Carla for win64 under wine64. By default qt5 uses native font renderer on win, but freetype also may be enabled. What is interesting, with default renderer birdview has string font rendering issue, giving it quite annoying uglyness. Just look to screenshots:

Default renderer:
![carla-wine-patchbay-font-default](https://user-images.githubusercontent.com/3896190/39957410-3b9731fa-560c-11e8-97c8-bb34ec4255c3.png)
Freetype renderer:
![carla-wine-patchbay-font-freetype](https://user-images.githubusercontent.com/3896190/39957411-448c95fc-560c-11e8-91b6-c0353a372bd5.png)
Of course, font itself is improved not as close as in linux, but looks better (also look to canvas itself).
To force freetype for qt5 app, create qt.conf in one dir with executable and add these lines to it:
```
[Platforms]
WindowsArguments = fontengine=freetype
```
Found here: https://stackoverflow.com/questions/21641968/use-freetype-on-windows-with-qt5

upd: I'm not sure, how it looks in windows... Yet may be true for mac too.

**Comment by falkTX** [comment]
Looking into windows specific issues, I noticed this that I had forgotten.
Added in the codebase now, thanks for the tip!
