### ISSUE TITLE
carla-discovery on Ubuntu 18.04

### ISSUE THREAD

**Issue by Sir-hennihau** [falkTX/Carla#630]
Hi,
is there  a way to install 

- carla-discovery-posix32
- carla-discovery-win32
- carla-discovery-win64

on a Ubuntu 18?

I added the kxstudio repos to my ppa's, but apt can't find any related packages. Those libraries are needed to run Windows VST's in Carla. Is there a way to get this working?

**Comment by falkTX** [comment]
The packages are named carla-bridge-...
So look for those in synaptic or whatever other tool you use, and you'll be able to install them.

For reference, in my system I have this:
```
$ dpkg -l | grep carla-bridge
ii  carla-bridge-linux32                        2:1.9.8+git20180508                               i386         audio plugin host (linux32 bridge)
ii  carla-bridge-linux64                        2:1.9.8+git20180508                               amd64        audio plugin host (linux64 bridge)
ii  carla-bridge-win32                          2:1.9.8+git20180124                               amd64        carla win32 bridge
ii  carla-bridge-win64                          2:1.9.8+git20180124                               amd64        carla win64 bridge
ii  carla-bridge-wine32                         2:1.9.8+git20180124                               i386         carla win32 bridge (wine DLL)
ii  carla-bridge-wine64                         2:1.9.5+git20160114                               amd64        carla win64 bridge (wine DLL)
```

**Comment by Sir-hennihau** [comment]
Synaptic does not show me any packages related to "carla" or "carla-bridge". 

"kxstudio-repos" and "kxstudio-repos-gcc5" are installed and enabled according to synapse, though.

apt can read from the kxstudio ppa, too.

```
sudo apt update
Hit:1 http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu bionic InRelease
... 
...    
Reading package lists... Done                      
Building dependency tree       
Reading state information... Done
All packages are up to date.

```

**Comment by Ghoost666** [comment]
same problem here on fedora 38... any solution?
