### ISSUE TITLE
KXStudio repositorys does not contain packages

### ISSUE THREAD

**Issue by Life-is-easy** [falkTX/Carla#633]
I can not install from KXStudio Repositorys. **Ubuntu 18.04**.

Ran the instructions

```
# Install required dependencies if needed
sudo apt-get install apt-transport-https software-properties-common wget

# Download package file
wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_9.5.1~kxstudio3_all.deb

# Install it
sudo dpkg -i kxstudio-repos_9.5.1~kxstudio3_all.deb

# Install required dependencies if needed
sudo apt-get install libglibmm-2.4-1v5

# Download package file
wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos-gcc5_9.5.1~kxstudio3_all.deb

# Install it
sudo dpkg -i kxstudio-repos-gcc5_9.5.1~kxstudio3_all.deb
```

`sudo apt update `throws KXStudio as a repository:
`Hit:2 http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu bionic InRelease`

But installing from it results in an error.

```
sudo apt install carla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package carla is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'carla' has no installation candidate

sudo apt install carla-git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package carla-git
```

I can not install other software from the KXStudio repository with either apt or synapse. I would build from scource, but I'll need the carla-bridge-... plugins afterwards, too.

**Comment by falkTX** [comment]
The instructions are for enabling the repositories.

After you do that, you should update the software lists, eg:
`sudo apt-get update`

**Comment by Life-is-easy** [comment]
I already run `sudo apt-get update`.
Still no carla or carla-git package are found.

**Comment by falkTX** [comment]
Something is odd then.. I have 18.04 in my machine, and installed it from scratch for the ISO preparations a few times without issues.

**Comment by Life-is-easy** [comment]
You think it could relate to my machine being upgraded from 16.04 -> 17.10 -> 18.04?

**Comment by falkTX** [comment]
oh, that would be the reason for sure..
purge the kxstudio-repos packages first, then try again.
like this:
`sudo apt-get purge kxstudio-repos*`

**Comment by Life-is-easy** [comment]
Could fix it by doing a fresh installation of Ubuntu. Thanks for your help.
