### ISSUE TITLE
No rule to make target `features_print_external_plugins'

### ISSUE THREAD

**Issue by suedwestlicht** [falkTX/Carla#636]
```
make features CARLA_ZYN_COMPAT=true EXTERNAL_PLUGINS=true
---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: YES
make: *** No rule to make target `features_print_external_plugins', needed by `features'.  Stop.
```

The same happens when doing 
```
make install CARLA_ZYN_COMPAT=true EXTERNAL_PLUGINS=true
[…]
ln -sf ../../carla/styles /usr/local/lib/vst/carla.vst/styles
make: *** No rule to make target `install_external_plugins', needed by `install'.  Stop.
```

**Comment by falkTX** [comment]
Remove `EXTERNAL_PLUGINS=true` and it will work again.
The flag is now automatically handled in the makefiles, by checking if the git submodules are present.

**Comment by suedwestlicht** [comment]
It works then. But Zyn is not built as external plugin. Is this intended?

**Comment by FilipeCSnuk** [comment]
Zyn will be in the internal plugins if you have the dependencies for it.
It is not exported as part of the carla.lv2 plugin set, since a long time.
Zyn has an official LV2 and VST version, even for linux, and it works much better than the internal carla version.

**Comment by falkTX** [comment]
Zyn will be in the internal plugins if you have the dependencies for it.
It is not exported as part of the carla.lv2 plugin set, since a long time.
Zyn has an official LV2 and VST version, even for linux, and it works much better than the internal carla version.
