### ISSUE TITLE
carla-vst not recalling LV2 config when loading project in Bitwig

### ISSUE THREAD

**Issue by SeanArchibald** [falkTX/Carla#637]
I'm using carla-vst within Bitwig so that I can use LV2 plugins within my Bitwig projects. carla-vst is successfully bridging LV2<>VST except for one issue:

When I save my Bitwig project, close it and re-load it, the settings within the LV2 plugin are lost. The LV2 plugins I have tried are synthv1 and samplv1.

OS: KDE Neon user edition (based on Ubuntu 16.04) with KXStudio repo installed.

If you need any more info please ask. Thank you!

**Comment by falkTX** [comment]
there are 3 bugs about this, closing this one.
discussion to go in #640
