### ISSUE TITLE
carla+vst=do not save config

### ISSUE THREAD

**Issue by lagunax** [falkTX/Carla#639]
carla 2:1.9.8+git20180508
vst Kontakt 5

tryin to save project with vst, when i open project then vst is not load.

**Comment by lagunax** [comment]
add:
removed vst dlls from wine folders. moved x64 vst dlls into ~/.vst, removed spaces in names. refreshing plugin shows only one lib Kontakt5.dll. other two 'kontakt516.dll' and 'kontakt58.dll' do not exist in plugin list

**Comment by lagunax** [comment]
not only ardour. same with claudia

**Comment by falkTX** [comment]
there are 3 bugs about this, closing this one.
discussion to go in #640
