### ISSUE TITLE
VST Plugin parameters are lost on closing DAW

### ISSUE THREAD

**Issue by Sir-hennihau** [falkTX/Carla#640]
Windows VST bridged plugins **lose their parameters**, when the DAW is closed & reopened.

Also, when I save the Rack with "export as" .carxp the Windows VSTs do not reload the stored parameters.

Maybe a duplicate of #637 

Tracktion Waveform 9.2.1
Ubuntu 18.04
Using Carla version 1.9.8 (2.0-beta6)
Python version: 3.6.5
Qt version: 5.9.5
PyQt version: 5.10.1
Binary dir: /usr/lib/carla
Resources dir: /usr/share/carla/resources

Tested on multiple vsts, for example TS Substance.

**Comment by lagunax** [comment]
#639, but maybe #637 is same

**Comment by falkTX** [comment]
I can see what is going on, these damn plugins ask the host to change their parameters to the default when they are loaded, then override the saved project settings...
I can reproduce, so will add a workaround for it.

**Comment by falkTX** [comment]
Actually no, it is something else, but it is just carla having the wrong data. Custom UI of the plugin has the proper values.

**Comment by SeanArchibald** [comment]
I'm still seeing the issue with the samplv1 LV2 plugin losing all parameters on reload

**Comment by falkTX** [comment]
ok, I thought this was related to VST only.
@SeanArchibald please add as much details as possible about your system, carla build and usage of carla, so I have more chances to reproduce it.

**Comment by SeanArchibald** [comment]
```
$ dpkg -s carla-git | grep Version   
Version: 2:1.9.8+git20180610.2v5
$ dpkg -s carla-data | grep Version
Version: 2:1.9.8+git20180610.2v5
$ dpkg -s carla-vst | grep Version
Version: 2:1.9.8+git20180610.2v5
$ dpkg -s carla-lv2 | grep Version
Version: 2:1.9.8+git20180610.2v5
```

**OS:** KDE Neon (Ubuntu 16.04 based) with KXStudio repo
**Usage:** I use carla-vst inside my VST host, Bitwig Studio. Bitwig doesn't support LV2 plugins, so I am now able to access LV2 plugins via the Carla Rack VST plugin.
**Issue:** When using samplv1 LV2 within Carla Rack, the parameters are lost after re-loading the saved Bitwig project.

**Comment by lagunax** [comment]
as i remember 32 bit on debian jessie saved sessions with wine-vsts without big problems. one problem was if paths was with cirilyc symbols - session didn't save vsts in this way.

**Comment by falkTX** [comment]
I can confirm the issue with LV2 plugins in bridge mode (like v1 synths).
Now fixed in latest git.

If something related to this still happens, please open a new ticket.
I am closing this one.
