### ISSUE TITLE
Export as .lv2 does nothing

### ISSUE THREAD

**Issue by Sir-hennihau** [falkTX/Carla#641]
**Export as .lv2 does nothing**, no matter on which plugin I try it.

I got the experimental feature for it enabled.

Ubuntu 18.04
Using Carla version 1.9.8 (2.0-beta6)
  Python version: 3.6.5
  Qt version:     5.9.5
  PyQt version:   5.10.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources

**Comment by falkTX** [comment]
This is fixed now, reworked how lv2 export-dialog is handled.
