### ISSUE TITLE
Open GUI of an already running session

### ISSUE THREAD

**Issue by Bleuzen** [falkTX/Carla#645]
Hi, I start Carla with the --no-gui option on login.
But sometimes I want to change something with the effects after that, so I would open the Carla GUI and do the changes. But I can't. At least I didn't find a way to do so.
Would it be possible to detect running sessions and open the GUI for them?

**Comment by falkTX** [comment]
The only way I see this working is to use OSC, via carla-control.
Will be possible to change parameters, but not add or remove plugins.

**Comment by Bleuzen** [comment]
Ok, tryed carla-control. Can not connect, I get this:
```
LRDF Support not available (LADSPA-RDF will be disabled)
Carla 1.9.8 (2.0-beta6) started, status:
  Python version: 3.6.5
  Qt version:     5.11.0
  PyQt version:   5.10.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
lo_target is None
lo_target is None
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Icon theme "ubuntu-mono-dark" not found.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Connecting to "osc.tcp://127.0.0.1:19000/Carla" as 'Carla'...
Traceback (most recent call last):
  File "/usr/share/carla/carla_control.py", line 505, in slot_fileConnect
    self.connectOsc(addr)
  File "/usr/share/carla/carla_control.py", line 456, in connectOsc
    lo_send(lo_target, "/register", self.fOscServer.getFullURL())
  File "src/liblo.pyx", line 186, in liblo.send
  File "src/liblo.pyx", line 160, in liblo._send
OSError: sending failed: b'Verbindungsaufbau abgelehnt'
```

Oh and one question: If I can only control the parameters.. I would add all the plugins I need and use the bypass parameter..
but will the bypassed plugins take cpu during being loaded but bypassed?

**Comment by falkTX** [comment]
Disabled plugins do not consume CPU.
Full dry (0% wet) plugins do.

**Comment by Bleuzen** [comment]
Any idea about the carla-control connect error?
Do I have to enable something like the 'server-side' in Carla?
I also tryed it with a new Carla instance with GUI, but still can't connect.
Code error or did I forgot something? (never used OSCbefore)

**Comment by falkTX** [comment]
sorry for not replying here, there are many reason why such thing can fail.
I just pushed some changes in develop branch that should make carla-control behave a lot better.
It also tells you of errors if they happen.

Also, as now carla has settings for OSC, getting remote control should be a lot easier.
Going with the defaults, Carla-Control will be able to connect to main Carla "as-is" :)
