### ISSUE TITLE
unable to start kxstudio software (precompiled packages) in the last Fedora 28

### ISSUE THREAD

**Issue by legocef01** [falkTX/Carla#648]
When I try to start the latest precompiled kxstudio packages on Fedora 28, it crashes and displays this in the terminal with Carla by example : 

Cadence: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
[1]    981 abort (core dumped)  ./Cadence

**Comment by falkTX** [comment]
there are 3 bugs about this, closing this one.
discussion to go in #623
