### ISSUE TITLE
plugins within Carla Rack not receiving MIDI from VST host

### ISSUE THREAD

**Issue by SeanArchibald** [falkTX/Carla#655]
I am using Carla Rack as a way to use ZynAddSubFX in my Bitwig projects. This has mostly been working well for me, i.e. each instance of ZynAddSubFX was able to receive the MIDI note data coming from the Bitwig piano roll via Carla Rack.

**Issue:** Instances of ZynAddSubFX are no longer receiving MIDI data from the host. This started after my most recent apt update of carla-git, carla-lv2, carla-data and carla-vst packages.

```
Start-Date: 2018-06-09  17:11:27
Commandline: apt upgrade
Requested-By: s (1000)
Upgrade: carla-git:amd64 (2:1.9.8+git20180607v5, 2:1.9.8+git20180608v5), carla-lv2:amd64 (2:1.9.8+git20180607v5, 2:1.9.8+git20180608v5), carla-data:amd64 (2:1.9.8+git20180607v5, 2:1.9.8+git20180608v5), carla-vst:amd64 (2:1.9.8+git20180607v5, 2:1.9.8+git20180608v5)
End-Date: 2018-06-09  17:11:34

```

**More info:**
- Instances of ZynAddSubFX DO respond to the virtual keyboard within Carla Rack so I suspect the issue lies within Carla and not ZynAddSubFX, but I'm not sure.
- Nekobi has the same issue. It won't receive MIDI notes from the DAW but it does respond to Carla's virtual keyboard.
- synthv1 and samplv1 plugins that I have installed respond correctly to MIDI from the host DAW and also from Carla's virtual keyboard.
- I'm using KDE Neon (based on Ubuntu 16.04) with packages from the KXStudio repository.

I'm happy to provide more info if needed.

**Comment by falkTX** [comment]
Thanks for the quick report.
It is a regression in 8b1fd1f537fe711d53617f44f801cf27a00974a7
Investigating...

**Comment by FallenVEye** [comment]
I encountered similar problem. I'm using ASIOLinkPro + Carla on Windows 10 Pro 22H2.
Looks like midi just stops working inside the carla patchbay, whether the midi source is inside the patchbay or outside
