### ISSUE TITLE
Invisible rubberband after canvas refresh

### ISSUE THREAD

**Issue by nick87720z** [falkTX/Carla#656]
Problem appears exactly, when some existing carla project is loaded. Even with empty project. No matter, is it loaded after start or specified in carla command line. However, selection itself works.

After first look i could not find, from where in code it goes. Coordinates are set, and setting rubberband pen to fixed value from one of styles, in mouse move handler, doesn't help.

**Comment by falkTX** [comment]
Problem appears when canvas is refreshed.
Just do ctrl+r and the issue is visible.

Note that even cadence tools have this (catia, claudia and catarina).
So it is not specific to carla.

**Comment by nick87720z** [comment]
Thanks. I tried it rather in hope to fix issue, but not when it was absent.
