### ISSUE TITLE
Cannot modify connections on canvas in lv2 carla plugin

### ISSUE THREAD

**Issue by darijan** [falkTX/Carla#657]
I'm not able to modify connections between elements using carla lv2 plugin. Everything works fine for standalone application patchbay, the problem affects only Carla-Patchbay plugins (lv2 and vst as well).

It looks like the layer with the elements is not clickable at all, cause the border selection is working when I'm trying to click on the element. See also a short [video](https://youtu.be/17dL3sidUWM)

Some version info:
`Carla 1.9.8 (2.0-beta6), 
  Python version: 3.5.2, 
  Qt version:     5.5.1, 
  PyQt version:   5.5.1, 
Ubuntu 16.04`

--UPDATE--:
I was wrong. The layer is clickable. I guess this problem has something to do with calculating coordinates.

It works like it adds an offset to  coordinates depends on the current window position on the screen. I did some tests with a window at the top-left, and that's what behavior I noticed: See a [video](https://youtu.be/7j_wa4VTqD8)

I hope it'll be helpful to fix that issue.

**Comment by darijan** [comment]
I was wrong. The layer is clickable. I guess this problem has something to do with calculating coordinates.

It works like it adds an offset to  coordinates depends on the current window position on the screen. I did some tests with a window at the top-left, and that's what behaviour I noticed: See a [video](https://youtu.be/7j_wa4VTqD8)

I hope it'll be helpful to fix that issue.

**Comment by falkTX** [comment]
Should be fixed now, I added a few more tricks to make the x11 embed window position itself properly.

**Comment by darijan** [comment]
Perfect. Now it works correctly. Thanks a lot.

**Comment by falkTX** [comment]
Thanks for confirming, and report the bug!
