### ISSUE TITLE
Mixer-style interface

### ISSUE THREAD

**Issue by falkTX** [falkTX/Carla#664]
An idea by @pdesaulniers 
Created the so we can keep all related conversation in a single place.

**Comment by falkTX** [comment]
Regarding the backend implementation, the plan is to use the Carla Engine C++ API.
We assuming JACK support for the initial version (not even sure how useful this is without JACK doing its thing). Depends on how far away we can go really. If we want a single JACK standalone, or make it a plugin version eventually.

Each mixer strip can initiate a new CarlaEngine instance, set it as Rack mode, and manage plugins from there.
See https://github.com/falkTX/Carla/blob/master/source/backend/CarlaEngine.hpp#L795

Alternatively, we can use a carla-patchbay instance with several carla-racks running inside.
For this, we create a single engine instance (so it can use any audio driver), then load the internal carla-rack plugin inside. We can make it possible to get the CarlaEngine class from that plugin, and thus control the individual racks inside.
The problem with this is that the number of mixer strips will be static. But in turn, we can make it work as a plugin.

**Comment by pdesaulniers** [comment]
This would partially implement https://github.com/falkTX/Carla/issues/110

> (not even sure how useful this is without JACK doing its thing)

Not sure either.

> The problem with this is that the number of mixer strips will be static

I think the FL Studio mixer has a static amount of about 100 strips. I guess it's sufficient for most people :p

> But in turn, we can make it work as a plugin.

What would be a nice use-case for running the mixer as a plugin?

Anyway, I think it would be nice if the mixer had these features:
- Volume slider and pan for each track
- Send from insert to insert, with volume knob for controlling the amount of send. By default, all tracks would be routed to the master track with 100% gain
- Mute and solo. Right-clicking on mute makes the track solo
- Loading plugins, obviously :p I suppose we can use carla-database for selecting plugins?
- Activate / deactivate FX for track
- Grouping tracks. Make it easy to create drum busses and whatnot. Also, setting the color and names of groups. We can use zenity or an equivalent program to get the appropriate widgets for this
- Maybe recording? Clicking on the record button for the first time would prompt for a folder, and then all recordings would end up in that folder with a name like Recording-Track1-<timestamp>.wav
- Some way to set Jack input / output from the mixer, to route a microphone into a mixer track and send the output to another device for monitoring, or whatever.

Mixers tend to have fancy features like "Invert polarity" and such, but uh, why not just use a plugin for that :p Same thing for the EQ we've mentioned.

**Comment by falkTX** [comment]
That is a little bit over-featured for an initial version...

- Volume and pan are sorta there already, so easy to do.

- Sends, not really... it would involve the Mixer controlling the JACK connections (and also handling them being [dis]connected from the outside), not a trivial matter

- Mute and solo would be something on the frontend side. it just mutes or deactivates the carla-racks

- Loading plugins, we can at least list internal and LV2 using the carla-utils API.
Eventually Carla needs a DB to handle the plugin collection, we are not there yet.

- Grouping, isn't that UI specific feature?

- Recordng could be done with a plugin I guess.. no need to add it in carla-mixer

- the racks just expose jack clients. a list of possible connections is possible there.

**Comment by pdesaulniers** [comment]
> That is a little bit over-featured for an initial version...

Haha, sure :p It's just a wish-list, basically.

> Sends, not really... it would involve the Mixer controlling the JACK connections (and also handling them being [dis]connected from the outside), not a trivial matter

OK, I see. Would've been neat, but we can live without it.

> Eventually Carla needs a DB to handle the plugin collection

What are your plans for this? Would this also allow marking plugins as "favorite" and such?

> Recordng could be done with a plugin I guess.. no need to add it in carla-mixer

Indeed.

**Comment by falkTX** [comment]
The entire way carla saves scanned plugins needs to be handled differently.
But there was not a big need to change it yet, plus I dont know a lot about DB to make this an easy thing.

**Comment by falkTX** [comment]
Giving the same reply as I did for #665 

---

I have been thinking about this, and possible feature-creep in Carla.
I like `nilshi`'s approach with Patroneo, Vico and Fluahjo where there is a tool for a task, and it does the task well.
Carla already expanded in some areas I was originally not planning to cover, while the ones I still want to add remain unimplemented.
To make this clear I will create a document (in kx carla page) detailing exactly what I want carla to do.
A timeline, while nice to have, can be done by an external tool just fine.
One can even be made based on carla, while not be carla itself.

For this reason, I am closing this ticket.
Thanks for understanding.
