### ISSUE TITLE
Add a timeline

### ISSUE THREAD

**Issue by pdesaulniers** [falkTX/Carla#665]
Abstractly related to https://github.com/falkTX/Carla/issues/664

This would turn Carla into a proper DAW.

Automation would be done with spline-based graphs, using OSC or whatever. Real quick, I see two approaches for this : the "stack tons of automation clips vertically like in FL Studio" or "use a clean automation pane like in Renoise". The disadvantage with the Renoise one is that it only shows one parameter at a time.

Midi tracks would be nice. Midi recording too. They could be edited with something like Carla's "MIDI Pattern" plugin (though I would prefer a tracker-style view ;)

Then, you'd also have your average audio clip playback.

Adding the ability to render a section to sample would be a very nice time saver.

Anyway, gotta make the mixer first :p

**Comment by falkTX** [comment]
Let us have 2.0 released as stable first, before we even start talking about ideas on this :)

**Comment by falkTX** [comment]
I have been thinking about this, and possible feature-creep in Carla.
I like `nilshi`'s approach with Patroneo, Vico and Fluahjo where there is a tool for a task, and it does the task well.
Carla already expanded in some areas I was originally not planning to cover, while the ones I still want to add remain unimplemented.
To make this clear I will create a document (in kx carla page) detailing exactly what I want carla to do.
A timeline, while nice to have, can be done by an external tool just fine.
One can even be made based on carla, while not be carla itself.

For this reason, I am closing this ticket.
Thanks for understanding.

**Comment by pdesaulniers** [comment]
No problem, that makes sense.
