### ISSUE TITLE
Make sure releases and tags match

### ISSUE THREAD

**Issue by simonvanderveldt** [falkTX/Carla#668]
Hi falk,

Small request: Can you make sure the releases you create match with the tags used in git?
I.e. either call the release and the tag 1.9.7 or call both 2.0-beta5. These non-matching tags and releases make it quiet annoying to package.
It would be nice if this could be retroactively done for 2.0-beta5.

**Comment by falkTX** [comment]
this will be a "wont fix" until carla reaches stable 2.0

**Comment by falkTX** [comment]
Should be correct now.
I just have to watch out going forward
