### ISSUE TITLE
LV2 plugin doesn't remember state across Qtractor sessions

### ISSUE THREAD

**Issue by contrapunctus-1** [falkTX/Carla#669]
Debian v9.4
carla-lv2 v2:1.9.8+git20180628v5
qtractor v2:0.9.1-1kxstudio1v5

I added the Carla-Rack plugin to a few Qtractor MIDI tracks, and added a single SFZ to each Carla-Rack instance. I closed Qtractor and opened the project again - now some Carla-Rack instances remember their state, others don't. (Seemed rather random.)

I've tried saving the state of each Carla-Rack to disk, but that didn't make any difference.

**Comment by contrapunctus-1** [comment]
The Carla Rack plugin was present on every track I added it. But when I opened the plugin GUI, the SFZ I had added was not present in some instances of Carla Rack.

> Which plugin(s) specifically is misbehaving?
Sorry, I don't understand what you mean. I was using the Carla Rack LV2 plugin, and the SFZs are of my own creation.

**Comment by falkTX** [comment]
I might know the issue. damn linuxsampler...

**Comment by aki-k** [comment]
I have this same problem with Ardour 5.12 on Ubuntu 16.04 32-bit. Carla-rack sometimes forgets the SF2 that I add as a plugin. This seems to happen only to the first midi track's (in order from top) Carla-rack.

**Comment by falkTX** [comment]
SF2? or SFZ? the distinction here is really important...

**Comment by falkTX** [comment]
This will need some drastic changes in the carla-linuxsampler code, trying out things until it works in a stable way.
I have a new beta ready to go, we can start testing for changes after that.

**Comment by falkTX** [comment]
Since this issue is related only to linuxsampler, I am closing in favour of #250 which is its sorta duplicate.
Discussion should happen there.

**Comment by falkTX** [comment]
hmm I forgot to close this issue :P
#250 is fixed now, so this should be too.
If it is not the case, please let me know. Otherwise I assume the bug is really fixed.
