### ISSUE TITLE
Moving up/down doesn't work in Reaper or in Ardour

### ISSUE THREAD

**Issue by codecollider** [falkTX/Carla#671]
The new feature move up / move down doesn't not work in a DAW like REAPER or ARDOUR. It only works with the stand alone CARLA application. 

http://i.imgur.com/scOIMSP.png

Carla 1.9.9 (2.0. beta 7)
Debian / XFCE

**Comment by falkTX** [comment]
Can confirm, moving up/down plugins not working correctly when carla runs as a plugin.
