### ISSUE TITLE
Rack dial labels obscured when toolkit font increases preset menu height

### ISSUE THREAD

**Issue by milkmiruku** [falkTX/Carla#672]
![rose_2018-07-24_220222_099544822](https://user-images.githubusercontent.com/108225/43166137-af1d71d8-8f8d-11e8-8436-59816ab54210.png)

**Comment by falkTX** [comment]
his was fixed by your PR, right?

**Comment by milkmiruku** [comment]
No, the only PR I've made was for the MIDI Channel AB native plugin.

(Aside; for the AB plugin, I need to figure out enums so I can add a third "C (A+B)" output port as a workaround for the only-one-midi-output-for-each-event restriction)

**Comment by falkTX** [comment]
Ah right, it was not you, but the #700 might fix this.
Please check.

**Comment by milkmiruku** [comment]
Yup, that resolves the issue, thanks :+1:
