### ISSUE TITLE
Obxd both LV2+VST as well Helm escape their Carla window

### ISSUE THREAD

**Issue by hammerandtongs** [falkTX/Carla#674]
Carla draws a black managed window frame over the top of the "escaped" ie frameless ui for obxd and helm.

When moving the carla drawn frame from out of the way the plugin is useable but can't be moved, not sure if the plugin/skins feature of obxd is working however.

Said a different way, the plugin is drawn at the correct location but its not parented by the windowmanager ui.

I suspect this is related to #452 ?

I didn't find any others with this problem though I didn't check them all.

I'm on Ubuntu 18.04 with kubuntu/plasma desktop and kxstudio.

**Comment by falkTX** [comment]
are you using wayland by any chance...?

**Comment by hammerandtongs** [comment]
No X11 still.

**Comment by hammerandtongs** [comment]
Just checked and my laptop (vs the desktop I found the bug on) with same 18.04 etc also shows the same behaviour.

I assume since I see the right click plugin browser that you have the newer version of obxd from https://github.com/reales/OB-Xd ?

The skin/patch browser does work with obxd, though I'm not sure how to access the banks? midi only? 

Also - do I need to use your DISTHRO to build an lv2 version? I'm unfamiliar with the territory but was thinking OBXd might be nice with my https://zynthian.org rasberrry pi 3

**Comment by hammerandtongs** [comment]
Yes actually it's fixed now. Tried the RC1 binary from the website.

Thank you, this looks nice btw and I look forward to it making its way into KXStudio!
