### ISSUE TITLE
Please bundle plugins with precompiled Linux tarball

### ISSUE THREAD

**Issue by geckolinux** [falkTX/Carla#675]
Hi there,

I use the Carla 2.0-beta7 precompiled version for Linux from `Carla_2.0-beta7-linux64.tar.xz`. The [release announcement](http://kxstudio.linuxaudio.org/News/?action=view&url=carla-20-beta7-is-here) mentions:
>  most of the plugins bundled in Carla's code.
> They were moved into a separate repository, to keep Carla's code-base smaller.
Would it be possible to include them in the precompiled tarball?

Thanks a lot!

**Comment by falkTX** [comment]
why did you close this issue?

**Comment by geckolinux** [comment]
Sorry, I realized that they were already included, just moved to a different Github repo, right?

**Comment by falkTX** [comment]
That is correct. :)

That way I can actually increase the number of plugins in the future

**Comment by geckolinux** [comment]
Cool thanks!
