### ISSUE TITLE
Calf LV2 plugins fail to load

### ISSUE THREAD

**Issue by geckolinux** [falkTX/Carla#676]
Hi, I've been testing Carla at version 2.0-beta7 (via the binary Linux tarball) and version "1.9.7+git20171111" from the openSUSE Leap 15.0 repo. I also installed `calf` and `lv2-calf` at version  0.0.60 from the Packman repository for openSUSE Leap 15.0

With Carla 2.0-beta7, whenever I try to load any Calf plugins it says "Failed to load plugin". On the older "1.9.7+git20171111" it segfaults. There are no other helpful messages when I run it from the terminal.

Possibly related to #569?

Thanks a lot!

**Comment by geckolinux** [comment]
Thanks a lot for the reply.

I tried the Calf LV2 plugins in Qtractor, and interestingly it did crash the first time I tried to load one. But on subsequent tries they all load and work reliably.

Carla does load other LV2 plugins, for example ZynAddSubFx.

**Comment by geckolinux** [comment]
Here's a bit of helpful output that I found in the stderr log in 2.0-beta7 after trying to load a Calf plugin:

> Failed to initialize Non-RT server control

**Comment by falkTX** [comment]
hmm I see, that means plugin bridges dont seem to be working at all in your distro.
do you have the ir.lv2 plugin? can you try to load that one?

**Comment by geckolinux** [comment]
Hmm, can't seem to find that plugin. Any ideas on alternate package names or what it does?

I just tried loading a Guitarix LV2 plugin in Carla, and it worked fine, as do the ZynAddSubFx plugins.

**Comment by falkTX** [comment]
I dont know the package name, I dont use opensuse myself.
Official page is http://tomszilagyi.github.io/plugins/ir.lv2/

**Comment by falkTX** [comment]
ok so plugin bridges for sure are not working there.
what exact distribution are you using, which version, which architecture?
any special configuration you did to it?

I will try to reproduce the issue in a similar system to yours.

**Comment by geckolinux** [comment]
Thanks a lot Filipe. I'm running GeckoLinux STATIC Mate, which is a custom spin of openSUSE Leap 15.0 for x86_64 with the Mate desktop. No special configuration, just QJackCtl to connect an M-AUDIO KeyStation 88es MIDI controller/keyboard.

I don't understand how the Guitarix and Zyn LV2 plugins can load but not Calf or the IR plugins?

**Comment by tresf** [comment]
Possible worth nothing: https://github.com/LMMS/lmms/issues/3942

**Comment by chitholian** [comment]
I have the similar issue on Fedora 29 KDE. I installed `calf 0.90.1` and `Carla version 1.9.12 (2.0-RC2)`, both from Github. I have no `ladspa` plugin installed. Whenerver I try to load a calf lv2 plugin Carla Rack freezes for a  while, the log output is:

    Carla assertion failure: "ok" in file ../utils/CarlaThread.hpp, line 133
    CarlaRingBuffer::tryWrite(0x7ffc0a84e450, 4): failed, not enough space
    waitForClient(resize-pool) timed out
    Carla assertion failure: "! fTimedOut" in file CarlaPluginBridge.cpp, line 2606
    Carla assertion failure: "unlocked" in file ../utils/CarlaSemUtils.hpp, line 182
    waitForClient(activate) timed out
    Carla assertion failure: "unlocked" in file ../utils/CarlaSemUtils.hpp, line 182
    waitForClient(deactivate) timed out
    
Then there is no output from calf plugin (it becomes disabled automatically).

If I remove the plugin from the rack, the log output is:

    CarlaThread with realtime priority successful
    Will use LV2 Gtk2 UI for 'Calf Limiter', NOT!
    Carla Bridge Ready!

Note: Calf Plugins working well in `Ardour`.

**Comment by falkTX** [comment]
Ah yes, I forgot this is still an issue in Fedora for some reason.
I was not able to fix the issue regarding lv2 state in plugin bridges, so I am taking out the hardcoded use-calf-always-in-bridges rule.
If you build carla from latest git, calf plugins will work nicely there again.
Parts of the UI might be missing, due to instance-access being required, but at least the base plugin functionality still works.
