### ISSUE TITLE
All VST plugins in carla crash after unmute a track in Ardour

### ISSUE THREAD

**Issue by buerdman** [falkTX/Carla#696]
Hallo,

At first I will thank you for your great work! After updating carla and wine yesterday all carla instances crash if I unmute a track in ardour on Ubuntu Mate 16.4. I use several carla lv2 instances with win vst plugins in different tracks and they all crash if I unmute any single track. I have made the following updates:

Setting up carla-bridge-win32 (2:1.9.8+git20180819) ...
Setting up carla-data (2:1.9.9+git20180820v5) ...
Setting up carla-git (2:1.9.9+git20180820v5) ...
Setting up carla-lv2 (2:1.9.9+git20180820v5) ...
Setting up carla-vst (2:1.9.9+git20180820v5) ...
Setting up carla-plugins-lv2 (2:1.9.9+git20180820v5) ...
Setting up mixxx (2.1.3-0ubuntu1~2.1~git6763~xenial) ...
Setting up wpasupplicant (2.4-0ubuntu6.3) ...
Setting up wine-rt-amd64 (2:3.0.2-1~kxstudio2v5) ...
Setting up wine-rt-i386:i386 (2:3.0.2-1~kxstudio2v5) ...
Setting up carla-bridge-wine64 (2:1.9.8+git20180819) ...
Setting up carla-bridge-win64 (2:1.9.8+git20180819) ...
Setting up wine-rt (2:3.0.2-1~kxstudio2v5) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...

This is the wine error Message:
Unhandled exception: page fault on read access to 0xffffffff in 32-bit code (0x0048383a).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:0048383a ESP:00d0fc44 EBP:00d0fd3c EFLAGS:00010206(  R- --  I   - -P- )
 EAX:002634c0 EBX:000000ff ECX:00d0fc44 EDX:0025a458
 ESI:000003ff EDI:0025a420
Stack dump:
0x00d0fc44:  0025a438 00000000 00000020 42800000
0x00d0fc54:  000000c4 00d0fc98 7b474a7c 002415c0
0x00d0fc64:  7b4639f6 00d0fc84 7b474a7c 00000001
0x00d0fc74:  00d0fca4 00000000 00000000 00000000
0x00d0fc84:  0025a438 00d0fc4c 00000000 01d0fca4
0x00d0fc94:  7bcdf000 00d0fcc8 7bc3dc69 002415c0
Backtrace:
=>0 0x0048383a in carla-bridge-win32 (+0x8383a) (0x00d0fd3c)
  1 0x0048ca02 in carla-bridge-win32 (+0x8ca01) (0x00d0fe3c)
  2 0x004373c0 in carla-bridge-win32 (+0x373bf) (0x00d0fecc)
  3 0x7bc81728 call_thread_func_wrapper+0xb() in ntdll (0x00d0fedc)
  4 0x7bc855e9 in ntdll (+0x755e8) (0x00d0ffdc)
  5 0x7bc8171a call_thread_exit_func+0x31() in ntdll (0x00d0ffec)
0x0048383a: 	
Modules:
Module	Address			Debug info	Name (100 modules)
PE	  400000-  5ee000	Export          carla-bridge-win32
PE	10000000-10168000	Deferred        synth1 vst
ELF	7b400000-7b7ea000	Deferred        kernel32<elf>
  \-PE	7b410000-7b7ea000	\               kernel32
ELF	7bc00000-7bcfc000	Dwarf           ntdll<elf>
  \-PE	7bc10000-7bcfc000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7cfea000-7d000000	Deferred        libgpg-error.so.0
ELF	7d000000-7d075000	Deferred        libpcre.so.3
ELF	7d075000-7d124000	Deferred        libgcrypt.so.20
ELF	7d124000-7d14a000	Deferred        liblzma.so.5
ELF	7d14a000-7d170000	Deferred        libselinux.so.1
ELF	7d170000-7d1fe000	Deferred        libsystemd.so.0
ELF	7d1fe000-7d207000	Deferred        libffi.so.6
ELF	7d207000-7d220000	Deferred        libresolv.so.2
ELF	7d220000-7d27a000	Deferred        libdbus-1.so.3
ELF	7d27a000-7d306000	Deferred        libgmp.so.10
ELF	7d306000-7d33b000	Deferred        libhogweed.so.4
ELF	7d33b000-7d378000	Deferred        libnettle.so.6
ELF	7d378000-7d38d000	Deferred        libtasn1.so.6
ELF	7d38d000-7d3c1000	Deferred        libidn.so.11
ELF	7d3c1000-7d497000	Deferred        libkrb5.so.3
ELF	7d497000-7d5ef000	Deferred        libgnutls.so.30
ELF	7d655000-7d65a000	Deferred        libkeyutils.so.1
ELF	7d65a000-7d6bb000	Deferred        libp11-kit.so.0
ELF	7d6bb000-7d6c8000	Deferred        libkrb5support.so.0
ELF	7d6c8000-7d6cd000	Deferred        libcom_err.so.2
ELF	7d6cd000-7d6fe000	Deferred        libk5crypto.so.3
ELF	7d6fe000-7d712000	Deferred        libavahi-client.so.3
ELF	7d712000-7d720000	Deferred        libavahi-common.so.3
ELF	7d720000-7d772000	Deferred        libgssapi_krb5.so.2
ELF	7d772000-7d7f9000	Deferred        libcups.so.2
ELF	7d81d000-7d855000	Deferred        uxtheme<elf>
  \-PE	7d820000-7d855000	\               uxtheme
ELF	7d855000-7d8e8000	Deferred        gdiplus<elf>
  \-PE	7d860000-7d8e8000	\               gdiplus
ELF	7d8e8000-7d928000	Deferred        winspool<elf>
  \-PE	7d8f0000-7d928000	\               winspool
ELF	7d928000-7da47000	Deferred        comctl32<elf>
  \-PE	7d930000-7da47000	\               comctl32
ELF	7da47000-7db32000	Deferred        comdlg32<elf>
  \-PE	7da50000-7db32000	\               comdlg32
ELF	7db9b000-7dba2000	Deferred        libxfixes.so.3
ELF	7dba2000-7dbae000	Deferred        libxcursor.so.1
ELF	7dbae000-7dbc1000	Deferred        libxi.so.6
ELF	7dbc1000-7dbc5000	Deferred        libxcomposite.so.1
ELF	7dbc5000-7dbd2000	Deferred        libxrandr.so.2
ELF	7dbd2000-7dbde000	Deferred        libxrender.so.1
ELF	7dbde000-7dbe5000	Deferred        libxxf86vm.so.1
ELF	7dbe5000-7dbe9000	Deferred        libxinerama.so.1
ELF	7dbe9000-7dbf0000	Deferred        libxdmcp.so.6
ELF	7dbf0000-7dbf4000	Deferred        libxau.so.6
ELF	7dbf4000-7dc1a000	Deferred        libxcb.so.1
ELF	7dc1a000-7dd65000	Deferred        libx11.so.6
ELF	7dd65000-7dd7a000	Deferred        libxext.so.6
ELF	7dd7a000-7de08000	Deferred        winex11<elf>
  \-PE	7dd80000-7de08000	\               winex11
ELF	7de08000-7de25000	Deferred        libgcc_s.so.1
ELF	7df9c000-7dfa5000	Deferred        librt.so.1
PE	7dfc9000-7dfec000	Deferred        jackbridge-wine32
ELF	7dfec000-7e010000	Deferred        imm32<elf>
  \-PE	7dff0000-7e010000	\               imm32
ELF	7e0c8000-7e0f2000	Deferred        libexpat.so.1
ELF	7e0f2000-7e13b000	Deferred        libfontconfig.so.1
ELF	7e13b000-7e166000	Deferred        libpng12.so.0
ELF	7e166000-7e181000	Deferred        libz.so.1
ELF	7e181000-7e231000	Deferred        libfreetype.so.6
ELF	7e255000-7e280000	Deferred        msacm32<elf>
  \-PE	7e260000-7e280000	\               msacm32
ELF	7e280000-7e338000	Deferred        winmm<elf>
  \-PE	7e290000-7e338000	\               winmm
ELF	7e338000-7e3ae000	Deferred        shlwapi<elf>
  \-PE	7e350000-7e3ae000	\               shlwapi
ELF	7e3ae000-7e5fe000	Deferred        shell32<elf>
  \-PE	7e3c0000-7e5fe000	\               shell32
ELF	7e5fe000-7e67f000	Deferred        rpcrt4<elf>
  \-PE	7e610000-7e67f000	\               rpcrt4
ELF	7e67f000-7e7ae000	Deferred        gdi32<elf>
  \-PE	7e690000-7e7ae000	\               gdi32
ELF	7e7ae000-7e98e000	Deferred        user32<elf>
  \-PE	7e7c0000-7e98e000	\               user32
ELF	7e98e000-7ea06000	Deferred        advapi32<elf>
  \-PE	7e9a0000-7ea06000	\               advapi32
ELF	7ea06000-7eb61000	Deferred        ole32<elf>
  \-PE	7ea20000-7eb61000	\               ole32
ELF	7eb61000-7ec1a000	Deferred        msvcrt<elf>
  \-PE	7eb80000-7ec1a000	\               msvcrt
ELF	7ef4c000-7ef5f000	Deferred        libnss_files.so.2
ELF	7ef5f000-7ef6c000	Deferred        libnss_nis.so.2
ELF	7ef6c000-7ef87000	Deferred        libnsl.so.1
ELF	7ef87000-7efdc000	Deferred        libm.so.6
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f7349000-f734e000	Deferred        libdl.so.2
ELF	f734e000-f7504000	Deferred        libc.so.6
ELF	f7504000-f7521000	Deferred        libpthread.so.0
ELF	f7526000-f7530000	Deferred        libnss_compat.so.2
ELF	f7545000-f76fc000	Dwarf           libwine.so.1
ELF	f76fd000-f7722000	Deferred        ld-linux.so.2
ELF	f7725000-f7726000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 carla-bridge-win32.exe
	0000002e    0
	0000002d    0
	00000009    0
0000000e services.exe
	00000025    0
	00000022    0
	0000001d    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	0000001a    0
	00000017    0
	00000016    0
	00000012    0
0000001b plugplay.exe
	0000001f    0
	0000001e    0
	0000001c    0
00000020 winedevice.exe
	00000024    0
	00000023    0
	00000021    0
00000028 explorer.exe
	0000002c    0
	0000002b    0
	0000002a    0
	00000029    0
0000002f (D) Z:\usr\lib\lv2\carla.lv2\carla-bridge-win32.exe
	00000032    0 <==
	00000031    0
	00000030    0
0000004c winedbg.exe
	0000004d    0
System information:
    Wine build: wine-3.0.2
    Platform: i386 (WOW64)
    Version: Windows XP
    Host system: Linux
    Host version: 4.4.0-133-lowlatency

Thank You very much!

**Comment by falkTX** [comment]
ah bummer, I see 0xffffffff, so likely a -1 on a null pointer that got rogue..
can't reproduce though.

got a few questions..
1. which carla-plugin variant are you using? rack or patchbay, lv2 or vst
2. which winvst plugin are you using that causes this? can you reduce it to a specific one you know fore sure triggers a crash?

maybe related to the typo causing midi out events to be crappy.
update again before testing any more please, latest carla as of today should be version 2:1.9.9+git20180822.2v5

**Comment by buerdman** [comment]
1. its carla rack
2. I use two VSTs in different tracks and they crash all together. Its synth1 and Synsonic BD-909

I have done the Update, but the problem persists.

**Comment by falkTX** [comment]
alright, it is related to synths.
I can reproduce with the repo package.
I don't know exactly what I did recently, but latest local build of mine does not have the issue, so it has already been fixed :)
I will publish another update to Carla in the kx repos after I finish a few more things today.

**Comment by falkTX** [comment]
nevermind, the bug is still there.
quite curious.. does not happen with a local build. perhaps it is time to update mingw.

**Comment by falkTX** [comment]
This is very stupid... I was able to reproduce the bug, and find exactly which line it crashes in.
Crashes when starting a normal operation, for no reason at all..
Seems a compiler bug, as building without optimizations I can get the mute action to work fine.
Also my new system with a different (new) mingw does not show this issue.

Pretty shitty, but I know now what is going on.
Likely other crashes happened too because of the broken mingw.
I will upload a build of carla-bridges-win32/64 to the kxstudio repos with optimizations disabled for now, while I see about updating the compiler.

**Comment by falkTX** [comment]
@buerdman I got your email, thanks for reporting back (you could have reopen this ticket or commented here though).
Anyway, after investigating, I found a specific compiler optimization that made the issue appear.
Even after updating my mingw (from 4.7 to 4.9), we still had that crash :(
f13e9e52186bfc98956e0d5236ef5882c01f2015 now fixes this, will push an update to the kx repos sometime soon.

**Comment by buerdman** [comment]
Great, now it works! Thank you very much!
