### ISSUE TITLE
[nsm] closing carla takes long when closing nsm session

### ISSUE THREAD

**Issue by johnsen** [falkTX/Carla#70]
carla 1.1.0 takes significantly long to close when you hit close in latest nsm. It took nsm till 'loop 36' before it closes.

NSM terminal:
[nsmd] ../session-manager/src/nsmd.C:1010 wait_for_killed_clients_to_die(): Loop 33
[nsmd] ../session-manager/src/nsmd.C:1010 wait_for_killed_clients_to_die(): Loop 34
[nsmd] ../session-manager/src/nsmd.C:1010 wait_for_killed_clients_to_die(): Loop 35
[nsmd] ../session-manager/src/nsmd.C:329 handle_client_process_death(): Client Carla terminated because we told it to.
[nsmd] ../session-manager/src/nsmd.C:1010 wait_for_killed_clients_to_die(): Loop 36
[nsmd] ../session-manager/src/nsmd.C:1037 wait_for_killed_clients_to_die(): All clients have died.
[nsmd] ../session-manager/src/nsmd.C:1732 osc_close(): Done
[non-session-manager] ../session-manager/src/session-manager.C:1205 osc_handler(): /nsm/server/close says Closed.

NSM log:
00:04:34 Commanding attached clients to quit.
00:04:35 Client Non-Mixer terminated because we told it to.
00:04:35 Client ZynAddSubFX terminated because we told it to.
00:04:36 Client ams terminated because we told it to.
00:04:36 Client patchage terminated because we told it to.
00:04:36 Client JACKPatch terminated because we told it to.
00:04:36 Client Non-Sequencer terminated because we told it to.
00:05:10 Client Carla terminated because we told it to.
00:05:11 Closed.

**Comment by falkTX** [comment]
This is now fixed with the NSM code rework.
