### ISSUE TITLE
Start aborted with PyQt5.QtCore and PyQt4.QtCore error

### ISSUE THREAD

**Issue by zettberlin** [falkTX/Carla#704]
Built today from Git on fresh upgraded Ubuntu Studio 18.04:

`Traceback (most recent call last):
  File "/usr/local/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/local/share/carla/carla_host.py", line 42, in <module>
    import ui_carla_host
  File "/usr/local/share/carla/ui_carla_host.py", line 9, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class`

so sad...

make features did not mention any problems. Built went OK.

**Comment by falkTX** [comment]
you seem to have mixed old version and new version.
run make uninstall, and make install again

**Comment by zettberlin** [comment]
Just uninstall/install again did not make it. I deleted the git clone, cloned again and run make again.
Now it works, cool, thank you.
So I consider this closed.
