### ISSUE TITLE
new code regressions

### ISSUE THREAD

**Issue by falkTX** [falkTX/Carla#710]
reported by akik on IRC:

- [x] 12:38 <+akik> falktx: not sure what's going on. i can't open the carla-rack ui any more: Carla assertion failure: "! isEmbed" in file carla-lv2.cpp, line 965 suil error: Failed to instantiate UI <http://kxstudio.sf.net/carla/ui-embed> in /usr/lib/lv2/carla.lv2/carla.so (2:1.9.9+git20180831v5)
- [x] 23:27 <+akik> falktx: i used the pin connections window to add two new audio outs and that way i can get stereo
03:15 <+akik> falktx: it's the carla-rack lv2 i've added to a midi track
03:17 <+akik> well, three tracks, three carla-racks, but they showed this same behaviour

**Comment by CG-3D** [comment]
Since last version (Aug 31) all lv2-versions of Carla Patchbay/16/32 Refuse to open their GUI in Ardour 5.12.0 on Ubuntu 18.04 (Gnome) and Mint 19+18.3 (Cinnamon+XFCE). Ardour log: [ERROR]: failed to instantiate LV2 GUI.

**Comment by falkTX** [comment]
thanks, I will take a look at these tomorrow.

**Comment by falkTX** [comment]
@aki-k I dont really understand the 2nd issue here. carla plugin outputting mono, was that it? I already forgot, and my IRC logs dont go very far

**Comment by codecollider** [comment]
Just updated CARLA. SFZ is working again, but it doesn't find any SF2 files anymore.

**Comment by falkTX** [comment]
You have to be more specific than that.
I cant reproduce it here.

If it is about missing plugins, you just need to rescan again.
Some code was rewritten, full new scan is needed now.

**Comment by aki-k** [comment]
I'm able to compile Carla from GitHub source but I can't make Ardour find it after a plugin scan.
I compiled it to /opt/carla (changed PREFIX in Makefile) and added /opt/carla/lib to the plugin path. 

What needs to be done for Ardour to find it? (Ubuntu 16.04.5, 32-bit)

**Comment by falkTX** [comment]
That should be a new issue.
But you need to add /opt/carla/lib/vst to the list of VST locations.
Though because you already have carla-git and carla-vst packages, ardour might skip the duplicates.

**Comment by aki-k** [comment]
There's no /opt/carla/lib/vst. Actually no files matching "*vst*". Should I put the Steinberg VST SDK files somewhere for it to compile?

**Comment by falkTX** [comment]
Carla does not use the SDK, the VST plugin is built if you have X11 and pyqt5 dev packages installed.
perhaps your build was missing those.
