### ISSUE TITLE
Sending SIGUSR1 to carla win bridge does not generate project file

### ISSUE THREAD

**Issue by ElArtista** [falkTX/Carla#711]
According to the code, when using carla-single, sending a USR1 signal to the process should trigger the carla save state functionality for the running plugin generating a *.carxs file in the working directory.
This does not happen.

**Comment by falkTX** [comment]
Seems getting this to work with wine is tricky, it uses SIGUSR1 internally.
So instead, we can just call bridges within carla-single.
This way we can still send a signal to carla-bridge-native, which controls the carla-bridge-win* stuff.
See 1d32de24b7bee82f5c3e0bf8d3d43d572d36d014
An example was added on how to achieve this.

PS: bonus points, with this last method, carla will automatically find the right WINEPREFIX needed for the plugin for you :)
