### ISSUE TITLE
PyQt4 undefined symbol

### ISSUE THREAD

**Issue by sheosi** [falkTX/Carla#713]
Carla latest precompiled binaries (beta-7) output this error while trying to execute Carla both in it's VST form as in executable form:
`Traceback (most recent call last):
  File "/usr/share/cx-freeze-common/initscripts/Console3.py", line 27, in <module>
  File "build-carla/resources/carla-plugin.py", line 31, in <module>
  File "ExtensionLoader_PyQt4_QtGui.py", line 11, in <module>
ImportError: /home/sergio/.vst/carla.vst/resources/PyQt4.QtGui.so: undefined symbol: _ZN15QSessionManager16staticMetaObjectE`

My guess would be either wrong packaging of PyQt4 or incompatiblities with my Qt4 installation. I'm running the linux64 version inside a Solus OS installation.

**Comment by falkTX** [comment]
Some incompatibility then, first time I hear about such thing.

Just build Carla yourself instead of using the pre-compiled binaries then.

**Comment by falkTX** [comment]
I am marking this as won't fix, I cannot do anything to fix it on my side.
If you have issues building carla, let me know.
