### ISSUE TITLE
carla-bridge-win64/32

### ISSUE THREAD

**Issue by tank-trax** [falkTX/Carla#715]
Carla, when scanning VST Instruments plugins crashes WINE -> carla-discovery-win64.exe has encountered a serious problem and needs to close. same thing for carla-discovery-win32.exe

Effects are ok

started after the upgrade to the following packages or very recently:
carla-bridge-win32 (2:1.9.8+git20180904) to 2:1.9.8+git20180904.2
carla-bridge-win64 (2:1.9.8+git20180904) to 2:1.9.8+git20180904.2

**Comment by falkTX** [comment]
Maybe the same as #712
I cannot reproduce though.
See if you can get one plugin to crash every single time, but via CLI. like so:
`wine64 /usr/lib/carla/carla-discovery-win64.exe vst /path/to/vst.dll`

**Comment by tank-trax** [comment]
Yep. Same issue as #712

**Comment by tank-trax** [comment]
vstHostCallback(000000000007f570, 42:audioMasterUpdateDisplay, 0, 0, 0000000000000000, 0.000000)
vstHostCallback(000000000007f570, 42:audioMasterUpdateDisplay, 0, 0, 0000000000000000, 0.000000)

carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo"
wine: Unhandled page fault on write access to 0x00000000 at address 0x1800449b9 (thread 0009), starting debugger...
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 11
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 10
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 9
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 8
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 7
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 11
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 10
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 9
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 8
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 7
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6

**Comment by tank-trax** [comment]
0009:fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Ani"!

carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo"

carla-discovery::init::-----------

carla-discovery::build::4

carla-discovery::hints::12

carla-discovery::name::PolyGAS

carla-discovery::label::PolyGAS

carla-discovery::maker::Stone Voices

carla-discovery::uniqueId::1346847059

carla-discovery::audio.ins::2

carla-discovery::audio.outs::2

carla-discovery::midi.ins::1

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::47

carla-discovery::end::------------

**Comment by tank-trax** [comment]
0009:fixme:heap:RtlSetHeapInformation 0x5c0000 0 0x33f4b0 4 stub
0009:fixme:heap:RtlSetHeapInformation 0x5c0000 0 0x33f4b0 4 stub
wine: Unhandled page fault on write access to 0x00000000 at address 0x18014cd00 (thread 0009), starting debugger...
Unhandled exception: page fault on write access to 0x00000000 in 64-bit code (0x000000018014cd00).
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 11
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 10
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 9
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 8
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 7
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 11
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 10
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 9
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 8
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 7
002d:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6
Register dump:
 rip:000000018014cd00 rsp:000000000033f708 rbp:000000000033f8c0 eflags:00010283 (  R- --  I S - - -C)
 rax:0000000000000000 rbx:00000000005c5320 rcx:0000000000000000 rdx:0000000000000000
 rsi:000000000033f810 rdi:000000000033f9d0  r8:0000000000000000  r9:0000000000000020 r10:000000018018dc68
 r11:00000000005cb8e0 r12:0000000000486e80 r13:000000000000000c r14:000000000033f970 r15:0000000000000000
Stack dump:
0x000000000033f708:  0000000180043a82 00000000005c52f0
0x000000000033f718:  0000000000000001 0000000000000000
0x000000000033f728:  0000000000000000 0000000000000800
0x000000000033f738:  00000000005c5320 006f006d00000000
0x000000000033f748:  0000000000000000 ffffffff00ffffff
0x000000000033f758:  0000000180037098 00000000005cb8e0
0x000000000033f768:  000000000033f860 000000000033f810
0x000000000033f778:  0000000100000200 0000000000000010
0x000000000033f788:  0000000000000019 0000000000000000
0x000000000033f798:  00000001800447b5 00000000005c52f0
0x000000000033f7a8:  000000000033f860 000000000033f810
0x000000000033f7b8:  0000000000000200 00000000005c52f0
Backtrace:
=>0 0x000000018014cd00 in model-e (+0x14cd00) (0x000000000033f8c0)
  1 0x0000000180043a82 in model-e (+0x43a81) (0x000000000033f8c0)
  2 0x0000000180037098 in model-e (+0x37097) (0x000000000033f8c0)
  3 0x00000001800447b5 in model-e (+0x447b4) (0x000000000033f8c0)
  4 0x000000000041ae18 in carla-discovery-win64 (+0x1ae17) (0x000000000033f8c0)
  5 0x000000000046fccd in carla-discovery-win64 (+0x6fccc) (0x000000000033fba0)
  6 0x00000000004013e8 in carla-discovery-win64 (+0x13e7) (0x00000000004b1b10)
  7 0x000000000040151b in carla-discovery-win64 (+0x151a) (0x000000000033ffd0)
  8 0x000000007b47a6a8 in kernel32 (+0x5a6a7) (0x000000000033ffd0)
0x000000018014cd00: movq	%rdx,(%rcx)
Modules:
Module	Address					Debug info	Name (99 modules)
PE	          400000-          4ad000	Export          carla-discovery-win64
ELF	        7a800000-        7aa05000	Deferred        opengl32<elf>
  \-PE	        7a850000-        7aa05000	\               opengl32
ELF	        7b400000-        7b819000	Dwarf           kernel32<elf>
  \-PE	        7b420000-        7b819000	\               kernel32
ELF	        7bc00000-        7bd22000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bd22000	\               ntdll
ELF	        7c000000-        7c004000	Deferred        <wine-loader>
PE	       180000000-       1802f0000	Export          model-e
ELF	    7f547bd97000-    7f547bfab000	Deferred        libgpg-error.so.0
ELF	    7f547bfab000-    7f547c21b000	Deferred        libpcre.so.3
ELF	    7f547c21b000-    7f547c4fc000	Deferred        libgcrypt.so.20
ELF	    7f547c4fc000-    7f547c71e000	Deferred        liblzma.so.5
ELF	    7f547c71e000-    7f547c926000	Deferred        librt.so.1
ELF	    7f547c926000-    7f547cb48000	Deferred        libselinux.so.1
ELF	    7f547cb48000-    7f547cbcd000	Deferred        libsystemd.so.0
ELF	    7f547cbcd000-    7f547cdd5000	Deferred        libffi.so.6
ELF	    7f547cdd5000-    7f547cff0000	Deferred        libresolv.so.2
ELF	    7f547cff0000-    7f547d1f4000	Deferred        libkeyutils.so.1
ELF	    7f547d1f4000-    7f547d440000	Deferred        libdbus-1.so.3
ELF	    7f547d440000-    7f547d6c0000	Deferred        libgmp.so.10
ELF	    7f547d6c0000-    7f547d8f3000	Deferred        libhogweed.so.4
ELF	    7f547d8f3000-    7f547db29000	Deferred        libnettle.so.6
ELF	    7f547db29000-    7f547dd3c000	Deferred        libtasn1.so.6
ELF	    7f547dd3c000-    7f547df6f000	Deferred        libidn.so.11
ELF	    7f547df6f000-    7f547e1d3000	Deferred        libp11-kit.so.0
ELF	    7f547e1d3000-    7f547e3de000	Deferred        libkrb5support.so.0
ELF	    7f547e3de000-    7f547e5e2000	Deferred        libcom_err.so.2
ELF	    7f547e5e2000-    7f547e811000	Deferred        libk5crypto.so.3
ELF	    7f547e811000-    7f547eae3000	Deferred        libkrb5.so.3
ELF	    7f547eae3000-    7f547ecf4000	Deferred        libavahi-client.so.3
ELF	    7f547ecf4000-    7f547ef00000	Deferred        libavahi-common.so.3
ELF	    7f547ef00000-    7f547f230000	Deferred        libgnutls.so.30
ELF	    7f547f230000-    7f547f47a000	Deferred        libgssapi_krb5.so.2
ELF	    7f547f47a000-    7f547f6fa000	Deferred        libcups.so.2
ELF	    7f547f729000-    7f547f967000	Deferred        uxtheme<elf>
  \-PE	    7f547f730000-    7f547f967000	\               uxtheme
ELF	    7f547f967000-    7f547fb6d000	Deferred        libxfixes.so.3
ELF	    7f547fb6d000-    7f547fd77000	Deferred        libxcursor.so.1
ELF	    7f547fd77000-    7f547ff87000	Deferred        libxi.so.6
ELF	    7f547ff87000-    7f548018a000	Deferred        libxcomposite.so.1
ELF	    7f548018a000-    7f5480395000	Deferred        libxrandr.so.2
ELF	    7f5480395000-    7f548059f000	Deferred        libxrender.so.1
ELF	    7f548059f000-    7f54807a5000	Deferred        libxxf86vm.so.1
ELF	    7f54807a5000-    7f54809a8000	Deferred        libxinerama.so.1
ELF	    7f54809a8000-    7f5480bae000	Deferred        libxdmcp.so.6
ELF	    7f5480bae000-    7f5480db2000	Deferred        libxau.so.6
ELF	    7f5480db2000-    7f5480fd4000	Deferred        libxcb.so.1
ELF	    7f5480fd4000-    7f548130e000	Deferred        libx11.so.6
ELF	    7f548130e000-    7f5481520000	Deferred        libxext.so.6
ELF	    7f548154f000-    7f54817f0000	Deferred        winex11<elf>
  \-PE	    7f5481560000-    7f54817f0000	\               winex11
ELF	    7f54817f0000-    7f5481a18000	Deferred        imm32<elf>
  \-PE	    7f5481800000-    7f5481a18000	\               imm32
ELF	    7f5481b1e000-    7f5481d47000	Deferred        libexpat.so.1
ELF	    7f5481d47000-    7f5481f8a000	Deferred        libfontconfig.so.1
ELF	    7f5481f8a000-    7f54821af000	Deferred        libpng12.so.0
ELF	    7f54821af000-    7f54823c9000	Deferred        libz.so.1
ELF	    7f54823c9000-    7f5482673000	Deferred        libfreetype.so.6
ELF	    7f5482673000-    7f548292b000	Deferred        gdiplus<elf>
  \-PE	    7f5482690000-    7f548292b000	\               gdiplus
ELF	    7f548292b000-    7f5482bc5000	Deferred        rpcrt4<elf>
  \-PE	    7f5482940000-    7f5482bc5000	\               rpcrt4
ELF	    7f5482bc5000-    7f5482f7a000	Deferred        ole32<elf>
  \-PE	    7f5482bf0000-    7f5482f7a000	\               ole32
ELF	    7f5482f7a000-    7f54831c3000	Deferred        winspool<elf>
  \-PE	    7f5482f80000-    7f54831c3000	\               winspool
ELF	    7f54831c3000-    7f54834fa000	Deferred        comctl32<elf>
  \-PE	    7f54831d0000-    7f54834fa000	\               comctl32
ELF	    7f54834fa000-    7f548378e000	Deferred        shlwapi<elf>
  \-PE	    7f5483510000-    7f548378e000	\               shlwapi
ELF	    7f548378e000-    7f5483c2c000	Deferred        shell32<elf>
  \-PE	    7f54837b0000-    7f5483c2c000	\               shell32
ELF	    7f5483c2c000-    7f5483f26000	Deferred        comdlg32<elf>
  \-PE	    7f5483c30000-    7f5483f26000	\               comdlg32
ELF	    7f5483f26000-    7f5484140000	Deferred        version<elf>
  \-PE	    7f5483f30000-    7f5484140000	\               version
ELF	    7f5484140000-    7f54843d7000	Deferred        advapi32<elf>
  \-PE	    7f5484150000-    7f54843d7000	\               advapi32
ELF	    7f54843d7000-    7f5484757000	Deferred        gdi32<elf>
  \-PE	    7f54843f0000-    7f5484757000	\               gdi32
ELF	    7f5484757000-    7f5484b9c000	Deferred        user32<elf>
  \-PE	    7f5484780000-    7f5484b9c000	\               user32
ELF	    7f5484c9c000-    7f5484ec5000	Deferred        libtinfo.so.5
ELF	    7f5484ec5000-    7f54850e7000	Deferred        libncurses.so.5
ELF	    7f54851e7000-    7f54854c1000	Deferred        msvcrt<elf>
  \-PE	    7f5485200000-    7f54854c1000	\               msvcrt
ELF	    7f5485799000-    7f54859ab000	Deferred        libnss_files.so.2
ELF	    7f54859ab000-    7f5485bb7000	Deferred        libnss_nis.so.2
ELF	    7f5485bb7000-    7f5485dd0000	Deferred        libnsl.so.1
ELF	    7f5485dd0000-    7f5485fd9000	Deferred        libnss_compat.so.2
ELF	    7f54861d9000-    7f54863ef000	Deferred        libgcc_s.so.1
ELF	    7f54863ef000-    7f54866f8000	Deferred        libm.so.6
ELF	    7f54866fb000-    7f54868ff000	Deferred        libdl.so.2
ELF	    7f5486900000-    7f5486cca000	Deferred        libc.so.6
ELF	    7f5486cca000-    7f5486ee7000	Deferred        libpthread.so.0
ELF	    7f5486f16000-    7f54872bc000	Dwarf           libwine.so.1
ELF	    7f54872bd000-    7f54874e5000	Deferred        ld-linux-x86-64.so.2
ELF	    7ffddb7c8000-    7ffddb7ca000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\usr\lib\carla\carla-discovery-win64.exe
	00000009    0 <==
0000000e services.exe
	00000022    0
	0000001d    0
	00000015    0
	00000014    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	0000001a    0
	00000019    0
	00000018    0
	00000017    0
	00000016    0
	00000012    0
0000001b plugplay.exe
	0000001f    0
	0000001e    0
	0000001c    0
00000020 winedevice.exe
	00000026    0
	00000025    0
	00000024    0
	00000023    0
	00000021    0
00000027 explorer.exe
	0000002b    0
	0000002a    0
	00000029    0
	00000028    0
System information:
    Wine build: wine-3.0.2
    Platform: x86_64
    Version: Windows XP
    Host system: Linux
    Host version: 4.15.0-33-lowlatency

**Comment by falkTX** [comment]
All these logs that you are posted are useless if you dont tell me which plugin fails with the crash.
The one I saw being used, PolyGAS, works fine for me.
So which plugin is failing??

**Comment by falkTX** [comment]
meh, found the issue, stupid typo...

**Comment by falkTX** [comment]
will push an update to the kx repos asap, version 20180905.2

**Comment by tank-trax** [comment]
basically any VSTi

64bit
fb3300/fb330064.dll
PolyGAS_v2.4/PolyGAS64.dll
VST Classics 1/Model-E/Model-E.dll
VK-1 Viking Synthesizer/VK-1 Viking Synthesizer.dll

same thing for the list of 32bit VSTi's

it doens't happen to Effects only Intruments

**Comment by tank-trax** [comment]
~/.wine/drive_c/VST/Intruments32/Elektrostudio/Elektrostudio10AnalogPack.v.2.54b/Davosynth.dll


Unhandled exception: page fault on write access to 0x00000000 in 32-bit code (0x100c646a).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:100c646a ESP:0069f9e8 EBP:00000000 EFLAGS:00010202(  R- --  I   - - - )
 EAX:00000200 EBX:00c951c8 ECX:00000080 EDX:00000200
 ESI:00cb8c40 EDI:00000000
Stack dump:
0x0069f9e8:  00d23f28 00c951c8 00000000 00000000
0x0069f9f8:  00000001 100717af 00000000 00000080
0x0069fa08:  00c93580 00c951c8 00000080 00000080
0x0069fa18:  00000000 00000080 1005d70e 00000080
0x0069fa28:  00000200 007d35b8 0069fcc8 00000010
0x0069fa38:  00000080 1005b828 00000200 0069fbb0
Backtrace:
=>0 0x100c646a in davosynth (+0xc646a) (0x00000000)
0x100c646a: repe movsl	(%esi),%es:(%edi)
Modules:
Module	Address			Debug info	Name (89 modules)
PE	  370000-  37f000	Deferred        elstun70.sem
PE	  380000-  38f000	Deferred        elstun69.sem
PE	  390000-  39f000	Deferred        elstun84.sem
PE	  3a0000-  3af000	Deferred        elstun88.sem
PE	  3b0000-  3bf000	Deferred        elstun77.sem
PE	  3c0000-  3cf000	Deferred        elstun61.sem
PE	  3d0000-  3df000	Deferred        elstun85.sem
PE	  3e0000-  3ef000	Deferred        elstun04.sem
PE	  3f0000-  3ff000	Deferred        elstun89.sem
PE	  400000-  498000	Deferred        carla-discovery-win32
PE	  8d0000-  8df000	Deferred        dh_midi control meister_b.sep
PE	  9f0000-  9fe000	Deferred        dh_midi control meister_a.sep
PE	 2120000- 212f000	Deferred        elstun68.sem
PE	 2340000- 234f000	Deferred        elstun49.sem
PE	 2560000- 256f000	Deferred        elstun94.sem
PE	 2780000- 278f000	Deferred        elstun50.sem
PE	 29a0000- 29af000	Deferred        elstun95.sem
PE	 2bc0000- 2bcf000	Deferred        elstun29.sem
PE	 2de0000- 2def000	Deferred        elstun11.sem
PE	10000000-10355000	Export          davosynth
ELF	7b400000-7b7ea000	Deferred        kernel32<elf>
  \-PE	7b410000-7b7ea000	\               kernel32
ELF	7bc00000-7bcfc000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bcfc000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d8e5000-7d978000	Deferred        gdiplus<elf>
  \-PE	7d8f0000-7d978000	\               gdiplus
ELF	7d978000-7d9b0000	Deferred        uxtheme<elf>
  \-PE	7d980000-7d9b0000	\               uxtheme
ELF	7d9b0000-7d9c3000	Deferred        libxi.so.6
ELF	7d9c3000-7d9cf000	Deferred        libxrender.so.1
ELF	7d9cf000-7d9d6000	Deferred        libxxf86vm.so.1
ELF	7d9d6000-7d9dd000	Deferred        libxdmcp.so.6
ELF	7d9dd000-7d9e1000	Deferred        libxau.so.6
ELF	7d9e1000-7da07000	Deferred        libxcb.so.1
ELF	7da07000-7db52000	Deferred        libx11.so.6
ELF	7db52000-7db67000	Deferred        libxext.so.6
ELF	7db96000-7dc24000	Deferred        winex11<elf>
  \-PE	7dba0000-7dc24000	\               winex11
ELF	7dc24000-7dc48000	Deferred        imm32<elf>
  \-PE	7dc30000-7dc48000	\               imm32
ELF	7dced000-7dd17000	Deferred        libexpat.so.1
ELF	7dd17000-7dd60000	Deferred        libfontconfig.so.1
ELF	7dd60000-7dd8b000	Deferred        libpng12.so.0
ELF	7dd8b000-7dda6000	Deferred        libz.so.1
ELF	7dda6000-7de56000	Deferred        libfreetype.so.6
ELF	7de85000-7dfb7000	Deferred        oleaut32<elf>
  \-PE	7dea0000-7dfb7000	\               oleaut32
ELF	7dfb7000-7dff7000	Deferred        winspool<elf>
  \-PE	7dfc0000-7dff7000	\               winspool
ELF	7dff7000-7e116000	Deferred        comctl32<elf>
  \-PE	7e000000-7e116000	\               comctl32
ELF	7e116000-7e18c000	Deferred        shlwapi<elf>
  \-PE	7e120000-7e18c000	\               shlwapi
ELF	7e18c000-7e3dc000	Deferred        shell32<elf>
  \-PE	7e1a0000-7e3dc000	\               shell32
ELF	7e3dc000-7e4c7000	Deferred        comdlg32<elf>
  \-PE	7e3e0000-7e4c7000	\               comdlg32
ELF	7e4c7000-7e4f2000	Deferred        msacm32<elf>
  \-PE	7e4d0000-7e4f2000	\               msacm32
ELF	7e4f2000-7e573000	Deferred        rpcrt4<elf>
  \-PE	7e500000-7e573000	\               rpcrt4
ELF	7e573000-7e6ce000	Deferred        ole32<elf>
  \-PE	7e590000-7e6ce000	\               ole32
ELF	7e6ce000-7e746000	Deferred        advapi32<elf>
  \-PE	7e6e0000-7e746000	\               advapi32
ELF	7e746000-7e875000	Deferred        gdi32<elf>
  \-PE	7e750000-7e875000	\               gdi32
ELF	7e875000-7ea55000	Deferred        user32<elf>
  \-PE	7e890000-7ea55000	\               user32
ELF	7ea55000-7eb0d000	Deferred        winmm<elf>
  \-PE	7ea60000-7eb0d000	\               winmm
ELF	7eb0d000-7eb30000	Deferred        libtinfo.so.5
ELF	7eb30000-7eb56000	Deferred        libncurses.so.5
ELF	7eb56000-7ec0f000	Deferred        msvcrt<elf>
  \-PE	7eb70000-7ec0f000	\               msvcrt
ELF	7ef41000-7ef54000	Deferred        libnss_files.so.2
ELF	7ef54000-7ef61000	Deferred        libnss_nis.so.2
ELF	7ef61000-7ef7c000	Deferred        libnsl.so.1
ELF	7ef7c000-7efd1000	Deferred        libm.so.6
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f7be3000-f7be8000	Deferred        libdl.so.2
ELF	f7be8000-f7d9e000	Deferred        libc.so.6
ELF	f7d9e000-f7dbb000	Deferred        libpthread.so.0
ELF	f7de0000-f7dea000	Deferred        libnss_compat.so.2
ELF	f7dea000-f7fa1000	Dwarf           libwine.so.1
ELF	f7fa2000-f7fc7000	Deferred        ld-linux.so.2
ELF	f7fca000-f7fcc000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\usr\lib\carla\carla-discovery-win32.exe
	00000009    0 <==
0000000e services.exe
	00000022    0
	0000001d    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	0000001a    0
	00000017    0
	00000016    0
	00000012    0
0000001b plugplay.exe
	0000001f    0
	0000001e    0
	0000001c    0
00000020 winedevice.exe
	00000024    0
	00000023    0
	00000021    0
00000027 explorer.exe
	0000002b    0
	0000002a    0
	00000029    0
	00000028    0
System information:
    Wine build: wine-3.0.2
    Platform: i386 (WOW64)
    Version: Windows XP
    Host system: Linux
    Host version: 4.15.0-33-lowlatency
