### ISSUE TITLE
still can't load VSTi's

### ISSUE THREAD

**Issue by tank-trax** [falkTX/Carla#721]
wine /usr/lib/carla/carla-discovery-win32.exe vst ~/.wine/drive_c/VST/Intruments32/Elektrostudio/Elektrostudio10AnalogPack.v.2.54b/Davosynth.dll
0009:fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Ani"!

carla-discovery::warning::Plugin requested idle more than once

carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo"

carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo"
wine: Unhandled page fault on write access to 0x00000000 at address 0x100c646a (thread 0009), starting debugger...

---------------

Unhandled exception: page fault on write access to 0x00000000 in 32-bit code (0x100c646a).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:100c646a ESP:0069f9e8 EBP:00000000 EFLAGS:00010202(  R- --  I   - - - )
 EAX:00000200 EBX:00c951c8 ECX:00000080 EDX:00000200
 ESI:00cb8c40 EDI:00000000
Stack dump:
0x0069f9e8:  00d23f28 00c951c8 00000000 00000000
0x0069f9f8:  00000001 100717af 00000000 00000080
0x0069fa08:  00c93580 00c951c8 00000080 00000080
0x0069fa18:  00000000 00000080 1005d70e 00000080
0x0069fa28:  00000200 007d35b8 0069fcc8 00000010
0x0069fa38:  00000080 1005b828 00000200 0069fbb0
Backtrace:
=>0 0x100c646a in davosynth (+0xc646a) (0x00000000)
0x100c646a: repe movsl	(%esi),%es:(%edi)
Modules:
Module	Address			Debug info	Name (89 modules)
PE	  370000-  37f000	Deferred        elstun70.sem
PE	  380000-  38f000	Deferred        elstun69.sem
PE	  390000-  39f000	Deferred        elstun84.sem
PE	  3a0000-  3af000	Deferred        elstun88.sem
PE	  3b0000-  3bf000	Deferred        elstun77.sem
PE	  3c0000-  3cf000	Deferred        elstun61.sem
PE	  3d0000-  3df000	Deferred        elstun85.sem
PE	  3e0000-  3ef000	Deferred        elstun04.sem
PE	  3f0000-  3ff000	Deferred        elstun89.sem
PE	  400000-  498000	Deferred        carla-discovery-win32
PE	  8d0000-  8df000	Deferred        dh_midi control meister_b.sep
PE	  9f0000-  9fe000	Deferred        dh_midi control meister_a.sep
PE	 2120000- 212f000	Deferred        elstun68.sem
PE	 2340000- 234f000	Deferred        elstun49.sem
PE	 2560000- 256f000	Deferred        elstun94.sem
PE	 2780000- 278f000	Deferred        elstun50.sem
PE	 29a0000- 29af000	Deferred        elstun95.sem
PE	 2bc0000- 2bcf000	Deferred        elstun29.sem
PE	 2de0000- 2def000	Deferred        elstun11.sem
PE	10000000-10355000	Export          davosynth
ELF	7b400000-7b7ea000	Deferred        kernel32<elf>
  \-PE	7b410000-7b7ea000	\               kernel32
ELF	7bc00000-7bcfc000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bcfc000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d8ee000-7d981000	Deferred        gdiplus<elf>
  \-PE	7d900000-7d981000	\               gdiplus
ELF	7d981000-7d9b9000	Deferred        uxtheme<elf>
  \-PE	7d990000-7d9b9000	\               uxtheme
ELF	7d9b9000-7d9cc000	Deferred        libxi.so.6
ELF	7d9cc000-7d9d8000	Deferred        libxrender.so.1
ELF	7d9d8000-7d9df000	Deferred        libxxf86vm.so.1
ELF	7d9df000-7d9e6000	Deferred        libxdmcp.so.6
ELF	7d9e6000-7d9ea000	Deferred        libxau.so.6
ELF	7d9ea000-7da10000	Deferred        libxcb.so.1
ELF	7da10000-7db5b000	Deferred        libx11.so.6
ELF	7db5b000-7db70000	Deferred        libxext.so.6
ELF	7db9f000-7dc2d000	Deferred        winex11<elf>
  \-PE	7dbb0000-7dc2d000	\               winex11
ELF	7dc2d000-7dc51000	Deferred        imm32<elf>
  \-PE	7dc30000-7dc51000	\               imm32
ELF	7dced000-7dd17000	Deferred        libexpat.so.1
ELF	7dd17000-7dd60000	Deferred        libfontconfig.so.1
ELF	7dd60000-7dd8b000	Deferred        libpng12.so.0
ELF	7dd8b000-7dda6000	Deferred        libz.so.1
ELF	7dda6000-7de56000	Deferred        libfreetype.so.6
ELF	7de85000-7dfb7000	Deferred        oleaut32<elf>
  \-PE	7dea0000-7dfb7000	\               oleaut32
ELF	7dfb7000-7dff7000	Deferred        winspool<elf>
  \-PE	7dfc0000-7dff7000	\               winspool
ELF	7dff7000-7e116000	Deferred        comctl32<elf>
  \-PE	7e000000-7e116000	\               comctl32
ELF	7e116000-7e18c000	Deferred        shlwapi<elf>
  \-PE	7e120000-7e18c000	\               shlwapi
ELF	7e18c000-7e3dc000	Deferred        shell32<elf>
  \-PE	7e1a0000-7e3dc000	\               shell32
ELF	7e3dc000-7e4c7000	Deferred        comdlg32<elf>
  \-PE	7e3e0000-7e4c7000	\               comdlg32
ELF	7e4c7000-7e4f2000	Deferred        msacm32<elf>
  \-PE	7e4d0000-7e4f2000	\               msacm32
ELF	7e4f2000-7e573000	Deferred        rpcrt4<elf>
  \-PE	7e500000-7e573000	\               rpcrt4
ELF	7e573000-7e6ce000	Deferred        ole32<elf>
  \-PE	7e590000-7e6ce000	\               ole32
ELF	7e6ce000-7e746000	Deferred        advapi32<elf>
  \-PE	7e6e0000-7e746000	\               advapi32
ELF	7e746000-7e875000	Deferred        gdi32<elf>
  \-PE	7e750000-7e875000	\               gdi32
ELF	7e875000-7ea55000	Deferred        user32<elf>
  \-PE	7e890000-7ea55000	\               user32
ELF	7ea55000-7eb0d000	Deferred        winmm<elf>
  \-PE	7ea60000-7eb0d000	\               winmm
ELF	7eb0d000-7eb30000	Deferred        libtinfo.so.5
ELF	7eb30000-7eb56000	Deferred        libncurses.so.5
ELF	7eb56000-7ec0f000	Deferred        msvcrt<elf>
  \-PE	7eb70000-7ec0f000	\               msvcrt
ELF	7ef41000-7ef54000	Deferred        libnss_files.so.2
ELF	7ef54000-7ef61000	Deferred        libnss_nis.so.2
ELF	7ef61000-7ef7c000	Deferred        libnsl.so.1
ELF	7ef7c000-7efd1000	Deferred        libm.so.6
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f7b4c000-f7b51000	Deferred        libdl.so.2
ELF	f7b51000-f7d07000	Deferred        libc.so.6
ELF	f7d07000-f7d24000	Deferred        libpthread.so.0
ELF	f7d26000-f7d30000	Deferred        libnss_compat.so.2
ELF	f7d53000-f7f0a000	Dwarf           libwine.so.1
ELF	f7f0b000-f7f30000	Deferred        ld-linux.so.2
ELF	f7f33000-f7f35000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\usr\lib\carla\carla-discovery-win32.exe
	00000009    0 <==
0000000e services.exe
	00000022    0
	0000001d    0
	00000015    0
	00000014    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	0000001a    0
	00000019    0
	00000018    0
	00000017    0
	00000016    0
	00000012    0
0000001b plugplay.exe
	0000001f    0
	0000001e    0
	0000001c    0
00000020 winedevice.exe
	00000026    0
	00000025    0
	00000024    0
	00000023    0
	00000021    0
00000027 explorer.exe
	0000002b    0
	0000002a    0
	00000029    0
	00000028    0
System information:
    Wine build: wine-3.0.2
    Platform: i386 (WOW64)
    Version: Windows XP
    Host system: Linux
    Host version: 4.15.0-33-lowlatency

---------------

wine64 /usr/lib/carla/carla-discovery-win64.exe vst ~/.wine/dosdevices/c:/VST/Intruments64/fb3300/fb330064.dll
vstHostCallback(000000000007f570, 42:audioMasterUpdateDisplay, 0, 0, 0000000000000000, 0.000000)
vstHostCallback(000000000007f570, 42:audioMasterUpdateDisplay, 0, 0, 0000000000000000, 0.000000)

carla-discovery::warning::Plugin requested timeInfo but didn't ask if host could do "sendVstTimeInfo"
wine: Unhandled page fault on write access to 0x00000000 at address 0x1800449b9 (thread 0009), starting debugger...
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 11
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 10
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 9
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 8
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 7
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 11
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 10
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 9
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 8
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 7
002e:fixme:dbghelp:interpret_function_table_entry PUSH_MACHFRAME 6

---------------

Unhandled exception: page fault on write access to 0x00000000 in 64-bit code (0x00000001800449b9).
Register dump:
 rip:00000001800449b9 rsp:000000000033f708 rbp:0000000000000200 eflags:00010203 (  R- --  I   - - -C)
 rax:0000000000000000 rbx:0000000000000800 rcx:0000000000000800 rdx:000000000007f570
 rsi:000000000007eb30 rdi:0000000000000000  r8:0000000000000800  r9:0000000000000000 r10:00000000005c0000
 r11:0000000000000000 r12:0000000000486e80 r13:000000000000000c r14:0000000000000000 r15:0000000000000000
Stack dump:
0x000000000033f708:  0000000180016bad 0000000000000000
0x000000000033f718:  0000000000000000 0000000000000000
0x000000000033f728:  000000000033f840 0000000000000000
0x000000000033f738:  0000000000000000 0000000000000000
0x000000000033f748:  0000000000000000 0000000000000000
0x000000000033f758:  0000000000000000 000000000007eb30
0x000000000033f768:  0000000000000001 0000000000000001
0x000000000033f778:  00000001800030ab 000000000033f860
0x000000000033f788:  000000000007eb30 0000000000000200
0x000000000033f798:  000000000033f840 000000000007eb50
0x000000000033f7a8:  00000001800032b0 fffffffffffffffe
0x000000000033f7b8:  000000000033f860 000000000007eb30
Backtrace:
=>0 0x00000001800449b9 in fb330064 (+0x449b9) (0x0000000000000200)
  1 0x0000000180016bad in fb330064 (+0x16bac) (0x0000000000000200)
  2 0x00000001800032b0 in fb330064 (+0x32af) (0x000000000033f840)
  3 0x000000000041ae18 in carla-discovery-win64 (+0x1ae17) (0x000000000033f8c0)
  4 0x000000000046fccd in carla-discovery-win64 (+0x6fccc) (0x000000000033fba0)
  5 0x00000000004013e8 in carla-discovery-win64 (+0x13e7) (0x00000000004b1b00)
  6 0x000000000040151b in carla-discovery-win64 (+0x151a) (0x000000000033ffd0)
  7 0x000000007b47a6a8 in kernel32 (+0x5a6a7) (0x000000000033ffd0)
0x00000001800449b9: repe stosb	%es:(%rdi)
Modules:
Module	Address					Debug info	Name (105 modules)
PE	          400000-          4ad000	Export          carla-discovery-win64
ELF	        7b400000-        7b819000	Dwarf           kernel32<elf>
  \-PE	        7b420000-        7b819000	\               kernel32
ELF	        7bc00000-        7bd22000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bd22000	\               ntdll
ELF	        7c000000-        7c004000	Deferred        <wine-loader>
PE	       180000000-       180268000	Export          fb330064
ELF	    7fa1676c1000-    7fa1678d5000	Deferred        api-ms-win-core-sysinfo-l1-2-1<e
PE	    7fa1676d0000-    7fa1678d5000	Deferred        api-ms-win-core-sysinfo-l1-2-1
PE	    7fa1678d5000-    7fa167ae9000	Deferred        api-ms-win-core-localization-l1-
PE	    7fa1678e0000-    7fa167ae9000	Deferred        api-ms-win-core-localization-l1-C:\windows\system32\api-ms-win-core-localization-l1-2-1.dll
ELF	    7fa167ae9000-    7fa167cfc000	Deferred        api-ms-win-core-fibers-l1-1-1<el
PE	    7fa167af0000-    7fa167cfc000	Deferred        api-ms-win-core-fibers-l1-1-1
ELF	    7fa167cfc000-    7fa167f10000	Deferred        api-ms-win-core-synch-l1-2-0<elf
PE	    7fa167d00000-    7fa167f10000	Deferred        api-ms-win-core-synch-l1-2-0
ELF	    7fa167f10000-    7fa168124000	Deferred        libgpg-error.so.0
ELF	    7fa168124000-    7fa168394000	Deferred        libpcre.so.3
ELF	    7fa168394000-    7fa168675000	Deferred        libgcrypt.so.20
ELF	    7fa168675000-    7fa168897000	Deferred        liblzma.so.5
ELF	    7fa168897000-    7fa168a9f000	Deferred        librt.so.1
ELF	    7fa168a9f000-    7fa168cc1000	Deferred        libselinux.so.1
ELF	    7fa168cc1000-    7fa168d46000	Deferred        libsystemd.so.0
ELF	    7fa168d46000-    7fa168f4e000	Deferred        libffi.so.6
ELF	    7fa168f4e000-    7fa169169000	Deferred        libresolv.so.2
ELF	    7fa169169000-    7fa16936d000	Deferred        libkeyutils.so.1
ELF	    7fa16936d000-    7fa1695b9000	Deferred        libdbus-1.so.3
ELF	    7fa1695b9000-    7fa169839000	Deferred        libgmp.so.10
ELF	    7fa169839000-    7fa169a6c000	Deferred        libhogweed.so.4
ELF	    7fa169a6c000-    7fa169ca2000	Deferred        libnettle.so.6
ELF	    7fa169ca2000-    7fa169eb5000	Deferred        libtasn1.so.6
ELF	    7fa169eb5000-    7fa16a0e8000	Deferred        libidn.so.11
ELF	    7fa16a0e8000-    7fa16a34c000	Deferred        libp11-kit.so.0
ELF	    7fa16a34c000-    7fa16a557000	Deferred        libkrb5support.so.0
ELF	    7fa16a557000-    7fa16a75b000	Deferred        libcom_err.so.2
ELF	    7fa16a75b000-    7fa16a98a000	Deferred        libk5crypto.so.3
ELF	    7fa16a98a000-    7fa16ac5c000	Deferred        libkrb5.so.3
ELF	    7fa16ac5c000-    7fa16ae6d000	Deferred        libavahi-client.so.3
ELF	    7fa16ae6d000-    7fa16b079000	Deferred        libavahi-common.so.3
ELF	    7fa16b079000-    7fa16b3a9000	Deferred        libgnutls.so.30
ELF	    7fa16b3a9000-    7fa16b5f3000	Deferred        libgssapi_krb5.so.2
ELF	    7fa16b5f3000-    7fa16b873000	Deferred        libcups.so.2
ELF	    7fa16b8a2000-    7fa16bae0000	Deferred        uxtheme<elf>
  \-PE	    7fa16b8b0000-    7fa16bae0000	\               uxtheme
ELF	    7fa16bae0000-    7fa16bce6000	Deferred        libxfixes.so.3
ELF	    7fa16bce6000-    7fa16bef0000	Deferred        libxcursor.so.1
ELF	    7fa16bef0000-    7fa16c100000	Deferred        libxi.so.6
ELF	    7fa16c100000-    7fa16c303000	Deferred        libxcomposite.so.1
ELF	    7fa16c303000-    7fa16c50e000	Deferred        libxrandr.so.2
ELF	    7fa16c50e000-    7fa16c718000	Deferred        libxrender.so.1
ELF	    7fa16c718000-    7fa16c91e000	Deferred        libxxf86vm.so.1
ELF	    7fa16c91e000-    7fa16cb21000	Deferred        libxinerama.so.1
ELF	    7fa16cb21000-    7fa16cd27000	Deferred        libxdmcp.so.6
ELF	    7fa16cd27000-    7fa16cf2b000	Deferred        libxau.so.6
ELF	    7fa16cf2b000-    7fa16d14d000	Deferred        libxcb.so.1
ELF	    7fa16d14d000-    7fa16d487000	Deferred        libx11.so.6
ELF	    7fa16d487000-    7fa16d699000	Deferred        libxext.so.6
ELF	    7fa16d6c8000-    7fa16d969000	Deferred        winex11<elf>
  \-PE	    7fa16d6e0000-    7fa16d969000	\               winex11
ELF	    7fa16d969000-    7fa16db91000	Deferred        imm32<elf>
  \-PE	    7fa16d970000-    7fa16db91000	\               imm32
ELF	    7fa16dc97000-    7fa16dec0000	Deferred        libexpat.so.1
ELF	    7fa16dec0000-    7fa16e103000	Deferred        libfontconfig.so.1
ELF	    7fa16e103000-    7fa16e328000	Deferred        libpng12.so.0
ELF	    7fa16e328000-    7fa16e5d2000	Deferred        libfreetype.so.6
ELF	    7fa16e5d2000-    7fa16e81b000	Deferred        winspool<elf>
  \-PE	    7fa16e5e0000-    7fa16e81b000	\               winspool
ELF	    7fa16e81b000-    7fa16eb15000	Deferred        comdlg32<elf>
  \-PE	    7fa16e820000-    7fa16eb15000	\               comdlg32
ELF	    7fa16eb15000-    7fa16ee4c000	Deferred        comctl32<elf>
  \-PE	    7fa16eb20000-    7fa16ee4c000	\               comctl32
ELF	    7fa16ee4c000-    7fa16f08d000	Deferred        ws2_32<elf>
  \-PE	    7fa16ee50000-    7fa16f08d000	\               ws2_32
ELF	    7fa16f08d000-    7fa16f52b000	Deferred        shell32<elf>
  \-PE	    7fa16f0b0000-    7fa16f52b000	\               shell32
ELF	    7fa16f52b000-    7fa16f7bf000	Deferred        shlwapi<elf>
  \-PE	    7fa16f540000-    7fa16f7bf000	\               shlwapi
ELF	    7fa16f7bf000-    7fa16f9d9000	Deferred        version<elf>
  \-PE	    7fa16f7c0000-    7fa16f9d9000	\               version
ELF	    7fa16f9d9000-    7fa16fc70000	Deferred        advapi32<elf>
  \-PE	    7fa16f9f0000-    7fa16fc70000	\               advapi32
ELF	    7fa16fc70000-    7fa16fff0000	Deferred        gdi32<elf>
  \-PE	    7fa16fc90000-    7fa16fff0000	\               gdi32
ELF	    7fa16fff0000-    7fa170435000	Deferred        user32<elf>
  \-PE	    7fa170010000-    7fa170435000	\               user32
ELF	    7fa170435000-    7fa170661000	Deferred        mpr<elf>
  \-PE	    7fa170440000-    7fa170661000	\               mpr
ELF	    7fa170661000-    7fa17087b000	Deferred        libz.so.1
ELF	    7fa17087b000-    7fa170b03000	Deferred        wininet<elf>
  \-PE	    7fa170890000-    7fa170b03000	\               wininet
ELF	    7fa170c03000-    7fa170e2c000	Deferred        libtinfo.so.5
ELF	    7fa170e2c000-    7fa17104e000	Deferred        libncurses.so.5
ELF	    7fa17114e000-    7fa171428000	Deferred        msvcrt<elf>
  \-PE	    7fa171170000-    7fa171428000	\               msvcrt
ELF	    7fa171700000-    7fa171912000	Deferred        libnss_files.so.2
ELF	    7fa171912000-    7fa171b1e000	Deferred        libnss_nis.so.2
ELF	    7fa171b1e000-    7fa171d37000	Deferred        libnsl.so.1
ELF	    7fa171d37000-    7fa171f40000	Deferred        libnss_compat.so.2
ELF	    7fa172140000-    7fa172356000	Deferred        libgcc_s.so.1
ELF	    7fa172356000-    7fa17265f000	Deferred        libm.so.6
ELF	    7fa172662000-    7fa172866000	Deferred        libdl.so.2
ELF	    7fa172867000-    7fa172c31000	Deferred        libc.so.6
ELF	    7fa172c31000-    7fa172e4e000	Deferred        libpthread.so.0
ELF	    7fa172e7d000-    7fa173223000	Dwarf           libwine.so.1
ELF	    7fa173224000-    7fa17344c000	Deferred        ld-linux-x86-64.so.2
ELF	    7fffc6bfe000-    7fffc6c00000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\usr\lib\carla\carla-discovery-win64.exe
	00000009    0 <==
0000000e services.exe
	00000023    0
	0000001e    0
	00000018    0
	00000015    0
	00000014    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	0000001b    0
	0000001a    0
	00000019    0
	00000017    0
	00000016    0
	00000012    0
0000001c plugplay.exe
	00000020    0
	0000001f    0
	0000001d    0
00000021 winedevice.exe
	00000027    0
	00000026    0
	00000025    0
	00000024    0
	00000022    0
00000028 explorer.exe
	0000002c    0
	0000002b    0
	0000002a    0
	00000029    0
System information:
    Wine build: wine-3.0.2
    Platform: x86_64
    Version: Windows XP
    Host system: Linux
    Host version: 4.15.0-33-lowlatency

---------------

**Comment by falkTX** [comment]
Why did you open a new issue?
Just leave a comment on the other one next time.

Anyway, the issue *is fixed*, I just need to update the kxstudio repos now.
If you built carla yourself, you would not have the issue.

**Comment by tank-trax** [comment]
My apologies. Just did the update and the same thing happened.

**Comment by tank-trax** [comment]
out of curiosity how to build the source code with WIN VST bridge support

**Comment by tank-trax** [comment]
no need to reply.... I figured it out... compiled it from your git clone...

it's all good now

thanks!!!
