### ISSUE TITLE
Carla missing WINE bridge

### ISSUE THREAD

**Issue by tank-trax** [falkTX/Carla#722]
after updating via Synaptic this is what the plug in scan screen gives...
![carla repo](https://user-images.githubusercontent.com/41337033/45104225-981d3480-b0ff-11e8-921c-ee6c9dbb9566.png)

i compiled the git clone and the WINE bridge works but can't scan new Soundfonts
![carla comp](https://user-images.githubusercontent.com/41337033/45104303-cf8be100-b0ff-11e8-89fb-cc1f9a53e581.png)

![no fluid](https://user-images.githubusercontent.com/41337033/45104316-d581c200-b0ff-11e8-8902-8d399fb1e864.png)

**Comment by tank-trax** [comment]
make features provides the following:

---> Main features 
Front-End:     YES (Using Qt5)
LV2 plugin:    YES
VST plugin:    YES
Link support:  YES
OSC support:   YES
Binary detect: YES

---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  YES
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]
WASAPI:      NO  [Windows only]

---> Plugin formats: 
Internal: YES
LADSPA:   YES
DSSI:     YES
LV2:      YES
VST:      YES (with UI)

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     YES (bridge)
Gtk3:     YES (bridge)
Qt4:      YES (bridge)
Qt5:      YES (bridge)
X11:      YES (direct+bridge)
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
Basic: YES
Extra: NO [FFmpeg missing or too new]
SF2/3: YES
SFZ:   YES

---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: NO
david@Studio ~/Desktop/Carla $

**Comment by falkTX** [comment]
if you installed some extra packages after an initial build, then `make features` is useless.
it displays the features for a *future* build.
your previous build had no fluidsynth support, so do a "make clean" and "make" again.

the updates removing bridges is just not possible...
likely some conflict with something else.

**Comment by tank-trax** [comment]
thanks. all is well now.
