### ISSUE TITLE
Carla compilation incomplete and Fluidsynth missing

### ISSUE THREAD

**Issue by tank-trax** [falkTX/Carla#735]
I have all the requisite packages yet when I try to build from source (on a fresh install of Linux) 'make features' states -> SF2/3: NO [FluidSynth missing or too old]

FluidSynth is installed as well as libfluidsynth-dev

I even tried updating fluidsynth-dev
I have version libfluidsynth-dev_1.1.6-4_amd64 installed

Am I missing something? I was able to build this last week (on another installation)

**Comment by falkTX** [comment]
I bumped the requirement of fluidsynth to 1.1.6 in 5b3db940e43263b091d064a826336900b2515549
Optionally handling sf3 support would be a pain, for something I would never use myself at all, so I took a shortcut to save myself some time.

You can force the build with fluidsynth on by using `make HAVE_FLUIDSYNTH=true`.
But i really recommend to update fluidsynth, as newer versions fixed possible crashes.
