### ISSUE TITLE
Carla not discovering 64bit plugin when using wine-rt binary

### ISSUE THREAD

**Issue by bellt** [falkTX/Carla#736]
I use "wine-rt" as my wine binary in carla for VST bridging. 

The only VST I use is Steven Slate Drums 4, and after a recent update of a whole bunch of things, the 64bit version of the plugin disappeared from the list of available plugins in carla. The 32bit version is still there and works, but it feels a little less stable?

Here are a few of the packages that were updated just before it stopped working:
```
wine-rt-amd64:amd64 (2:2.0.1-1~xenial1, 2:3.0.2-1~kxstudio2v5), 
carla-git:amd64 (2:1.9.9+git20180721v5, 2:1.9.9+git20180819.2v5), 
wine-rt:amd64 (2:2.0.1-1~xenial1, 2:3.0.2-1~kxstudio2v5), 
linux-image-lowlatency-hwe-16.04:amd64 (4.15.0.30.52, 4.15.0.32.54), 
carla-lv2:amd64 (2:1.9.9+git20180721v5, 2:1.9.9+git20180819.2v5), 
carla-data:amd64 (2:1.9.9+git20180721v5, 2:1.9.9+git20180819.2v5), 
carla-bridge-win32:amd64 (2:1.9.8+git20180625, 2:1.9.8+git20180819), 
wine-rt-i386:i386 (2:2.0.1-1~xenial1, 2:3.0.2-1~kxstudio2v5), 
carla-bridge-wine64:amd64 (2:1.9.8+git20180625, 2:1.9.8+git20180819)
```
(after pasting this, I've noticed that I have gone from an ubuntu packaged version of wine-rt to a kxstudio one, so maybe that's the cause of the problem?)

It looks like carla-bridge can still see the plugin when run from the command line:
```
wine-rt /usr/lib/carla/carla-discovery-win64.exe vst /home/tomb/.wine/drive_c/Program\ Files/VstPlugins/SsdSampler.dll 
00b1:fixme:heap:RtlSetHeapInformation 0x6d0000 0 0x33f4b0 4 stub
00b1:fixme:heap:RtlSetHeapInformation 0x6d0000 0 0x33f4b0 4 stub

carla-discovery::init::-----------

carla-discovery::build::4

carla-discovery::hints::12

carla-discovery::name::SSDSampler

carla-discovery::label::SSDSampler

carla-discovery::maker::Slate Digital

carla-discovery::uniqueId::1399681132

carla-discovery::audio.ins::0

carla-discovery::audio.outs::24

carla-discovery::midi.ins::1

carla-discovery::midi.outs::0

carla-discovery::parameters.ins::5

carla-discovery::end::------------
```

If I just use "wine" as my wine binary in carla, then it sees the 64bit version but I get all kinds of xruns when using the plugin.

**Comment by falkTX** [comment]
Using "wine-rt" from the command-line is okay, but don't set it as the wine to use under carla.
Carla automatically adds a "64" suffix to the command when running 64bit plugins, so it would try to start the plugin using wine-rt64 which does not exist (maybe I should create it though...)
There is no need to set wine-rt as the wine to use in Carla gui, as the variable it sets before starting the application are then overridden by carla.

Your wine version seems wrong though, and I bet that is the source of issues.
"2:3.0.2-1~kxstudio2v5" version seems fine, it is built for xenial as well.
Maybe it is this wine version that is less stable.
I recommend to try wine-staging and see if it makes any difference.

**Comment by bellt** [comment]
Thanks for your feedback falk.
Your comment about Carla automatically adding the "64" suffix is interesting, because before this update I had been using "wine-rt" for the binary in the Carla gui for about a year, and it was running the 64bit version of the VST without any issues. And I definitely notice a difference between using "wine-rt" and "wine". If I just set it to "wine", then xruns occur seemingly randomly while the VST is running. When using "wine-rt", I only get xruns when I first load up the VST and then none after that.

I just tried using "wine", but setting the realtime base priority to 55 and wineserver priority to 70 in Carla (juding from the command line output when using wine-rt, that is what wine-rt is setting). That hasn't appeared to have made a difference and I am still getting the random xruns (I just had a few hundred occur whilst writing this comment).

I'm a little confused by your comment about my wine version. You said it seems wrong, but then stated that the version I have seems fine? The update in question took it from "2:2.0.1-1\~xenial1" to "2:3.0.2-1\~kxstudio2v5"

Anyway, I'll get wine-staging installed and see how that goes.

Thanks again.

**Comment by falkTX** [comment]
ah, nevermind my comment. morning brain not working properly.
I was writing something, deleted half and forgot to correct the rest.
the version of wine-rt you have installed is fine.

curious thing about the wine env vars, I will have to do some tests.
btw, are you running carla as standalone or as a plugin in a daw?

PS: I am dealing with the wine-rt package now to add a wine-rt64 script

**Comment by bellt** [comment]
Ah yes, I know what it's like to change what you were writing but then forget to delete what you originally wrote! An all too common occurence for me...

I'm running Carla standalone. It is basically just hosting Steven Slate Drums so I can use it with my edrums when I practice.

**Comment by falkTX** [comment]
ok, then something fishy is going on. perhaps the env vars not being set correctly.
I added this issue to RC1 milestone, will handle it asap.

**Comment by bellt** [comment]
Awesome, thank you.

**Comment by falkTX** [comment]
Just found out wine-rt patch only applies to base wine, not wine64.
That explains some things.
I fixed carla to handle wine commands without a "64" suffix, just in case.
