### ISSUE TITLE
LMMS + Carla macOS specific issues

### ISSUE THREAD

**Issue by falkTX** [falkTX/Carla#737]
- [x] Mouse events pass-through MDI windows when carla is loaded
- [x] LMMS is not able to restart (not reproducible on CLI)
- [x] Create new carla-plugin.so file (and pkg-config) for others to link to (or figure out something better)

**Comment by falkTX** [comment]
mouse events-pass through identified to not come from carla, no idea still what happens sadly.

LMMS not being able to restart seems to be caused by carla.

**Comment by tresf** [comment]
> Mouse events pass-through MDI windows when carla is loaded

Duplicate of https://github.com/LMMS/lmms/issues/4183.  Upstream reported here: https://bugreports.qt.io/browse/QTBUG-69343?attachmentOrder=desc

**Comment by falkTX** [comment]
thanks for the confirmation!
so just 1 last issue left to do (besides getting lmms to build with the new carla stuff, but that is outside of carla now)

**Comment by tresf** [comment]
> Mouse events pass-through MDI windows when carla is loaded

FYI, patched downstream by [removing the call to `winId()`](https://github.com/LMMS/lmms/pull/4558/commits/38e48c0d2d7aec080098bcbe94fac6b5005a347a#diff-39ebb2eece4517af2a230e4737733950R447.).

**Comment by falkTX** [comment]
after some stupid long hours debugging, issue was found and fixed.
no more tickets left for 2.0-RC1! \o/
