### ISSUE TITLE
[Feature request] List SF3 as SF3 (not SF2)

### ISSUE THREAD

**Issue by trebmuh** [falkTX/Carla#739]
_originally from https://github.com/falkTX/Carla/issues/607#issuecomment-420444846_

I've spotted a small buggish thingy: while Carla can now use a SF3, the "type column" in the search window is set to SF2. That's not a big deal but it did confuses me for a few minutes while I was searching for a SF3 with the help of the "type" column.

![carla-sf3](https://user-images.githubusercontent.com/8705846/45390859-165a6900-b621-11e8-980d-a3e782c69531.png)

**Comment by falkTX** [comment]
This ticket is now invalid. The new add-plugin dialog does not show SF2 or SF3 information
