### ISSUE TITLE
Carla assertion failure when loading 64bits windows VST

### ISSUE THREAD

**Issue by terencode** [falkTX/Carla#740]
Loading a win64 bridged plugin like VB3, Addictive Drums 2 using the "Add Plugin" button from carla standalone

> Carla assertion failure: "path.startsWith ("./") || path.startsWith ("../")" in file files/File.cpp, line 222

Archlinux 4.18.7
wine=3.15
carla 1:1.9.9.r323.gf114739e-1

**Comment by falkTX** [comment]
can you please add any more information on this?

**Comment by terencode** [comment]
@falkTX sure, what would you need?

**Comment by falkTX** [comment]
which plugin, wine version, distro you are using (and version).
loading in standalone, plugin mode or via carla-single?
do others fail the same way, or is it a specific one?

you really could not have given less information...

**Comment by terencode** [comment]
I updated the original post, really sorry for not providing more information.

**Comment by falkTX** [comment]
I cant reproduce. might be a thing with older carla.
You are taking the carla windows bridges from AUR right? please update them and re-test.
Thanks.

**Comment by terencode** [comment]
As said in the description, this happens with Carla built from latest master commit.

**Comment by falkTX** [comment]
but you say you have carla version 1:1.9.9.r323.gf114739e-1, this is not the latest.

**Comment by terencode** [comment]
this was the latest at the time I opened the issue, I now updated it again and the log is the same.
