### ISSUE TITLE
Plugins are not remembered

### ISSUE THREAD

**Issue by SynthaClaus** [falkTX/Carla#744]
Changes in the plugin list are not saved / remembered between instances of Carla and Patchbay (LV2). Native and bridged plugins show up in the list after scanning but are gone when a new instance of Carla is opened. Removed plugins also reappear (though they are removed) in new instances of Carla / Patchbay.

Ubuntu 18.04 Desktop x64 (lowlatency)
Carla (standalone) 1.9.11 (2.0-RC1)
Carla Patchbay LV2 in Ardour 5.12.0
Carla Patchbay VST in Waveform 9.3.4

**Comment by falkTX** [comment]
I cannot reproduce this.
There was a small time where carla in the kxstudio repos had this issue, but not anymore.
you get this behaviour in the version you describe in this bug right? not something you had before and reported just now..?

**Comment by SynthaClaus** [comment]
Yes, the version mentioned is correct; 1.9.11 (2.0-RC1). The latest update is from carla-git earlier today (sept 15, 2018). I removed carla-git, then deleted /usr/share/carla and reïnstalled carla-git. The issue persisted...

**Comment by falkTX** [comment]
Try to remove ~/.falkTX/ (the config folder where carla stuff resides) and try again.
Starting with a fresh carla I am not able to reproduce.
Maybe that file got invalid permissions and Carla can't update it anymore, I dont know...

**Comment by SynthaClaus** [comment]
I found no ~/.falkTX/ folder but I did find ~/.config/falkTX/. I renamed it and the issue was solved. A few config files in there were indeed owned by root, probably because I -accidentally- ran Carla with sudo?

Anyway, the issue is solved. Thank you for helping me out!

**Comment by falkTX** [comment]
ah yes, I meant to write ~/.config/falkTX sorry.
if it was owned by root, then indeed it was caused by use of sudo.
gui apps should not be run like that.

anyway, glad the issue is fixed. let me know if you find anything else.
