### ISSUE TITLE
[2.0 RC1] macOS indication on linux

### ISSUE THREAD

**Issue by trebmuh** [falkTX/Carla#747]
Using a 2.0-RC1 build on linux, there is an indication in the preferences which looks to be intended for the macOS users of Carla.

Suggestion to hide it on non-macOS.

![carla-macos](https://user-images.githubusercontent.com/8705846/45600517-42e5fa80-b9fe-11e8-93fc-721d4fde893e.png)

**Comment by falkTX** [comment]
Fixed in cd820b20ec0ad69cfc78ac57e81d9d09bdaaed8c

**Comment by trebmuh** [comment]
:+1:
