### ISSUE TITLE
Using OSC - Windows

### ISSUE THREAD

**Issue by anonimo82** [falkTX/Carla#748]
Dear, I'm using Carla x64 with Windows 10.
I'd like to send/receive OSC messages to/from it, but I can't find the appropriate menu item.

What should I do?

**Comment by falkTX** [comment]
Go to menu Help -> About, then OSC tab.
You will see the list of valid commands that Carla can receive.

Note that I don't use OSC much myself, so while some OSC support is in there, likely it is not done in the best way (regarding workflow).
Suggestions to make it better are welcome.

**Comment by anonimo82** [comment]
Thanks. I found the screen you was talking about, but I'm unsure what to type in the message sender.
I'm using AddOSC from Blender, http://www.jpfep.net/pages/addosc/

So, what should i do to simply trigger a note through Nekobi?

Thanks in advance

**Comment by bencrossman** [comment]
I can confirm I was successfully able to use the OSC "/set_active" command today on Windows 10.
Worked great!

**Comment by bencrossman** [comment]
Not sure if this helps but I had to use the port listed under udp (not tcp) to get my OSC command line tool to work.

**Comment by bencrossman** [comment]
Actually probably spoke a bit too soon. Although /set_active and /set_volume work great, no matter what values I send using:

/set_parameter_midi_cc
/set_parameter_midi_channel
/set_midi_program
/note_on
/note_off

Nothing is received by the VST's.

**Comment by anonimo82** [comment]
Thanks, so it's not me?

Anyhow, can you share a screenshot in which you do this in Blender, or at least tell me how to?

**Comment by anonimo82** [comment]
I got what to type for sending an OSC message to Carla, but I don't know how can I receive such event in Carla.
The message is /Carla/2/note_on 1

What's next?

**Comment by anonimo82** [comment]
So far, I've been able to rotate a cube in Blender using my phone with OSC.
I still can't get how to send NoteOn events to Carla.

Please, help.

**Comment by anonimo82** [comment]
Posting fresh
