### ISSUE TITLE
lv2 midifilter plugins not working correctly

### ISSUE THREAD

**Issue by cocreature** [falkTX/Carla#75]
The midi channel filter plugin from https://github.com/x42/midifilter.lv2 is not working correctly in Carla. Filtering seems to work however it routes everything through midi channel 1 before applying the filter which defeats the purpose of a channel filter.

**Comment by falkTX** [comment]
It has been a long time :P
Code has changed a lot, I believe Carla handles all sorts of LV2 MIDI plugins well now.

**Comment by falkTX** [comment]
@cocreature can you confirm?
thanks

**Comment by falkTX** [comment]
Locally confirmed fixed.
