### ISSUE TITLE
Dialog X Window Hint for plugin UIs

### ISSUE THREAD

**Issue by diovudau** [falkTX/Carla#750]
Automatically resizing tiling window managers resize Plugin UI windows bigger than they want leaving ugly areas on the screen full of X artefacts.
I use Qtile, if you want to test yourself.
The solution is to declare the windows as actual dialogs, not full X Windows.

These are the typical hints of a Qt Dialog, which displays correctly 
```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL
```

**Comment by falkTX** [comment]
See the code around https://github.com/falkTX/Carla/blob/master/source/utils/CarlaPluginUI.cpp#L103
This controls how X11 UIs on Linux are created.

Try some changes and send a PR please.
I dont run a tiling WM, so I do not know what to expect from them.
Thanks

**Comment by falkTX** [comment]
Made some small changes in a21e740612232819ccd5f37573df556b3f10bcbc
Tested to have desired hints with `xprop` tool.
Thanks

Note: This will be part of the next release, but not in 2.0.
