### ISSUE TITLE
Carla.lv2's x11 gui can't be resized in Qtractor

### ISSUE THREAD

**Issue by suedwestlicht** [falkTX/Carla#755]
Rui has changed the preference which UI is used when there are several. Now x11 has preference before external. That shows a bug in the x11 UI: the window can be enlarged but Carla.lv2 doesn't use that additional space. The elements are drawn as if the window wasn't resized.

Workaround: Check view->options->plugin->Select plugin's editor(GUI) if more than one are available

**Comment by falkTX** [comment]
Ah, perfect timing.
Check the develop branch, the embed UI is gone now, so this cannot be an issue anymore. :)
Will be part of the 2.1 release
