### ISSUE TITLE
[2.0-RC1] adding lxvst paths

### ISSUE THREAD

**Issue by trebmuh** [falkTX/Carla#756]
Some linux-vst plugins are installed under `/usr/lib/lxvst/` , `/usr/local/lib/lxvst/` , or `~/.lxvst/` (see https://community.ardour.org/node/7744 and http://www.manual.ardour.org/working-with-plugins/getting-plugins/).

It could be great to add it to the PATHS Carla configuration basics.

**Comment by falkTX** [comment]
Added in 63769e798c3e0ea057ff2f6672f9108b7646f763

**Comment by trebmuh** [comment]
:+1: thanks
