### ISSUE TITLE
[Feature request] [2.0 RC1] drag'n'drop plugin into the patchbay

### ISSUE THREAD

**Issue by trebmuh** [falkTX/Carla#759]
While it's possible to drag'n'drop a plugin from the embedded Carla's list browser (on the left) in the **rack tab**, it's not possible to do the same in the **patchbay tab**.

It'd be great to do it so.

**Comment by falkTX** [comment]
Since the rework yesterday to make backend save canvas positions, new plugins always get added to the middle of the canvas.
I added d&d to the patchbay area in cfa1bf23e420c50f874661c0b76a05d9a66265bc

**Comment by trebmuh** [comment]
Nice, thanks you.
