### ISSUE TITLE
Building for Windows 10

### ISSUE THREAD

**Issue by bencrossman** [falkTX/Carla#763]
Hi

I understand you prefer developers don't compile their own builds but just so I can test code changes and maybe one day contribute to the repo, just wondering where the final carla.exe (inside the exe zip carla.exe) comes from. I successfully compiled everything under MSYS2 /MINGW64 (with a couple of makefile changes) using:

make BUILDING_FOR_WINDOWS=true DEBUG=true

And get the following result:
![image](https://user-images.githubusercontent.com/13842596/46576482-e038bb00-ca0d-11e8-9f4c-2e4e91751158.png)

None of the targets seem to make Carla.exe unlike the linux build.

Thanks
Ben

**Comment by falkTX** [comment]
I dont have problems at all with developers building their own carla. I dont know where this notion comes from.
Carla is opensource, do with it what you want, that is entirely the point of it.
It is packaged in a few distros already, which is great :)

Regarding the official builds for windows, I use the stuff in https://github.com/falkTX/Carla/tree/master/data/windows
This assumes you have a working mingw and wine.

- `build-deps.sh` is the first step, it builds all dependencies in the home dir.

- then I manually run the things in `create-wineprefixes.sh`. the commented out stuff needs manual download, I did not figure out a way to automate the download and installation of those packages, but you can see the filename of them there, so you will know what is needed

- finally, `build-win-all.sh` is used which calls some other scripts in succession to build the actual carla binaries.

You will note that the `./data/` dir has a linux and macos dir, used in similar fashion.
I place the final, official build scripts there.

**Comment by bencrossman** [comment]
Hi

Yes you're right. The last time I looked at Carla code was a few years ago when this was the post I was using as a reference for building:
https://linuxmusicians.com/viewtopic.php?f=47&t=12812#p55203
I fully understand you meant reporting bugs on self compiled code rather than compiling code.

Thanks for the pointers to /data/windows, will check it out.

**Comment by bencrossman** [comment]
Ok I have my local 64 bit build running now.

Turns out all I needed to do is run:
"D:\msys64\mingw64\bin\python3.exe" source/frontend/carla

So I didn't have to worry about building the 32 bit parts I just copied the RC1 versions of:
carla-discovery-win32.exe
carla-bridge-win32.exe

Cheers
Ben
