### ISSUE TITLE
SF2/3: NO [FluidSynth missing or too old]

### ISSUE THREAD

**Issue by unhandyandy** [falkTX/Carla#775]
Hi again,
I'm able to run sf2 files using fluidsynth (1.1.6) and qsynth, but nevertheless I get this line

`SF2/3: NO [FluidSynth missing or too old]`

on running `make features`.  Does Carla have some additional requirement of fluidsynth, beyond just being able to read sf2 files?  Or will this feature be lacking even if it's only sf3 files that can't be read?

**Comment by falkTX** [comment]
You can force the build with `make HAVE_FLUIDSYNTH=true` but I cannot promise there won't be errors.
The version check is only there to ensure a version that I know works well, and handles sf2 and sf3 formats.

**Comment by unhandyandy** [comment]
OK, I'll give that a try, thanks.

**Comment by unhandyandy** [comment]
FYI:  I tried the forced build and I've successfully loaded an sf2 file.
