### ISSUE TITLE
VST load is broken

### ISSUE THREAD

**Issue by smrg-lm** [falkTX/Carla#781]
Hi, just updated carla-git I get this messages and vsts will not load:

carla-discovery::warning::Plugin 'Decimator' is not hard real-time capable - /usr/lib/ladspa/decimator_1202.so
carla-discovery::warning::Plugin 'Delayorama' is not hard real-time capable - /usr/lib/ladspa/delayorama_1402.so
carla-discovery::warning::Plugin 'Fractionally Addressed Delay Line' is not hard real-time capable - /usr/lib/ladspa/fad_delay_1192.so
carla-discovery::warning::Plugin 'GSM simulator' is not hard real-time capable - /usr/lib/ladspa/gsm_1215.so
carla-discovery::warning::Plugin 'Impulse convolver' is not hard real-time capable - /usr/lib/ladspa/imp_1199.so
carla-discovery::warning::Plugin 'Multivoice Chorus' is not hard real-time capable - /usr/lib/ladspa/multivoice_chorus_1201.so
carla-discovery::warning::Plugin 'Signal sifter' is not hard real-time capable - /usr/lib/ladspa/sifter_1210.so
carla-discovery::warning::Plugin 'Tape Delay Simulation' is not hard real-time capable - /usr/lib/ladspa/tape_delay_1211.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/carla-bridge-lv2.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_interposer-jack-x11.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_interposer-safe.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_interposer-x11.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_native-plugin.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_utils.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/jackbridge-wine32.dll
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/jackbridge-wine64.dll

[...]

Cannot read socket fd = 50 err = Success
CheckRes error
JackSocketClientChannel read fail
Cannot read socket fd = 48 err = No such file or directory
CheckRes error
Could not read result type = 1
Carla assertion failure: "jackPort != nullptr" in file CarlaEngineJack.cpp, line 581
Server is not running
Carla assertion failure: "jackPort != nullptr" in file CarlaEngineJack.cpp, line 581
Server is not running
Carla assertion failure: "jackPort != nullptr" in file CarlaEngineJack.cpp, line 581
Server is not running
Carla assertion failure: "jackPort != nullptr" in file CarlaEngineJack.cpp, line 581
Carla assertion failure: "pData->active" in file CarlaEngineClient.cpp, line 82
Carla assertion failure: "fJackClient != nullptr && ! isActive()" in file CarlaEngineJack.cpp, line 487

**Comment by smrg-lm** [comment]
Or it might be the jack package, just noticed this when updating the other machine:

Unpacking libjack-jackd2-dev:amd64 (2:1.9.12+git20181015~zz~bionic1) over (2:1.9.12-1~kxstudio1v5) ...
dpkg: libjack-jackd2-0:i386: dependency problems, but removing anyway as you requested:
 carla-bridge-wine32:i386 depends on libjack-jackd2-0 | libjack0.
 libasound2-plugins:i386 depends on libjack-jackd2-0 (>= 1.9.5~dfsg-14) | libjack-0.116.
 libasound2-plugins:i386 depends on libjack-jackd2-0 (>= 1.9.5~dfsg-14) | libjack-0.116.

(Reading database ... 318002 files and directories currently installed.)
Removing libjack-jackd2-0:i386 (2:1.9.12-1~kxstudio1v5) ...
dpkg: libjack-jackd2-0:amd64: dependency problems, but removing anyway as you requested:
 simplescreenrecorder depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 libmlt6 depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 carla-bridge-wine64 depends on libjack-jackd2-0 | libjack0; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack0 is not installed.
 libfluidsynth1:amd64 depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 linuxsampler depends on libjack-jackd2-0 (>= 1.9.5~dfsg-14) | libjack-0.116; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.116 is not installed.
  Package libjack-jackd2-0:amd64 which provides libjack-0.116 is to be removed.
 gstreamer1.0-plugins-good:amd64 depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 jackd2 depends on libjack-jackd2-0 (= 2:1.9.12-1~kxstudio1v5).
 a2jmidid depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 jack-keyboard depends on libjack-jackd2-0 | libjack0; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack0 is not installed.
 libjack-jackd2-dev:amd64 depends on libjack-jackd2-0 (= 2:1.9.12+git20181015~zz~bionic1).
 jack-capture depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 ladish depends on libjack-jackd2-0 (>= 1.9.5~dfsg-14) | libjack-0.116; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.116 is not installed.
  Package libjack-jackd2-0:amd64 which provides libjack-0.116 is to be removed.
 wineasio-amd64 depends on libjack-jackd2-0 | libjack0; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack0 is not installed.
 recordmydesktop depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 meterbridge depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 pulseaudio-module-jack depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 libasound2-plugins:amd64 depends on libjack-jackd2-0 (>= 1.9.5~dfsg-14) | libjack-0.116; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.116 is not installed.
  Package libjack-jackd2-0:amd64 which provides libjack-0.116 is to be removed.
 librtaudio6:amd64 depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 libportaudio2:amd64 depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 mpd depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 libavdevice57:amd64 depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 obs-studio depends on libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.125 is not installed.
 linuxsampler depends on libjack-jackd2-0 (>= 1.9.5~dfsg-14) | libjack-0.116; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.116 is not installed.
  Package libjack-jackd2-0:amd64 which provides libjack-0.116 is to be removed.
 ladish depends on libjack-jackd2-0 (>= 1.9.5~dfsg-14) | libjack-0.116; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.116 is not installed.
  Package libjack-jackd2-0:amd64 which provides libjack-0.116 is to be removed.
 libasound2-plugins:amd64 depends on libjack-jackd2-0 (>= 1.9.5~dfsg-14) | libjack-0.116; however:
  Package libjack-jackd2-0:amd64 is to be removed.
  Package libjack-0.116 is not installed.
  Package libjack-jackd2-0:amd64 which provides libjack-0.116 is to be removed.

Removing libjack-jackd2-0:amd64 (2:1.9.12-1~kxstudio1v5) ...

**Comment by falkTX** [comment]
Just restart jack after the update and all will be fine

**Comment by smrg-lm** [comment]
yep, sorry, it works so well that I never restart jack anymore :-D

**Comment by falkTX** [comment]
no worries, it is rare to have an update of jack that needs an update.
but it is for a good cause, we have meta-data api now working on jack2! :)
