### ISSUE TITLE
Errors trying to compile/package for Ubuntu

### ISSUE THREAD

**Issue by eeickmeyer** [falkTX/Carla#785]
Hi @falkTX ! Love the work you're doing here.

I'm the Council Chair for Ubuntu Studio, and since Patchage has ceased development, we decided that Carla would be a suitable replacement and I am currently working on getting it into Ubuntu's Universe repository. Not only would Carla's patchbay feature be a great replacement, but the extra bonus of having a plugin host "rack" means we could, in theory, replace other software such as Jack Rack.

Anyhow, when trying to compile the bridge plugins, especially the WINE plugins, I keep running into the same error and was wondering if you could help me out. Considering the goal is now to get Carla into Universe by the next release (DD, to become 19.04), I've been getting proative on this front.

Here's the issue I keep running into, and I think it might be a difference in mingw versions between what you used to develop and what Ubuntu (18.10, in this case) has included:

```
Linking carla-bridge-win32.exe
/usr/bin/i686-w64-mingw32-ld: unrecognized option '-z'
/usr/bin/i686-w64-mingw32-ld: use the --help option for usage information
```
Any chance you can help shed a light on this?

Thanks in advance,
Erich
(Eickmeyer in Freenode, I'm lurking in your #kxstudio channel currently)

**Comment by eeickmeyer** [comment]
I'm able to get the base fully functional, so I've got that going for me, which is nice. :) The errors come when I try to get the bridges to compile. 

Here's the entire logfile from Launchpad, which includes the output from `make features`:
https://launchpadlibrarian.net/394362115/buildlog_ubuntu-cosmic-amd64.carla_2.0-0~201810220313~ubuntu18.10.1_BUILDING.txt.gz

Here's the /debian directory, and I have the feeling I'm doing something wrong in the rules and/or control file:
https://git.launchpad.net/carla/tree/debian

Let me know if I'm missing a dependency, or if I've just got this completely wrong. I borrowed some items in the /debian directory from your KXStudio repo hoping that would be a good starting point.

Right now I'm using your github repo, adding the /debian directory, and pushing to Launchpad, so this is all based on the latest code. Once that's dialed-in, my plan is to redo the packaging using the /debian directory I created and do it the clean "debian" way. This is just to get it to build and package, a "rough draft" if you will.

Thank you so much for your help!

**Comment by WasIstDasDingDa** [comment]
Hi @falkTX, thanks for your miracle machine named Carla. I had problems when building the Wine bridges too, base is fully functional (also POSIX32 Bridge and Windows executables standalone under Wine). Everything is ok when building up to recompiling Windows code. WineGCC breaks then off immediately with the error message:

In file included from ../utils/CarlaUtils.hpp:26,
                 from ../utils/CarlaLibUtils.hpp:21,
                 from JackBridge1.cpp:32:
/usr/include/c++/8/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
winegcc: gcc failed
make[1]: *** [Makefile:210: ../../build/jackbridge/Release/JackBridge1.cpp.wine32.o] Error 2
make: *** [Makefile:215: wine32] Error 2

At wine64 the same, cstdlib.h and stdlib.h are in the same directory both. For other projects there are reports for this specific error in the net, but I do not have enough knowledge to solve the problem myself. Im running openSUSE Tumbleweed, the toolchain is very recent, GCC (with WineGCC) is version 8.2.1, MinGW 8.2.0 - maybe that's the cause.
Can you help?

**Comment by falkTX** [comment]
No idea about RPM based distros, I guess wine-dev thing missing..

@eeickmeyer carla is getting stable release very soon, I will be taking a look at this, making the initial debian package structure.

**Comment by falkTX** [comment]
easier than I thought.. pushed the contents into a new `debian` branch
Feel free to take everything
https://github.com/falkTX/Carla/tree/debian/debian

**Comment by eeickmeyer** [comment]
Looking forward to the stable release!
However, I did just run into a build error using the directory in your debian branch. Seems as though it can't find winegcc.

https://launchpadlibrarian.net/409890820/buildlog_ubuntu-disco-amd64.carla_2.0.0~rc3-0~201902052233~ubuntu19.04.1_BUILDING.txt.gz

**Comment by eeickmeyer** [comment]
Uncommenting the PATH variable in the rules file was enough to fix the winegcc error, but there's something else going on that's quite a bit over my head. Not sure what this is.

https://launchpadlibrarian.net/409896271/buildlog_ubuntu-disco-amd64.carla_2.0.0~rc3-0~201902052315~ubuntu19.04.1_BUILDING.txt.gz
