### ISSUE TITLE
Make Cadence respect the path of the system or add cpu affinity to jackd

### ISSUE THREAD

**Issue by christianwn** [falkTX/Carla#788]
I want to wrap jackdbus so that I use: taskset -c 7 jackdbus. Doing this by making a bash script with the same name in /usr/local/bin. It seams that Cadence is coded without respecting the system path priority. Normally /usr/local/bin is first then comes /usr/bin.

But ideally we need an option in Cadence for cpu affinity. The reason for this is cpu core isolation on rt kernels. You don't want to run jackdbus on the non isolated cores, this is the default behaviour, to follow the system affinity. In my tests, putting jackdbus on an isolated core results in about 5% more dsp power on my system!

Best regards
Christian W. Nyman

**Comment by trebmuh** [comment]
@christianwn : shouldn't that issue be on https://github.com/falkTX/Cadence instead of https://github.com/falkTX/Carla ?

**Comment by christianwn** [comment]
Moved to: [https://github.com/falkTX/Cadence/issues/235](url)
