### ISSUE TITLE
Harrison Mixbus LV2 plugis don't show their GUi

### ISSUE THREAD

**Issue by codecollider** [falkTX/Carla#793]
In the latest CARLA version the Mixbus plugins don't show their GUI and a buzz occurs when trying to open the GUI. 

Carla 2.0 RC2

**Comment by falkTX** [comment]
I cannot reproduce this issue.
If it possible for you to update the mixbus plugins? if not, try to see which exact version of them you have so I can ask the developer for the same build.

**Comment by codecollider** [comment]
Problem still occurs with:

Using Carla version 1.9.13 (2.0-RC3)
  Python version: 3.5.3
  Qt version:     5.7.1
  PyQt version:   5.7
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources

**Comment by falkTX** [comment]
This is a tricky one, can no longer reproduce reliably but happens randomly :(
Will leave it for v2.1

**Comment by codecollider** [comment]
ok, for me it's not working at all :)

**Comment by falkTX** [comment]
This was fixed in 2.2, x11 child window not always valid, issue is actually duplicate of a few others ones.
