### ISSUE TITLE
MIDI-Clock / Timecode not properly sent to/received from Plugin

### ISSUE THREAD

**Issue by JanFeld** [falkTX/Carla#795]
Hi,

when i've time signature changes in my projects (DAW, Reaper and Ardour) from let's say 4/4 to 6/8 they aren't received properly by Superior Drummer 3.

While in 4/4 parts it's working well without any problems when i've programmed my drums inside Superior Drummer 3. When i'm switching the DAW-Time-Signature within the project to 6/8 then i can see and hear jumps in Superior Drummer 3 between bars. 

# A quick example:

## Bars 1 to 4 = 4/4:
**1** 2 3 4 - **2** 2 3 4 - **3** 2 3 4 - **4** 2 3 4 

## Bars 5 to 8 = 6/8:
**5** 2 3 4 5 6 - **6** 2 3 4 5 6 - **7** 2 3 4 5 6 - **8** 2 3 4 5 6

## What should be:
**1** 2 3 4 - **2** 2 3 4 - **3** 2 3 4 - **4** 2 3 4 - **5** 2 3 4 5 6 - **6** 2 3 4 5 6 - **7** 2 3 4 5 6 - **8** 2 3 4 5 6

## What actually happens in Superior Drummer 3:
**1** 2 3 4 - **2** 2 3 4 - **3** 2 3 4 - **4** 2 3 4 - **5** 2 3 - **6** 2 3 4 5 6 - **7** 2 3 - **8** 2 3 4 5 6 - **9** ...

Sometimes it misses a whole bar. Then it's jumping from 5 to 7 for example.

I think this is due to some issues with the MIDI Clock signal and/or MIDI Timecode synchronization. 

It doesn't make any difference if i switch the Tempomap of Superior Drummer 3 to 6/8 as well or if i leave it as it was. 

When switching to 3/4 instead of 6/8 it's sounding normal and seems to work but it makes a mess of the rest of the project.

If i'm programming the drums directly in the DAW it's working as well. But i think this does not relate to superior drummer 3 only but to other timecode/timesignature dependet plugins or effects like delays, chorus, and so on.

### My Setup:
* Arch Linux 4.19.2
* Ardour 5.12
* Reaper v5.961 (Linux Build)
* Carla 1.9.12 (2.0-RC2)

Thanks for your answer in advance!

**Comment by falkTX** [comment]
I do not think this is related to time code, just carla not passing some time information correctly to the plugin.
Try without MIDI sync, just set ardour to use a non 4/4 signature, and let me know if the issue still happens.
Thanks.

**Comment by IanOField** [comment]
Ho do i disable the MIDI-Sync? Can it be disabled in the DAW or in the settings?

**Comment by IanOField** [comment]
I've tried with an project purely set up with 6/8 signature as well in Ardour as in Reaper and got the same effects. SD3 jumping back and forward. 

I've played around with various midi-settings as well as running carla-standalone using jack_midi_clock as connection between ardour and carla. Same effects but carla's transport tab shows the correct position and values. Just SD3 doesn't get the right ones.

**Comment by JanFeld** [comment]
Is still more info needed? If yes, which kind of information?

**Comment by falkTX** [comment]
No more info needed, I can reproduce the issue.
Will be fixed before 2.0 is considered final. But I am not sure if I have time for it in the short-term right now.
Everything in 2.0-final milestone will be handled, hopefully not taking too long..
