### ISSUE TITLE
"cx_Freeze: Python error in main script" Windows 10 64bits

### ISSUE THREAD

**Issue by iosca** [falkTX/Carla#797]
I format my pc today, and when I tried to open carla I get this message. before formatting carla worked fine. What is going on?

![image](https://user-images.githubusercontent.com/45272475/48920822-61df8d80-ee82-11e8-9daa-03a71ce150b5.png)

**Comment by iosca** [comment]
Thanks for the help, I just realized that I formatted my pc and just installed the vcredist. I feel like an idiot for opening the thread.

**Comment by falkTX** [comment]
no problem, we always forget things.
but it is unclear, do you have carla working now?

**Comment by iosca** [comment]
yeah, working 100%

**Comment by falkTX** [comment]
alright, thanks for confirming. I will close the ticket then.
