### ISSUE TITLE
JACK outputs are not automatically connected to playback

### ISSUE THREAD

**Issue by myfreeweb** [falkTX/Carla#798]
I was wondering why there was no sound (meters in Carla were working, but I didn't hear anything) — turns out I had to connect the outputs to system playback inputs with e.g. `qjackctl`:

![jack-not-conn.png](https://user-images.githubusercontent.com/208340/48954255-c883aa80-ef59-11e8-8ba4-ddfe0ceb9355.png)

Would be much better if Carla could directly connect to the JACK system playback thing..

**Comment by falkTX** [comment]
There is an option to auto-connect to system outputs, in engine, audio driver extra options via the "..." button.
Requires >= 2.0-RC1 version.
It is disabled by default, as quite a large number of users do not want this.
