### ISSUE TITLE
Windows Vsts Don't Always Load in Carla

### ISSUE THREAD

**Issue by brandflake11** [falkTX/Carla#802]
Hey falkTX,

Whenever I load a project with Carla, whether they are Carla Project Files, Reaper files with Carla being used as a plugin, or Renoise files with Carla being used, Windows Vsts that I use don't always load/substantiate with the project load. When I load the project again however, most of the times Carla will then load the plugins, this is not terribly consistent though. Is there a way to make sure Carla loads these plugins in the first time, regardless of how much time it takes? Is there a timeout function that I can turn off to make sure these plugins load every single time, or even a new version of Carla that fixes this that I am unaware of?

I am rocking Ubuntu Studio 16.04 with Kxstudio installed and using Carla 1.9.12 (2.0-RC2) with Winert from Kxstudio with a 64-bit prefix. 

(Also, I love everything that you're doing, please, please, PLEASE don't stop!)

**Comment by falkTX** [comment]
There is a time out yes, but it is large enough that I did not think it would be a problem.
It waits 10 seconds for windows bridges to start, 20 seconds if it is the first time loading such bridge (to give time for wine to "boot")

There is no option to configure this yet.
If you are okay with building carla yourself, I can tell you which lines to modify...

**Comment by brandflake11** [comment]
Thanks falkTX. I guess this should be a feature request then, but I would love to be able to turn the time out off then. What lines are they?

**Comment by falkTX** [comment]
I will do a custom build with timeouts disabled next week for you to test, seems easier that way.

**Comment by falkTX** [comment]
I forgot sorry.
Assuming you have a 64bit OS, here are some debs for you:
https://launchpad.net/~kxstudio-debian/+archive/ubuntu/testing/+files/carla-git_1.9.12+git20181225v5+test-no-timeout1_amd64.deb
https://launchpad.net/~kxstudio-debian/+archive/ubuntu/testing/+files/carla-lv2_1.9.12+git20181225v5+test-no-timeout1_amd64.deb
https://launchpad.net/~kxstudio-debian/+archive/ubuntu/testing/+files/carla-vst_1.9.12+git20181225v5+test-no-timeout1_amd64.deb
https://launchpad.net/~kxstudio-debian/+archive/ubuntu/testing/+files/carla-data_1.9.12+git20181225v5+test-no-timeout1_all.deb

Let me know how that works for you

**Comment by falkTX** [comment]
(make sure to install all of them)

**Comment by brandflake11** [comment]
After installing these .debs and doing a whole bunch of tests that would normally result in Carla failing to load windows plugins on first launch of both standalone carla and carla used inside DAW projects, this disabling of the timeout has fixed the problem, which is awesome! I will continue to test and use this version of carla though, as I only tested this for about an hour and I will post if the error happens. One thing that did happen was this:
 `======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  44100.0
  Process mode: Continuous Rack
Using WINEPREFIX '/home/brandon/.wine', with base RT prio 15 and server RT prio 10
Starting plugin bridge, command is:
/usr/lib/carla/carla-bridge-win64.exe "VST2" "/home/brandon/WinVST/Reaktor5 FX.dll" "Reaktor5" 1314010470

CarlaThread with realtime priority successful

CarlaRingBuffer::tryWrite(0x7ffde2d7b7b4, 4): failed, not enough space
carla_vst_hostCanDo("asyncProcessing") - unknown feature

carla_vst_hostCanDo("editFile") - unknown feature

Carla Bridge Ready!

Trying to get window...
Trying to get window...
Match found using pid, simple and UTF-8 name all at once, nice!
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"`

I don't know what `CarlaRingBuffer::tryWrite(0x7ffde2d7b7b4, 4): failed, not enough space` is, as I'm not sure if I've seen it before, but this did appear when the windows plugins would normally fail, which is when my computer boots and carla starts and tries to load a windows plugin for the first time, so I don't know if it is related but I thought I would share this anyway. This error also did not appear when loading any other windows plugins afterwords, it only happened on the first time loading a windows plugin on boot. Could this be related?

**Comment by brandflake11** [comment]
Okay, after doing lots of playing around with Windows vsts on linux and using them in a project I am working on, I'm happy to report that they always load now that the timeout option is disabled! This build that you sent me is absolutely awesome! I am so less stressed than I was before!

**Comment by ormf** [comment]
Hi,
I'm on arch linux and have the same problem with many Windows VST plugins. The timeout error is signaled in less than 2 seconds after trying to add the plugin. This is much shorter than those plugins load in lmms, where they work. Maybe this is a version clash in the arch packages (in that case: Sorry for the noise but it'd be great if you could clear that up)

The arch packages used are: carla-git and carla-bridges-window 

carla-bridges-window ist labeled:
carla-bridges-win-2.0beta5.1-1-x86_64.pkg.tar.xz

carla --version gives:
Using Carla version 1.9.13 (2.0-RC3)
  Python version: 3.7.2
  Qt version:     5.12.0
  PyQt version:   5.11.3
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources

In case it is not a version clash: Is there a way to get a carla version without timeout compilable on my system? (you don't have to provide the binaries, a git branch or info where to patch the sources would suffice).

**Comment by falkTX** [comment]
Latest git (develop branch) has an infinite timeout now.
Instead of strict timeout, a window appears with a button that is clickable by the user, which will cancel the wait.
This applies to loading projects, loading bridged plugins and loading jack applications.
So I consider this issue fixed.
