### ISSUE TITLE
Carla only compiles on x86_64 and i686 architecture

### ISSUE THREAD

**Issue by martinkg** [falkTX/Carla#805]
Hi,

the Carla build breaks on different platforms with this error messages:

`ppc64le:
cc: error: unrecognized argument in option '-mtune=generic'

ppc64:
g++: error: unrecognized argument in option '-mtune=generic'
g++: note: valid arguments to '-mtune=' are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power3 power4 power5 power5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan

s390x:
BUILDSTDERR: g++: error: unrecognized argument in option '-mtune=generic'
BUILDSTDERR: g++: note: valid arguments to '-mtune=' are: arch10 arch11 arch12 arch3 arch5 arch6 arch7 arch8 arch9 g5 g6 native z10 z13 z14 z196 z9-109 z9-ec z900 z990 zEC12

armv7hl:
cc1: error: unrecognized command line option '-msse'
cc1: error: unrecognized command line option '-msse2'
cc1: error: unrecognized command line option '-mfpmath=sse'

aarch64:
cc1plus: error: unrecognized command line option '-msse'
cc1plus: error: unrecognized command line option '-msse2'
cc1plus: error: unrecognized command line option '-mfpmath=sse'`

I' am working on Fedora 29, with the following patch and sed command it compiles on all platforms.

remove upstream optimisation options with sed command:
```
sed -i "s|-O3 -mtune=generic -msse -msse2 -mfpmath=sse||" data/linux/build-deps.sh
sed -i "s|-O3 -ffast-math -mtune=generic -msse -msse2 -mfpmath=sse||" source/{tests/Makefile,Makefile.mk}
```
Carla-bswap.patch:
```
--- a/source/modules/water/memory/ByteOrder.h	2018-12-21 11:41:10.199136525 +0000
+++ b/source/modules/water/memory/ByteOrder.h	2018-12-21 11:42:29.498743747 +0000
@@ -153,7 +153,7 @@
 {^M
    #ifdef CARLA_OS_MAC^M
     return OSSwapInt32 (n);^M
-   #elif defined(CARLA_OS_WIN) || ! (defined (__arm__) || defined (__arm64__) || defined (__aarch64__))^M
+   #elif defined(CARLA_OS_WIN) || defined(__i386__) || defined(__x86_64__)^M
     asm("bswap %%eax" : "=a"(n) : "a"(n));^M
     return n;^M
    #else^M
```

**Comment by falkTX** [comment]
No need to patch makefile, just use `make NOOPT=true` and pass your own optimization flags via environment.
What architecture are you trying to build for? ppc?

**Comment by martinkg** [comment]
I create rpm packages on the Fedora Build Server for Fedora 30 (rawhide), 29 and 28.
The results can be seen here:

[F30 Builds](https://koji.fedoraproject.org/koji/taskinfo?taskID=31555422)
[F29 Builds](https://koji.fedoraproject.org/koji/taskinfo?taskID=31555424)
[F28 Builds](https://koji.fedoraproject.org/koji/taskinfo?taskID=31555426)

**Comment by martinkg** [comment]
with the proposed option `make NOOPT=true` Carla compiles
on x86_64, aarch64, i686 and armv7hl [Buld result](https://koji.fedoraproject.org/koji/taskinfo?taskID=31557060) but not on ppc64le and s390x.

**Comment by martinkg** [comment]
Thanks for fixing this.
The dev brach builds now with this options:
`+ /usr/bin/make -O -j2 SKIP_STRIPPING=true NOOPT=true V=1`
see [Build log](https://koji.fedoraproject.org/koji/taskinfo?taskID=31647520)

**Comment by falkTX** [comment]
Cool, thanks for confirming.
Feel free to cherry-pick the patch to get it against the (upcoming) stable release.
I won't put it on the master branch just yet, need to see if it builds on BSD first.

@yurivict Can you check? I mean, if the develop branch still builds fine for you or not.
