### ISSUE TITLE
[Feature Request] GUI (re)size when used as a plugin

### ISSUE THREAD

**Issue by kickore** [falkTX/Carla#808]
Hi.

This is mostly a feature request for the ability to resize the plugin GUI. I've been reading around, though, and it seems this is a complicated subject.

If there is no easy way to do this, where would one specify the size of the plugin GUI for Carla before building from source?

Just to clarify, this is not in regards to the size of an external third party plugin. This is just for the Carla GUI.

Thanks!

Edit: In the event it matters, I'm building on linux. Arch, specifically.

**Comment by falkTX** [comment]
please build from the develop branch, the carla plugin ui will be fully resizable there, as the UI is now always "external" to the host and not embed anymore.
embedding external applications like carla frontend is too hacky, so in version 2.1 the UI is always external.

**Comment by kickore** [comment]
Done.
Works for me!

Thanks!
