### ISSUE TITLE
Carla in NixOS

### ISSUE THREAD

**Issue by suhr** [falkTX/Carla#813]
[NixOS](https://nixos.org/) is a linux disro based on pure functional package manager Nix. Unlike other package managers, Nix stores all artifacts in paths like `/nix/store/5rnfzla9kcx4mj5zdc7nlnv8na1najvg-firefox-3.5.4`. This allows to avoid dependency hell and to have various nice things (rollbacks, reproducible builds, etc).

I created the following derivation for Carla: https://gist.github.com/suhr/912c714c9ac73ccfc0d52303e1caeb7c

The standalone version of Carla works great. But when I try to use Carla as a VST in Helio, the Carla window is black. And this is printed to the terminal:

```
Trying to start carla-plugin using "/home/suhr/.vst/carla.vst/resources/carla-plugin-patchbay"
LRDF Support not available (LADSPA-RDF will be disabled)
Could not initialize GLX
waitForClientFirstMessage() - read returned 0
```

Additional info: `$HOME/.vst` is a symlink to `$HOME/.nix-profile/lib/vst`.

**Comment by suhr** [comment]
PS: you may find this interesting:

- https://discourse.nixos.org/t/nixos-and-linux-pro-audio/1788/10
- https://github.com/helio-fm/helio-workstation/issues/102

**Comment by falkTX** [comment]
The VST UI uses openGL for graphics, but it only displays a static image for now.

> Could not initialize GLX

This tells me required OpenGL setup failed for the window, so it cannot draw contents.
Clicking inside the window should still make the full carla UI appear though.

There is nothing I can think regarding carla on how to fix this, seems like a problem in your setup instead.
Note that the LV2 version will not have such an issue, since it opens the external (full) carla UI directly.

**Comment by suhr** [comment]
> Clicking inside the window should still make the full carla UI appear though.

It doesn't, unfortunately.

**Comment by suhr** [comment]
This is the stderr with `LD_DEBUG=libs`: https://gist.github.com/suhr/68f8cf0259a9ef9295bd248ae9481cba

It look like Carla VST completely ignores `LD_LIBRARY_PATH`. But why?

**Comment by luzpaz** [comment]
soft bumping this. It would be great to have this available in NixOS

**Comment by falkTX** [comment]
can you tell me which env vars are required for nixos stuff to work?
carla modifies a few, in order to get python-ui to work. this likely is the culprit things dont work well.

also, please try develop branch of carla to see if it behaves any better

**Comment by suhr** [comment]
The develop version fails to build:

```
# Create directories
install -d /nix/store/n8yyv7ahfg8k6lp3bhh4vckdfjw28dpj-carla-2.0.0/bin
install -d /nix/store/n8yyv7ahfg8k6lp3bhh4vckdfjw28dpj-carla-2.0.0/lib/carla/jack
install -d /nix/store/n8yyv7ahfg8k6lp3bhh4vckdfjw28dpj-carla-2.0.0/lib/pkgconfig
install -d /nix/store/n8yyv7ahfg8k6lp3bhh4vckdfjw28dpj-carla-2.0.0/include/carla/includes
install -d /nix/store/x5agg0ivf2jhqgs3bf0k12x64zyyiqac-jack2-1.9.12/lib/jack
install: cannot change permissions of '/nix/store/x5agg0ivf2jhqgs3bf0k12x64zyyiqac-jack2-1.9.12/lib/jack': Operation not permitted
make: *** [Makefile:391: install_main] Error 1
builder for '/nix/store/pv7vl5g80gpfignrnbhspvpwa5ws2c95-carla-2.0.0.drv' failed with exit code 2
```

**Comment by falkTX** [comment]
Just fixed that, please try again

**Comment by suhr** [comment]
Now it builds just fine. There's `ModuleNotFoundError: No module named 'PyQt5'` error which is a bug in the nixpkgs package for carla rather than the problem with GLX I had with my own package.

I need to fix this before I know whether there's still an issue with GLX.

**Comment by suhr** [comment]
With [this PR](https://github.com/NixOS/nixpkgs/pull/68795) in nixpkgs, Carla plugins work fine. And I can confirm that it also works with the `develop` version of Carla.

 The only remaining issue is, `Carla-Patchbay` provides the rack interface instead of the patchbay interface.
