### ISSUE TITLE
Carla cannot pick up my mic

### ISSUE THREAD

**Issue by MrTeeXD** [falkTX/Carla#817]
Hello, i have a huge problem with Carla where it cannot pick up my mic for some reason, it worked before but now Carla doesnt pick up my mic anymore, can anyone help me with this situation?

**Comment by falkTX** [comment]
I do not know how that would be possible.

You can download previous versions of carla, to see if any of them works.
See https://github.com/falkTX/Carla/releases

**Comment by falkTX** [comment]
That is another issue. please confirm for what I asked first

**Comment by MisterTeeXD** [comment]
Yes, i have and now it works again

**Comment by falkTX** [comment]
sorry for late reply, I did not notice your answer.
to be honest, I do not really understand the issue here.
I thought a previous version of carla was working for you, but a new one is not.
But now seems to be related to the driver you select..?

Can you try to explain the issue in as much detail as possible please?

**Comment by MisterTeeXD** [comment]
Oh, my apologies. Alright, so, Carla uses only one driver which is the speaker of the PC, what i was wondering is how does Carla pick up my mic, when the driver is selected to "Default Driver", Carla can pick up my Mic, showing a input node in the patchbay, when switched to The "Speakers (Realtek High Definition Audio" driver, Carla fails to pick up my mic, even though my sound is played back through the connected speakers, namely the Realtek HD Audio driver, i wonder if this is a bug in Carla

**Comment by Keith-Cancel** [comment]
I can confirm this on windows. If I set device to anything but default I can long have mic input.
Here is a video showing what I am I ran into: https://youtu.be/gTZjSy8_nqo

It might be wise to have options to select both input and output device in the interface.

**Comment by mandark321** [comment]
> I can confirm this on windows. If I set device to anything but default I can long have mic input.
> Here is a video showing what I am I ran into: https://youtu.be/gTZjSy8_nqo
> 
> It might be wise to have options to select both input and output device in the interface.

Can confirm this as well, had the same issue happen when trying to select a specific input vs using default device.

**Comment by ibex-are-goats** [comment]
This happens to me too, I just have no audio input or output device in Windows and I can't decide if Carla is too complicated for me to figure out, or if it's actually a bug and stuff is missing.
