### ISSUE TITLE
Use Carla as VST on Windows?

### ISSUE THREAD

**Issue by ttay24** [falkTX/Carla#819]
I'm on Windows 10, and I can't seem to load Carla as a VST in my DAW (I'm using Reaper). I've downloaded the Windows binaries from the main site, and added that folder to my path for VSTs, but Reaper can't find it. Is there something else I need to do? I've seen people say they're able to do this, but they're on Linux...

Thanks!

**Comment by falkTX** [comment]
Carla as VST for Windows was not implemented for the 2.0 stable series.
I implemented it already for the next 2.1 release series, but want to fix 2.0 bugs first before jumping to 2.1.

I can provide an early build if you want to do some testing and check out how it runs.

**Comment by ttay24** [comment]
Ah ok, that makes sense! Yeah I would love to if you could point me to the build


________________________________

**Comment by falkTX** [comment]
I have to make one, give me a few days and I will get back to you

**Comment by ttay24** [comment]
Awesome, thanks man!

**Comment by falkTX** [comment]
I implemented the packaging of Windows VST plugin for new builds (2.1 series).
Here's a test release: https://github.com/falkTX/Carla/releases/download/v2.1-alpha1-winvst/Carla_2.0-alpha1-win64.zip
