### ISSUE TITLE
Jack and JackRouter don't work on Carla in Win10 

### ISSUE THREAD

**Issue by alfonso73** [falkTX/Carla#820]
This issue 

https://github.com/falkTX/Carla/issues/130

is back on Windows 10 64x. Everything works on Windows 7 but not on Windows 10.
Jack does not work on Win10 64x in Carla. Even JackRouter is not present in the ASIO list.
Could it be the same cause of the SuperCollider server not booting on Win10 64x when Jack is installed?
Other software like Ableton Live and Reaper are working with Jack and JackRouter.

**Comment by alfonso73** [comment]
Thanks. Now perfectly working with a combo of Carla, Ableton Live and Pure
Data! Paradise!
As for SuperCollider...do you have an idea?
Do you think that the fix you did to Carla to see JackRouter coudl be
usfeul to fix the SuperCollider bug about SC Server not booting if Jack 64
is installed on Win10 64?

thanks!

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by falkTX** [comment]
It seems RtAudio usage of ASIO devices is not great.
Some weird quirk is likely needed. Someone else will have to look into it...

**Comment by falkTX** [comment]
forgot to close this issue that is fixed now..
regarding the question, sorry for late answer, but there is nothing that useful I can say.
the windows builds switched from rtaudio to juce, a whole different audio stack.

**Comment by alfonso73** [comment]
Thanks Felipe.
all the best and stay safe!

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone
