### ISSUE TITLE
Guitarix as carla plugin, "Failed to load plugin"

### ISSUE THREAD

**Issue by donlombardo** [falkTX/Carla#828]
I have done all the steps:
I've installed guitarix (no problems)
I've installed Carla
I've made the experimental settings changes
I've added the Carla vst to Reaper

BUT! I'm getting an error when I'm trying to add guitarix to Carla: "Failed to load plugin. Invalid or unsupported plugin type". I've followed all the tutorials and instructions in this https://linuxmusicians.com/viewtopic.php?f=48&t=18280&start=30, every correct box is ticked, but still getting the message. WHAT AM I DOING WRONG? It's driving me insane.

**Comment by terencode** [comment]
I can run the plugin without any problem. Please specify your distro, Carla version, see if you can gather up any other useful info.

**Comment by donlombardo** [comment]
Could I be missing some repositories?

From apt-cache policy carla:
carla:
  Installerad: (ingen)
  Kandidat:    2:1.2.4-1kxstudio2
  Versionstabell:
     2:1.2.4-1kxstudio2 500
        500 http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu lucid/main i386 Packages

Xubuntu Ubuntu 17.10 4.13.0-46-generic #51-Ubuntu SMP  i686 i686 i686 GNU/Linux

**Comment by terencode** [comment]
It might have to do with the fact you have a 32-bit computer and the guitarix plugin is only made for 64-bit.

**Comment by falkTX** [comment]
You need carla-git if installing carla from the kxstudio repos.
There is no "add jack application" button on the old carla anyway.

I do not understand how you can be seemingly running the new frontend with and old backend...

**Comment by donlombardo** [comment]
Ok, so i tried with running carla with sudo, and i could add guitarix. But there's no sound and when i add it in reaper it just Plugin failed to initialize....

**Comment by falkTX** [comment]
wtf are you doing?
please do not run gui applications as root!!!
now everytime you run carla as regular user, it will fail to write its config files (so no more plugin scanning updates, among other things)

I will not support such use case.
