### ISSUE TITLE
Carla - Add New: grid height doesn't scale well for 2 lines entries

### ISSUE THREAD

**Issue by terencode** [falkTX/Carla#838]
If you adjust the grid size to be less than the width needed to display in one line a string, it will change to display it on 2 lines but the top and the bottom are cut:

![image](https://user-images.githubusercontent.com/12665563/52902226-6cee5380-320e-11e9-9110-d5497c69e678.png)

**Comment by falkTX** [comment]
does not happen here.
do you have the option to use the "PRO" theme switched off in the settings?

![image](https://user-images.githubusercontent.com/1334853/52919430-ac966780-3302-11e9-94b4-33e7fc38cdc3.png)

**Comment by terencode** [comment]
Nope, it's ON but changes any of the themes settings didn't do anything.

**Comment by falkTX** [comment]
hmm your picture looks scaled, are you using your desktop with scaling?

**Comment by terencode** [comment]
Nope, here is the full screen:
![image](https://user-images.githubusercontent.com/12665563/53300420-4bf9b400-3847-11e9-80de-dfa7c674baaf.png)

**Comment by falkTX** [comment]
if you compare your screenshot to mine, at least your font size looks much bigger than mine.
what system/distro are you using again?

**Comment by terencode** [comment]
ArchLinux with Gnome DE 3.30, font-size is 11.

**Comment by eeickmeyer** [comment]
Gnome 3.30 hasn't even been finalized/released yet, so the bugs could be coming from there. There are lots of bug fixes, and 3.30 is very much still work-in-progress, and is not expected to release until March 13th. As such, it could be related to that.

I also could not reproduce this bug in Ubuntu Disco with GNOME 3.30 (prerelease).

**Comment by terencode** [comment]
@eeickmeyer thanks for trying to help but you're mistaken : gnome 3.30 is stable. It's gnome 3.32 you are talking about.

**Comment by eeickmeyer** [comment]
@terencode Oh, yes, sorry. I got my releases mixed-up. Either way, I was not able to reproduce.
