### ISSUE TITLE
MIDI CC automation assertion failure

### ISSUE THREAD

**Issue by terencode** [falkTX/Carla#841]
The following is spammed when you set up a midi CC automation on any parameter:
``Carla assertion failure: "fIsProcessing" in file CarlaPluginVST2.cpp, line 1833``

 ---
ArchLinux
Carla 1:2.1.alpha1.winvst.r39.g3006738b-1

**Comment by falkTX** [comment]
The comment I left on some other bug was meant to be for this one...

which plugin triggers this?
I guess it will be one of those that has built-in "midi learn". But I do not know many that still do this...

**Comment by falkTX** [comment]
ping

**Comment by terencode** [comment]
I think it was pianoteq but I can't retest because of https://github.com/falkTX/Carla/issues/932

**Comment by terencode** [comment]
Cannot reproduce anymore. Will reopen in case it happens again.
