### ISSUE TITLE
MIDI CC automation not working on LV2

### ISSUE THREAD

**Issue by terencode** [falkTX/Carla#842]
Although the LV2 plugins seems to receive MIDI CC events as well as MIDI NoteOn/Off message, the red indicator on the right of the rack doesn't light up.
Moreover, when you try to setup a MIDI CC automation on one of the parameter, nothing happens.

---
Archlinux
Carla 1:2.1.alpha1.winvst.r39.g3006738b-1

**Comment by falkTX** [comment]
which plugin triggers this?
I guess it will be one of those that has built-in "midi learn". But I do not know many that still do this...

**Comment by terencode** [comment]
This happens on all LV2.

**Comment by Gerbmouse** [comment]
Is 9712dc1 really closing the bug? - At least I was not able to have any automation of lv2 plugins (see e.g.: https://github.com/falkTX/Carla/issues/1406)

**Comment by agaricus-campestris** [comment]
> Is [9712dc1](https://github.com/falkTX/Carla/commit/9712dc1e256f4d099a1aee2fd2e454d645f5bc97) really closing the bug? - At least I was not able to have any automation of lv2 plugins (see e.g.: [#1406](https://github.com/falkTX/Carla/issues/1406))

I actually have the same problem but I may be a super noob ^_^, see here what I wrote about it :
https://github.com/falkTX/Carla/issues/1406
