### ISSUE TITLE
Save a2j MIDI bridge status when using Non Session Manager

### ISSUE THREAD

**Issue by miquecg** [falkTX/Carla#843]
I'm using Non Session Manager together with Carla and a2j bridge status is not saved. Every time I have to start the bridge myself manually so I'm wondering if it would be reasonable to have this. Maybe it's out of the scope to save this kind of "server" settings in Carla so I'm asking.

For the moment I've tried `nsm-proxy` client and it works. I can make it execute `a2j_control` command except for a minor issue, the client dies after the call but the bridge remains open.

**Comment by falkTX** [comment]
This is completely out of scope for Carla.

What you actually want to do is start the daemon manually.
Just run `a2jmidid -e` which does what you want and does not launch a daemon but runs as normal.
(a2jmidid is the thing that a2j actually starts)

**Comment by miquecg** [comment]
Thanks for the tip. Running the daemon directly within `nsm-proxy` does the trick.
