### ISSUE TITLE
Loading sample in samplv2 crashes Carla

### ISSUE THREAD

**Issue by martinsolberg** [falkTX/Carla#847]
After adding the samplv2 plugin to Carla, it crashes when trying to load a sample in the plugin. Loading samples (and playing them back) on samplv2 is working on other LV2 hosts on my system (Qtractor).

Using Carla version 2.0.90 (2.1-alpha1)
  Python version: 3.7.2
  Qt version:     5.11.3
  PyQt version:   5.11.3
  Binary dir:     /usr/local/lib/carla
  Resources dir:  /usr/local/share/carla/resources

[carla_dump_samplv2.txt](https://github.com/falkTX/Carla/files/2902586/carla_dump_samplv2.txt)

**Comment by falkTX** [comment]
I wonder if this is mixing different qt versions somehow.
crash does not seem to be relevant to carla, at least from the gdb output

does it work on other hosts besides qtractor? say jalv and ardour

**Comment by martinsolberg** [comment]
Doesn't work in Ardour either. Won't even draw the interface. I'm using:

Name         : samplv1
Version      : 0.8.6
Release      : 4.fc29

**Comment by falkTX** [comment]
Sounds like an issue with samplv1 then.
There is 0.9.2 out there yet, that one can only use qt5 (like carla in develop branch), so we can be sure the issue won't be library conflicts
Try to update samplv1 to the latest version and let me know how it goes. thanks.

**Comment by martinsolberg** [comment]
Updated and it works. Thanks!
