### ISSUE TITLE
Regression in Carla 1.9.14 with Non Session Manager

### ISSUE THREAD

**Issue by miquecg** [falkTX/Carla#848]
After updating Carla to version 1.9.14 I cannot use it with Non Session Manager. Starting a previous session didn't show anything under rack, patchbay or log. A new empty session just alone with Carla as client didn't work either.

Logs are empty. It looks like Carla is not starting properly when invoked from NSM.

**Comment by falkTX** [comment]
I cannot reproduce, working just as before.
Try disabling capturing logs into carla window (so we get output on the terminal) and run non-session-manager on a terminal to see all possible output.

**Comment by miquecg** [comment]
Let me check it again. [1.19.14 version was re-packaged today](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/carla&id=d11e43eb3d6993bf76985cf1f79f6090ba94ebc9) in Arch Linux. I think I was using a different one.

**Comment by diovudau** [comment]
I looked for your bug. There were other problems with Carla and NSM and it turned out that the arch package was build from the wrong source file. Could you check if the new one works again?
It should be package 1.19.4-2.  For `carla --version` it prints `Using Carla version 1.9.14 (2.0-RC4)`

**Comment by miquecg** [comment]
Thanks for watching the issue. I can confirm that version `1.9.14 (2.0-RC4)` plays nice with Non Session Manager. Indeed it was a packaging problem in my distro.
