### ISSUE TITLE
[feature request] allow to specify the remote control port

### ISSUE THREAD

**Issue by BrainDamage** [falkTX/Carla#851]
When launching carla using --no-gui and wanting to control it remotely, one needs to know the port osc is listening to. However, the port it listens to is randomly assigned, making frustrating  establishing connection since it has to be manually checked every time by listing the listening sockets of the program.
Ideally it should be specified on a command-line argument basis, since one may want to launch multiple instances, with different ports.

**Comment by falkTX** [comment]
OSC settings have been added in develop branch, so now you can define a port to use by default much more easily.
If the port is already taken, carla tries 5 times with a +1 on the port.

Default behaviour is to use static port 22752 (maps to "carla" in old-phone-style keys)
