### ISSUE TITLE
carla-git can't find a plugin 

### ISSUE THREAD

**Issue by 666meow666** [falkTX/Carla#853]
Hi everyone, 

I'm on Ubuntu 18.04

I've followed the step by step videos explaining how to use windows VST on Linux via Carla. So I've installed the bridge plugins. 

I read this : http://kxstudio.linuxaudio.org/News/?action=view&url=carla-20-beta6-is-here
and also the issue #591 (I enabled experimental options, plugin bridges, and wine bridges too...)

But when Carla scans the VSTs, it finds only native VSTs but never Win32 or 64 ones. 
I checked that the windows VSTs are in the right folder, following the right path... 

I'm confused... really need some help

**Comment by eeickmeyer** [comment]
Hi. If you're using the Ubuntu Backports PPA, you might want to do a "sudo apt update && sudo apt full-upgrade" since we recently had a problem with the packaging of the Windows bridges. That might clear things up a little.

**Comment by 666meow666** [comment]
wow, fast response haha ! but unfortunately it still doesn't work....

**Comment by eeickmeyer** [comment]
You may have to completely remove carla "sudo apt autoremove --purge carla*" and re-add it, plus the packages required for the plugin bridges (carla-bridges-win32, carla-bridges-wine32, carla-bridges-win64, carla-bridges-wine64), and keep in mind that most Windows VSTs are 32-bit.

**Comment by JanFeld** [comment]
Did you explicitely enable the search filter in the "Add Plugin" window? I had to check two boxes for being able to select these plugins. The scan finds them but they just weren't shown in the list.

**Comment by falkTX** [comment]
any news on this?
did you try to enable the experimental options?

**Comment by 666meow666** [comment]
Hey everyone, thanks a lot for your responses. 
The problem was just a stupid one: 

indeed, as @JanFeld said, I didn't check the "_Bridged (32bit)_" and the _"Bridged (Wine)_" boxes in the _**Special Filters**_ menu of the **Add Plugin** window of Carla-git

Thank you !!

**Comment by falkTX** [comment]
Great to hear that.
This is rather a problem of documentation.
Still busy with other things, but eventually I hope to start a Carla manual or at least quick-start guide.
