### ISSUE TITLE
VST not found - but is loadable via drag'n drop...

### ISSUE THREAD

**Issue by esp901** [falkTX/Carla#854]
Hi. I am using the 64Bit-Windows-Version of Carla. When searching for VST's inside the given path, Carla
only finds very few of my plugins. But when I dndrop a plugin inside the rack, almost every plugin
works fine. So this surely not a prio1-issue.... Or am I missing somewhat?
Thanx for this great program btw!

Wolfgang

**Comment by falkTX** [comment]
You just need to set the paths correctly.
Go to the settings, Paths, choose VST (I guess that is what you want to load), and add the folder where they are located.
If loading windows bridges, don't forget to enable experimental options and bridges (inside experimental settings).
And on the window with the list of plugins, make sure to enable the filters so you can show windows plugins.

**Comment by esp901** [comment]
Very good! Worked ☺ You're THE man.
