### ISSUE TITLE
Can't debug Carla from Visual Studio

### ISSUE THREAD

**Issue by p0nce** [falkTX/Carla#856]
It keep detaching on load.

![image](https://user-images.githubusercontent.com/1067485/54086983-fa751d00-434e-11e9-9435-92f2f23c10a1.png)

Then pressing "Start Debugging" only attaches temporarily, it will get detached once run:

![image](https://user-images.githubusercontent.com/1067485/54086991-0f51b080-434f-11e9-8886-abb6aedf3a2f.png)

Not sure why this happens, I know of no other host that does this.

**Comment by falkTX** [comment]
The current carla binaries are self-extracting zip files. rename the exe to zip and extract it, then you will find the real stuff inside.

**Comment by p0nce** [comment]
!!!!!!

**Comment by p0nce** [comment]
Works now. thanks!
