### ISSUE TITLE
Unable to run "make wine32"

### ISSUE THREAD

**Issue by Grimecake** [falkTX/Carla#857]
First, thank you for creating what seems to be an awesome piece of software. I have been working to compile this for a few days now and it is driving me bonkers. I keep running into the following error. Any advice would be greatly appreciated as Carla is only detecting native Plugins, any DLL's are skipped, which I understand is because they are 32bit plugins.

make wine32
make -C source/jackbridge wine32
make[1]: Entering directory '/home/nikuya/Downloads/Carla/source/jackbridge'
Linking jackbridge-wine32.dll.so
ld: Relocatable linking with relocations from format elf64-x86-64 (/usr/lib/x86_64-linux-gnu/wine/libwinecrt0.a(dll_entry.o)) to format elf32-i386 (jackbridge-wine32.IF78dk.o) is not supported
winebuild: ld failed with status 1
winegcc: /usr/lib/wine/winebuild failed
Makefile:150: recipe for target '../../build/modules/Release/jackbridge-wine32.dll.so' failed
make[1]: *** [../../build/modules/Release/jackbridge-wine32.dll.so] Error 2
make[1]: Leaving directory '/home/nikuya/Downloads/Carla/source/jackbridge'
Makefile:325: recipe for target 'wine32' failed
make: *** [wine32] Error 2

I _BELIEVE_ I have the relevant dependencies but that doesn't mean I do and am fully expecting this to be user error :)

**Comment by falkTX** [comment]
Seems like you are missing some wine 32bit things
Do you have the file /usr/lib/i386-linux-gnu/wine/libwinecrt0.a ?

**Comment by Grimecake** [comment]
I don't appear to have that file. The only two I have are:

libwine.so.1
libwine.so.1.0

Which dependency am I missing? :(

**Comment by falkTX** [comment]
I do not know how it happens for the specific distro you have  (which one is it? I guess a form of debian..)
Looking at https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=contents&keywords=libwinecrt0.a we can see which packages provide that file.
so you can try:
```
sudo apt-get install libwine-development-dev:i386
```
or:

```
sudo apt-get install libwine-dev:i386
```

In any case, I recommend the use of wine-staging, as that one listens to RT permissions set by carla

**Comment by Grimecake** [comment]
Sorry for the delay! Had a busy weekend. Correct on the Debian guess. Using Ubuntu 18.04. I will try it again tonight and let you know how I go.

**Comment by eeickmeyer** [comment]
@Grimecake You can, of course, download it completely compiled, including the bridges, from the Ubuntu Studio Backports PPA.

`sudo add-apt-repository ppa:ubuntustudio-ppa/backports`
`sudo apt update`
`sudo apt install carla carla-bridge-wine carla-bridge-wine32`

**Comment by Grimecake** [comment]
@falkTX that command fixed it and it loads the plugin without any problems. Thank you very much!

@eeickmeyer I actually enjoy the compiling side of things. Don't ruin my fun ;)
