### ISSUE TITLE
Can't add any VST plugin

### ISSUE THREAD

**Issue by spoontex** [falkTX/Carla#858]
Hello,

I've just installed carla, with plugins bridges and enable experimental settings. But when scan for vst plugins, can't add them to carla.

I tried to reinstall everything, and try this:

carla win32 vst2 "Guitar Rig 5.dll"

but this only launch carla, and whitout errors in console.

Anybody can help me?

thanks.

**Comment by spoontex** [comment]
I've fixed. Sorry.

Is necessary enable Bridged ( WINE ) in special filters.

I don't know if it's correct.

**Comment by falkTX** [comment]
yeah, that makes sense.
Glad you figured it out by yourself.

**Comment by spoontex** [comment]
Now I have a lot of Xruns... 

Any advice?

**Comment by falkTX** [comment]
Look online on how to optimize your system for audio.
This is out of scope of the carla project, sorry, but a general OS setup.

**Comment by spoontex** [comment]
I know, but I have a low latency kernel installed and all the native linux apps works well ( ardour, gutiarix etc... ) I have xruns only with carla...

**Comment by falkTX** [comment]
carla in general, loading native plugins, or just with the wine bridges?
I recommend getting wine-staging, carla sets the environment for it so that it uses realtime permissons

**Comment by spoontex** [comment]
Only with wine bridges.

Okey, I try wine-staging.

Thanks!!!
