### ISSUE TITLE
How do I completely remove carla-git?

### ISSUE THREAD

**Issue by qwertysam** [falkTX/Carla#865]
I would like to fully remove carla-git, as there are a number of bugs that started happening (can't modify config, plugins under /usr/lib/vst don't show up in BitWig, scanning for plugins doesn't recognize carla-discovery-win32, etc.) I think part of it may be due to my own tinkering, but when I `sudo apt remove carla-git` and `sudo apt install carla-git`, the bugs stay. How can I delete the config files, any cache files, (and pretty much every file that carla creates on my pc)?

P.S. These bugs are happening with `Carla 2.0.90 (2.1-alpha2)`, the version on the repo. Downloading and using Carla 2.0.0 works like a charm, but then it isn't installed on my pc :( I can do repos and appimages and deb files, but I'm kind of a noob when it comes to raw binaries

**Comment by falkTX** [comment]
just install the "carla" package which will switch places with "carla-git"

I am surprised you have so many issues with the git version.
but anyway, configs are stored in `~/.config/falkTX/` there will be a bunch of Carla* config files there.

**Comment by qwertysam** [comment]
Thanks! I'm not sure what I did differently this time, but reinstalling `carla-git` made it detect my `carla-discovery-*` libraries properly, and now I can edit the config files. This makes me think that the permissions of that folder were somehow messed up.

Follow up question: I noticed that `carla` produces the `/usr/lib/vst` folder which I can add as a VST plugin source in BitWig, but `carla-git` does not. I'd like to use the newer features, should I be doing something differently to use Carla-git as a plugin in my DAW?

**Comment by falkTX** [comment]
> Follow up question: I noticed that `carla` produces the `/usr/lib/vst` folder which I can add as a VST plugin source in BitWig, but `carla-git` does not. I'd like to use the newer features, should I be doing something differently to use Carla-git as a plugin in my DAW?

Ah, I messed up this part. The carla-git package is missing the lv2 and vst plugins
Thanks for noticing, will push a fix right away.

**Comment by falkTX** [comment]
@qwertysam any success?

**Comment by falkTX** [comment]
nevermind, I forgot to refresh this page...
the fix for the missing carla lv2 and vst plugins is up.

**Comment by qwertysam** [comment]
The `carla-git` package is working now! And I get all the fancy new features that make it so much easier to use :)

![image](https://user-images.githubusercontent.com/1940579/54876476-df8eb800-4de6-11e9-9fab-a9214c9535ad.png)

Thank you for this software!
