### ISSUE TITLE
Adding carla lv2 to carla, qtractor assertion faliure.

### ISSUE THREAD

**Issue by Stazed** [falkTX/Carla#867]
======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  44100
  Process mode: Multi client
Will use LV2 External UI for 'Carla-Patchbay'
lv2ui_extension_data("http://lv2plug.in/ns/extensions/ui#idleInterface")
lv2ui_extension_data("http://lv2plug.in/ns/extensions/ui#showInterface")
lv2ui_extension_data("http://lv2plug.in/ns/extensions/ui#resize")
lv2ui_extension_data("http://kxstudio.sf.net/ns/lv2ext/programs#UIInterface")
Invalid lv2 beatsPerMinute value
Carla assertion failure: "fPorts.paramsPtr[i] != nullptr" in file ../utils/CarlaLv2Utils.hpp, line 938
Carla assertion failure: "fPorts.paramsPtr[i] != nullptr" in file ../utils/CarlaLv2Utils.hpp, line 938

The assertion failure repeats indefinitely.
CPU usage goes to max.

To re-create:
1) - Start carla standalone, carla, carla-patchbay or carla-rack.
2) - Add any variant of carla lv2 as plugin.
3) - Clicking the gear icon for the custom gui does not show the gui.

The internal carla and vst2 versions do not have this issue.

The lv2 versions do seem work with jalv.

The same issue occurs when adding lv2 in qtractor.

I'm on ubuntu studio 16.04 with kxstudio repos - using carla-git.

**Comment by falkTX** [comment]
I made some changes that made carla expose parameters in its internal plugin, but did not make it work for lv2. the carla lv2 version cant expose parameters, not taking that into account led to issues.
it is fixed now in latest git/develop.
