### ISSUE TITLE
Recent updates have stopped Carla loading plugins

### ISSUE THREAD

**Issue by Grimecake** [falkTX/Carla#869]
Hi again,

Am sorry to open another issue. I have been using Carla since my last issue quite happily however I had a ppa in my sources for the kxstudio repo's. Last night I received some updates from the repo and since then Carla is no longer loading the windows plugins I was using.

I was using ardour/carla, finished up, saw some updates were pending, installed and then checked ardour before going to bed and none of the previous plugins were working.

There are no error messages aside from the generic error about wine taking too long, and did the bridge crash? There are also no errors listed in the log tab.

I did a new clone of the git repo and recompiled/installed but there was no change.

System is Ubuntu 18.04 and have compiled Carla from source. I am at work at the moment so apologies for light on detail, although not sure what you require. Is there anything you can think of off the top of your head that could cause this?

If not, let me know what further info you would like and I will get it ASAP.

**Comment by falkTX** [comment]
Sounds serious, hopefully a straight forward thing.
Try the carla binaries available here and tell me if they work for you https://github.com/falkTX/Carla/releases/tag/v2.0.0

Also, do you have carla or carla-git package installed?
It is recommended to switch to the non-git, normal carla package now.

**Comment by Grimecake** [comment]
I am certain I downloaded those packages, but I will check everything tonight. failing that, I will give the binaries a shot.

**Comment by Grimecake** [comment]
Have Carla-git. No change when running the binary. Still gives same message "Failed to load file. Timeout while waiting for a response..." I have the bridges downloaded and installed as well. There are green ticks next to the plugin types.

**Comment by falkTX** [comment]
Switch to "carla" (no -git) and make sure to install all the updates.
The bridge format has changed, so both carla and the bridges need to updated and in sync.

Regardless, when it happens again, please post the messages in the logs.
Otherwise I am just guessing here..

**Comment by Grimecake** [comment]
have switched to carla (not -git) done an update/upgrade. no change. Unless the logs are hidden somewhere less obvious there are no errors (screenshot...png) aside from the generic (no detail.png).

**Comment by falkTX** [comment]
There are always some logs. maybe you disabled the option to show capture logs in the logs tab, and they end up then in the console.
Try running carla from a terminal.

**Comment by bellt** [comment]
I'm having the same issue. It was working yesterday before the updates, today the VST plugin I always use isn't working. 
Everything I've installed related to this is from the kxstudio repos.

Here is the popup error message when I manually try to add a VST plugin:
![Screenshot from 2019-03-28 10-54-09](https://user-images.githubusercontent.com/345478/55115137-a472e880-5148-11e9-9bfa-121437c7131a.png)
And the log, from when I open my usual Carla project file:
`======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  44100.0
  Process mode: Single client
Using WINEPREFIX '/home/tomb/.wine', with base RT prio 55 and server RT prio 70
Starting plugin bridge, command is:
/usr/lib/carla/carla-bridge-win64.exe "VST2" "/home/tomb/.wine/drive_c/Program Files/VstPlugins/SsdSampler.dll" """" 1399681132
WINE realtime scheduling hack enabled, realtime base priority has been set to 55
wineserver running SCHED_FIFO at priority 70
Carla assertion failure: "apiVersion == CARLA_PLUGIN_BRIDGE_API_VERSION" in file ../backend/engine/CarlaEngineBridge.cpp, line 178

Carla assertion failure: "maxPluginNumber == 0" in file ../backend/engine/CarlaEngineInternal.cpp, line 415

Carla assertion failure: "nextPluginId == 0" in file ../backend/engine/CarlaEngineInternal.cpp, line 416

Carla assertion failure: "in == nullptr" in file ../backend/engine/CarlaEngineInternal.cpp, line 44

Carla assertion failure: "out == nullptr" in file ../backend/engine/CarlaEngineInternal.cpp, line 45

Carla assertion failure: "! isThreadRunning()" in file ../utils/CarlaThread.hpp, line 54

Failed to init engine, error was:



carla_engine_close: Engine is not initialized

Failed to load a plugin, error was:
Timeout while waiting for a response from plugin-bridge
(or the plugin crashed on initialization?)
Error opening file /usr/lib/lv2/carla.lv2/manifest.ttl (No such file or directory)
Will use UI-Bridge for 'Calf Compressor', binary: "/usr/lib/carla/carla-bridge-lv2-gtk2"`

**Comment by falkTX** [comment]
> Carla assertion failure: "apiVersion == CARLA_PLUGIN_BRIDGE_API_VERSION"

This is the issue right here, you have a partial update.
Install the updated carla or carla-git, and also the bridges, and things will work as expected.

I tested it locally, can switch between carla and carla-git, things keep working just as before.

**Comment by bellt** [comment]
Thanks falk.
Turns out apt was keeping back the following packages from being upgraded:
```
The following packages have been kept back:
  carla-data carla-git
```
I tried just installing those two, to no avail:
```
tomb@ragnarok:~$ sudo apt install carla-data carla-git
[sudo] password for tomb: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 carla-git : Depends: carla-git-data (= 2:2.1~alpha2+git20190327v5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
So I tried:
`sudo apt install carla-git-data carla-git`
Followed by:
`sudo apt update && sudo apt upgrade`
Which automatically upgraded `carla-git carla-git-data carla-lv2 carla-vst`

And now everything works again!
I included the steps I took in case someone else comes across this thread with the same problem. Hopefully it also helps @Grimecake 

Seems like I had a weird combination of `carla-git` and `carla-data` installed (instead of `carla-git-data`)?

Thanks again Falk. I really appreciate your work on this project, and your quick responses here! Now I can get back to my drum practice :-)

**Comment by Grimecake** [comment]
Those steps got me a little further. Its now outputting logs. I dont remember ticking/unticking but its definitely something I could have done accidentally.

Terminal output:
Carla 2.0.90 (2.1-alpha2) started, status:
  Python version: 3.6.7
  Qt version:     5.9.5
  PyQt version:   5.10.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
qt.svg: <input>:552:178: Could not resolve property: linearGradient5167
qt.svg: <input>:30274: Could not resolve property: linearGradient5167
qt.svg: <input>:30274: Could not resolve property: pattern5614
qt.svg: <input>:30274: Could not resolve property: pattern5626
qt.svg: <input>:5672: Could not resolve property: radialGradient3709
qt.svg: <input>:3226: Could not resolve property: linearGradient3893-1
qt.svg: <input>:3190: Could not resolve property: linearGradient3893-1
qt.svg: <input>:3208: Could not resolve property: linearGradient3893-1
libjack.so.0 loaded sucessfully!

Carla Log output:
====== Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  44100
  Process mode: Continuous Rack
Using WINEPREFIX '/home/nikuya/.wine', with base RT prio 15 and server RT prio 10
Starting plugin bridge, command is:
/usr/lib/carla/carla-bridge-win32.exe "VST2" "/home/nikuya/Carla/TSE808_win32/TSE_808_2.0.dll" """" 0

As shown below, all the bridges are considered up to date:
carla-bridge-linux64 is already the newest version (2:2.1~alpha2+git20190327.2v5).
carla-bridge-linux32:i386 is already the newest version (2:2.1~alpha2+git20190327.2v5).
carla-bridge-win64 is already the newest version (2:2.1~alpha2+git20190321).
carla-bridge-win32 is already the newest version (2:2.1~alpha2+git20190321).
carla-bridge-wine32:i386 is already the newest version (2:2.1~alpha2+git20190321).
carla-bridge-wine64 is already the newest version (2:2.1~alpha2+git20190321).

**Comment by Grimecake** [comment]
Unfortunately, no. still same error.

**Comment by falkTX** [comment]
please install carla package then and try with that.

Afterwards, please run the following commands and paste the output:
```
dpkg -l | grep carla
carla -v
```

**Comment by Grimecake** [comment]
first command:
```
nikuya@nikbuntu:~$ dpkg -l | grep carla
ii  carla                                      2:2.0.0+git20190322v5                        amd64        audio plugin host
ii  carla-bridge-linux32:i386                  2:2.1~alpha2+git20190327.2v5                 i386         audio plugin host (linux32 bridge)
ii  carla-bridge-linux64                       2:2.1~alpha2+git20190327.2v5                 amd64        audio plugin host (linux64 bridge)
ii  carla-bridge-win32                         2:2.1~alpha2+git20190321                     amd64        carla win32 bridge
ii  carla-bridge-win64                         2:2.1~alpha2+git20190321                     amd64        carla win64 bridge
ii  carla-bridge-wine32:i386                   2:2.1~alpha2+git20190321                     i386         carla win32 bridge (wine DLL)
ii  carla-bridge-wine64                        2:2.1~alpha2+git20190321                     amd64        carla win64 bridge (wine DLL)
ii  carla-data                                 2:2.0.0+git20190322v5                        all          audio plugin host (common data)
ii  carla-lv2                                  2:2.1~alpha2+git20190327.2v5                 amd64        Dummy package
ii  carla-vst                                  2:2.1~alpha2+git20190327.2v5                 amd64        Dummy package
```

Second:
```
nikuya@nikbuntu:~$ carla -v
Using Carla version 2.0.0
  Python version: 3.6.7
  Qt version:     5.9.5
  PyQt version:   5.10.1
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources

```

**Comment by falkTX** [comment]
Versions look fine. so I don't really know what is going on.

Does the bridge work if you run it manually?
```
/usr/lib/carla/carla-bridge-win32.exe VST2 "/home/nikuya/Carla/TSE808_win32/TSE_808_2.0.dll" "" 0
```

Also..just a wild guess, but please try a windows 64bit plugin and see if that works.

**Comment by Grimecake** [comment]
Will try both suggestions ASAP. Have a busy weekend so don't be surprised if I dont get back to you before Sunday.

One thing to note, I only realised late last night. It seems like the sound in tux guitar has died as well. When I try to do an update it essentially comes up with a version mismatch from the kx repo and the packages was held back.

I figure if there is no luck regarding the cli usage or x64 plugin I will remove all the updates that were installed the other night and see if that helps at all.

**Comment by FilipeCSnuk** [comment]
(falkTX here, replying from another account as I am traveling, complicated...)

If you perhaps did not see https://kx.studio/News/?action=view&url=changes-in-kxstudio-repos-regarding-carla-and-jack2 then I recommend a quick little read

After the full update you will need a force-restart of jack.
That might be the reason some things are not working for you.

A reboot after applying all updates is recommended, just be to safe.
And I recommend using this for doing the updates:

```
sudo apt-get update
sudo apt-get dist-upgrade
```

The last command will figure out dependency issues automatically.

**Comment by Grimecake** [comment]
Unfortunately the dist-upgrade didn't help regarding the sound. I ended up going through the packages that were installed and removing some of the obvious ones. Tuxguitar began playing sound again but carla was still not a happy camper. 

At this stage, after looking at time spent vs time to restore files from backups, it was easier/quicker to completely nuke the system add the ubuntu studio repos and reinstall relevant software. Once all that was done, I opened carla set it back up for experimental and tried loading a plugin. Worked first time. After that I opened the project I had been working on in Ardour and everything was back to normal.

I am not sure what caused it, although as removing/reinstalling some packages from the ubuntu repo vs kx brought sound back in somethings I can only assume it was a conflict on my system and a "nuke and boot" removed it.

Thanks for your assistance with this and hope the traveling is going well.

**Comment by eeickmeyer** [comment]
> add the ubuntu studio repos...
@Grimecake There's no such thing as "Ubuntu Studio Repos." Ubuntu Studio is Ubuntu, so if you have the Ubuntu repos, you have the Ubuntu Studio repos. They're one in the same. I'm trying to stop this mentality that any of the official Ubuntu flavors are somehow separated, because they're not.

The only thing that's separate is the backports PPA, which simply updates a few select items in the Ubuntu repos for 18.04 and (as of this writing) 18.10.

**Comment by Grimecake** [comment]
Ah. Ok. I misunderstood and have been conflating the two.
