### ISSUE TITLE
make wine64 fails because of undefined LIBDL_LIBS

### ISSUE THREAD

**Issue by guitoo** [falkTX/Carla#871]
System: Gentoo Linux with an ebuild based on the arch carla-bridges-win64-git package

It compiles fine if I export LIBDL_LIBS=-ldl before make wine64

**Comment by falkTX** [comment]
sorry for late response, I did not know how to go about this.
looking at it further, it is likely that the filter for linux is not working when winegcc is used.
please tell me your output of:
```
winegcc -dumpmachine
```
thanks

**Comment by guitoo** [comment]
I can't reproduce the issue anymore. A lot of things have changed in a year.
