### ISSUE TITLE
Arch, Carla 2.0.0: Assertion failures when bridging Windows VST in Carla Rack or Patchbay

### ISSUE THREAD

**Issue by dgmulf** [falkTX/Carla#872]
While carla-single is capable of bridging VST plugins perfectly, Carla fails when bridging to the rack/patchbay in standalone mode or plug-in mode:

======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  44100.0
  Process mode: Multi client
Using WINEPREFIX '/home/dgmulf/.wine', with base RT prio 15 and server RT prio 10
Starting plugin bridge, command is:
/usr/lib/carla/carla-bridge-win64.exe "VST2" "/home/dgmulf/.wine/drive_c/Program Files/Common Files/VST2/Voxengo/Tube Amp.dll" "Voxengo Tube Amp" 1903783991
Carla assertion failure: "apiVersion == CARLA_PLUGIN_BRIDGE_API_VERSION" in file ../backend/engine/CarlaEngineBridge.cpp, line 178

Carla assertion failure: "maxPluginNumber == 0" in file ../backend/engine/CarlaEngineInternal.cpp, line 409

Carla assertion failure: "nextPluginId == 0" in file ../backend/engine/CarlaEngineInternal.cpp, line 410

Carla assertion failure: "in == nullptr" in file ../backend/engine/CarlaEngineInternal.cpp, line 41

Carla assertion failure: "out == nullptr" in file ../backend/engine/CarlaEngineInternal.cpp, line 42

Carla assertion failure: "! isThreadRunning()" in file ../utils/CarlaThread.hpp, line 54

Failed to init engine, error was:

carla_engine_close: Engine is not initialized

OS: Arch Linux 64-bit
Audio: Jack (jack2-dbus)
Carla: 2.0.0 (both official Arch package and built-from-source)
Carla bridges: 2.0.0 prebuilt binaries from Github
Wine: 64-bit prefix (tried both wine and wine-staging)

**Comment by falkTX** [comment]
Did you try updating the wine bridges from AUR?
This is just things being out of sync. One of them is more recent than the other, thus getting in conflict.
Versions must match, I guess you have so older build of the bridges which needs to be updated

**Comment by dgmulf** [comment]
Hi FalkTX,

I tried building everything in the latest git commit from source, and it
works without issue. I can confirm that my PKGBUILD was pulling the latest
binaries, but it still resulted in the error. Oddly, I had to remove the
md5sum check in the PKGBUILD, because the included hash was incorrect, but
maybe that was the package maintainer's oversight?

Thanks,
Danny

**Comment by falkTX** [comment]
this issue was fixed long time ago, forgot to close before, so doing that now
