### ISSUE TITLE
Adding Carla Rack LV2 to carla-jack-multi generates a lot of Xruns

### ISSUE THREAD

**Issue by diovudau** [falkTX/Carla#875]
Carla Version is 1:2.1.alpha2.r121.g1ae01df0-1 from archlinux AUR carla-git.
jackdmp version 1.9.12 tmpdir /dev/shm protocol 8 (git: 1:1.9.12.r119.g82329969-1 )
no other jack programs are running. 

When I add the LV2 variant of carla-rack into standalone carla-jack-multi (no NSM) starts generating XRuns, a few dozen per second.

The internal carla-rack version works.

**Comment by falkTX** [comment]
please test now, should be fixed with latest git

**Comment by diovudau** [comment]
Confirmed, no xruns anymore.
