### ISSUE TITLE
Patchbay wires do not disappear on middle click up

### ISSUE THREAD

**Issue by pdesaulniers** [falkTX/Carla#880]
If I middle click a port in the patchbay, drag it, then release it in the middle of nowhere, I get this:

![2019-04-18-20:18:42](https://user-images.githubusercontent.com/23723605/56398569-31283800-6217-11e9-8bca-6a4edb5307a5.png)

This seems pretty trivial to fix, I'll take a look at it.

**Comment by pdesaulniers** [comment]
The mouseReleaseEvent is not getting called because of the `return` here: https://github.com/falkTX/Carla/blob/develop/source/frontend/patchcanvas/scene.py#L381

I guess it would be better to avoid dragging connections using middle click and drag, since left click is already used for doing this?

**Comment by trebmuh** [comment]
Note that, if I left-click on a port, then move the mouse somewhere on a empty/dark place, then right-click, I obtain the same behavior.

(_Note that, with Catia 0.8.1, I obtain the same kind of behavior._)
