### ISSUE TITLE
FluidSynth Polyphony default value in UI is 0 but I believe reflecting the real default value make more sense

### ISSUE THREAD

**Issue by Anyeos** [falkTX/Carla#881]
Edited: I guess I am wrong here

In the UI I can set Polyphony parameter from 1 and more, but the FluidSynth code uses 0 too as a valid value. 
As an example I looked in the file Part.cpp from ZynAdd:

>                 "Polyphonic - Each note is played independently\n"
>                 "Monophonic - A single note is played at a time with"
>                 " envelopes resetting between notes\n"
>                 "Legato     - A single note is played at a time without"
>                 " envelopes resetting between notes\n"

[...]

>            if(i == 0) {
>                 p->Ppolymode = 1;
>                 p->Plegatomode = 0;
>             } else if(i==1) {
>                 p->Ppolymode = 0;
>                 p->Plegatomode = 0;
>             } else {
>                 p->Ppolymode = 0;
>                 p->Plegatomode = 1;
>             }}},

As can be see it uses zero (i == 0) as valid value to determine when the sample will be played in full polyphonic mode.
I know FluidSynth do the same because sometimes when I save my SF2 samples becomes monophonic last time I reopen the file. And researching I found that the problem is in the parameter #11 (Polyphony) that it say "1". And in the working samples (SF2 too) in the same parameter #11 it say "0". So, 0 is valid for FluidSynth and is the default value as can be see.
So, when I change the value "1" to "0" manually in the saved file, when I open it, it works as expected.

In the UI, for other way, the zero cannot be choosen, neither typed. The minimal number accepted with the input edit box is 1.

That is a big annoying little bug :P

But I solved it modifying the code that specifies the minimal value for FluidSynth and it worked as expected now:

### in /source/backend/plugin
```
diff CarlaPluginFluidSynth.cpp.old CarlaPluginFluidSynth.cpp 
882c882
<             pData->param.ranges[j].min = 1.0f;
---
>             pData->param.ranges[j].min = 0.0f;

```

**Comment by Anyeos** [comment]
Sorry, this does not work as expected. When I put it to 0 it only play one note at time (like 1).
I checked the sourcecode of CarlaPluginFluidSynth.cpp and found that at startup Carla sets a default value of 64 to Polyphony. That I don't understand is why it is reflected as "0" in the UI and in the saved file.

And the other thing that I didn't understood is why setting it to something greater than 1 give me a "sustain" effect instead a real polyphony. But that was in the last snapshot that I had. Now the behaviour is as expected (more than 1 means at least n-1 voices at the same time).

Im still trying to figure out what is wrong. But I don't know if 0 is a value that mean "default" in Carla "standard". I will try to force it to reflex the real default value of 64 instead of 0.

**Comment by falkTX** [comment]
I noticed this too, something odd is going on with the SF2 parameters.
I dont have time to deal with it now, but promise to do so later.
Still have to update to latest fluidsynth anyway, as I want to get DLS file support in Carla. So once I do that, will give this and sf2 code an overall look.
