### ISSUE TITLE
carla + calf gui = crash

### ISSUE THREAD

**Issue by lagunax** [falkTX/Carla#882]
debian 9, xfce
carla 2:2.0.0+git20190322v5 from kxstudio repo crashes when tries to open gui of any calf plugin (segmentation fault). when option [Engine]->[Use UI bridges instead of direct handling when possible] turn on(check it), then all works except showing grafs, turn off - opening gui makes crash carla.
rolling back to carla 2:2.0.0+git20190322 (without 'v5') gives stable working. update to v5 and it crashes.

**Comment by falkTX** [comment]
sorry for late response.
but this is kinda expected. carla runs lv2 UIs in a separate process, and thus no fancy graphs, as a way to get around crashes regarding plugin toolkit issues.
calf using gtk2 is problematic in the context of plugins. the crashes are to be expected sadly.
our best approach is to ask the calf plugin developers to move away from gtk
