### ISSUE TITLE
can't launch gui - no pyqt5 module

### ISSUE THREAD

**Issue by vlad0337187** [falkTX/Carla#889]
System: Linux Mint 19.1 Cinnamon
Carla: carla-git 2:2.1~alpha2+git20190327.2

It drops such error when I try to launch it:
```
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 24, in <module>
    from PyQt5.Qt import PYQT_VERSION
ModuleNotFoundError: No module named 'PyQt5
```

after I installed `python3-pyqt5`:
```
LRDF Support not available (LADSPA-RDF will be disabled)
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 40, in <module>
    from patchcanvas import patchcanvas
  File "/usr/share/carla/patchcanvas/patchcanvas.py", line 55, in <module>
    from .canvasbox import CanvasBox
  File "/usr/share/carla/patchcanvas/canvasbox.py", line 64, in <module>
    from .canvasicon import CanvasIcon
  File "/usr/share/carla/patchcanvas/canvasicon.py", line 24, in <module>
    from PyQt5.QtSvg import QGraphicsSvgItem, QSvgRenderer
ModuleNotFoundError: No module named 'PyQt5.QtSvg'
```

So I also needed to install `python3-pyqt5.qtsvg`.

So I think, that it would be enough to add this packages to dependencies:
`python3-pyqt5` 5.10.1+dfsg-1ubuntu2
`python3-pyqt5.qtsvg` 5.10.1+dfsg-1ubuntu2

Thank you.

**Comment by falkTX** [comment]
If you see the `INSTALL.md` file, the packages you mention are in there.

> Under Debian based systems, you can use this command to install everything:
> sudo apt install python3-pyqt5.qtsvg python3-rdflib pyqt5-dev-tools \
>   libmagic-dev liblo-dev libasound2-dev libpulse-dev libx11-dev \
>   libgtk2.0-dev libgtk-3-dev libqt4-dev qtbase5-dev libfluidsynth-dev

If you install carla from a repository, like Ubuntu, ArchLinux or Fedora, the dependencies are handled automatically.

So I am not sure what to do about this ticket...
Closing.

**Comment by cwellm** [comment]
Apparently, not. When I install it via pacman (ArchLinux) from the official repository, it gives me the same error.
