### ISSUE TITLE
Can't launch carla-control

### ISSUE THREAD

**Issue by Jacalz** [falkTX/Carla#890]
I have built carla with needed support and when opening the carla control ui it errors and tell me that liblo isn't installed (which it clearly is). I can open the normal ui just fine but I can't understand why control doesn't work.

Launch of normal ui:
![image](https://user-images.githubusercontent.com/25466657/59783755-2c3c3f00-92c1-11e9-89b2-6a5ae29c9102.png)

Launch of carla-control:
![image](https://user-images.githubusercontent.com/25466657/59783780-4249ff80-92c1-11e9-9408-a64f482127ab.png)

**Comment by terencode** [comment]
Install https://www.archlinux.org/packages/community/x86_64/python-pyliblo/

**Comment by falkTX** [comment]
yes, as terencecode mentioned, you need to install liblo's python bindings

**Comment by Jacalz** [comment]
Thanks for the help :+1: Couldn't this be better printed as an error so the user actually gets that without opening an issue? Like adding a line that says something along the lines of "make sure that you have "pyliblo" installed...

**Comment by terencode** [comment]
If you are building something from source, one of the first thing you do is check what the project needs as dependencies: https://github.com/falkTX/Carla/blob/develop/INSTALL.md#build-dependencies

**Comment by Jacalz** [comment]
I used the INSTALL.md file when building but it has no reference to python-pyliblo...

**Comment by terencode** [comment]
It mentions liblo but it might nor be clear enough.

**Comment by trebmuh** [comment]
(Correct me if I'm wrong but) INSTALL.md mentions liblo in the building dependencies, while here, python-pyliblo is a runtine dependency (which are 2 different things).

We probably should add a "RUNTIME dependency" section in the doc mentioning this python-pyliblo thing.

@falkTX thought?

**Comment by terencode** [comment]
@trebmuh you're correct, the documentation needs to be improved.
