### ISSUE TITLE
Hijacking control from qjackctl?

### ISSUE THREAD

**Issue by Gooberpatrol66** [falkTX/Carla#892]
I used carla to host a VST and qjackctl patchbay to get applications to auto-connect, but after a recent update, carla prevents qjackctl from controlling connections. Is there a workaround for this?

**Comment by falkTX** [comment]
Carla does no such thing.
something else happened there...

**Comment by Gooberpatrol66** [comment]
Oh, the names for the carla plugins changed, preventing things from connecting. Re-adding all the plugs fixed it.
