### ISSUE TITLE
ardour+carla(lv2) writes on disk in idle

### ISSUE THREAD

**Issue by Laguna-x** [falkTX/Carla#893]
Debian stretch+KXstudio(jackd as Firewire driver for Focusrite saffire pro 14 through ffado)
Hi. When add Carla-Rack as LV2 in ardour in any place - ardour makes 12 threads and they starts to write on disk right after adding (without any plugin loaded in rack(clean rack), also continues when adding anything in rack). in every ~30sec it makes glitches with sound. total write speed is about 2MB/s (as iotop says). if i load carla-rack as LXVST or open it as a own process - all OK, nothing writes on disk, no glitches.
any other LV2 works fine (not all LV2 checked, but several instruments works fine)

`root@studio:/home/producer# apt list --installed |grep ardour

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ardour/gcc5,now 2:5.12.0-1kxstudio2v5 amd64 [установлен, автоматически]
ardour-data/stable,stable,now 1:5.5.0~dfsg-1 all [установлен]
ardour-video-timeline/stable,stable,now 1:5.5.0~dfsg-1 all [установлен]
root@studio:/home/producer# apt list --installed |grep carla

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

carla-bridge-win32/trusty,now 2:2.1~alpha2+git20190321 amd64 [установлен, автоматически]
carla-bridge-win64/trusty,now 2:2.1~alpha2+git20190321 amd64 [установлен, автоматически]
carla-bridge-wine32/trusty,now 2:2.1~alpha2+git20190321 i386 [установлен]
carla-bridge-wine64/stable,now 2:2.1~alpha2+git20190321 amd64 [установлен, автоматически]
carla-git/xenial,now 2:2.1~alpha2+git20190327.2v5 amd64 [установлен, автоматически]
carla-git-data/xenial,xenial,now 2:2.1~alpha2+git20190327.2v5 all [установлен, автоматически]
carla-lv2/xenial,now 2:2.1~alpha2+git20190327.2v5 amd64 [установлен, автоматически]
carla-plugins-lv2/xenial,now 2:2.1~alpha2+git20190327.2v5 amd64 [установлен]
carla-vst/xenial,now 2:2.1~alpha2+git20190327.2v5 amd64 [установлен, автоматически]
root@studio:/home/producer# uname -a
Linux studio 4.9.0-9-rt-amd64 #1 SMP PREEMPT RT Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
`

**Comment by falkTX** [comment]
This is likely related to #885
Too much logging from carla makes ardour write to disk every couple of seconds.
I am investigating...

**Comment by falkTX** [comment]
Ok I think I found the issue. pushing an update to the kxstudio repos, version 2.1~alpha2+git20190712v5
