### ISSUE TITLE
Carla doesn't compile with gcc 9.1 and Qt 5.13

### ISSUE THREAD

**Issue by terencode** [falkTX/Carla#894]
Trying to compile carla-git on ArchLinux gives the following:
[carla_gcc9_make-error.txt](https://github.com/falkTX/Carla/files/3349935/carla_gcc9_make-error.txt)

**Comment by dvzrv** [comment]
I can confirm this and can provide some more extensive logs later.

**Comment by dvzrv** [comment]
[carla-2.0.0-build.txt](https://github.com/falkTX/Carla/files/3350844/carla-2.0.0-build.txt)

This should be the complete build log. I'll try to look into it later, but I'm pretty packed this week.

**Comment by dvzrv** [comment]
Hm, this seems to be a namespacing issue, because Qt5.13 .moc includes `<memory>` and it then gets namespaced.
I have fumbled around a bit with the .moc include location, but neither moving it before or after the namespace `CARLA_BRIDGE_UI_*` seems to work.
