### ISSUE TITLE
ladspa plugins not loaded

### ISSUE THREAD

**Issue by zokrezyl** [falkTX/Carla#902]
Hi, did run Carla with strace and the directories /usr/lib/ladspa are not scanned at all, no files are loaded. The config makes reference to /usr/lib/ladspa

**Comment by falkTX** [comment]
plugins are not scanned automatically (only internal and lv2 have that).
did you do a plugin scan? (menu plugin -> add-new -> refresh -> start)

**Comment by zokrezyl** [comment]
After "refresh" it works However not so intuitive, frankly. I someway thought that refresh would search for newly added plugins, thus if LDSPA were not found at start time, they would not be found with refresh...
