### ISSUE TITLE
MIDI Controller: Change Velocity

### ISSUE THREAD

**Issue by peterjschroeder** [falkTX/Carla#904]
It would be useful to be able to change the velocity of MIDI controllers in Carla.

**Comment by SpotlightKid** [comment]
I suppose you mean applying a scaling factor or curve to control change values? Only note-on/-off messages have velocity data. If you mean the latter, there are velocity scaling plugins in [this collection](http://x42.github.io/midifilter.lv2/) and I'm pretty the [pizMIDI](https://bitbucket.org/agraef/pizmidi/src/master/) collection also has them.

If you mean control change value scaling, x42/midifilrer.lv2 also has [a plugin](http://x42.github.io/midifilter.lv2/http___gareus_org_oss_lv2_midifilter_scalecc.html) for that too.

**Comment by peterjschroeder** [comment]
I was looking to disable touch sensitivity. The midifilters collection you linked to works (MIDI Velocity Adjust). Thank you.

**Comment by SpotlightKid** [comment]
Can you close the issue then, please?
