### ISSUE TITLE
Add /usr/share/sounds/sf3 to default path 

### ISSUE THREAD

**Issue by trebmuh** [falkTX/Carla#905]
I was reading at https://github.com/falkTX/Carla/issues/877 and am wondering if the default path for sf3 shouldn't be added to https://github.com/falkTX/Carla/blob/develop/source/frontend/carla_shared.py

FWIW, SF3 is currently worked on being integrated within Debian: https://lists.debian.org/debian-devel/2019/08/msg00005.html

@falkTX what do you think?

**Comment by falkTX** [comment]
Makes sense. I will add DLS support later on too, since latest fluidsynth releases can do that now.

**Comment by trebmuh** [comment]
Nice one!
