### ISSUE TITLE
duplication of available sfz when scanning for new plugin

### ISSUE THREAD

**Issue by YruamaLairba** [falkTX/Carla#906]
Hello,

I'm using carla 2.0.0 from librazik2 repository (based on Debian stretch)

Each time i'm scanning to discover new SFZ on my system, it's create a duplicate entry for each sfz already present on the available plugin list.

Highlighting the issue (menu name may inaccurate because my carla version is in french):
- inside carla, click on "add new plugin"
- in the new window, display special filter
- in column "plugin format" check "soundbank" and uncheck the others
- in the column "category"  instruments must be checked
-in the column "prerequisite" uncheck all
=> Now, only SFZ and SF2 should displayed. look at "type" column to know if it's a SFZ or SF2 soundbank
- click on refresh
 - in the new displayed window, uncheck all except SFZ
- click on "scan"
=> expectd result: only SFZ not already present on the list should be added.
=> obtained result: all SFZ found during scan are added, even those already present in the list, creating duplicate entry.

PS: can tell me how to reset plugin database until this problem is solved ?

**Comment by YruamaLairba** [comment]
i confirm the bug in the version downloaded from here: https://kx.studio/Applications:Carla#Download
(i used the Linux 64 bits)

I also found he file where plugin/soundbank list is stored: $HOME/.config/falkTX/CarlaPlugins4.conf.
deleting it allow to reset the plugin/soundbank list

**Comment by falkTX** [comment]
sorry for late response. is this still an issue with 2.1?

**Comment by YruamaLairba** [comment]
Sorry, still here, with subtle difference:
* i need to close the "refresh" modal window to make new duplicate entries appear.
* if i close carla, re-launch it, and refresh the SFZ list, all duplicate entries disappear. Have you made a workaround here ?

I couldn't test it under LZK because QT is too old. So this time the test was done on another machine with debian 10.

**Comment by trebmuh** [comment]
For info, the issue is still here with 2.1 on LibraZiK-3 (Debian Buster based).

**Comment by wvengen** [comment]
I'm experiencing this too with Carla 2.1+git20200614.

**Comment by falkTX** [comment]
ok I can reproduce this. the previous SFZ entries are not cleared when doing sfz rescan.
can try a fix..
