### ISSUE TITLE
[Feature Request] Carla-Patchbay, please add 64 channel variant

### ISSUE THREAD

**Issue by it9exm** [falkTX/Carla#908]
Hi,
Kontakt can output 64 channels, but carla-patchbay is limited to 32. I tried to add it by myself in the same way you did in commit 3ea17b4 but the newly created plugin is always showing 32 input and 32 output to jack. Do we need something else to make this work?

**Comment by falkTX** [comment]
wow, 64 channels?
I can add it sure, but not that I fully understand why.

**Comment by it9exm** [comment]
Thank you Felipe,
In this way I figured out why my modifications to the source weren't working, I didn't know about CarlaEngineGraph.cpp

Still can't explain why Carla-Patchbay64 VST is still showing only 32 playback and 32 capture in the connection graph. That's the only one i can launch from REAPER, which is currently lacking LV2 support.

LV2 patchbay launched from Ardour works correctly.

**Comment by falkTX** [comment]
ah my bad, forgot to add the rules to make `CarlaPatchbay64.so`
that one should work..

**Comment by it9exm** [comment]
Now i get this with 64ch VST version after building as usual:

Carla assertion failure: "pluginDesc != nullptr" in file carla-vst.cpp, line 1008

**Comment by falkTX** [comment]
you are correct, I was forgetting a few things.
Now fixed, might need a full rebuild
