### ISSUE TITLE
Clarify settings option "Prevent plugins from doing bad stuff"

### ISSUE THREAD

**Issue by CodingSpiderFox** [falkTX/Carla#909]
In the Carla settings -> Enable experimental features, go to the experimental settings menu.
There is a section "Engine" with an option "Prevent plugins from doing bad stuff"

a) I think security should be turned on by default
b) I don't know what bad stuff means in this context. I'd like to have a questionmark icon button next to the option that opens a popup window with explanation"

**Comment by sgissi** [comment]
I dug into the code, basically it is only active for Linux at the moment and what it does is to pre-load "interposer-safe" which blocks calls that are potentially dangerous like spawning new processes, initialize GTK, etc. I think it would be better worded as "Enable safe mode" or "Lock down plugins". I like the idea of adding an explanation too. While at it, grey it out if not running Linux. If other OS gets implemented, we can always enable the option then. I can do the PR if there is an agreement on what to implement.
