### ISSUE TITLE
Display installed wine version at startup of ./Carla

### ISSUE THREAD

**Issue by CodingSpiderFox** [falkTX/Carla#910]
I was trying to identify the cause for why my DensityMK3 2.0.3 Windows VST wouldn't load until I thought about checking my Wine version. It was 3.x and it seems that plugin needs 4.0.2. At least, after installing Wine 4, after dragging the plugin into the Carla rack, there came a window up saying it's updating the Wine config, and then it asked to install mono.

Displaying the Wine version on the commandline after startup of Carla could have given me a hint earlier on and might help others during troubleshooting, too.

**Comment by falkTX** [comment]
While I agree it would be nice, calling into wine is asking for trouble as it would most likely block carla startup.
Going to say no to this, sorry
