### ISSUE TITLE
Show log messages on the command line

### ISSUE THREAD

**Issue by CodingSpiderFox** [falkTX/Carla#911]
Event after installing Wine 4.0.2, the DensityMKIII plugin fails to load with this error messages.

![image](https://user-images.githubusercontent.com/25173078/64474906-c8603e80-d16a-11e9-8d9a-90c192a01978.png)

I'd like to see some logs about what fails in Carla or Wine (not sure where the actual issue is).

**Comment by SpotlightKid** [comment]
have you looked whether there are any error messages in the "Logs" tab?

**Comment by CodingSpiderFox** [comment]
Totally overlooked that tab. However, it works now. Don't know why

Thanks
