### ISSUE TITLE
make wine32 issue

### ISSUE THREAD

**Issue by jerboyd** [falkTX/Carla#914]
hello, I'm on fedora 30 x86_64. mingw version is
mingw32-gcc-8.3.0-2.fc30.x86_64
mingw64-wine-gecko-2.47-2.fc26.noarch
mingw64-filesystem-107-1.fc30.noarch
mingw32-filesystem-107-1.fc30.noarch
mingw32-headers-5.0.4-3.fc30.noarch
mingw32-wine-gecko-2.47-2.fc26.noarch
mingw64-crt-5.0.4-3.fc30.noarch
mingw32-winpthreads-5.0.4-3.fc30.noarch
mingw64-winpthreads-static-5.0.4-3.fc30.noarch
mingw64-cpp-8.3.0-2.fc30.x86_64
mingw32-binutils-2.30-6.fc30.x86_64
mingw64-headers-5.0.4-3.fc30.noarch
mingw32-cpp-8.3.0-2.fc30.x86_64
mingw-binutils-generic-2.30-6.fc30.x86_64
mingw64-gcc-8.3.0-2.fc30.x86_64
mingw64-gcc-c++-8.3.0-2.fc30.x86_64
mingw64-binutils-2.30-6.fc30.x86_64
mingw32-crt-5.0.4-3.fc30.noarch
mingw32-winpthreads-static-5.0.4-3.fc30.noarch
mingw-filesystem-base-107-1.fc30.noarch
mingw32-gcc-c++-8.3.0-2.fc30.x86_64
mingw64-winpthreads-5.0.4-3.fc30.noarch

i was able to get through to the last step of the process and during 'make wine32' i get this error.

make -C source/jackbridge wine32
make[1]: Entering directory '/home/jeremy/bin/Carla/source/jackbridge'
Compiling JackBridge1.cpp (wine32)
In file included from /usr/include/wine/windows/objbase.h:252,
                 from /usr/include/wine/windows/ole2.h:25,
                 from /usr/include/wine/windows/wtypes.h:13,
                 from /usr/include/wine/windows/winscard.h:22,
                 from /usr/include/wine/windows/windows.h:70,
                 from JackBridge1.cpp:22:
/usr/include/wine/windows/objidl.h:6100:15: error: ‘union _userSTGMEDIUM::<unnamed struct>::__WIDL_objidl_generated_name_0000000C’ invalid; an anonymous struct may only have public non-static data members [-fpermissive]
 6100 |         union __WIDL_objidl_generated_name_0000000C {
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
winegcc: gcc failed
make[1]: *** [Makefile:228: ../../build/jackbridge/Release/JackBridge1.cpp.wine32.o] Error 2
make[1]: Leaving directory '/home/jeremy/bin/Carla/source/jackbridge'
make: *** [Makefile:342: wine32] Error 2

this is way above my pay grade. any help would be appreciated.

**Comment by falkTX** [comment]
latest wine is broken, downgrade to get things to build again

**Comment by jerboyd** [comment]
Thx. That solved the issue.

**Comment by falkTX** [comment]
I added `-fpermissive` to the wine compiler flags, so this should not happen again.
If it still does somehow, then it will be a real nasty bug on Wine side of things

**Comment by tank-trax** [comment]
I am getting the same issue using wine-staging 4.20

**Comment by tank-trax** [comment]
On Debian Stretch I rolled back to 4.18 and had the same issue. Rolled back to 4.10 and it built.

**Comment by falkTX** [comment]
Opening again as it seems `-fpermissive` is not in use

**Comment by tank-trax** [comment]
still the same issue with wine-staging 5.0-rc1
is there another workaround other than downgrading/rolling back?

**Comment by DavidParkin** [comment]
I edited /usr/include/wine/windows/objidl.h around line 6101 and replaced
`        union __WIDL_objidl_generated_name_0000000C {
`
with
`        union  {
`
May not be suitable for everyone but Carla compiled.

**Comment by tank-trax** [comment]
that file is `objidl.h` different in the two locations for the `wine/windows` folder

the `objidl.h` file in `/opt/wine-staging/include/wine/windows/` has the line

the `objidl.h` file in `/usr/include/wine/wine/windows/` doesn't

is there a way to get the build to look in `/usr/include/wine/wine/windows/` rather than `/opt/wine-staging/include/wine/windows/` ?

**Comment by tank-trax** [comment]
I had to comment out these sections of lines 6091 and 6100 

 `union /*__WIDL_objidl_generated_name_0000000B */{`

`union /*__WIDL_objidl_generated_name_0000000C*/ {`

from `/opt/wine-staging/include/wine/windows/objidl.h`

and it built

**Comment by DavidParkin** [comment]
You took a more subtle approach than me. I would guess the version in your opt libs is more recent and built locally and if you could remove it the version in /usr/include will be used. Can you manage without the newer wine?

**Comment by tank-trax** [comment]
I recently migrated to Debian Buster and am using Wine Staging 5.0-rc1. I could have rolled back (did that on Stretch) but wanted to avoid doing that and prefer this solution you posted. 

I wanted to build LMMS and in order to do so, Carla has to be built locally. For some reason LMMS won't build or if builds will segfault when loading Carla. 

LMMS built, loads Carla... and the Github develop branch LMMS Vestige plugin is capable of loading both 64 and 32 bit Windows VST's whereas the LMMS AppImage's Vestige can only load 32 bit Windows VST's

Thanks again for posting that workaround.

**Comment by jerboyd** [comment]
I've recently upgraded to Fedora 33 and am having trouble compiling "make wine32" again. here is the output from make wine32

**Comment by falkTX** [comment]
Do you have the file `/usr/lib32/wine/libwinecrt0.a` ?

**Comment by jerboyd** [comment]
i have

/usr/lib64/wine/libwinecrt0.a
/usr/lib/wine/libwinecrt0.a

**Comment by falkTX** [comment]
Ah I see, that path is not there for linking.
Possibly fixed in 3c56f26a5fda9aa61960abfbd5a40560bfe2b592
Try building from the develop branch and let me know if that works for you

**Comment by jerboyd** [comment]
same result

**Comment by jerboyd** [comment]
Downgraded wine to 4.13 staging, which is what i was using on my previous installation and everything made just fine.

**Comment by falkTX** [comment]
this is fixed in 2.3-rc2
