### ISSUE TITLE
arpeggiator.lv2 receives no MIDI events

### ISSUE THREAD

**Issue by SpotlightKid** [falkTX/Carla#915]
[arpeggiator.lv2](https://github.com/BramGiesen/arpeggiator_LV2) works fine in `jalv.gtk` and Ardour (5.12) but when I load it in Carla, it receives no MIDI events. It shows up with two event input ports, `MIDI_in` and `events-in`, but regardless of whether I connect a MIDI source to one or the other or both, no MIDI events reach the plugin.

I inserted some debug logging calls into the MIDI [event handling loop](https://github.com/BramGiesen/arpeggiator_LV2/blob/master/arpeggiator/source/arpeggiator.c#L555) in the plugin's `run()` function, to verify this. Events were printed in `jalv`, but the loop body wasn't executed at all in Carla.

The plugin defines a MIDI input port and also [an additional input](https://github.com/BramGiesen/arpeggiator_LV2/blob/master/arpeggiator/source/arpeggiator.lv2/arpeggiator.ttl#L125) `atom:AtomPort` marked with `atom:bufferType atom:Sequence` and `atom:supports time:Position`, named "control", which may confuse Carla.

As a test, as suggested by @falkTX, I added `lv2:designation lv2:control` to the MIDI input port (index 0), but that only lead to lots of errors in the log:

    Carla assertion failure: "fJackBuffer != nullptr" in file CarlaEngineJack.cpp, line 333

That's in `CarlaEngineJackEventPort::getEvent()`.

**Comment by SpotlightKid** [comment]
If I change `arpeggiator.lv2` to merge the `control` port into the `MIDI_in` port, the plugin works in Carla too and shows only one input (`events-in`) and still works in `jalv` as well.

Here's a [patch for arpeggiator.lv2](https://github.com/SpotlightKid/arpeggiator_LV2/commit/09be8e67bd18a866855b788c22e24f0cb6a2af5f).

While that's a workaround, there still seems to be an issue with the way Carla handles multiple `atom:AtomPort`s.

**Comment by SpotlightKid** [comment]
Possible duplicate of #866.

**Comment by SpotlightKid** [comment]
Any news on this?

**Comment by falkTX** [comment]
No news yet, been busy with traveling and meeting people during my few days in berlin.
Things will slowly go back to normal again next week.

This should be something small to fix, I will mark it for v2.1

**Comment by SpotlightKid** [comment]
Just as a heads up for testing: latest versions of arpeggiator.lv2 only have one atom input anymore.

**Comment by falkTX** [comment]
I am going to close this one since the plugin works now.
The multiple lv2 input port handling is quite tricky for carla to handle, at least at the moment.

Next time such an issue arrives, let's work on it one plugin at a time.
