### ISSUE TITLE
Add a Package Status repology badge

### ISSUE THREAD

**Issue by luzpaz** [falkTX/Carla#917]
### Summary
A way for users to see what downstream repositories carry carla

### Proposed design
The compact badge looks like so:  
[![Packaging status](https://repology.org/badge/tiny-repos/carla.svg)](https://repology.org/project/carla/versions)

The full badge looks like so (but may be too "bulky"):  
[![Packaging status](https://repology.org/badge/vertical-allrepos/carla.svg?header=carla)](https://repology.org/project/carla/versions)  

---------

**Note:** There is also a possibility to add the full badge in to it's own section, like so:

```
### Packaging Status

<details>
  <summary>Expand to see the packaging status of carla...</summary>

[![Packaging status](https://repology.org/badge/vertical-allrepos/carla.svg?header=carla)](https://repology.org/project/carla/versions)  

</details>
```

**Which gives us:**  

### Packaging Status

<details>
  <summary>Expand to see the packaging status of carla...</summary

[![Packaging status](https://repology.org/badge/vertical-allrepos/carla.svg?header=carla)](https://repology.org/project/carla/versions)  

</details>

**Comment by luzpaz** [comment]
@falkTX care to take a quick look at this ?

**Comment by falkTX** [comment]
I dont particularly see the usefulness on this.
I actually have privacy concerns regarding such badges, as they access an external service everytime someone opens the carla page. This can be reused as analytics and perhaps tracking.

better to not waste your time here. I appreciate the intention, but I am not interested

**Comment by luzpaz** [comment]
fair enough.
