### ISSUE TITLE
ASIO selector doesn't open on Windows Server 2019 (1809)

### ISSUE THREAD

**Issue by OttoWerse** [falkTX/Carla#919]
I just recently started using Carla on my desktop PC (mostly for noise cancelation purposes) and found the setup pretty easy (with some YouTube assistance) to remove noise using Reaper's ReaFir plugin. 
However, when I wanted to do the same setup on my server machine (which is mostly used for multiroom audio hosting through Voicemeeters VBAN functionality) I almost immediately ran into an issue. I can't seem to select any ASIO, as the popup windows that lets you select which one to use simply won't open at all. I don't get any error message, just nothing happens. 

I don't know if Windows Server is even officially supported, but as far as I can tell the rest of the programme works perfectly fine, just this one window won't open for me.

I would really appreciate some hint as to what is going wrong here or even a possible workaround. (maybe this can be set up using the command line or through modifying some settings file)

**Comment by falkTX** [comment]
I am not sure if I ever implemented that button.
At least on 2.0 series I do not think it is even possible.
For 2.1 it will be.

So, I will add it in the future, but currently busy with other projects at the moment

**Comment by falkTX** [comment]
This has been implemented in 2.1, which is already out as RC.
The RC2 will be out very soon
