### ISSUE TITLE
Precompiled 64-bit binary of 2.0.0 fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by gdhgdhgdh** [falkTX/Carla#920]
Hullo!

I hoped that downloading the 64-bit binary would _JustWork_ but alas no. When I run either of the two big binaries in the root of the download, I get these interesting errors:

```
22:52 $ ./Carla
Carla self-contained executable 2.0.0, based on UnZipSFX.
Launching: '/tmp/carla/carla'
Traceback (most recent call last):
  File "/usr/share/cx-freeze-common/initscripts/Console3.py", line 27, in <module>
  File "build-carla/src/carla", line 22, in <module>

✔ ~/Desktop/Carla_2.0.0-linux64 
22:52 $ ./CarlaControl 
CarlaControl self-contained executable 2.0.0, based on UnZipSFX.
Launching: '/tmp/carla-control/carla-control'
Traceback (most recent call last):
  File "/usr/share/cx-freeze-common/initscripts/Console3.py", line 27, in <module>
  File "build-carla/src/carla-control", line 22, in <module>
```

This is a freshly-installed system 2 weeks ago and, other than Google Chrome, I haven't yet installed *anything* outside of Ubuntu's own packages or snaps.

**Comment by eeickmeyer** [comment]
The Ubuntu Studio team has a [Backports PPA](https://help.ubuntu.com/community/UbuntuStudio/BackportsPPA) that contains the Carla 2.0 package. I highly recommend using it instead.

**Comment by falkTX** [comment]
This is because the precompiled binary uses Qt4, as to support older distros as much as possible.
Install that and it should work

**Comment by gdhgdhgdh** [comment]
Superb, thank you :) Got it running with VSTs + Wine bridge.
