### ISSUE TITLE
One or more files did not pass the validity check

### ISSUE THREAD

**Issue by ex3lio** [falkTX/Carla#924]
Hello, I'm on Manjaro.

When I wanted to add plugins, I got the error "Failed to load plugin". Then I realized I hadn't build Carla-wine. But when I try, I get the following :

Building carla-bridges-wine...
==> Making package: carla-bridges-wine 2.0.0-1 (Tue 08 Oct 2019 05:40:08 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found carla-bridges-wine-2.0.0.tar.xz
==> Validating source files with md5sums...
    carla-bridges-wine-2.0.0.tar.xz ... FAILED
==> ERROR: One or more files did not pass the validity check!

Any help would be greatly appreciated

**Comment by falkTX** [comment]
Please raise the issue against the package manager, this is not something I can do a thing about.
