### ISSUE TITLE
Pianoteq UI has only 1/4 of it shown

### ISSUE THREAD

**Issue by terencode** [falkTX/Carla#932]
![image](https://user-images.githubusercontent.com/12665563/66760306-1b33c100-eea2-11e9-9b45-73006f490bd0.png)

- Resizing it with the shortcut keys still makes it 1/4 but bigger or smaller.
- Closing/Opening the UI or removing and adding back the plugin doesn't change anything.
- Clearing the pianoteq config files doesn't change anything
- This affects both the LV2 and VST version and also Reaper and jalv.
- Sometimes, the UI disappear completely

- I see the following in the log:
```
error: failed to expand CURIE `xsd:float'
Carla assertion failure: "index > 0" in file CarlaPluginVST2.cpp, line 2066
Carla assertion failure: "index > 0" in file CarlaPluginVST2.cpp, line 2066
```
- With Jalv, restarting the LV2 after resizing fixes it as demonstrated in the following video:

![Peek 2019-10-14 16-40](https://user-images.githubusercontent.com/12665563/66759968-7b763300-eea1-11e9-928b-d1d5a959e3fa.gif)

- I'm using Pianoteq Stage 6.6.0 but same behaviour with the regular version.

- I can reproduce on both Xorg and Wayland but it seems with Wayland I can somehow resize the window but it corrupts the UI.

- Gnome 3.34 and Qt 5.13.1

**Comment by terencode** [comment]
Playing with the code a bit inside CarlaPluginVST2.cpp for an issue only affecting the VST2 version, commenting out line 543-544 made the windows show everything.
https://github.com/falkTX/Carla/blob/8e8fe2e111b669fcd38be1d146cdf9e612949fa9/source/backend/plugin/CarlaPluginVST2.cpp#L536-L545

**Comment by falkTX** [comment]
oh so perhaps pianoteq calls host resize when its UI is open? that would be very odd, but so are vst plugins usually.
I will make a change to detect this.

**Comment by terencode** [comment]
I tried again with jalv and the issue might be the UI backend because jalv.gtk3 renders it correctly but jalv.qt5 renders it like that: 
![image](https://user-images.githubusercontent.com/12665563/77974229-ca504180-72f6-11ea-8583-89b22c01d201.png)

Carla also uses Qt5 so maybe there is something going on with this...

**Comment by falkTX** [comment]
Carla does not use Qt5 for the plugin handling, the backend and frontend are separate.
gtk3 must be setting up the window in a way pianoteq expects.

**Comment by falkTX** [comment]
I am closing this issue since it is not a Carla bug, but something in the plugin side.
We fixed that, and it behaves correctly.
Now we just have to hope JUCE devs will merge the changes.
