### ISSUE TITLE
BPM not automatically restored

### ISSUE THREAD

**Issue by moonshaadow** [falkTX/Carla#934]
Carla 2.0.0
When opening a project using "open", the project 's BPM isn't restored until I click on "Use JACK Transport ", although the button is already marked as enabled. After clicking, the BPM is correctly restored during the whole Carla's session.

The BPM is correctly restored when opening manually a file without start Carla before.

**Comment by falkTX** [comment]
Fixed in 302854ae65b5bef44bc013d3be9837f8a384bbb9
