### ISSUE TITLE
Error while loading SFZ soundbank

### ISSUE THREAD

**Issue by lootre** [falkTX/Carla#938]
Hi,

I'm unable to get Carla to load any of the SFZ sounbanks I try to load. I always get the same error message:

`Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ad_open(): fatal: no decoder backend available
Carla assertion failure: "handle != nullptr" in file sfzero/SFZSample.cpp, line 64
ynth based plugin - /usr/lib/dssi/fluidsynth-dssi.so
carla-discovery::error::/usr/lib/dssi/whysynth.so: undefined symbol: dssp_voicelist_mutex_unlock - /usr/lib/dssi/whysynth.so
carla-discovery::warning::Plugin 'Xsynth DSSI plugin' is not hard real-time capable - /usr/lib/dssi/xsynth-dssi.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/carla-bridge-lv2.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_interposer-jack-x11.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_interposer-safe.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_interposer-x11.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_native-plugin.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/carla.vst/libcarla_utils.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/lsp-plugins-lxvst-1.1.10/lsp-plugins-r3d-glx.so
carla-discovery::error::Not a VST plugin - /usr/lib/vst/lsp-plugins-lxvst-1.1.10/lsp-plugins-vst-core-1.1.10.so
SFZ '1st-violin-SEC-accent' loaded with 42 errors and 11 warnings:
Errors:
Couldn't load sample "1st-violins-stc-rr1-g3-PB.wav"
Couldn't load sample "1st-violins-stc-rr2-a#5-PB.wav"
Couldn't load sample "1st-violins-sus-e5.wav"
Couldn't load sample "1st-violins-sus-c#4.wav"
Couldn't load sample "1st-violins-stc-rr2-g3-PB.wav"
Couldn't load sample "1st-violins-stc-rr2-e4-PB.wav"
Couldn't load sample "1st-violins-stc-rr1-g5-PB.wav"
Couldn't load sample "1st-violins-stc-rr1-a#4-PB.wav"
Couldn't load sample "1st-violins-stc-rr2-g5-PB.wav"
Couldn't load sample "1st-violins-sus-g4.wav"
Couldn't load sample "1st-violins-stc-rr2-e6-PB.wav"
Couldn't load sample "1st-violins-stc-rr2-c#5-PB.wav"
Couldn't load sample "1st-violins-sus-a#5.wav"
Couldn't load sample "1st-violins-stc-rr1-a#6-PB.wav"
Couldn't load sample "1st-violins-stc-rr1-a#3-PB.wav"
Couldn't load sample "1st-violins-sus-e4.wav"
Couldn't load sample "1st-violins-stc-rr2-g4-PB.wav"
Couldn't load sample "1st-violins-stc-rr2-c#4-PB.wav"
Couldn't load sample "1st-violins-stc-rr1-a#5-PB.wav"
Couldn't load sample "1st-violins-stc-rr2-g6-PB.wav"
Couldn't load sample "1st-violins-stc-rr2-c#6-PB.wav"
Couldn't load sample "1st-violins-sus-g3.wav"
Couldn't load sample "1st-violins-sus-a#4.wav"
Couldn't load sample "1st-violins-stc-rr1-c#5-PB.wav"
Couldn't load sample "1st-violins-stc-rr1-c#4-PB.wav"
Couldn't load sample "1st-violins-sus-c#6.wav"
Couldn't load sample "1st-violins-sus-a#3.wav"
Couldn't load sample "1st-violins-stc-rr1-c#6-PB.wav"
Couldn't load sample "1st-violins-sus-g6.wav"
Couldn't load sample "1st-violins-stc-rr1-e4-PB.wav"
Couldn't load sample "1st-violins-stc-rr1-e6-PB.wav"
Couldn't load sample "1st-violins-sus-e6.wav"
Couldn't load sample "1st-violins-sus-c#5.wav"
Couldn't load sample "1st-violins-stc-rr2-a#4-PB.wav"
Couldn't load sample "1st-violins-stc-rr1-g4-PB.wav"
Couldn't load sample "1st-violins-stc-rr2-a#6-PB.wav"
Couldn't load sample "1st-violins-stc-rr1-e5-PB.wav"
Couldn't load sample "1st-violins-sus-g5.wav"
Couldn't load sample "1st-violins-sus-a#6.wav"
Couldn't load sample "1st-violins-stc-rr2-e5-PB.wav"
Couldn't load sample "1st-violins-stc-rr2-a#3-PB.wav"
Couldn't load sample "1st-violins-stc-rr1-g6-PB.wav"
Warnings:
unsupported opcode: pitch_random
unsupported opcode: amp_random
unsupported opcode: seq_position
unsupported opcode: seq_length
unsupported opcode: delay
unsupported opcode: eq1_freq
unsupported opcode: eq1_bw
unsupported opcode: eq1_gain
unsupported opcode: eq2_freq
unsupported opcode: eq2_bw
unsupported opcode: eq2_gain
SFZ '1st-violin-SEC-accent' loaded without errors, but has 11 warnings:
unsupported opcode: pitch_random
unsupported opcode: amp_random
unsupported opcode: seq_position
unsupported opcode: seq_length
unsupported opcode: delay
unsupported opcode: eq1_freq
unsupported opcode: eq1_bw
unsupported opcode: eq1_gain
unsupported opcode: eq2_freq
unsupported opcode: eq2_bw
unsupported opcode: eq2_gain
SFZ 'G800-A112-Piano1d-2-1f' loaded with 30 errors and 5 warnings:
Errors:`

I'm working with a fresh install of UbuntuStudio 19.10 and the provided version of Carla (2.0.0). However, I already had the same problem with Ubuntu 19.04.

Thanks for your help !

**Comment by falkTX** [comment]
This line is what starts it all:
> ad_open(): fatal: no decoder backend available

seems like there is no audio file support at all in this build.

please report this to UbuntuStudio devs. I will see if I can get a hold of them..

**Comment by falkTX** [comment]
I think UbuntuStudio fixed the package now.
in any case, it is not a problem from carla's side.

**Comment by eeickmeyer** [comment]
That's correct. SRU is done, just waiting during the mandatory waiting period of 1 week before it can be put into 19.10's update repo. That said, it's already in Focal Fossa (what will be 20.04 LTS).

**Comment by lootre** [comment]
Thanks a lot @falkTX and @eeickmeyer , I'll wait for the official update and try it again.

**Comment by lootre** [comment]
Just a message to let you know this issue is fixed ! Thanks a lot for your job.

Now there are some other issues but I'll report them in seperates bug reports.
