### ISSUE TITLE
Passthrough of CV between external and internal?

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#955]
So CV can be passed to/from external software/hardware.

**Comment by falkTX** [comment]
In theory yes, but besides MOD Duo X, I do not know of any projects that expose physical CV ports in a patchbay scenario.

There seems to be a way for soundcards to support CV, by tagging specific audio channels as CV (I have seen one of these at superbooth this year), but I am not aware of how it works internally.

**Comment by mxmilkb** [comment]
I was meaning for Patchbay mode Carla, between Internal and External.

I realise now I made a mistake on checking and that this works already directly in Multi-client mode! (I can't remember why I was using Patchbay over Multi-client. Is one more efficient than the other?)

Regarding to external hardware, I've [made](https://github.com/flok99/UTWIN6001/issues/1) [some](https://github.com/mxmxmx/terminal_tedium/issues/11) [requests](https://github.com/hdavid/ports/issues/1) to some projects, will see what happens. There was interest for that in #opensourcemusicinans before.

**Comment by falkTX** [comment]
ah okay, I misunderstood.
I added a "patchbay with cv" variant to the carla plugins so we are able to get CV in and out of they patchbay to other things. VST cannot support this, but LV2 can

**Comment by falkTX** [comment]
Closing since the actual issue is resolved with the "new" carla plugin variants.
