### ISSUE TITLE
LV2 CV min/max/units as JACK port metadata?

### ISSUE THREAD

**Issue by mxmilkb** [falkTX/Carla#956]
As mentioned in #jack.

**Comment by falkTX** [comment]
Carla already sets and reads the min/max as of some commits ago.
It does not care about the unit, since there is no specification around this.

**Comment by mxmilkb** [comment]
Does not the LV2 Unit spec not have various forms of unit, so one could say or a min of 20, a max of 20000 and a unit of hz?

**Comment by falkTX** [comment]
sure yes, but we have not defined what to use for CV ports.
In MOD I had to create a new unit mod:volts, which is used for the mod:CVPorts.
As of right now lv2 units do not have a "volts" unit.
