### ISSUE TITLE
[Feature Request] have a command-line option to set the OSC bind url

### ISSUE THREAD

**Issue by BrainDamage** [falkTX/Carla#959]
currently Carla uses a random osc port(s) assigned by the os, ideally there should be a command line variable to allow one to chose a fixed one to allow to use the remote interface more easily because launching an instance and trying to monitor which port it got bound to is pretty awkward

**Comment by falkTX** [comment]
In the develop branch, there is a tab dedicated to OSC in the settings. You set the specific OSC port there.
You can always use CLI env vars for that too.
Please try latest git and let me know if that works well enough for you.

**Comment by BrainDamage** [comment]
ah excellent, the env var makes it pretty usable from the command-line too
