### ISSUE TITLE
Need help setting up

### ISSUE THREAD

**Issue by azimoert** [falkTX/Carla#964]
I have to say that I am new in this and my question might be stupid.

The issue I have right now is that I can't force Carla to recognize the sound from Voicemeeter. Most guides on youtube just say that you have to use ASIO in the settings of Carla and Patch Composite in Voicemeeter. So I did try this but Carla still didn't catch a sound.

Do I miss any steps? What should I do to set up Carla for live audio formatting?

**Comment by azimoert** [comment]
After 8 hours of exploring the issue, I now know that Kaspersky Antivirus basically blocked all possible activities locking sound from any possible source.

**Comment by falkTX** [comment]
sorry for the lack of response, I was hoping someone else would chime in.
next time, please use the kxstudio chat over at https://chat.kx,studio and people will more likely answer there.
The github project is more for bug reporting and feature request, not general user help. Thanks
