### ISSUE TITLE
"Failed to load plugin - Invalid or unsupported plugin type"

### ISSUE THREAD

**Issue by mmedr** [falkTX/Carla#965]
Freshly installed carla-git does not work for me.
Tried to add Guitarix and Dexed, both failed. The Error Dialog says "Failed to load plugin - Invalid or unsupported plugin type".
Only "Internal" Plugins are addable. LV2, VST2, VST3, and so on not.

I am running a Manjaro Machine. 

Do you need more information? This is my very first issue message, so please excuse my newbish approach.

**Comment by falkTX** [comment]
Sorry for the late response.
Can do you a full rescan of the plugins? That might help here

**Comment by mmedr** [comment]
No problem mate! Glad to hear from you. While scanning/rescaning for plugins I encounter the following error:

"The program carla-discovery-win32.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience."

I don't know if it is a carla-specific error. The Carla-Log-Panel says the following :
 
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  48000
  Process mode: Continuous Rack
wine: Call from 0x7ee5a702 to unimplemented function msvcr120.dll.?_NewCollection@_AsyncTaskCollection@details@Concurrency@@SAPAV123@PAV_CancellationTokenState@23@@Z, aborting
wine: Unimplemented function msvcr120.dll.?_NewCollection@_AsyncTaskCollection@details@Concurrency@@SAPAV123@PAV_CancellationTokenState@23@@Z called at address 7EE5A702 (thread 0009), starting debugger...

I hope this information will help us.

Kindest greetings!

**Comment by falkTX** [comment]
That is a wine crash, a plugin trying to call a function that is not yet implemented in wine.

Do plugins load after that full rescan?

**Comment by mmedr** [comment]
Thanks for your quick reply. The scan/plugin-load-process continues after confirming the wine-discovery error dialog, but the desired plugin (i.e. Guitar Rig 5) does not appear in the plugin list. I do not encounter any problems with vsts that are not based on wine (i.e. Dexed)

**Comment by falkTX** [comment]
That will be an issue with wine then (if it is guitar rig the one that triggers the crash dialog)
By what you say, I consider the originally reported issue to be fixed.

For the plugin, see if you are able to run its standalone version first. Before that works, there is no point trying it in carla (as it will have similar issues, due to wine)
