### ISSUE TITLE
Carla-Rack : Parameters font size is too small

### ISSUE THREAD

**Issue by terencode** [falkTX/Carla#966]
No matter the number of parameters exposed, the font size is always too small to be useful: 
![image](https://user-images.githubusercontent.com/12665563/69728447-bc11cf00-1124-11ea-800a-5f019cabd887.png)

This is on a 1440p screen.

**Comment by falkTX** [comment]
I tried a couple of things to get around this a few days ago, but nothing that showed visible effort.
First I have to reproduce it properly though.
what desktop and linux distro are you using? did you set a custom desktop scale?

also, is this carla 2.0 or 2.1?

**Comment by terencode** [comment]
- Gnome 3.36
- ArchLinux
- Xorg so I can't use a custom desktop scale
- This is carla tested up to 76e50bf2f

**Comment by terencode** [comment]
Carla correctly reacts to `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1.5` but then the rest is too big.

**Comment by terencode** [comment]
Maybe a solution is to make the rack for each plugins bigger.

**Comment by terencode** [comment]
Fixed by using `QT_SCREEN_SCALE_FACTORS=1.25`.

**Comment by robouden** [comment]
terencode,

I have same issue as you have.
Where did you change the parameters?

BTW I use Linux Mind 19.3

**Comment by terencode** [comment]
@robouden those are [Environment Variables](https://wiki.archlinux.org/index.php/Environment_variables) so you can first test if it works for you by opening your terminal and running `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS=1.25 carla`

If it gives you the correct result you can enable it for all Qt applications by putting them in `/etc/profile.d/qt.sh` for example.
Inside qt.sh :
```
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCREEN_SCALE_FACTORS=1.25
```

After saving, reboot and you should have those envs globally applied.
You can check if this is the case by opening a shell and doing `echo $QT_SCREEN_SCALE_FACTORS`.
If it prints `1.25` then you are good to go!

**Comment by topazUK** [comment]
is there a way to use this tweak in windows please ? ;-)
