### ISSUE TITLE
Lots of crackling and popping on OSX 10.14.5

### ISSUE THREAD

**Issue by dmorgan-github** [falkTX/Carla#969]
I'm using midi-in -> reaktor6 -> audio-out. Core Audio (Built-in Output). I am getting cracks and pops at any volume level. 

Is there a setting I need to adjust?

This is what is currently showing in the log tab:

======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  44100.0
  Process mode: Patchbay
QNSView mouseDragged: Internal mouse button tracking invalid (missing Qt::LeftButton)
2019-11-25 11:52:29.928 carla-discovery-native[31995:5217082] Error loading /Library/Audio/Plug-Ins/VST/JACK-insert.vst/Contents/MacOS/JACK-insert:  dlopen(/Library/Audio/Plug-Ins/VST/JACK-insert.vst/Contents/MacOS/JACK-insert, 262): no suitable image found.  Did find:
	/Library/Audio/Plug-Ins/VST/JACK-insert.vst/Contents/MacOS/JACK-insert: no matching architecture in universal wrapper
	/Library/Audio/Plug-Ins/VST/JACK-insert.vst/Contents/MacOS/JACK-insert: no matching architecture in universal wrapper
vstHostCanDo("asyncProcessing") - unknown feature
vstHostCanDo("editFile") - unknown feature
vstHostCanDo("asyncProcessing") - unknown feature
vstHostCanDo("editFile") - unknown feature
vstHostCanDo("asyncProcessing") - unknown feature
vstHostCanDo("editFile") - unknown feature
[VCV Bridge] client initialized
[VCV Bridge] connect() failed: error 61
[VCV Bridge] client destroyed
[VCV Bridge] client initialized
[VCV Bridge] connect() failed: error 61
[VCV Bridge] client destroyed
carla_vst_hostCanDo("asyncProcessing") - unknown feature
carla_vst_hostCanDo("editFile") - unknown feature
QNSView mouseDragged: Internal mouse button tracking invalid (missing Qt::LeftButton)
======= Stopping engine =======
======= Engine stopped ========
======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  CoreAudio
  Sample rate:  44100.0
  Process mode: Patchbay
carla_vst_hostCanDo("asyncProcessing") - unknown feature
carla_vst_hostCanDo("editFile") - unknown feature

**Comment by falkTX** [comment]
Please try with 2.1-RC1, just released today.
The audio library that handles macOS stuff has been replaced, hopefully audio works fine now, please confirm

**Comment by dmorgan-github** [comment]
Seems like it is better. Unfortunately, I just can't figure out how to use your program. The Midi Input plugin doesn't seem to capture midi note-on events. I can't find where midi devices are configured. Also, the Midi Pattern plugin doesn't allow me to place notes on the timeline. Clicking notes on the keyboard does work so I know sound can come out of it.

**Comment by falkTX** [comment]
> Unfortunately, I just can't figure out how to use your program.

I am working on a user manual for Carla right now, precisely because of this.

> The Midi Input plugin doesn't seem to capture midi note-on events. I can't find where midi devices are configured.

You setup MIDI devices by going to the menu Canvas -> Show external.
Then you can connect from hardware devices into Carla.

I plan to add an option in the settings so that devices are automatically connected. But have not done that yet..

> Also, the Midi Pattern plugin doesn't allow me to place notes on the timeline. Clicking notes on the keyboard does work so I know sound can come out of it.

You can use the menus to change between modes, or press the letter "F" to toggle between selection/edition mode. I will see about adding a button to the GUI, so it is more clear how to do things.

Thanks for the feedback.

I am closing this ticket due to the original issue being fixed.
Let me know if you find any more issues.

**Comment by dmorgan-github** [comment]
I was interested in using this with SuperCollider sending midi events. When I "show external" I can see scsynth in the wire up but it doesn't show any option to wire midi. Also I have a Roli Block connected to my laptop and it doesn't show up in the external setup and I don't know where to look to add it. A guide would be very helpful. Until then, I'm finding this very confusing - though I really like the idea of a simple modular vst host and would like to make it work. Thanks.
