### ISSUE TITLE
carla doesn't load Pure Data as jack app

### ISSUE THREAD

**Issue by daveriedstra** [falkTX/Carla#970]
I'm trying to use Pure Data as a plugin in a DAW via Carla, but Pd won't load using the "Add Jack Application" feature. I've tried loading Pd minimally, using both the `puredata` and `pd-l2ork` versions.

**OS**: Pop!_OS 19.10
**DE**: Gnome 3.34.1 (affects both wayland and X sessions)
**Carla version**: 
```
$ carla --version
Using Carla version 2.0.0
  Python version: 3.7.5
  Qt version:     5.12.4
  PyQt version:   5.12.3
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
```

with `puredata`:
1. add jack application with command: `puredata -jack`
2. carla logs 
```
waitForClient(process) timed out
```
3. switch to rack view, `puredata` module is disabled
4. enable `puredata` module
5. carla logs 
```
Carla assertion failure: "unlocked" in file ../utils/CarlaSemUtils.hpp, line 182
waitForClient(process) timed out
```

with `pd-l2ork`:
1. add jack application with command: `pd-l2ork -jack`
2. carla logs 
```
guidir is /usr/lib/pd-l2ork/bin
priority 6 scheduling enabled.
[1130/121738.364487:WARNING:chrome_main_delegate.cc(565)] final extension: 
Carla assertion failure: "shmIds != nullptr && std::strlen(shmIds) == 6*4" in file libjack.cpp, line 133
[5332:5354:1130/121738.471502:ERROR:nss_util.cc(802)] After loading Root Certs, loaded==false: NSS error code: -8018
priority 8 scheduling enabled.
priority 8 scheduling enabled.
Created new window in existing browser session.
waitForClient(process) timed out
```
3. switch to rack view, `pd-l2ork` module is disabled
4. enable `pd-l2ork` module
5. carla logs 
```
guidir is /usr/lib/pd-l2ork/bin
priority 6 scheduling enabled.
[1130/121823.648199:WARNING:chrome_main_delegate.cc(565)] final extension: 
Carla assertion failure: "shmIds != nullptr && std::strlen(shmIds) == 6*4" in file libjack.cpp, line 133
Carla assertion failure: "unlocked" in file ../utils/CarlaSemUtils.hpp, line 182
[5395:5415:1130/121823.752554:ERROR:nss_util.cc(802)] After loading Root Certs, loaded==false: NSS error code: -8018
priority 8 scheduling enabled.
priority 8 scheduling enabled.
Created new window in existing browser session.
waitForClient(process) timed out
```

**Comment by falkTX** [comment]
I went deep into this, puredata is forking itself (or using watchdog) for some reason.
The forking behaviour is nasty, luckily works with regular jack, but that approach will not work for carla.
I tried to get a few workarounds, but nothing works in the end.
So as far as I am concerned, puredata is not compatible with the way carla handles its fake libjack, sorry

**Comment by daveriedstra** [comment]
Ah that's a shame, this would have allowed a Max-for-Live type setup in a Linux setup. I'll have to look for some other way to do this. Thank you for looking into it though, and for all the other work you do!

**Comment by falkTX** [comment]
no problem.
I sadly dont know anything regarding how puredata works internally, so I cant help much.

perhaps the purrdata works? did you try that one?

**Comment by daveriedstra** [comment]
I'll give it a shot, but I think purrdata is primarily pd-l2ork with a NW.js frontend so I doubt it will work.

**Comment by daveriedstra** [comment]
nearly the same result using `purr-data` as with `pd-l2ork`.
after adding jack app:
```
guidir is /opt/purr-data/lib/pd-l2ork/bin
priority 6 scheduling enabled.
[0331/092715.279725:WARNING:chrome_main_delegate.cc(590)] final extension: 
Gtk-Message: 09:27:15.329: Failed to load module "appmenu-gtk-module"
[19826:19850:0331/092715.469826:ERROR:nss_util.cc(802)] After loading Root Certs, loaded==false: NSS error code: -8018
[19860:19860:0331/092715.522147:ERROR:sandbox_linux.cc(346)] InitializeSandbox() called with multiple threads in process gpu-process.
Carla assertion failure: "shmIds != nullptr && std::strlen(shmIds) == 6*4" in file libjack.cpp, line 133
Carla assertion failure: "shmIds != nullptr && std::strlen(shmIds) == 6*4" in file libjack.cpp, line 133
priority 8 scheduling enabled.
priority 8 scheduling enabled.
JACK application window found and captured
waitForClient(process) timed out
```

after attempting to enable rack module:
```
guidir is /opt/purr-data/lib/pd-l2ork/bin
priority 6 scheduling enabled.
Carla assertion failure: "unlocked" in file ../utils/CarlaSemUtils.hpp, line 182
[0331/092732.331640:WARNING:chrome_main_delegate.cc(590)] final extension: 
Gtk-Message: 09:27:32.368: Failed to load module "appmenu-gtk-module"
[19906:19928:0331/092732.494932:ERROR:nss_util.cc(802)] After loading Root Certs, loaded==false: NSS error code: -8018
[19937:19937:0331/092732.547956:ERROR:sandbox_linux.cc(346)] InitializeSandbox() called with multiple threads in process gpu-process.
Carla assertion failure: "shmIds != nullptr && std::strlen(shmIds) == 6*4" in file libjack.cpp, line 133
Carla assertion failure: "shmIds != nullptr && std::strlen(shmIds) == 6*4" in file libjack.cpp, line 133
priority 8 scheduling enabled.
priority 8 scheduling enabled.
JACK application window found and captured
waitForClient(process) timed out
```

**Comment by falkTX** [comment]
what is the best way to get or install purrdata?
is there an example file I can load that produces sound?

I am quite interested to get something that does puredata to work this way

**Comment by daveriedstra** [comment]
there are some linux install instructions here: https://git.purrdata.net/jwilkes/purr-data#downloads

here's a simple patch that generates a 440 tone. (I had to add the .txt extension to attach it here, you'll need to rename the file to `tone.pd`):
[tone.pd.txt](https://github.com/falkTX/Carla/files/4409529/tone.pd.txt)
