### ISSUE TITLE
Carla Rack doesn't show enabled vsts

### ISSUE THREAD

**Issue by raven-wing** [falkTX/Carla#974]
CarlaRack (tested in Tracktion) doesn't show vsts connected to rack. Drag and drop from dir to to rack  also doesn't work.
It resulted with:
```
File "/usr/share/carla/resources/carla_widgets.py", line 1494, in _createParameterWidgets
    groupName = paramInfo['groupName']
```
Changing initialization of comment and groupName to empty string makes thing work.
```
def reloadParameters(self):
.
.
.
                'comment': "", #  paramInfo['comment'],
                'groupName':"", # paramInfo['groupName'],
```

It seems some initial assignment would solve problem

**Comment by falkTX** [comment]
is your carla build up to date?
this used to be an issue in a few commits, but was quickly fixed afaik

**Comment by raven-wing** [comment]
You're right. It works. Though drag and drop does not. But it's another story. 
Thanks!
