### ISSUE TITLE
Carla-bridge: black borders for windows plugins

### ISSUE THREAD

**Issue by terencode** [falkTX/Carla#975]
![image](https://user-images.githubusercontent.com/12665563/69916566-cc93b380-145c-11ea-8535-39e2c43118c4.png)

This is a regression due to the switch to JUCE as the windows plugin backend: https://github.com/falkTX/Carla/commit/7b754358e6ee2a204c7ed24a56d465f3e4a1fdd2

A solution discussed on IRC would be do add a setting to use the native backend instead for VST2/3.

**Comment by terencode** [comment]
There is now `CARLA_DO_NOT_USE_JUCE_FOR_VST2` but the same can't be done for VST3 as it lacks a native implementation for now.

**Comment by falkTX** [comment]
This is an issue with Juce. let's keep the issue open until it is fixed, Juce still has a few issues regarding scaling and size,
I would rather not update Juce stuff for v2.1, so let's review this on a later release

**Comment by terencode** [comment]
FIxed with the new JUCE update.
Is there still a use-case for `CARLA_DO_NOT_USE_JUCE_FOR_VST2` or should it be removed ?

**Comment by falkTX** [comment]
Windows plugins need quite a lot of hacking to get right, so I rather let JUCE handle them.
