### ISSUE TITLE
eq10q plugins fail to load UI

### ISSUE THREAD

**Issue by dr-diem** [falkTX/Carla#978]
Hi,

When I attempt to load any of the eq10q plugins, whilst the rack item loads the cog icon is greyed out and the Log windows shows the error:

`Failed to find UI bridge binary for 'EQ10Q Stereo', cannot use UI`

That error is only thrown in one place in carla's code and seems to be generic to all plugins, however other LV2 plugins do load their UIs, so I am at a loss as to why the eq10q ones do not work. I have tried manually moving the plugin folder from it's default install location (/usr/local/lib/lv2) to where others seem to install (/usr/lib64/lv2) but that did not change the behaviour. I also note that the eq10q plugin folder (sapistaEQv2.lv2) stores ui elements in a subfolder named 'gui' whilst others don't, FWIW.

I have seen mention elsewhere on the net that others have eq10q working via carla, so could you suggest my next troubleshooting step?

Many thanks,

Ian

**Comment by dr-diem** [comment]
Oh and worth mentioning I guess that I installed eq10q in gcc5 'mode' per it's install script question, rather than gcc4.

**Comment by dr-diem** [comment]
Also, the error is thrown regardless of the states of the two Plugin UIs checkboxes in Configure Carla.. Engine.

**Comment by falkTX** [comment]
your build of carla likely does not have gtk2 ui support, so it cannot show eq10q uis.
do you have the binary `carla-bridge-lv2-gtk2` in the carla binary dir?

**Comment by dr-diem** [comment]
Ah-hah! No, I did not have that binary. I am using Gentoo, and the ebuild provides a gtk2 option (USE flag), which tells it to build using GTK2 instead of 3. Rebuilding with that option did result in it including the GTK2 bridge binary, meaning it is now able to load the eq10q UI:

`Will use UI-Bridge for 'EQ10Q Stereo', binary: "/usr/lib/carla/carla-bridge-lv2-gtk2"`

Unfortunately, when I click the now-enabled cog icon on the rack element the UI still does not display, with the following error:
```
Carla assertion failure: "fLibFilename.isNotEmpty()" in file CarlaBridgeFormat.cpp, line 103
Failed to load UI binary, error was:
(null)
```
What does that suggest? Thanks so much for the rapid support!

**Comment by dr-diem** [comment]
Yes! My second issue was a missing dependency for eq10q - I did not have a gtkmm-2 library installed. With that done and eq10q reinstalled carla now displays the eq10q GUI.

Thanks for your help in getting me here!
