### ISSUE TITLE
Patch bay, open UI by double click 

### ISSUE THREAD

**Issue by davidhealey** [falkTX/Carla#986]
Has this functionality been removed or did I need to enable something specific when building? I also don't see an edit or custom UI option in the context menu.

**Comment by falkTX** [comment]
There are 2 things:
1. the develop branch in jack multi-client mode requires jack v1.9.13 (meta-data)
2. the patchbay mode is broken atm, my bad, will fix them after finishing the current cv-related work

**Comment by davidhealey** [comment]
Hi,

Good to know I hadn't messed something up.

Thanks for the quick response. :)
