### ISSUE TITLE
Unable to load some plugins (Windows 32bit plugins on Linux)

### ISSUE THREAD

**Issue by RedactedCode** [falkTX/Carla#993]
Linux 64-bit (Puppy Linux - Ubuntu Bionic compatible).
Wine 3-15.
32-bit compatibility libraries loaded.
____________________________________

Carla:
LRDF Support not available (LADSPA-RDF will be disabled)
Using Carla version 2.0.95 (2.1-beta1)
  Python version: 3.8.1
  Qt version:     5.14.0
  PyQt version:   5.14.1
  Binary dir:     /usr/local/lib/carla
  Resources dir:  /usr/local/share/carla/resources
_________________________________________________

"make features" output:
```---> Main features 
Front-End:     YES
LV2 plugin:    YES
VST plugin:    YES
Link support:  YES
OSC support:   YES
Binary detect: YES

---> Engine drivers 
JACK:        YES
ALSA:        YES
PulseAudio:  YES
CoreAudio:   NO  [MacOS only]
ASIO:        NO  [Windows only]
DirectSound: NO  [Windows only]
WASAPI:      NO  [Windows only]

---> Plugin formats: 
Internal: YES
LADSPA:   YES
DSSI:     YES
LV2:      YES
VST:      YES (with UI)

---> LV2 UI toolkit support: 
External: YES (direct)
Gtk2:     YES (bridge)
Gtk3:     YES (bridge)
Qt4:      YES (bridge)
Qt5:      YES (bridge)
X11:      YES (direct+bridge)
Cocoa:    NO  [MacOS only]
Windows:  NO  [Windows only]

---> File formats: 
Basic: YES
Extra: YES
SF2/3: YES
SFZ:   YES

---> Internal plugins: 
Basic Plugins:    YES
Carla-Patchbay:   YES
Carla-Rack:       YES
External Plugins: NO
```
Carla has apparently built and installed OK.
Can load Carla as instrument plugins in LMMS OK.
Can run Carla standalone OK.

Rack/Add Plugin/ --> select (eg) ninjas2

log output:
```
======= Starting engine =======
======= Engine started ========
Carla engine started, details:
  Driver name:  JACK
  Sample rate:  48000
  Process mode: Multi client
qt.svg: <input>:7064: Could not resolve property: #radialGradient3709
Error opening file /root/lmms/plugins/vst/arcDev Dubb Box/manifest.ttl (No such file or directory)
Starting plugin bridge, command is:
/usr/local/lib/carla/carla-bridge-native "LV2" "ninjas2.lv2" "https://github.com/rghvdberg/ninjas2" 0
Error opening file /root/lmms/plugins/vst/arcDev Dubb Box/manifest.ttl (No such file or directory)
Plugin failed to load, error was:
/root/lmms/plugins/vst/ninjas2.lv2/ninjas2.dll: invalid ELF header
```

Both of these plugins (arcDev Dubb Box & ninjas2) load OK and can be used within LMMS without using Carla.

Maybe I don't understand how to configure Carla correctly?

**Comment by falkTX** [comment]
You are putting lv2 plugins (ninjas.lv2) in your vst plugin folder. this will not go well.
LV2 does not have a way to handle multi-architecture binaries, they need to match the system/host. not a problem in Carla, but just how things work for LV2

**Comment by RedactedCode** [comment]
sh!t i'm an idiot
