### ISSUE TITLE
carla hangs when using nekobi with usb controller

### ISSUE THREAD

**Issue by muziker** [falkTX/Carla#999]
I use a usb keyboard controller running through a2jmidid. It is routed into a dpf nekobi plugin. When i press the octave change button on the controller, nekobi hangs, while carla is still responsive. However i cannot remove the plugin. Once i try, all of carla hangs and has to be killed from the terminal. 

On the other hand, when i do the same thing but in ardour. Ardour handles the octave change fine. At first i thought the controller was supposed to do the midi note calculations, but now i think it is a problem with the host application.

**Comment by falkTX** [comment]
What MIDI bytes does the controller send on such cases, are you able to find out?

**Comment by muziker** [comment]
The problem seems to have resolved itself. I redid parts of my pure data patch. Ran a2jmidid -e for exported hardware, and was running gmidimonitor to check the midi output. Though gmidimonitor seems to only display midi note outputs. 

I'll repost if anything different happens

**Comment by muziker** [comment]
Interestingly the minute i closed gmidimonitor, carla crashed

**Comment by muziker** [comment]
About 3 hours of running through this setup, it has crashed

**Comment by muziker** [comment]
Running through my arps and into carla into yoshimi. 2 hours later of continuous use, carla crashed

**Comment by falkTX** [comment]
can you define what this continuous use involve please?

**Comment by falkTX** [comment]
I had similar issues before, with carla crashing with just running a big project.
Was fixed a couple commits ago, so I believe it will fix this too.
The ticket was about nekobi anyway, which seems to be solved, so I will close this ticket.
